package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Fpxxfq1a5xwwqqhxxxxxitem generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "item")
public class Fpxxfq1a5xwwqqhxxxxxitem implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem;
	private Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation;
	private String a0xxukixbxxxxxxxxxxxmatcode;
	private BigDecimal b0xxziqxlvxxsaxxxxxxquantity;
	private String b1xxuszsbvxxxxxxxxxxdescript;
	private Date z2xxcsxrlxxxxxxxxxxxdateadded;
	private String b3xxuxxrbvxxxxxxxxxxsource1;
	private String y1xxuxxrbvxxxxxxxxxxsource2;
	private String b5fbuxxrbvxxxxxxxxxxupccode;
	private BigDecimal b6fbzicxbvxxxxxxxxxxcost;
	private BigDecimal b7fbzxxxbvxxxxxxxxxxreplcost;
	private BigDecimal b8fbzpxxbvxxxxxxxxxxselprice;
	private BigDecimal b9xxzxxxlvxxxxxxxxxxspricold;
	private BigDecimal c1xxzxxxbhxxsxxxxxxxspricnew;
	private Date c2fbcxxrehxxsxxxxxxxspriceffdt;
	private String c3fbuxscbvxxxxxxxxxxshipcode;
	private Integer z2xxzzprhvxxxxxxxxxxprintmstat;
	private Date z3xxczqxlhxxxxxxxxxxprinmtfldt;
	private String y2xxuxxrbvxxxxxxxxxxmisccode1;
	private String y3xxuxxrbvxxxxxxxxxxmisccode2;
	private BigDecimal c4fbzxxxbvxxxxxxxxxxqtylevel1;
	private String c5fbuuxrbv18xxxxxxxxunit;
	private BigDecimal y4xxuxxrbvxxxxxxxxxxcaseqty;
	private String c6xxusxrbv16xxxxxxxxtype;
	private Boolean c7fbfxz1bvxxxxxxxxxxtax1;
	private Boolean c8fbfxz2bvxxxxxxxxxxtax2;
	private Boolean y6fbfxz3bvxxxxxxxxxxtax3;
	private String f1xxuxxrbvxxxxxxxxxxaliascode;
	private BigDecimal f3xxzxxxlvxxxxxxxxxxavgprice;
	private BigDecimal z4xxzxxxlvxxxxxxxxxxavgcost;
	private Integer z5xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z6xxcztxlxxxxxxxxxxxstatusfldt;
	private String g2xxuxn1bvxxxxxxxxxxsubcodesn;
	private String g2xxuxn2bvxxxxxxxxxxsubcodesn2;
	private String g2xxuxn3bvxxxxxxxxxxsubcodesn3;
	private BigDecimal z7xxzxxxlvxxxxxxxxxxcuordqty;
	private BigDecimal z8xxzxxxlvxxxxxxxxxxvenorqty;
	private BigDecimal z9xxzxxxlvxxxxxxxxxxcupicqty;
	private BigDecimal zaxxzxxxlvxxxxxxxxxxvenpiqty;
	private BigDecimal zbxxzxxxlvxxxxxxxxxxcuinvqty;
	private BigDecimal zcxxzxxxlvxxxxxxxxxxcushiqty;
	private BigDecimal zdxxzxxxlvxxxxxxxxxxvenshqty;
	private Date h1xxcxxrbxxxxxxxxxxxeffdate;
	private String h2xxuwmrbv40xxxxxxxxintegrset;
	private String w7xxuznxbvxxxxxxxxxxnotes;
	private String w8xxuzdrbvxxxxxxxxxxdocmnt;
	private String zexxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String zxxrbvxxxvxxxxxxxxxxbarupc;
	private Date z2xxcxxrlxxxxxxxxxxxdateexpiry;
	private Date y5xxcxxrlxxxxxxxxxxxdatetorenew;
	private Set<Xoxxuq454xwwqqhxxxxxemplodetails> xoxxuq454xwwqqhxxxxxemplodetailses = new HashSet<Xoxxuq454xwwqqhxxxxxemplodetails>(
			0);
	private Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> xoxxuq2a4xwwqqhxxxxxcuidetailses = new HashSet<Xoxxuq2a4xwwqqhxxxxxcuidetails>(
			0);
	private Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> xoxxuq2b4xwwqqhxxxxxcuodetailses = new HashSet<Xoxxuq2b4xwwqqhxxxxxcuodetails>(
			0);
	private Set<Fxxxuq1bhxwwqqhxxxxxusagebyperiods> fxxxuq1bhxwwqqhxxxxxusagebyperiodses = new HashSet<Fxxxuq1bhxwwqqhxxxxxusagebyperiods>(
			0);
	private Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices = new HashSet<Trexuq3a6xwwqqhxxxxxvinvoice>(
			0);
	private Set<Fpxxfq1a5xwwqqhxxxxxitem> fpxxfq1a5xwwqqhxxxxxitems = new HashSet<Fpxxfq1a5xwwqqhxxxxxitem>(
			0);
	private Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments = new HashSet<Trxxuq9aaxwwqqhefxxxjobassignment>(
			0);
	private Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses = new HashSet<Jxxxuq54exwwqqhxxxxxgroupmembers>(
			0);
	private Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> xoxxuq3d4xwwqqhxxxxxvendodetailses = new HashSet<Xoxxuq3d4xwwqqhxxxxxvendodetails>(
			0);
	private Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = new HashSet<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails>(
			0);
	private Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses = new HashSet<Trexuq244xwwqqhxxxxxcuorders>(
			0);
	private Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> fxxxuq1hhxwwqqhefxxxitembomdetailses = new HashSet<Fxxxuq1hhxwwqqhefxxxitembomdetails>(
			0);
	private Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses = new HashSet<Trexuq344xwwqqhxxxxxvendorders>(
			0);
	private Set<Dxxxuq92bxwwqqhefxxxitemjob> dxxxuq92bxwwqqhefxxxitemjobs = new HashSet<Dxxxuq92bxwwqqhefxxxitemjob>(
			0);
	private Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> xoxxuq295xwwqqhxxxxxshipmentdetailses = new HashSet<Xoxxuq295xwwqqhxxxxxshipmentdetails>(
			0);
	private Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes = new HashSet<Trexuq233xwwqqhxxxxxcuquote>(
			0);
	private Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplorderses = new HashSet<Trexuq444xwwqqhxxxxxemplorders>(
			0);
	private Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> xxxxuq9ccxwwqqhxxxxxprocessdetailses = new HashSet<Xxxxuq9ccxwwqqhxxxxxprocessdetails>(
			0);
	private Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices = new HashSet<Trexuq266xwwqqhxxxxxcuinvoice>(
			0);
	private Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> xoxxuq3e4xwwqqhxxxxxvendqdetailses = new HashSet<Xoxxuq3e4xwwqqhxxxxxvendqdetails>(
			0);
	private Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens = new HashSet<Trexuq377xwwqqhxxxxxvshipmen>(
			0);
	private Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes = new HashSet<Trexuq333xwwqqhxxxxxvenquote>(
			0);
	private Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> xoxxuq2c4xwwqqhxxxxxcuqdetailses = new HashSet<Xoxxuq2c4xwwqqhxxxxxcuqdetails>(
			0);
	private Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses = new HashSet<Xoxxuq3c4xwwqqhxxxxxvendidetails>(
			0);
	private Set<Xoxxuq399xvwwqqhxxxxvshipmendetails> xoxxuq399xvwwqqhxxxxvshipmendetailses = new HashSet<Xoxxuq399xvwwqqhxxxxvshipmendetails>(
			0);
	private Set<Fpxxfq1t8xwwqqhxxxxxitemprofl> fpxxfq1t8xwwqqhxxxxxitemprofls = new HashSet<Fpxxfq1t8xwwqqhxxxxxitemprofl>(
			0);
	private Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipments = new HashSet<Trexuq255xwwqqhxxxxxshipment>(
			0);

	public Fpxxfq1a5xwwqqhxxxxxitem() {
	}

	public Fpxxfq1a5xwwqqhxxxxxitem(String a0xxukixbxxxxxxxxxxxmatcode) {
		this.a0xxukixbxxxxxxxxxxxmatcode = a0xxukixbxxxxxxxxxxxmatcode;
	}
	public Fpxxfq1a5xwwqqhxxxxxitem(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem,
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation,
			String a0xxukixbxxxxxxxxxxxmatcode,
			BigDecimal b0xxziqxlvxxsaxxxxxxquantity,
			String b1xxuszsbvxxxxxxxxxxdescript,
			Date z2xxcsxrlxxxxxxxxxxxdateadded,
			String b3xxuxxrbvxxxxxxxxxxsource1,
			String y1xxuxxrbvxxxxxxxxxxsource2,
			String b5fbuxxrbvxxxxxxxxxxupccode,
			BigDecimal b6fbzicxbvxxxxxxxxxxcost,
			BigDecimal b7fbzxxxbvxxxxxxxxxxreplcost,
			BigDecimal b8fbzpxxbvxxxxxxxxxxselprice,
			BigDecimal b9xxzxxxlvxxxxxxxxxxspricold,
			BigDecimal c1xxzxxxbhxxsxxxxxxxspricnew,
			Date c2fbcxxrehxxsxxxxxxxspriceffdt,
			String c3fbuxscbvxxxxxxxxxxshipcode,
			Integer z2xxzzprhvxxxxxxxxxxprintmstat,
			Date z3xxczqxlhxxxxxxxxxxprinmtfldt,
			String y2xxuxxrbvxxxxxxxxxxmisccode1,
			String y3xxuxxrbvxxxxxxxxxxmisccode2,
			BigDecimal c4fbzxxxbvxxxxxxxxxxqtylevel1,
			String c5fbuuxrbv18xxxxxxxxunit,
			BigDecimal y4xxuxxrbvxxxxxxxxxxcaseqty,
			String c6xxusxrbv16xxxxxxxxtype,
			Boolean c7fbfxz1bvxxxxxxxxxxtax1,
			Boolean c8fbfxz2bvxxxxxxxxxxtax2,
			Boolean y6fbfxz3bvxxxxxxxxxxtax3,
			String f1xxuxxrbvxxxxxxxxxxaliascode,
			BigDecimal f3xxzxxxlvxxxxxxxxxxavgprice,
			BigDecimal z4xxzxxxlvxxxxxxxxxxavgcost,
			Integer z5xxzzfxhhxxxxxxxxxxstatusfl,
			Date z6xxcztxlxxxxxxxxxxxstatusfldt,
			String g2xxuxn1bvxxxxxxxxxxsubcodesn,
			String g2xxuxn2bvxxxxxxxxxxsubcodesn2,
			String g2xxuxn3bvxxxxxxxxxxsubcodesn3,
			BigDecimal z7xxzxxxlvxxxxxxxxxxcuordqty,
			BigDecimal z8xxzxxxlvxxxxxxxxxxvenorqty,
			BigDecimal z9xxzxxxlvxxxxxxxxxxcupicqty,
			BigDecimal zaxxzxxxlvxxxxxxxxxxvenpiqty,
			BigDecimal zbxxzxxxlvxxxxxxxxxxcuinvqty,
			BigDecimal zcxxzxxxlvxxxxxxxxxxcushiqty,
			BigDecimal zdxxzxxxlvxxxxxxxxxxvenshqty,
			Date h1xxcxxrbxxxxxxxxxxxeffdate,
			String h2xxuwmrbv40xxxxxxxxintegrset,
			String w7xxuznxbvxxxxxxxxxxnotes,
			String w8xxuzdrbvxxxxxxxxxxdocmnt,
			String zexxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String zxxrbvxxxvxxxxxxxxxxbarupc,
			Date z2xxcxxrlxxxxxxxxxxxdateexpiry,
			Date y5xxcxxrlxxxxxxxxxxxdatetorenew,
			Set<Xoxxuq454xwwqqhxxxxxemplodetails> xoxxuq454xwwqqhxxxxxemplodetailses,
			Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> xoxxuq2a4xwwqqhxxxxxcuidetailses,
			Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> xoxxuq2b4xwwqqhxxxxxcuodetailses,
			Set<Fxxxuq1bhxwwqqhxxxxxusagebyperiods> fxxxuq1bhxwwqqhxxxxxusagebyperiodses,
			Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices,
			Set<Fpxxfq1a5xwwqqhxxxxxitem> fpxxfq1a5xwwqqhxxxxxitems,
			Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments,
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses,
			Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> xoxxuq3d4xwwqqhxxxxxvendodetailses,
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses,
			Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses,
			Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> fxxxuq1hhxwwqqhefxxxitembomdetailses,
			Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses,
			Set<Dxxxuq92bxwwqqhefxxxitemjob> dxxxuq92bxwwqqhefxxxitemjobs,
			Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> xoxxuq295xwwqqhxxxxxshipmentdetailses,
			Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes,
			Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplorderses,
			Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> xxxxuq9ccxwwqqhxxxxxprocessdetailses,
			Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices,
			Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> xoxxuq3e4xwwqqhxxxxxvendqdetailses,
			Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens,
			Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes,
			Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> xoxxuq2c4xwwqqhxxxxxcuqdetailses,
			Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses,
			Set<Xoxxuq399xvwwqqhxxxxvshipmendetails> xoxxuq399xvwwqqhxxxxvshipmendetailses,
			Set<Fpxxfq1t8xwwqqhxxxxxitemprofl> fpxxfq1t8xwwqqhxxxxxitemprofls,
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipments) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
		this.a0xxukixbxxxxxxxxxxxmatcode = a0xxukixbxxxxxxxxxxxmatcode;
		this.b0xxziqxlvxxsaxxxxxxquantity = b0xxziqxlvxxsaxxxxxxquantity;
		this.b1xxuszsbvxxxxxxxxxxdescript = b1xxuszsbvxxxxxxxxxxdescript;
		this.z2xxcsxrlxxxxxxxxxxxdateadded = z2xxcsxrlxxxxxxxxxxxdateadded;
		this.b3xxuxxrbvxxxxxxxxxxsource1 = b3xxuxxrbvxxxxxxxxxxsource1;
		this.y1xxuxxrbvxxxxxxxxxxsource2 = y1xxuxxrbvxxxxxxxxxxsource2;
		this.b5fbuxxrbvxxxxxxxxxxupccode = b5fbuxxrbvxxxxxxxxxxupccode;
		this.b6fbzicxbvxxxxxxxxxxcost = b6fbzicxbvxxxxxxxxxxcost;
		this.b7fbzxxxbvxxxxxxxxxxreplcost = b7fbzxxxbvxxxxxxxxxxreplcost;
		this.b8fbzpxxbvxxxxxxxxxxselprice = b8fbzpxxbvxxxxxxxxxxselprice;
		this.b9xxzxxxlvxxxxxxxxxxspricold = b9xxzxxxlvxxxxxxxxxxspricold;
		this.c1xxzxxxbhxxsxxxxxxxspricnew = c1xxzxxxbhxxsxxxxxxxspricnew;
		this.c2fbcxxrehxxsxxxxxxxspriceffdt = c2fbcxxrehxxsxxxxxxxspriceffdt;
		this.c3fbuxscbvxxxxxxxxxxshipcode = c3fbuxscbvxxxxxxxxxxshipcode;
		this.z2xxzzprhvxxxxxxxxxxprintmstat = z2xxzzprhvxxxxxxxxxxprintmstat;
		this.z3xxczqxlhxxxxxxxxxxprinmtfldt = z3xxczqxlhxxxxxxxxxxprinmtfldt;
		this.y2xxuxxrbvxxxxxxxxxxmisccode1 = y2xxuxxrbvxxxxxxxxxxmisccode1;
		this.y3xxuxxrbvxxxxxxxxxxmisccode2 = y3xxuxxrbvxxxxxxxxxxmisccode2;
		this.c4fbzxxxbvxxxxxxxxxxqtylevel1 = c4fbzxxxbvxxxxxxxxxxqtylevel1;
		this.c5fbuuxrbv18xxxxxxxxunit = c5fbuuxrbv18xxxxxxxxunit;
		this.y4xxuxxrbvxxxxxxxxxxcaseqty = y4xxuxxrbvxxxxxxxxxxcaseqty;
		this.c6xxusxrbv16xxxxxxxxtype = c6xxusxrbv16xxxxxxxxtype;
		this.c7fbfxz1bvxxxxxxxxxxtax1 = c7fbfxz1bvxxxxxxxxxxtax1;
		this.c8fbfxz2bvxxxxxxxxxxtax2 = c8fbfxz2bvxxxxxxxxxxtax2;
		this.y6fbfxz3bvxxxxxxxxxxtax3 = y6fbfxz3bvxxxxxxxxxxtax3;
		this.f1xxuxxrbvxxxxxxxxxxaliascode = f1xxuxxrbvxxxxxxxxxxaliascode;
		this.f3xxzxxxlvxxxxxxxxxxavgprice = f3xxzxxxlvxxxxxxxxxxavgprice;
		this.z4xxzxxxlvxxxxxxxxxxavgcost = z4xxzxxxlvxxxxxxxxxxavgcost;
		this.z5xxzzfxhhxxxxxxxxxxstatusfl = z5xxzzfxhhxxxxxxxxxxstatusfl;
		this.z6xxcztxlxxxxxxxxxxxstatusfldt = z6xxcztxlxxxxxxxxxxxstatusfldt;
		this.g2xxuxn1bvxxxxxxxxxxsubcodesn = g2xxuxn1bvxxxxxxxxxxsubcodesn;
		this.g2xxuxn2bvxxxxxxxxxxsubcodesn2 = g2xxuxn2bvxxxxxxxxxxsubcodesn2;
		this.g2xxuxn3bvxxxxxxxxxxsubcodesn3 = g2xxuxn3bvxxxxxxxxxxsubcodesn3;
		this.z7xxzxxxlvxxxxxxxxxxcuordqty = z7xxzxxxlvxxxxxxxxxxcuordqty;
		this.z8xxzxxxlvxxxxxxxxxxvenorqty = z8xxzxxxlvxxxxxxxxxxvenorqty;
		this.z9xxzxxxlvxxxxxxxxxxcupicqty = z9xxzxxxlvxxxxxxxxxxcupicqty;
		this.zaxxzxxxlvxxxxxxxxxxvenpiqty = zaxxzxxxlvxxxxxxxxxxvenpiqty;
		this.zbxxzxxxlvxxxxxxxxxxcuinvqty = zbxxzxxxlvxxxxxxxxxxcuinvqty;
		this.zcxxzxxxlvxxxxxxxxxxcushiqty = zcxxzxxxlvxxxxxxxxxxcushiqty;
		this.zdxxzxxxlvxxxxxxxxxxvenshqty = zdxxzxxxlvxxxxxxxxxxvenshqty;
		this.h1xxcxxrbxxxxxxxxxxxeffdate = h1xxcxxrbxxxxxxxxxxxeffdate;
		this.h2xxuwmrbv40xxxxxxxxintegrset = h2xxuwmrbv40xxxxxxxxintegrset;
		this.w7xxuznxbvxxxxxxxxxxnotes = w7xxuznxbvxxxxxxxxxxnotes;
		this.w8xxuzdrbvxxxxxxxxxxdocmnt = w8xxuzdrbvxxxxxxxxxxdocmnt;
		this.zexxutoxlhxxxxxxxxxxowner = zexxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.zxxrbvxxxvxxxxxxxxxxbarupc = zxxrbvxxxvxxxxxxxxxxbarupc;
		this.z2xxcxxrlxxxxxxxxxxxdateexpiry = z2xxcxxrlxxxxxxxxxxxdateexpiry;
		this.y5xxcxxrlxxxxxxxxxxxdatetorenew = y5xxcxxrlxxxxxxxxxxxdatetorenew;
		this.xoxxuq454xwwqqhxxxxxemplodetailses = xoxxuq454xwwqqhxxxxxemplodetailses;
		this.xoxxuq2a4xwwqqhxxxxxcuidetailses = xoxxuq2a4xwwqqhxxxxxcuidetailses;
		this.xoxxuq2b4xwwqqhxxxxxcuodetailses = xoxxuq2b4xwwqqhxxxxxcuodetailses;
		this.fxxxuq1bhxwwqqhxxxxxusagebyperiodses = fxxxuq1bhxwwqqhxxxxxusagebyperiodses;
		this.trexuq3a6xwwqqhxxxxxvinvoices = trexuq3a6xwwqqhxxxxxvinvoices;
		this.fpxxfq1a5xwwqqhxxxxxitems = fpxxfq1a5xwwqqhxxxxxitems;
		this.trxxuq9aaxwwqqhefxxxjobassignments = trxxuq9aaxwwqqhefxxxjobassignments;
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
		this.xoxxuq3d4xwwqqhxxxxxvendodetailses = xoxxuq3d4xwwqqhxxxxxvendodetailses;
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
		this.trexuq244xwwqqhxxxxxcuorderses = trexuq244xwwqqhxxxxxcuorderses;
		this.fxxxuq1hhxwwqqhefxxxitembomdetailses = fxxxuq1hhxwwqqhefxxxitembomdetailses;
		this.trexuq344xwwqqhxxxxxvendorderses = trexuq344xwwqqhxxxxxvendorderses;
		this.dxxxuq92bxwwqqhefxxxitemjobs = dxxxuq92bxwwqqhefxxxitemjobs;
		this.xoxxuq295xwwqqhxxxxxshipmentdetailses = xoxxuq295xwwqqhxxxxxshipmentdetailses;
		this.trexuq233xwwqqhxxxxxcuquotes = trexuq233xwwqqhxxxxxcuquotes;
		this.trexuq444xwwqqhxxxxxemplorderses = trexuq444xwwqqhxxxxxemplorderses;
		this.xxxxuq9ccxwwqqhxxxxxprocessdetailses = xxxxuq9ccxwwqqhxxxxxprocessdetailses;
		this.trexuq266xwwqqhxxxxxcuinvoices = trexuq266xwwqqhxxxxxcuinvoices;
		this.xoxxuq3e4xwwqqhxxxxxvendqdetailses = xoxxuq3e4xwwqqhxxxxxvendqdetailses;
		this.trexuq377xwwqqhxxxxxvshipmens = trexuq377xwwqqhxxxxxvshipmens;
		this.trexuq333xwwqqhxxxxxvenquotes = trexuq333xwwqqhxxxxxvenquotes;
		this.xoxxuq2c4xwwqqhxxxxxcuqdetailses = xoxxuq2c4xwwqqhxxxxxcuqdetailses;
		this.xoxxuq3c4xwwqqhxxxxxvendidetailses = xoxxuq3c4xwwqqhxxxxxvendidetailses;
		this.xoxxuq399xvwwqqhxxxxvshipmendetailses = xoxxuq399xvwwqqhxxxxvshipmendetailses;
		this.fpxxfq1t8xwwqqhxxxxxitemprofls = fpxxfq1t8xwwqqhxxxxxitemprofls;
		this.trexuq255xwwqqhxxxxxshipments = trexuq255xwwqqhxxxxxshipments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentcode")
	public Fpxxfq1a5xwwqqhxxxxxitem getFpxxfq1a5xwwqqhxxxxxitem() {
		return this.fpxxfq1a5xwwqqhxxxxxitem;
	}

	public void setFpxxfq1a5xwwqqhxxxxxitem(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public Fxxxcq144xwwqqhxxxxxlocation getFxxxcq144xwwqqhxxxxxlocation() {
		return this.fxxxcq144xwwqqhxxxxxlocation;
	}

	public void setFxxxcq144xwwqqhxxxxxlocation(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
	}

	@Column(name = "matcode", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukixbxxxxxxxxxxxmatcode() {
		return this.a0xxukixbxxxxxxxxxxxmatcode;
	}

	public void setA0xxukixbxxxxxxxxxxxmatcode(
			String a0xxukixbxxxxxxxxxxxmatcode) {
		this.a0xxukixbxxxxxxxxxxxmatcode = a0xxukixbxxxxxxxxxxxmatcode;
	}

	@Column(name = "quantity", precision = 14)
	public BigDecimal getB0xxziqxlvxxsaxxxxxxquantity() {
		return this.b0xxziqxlvxxsaxxxxxxquantity;
	}

	public void setB0xxziqxlvxxsaxxxxxxquantity(
			BigDecimal b0xxziqxlvxxsaxxxxxxquantity) {
		this.b0xxziqxlvxxsaxxxxxxquantity = b0xxziqxlvxxsaxxxxxxquantity;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getB1xxuszsbvxxxxxxxxxxdescript() {
		return this.b1xxuszsbvxxxxxxxxxxdescript;
	}

	public void setB1xxuszsbvxxxxxxxxxxdescript(
			String b1xxuszsbvxxxxxxxxxxdescript) {
		this.b1xxuszsbvxxxxxxxxxxdescript = b1xxuszsbvxxxxxxxxxxdescript;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateadded", length = 29)
	public Date getZ2xxcsxrlxxxxxxxxxxxdateadded() {
		return this.z2xxcsxrlxxxxxxxxxxxdateadded;
	}

	public void setZ2xxcsxrlxxxxxxxxxxxdateadded(
			Date z2xxcsxrlxxxxxxxxxxxdateadded) {
		this.z2xxcsxrlxxxxxxxxxxxdateadded = z2xxcsxrlxxxxxxxxxxxdateadded;
	}

	@Column(name = "source1", length = 35)
	@Size(max = 35)
	public String getB3xxuxxrbvxxxxxxxxxxsource1() {
		return this.b3xxuxxrbvxxxxxxxxxxsource1;
	}

	public void setB3xxuxxrbvxxxxxxxxxxsource1(
			String b3xxuxxrbvxxxxxxxxxxsource1) {
		this.b3xxuxxrbvxxxxxxxxxxsource1 = b3xxuxxrbvxxxxxxxxxxsource1;
	}

	@Column(name = "source2", length = 35)
	@Size(max = 35)
	public String getY1xxuxxrbvxxxxxxxxxxsource2() {
		return this.y1xxuxxrbvxxxxxxxxxxsource2;
	}

	public void setY1xxuxxrbvxxxxxxxxxxsource2(
			String y1xxuxxrbvxxxxxxxxxxsource2) {
		this.y1xxuxxrbvxxxxxxxxxxsource2 = y1xxuxxrbvxxxxxxxxxxsource2;
	}

	@Column(name = "upccode", length = 25)
	@Size(max = 25)
	public String getB5fbuxxrbvxxxxxxxxxxupccode() {
		return this.b5fbuxxrbvxxxxxxxxxxupccode;
	}

	public void setB5fbuxxrbvxxxxxxxxxxupccode(
			String b5fbuxxrbvxxxxxxxxxxupccode) {
		this.b5fbuxxrbvxxxxxxxxxxupccode = b5fbuxxrbvxxxxxxxxxxupccode;
	}

	@Column(name = "cost", precision = 14)
	public BigDecimal getB6fbzicxbvxxxxxxxxxxcost() {
		return this.b6fbzicxbvxxxxxxxxxxcost;
	}

	public void setB6fbzicxbvxxxxxxxxxxcost(BigDecimal b6fbzicxbvxxxxxxxxxxcost) {
		this.b6fbzicxbvxxxxxxxxxxcost = b6fbzicxbvxxxxxxxxxxcost;
	}

	@Column(name = "replcost", precision = 14)
	public BigDecimal getB7fbzxxxbvxxxxxxxxxxreplcost() {
		return this.b7fbzxxxbvxxxxxxxxxxreplcost;
	}

	public void setB7fbzxxxbvxxxxxxxxxxreplcost(
			BigDecimal b7fbzxxxbvxxxxxxxxxxreplcost) {
		this.b7fbzxxxbvxxxxxxxxxxreplcost = b7fbzxxxbvxxxxxxxxxxreplcost;
	}

	@Column(name = "selprice", precision = 14)
	public BigDecimal getB8fbzpxxbvxxxxxxxxxxselprice() {
		return this.b8fbzpxxbvxxxxxxxxxxselprice;
	}

	public void setB8fbzpxxbvxxxxxxxxxxselprice(
			BigDecimal b8fbzpxxbvxxxxxxxxxxselprice) {
		this.b8fbzpxxbvxxxxxxxxxxselprice = b8fbzpxxbvxxxxxxxxxxselprice;
	}

	@Column(name = "spricold", precision = 14)
	public BigDecimal getB9xxzxxxlvxxxxxxxxxxspricold() {
		return this.b9xxzxxxlvxxxxxxxxxxspricold;
	}

	public void setB9xxzxxxlvxxxxxxxxxxspricold(
			BigDecimal b9xxzxxxlvxxxxxxxxxxspricold) {
		this.b9xxzxxxlvxxxxxxxxxxspricold = b9xxzxxxlvxxxxxxxxxxspricold;
	}

	@Column(name = "spricnew", precision = 14)
	public BigDecimal getC1xxzxxxbhxxsxxxxxxxspricnew() {
		return this.c1xxzxxxbhxxsxxxxxxxspricnew;
	}

	public void setC1xxzxxxbhxxsxxxxxxxspricnew(
			BigDecimal c1xxzxxxbhxxsxxxxxxxspricnew) {
		this.c1xxzxxxbhxxsxxxxxxxspricnew = c1xxzxxxbhxxsxxxxxxxspricnew;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "spriceffdt", length = 29)
	public Date getC2fbcxxrehxxsxxxxxxxspriceffdt() {
		return this.c2fbcxxrehxxsxxxxxxxspriceffdt;
	}

	public void setC2fbcxxrehxxsxxxxxxxspriceffdt(
			Date c2fbcxxrehxxsxxxxxxxspriceffdt) {
		this.c2fbcxxrehxxsxxxxxxxspriceffdt = c2fbcxxrehxxsxxxxxxxspriceffdt;
	}

	@Column(name = "shipcode", length = 25)
	@Size(max = 25)
	public String getC3fbuxscbvxxxxxxxxxxshipcode() {
		return this.c3fbuxscbvxxxxxxxxxxshipcode;
	}

	public void setC3fbuxscbvxxxxxxxxxxshipcode(
			String c3fbuxscbvxxxxxxxxxxshipcode) {
		this.c3fbuxscbvxxxxxxxxxxshipcode = c3fbuxscbvxxxxxxxxxxshipcode;
	}

	@Column(name = "printmstat")
	public Integer getZ2xxzzprhvxxxxxxxxxxprintmstat() {
		return this.z2xxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZ2xxzzprhvxxxxxxxxxxprintmstat(
			Integer z2xxzzprhvxxxxxxxxxxprintmstat) {
		this.z2xxzzprhvxxxxxxxxxxprintmstat = z2xxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZ3xxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.z3xxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZ3xxczqxlhxxxxxxxxxxprinmtfldt(
			Date z3xxczqxlhxxxxxxxxxxprinmtfldt) {
		this.z3xxczqxlhxxxxxxxxxxprinmtfldt = z3xxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "misccode1", length = 25)
	@Size(max = 25)
	public String getY2xxuxxrbvxxxxxxxxxxmisccode1() {
		return this.y2xxuxxrbvxxxxxxxxxxmisccode1;
	}

	public void setY2xxuxxrbvxxxxxxxxxxmisccode1(
			String y2xxuxxrbvxxxxxxxxxxmisccode1) {
		this.y2xxuxxrbvxxxxxxxxxxmisccode1 = y2xxuxxrbvxxxxxxxxxxmisccode1;
	}

	@Column(name = "misccode2", length = 25)
	@Size(max = 25)
	public String getY3xxuxxrbvxxxxxxxxxxmisccode2() {
		return this.y3xxuxxrbvxxxxxxxxxxmisccode2;
	}

	public void setY3xxuxxrbvxxxxxxxxxxmisccode2(
			String y3xxuxxrbvxxxxxxxxxxmisccode2) {
		this.y3xxuxxrbvxxxxxxxxxxmisccode2 = y3xxuxxrbvxxxxxxxxxxmisccode2;
	}

	@Column(name = "qtylevel1", precision = 14)
	public BigDecimal getC4fbzxxxbvxxxxxxxxxxqtylevel1() {
		return this.c4fbzxxxbvxxxxxxxxxxqtylevel1;
	}

	public void setC4fbzxxxbvxxxxxxxxxxqtylevel1(
			BigDecimal c4fbzxxxbvxxxxxxxxxxqtylevel1) {
		this.c4fbzxxxbvxxxxxxxxxxqtylevel1 = c4fbzxxxbvxxxxxxxxxxqtylevel1;
	}

	@Column(name = "unit", length = 12)
	@Size(max = 12)
	public String getC5fbuuxrbv18xxxxxxxxunit() {
		return this.c5fbuuxrbv18xxxxxxxxunit;
	}

	public void setC5fbuuxrbv18xxxxxxxxunit(String c5fbuuxrbv18xxxxxxxxunit) {
		this.c5fbuuxrbv18xxxxxxxxunit = c5fbuuxrbv18xxxxxxxxunit;
	}

	@Column(name = "caseqty", precision = 14)
	public BigDecimal getY4xxuxxrbvxxxxxxxxxxcaseqty() {
		return this.y4xxuxxrbvxxxxxxxxxxcaseqty;
	}

	public void setY4xxuxxrbvxxxxxxxxxxcaseqty(
			BigDecimal y4xxuxxrbvxxxxxxxxxxcaseqty) {
		this.y4xxuxxrbvxxxxxxxxxxcaseqty = y4xxuxxrbvxxxxxxxxxxcaseqty;
	}

	@Column(name = "type", length = 12)
	@Size(max = 12)
	public String getC6xxusxrbv16xxxxxxxxtype() {
		return this.c6xxusxrbv16xxxxxxxxtype;
	}

	public void setC6xxusxrbv16xxxxxxxxtype(String c6xxusxrbv16xxxxxxxxtype) {
		this.c6xxusxrbv16xxxxxxxxtype = c6xxusxrbv16xxxxxxxxtype;
	}

	@Column(name = "tax1")
	public Boolean getC7fbfxz1bvxxxxxxxxxxtax1() {
		return this.c7fbfxz1bvxxxxxxxxxxtax1;
	}

	public void setC7fbfxz1bvxxxxxxxxxxtax1(Boolean c7fbfxz1bvxxxxxxxxxxtax1) {
		this.c7fbfxz1bvxxxxxxxxxxtax1 = c7fbfxz1bvxxxxxxxxxxtax1;
	}

	@Column(name = "tax2")
	public Boolean getC8fbfxz2bvxxxxxxxxxxtax2() {
		return this.c8fbfxz2bvxxxxxxxxxxtax2;
	}

	public void setC8fbfxz2bvxxxxxxxxxxtax2(Boolean c8fbfxz2bvxxxxxxxxxxtax2) {
		this.c8fbfxz2bvxxxxxxxxxxtax2 = c8fbfxz2bvxxxxxxxxxxtax2;
	}

	@Column(name = "tax3")
	public Boolean getY6fbfxz3bvxxxxxxxxxxtax3() {
		return this.y6fbfxz3bvxxxxxxxxxxtax3;
	}

	public void setY6fbfxz3bvxxxxxxxxxxtax3(Boolean y6fbfxz3bvxxxxxxxxxxtax3) {
		this.y6fbfxz3bvxxxxxxxxxxtax3 = y6fbfxz3bvxxxxxxxxxxtax3;
	}

	@Column(name = "aliascode", length = 25)
	@Size(max = 25)
	public String getF1xxuxxrbvxxxxxxxxxxaliascode() {
		return this.f1xxuxxrbvxxxxxxxxxxaliascode;
	}

	public void setF1xxuxxrbvxxxxxxxxxxaliascode(
			String f1xxuxxrbvxxxxxxxxxxaliascode) {
		this.f1xxuxxrbvxxxxxxxxxxaliascode = f1xxuxxrbvxxxxxxxxxxaliascode;
	}

	@Column(name = "avgprice", precision = 14)
	public BigDecimal getF3xxzxxxlvxxxxxxxxxxavgprice() {
		return this.f3xxzxxxlvxxxxxxxxxxavgprice;
	}

	public void setF3xxzxxxlvxxxxxxxxxxavgprice(
			BigDecimal f3xxzxxxlvxxxxxxxxxxavgprice) {
		this.f3xxzxxxlvxxxxxxxxxxavgprice = f3xxzxxxlvxxxxxxxxxxavgprice;
	}

	@Column(name = "avgcost", precision = 14)
	public BigDecimal getZ4xxzxxxlvxxxxxxxxxxavgcost() {
		return this.z4xxzxxxlvxxxxxxxxxxavgcost;
	}

	public void setZ4xxzxxxlvxxxxxxxxxxavgcost(
			BigDecimal z4xxzxxxlvxxxxxxxxxxavgcost) {
		this.z4xxzxxxlvxxxxxxxxxxavgcost = z4xxzxxxlvxxxxxxxxxxavgcost;
	}

	@Column(name = "statusfl")
	public Integer getZ5xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z5xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ5xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z5xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z5xxzzfxhhxxxxxxxxxxstatusfl = z5xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ6xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z6xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ6xxcztxlxxxxxxxxxxxstatusfldt(
			Date z6xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z6xxcztxlxxxxxxxxxxxstatusfldt = z6xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "subcodesn", length = 35)
	@Size(max = 35)
	public String getG2xxuxn1bvxxxxxxxxxxsubcodesn() {
		return this.g2xxuxn1bvxxxxxxxxxxsubcodesn;
	}

	public void setG2xxuxn1bvxxxxxxxxxxsubcodesn(
			String g2xxuxn1bvxxxxxxxxxxsubcodesn) {
		this.g2xxuxn1bvxxxxxxxxxxsubcodesn = g2xxuxn1bvxxxxxxxxxxsubcodesn;
	}

	@Column(name = "subcodesn2", length = 35)
	@Size(max = 35)
	public String getG2xxuxn2bvxxxxxxxxxxsubcodesn2() {
		return this.g2xxuxn2bvxxxxxxxxxxsubcodesn2;
	}

	public void setG2xxuxn2bvxxxxxxxxxxsubcodesn2(
			String g2xxuxn2bvxxxxxxxxxxsubcodesn2) {
		this.g2xxuxn2bvxxxxxxxxxxsubcodesn2 = g2xxuxn2bvxxxxxxxxxxsubcodesn2;
	}

	@Column(name = "subcodesn3", length = 35)
	@Size(max = 35)
	public String getG2xxuxn3bvxxxxxxxxxxsubcodesn3() {
		return this.g2xxuxn3bvxxxxxxxxxxsubcodesn3;
	}

	public void setG2xxuxn3bvxxxxxxxxxxsubcodesn3(
			String g2xxuxn3bvxxxxxxxxxxsubcodesn3) {
		this.g2xxuxn3bvxxxxxxxxxxsubcodesn3 = g2xxuxn3bvxxxxxxxxxxsubcodesn3;
	}

	@Column(name = "cuordqty", precision = 14)
	public BigDecimal getZ7xxzxxxlvxxxxxxxxxxcuordqty() {
		return this.z7xxzxxxlvxxxxxxxxxxcuordqty;
	}

	public void setZ7xxzxxxlvxxxxxxxxxxcuordqty(
			BigDecimal z7xxzxxxlvxxxxxxxxxxcuordqty) {
		this.z7xxzxxxlvxxxxxxxxxxcuordqty = z7xxzxxxlvxxxxxxxxxxcuordqty;
	}

	@Column(name = "venorqty", precision = 14)
	public BigDecimal getZ8xxzxxxlvxxxxxxxxxxvenorqty() {
		return this.z8xxzxxxlvxxxxxxxxxxvenorqty;
	}

	public void setZ8xxzxxxlvxxxxxxxxxxvenorqty(
			BigDecimal z8xxzxxxlvxxxxxxxxxxvenorqty) {
		this.z8xxzxxxlvxxxxxxxxxxvenorqty = z8xxzxxxlvxxxxxxxxxxvenorqty;
	}

	@Column(name = "cupicqty", precision = 14)
	public BigDecimal getZ9xxzxxxlvxxxxxxxxxxcupicqty() {
		return this.z9xxzxxxlvxxxxxxxxxxcupicqty;
	}

	public void setZ9xxzxxxlvxxxxxxxxxxcupicqty(
			BigDecimal z9xxzxxxlvxxxxxxxxxxcupicqty) {
		this.z9xxzxxxlvxxxxxxxxxxcupicqty = z9xxzxxxlvxxxxxxxxxxcupicqty;
	}

	@Column(name = "venpiqty", precision = 14)
	public BigDecimal getZaxxzxxxlvxxxxxxxxxxvenpiqty() {
		return this.zaxxzxxxlvxxxxxxxxxxvenpiqty;
	}

	public void setZaxxzxxxlvxxxxxxxxxxvenpiqty(
			BigDecimal zaxxzxxxlvxxxxxxxxxxvenpiqty) {
		this.zaxxzxxxlvxxxxxxxxxxvenpiqty = zaxxzxxxlvxxxxxxxxxxvenpiqty;
	}

	@Column(name = "cuinvqty", precision = 14)
	public BigDecimal getZbxxzxxxlvxxxxxxxxxxcuinvqty() {
		return this.zbxxzxxxlvxxxxxxxxxxcuinvqty;
	}

	public void setZbxxzxxxlvxxxxxxxxxxcuinvqty(
			BigDecimal zbxxzxxxlvxxxxxxxxxxcuinvqty) {
		this.zbxxzxxxlvxxxxxxxxxxcuinvqty = zbxxzxxxlvxxxxxxxxxxcuinvqty;
	}

	@Column(name = "cushiqty", precision = 14)
	public BigDecimal getZcxxzxxxlvxxxxxxxxxxcushiqty() {
		return this.zcxxzxxxlvxxxxxxxxxxcushiqty;
	}

	public void setZcxxzxxxlvxxxxxxxxxxcushiqty(
			BigDecimal zcxxzxxxlvxxxxxxxxxxcushiqty) {
		this.zcxxzxxxlvxxxxxxxxxxcushiqty = zcxxzxxxlvxxxxxxxxxxcushiqty;
	}

	@Column(name = "venshqty", precision = 14)
	public BigDecimal getZdxxzxxxlvxxxxxxxxxxvenshqty() {
		return this.zdxxzxxxlvxxxxxxxxxxvenshqty;
	}

	public void setZdxxzxxxlvxxxxxxxxxxvenshqty(
			BigDecimal zdxxzxxxlvxxxxxxxxxxvenshqty) {
		this.zdxxzxxxlvxxxxxxxxxxvenshqty = zdxxzxxxlvxxxxxxxxxxvenshqty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "effdate", length = 29)
	public Date getH1xxcxxrbxxxxxxxxxxxeffdate() {
		return this.h1xxcxxrbxxxxxxxxxxxeffdate;
	}

	public void setH1xxcxxrbxxxxxxxxxxxeffdate(Date h1xxcxxrbxxxxxxxxxxxeffdate) {
		this.h1xxcxxrbxxxxxxxxxxxeffdate = h1xxcxxrbxxxxxxxxxxxeffdate;
	}

	@Column(name = "integrset", length = 20)
	@Size(max = 20)
	public String getH2xxuwmrbv40xxxxxxxxintegrset() {
		return this.h2xxuwmrbv40xxxxxxxxintegrset;
	}

	public void setH2xxuwmrbv40xxxxxxxxintegrset(
			String h2xxuwmrbv40xxxxxxxxintegrset) {
		this.h2xxuwmrbv40xxxxxxxxintegrset = h2xxuwmrbv40xxxxxxxxintegrset;
	}

	@Column(name = "notes", length = 4096000)
	@Size(max = 4096000)
	public String getW7xxuznxbvxxxxxxxxxxnotes() {
		return this.w7xxuznxbvxxxxxxxxxxnotes;
	}

	public void setW7xxuznxbvxxxxxxxxxxnotes(String w7xxuznxbvxxxxxxxxxxnotes) {
		this.w7xxuznxbvxxxxxxxxxxnotes = w7xxuznxbvxxxxxxxxxxnotes;
	}

	@Column(name = "docmnt", length = 90)
	@Size(max = 90)
	public String getW8xxuzdrbvxxxxxxxxxxdocmnt() {
		return this.w8xxuzdrbvxxxxxxxxxxdocmnt;
	}

	public void setW8xxuzdrbvxxxxxxxxxxdocmnt(String w8xxuzdrbvxxxxxxxxxxdocmnt) {
		this.w8xxuzdrbvxxxxxxxxxxdocmnt = w8xxuzdrbvxxxxxxxxxxdocmnt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZexxutoxlhxxxxxxxxxxowner() {
		return this.zexxutoxlhxxxxxxxxxxowner;
	}

	public void setZexxutoxlhxxxxxxxxxxowner(String zexxutoxlhxxxxxxxxxxowner) {
		this.zexxutoxlhxxxxxxxxxxowner = zexxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "barupc", length = 30)
	@Size(max = 30)
	public String getZxxrbvxxxvxxxxxxxxxxbarupc() {
		return this.zxxrbvxxxvxxxxxxxxxxbarupc;
	}

	public void setZxxrbvxxxvxxxxxxxxxxbarupc(String zxxrbvxxxvxxxxxxxxxxbarupc) {
		this.zxxrbvxxxvxxxxxxxxxxbarupc = zxxrbvxxxvxxxxxxxxxxbarupc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateexpiry", length = 29)
	public Date getZ2xxcxxrlxxxxxxxxxxxdateexpiry() {
		return this.z2xxcxxrlxxxxxxxxxxxdateexpiry;
	}

	public void setZ2xxcxxrlxxxxxxxxxxxdateexpiry(
			Date z2xxcxxrlxxxxxxxxxxxdateexpiry) {
		this.z2xxcxxrlxxxxxxxxxxxdateexpiry = z2xxcxxrlxxxxxxxxxxxdateexpiry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetorenew", length = 29)
	public Date getY5xxcxxrlxxxxxxxxxxxdatetorenew() {
		return this.y5xxcxxrlxxxxxxxxxxxdatetorenew;
	}

	public void setY5xxcxxrlxxxxxxxxxxxdatetorenew(
			Date y5xxcxxrlxxxxxxxxxxxdatetorenew) {
		this.y5xxcxxrlxxxxxxxxxxxdatetorenew = y5xxcxxrlxxxxxxxxxxxdatetorenew;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq454xwwqqhxxxxxemplodetails> getXoxxuq454xwwqqhxxxxxemplodetailses() {
		return this.xoxxuq454xwwqqhxxxxxemplodetailses;
	}

	public void setXoxxuq454xwwqqhxxxxxemplodetailses(
			Set<Xoxxuq454xwwqqhxxxxxemplodetails> xoxxuq454xwwqqhxxxxxemplodetailses) {
		this.xoxxuq454xwwqqhxxxxxemplodetailses = xoxxuq454xwwqqhxxxxxemplodetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> getXoxxuq2a4xwwqqhxxxxxcuidetailses() {
		return this.xoxxuq2a4xwwqqhxxxxxcuidetailses;
	}

	public void setXoxxuq2a4xwwqqhxxxxxcuidetailses(
			Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> xoxxuq2a4xwwqqhxxxxxcuidetailses) {
		this.xoxxuq2a4xwwqqhxxxxxcuidetailses = xoxxuq2a4xwwqqhxxxxxcuidetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> getXoxxuq2b4xwwqqhxxxxxcuodetailses() {
		return this.xoxxuq2b4xwwqqhxxxxxcuodetailses;
	}

	public void setXoxxuq2b4xwwqqhxxxxxcuodetailses(
			Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> xoxxuq2b4xwwqqhxxxxxcuodetailses) {
		this.xoxxuq2b4xwwqqhxxxxxcuodetailses = xoxxuq2b4xwwqqhxxxxxcuodetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Fxxxuq1bhxwwqqhxxxxxusagebyperiods> getFxxxuq1bhxwwqqhxxxxxusagebyperiodses() {
		return this.fxxxuq1bhxwwqqhxxxxxusagebyperiodses;
	}

	public void setFxxxuq1bhxwwqqhxxxxxusagebyperiodses(
			Set<Fxxxuq1bhxwwqqhxxxxxusagebyperiods> fxxxuq1bhxwwqqhxxxxxusagebyperiodses) {
		this.fxxxuq1bhxwwqqhxxxxxusagebyperiodses = fxxxuq1bhxwwqqhxxxxxusagebyperiodses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq3a6xwwqqhxxxxxvinvoice> getTrexuq3a6xwwqqhxxxxxvinvoices() {
		return this.trexuq3a6xwwqqhxxxxxvinvoices;
	}

	public void setTrexuq3a6xwwqqhxxxxxvinvoices(
			Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices) {
		this.trexuq3a6xwwqqhxxxxxvinvoices = trexuq3a6xwwqqhxxxxxvinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Fpxxfq1a5xwwqqhxxxxxitem> getFpxxfq1a5xwwqqhxxxxxitems() {
		return this.fpxxfq1a5xwwqqhxxxxxitems;
	}

	public void setFpxxfq1a5xwwqqhxxxxxitems(
			Set<Fpxxfq1a5xwwqqhxxxxxitem> fpxxfq1a5xwwqqhxxxxxitems) {
		this.fpxxfq1a5xwwqqhxxxxxitems = fpxxfq1a5xwwqqhxxxxxitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trxxuq9aaxwwqqhefxxxjobassignment> getTrxxuq9aaxwwqqhefxxxjobassignments() {
		return this.trxxuq9aaxwwqqhefxxxjobassignments;
	}

	public void setTrxxuq9aaxwwqqhefxxxjobassignments(
			Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments) {
		this.trxxuq9aaxwwqqhefxxxjobassignments = trxxuq9aaxwwqqhefxxxjobassignments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Jxxxuq54exwwqqhxxxxxgroupmembers> getJxxxuq54exwwqqhxxxxxgroupmemberses() {
		return this.jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	public void setJxxxuq54exwwqqhxxxxxgroupmemberses(
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses) {
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> getXoxxuq3d4xwwqqhxxxxxvendodetailses() {
		return this.xoxxuq3d4xwwqqhxxxxxvendodetailses;
	}

	public void setXoxxuq3d4xwwqqhxxxxxvendodetailses(
			Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> xoxxuq3d4xwwqqhxxxxxvendodetailses) {
		this.xoxxuq3d4xwwqqhxxxxxvendodetailses = xoxxuq3d4xwwqqhxxxxxvendodetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> getXoxxuq9bfxwwqqhexxxxjobassignmentdetailses() {
		return this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	public void setXoxxuq9bfxwwqqhexxxxjobassignmentdetailses(
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses) {
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq244xwwqqhxxxxxcuorders> getTrexuq244xwwqqhxxxxxcuorderses() {
		return this.trexuq244xwwqqhxxxxxcuorderses;
	}

	public void setTrexuq244xwwqqhxxxxxcuorderses(
			Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses) {
		this.trexuq244xwwqqhxxxxxcuorderses = trexuq244xwwqqhxxxxxcuorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> getFxxxuq1hhxwwqqhefxxxitembomdetailses() {
		return this.fxxxuq1hhxwwqqhefxxxitembomdetailses;
	}

	public void setFxxxuq1hhxwwqqhefxxxitembomdetailses(
			Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> fxxxuq1hhxwwqqhefxxxitembomdetailses) {
		this.fxxxuq1hhxwwqqhefxxxitembomdetailses = fxxxuq1hhxwwqqhefxxxitembomdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq344xwwqqhxxxxxvendorders> getTrexuq344xwwqqhxxxxxvendorderses() {
		return this.trexuq344xwwqqhxxxxxvendorderses;
	}

	public void setTrexuq344xwwqqhxxxxxvendorderses(
			Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses) {
		this.trexuq344xwwqqhxxxxxvendorderses = trexuq344xwwqqhxxxxxvendorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Dxxxuq92bxwwqqhefxxxitemjob> getDxxxuq92bxwwqqhefxxxitemjobs() {
		return this.dxxxuq92bxwwqqhefxxxitemjobs;
	}

	public void setDxxxuq92bxwwqqhefxxxitemjobs(
			Set<Dxxxuq92bxwwqqhefxxxitemjob> dxxxuq92bxwwqqhefxxxitemjobs) {
		this.dxxxuq92bxwwqqhefxxxitemjobs = dxxxuq92bxwwqqhefxxxitemjobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> getXoxxuq295xwwqqhxxxxxshipmentdetailses() {
		return this.xoxxuq295xwwqqhxxxxxshipmentdetailses;
	}

	public void setXoxxuq295xwwqqhxxxxxshipmentdetailses(
			Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> xoxxuq295xwwqqhxxxxxshipmentdetailses) {
		this.xoxxuq295xwwqqhxxxxxshipmentdetailses = xoxxuq295xwwqqhxxxxxshipmentdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq233xwwqqhxxxxxcuquote> getTrexuq233xwwqqhxxxxxcuquotes() {
		return this.trexuq233xwwqqhxxxxxcuquotes;
	}

	public void setTrexuq233xwwqqhxxxxxcuquotes(
			Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes) {
		this.trexuq233xwwqqhxxxxxcuquotes = trexuq233xwwqqhxxxxxcuquotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq444xwwqqhxxxxxemplorders> getTrexuq444xwwqqhxxxxxemplorderses() {
		return this.trexuq444xwwqqhxxxxxemplorderses;
	}

	public void setTrexuq444xwwqqhxxxxxemplorderses(
			Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplorderses) {
		this.trexuq444xwwqqhxxxxxemplorderses = trexuq444xwwqqhxxxxxemplorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> getXxxxuq9ccxwwqqhxxxxxprocessdetailses() {
		return this.xxxxuq9ccxwwqqhxxxxxprocessdetailses;
	}

	public void setXxxxuq9ccxwwqqhxxxxxprocessdetailses(
			Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> xxxxuq9ccxwwqqhxxxxxprocessdetailses) {
		this.xxxxuq9ccxwwqqhxxxxxprocessdetailses = xxxxuq9ccxwwqqhxxxxxprocessdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq266xwwqqhxxxxxcuinvoice> getTrexuq266xwwqqhxxxxxcuinvoices() {
		return this.trexuq266xwwqqhxxxxxcuinvoices;
	}

	public void setTrexuq266xwwqqhxxxxxcuinvoices(
			Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices) {
		this.trexuq266xwwqqhxxxxxcuinvoices = trexuq266xwwqqhxxxxxcuinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> getXoxxuq3e4xwwqqhxxxxxvendqdetailses() {
		return this.xoxxuq3e4xwwqqhxxxxxvendqdetailses;
	}

	public void setXoxxuq3e4xwwqqhxxxxxvendqdetailses(
			Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> xoxxuq3e4xwwqqhxxxxxvendqdetailses) {
		this.xoxxuq3e4xwwqqhxxxxxvendqdetailses = xoxxuq3e4xwwqqhxxxxxvendqdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq377xwwqqhxxxxxvshipmen> getTrexuq377xwwqqhxxxxxvshipmens() {
		return this.trexuq377xwwqqhxxxxxvshipmens;
	}

	public void setTrexuq377xwwqqhxxxxxvshipmens(
			Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens) {
		this.trexuq377xwwqqhxxxxxvshipmens = trexuq377xwwqqhxxxxxvshipmens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq333xwwqqhxxxxxvenquote> getTrexuq333xwwqqhxxxxxvenquotes() {
		return this.trexuq333xwwqqhxxxxxvenquotes;
	}

	public void setTrexuq333xwwqqhxxxxxvenquotes(
			Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes) {
		this.trexuq333xwwqqhxxxxxvenquotes = trexuq333xwwqqhxxxxxvenquotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> getXoxxuq2c4xwwqqhxxxxxcuqdetailses() {
		return this.xoxxuq2c4xwwqqhxxxxxcuqdetailses;
	}

	public void setXoxxuq2c4xwwqqhxxxxxcuqdetailses(
			Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> xoxxuq2c4xwwqqhxxxxxcuqdetailses) {
		this.xoxxuq2c4xwwqqhxxxxxcuqdetailses = xoxxuq2c4xwwqqhxxxxxcuqdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> getXoxxuq3c4xwwqqhxxxxxvendidetailses() {
		return this.xoxxuq3c4xwwqqhxxxxxvendidetailses;
	}

	public void setXoxxuq3c4xwwqqhxxxxxvendidetailses(
			Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses) {
		this.xoxxuq3c4xwwqqhxxxxxvendidetailses = xoxxuq3c4xwwqqhxxxxxvendidetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Xoxxuq399xvwwqqhxxxxvshipmendetails> getXoxxuq399xvwwqqhxxxxvshipmendetailses() {
		return this.xoxxuq399xvwwqqhxxxxvshipmendetailses;
	}

	public void setXoxxuq399xvwwqqhxxxxvshipmendetailses(
			Set<Xoxxuq399xvwwqqhxxxxvshipmendetails> xoxxuq399xvwwqqhxxxxvshipmendetailses) {
		this.xoxxuq399xvwwqqhxxxxvshipmendetailses = xoxxuq399xvwwqqhxxxxvshipmendetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Fpxxfq1t8xwwqqhxxxxxitemprofl> getFpxxfq1t8xwwqqhxxxxxitemprofls() {
		return this.fpxxfq1t8xwwqqhxxxxxitemprofls;
	}

	public void setFpxxfq1t8xwwqqhxxxxxitemprofls(
			Set<Fpxxfq1t8xwwqqhxxxxxitemprofl> fpxxfq1t8xwwqqhxxxxxitemprofls) {
		this.fpxxfq1t8xwwqqhxxxxxitemprofls = fpxxfq1t8xwwqqhxxxxxitemprofls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpxxfq1a5xwwqqhxxxxxitem")
	public Set<Trexuq255xwwqqhxxxxxshipment> getTrexuq255xwwqqhxxxxxshipments() {
		return this.trexuq255xwwqqhxxxxxshipments;
	}

	public void setTrexuq255xwwqqhxxxxxshipments(
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipments) {
		this.trexuq255xwwqqhxxxxxshipments = trexuq255xwwqqhxxxxxshipments;
	}

	// The following is extra code specified in the hbm.xml files

	private BigDecimal tempQuantity = new BigDecimal("1.0");
	@Transient
	public BigDecimal getTempQuantity() {
		return tempQuantity;
	}
	public void setTempQuantity(BigDecimal value) {
		tempQuantity = value;
	}

	private String[] checkedData = {" "};
	@Transient
	public String[] getCheckedData() {
		return checkedData;
	}
	public void setCheckedData(String[] value) {
		checkedData = value;
	}
	private String checkedSize = "S";
	@Transient
	public String getCheckedSize() {
		return checkedSize;
	}
	public void setCheckedSize(String value) {
		checkedSize = value;
	}

	// end of extra code specified in the hbm.xml files

}
