package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Fxxxuq166xwwqqhefmxxitembom generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "itembom")
public class Fxxxuq166xwwqqhefmxxitembom implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private String a0xxukxxbvxxxxxxxxxxbomcode;
	private String b1xxuszsbvxxxxxxxxxxdescript;
	private BigDecimal z1xxziqxlvxxxxxxxxxxquantity;
	private Boolean b2xxfxxxbvxxxxxxxxxxmode;
	private Integer z1xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z2xxcztxlxxxxxxxxxxxstatusfldt;
	private String z3xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> fxxxuq1hhxwwqqhefxxxitembomdetailses = new HashSet<Fxxxuq1hhxwwqqhefxxxitembomdetails>(
			0);

	public Fxxxuq166xwwqqhefmxxitembom() {
	}

	public Fxxxuq166xwwqqhefmxxitembom(String a0xxukxxbvxxxxxxxxxxbomcode) {
		this.a0xxukxxbvxxxxxxxxxxbomcode = a0xxukxxbvxxxxxxxxxxbomcode;
	}
	public Fxxxuq166xwwqqhefmxxitembom(
			String a0xxukxxbvxxxxxxxxxxbomcode,
			String b1xxuszsbvxxxxxxxxxxdescript,
			BigDecimal z1xxziqxlvxxxxxxxxxxquantity,
			Boolean b2xxfxxxbvxxxxxxxxxxmode,
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl,
			Date z2xxcztxlxxxxxxxxxxxstatusfldt,
			String z3xxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> fxxxuq1hhxwwqqhefxxxitembomdetailses) {
		this.a0xxukxxbvxxxxxxxxxxbomcode = a0xxukxxbvxxxxxxxxxxbomcode;
		this.b1xxuszsbvxxxxxxxxxxdescript = b1xxuszsbvxxxxxxxxxxdescript;
		this.z1xxziqxlvxxxxxxxxxxquantity = z1xxziqxlvxxxxxxxxxxquantity;
		this.b2xxfxxxbvxxxxxxxxxxmode = b2xxfxxxbvxxxxxxxxxxmode;
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.fxxxuq1hhxwwqqhefxxxitembomdetailses = fxxxuq1hhxwwqqhefxxxitembomdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@Column(name = "bomcode", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukxxbvxxxxxxxxxxbomcode() {
		return this.a0xxukxxbvxxxxxxxxxxbomcode;
	}

	public void setA0xxukxxbvxxxxxxxxxxbomcode(
			String a0xxukxxbvxxxxxxxxxxbomcode) {
		this.a0xxukxxbvxxxxxxxxxxbomcode = a0xxukxxbvxxxxxxxxxxbomcode;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getB1xxuszsbvxxxxxxxxxxdescript() {
		return this.b1xxuszsbvxxxxxxxxxxdescript;
	}

	public void setB1xxuszsbvxxxxxxxxxxdescript(
			String b1xxuszsbvxxxxxxxxxxdescript) {
		this.b1xxuszsbvxxxxxxxxxxdescript = b1xxuszsbvxxxxxxxxxxdescript;
	}

	@Column(name = "quantity", precision = 14)
	public BigDecimal getZ1xxziqxlvxxxxxxxxxxquantity() {
		return this.z1xxziqxlvxxxxxxxxxxquantity;
	}

	public void setZ1xxziqxlvxxxxxxxxxxquantity(
			BigDecimal z1xxziqxlvxxxxxxxxxxquantity) {
		this.z1xxziqxlvxxxxxxxxxxquantity = z1xxziqxlvxxxxxxxxxxquantity;
	}

	@Column(name = "mode")
	public Boolean getB2xxfxxxbvxxxxxxxxxxmode() {
		return this.b2xxfxxxbvxxxxxxxxxxmode;
	}

	public void setB2xxfxxxbvxxxxxxxxxxmode(Boolean b2xxfxxxbvxxxxxxxxxxmode) {
		this.b2xxfxxxbvxxxxxxxxxxmode = b2xxfxxxbvxxxxxxxxxxmode;
	}

	@Column(name = "statusfl")
	public Integer getZ1xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ1xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ2xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ2xxcztxlxxxxxxxxxxxstatusfldt(
			Date z2xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ3xxutoxlhxxxxxxxxxxowner() {
		return this.z3xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ3xxutoxlhxxxxxxxxxxowner(String z3xxutoxlhxxxxxxxxxxowner) {
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fxxxuq166xwwqqhefmxxitembom")
	public Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> getFxxxuq1hhxwwqqhefxxxitembomdetailses() {
		return this.fxxxuq1hhxwwqqhefxxxitembomdetailses;
	}

	public void setFxxxuq1hhxwwqqhefxxxitembomdetailses(
			Set<Fxxxuq1hhxwwqqhefxxxitembomdetails> fxxxuq1hhxwwqqhefxxxitembomdetailses) {
		this.fxxxuq1hhxwwqqhefxxxitembomdetailses = fxxxuq1hhxwwqqhefxxxitembomdetailses;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
