package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Fxxxuq1ffxwwqqhefxxxserialnumbers generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "serialnumbers")
public class Fxxxuq1ffxwwqqhefxxxserialnumbers implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private String a0xxukxxbvxxxxxxxxxxserialno;
	private String b1xxuxxrbvxxxxxxxxxxmatcode;
	private BigDecimal b2xxcxqrlxxxxxxxxxxxquanrecd;
	private String b3xxuxxrbvxxxxxxxxxxvendor;
	private String b4xxuxxrbvlxxxxxxxxxlocation;
	private String b5xxuxxrbvxxxxxxxxxxrecvrpt;
	private Boolean b6xxfxxxbvxxxxxxxxxxinfl;
	private Boolean b7xxfxxxbvxxxxxxxxxxphy;
	private Date b8xxcxxrlxxxxxxxxxxxdatetin;
	private Date b9xxcxxrlxxxxxxxxxxxdatetout;
	private String c1xxuxxrbvxxxxxxxxxxjobno;
	private Integer z1xxzzprhvxxxxxxxxxxprintmstat;
	private Date z2xxczqxlhxxxxxxxxxxprinmtfldt;
	private String z3xxuxxrbvxxxxxxxxxxpono;
	private Date z4xxcxxrlxxxxxxxxxxxscandatet;
	private BigDecimal c4xxcxqrlxxxxxxxxxxxquanissd;
	private String z5xxuxxrbvxxxxxxxxxxbutt;
	private Integer z6xxzzfxhhxxxxxxxxxxstatusfl;
	private BigDecimal d1xxcxqrlxxxxxxxxxxxquanrejd;
	private String d2xxuxxrbvxxxxxxxxxxcustomer;
	private String y3xxuxxrbvxxxxxxxxxxcpono;
	private String y4xxuxxrbvxxxxxxxxxxcustomej;
	private BigDecimal z7xxzcxrlxxxxxxxxxxxorgcost;
	private String z8xxuxxrbvxxxxxxxxxxorgpono;
	private String z9xxuxxrbvxxxxxxxxxxorgjobno;
	private String d3xxuxxrbvxxxxxxxxxxaltserno;
	private BigDecimal d4xxcxxrlxxxxxxxxxxxselprice;
	private BigDecimal d5xxcxqrlxxxxxxxxxxxphysqty;
	private String y6xxuxxrbvxxxxxxxxxxsperson;
	private String y7xxuxxrbvxxxxxxxxxxcartonid;
	private Boolean y8xxfxxxbvxxxxxxxxxxcartonpr;
	private String y9xxuxxrbvxxxxxxxxxxpackcode;
	private String yaxxuxxrbvxxxxxxxxxxtarecode;
	private String ybxxuxxrbvxxxxxxxxxxshipcode;
	private String ycxxuxxrbvxxxxxxxxxxtype;
	private String zaxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String zbxxuxxrbvxxxxxxxxxxbarserial;

	public Fxxxuq1ffxwwqqhefxxxserialnumbers() {
	}

	public Fxxxuq1ffxwwqqhefxxxserialnumbers(String a0xxukxxbvxxxxxxxxxxserialno) {
		this.a0xxukxxbvxxxxxxxxxxserialno = a0xxukxxbvxxxxxxxxxxserialno;
	}
	public Fxxxuq1ffxwwqqhefxxxserialnumbers(
			String a0xxukxxbvxxxxxxxxxxserialno,
			String b1xxuxxrbvxxxxxxxxxxmatcode,
			BigDecimal b2xxcxqrlxxxxxxxxxxxquanrecd,
			String b3xxuxxrbvxxxxxxxxxxvendor,
			String b4xxuxxrbvlxxxxxxxxxlocation,
			String b5xxuxxrbvxxxxxxxxxxrecvrpt,
			Boolean b6xxfxxxbvxxxxxxxxxxinfl, Boolean b7xxfxxxbvxxxxxxxxxxphy,
			Date b8xxcxxrlxxxxxxxxxxxdatetin,
			Date b9xxcxxrlxxxxxxxxxxxdatetout,
			String c1xxuxxrbvxxxxxxxxxxjobno,
			Integer z1xxzzprhvxxxxxxxxxxprintmstat,
			Date z2xxczqxlhxxxxxxxxxxprinmtfldt,
			String z3xxuxxrbvxxxxxxxxxxpono,
			Date z4xxcxxrlxxxxxxxxxxxscandatet,
			BigDecimal c4xxcxqrlxxxxxxxxxxxquanissd,
			String z5xxuxxrbvxxxxxxxxxxbutt,
			Integer z6xxzzfxhhxxxxxxxxxxstatusfl,
			BigDecimal d1xxcxqrlxxxxxxxxxxxquanrejd,
			String d2xxuxxrbvxxxxxxxxxxcustomer,
			String y3xxuxxrbvxxxxxxxxxxcpono,
			String y4xxuxxrbvxxxxxxxxxxcustomej,
			BigDecimal z7xxzcxrlxxxxxxxxxxxorgcost,
			String z8xxuxxrbvxxxxxxxxxxorgpono,
			String z9xxuxxrbvxxxxxxxxxxorgjobno,
			String d3xxuxxrbvxxxxxxxxxxaltserno,
			BigDecimal d4xxcxxrlxxxxxxxxxxxselprice,
			BigDecimal d5xxcxqrlxxxxxxxxxxxphysqty,
			String y6xxuxxrbvxxxxxxxxxxsperson,
			String y7xxuxxrbvxxxxxxxxxxcartonid,
			Boolean y8xxfxxxbvxxxxxxxxxxcartonpr,
			String y9xxuxxrbvxxxxxxxxxxpackcode,
			String yaxxuxxrbvxxxxxxxxxxtarecode,
			String ybxxuxxrbvxxxxxxxxxxshipcode,
			String ycxxuxxrbvxxxxxxxxxxtype, String zaxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String zbxxuxxrbvxxxxxxxxxxbarserial) {
		this.a0xxukxxbvxxxxxxxxxxserialno = a0xxukxxbvxxxxxxxxxxserialno;
		this.b1xxuxxrbvxxxxxxxxxxmatcode = b1xxuxxrbvxxxxxxxxxxmatcode;
		this.b2xxcxqrlxxxxxxxxxxxquanrecd = b2xxcxqrlxxxxxxxxxxxquanrecd;
		this.b3xxuxxrbvxxxxxxxxxxvendor = b3xxuxxrbvxxxxxxxxxxvendor;
		this.b4xxuxxrbvlxxxxxxxxxlocation = b4xxuxxrbvlxxxxxxxxxlocation;
		this.b5xxuxxrbvxxxxxxxxxxrecvrpt = b5xxuxxrbvxxxxxxxxxxrecvrpt;
		this.b6xxfxxxbvxxxxxxxxxxinfl = b6xxfxxxbvxxxxxxxxxxinfl;
		this.b7xxfxxxbvxxxxxxxxxxphy = b7xxfxxxbvxxxxxxxxxxphy;
		this.b8xxcxxrlxxxxxxxxxxxdatetin = b8xxcxxrlxxxxxxxxxxxdatetin;
		this.b9xxcxxrlxxxxxxxxxxxdatetout = b9xxcxxrlxxxxxxxxxxxdatetout;
		this.c1xxuxxrbvxxxxxxxxxxjobno = c1xxuxxrbvxxxxxxxxxxjobno;
		this.z1xxzzprhvxxxxxxxxxxprintmstat = z1xxzzprhvxxxxxxxxxxprintmstat;
		this.z2xxczqxlhxxxxxxxxxxprinmtfldt = z2xxczqxlhxxxxxxxxxxprinmtfldt;
		this.z3xxuxxrbvxxxxxxxxxxpono = z3xxuxxrbvxxxxxxxxxxpono;
		this.z4xxcxxrlxxxxxxxxxxxscandatet = z4xxcxxrlxxxxxxxxxxxscandatet;
		this.c4xxcxqrlxxxxxxxxxxxquanissd = c4xxcxqrlxxxxxxxxxxxquanissd;
		this.z5xxuxxrbvxxxxxxxxxxbutt = z5xxuxxrbvxxxxxxxxxxbutt;
		this.z6xxzzfxhhxxxxxxxxxxstatusfl = z6xxzzfxhhxxxxxxxxxxstatusfl;
		this.d1xxcxqrlxxxxxxxxxxxquanrejd = d1xxcxqrlxxxxxxxxxxxquanrejd;
		this.d2xxuxxrbvxxxxxxxxxxcustomer = d2xxuxxrbvxxxxxxxxxxcustomer;
		this.y3xxuxxrbvxxxxxxxxxxcpono = y3xxuxxrbvxxxxxxxxxxcpono;
		this.y4xxuxxrbvxxxxxxxxxxcustomej = y4xxuxxrbvxxxxxxxxxxcustomej;
		this.z7xxzcxrlxxxxxxxxxxxorgcost = z7xxzcxrlxxxxxxxxxxxorgcost;
		this.z8xxuxxrbvxxxxxxxxxxorgpono = z8xxuxxrbvxxxxxxxxxxorgpono;
		this.z9xxuxxrbvxxxxxxxxxxorgjobno = z9xxuxxrbvxxxxxxxxxxorgjobno;
		this.d3xxuxxrbvxxxxxxxxxxaltserno = d3xxuxxrbvxxxxxxxxxxaltserno;
		this.d4xxcxxrlxxxxxxxxxxxselprice = d4xxcxxrlxxxxxxxxxxxselprice;
		this.d5xxcxqrlxxxxxxxxxxxphysqty = d5xxcxqrlxxxxxxxxxxxphysqty;
		this.y6xxuxxrbvxxxxxxxxxxsperson = y6xxuxxrbvxxxxxxxxxxsperson;
		this.y7xxuxxrbvxxxxxxxxxxcartonid = y7xxuxxrbvxxxxxxxxxxcartonid;
		this.y8xxfxxxbvxxxxxxxxxxcartonpr = y8xxfxxxbvxxxxxxxxxxcartonpr;
		this.y9xxuxxrbvxxxxxxxxxxpackcode = y9xxuxxrbvxxxxxxxxxxpackcode;
		this.yaxxuxxrbvxxxxxxxxxxtarecode = yaxxuxxrbvxxxxxxxxxxtarecode;
		this.ybxxuxxrbvxxxxxxxxxxshipcode = ybxxuxxrbvxxxxxxxxxxshipcode;
		this.ycxxuxxrbvxxxxxxxxxxtype = ycxxuxxrbvxxxxxxxxxxtype;
		this.zaxxutoxlhxxxxxxxxxxowner = zaxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.zbxxuxxrbvxxxxxxxxxxbarserial = zbxxuxxrbvxxxxxxxxxxbarserial;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@Column(name = "serialno", nullable = false, length = 25)
	@NotNull
	@Size(max = 25)
	public String getA0xxukxxbvxxxxxxxxxxserialno() {
		return this.a0xxukxxbvxxxxxxxxxxserialno;
	}

	public void setA0xxukxxbvxxxxxxxxxxserialno(
			String a0xxukxxbvxxxxxxxxxxserialno) {
		this.a0xxukxxbvxxxxxxxxxxserialno = a0xxukxxbvxxxxxxxxxxserialno;
	}

	@Column(name = "matcode", length = 32)
	@Size(max = 32)
	public String getB1xxuxxrbvxxxxxxxxxxmatcode() {
		return this.b1xxuxxrbvxxxxxxxxxxmatcode;
	}

	public void setB1xxuxxrbvxxxxxxxxxxmatcode(
			String b1xxuxxrbvxxxxxxxxxxmatcode) {
		this.b1xxuxxrbvxxxxxxxxxxmatcode = b1xxuxxrbvxxxxxxxxxxmatcode;
	}

	@Column(name = "quanrecd", precision = 14)
	public BigDecimal getB2xxcxqrlxxxxxxxxxxxquanrecd() {
		return this.b2xxcxqrlxxxxxxxxxxxquanrecd;
	}

	public void setB2xxcxqrlxxxxxxxxxxxquanrecd(
			BigDecimal b2xxcxqrlxxxxxxxxxxxquanrecd) {
		this.b2xxcxqrlxxxxxxxxxxxquanrecd = b2xxcxqrlxxxxxxxxxxxquanrecd;
	}

	@Column(name = "vendor", length = 20)
	@Size(max = 20)
	public String getB3xxuxxrbvxxxxxxxxxxvendor() {
		return this.b3xxuxxrbvxxxxxxxxxxvendor;
	}

	public void setB3xxuxxrbvxxxxxxxxxxvendor(String b3xxuxxrbvxxxxxxxxxxvendor) {
		this.b3xxuxxrbvxxxxxxxxxxvendor = b3xxuxxrbvxxxxxxxxxxvendor;
	}

	@Column(name = "location", length = 20)
	@Size(max = 20)
	public String getB4xxuxxrbvlxxxxxxxxxlocation() {
		return this.b4xxuxxrbvlxxxxxxxxxlocation;
	}

	public void setB4xxuxxrbvlxxxxxxxxxlocation(
			String b4xxuxxrbvlxxxxxxxxxlocation) {
		this.b4xxuxxrbvlxxxxxxxxxlocation = b4xxuxxrbvlxxxxxxxxxlocation;
	}

	@Column(name = "recvrpt", length = 20)
	@Size(max = 20)
	public String getB5xxuxxrbvxxxxxxxxxxrecvrpt() {
		return this.b5xxuxxrbvxxxxxxxxxxrecvrpt;
	}

	public void setB5xxuxxrbvxxxxxxxxxxrecvrpt(
			String b5xxuxxrbvxxxxxxxxxxrecvrpt) {
		this.b5xxuxxrbvxxxxxxxxxxrecvrpt = b5xxuxxrbvxxxxxxxxxxrecvrpt;
	}

	@Column(name = "infl")
	public Boolean getB6xxfxxxbvxxxxxxxxxxinfl() {
		return this.b6xxfxxxbvxxxxxxxxxxinfl;
	}

	public void setB6xxfxxxbvxxxxxxxxxxinfl(Boolean b6xxfxxxbvxxxxxxxxxxinfl) {
		this.b6xxfxxxbvxxxxxxxxxxinfl = b6xxfxxxbvxxxxxxxxxxinfl;
	}

	@Column(name = "phy")
	public Boolean getB7xxfxxxbvxxxxxxxxxxphy() {
		return this.b7xxfxxxbvxxxxxxxxxxphy;
	}

	public void setB7xxfxxxbvxxxxxxxxxxphy(Boolean b7xxfxxxbvxxxxxxxxxxphy) {
		this.b7xxfxxxbvxxxxxxxxxxphy = b7xxfxxxbvxxxxxxxxxxphy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetin", length = 29)
	public Date getB8xxcxxrlxxxxxxxxxxxdatetin() {
		return this.b8xxcxxrlxxxxxxxxxxxdatetin;
	}

	public void setB8xxcxxrlxxxxxxxxxxxdatetin(Date b8xxcxxrlxxxxxxxxxxxdatetin) {
		this.b8xxcxxrlxxxxxxxxxxxdatetin = b8xxcxxrlxxxxxxxxxxxdatetin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetout", length = 29)
	public Date getB9xxcxxrlxxxxxxxxxxxdatetout() {
		return this.b9xxcxxrlxxxxxxxxxxxdatetout;
	}

	public void setB9xxcxxrlxxxxxxxxxxxdatetout(
			Date b9xxcxxrlxxxxxxxxxxxdatetout) {
		this.b9xxcxxrlxxxxxxxxxxxdatetout = b9xxcxxrlxxxxxxxxxxxdatetout;
	}

	@Column(name = "jobno", length = 20)
	@Size(max = 20)
	public String getC1xxuxxrbvxxxxxxxxxxjobno() {
		return this.c1xxuxxrbvxxxxxxxxxxjobno;
	}

	public void setC1xxuxxrbvxxxxxxxxxxjobno(String c1xxuxxrbvxxxxxxxxxxjobno) {
		this.c1xxuxxrbvxxxxxxxxxxjobno = c1xxuxxrbvxxxxxxxxxxjobno;
	}

	@Column(name = "printmstat")
	public Integer getZ1xxzzprhvxxxxxxxxxxprintmstat() {
		return this.z1xxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZ1xxzzprhvxxxxxxxxxxprintmstat(
			Integer z1xxzzprhvxxxxxxxxxxprintmstat) {
		this.z1xxzzprhvxxxxxxxxxxprintmstat = z1xxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZ2xxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.z2xxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZ2xxczqxlhxxxxxxxxxxprinmtfldt(
			Date z2xxczqxlhxxxxxxxxxxprinmtfldt) {
		this.z2xxczqxlhxxxxxxxxxxprinmtfldt = z2xxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "pono", length = 20)
	@Size(max = 20)
	public String getZ3xxuxxrbvxxxxxxxxxxpono() {
		return this.z3xxuxxrbvxxxxxxxxxxpono;
	}

	public void setZ3xxuxxrbvxxxxxxxxxxpono(String z3xxuxxrbvxxxxxxxxxxpono) {
		this.z3xxuxxrbvxxxxxxxxxxpono = z3xxuxxrbvxxxxxxxxxxpono;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scandatet", length = 29)
	public Date getZ4xxcxxrlxxxxxxxxxxxscandatet() {
		return this.z4xxcxxrlxxxxxxxxxxxscandatet;
	}

	public void setZ4xxcxxrlxxxxxxxxxxxscandatet(
			Date z4xxcxxrlxxxxxxxxxxxscandatet) {
		this.z4xxcxxrlxxxxxxxxxxxscandatet = z4xxcxxrlxxxxxxxxxxxscandatet;
	}

	@Column(name = "quanissd", precision = 14)
	public BigDecimal getC4xxcxqrlxxxxxxxxxxxquanissd() {
		return this.c4xxcxqrlxxxxxxxxxxxquanissd;
	}

	public void setC4xxcxqrlxxxxxxxxxxxquanissd(
			BigDecimal c4xxcxqrlxxxxxxxxxxxquanissd) {
		this.c4xxcxqrlxxxxxxxxxxxquanissd = c4xxcxqrlxxxxxxxxxxxquanissd;
	}

	@Column(name = "butt", length = 20)
	@Size(max = 20)
	public String getZ5xxuxxrbvxxxxxxxxxxbutt() {
		return this.z5xxuxxrbvxxxxxxxxxxbutt;
	}

	public void setZ5xxuxxrbvxxxxxxxxxxbutt(String z5xxuxxrbvxxxxxxxxxxbutt) {
		this.z5xxuxxrbvxxxxxxxxxxbutt = z5xxuxxrbvxxxxxxxxxxbutt;
	}

	@Column(name = "statusfl")
	public Integer getZ6xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z6xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ6xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z6xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z6xxzzfxhhxxxxxxxxxxstatusfl = z6xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Column(name = "quanrejd", precision = 14)
	public BigDecimal getD1xxcxqrlxxxxxxxxxxxquanrejd() {
		return this.d1xxcxqrlxxxxxxxxxxxquanrejd;
	}

	public void setD1xxcxqrlxxxxxxxxxxxquanrejd(
			BigDecimal d1xxcxqrlxxxxxxxxxxxquanrejd) {
		this.d1xxcxqrlxxxxxxxxxxxquanrejd = d1xxcxqrlxxxxxxxxxxxquanrejd;
	}

	@Column(name = "customer", length = 20)
	@Size(max = 20)
	public String getD2xxuxxrbvxxxxxxxxxxcustomer() {
		return this.d2xxuxxrbvxxxxxxxxxxcustomer;
	}

	public void setD2xxuxxrbvxxxxxxxxxxcustomer(
			String d2xxuxxrbvxxxxxxxxxxcustomer) {
		this.d2xxuxxrbvxxxxxxxxxxcustomer = d2xxuxxrbvxxxxxxxxxxcustomer;
	}

	@Column(name = "cpono", length = 20)
	@Size(max = 20)
	public String getY3xxuxxrbvxxxxxxxxxxcpono() {
		return this.y3xxuxxrbvxxxxxxxxxxcpono;
	}

	public void setY3xxuxxrbvxxxxxxxxxxcpono(String y3xxuxxrbvxxxxxxxxxxcpono) {
		this.y3xxuxxrbvxxxxxxxxxxcpono = y3xxuxxrbvxxxxxxxxxxcpono;
	}

	@Column(name = "customej", length = 20)
	@Size(max = 20)
	public String getY4xxuxxrbvxxxxxxxxxxcustomej() {
		return this.y4xxuxxrbvxxxxxxxxxxcustomej;
	}

	public void setY4xxuxxrbvxxxxxxxxxxcustomej(
			String y4xxuxxrbvxxxxxxxxxxcustomej) {
		this.y4xxuxxrbvxxxxxxxxxxcustomej = y4xxuxxrbvxxxxxxxxxxcustomej;
	}

	@Column(name = "orgcost", precision = 14)
	public BigDecimal getZ7xxzcxrlxxxxxxxxxxxorgcost() {
		return this.z7xxzcxrlxxxxxxxxxxxorgcost;
	}

	public void setZ7xxzcxrlxxxxxxxxxxxorgcost(
			BigDecimal z7xxzcxrlxxxxxxxxxxxorgcost) {
		this.z7xxzcxrlxxxxxxxxxxxorgcost = z7xxzcxrlxxxxxxxxxxxorgcost;
	}

	@Column(name = "orgpono", length = 20)
	@Size(max = 20)
	public String getZ8xxuxxrbvxxxxxxxxxxorgpono() {
		return this.z8xxuxxrbvxxxxxxxxxxorgpono;
	}

	public void setZ8xxuxxrbvxxxxxxxxxxorgpono(
			String z8xxuxxrbvxxxxxxxxxxorgpono) {
		this.z8xxuxxrbvxxxxxxxxxxorgpono = z8xxuxxrbvxxxxxxxxxxorgpono;
	}

	@Column(name = "orgjobno", length = 20)
	@Size(max = 20)
	public String getZ9xxuxxrbvxxxxxxxxxxorgjobno() {
		return this.z9xxuxxrbvxxxxxxxxxxorgjobno;
	}

	public void setZ9xxuxxrbvxxxxxxxxxxorgjobno(
			String z9xxuxxrbvxxxxxxxxxxorgjobno) {
		this.z9xxuxxrbvxxxxxxxxxxorgjobno = z9xxuxxrbvxxxxxxxxxxorgjobno;
	}

	@Column(name = "altserno", length = 25)
	@Size(max = 25)
	public String getD3xxuxxrbvxxxxxxxxxxaltserno() {
		return this.d3xxuxxrbvxxxxxxxxxxaltserno;
	}

	public void setD3xxuxxrbvxxxxxxxxxxaltserno(
			String d3xxuxxrbvxxxxxxxxxxaltserno) {
		this.d3xxuxxrbvxxxxxxxxxxaltserno = d3xxuxxrbvxxxxxxxxxxaltserno;
	}

	@Column(name = "selprice", precision = 14)
	public BigDecimal getD4xxcxxrlxxxxxxxxxxxselprice() {
		return this.d4xxcxxrlxxxxxxxxxxxselprice;
	}

	public void setD4xxcxxrlxxxxxxxxxxxselprice(
			BigDecimal d4xxcxxrlxxxxxxxxxxxselprice) {
		this.d4xxcxxrlxxxxxxxxxxxselprice = d4xxcxxrlxxxxxxxxxxxselprice;
	}

	@Column(name = "physqty", precision = 14)
	public BigDecimal getD5xxcxqrlxxxxxxxxxxxphysqty() {
		return this.d5xxcxqrlxxxxxxxxxxxphysqty;
	}

	public void setD5xxcxqrlxxxxxxxxxxxphysqty(
			BigDecimal d5xxcxqrlxxxxxxxxxxxphysqty) {
		this.d5xxcxqrlxxxxxxxxxxxphysqty = d5xxcxqrlxxxxxxxxxxxphysqty;
	}

	@Column(name = "sperson", length = 20)
	@Size(max = 20)
	public String getY6xxuxxrbvxxxxxxxxxxsperson() {
		return this.y6xxuxxrbvxxxxxxxxxxsperson;
	}

	public void setY6xxuxxrbvxxxxxxxxxxsperson(
			String y6xxuxxrbvxxxxxxxxxxsperson) {
		this.y6xxuxxrbvxxxxxxxxxxsperson = y6xxuxxrbvxxxxxxxxxxsperson;
	}

	@Column(name = "cartonid", length = 20)
	@Size(max = 20)
	public String getY7xxuxxrbvxxxxxxxxxxcartonid() {
		return this.y7xxuxxrbvxxxxxxxxxxcartonid;
	}

	public void setY7xxuxxrbvxxxxxxxxxxcartonid(
			String y7xxuxxrbvxxxxxxxxxxcartonid) {
		this.y7xxuxxrbvxxxxxxxxxxcartonid = y7xxuxxrbvxxxxxxxxxxcartonid;
	}

	@Column(name = "cartonpr")
	public Boolean getY8xxfxxxbvxxxxxxxxxxcartonpr() {
		return this.y8xxfxxxbvxxxxxxxxxxcartonpr;
	}

	public void setY8xxfxxxbvxxxxxxxxxxcartonpr(
			Boolean y8xxfxxxbvxxxxxxxxxxcartonpr) {
		this.y8xxfxxxbvxxxxxxxxxxcartonpr = y8xxfxxxbvxxxxxxxxxxcartonpr;
	}

	@Column(name = "packcode", length = 20)
	@Size(max = 20)
	public String getY9xxuxxrbvxxxxxxxxxxpackcode() {
		return this.y9xxuxxrbvxxxxxxxxxxpackcode;
	}

	public void setY9xxuxxrbvxxxxxxxxxxpackcode(
			String y9xxuxxrbvxxxxxxxxxxpackcode) {
		this.y9xxuxxrbvxxxxxxxxxxpackcode = y9xxuxxrbvxxxxxxxxxxpackcode;
	}

	@Column(name = "tarecode", length = 20)
	@Size(max = 20)
	public String getYaxxuxxrbvxxxxxxxxxxtarecode() {
		return this.yaxxuxxrbvxxxxxxxxxxtarecode;
	}

	public void setYaxxuxxrbvxxxxxxxxxxtarecode(
			String yaxxuxxrbvxxxxxxxxxxtarecode) {
		this.yaxxuxxrbvxxxxxxxxxxtarecode = yaxxuxxrbvxxxxxxxxxxtarecode;
	}

	@Column(name = "shipcode", length = 20)
	@Size(max = 20)
	public String getYbxxuxxrbvxxxxxxxxxxshipcode() {
		return this.ybxxuxxrbvxxxxxxxxxxshipcode;
	}

	public void setYbxxuxxrbvxxxxxxxxxxshipcode(
			String ybxxuxxrbvxxxxxxxxxxshipcode) {
		this.ybxxuxxrbvxxxxxxxxxxshipcode = ybxxuxxrbvxxxxxxxxxxshipcode;
	}

	@Column(name = "type", length = 12)
	@Size(max = 12)
	public String getYcxxuxxrbvxxxxxxxxxxtype() {
		return this.ycxxuxxrbvxxxxxxxxxxtype;
	}

	public void setYcxxuxxrbvxxxxxxxxxxtype(String ycxxuxxrbvxxxxxxxxxxtype) {
		this.ycxxuxxrbvxxxxxxxxxxtype = ycxxuxxrbvxxxxxxxxxxtype;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZaxxutoxlhxxxxxxxxxxowner() {
		return this.zaxxutoxlhxxxxxxxxxxowner;
	}

	public void setZaxxutoxlhxxxxxxxxxxowner(String zaxxutoxlhxxxxxxxxxxowner) {
		this.zaxxutoxlhxxxxxxxxxxowner = zaxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "barserial", length = 30)
	@Size(max = 30)
	public String getZbxxuxxrbvxxxxxxxxxxbarserial() {
		return this.zbxxuxxrbvxxxxxxxxxxbarserial;
	}

	public void setZbxxuxxrbvxxxxxxxxxxbarserial(
			String zbxxuxxrbvxxxxxxxxxxbarserial) {
		this.zbxxuxxrbvxxxxxxxxxxbarserial = zbxxuxxrbvxxxxxxxxxxbarserial;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
