package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Fxxxuq8bxxwwqqhxxxxxoutline generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "outline")
public class Fxxxuq8bxxwwqqhxxxxxoutline implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxuq8bxxwwqqhxxxxxoutline fxxxuq8bxxwwqqhxxxxxoutline;
	private int a0xxukxxbvxxxxxxxxxxproj;
	private BigDecimal b2xxzxxrbvxxxxxxxxxxuserow;
	private BigDecimal b3xxzxxrbvxxxxxxxxxxusecol;
	private String z1xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private Set<Fxxxuq8bxxwwqqhxxxxxoutline> fxxxuq8bxxwwqqhxxxxxoutlines = new HashSet<Fxxxuq8bxxwwqqhxxxxxoutline>(
			0);

	public Fxxxuq8bxxwwqqhxxxxxoutline() {
	}

	public Fxxxuq8bxxwwqqhxxxxxoutline(int a0xxukxxbvxxxxxxxxxxproj) {
		this.a0xxukxxbvxxxxxxxxxxproj = a0xxukxxbvxxxxxxxxxxproj;
	}
	public Fxxxuq8bxxwwqqhxxxxxoutline(
			Fxxxuq8bxxwwqqhxxxxxoutline fxxxuq8bxxwwqqhxxxxxoutline,
			int a0xxukxxbvxxxxxxxxxxproj,
			BigDecimal b2xxzxxrbvxxxxxxxxxxuserow,
			BigDecimal b3xxzxxrbvxxxxxxxxxxusecol,
			String z1xxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			Set<Fxxxuq8bxxwwqqhxxxxxoutline> fxxxuq8bxxwwqqhxxxxxoutlines) {
		this.fxxxuq8bxxwwqqhxxxxxoutline = fxxxuq8bxxwwqqhxxxxxoutline;
		this.a0xxukxxbvxxxxxxxxxxproj = a0xxukxxbvxxxxxxxxxxproj;
		this.b2xxzxxrbvxxxxxxxxxxuserow = b2xxzxxrbvxxxxxxxxxxuserow;
		this.b3xxzxxrbvxxxxxxxxxxusecol = b3xxzxxrbvxxxxxxxxxxusecol;
		this.z1xxutoxlhxxxxxxxxxxowner = z1xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.fxxxuq8bxxwwqqhxxxxxoutlines = fxxxuq8bxxwwqqhxxxxxoutlines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentcode")
	public Fxxxuq8bxxwwqqhxxxxxoutline getFxxxuq8bxxwwqqhxxxxxoutline() {
		return this.fxxxuq8bxxwwqqhxxxxxoutline;
	}

	public void setFxxxuq8bxxwwqqhxxxxxoutline(
			Fxxxuq8bxxwwqqhxxxxxoutline fxxxuq8bxxwwqqhxxxxxoutline) {
		this.fxxxuq8bxxwwqqhxxxxxoutline = fxxxuq8bxxwwqqhxxxxxoutline;
	}

	@Column(name = "proj", nullable = false)
	public int getA0xxukxxbvxxxxxxxxxxproj() {
		return this.a0xxukxxbvxxxxxxxxxxproj;
	}

	public void setA0xxukxxbvxxxxxxxxxxproj(int a0xxukxxbvxxxxxxxxxxproj) {
		this.a0xxukxxbvxxxxxxxxxxproj = a0xxukxxbvxxxxxxxxxxproj;
	}

	@Column(name = "userow", precision = 14)
	public BigDecimal getB2xxzxxrbvxxxxxxxxxxuserow() {
		return this.b2xxzxxrbvxxxxxxxxxxuserow;
	}

	public void setB2xxzxxrbvxxxxxxxxxxuserow(
			BigDecimal b2xxzxxrbvxxxxxxxxxxuserow) {
		this.b2xxzxxrbvxxxxxxxxxxuserow = b2xxzxxrbvxxxxxxxxxxuserow;
	}

	@Column(name = "usecol", precision = 14)
	public BigDecimal getB3xxzxxrbvxxxxxxxxxxusecol() {
		return this.b3xxzxxrbvxxxxxxxxxxusecol;
	}

	public void setB3xxzxxrbvxxxxxxxxxxusecol(
			BigDecimal b3xxzxxrbvxxxxxxxxxxusecol) {
		this.b3xxzxxrbvxxxxxxxxxxusecol = b3xxzxxrbvxxxxxxxxxxusecol;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ1xxutoxlhxxxxxxxxxxowner() {
		return this.z1xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ1xxutoxlhxxxxxxxxxxowner(String z1xxutoxlhxxxxxxxxxxowner) {
		this.z1xxutoxlhxxxxxxxxxxowner = z1xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fxxxuq8bxxwwqqhxxxxxoutline")
	public Set<Fxxxuq8bxxwwqqhxxxxxoutline> getFxxxuq8bxxwwqqhxxxxxoutlines() {
		return this.fxxxuq8bxxwwqqhxxxxxoutlines;
	}

	public void setFxxxuq8bxxwwqqhxxxxxoutlines(
			Set<Fxxxuq8bxxwwqqhxxxxxoutline> fxxxuq8bxxwwqqhxxxxxoutlines) {
		this.fxxxuq8bxxwwqqhxxxxxoutlines = fxxxuq8bxxwwqqhxxxxxoutlines;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
