package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Fxxxuq1kkxwwqqhfxxxxtask generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "task")
public class Fxxxuq1kkxwwqqhfxxxxtask implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxuq188xwwqqhxxxxxactivity fxxxuq188xwwqqhxxxxxactivity;
	private Jxxxuq54exwwqqhxxxxxgroupmembers jxxxuq54exwwqqhxxxxxgroupmembers;
	private Fxxxuq1ggxwwqqhxxxxxmembersgroup fxxxuq1ggxwwqqhxxxxxmembersgroup;
	private String a0xxuktpbvxxxxxxxxxxtaskid;
	private String a1xxuszsbvxxxxxxxxxxdescript;
	private Boolean y2xxfxxxbvxxxxxxxxxxmode;
	private Date b1xxcxxrbxxxxxxxxxxxeststart;
	private Date b1xxcxxrlxxxxxxxxxxxcalcstart;
	private Date z1xxcxxrlxxxxxxxxxxxactlstart;
	private Date b2xxcxxrbxxxxxxxxxxxestend;
	private Date z2xxcxxrlxxxxxxxxxxxcalcend;
	private Date z3xxcxxrlxxxxxxxxxxxactlend;
	private BigDecimal b3xxzqxxavxxxxxxxxxxsubqty;
	private Integer y3xxuxxrbvxxxxxxxxxxbomcode;
	private Integer y4xxuxxrbvlxxxxxxxxxlocation;
	private Integer zaxxzzfxhhxxxxxxxxxxstatusfl;
	private Date zbxxcztxlxxxxxxxxxxxstatusfldt;
	private String zcxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private Set<Dxxxuq2drxwwqqhfxxxxresourcedetails> dxxxuq2drxwwqqhfxxxxresourcedetailses = new HashSet<Dxxxuq2drxwwqqhfxxxxresourcedetails>(
			0);

	public Fxxxuq1kkxwwqqhfxxxxtask() {
	}

	public Fxxxuq1kkxwwqqhfxxxxtask(String a0xxuktpbvxxxxxxxxxxtaskid) {
		this.a0xxuktpbvxxxxxxxxxxtaskid = a0xxuktpbvxxxxxxxxxxtaskid;
	}
	public Fxxxuq1kkxwwqqhfxxxxtask(
			Fxxxuq188xwwqqhxxxxxactivity fxxxuq188xwwqqhxxxxxactivity,
			Jxxxuq54exwwqqhxxxxxgroupmembers jxxxuq54exwwqqhxxxxxgroupmembers,
			Fxxxuq1ggxwwqqhxxxxxmembersgroup fxxxuq1ggxwwqqhxxxxxmembersgroup,
			String a0xxuktpbvxxxxxxxxxxtaskid,
			String a1xxuszsbvxxxxxxxxxxdescript,
			Boolean y2xxfxxxbvxxxxxxxxxxmode,
			Date b1xxcxxrbxxxxxxxxxxxeststart,
			Date b1xxcxxrlxxxxxxxxxxxcalcstart,
			Date z1xxcxxrlxxxxxxxxxxxactlstart,
			Date b2xxcxxrbxxxxxxxxxxxestend,
			Date z2xxcxxrlxxxxxxxxxxxcalcend,
			Date z3xxcxxrlxxxxxxxxxxxactlend,
			BigDecimal b3xxzqxxavxxxxxxxxxxsubqty,
			Integer y3xxuxxrbvxxxxxxxxxxbomcode,
			Integer y4xxuxxrbvlxxxxxxxxxlocation,
			Integer zaxxzzfxhhxxxxxxxxxxstatusfl,
			Date zbxxcztxlxxxxxxxxxxxstatusfldt,
			String zcxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			Set<Dxxxuq2drxwwqqhfxxxxresourcedetails> dxxxuq2drxwwqqhfxxxxresourcedetailses) {
		this.fxxxuq188xwwqqhxxxxxactivity = fxxxuq188xwwqqhxxxxxactivity;
		this.jxxxuq54exwwqqhxxxxxgroupmembers = jxxxuq54exwwqqhxxxxxgroupmembers;
		this.fxxxuq1ggxwwqqhxxxxxmembersgroup = fxxxuq1ggxwwqqhxxxxxmembersgroup;
		this.a0xxuktpbvxxxxxxxxxxtaskid = a0xxuktpbvxxxxxxxxxxtaskid;
		this.a1xxuszsbvxxxxxxxxxxdescript = a1xxuszsbvxxxxxxxxxxdescript;
		this.y2xxfxxxbvxxxxxxxxxxmode = y2xxfxxxbvxxxxxxxxxxmode;
		this.b1xxcxxrbxxxxxxxxxxxeststart = b1xxcxxrbxxxxxxxxxxxeststart;
		this.b1xxcxxrlxxxxxxxxxxxcalcstart = b1xxcxxrlxxxxxxxxxxxcalcstart;
		this.z1xxcxxrlxxxxxxxxxxxactlstart = z1xxcxxrlxxxxxxxxxxxactlstart;
		this.b2xxcxxrbxxxxxxxxxxxestend = b2xxcxxrbxxxxxxxxxxxestend;
		this.z2xxcxxrlxxxxxxxxxxxcalcend = z2xxcxxrlxxxxxxxxxxxcalcend;
		this.z3xxcxxrlxxxxxxxxxxxactlend = z3xxcxxrlxxxxxxxxxxxactlend;
		this.b3xxzqxxavxxxxxxxxxxsubqty = b3xxzqxxavxxxxxxxxxxsubqty;
		this.y3xxuxxrbvxxxxxxxxxxbomcode = y3xxuxxrbvxxxxxxxxxxbomcode;
		this.y4xxuxxrbvlxxxxxxxxxlocation = y4xxuxxrbvlxxxxxxxxxlocation;
		this.zaxxzzfxhhxxxxxxxxxxstatusfl = zaxxzzfxhhxxxxxxxxxxstatusfl;
		this.zbxxcztxlxxxxxxxxxxxstatusfldt = zbxxcztxlxxxxxxxxxxxstatusfldt;
		this.zcxxutoxlhxxxxxxxxxxowner = zcxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.dxxxuq2drxwwqqhfxxxxresourcedetailses = dxxxuq2drxwwqqhfxxxxresourcedetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activitycode")
	public Fxxxuq188xwwqqhxxxxxactivity getFxxxuq188xwwqqhxxxxxactivity() {
		return this.fxxxuq188xwwqqhxxxxxactivity;
	}

	public void setFxxxuq188xwwqqhxxxxxactivity(
			Fxxxuq188xwwqqhxxxxxactivity fxxxuq188xwwqqhxxxxxactivity) {
		this.fxxxuq188xwwqqhxxxxxactivity = fxxxuq188xwwqqhxxxxxactivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource")
	public Jxxxuq54exwwqqhxxxxxgroupmembers getJxxxuq54exwwqqhxxxxxgroupmembers() {
		return this.jxxxuq54exwwqqhxxxxxgroupmembers;
	}

	public void setJxxxuq54exwwqqhxxxxxgroupmembers(
			Jxxxuq54exwwqqhxxxxxgroupmembers jxxxuq54exwwqqhxxxxxgroupmembers) {
		this.jxxxuq54exwwqqhxxxxxgroupmembers = jxxxuq54exwwqqhxxxxxgroupmembers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectteam")
	public Fxxxuq1ggxwwqqhxxxxxmembersgroup getFxxxuq1ggxwwqqhxxxxxmembersgroup() {
		return this.fxxxuq1ggxwwqqhxxxxxmembersgroup;
	}

	public void setFxxxuq1ggxwwqqhxxxxxmembersgroup(
			Fxxxuq1ggxwwqqhxxxxxmembersgroup fxxxuq1ggxwwqqhxxxxxmembersgroup) {
		this.fxxxuq1ggxwwqqhxxxxxmembersgroup = fxxxuq1ggxwwqqhxxxxxmembersgroup;
	}

	@Column(name = "taskid", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxuktpbvxxxxxxxxxxtaskid() {
		return this.a0xxuktpbvxxxxxxxxxxtaskid;
	}

	public void setA0xxuktpbvxxxxxxxxxxtaskid(String a0xxuktpbvxxxxxxxxxxtaskid) {
		this.a0xxuktpbvxxxxxxxxxxtaskid = a0xxuktpbvxxxxxxxxxxtaskid;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getA1xxuszsbvxxxxxxxxxxdescript() {
		return this.a1xxuszsbvxxxxxxxxxxdescript;
	}

	public void setA1xxuszsbvxxxxxxxxxxdescript(
			String a1xxuszsbvxxxxxxxxxxdescript) {
		this.a1xxuszsbvxxxxxxxxxxdescript = a1xxuszsbvxxxxxxxxxxdescript;
	}

	@Column(name = "mode")
	public Boolean getY2xxfxxxbvxxxxxxxxxxmode() {
		return this.y2xxfxxxbvxxxxxxxxxxmode;
	}

	public void setY2xxfxxxbvxxxxxxxxxxmode(Boolean y2xxfxxxbvxxxxxxxxxxmode) {
		this.y2xxfxxxbvxxxxxxxxxxmode = y2xxfxxxbvxxxxxxxxxxmode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eststart", length = 29)
	public Date getB1xxcxxrbxxxxxxxxxxxeststart() {
		return this.b1xxcxxrbxxxxxxxxxxxeststart;
	}

	public void setB1xxcxxrbxxxxxxxxxxxeststart(
			Date b1xxcxxrbxxxxxxxxxxxeststart) {
		this.b1xxcxxrbxxxxxxxxxxxeststart = b1xxcxxrbxxxxxxxxxxxeststart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "calcstart", length = 29)
	public Date getB1xxcxxrlxxxxxxxxxxxcalcstart() {
		return this.b1xxcxxrlxxxxxxxxxxxcalcstart;
	}

	public void setB1xxcxxrlxxxxxxxxxxxcalcstart(
			Date b1xxcxxrlxxxxxxxxxxxcalcstart) {
		this.b1xxcxxrlxxxxxxxxxxxcalcstart = b1xxcxxrlxxxxxxxxxxxcalcstart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actlstart", length = 29)
	public Date getZ1xxcxxrlxxxxxxxxxxxactlstart() {
		return this.z1xxcxxrlxxxxxxxxxxxactlstart;
	}

	public void setZ1xxcxxrlxxxxxxxxxxxactlstart(
			Date z1xxcxxrlxxxxxxxxxxxactlstart) {
		this.z1xxcxxrlxxxxxxxxxxxactlstart = z1xxcxxrlxxxxxxxxxxxactlstart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "estend", length = 29)
	public Date getB2xxcxxrbxxxxxxxxxxxestend() {
		return this.b2xxcxxrbxxxxxxxxxxxestend;
	}

	public void setB2xxcxxrbxxxxxxxxxxxestend(Date b2xxcxxrbxxxxxxxxxxxestend) {
		this.b2xxcxxrbxxxxxxxxxxxestend = b2xxcxxrbxxxxxxxxxxxestend;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "calcend", length = 29)
	public Date getZ2xxcxxrlxxxxxxxxxxxcalcend() {
		return this.z2xxcxxrlxxxxxxxxxxxcalcend;
	}

	public void setZ2xxcxxrlxxxxxxxxxxxcalcend(Date z2xxcxxrlxxxxxxxxxxxcalcend) {
		this.z2xxcxxrlxxxxxxxxxxxcalcend = z2xxcxxrlxxxxxxxxxxxcalcend;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actlend", length = 29)
	public Date getZ3xxcxxrlxxxxxxxxxxxactlend() {
		return this.z3xxcxxrlxxxxxxxxxxxactlend;
	}

	public void setZ3xxcxxrlxxxxxxxxxxxactlend(Date z3xxcxxrlxxxxxxxxxxxactlend) {
		this.z3xxcxxrlxxxxxxxxxxxactlend = z3xxcxxrlxxxxxxxxxxxactlend;
	}

	@Column(name = "subqty", precision = 14)
	public BigDecimal getB3xxzqxxavxxxxxxxxxxsubqty() {
		return this.b3xxzqxxavxxxxxxxxxxsubqty;
	}

	public void setB3xxzqxxavxxxxxxxxxxsubqty(
			BigDecimal b3xxzqxxavxxxxxxxxxxsubqty) {
		this.b3xxzqxxavxxxxxxxxxxsubqty = b3xxzqxxavxxxxxxxxxxsubqty;
	}

	@Column(name = "bomcode")
	public Integer getY3xxuxxrbvxxxxxxxxxxbomcode() {
		return this.y3xxuxxrbvxxxxxxxxxxbomcode;
	}

	public void setY3xxuxxrbvxxxxxxxxxxbomcode(
			Integer y3xxuxxrbvxxxxxxxxxxbomcode) {
		this.y3xxuxxrbvxxxxxxxxxxbomcode = y3xxuxxrbvxxxxxxxxxxbomcode;
	}

	@Column(name = "location")
	public Integer getY4xxuxxrbvlxxxxxxxxxlocation() {
		return this.y4xxuxxrbvlxxxxxxxxxlocation;
	}

	public void setY4xxuxxrbvlxxxxxxxxxlocation(
			Integer y4xxuxxrbvlxxxxxxxxxlocation) {
		this.y4xxuxxrbvlxxxxxxxxxlocation = y4xxuxxrbvlxxxxxxxxxlocation;
	}

	@Column(name = "statusfl")
	public Integer getZaxxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zaxxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZaxxzzfxhhxxxxxxxxxxstatusfl(
			Integer zaxxzzfxhhxxxxxxxxxxstatusfl) {
		this.zaxxzzfxhhxxxxxxxxxxstatusfl = zaxxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZbxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zbxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZbxxcztxlxxxxxxxxxxxstatusfldt(
			Date zbxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zbxxcztxlxxxxxxxxxxxstatusfldt = zbxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZcxxutoxlhxxxxxxxxxxowner() {
		return this.zcxxutoxlhxxxxxxxxxxowner;
	}

	public void setZcxxutoxlhxxxxxxxxxxowner(String zcxxutoxlhxxxxxxxxxxowner) {
		this.zcxxutoxlhxxxxxxxxxxowner = zcxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fxxxuq1kkxwwqqhfxxxxtask")
	public Set<Dxxxuq2drxwwqqhfxxxxresourcedetails> getDxxxuq2drxwwqqhfxxxxresourcedetailses() {
		return this.dxxxuq2drxwwqqhfxxxxresourcedetailses;
	}

	public void setDxxxuq2drxwwqqhfxxxxresourcedetailses(
			Set<Dxxxuq2drxwwqqhfxxxxresourcedetails> dxxxuq2drxwwqqhfxxxxresourcedetailses) {
		this.dxxxuq2drxwwqqhfxxxxresourcedetailses = dxxxuq2drxwwqqhfxxxxresourcedetailses;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
