package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Fxxxuq1bhxwwqqhxxxxxusagebyperiods generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "usagebyperiods")
public class Fxxxuq1bhxwwqqhxxxxxusagebyperiods implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem;
	private Jxxxuq53dxwwqqhxxxxxrollupgroup jxxxuq53dxwwqqhxxxxxrollupgroup;
	private String a0xxukupbvxxxxxxxxxxusagetrackerid;
	private String a1xxuszsbxxxxxxxxxxxdescript;
	private String b2xxuxxrbxxxxxxxxxxxcurrency;
	private String d3xxul0rbvxxxxxxxxxxperiod0label;
	private BigDecimal d3xxzb0rbvxxxxxxxxxxperiod0b;
	private BigDecimal d4xxza0rbvxxxxxxxxxxperiod0;
	private String d5xxzc0rbxxxxxxxxxxxperiod0formulae;
	private String e3xxul0rbvxxxxxxxxxxperiodtotalslabel;
	private BigDecimal e3xxzbtrbvxxxxxxxxxxperiodtotalsb;
	private BigDecimal e4xxzatrbvxxxxxxxxxxperiodtotals;
	private String e5xxzctrbxxxxxxxxxxxperiodtotalsformulae;
	private String f3xxul1rbvxxxxxxxxxxperiod1label;
	private BigDecimal f3xxzb1rbvxxxxxxxxxxperiod1budget;
	private BigDecimal f4xxza1rbvxxxxxxxxxxperiod1;
	private String f5xxzc1rbxxxxxxxxxxxperiod1formulae;
	private String g3xxul2rbvxxxxxxxxxxperiod2label;
	private BigDecimal g3xxzb2rbvxxxxxxxxxxperiod2b;
	private BigDecimal g4xxza2rbvxxxxxxxxxxperiod2;
	private String g5xxzc2rbxxxxxxxxxxxperiod2formulae;
	private String h3xxul3rbvxxxxxxxxxxperiod3label;
	private BigDecimal h3xxzb3rbvxxxxxxxxxxperiod3b;
	private BigDecimal h4xxza3rbvxxxxxxxxxxperiod3;
	private String h5xxzc3rbxxxxxxxxxxxperiod3formulae;
	private String i3xxul4rbvxxxxxxxxxxperiod4label;
	private BigDecimal i3xxzb4rbvxxxxxxxxxxperiod4b;
	private BigDecimal i4xxza4rbvxxxxxxxxxxperiod4;
	private String i5xxzc4rbxxxxxxxxxxxperiod4formulae;
	private String j3xxul5rbvxxxxxxxxxxperiod5label;
	private BigDecimal j3xxzb5rbvxxxxxxxxxxperiod5b;
	private BigDecimal j4xxza5rbvxxxxxxxxxxperiod5;
	private String j5xxzc5rbxxxxxxxxxxxperiod5formulae;
	private String k3xxul6rbvxxxxxxxxxxperiod6label;
	private BigDecimal k3xxzb6rbvxxxxxxxxxxperiod6b;
	private BigDecimal k4xxza6rbvxxxxxxxxxxperiod6;
	private String k5xxzc6rbxxxxxxxxxxxperiod6formulae;
	private String l3xxul7rbvxxxxxxxxxxperiod7label;
	private BigDecimal l3xxzb7rbvxxxxxxxxxxperiod7b;
	private BigDecimal l4xxza7rbvxxxxxxxxxxperiod7;
	private String l5xxzc7rbxxxxxxxxxxxperiod7formulae;
	private String m3xxul8rbvxxxxxxxxxxperiod8label;
	private BigDecimal m3xxzb8rbvxxxxxxxxxxperiod8b;
	private BigDecimal m4xxza8rbvxxxxxxxxxxperiod8;
	private String m5xxzc8rbxxxxxxxxxxxperiod8formulae;
	private String n3xxul9rbvxxxxxxxxxxperiod9label;
	private BigDecimal n3xxzb9rbvxxxxxxxxxxperiod9b;
	private BigDecimal n4xxza9rbvxxxxxxxxxxperiod9;
	private String n5xxzc9rbxxxxxxxxxxxperiod9formulae;
	private String o3xxularbvxxxxxxxxxxperiod10label;
	private BigDecimal o3xxzbarbvxxxxxxxxxxperiod10b;
	private BigDecimal o4xxzaarbvxxxxxxxxxxperiod10;
	private String o5xxzcarbxxxxxxxxxxxperiod10formulae;
	private String p3xxulbrbvxxxxxxxxxxperiod11label;
	private BigDecimal p3xxzbbrbvxxxxxxxxxxperiod11b;
	private BigDecimal p4xxzabrbvxxxxxxxxxxperiod11;
	private String p5xxzcbrbxxxxxxxxxxxperiod11formulae;
	private String q3xxulcrbvxxxxxxxxxxperiod12label;
	private BigDecimal q3xxzbcrbvxxxxxxxxxxperiod12b;
	private BigDecimal q4xxzacrbvxxxxxxxxxxperiod12;
	private String q5xxzccrbxxxxxxxxxxxperiod12formulae;
	private String r3xxuldrbvxxxxxxxxxxperiodnlabel;
	private BigDecimal r3xxzbdrbvxxxxxxxxxxperiodnb;
	private BigDecimal r4xxzadrbvxxxxxxxxxxperiodn;
	private String r5xxzxxrbxxxxxxxxxxxperiodnformulae;
	private String y1xxuxznbvxxxxxxxxxxnotes;
	private Integer zixxzzfxhhxxxxxxxxxxstatusfl;
	private Date zjxxcztxlxxxxxxxxxxxstatusfldt;
	private String zjxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Fxxxuq1bhxwwqqhxxxxxusagebyperiods() {
	}

	public Fxxxuq1bhxwwqqhxxxxxusagebyperiods(
			String a0xxukupbvxxxxxxxxxxusagetrackerid) {
		this.a0xxukupbvxxxxxxxxxxusagetrackerid = a0xxukupbvxxxxxxxxxxusagetrackerid;
	}
	public Fxxxuq1bhxwwqqhxxxxxusagebyperiods(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem,
			Jxxxuq53dxwwqqhxxxxxrollupgroup jxxxuq53dxwwqqhxxxxxrollupgroup,
			String a0xxukupbvxxxxxxxxxxusagetrackerid,
			String a1xxuszsbxxxxxxxxxxxdescript,
			String b2xxuxxrbxxxxxxxxxxxcurrency,
			String d3xxul0rbvxxxxxxxxxxperiod0label,
			BigDecimal d3xxzb0rbvxxxxxxxxxxperiod0b,
			BigDecimal d4xxza0rbvxxxxxxxxxxperiod0,
			String d5xxzc0rbxxxxxxxxxxxperiod0formulae,
			String e3xxul0rbvxxxxxxxxxxperiodtotalslabel,
			BigDecimal e3xxzbtrbvxxxxxxxxxxperiodtotalsb,
			BigDecimal e4xxzatrbvxxxxxxxxxxperiodtotals,
			String e5xxzctrbxxxxxxxxxxxperiodtotalsformulae,
			String f3xxul1rbvxxxxxxxxxxperiod1label,
			BigDecimal f3xxzb1rbvxxxxxxxxxxperiod1budget,
			BigDecimal f4xxza1rbvxxxxxxxxxxperiod1,
			String f5xxzc1rbxxxxxxxxxxxperiod1formulae,
			String g3xxul2rbvxxxxxxxxxxperiod2label,
			BigDecimal g3xxzb2rbvxxxxxxxxxxperiod2b,
			BigDecimal g4xxza2rbvxxxxxxxxxxperiod2,
			String g5xxzc2rbxxxxxxxxxxxperiod2formulae,
			String h3xxul3rbvxxxxxxxxxxperiod3label,
			BigDecimal h3xxzb3rbvxxxxxxxxxxperiod3b,
			BigDecimal h4xxza3rbvxxxxxxxxxxperiod3,
			String h5xxzc3rbxxxxxxxxxxxperiod3formulae,
			String i3xxul4rbvxxxxxxxxxxperiod4label,
			BigDecimal i3xxzb4rbvxxxxxxxxxxperiod4b,
			BigDecimal i4xxza4rbvxxxxxxxxxxperiod4,
			String i5xxzc4rbxxxxxxxxxxxperiod4formulae,
			String j3xxul5rbvxxxxxxxxxxperiod5label,
			BigDecimal j3xxzb5rbvxxxxxxxxxxperiod5b,
			BigDecimal j4xxza5rbvxxxxxxxxxxperiod5,
			String j5xxzc5rbxxxxxxxxxxxperiod5formulae,
			String k3xxul6rbvxxxxxxxxxxperiod6label,
			BigDecimal k3xxzb6rbvxxxxxxxxxxperiod6b,
			BigDecimal k4xxza6rbvxxxxxxxxxxperiod6,
			String k5xxzc6rbxxxxxxxxxxxperiod6formulae,
			String l3xxul7rbvxxxxxxxxxxperiod7label,
			BigDecimal l3xxzb7rbvxxxxxxxxxxperiod7b,
			BigDecimal l4xxza7rbvxxxxxxxxxxperiod7,
			String l5xxzc7rbxxxxxxxxxxxperiod7formulae,
			String m3xxul8rbvxxxxxxxxxxperiod8label,
			BigDecimal m3xxzb8rbvxxxxxxxxxxperiod8b,
			BigDecimal m4xxza8rbvxxxxxxxxxxperiod8,
			String m5xxzc8rbxxxxxxxxxxxperiod8formulae,
			String n3xxul9rbvxxxxxxxxxxperiod9label,
			BigDecimal n3xxzb9rbvxxxxxxxxxxperiod9b,
			BigDecimal n4xxza9rbvxxxxxxxxxxperiod9,
			String n5xxzc9rbxxxxxxxxxxxperiod9formulae,
			String o3xxularbvxxxxxxxxxxperiod10label,
			BigDecimal o3xxzbarbvxxxxxxxxxxperiod10b,
			BigDecimal o4xxzaarbvxxxxxxxxxxperiod10,
			String o5xxzcarbxxxxxxxxxxxperiod10formulae,
			String p3xxulbrbvxxxxxxxxxxperiod11label,
			BigDecimal p3xxzbbrbvxxxxxxxxxxperiod11b,
			BigDecimal p4xxzabrbvxxxxxxxxxxperiod11,
			String p5xxzcbrbxxxxxxxxxxxperiod11formulae,
			String q3xxulcrbvxxxxxxxxxxperiod12label,
			BigDecimal q3xxzbcrbvxxxxxxxxxxperiod12b,
			BigDecimal q4xxzacrbvxxxxxxxxxxperiod12,
			String q5xxzccrbxxxxxxxxxxxperiod12formulae,
			String r3xxuldrbvxxxxxxxxxxperiodnlabel,
			BigDecimal r3xxzbdrbvxxxxxxxxxxperiodnb,
			BigDecimal r4xxzadrbvxxxxxxxxxxperiodn,
			String r5xxzxxrbxxxxxxxxxxxperiodnformulae,
			String y1xxuxznbvxxxxxxxxxxnotes,
			Integer zixxzzfxhhxxxxxxxxxxstatusfl,
			Date zjxxcztxlxxxxxxxxxxxstatusfldt,
			String zjxxutoxlhxxxxxxxxxxowner, String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
		this.jxxxuq53dxwwqqhxxxxxrollupgroup = jxxxuq53dxwwqqhxxxxxrollupgroup;
		this.a0xxukupbvxxxxxxxxxxusagetrackerid = a0xxukupbvxxxxxxxxxxusagetrackerid;
		this.a1xxuszsbxxxxxxxxxxxdescript = a1xxuszsbxxxxxxxxxxxdescript;
		this.b2xxuxxrbxxxxxxxxxxxcurrency = b2xxuxxrbxxxxxxxxxxxcurrency;
		this.d3xxul0rbvxxxxxxxxxxperiod0label = d3xxul0rbvxxxxxxxxxxperiod0label;
		this.d3xxzb0rbvxxxxxxxxxxperiod0b = d3xxzb0rbvxxxxxxxxxxperiod0b;
		this.d4xxza0rbvxxxxxxxxxxperiod0 = d4xxza0rbvxxxxxxxxxxperiod0;
		this.d5xxzc0rbxxxxxxxxxxxperiod0formulae = d5xxzc0rbxxxxxxxxxxxperiod0formulae;
		this.e3xxul0rbvxxxxxxxxxxperiodtotalslabel = e3xxul0rbvxxxxxxxxxxperiodtotalslabel;
		this.e3xxzbtrbvxxxxxxxxxxperiodtotalsb = e3xxzbtrbvxxxxxxxxxxperiodtotalsb;
		this.e4xxzatrbvxxxxxxxxxxperiodtotals = e4xxzatrbvxxxxxxxxxxperiodtotals;
		this.e5xxzctrbxxxxxxxxxxxperiodtotalsformulae = e5xxzctrbxxxxxxxxxxxperiodtotalsformulae;
		this.f3xxul1rbvxxxxxxxxxxperiod1label = f3xxul1rbvxxxxxxxxxxperiod1label;
		this.f3xxzb1rbvxxxxxxxxxxperiod1budget = f3xxzb1rbvxxxxxxxxxxperiod1budget;
		this.f4xxza1rbvxxxxxxxxxxperiod1 = f4xxza1rbvxxxxxxxxxxperiod1;
		this.f5xxzc1rbxxxxxxxxxxxperiod1formulae = f5xxzc1rbxxxxxxxxxxxperiod1formulae;
		this.g3xxul2rbvxxxxxxxxxxperiod2label = g3xxul2rbvxxxxxxxxxxperiod2label;
		this.g3xxzb2rbvxxxxxxxxxxperiod2b = g3xxzb2rbvxxxxxxxxxxperiod2b;
		this.g4xxza2rbvxxxxxxxxxxperiod2 = g4xxza2rbvxxxxxxxxxxperiod2;
		this.g5xxzc2rbxxxxxxxxxxxperiod2formulae = g5xxzc2rbxxxxxxxxxxxperiod2formulae;
		this.h3xxul3rbvxxxxxxxxxxperiod3label = h3xxul3rbvxxxxxxxxxxperiod3label;
		this.h3xxzb3rbvxxxxxxxxxxperiod3b = h3xxzb3rbvxxxxxxxxxxperiod3b;
		this.h4xxza3rbvxxxxxxxxxxperiod3 = h4xxza3rbvxxxxxxxxxxperiod3;
		this.h5xxzc3rbxxxxxxxxxxxperiod3formulae = h5xxzc3rbxxxxxxxxxxxperiod3formulae;
		this.i3xxul4rbvxxxxxxxxxxperiod4label = i3xxul4rbvxxxxxxxxxxperiod4label;
		this.i3xxzb4rbvxxxxxxxxxxperiod4b = i3xxzb4rbvxxxxxxxxxxperiod4b;
		this.i4xxza4rbvxxxxxxxxxxperiod4 = i4xxza4rbvxxxxxxxxxxperiod4;
		this.i5xxzc4rbxxxxxxxxxxxperiod4formulae = i5xxzc4rbxxxxxxxxxxxperiod4formulae;
		this.j3xxul5rbvxxxxxxxxxxperiod5label = j3xxul5rbvxxxxxxxxxxperiod5label;
		this.j3xxzb5rbvxxxxxxxxxxperiod5b = j3xxzb5rbvxxxxxxxxxxperiod5b;
		this.j4xxza5rbvxxxxxxxxxxperiod5 = j4xxza5rbvxxxxxxxxxxperiod5;
		this.j5xxzc5rbxxxxxxxxxxxperiod5formulae = j5xxzc5rbxxxxxxxxxxxperiod5formulae;
		this.k3xxul6rbvxxxxxxxxxxperiod6label = k3xxul6rbvxxxxxxxxxxperiod6label;
		this.k3xxzb6rbvxxxxxxxxxxperiod6b = k3xxzb6rbvxxxxxxxxxxperiod6b;
		this.k4xxza6rbvxxxxxxxxxxperiod6 = k4xxza6rbvxxxxxxxxxxperiod6;
		this.k5xxzc6rbxxxxxxxxxxxperiod6formulae = k5xxzc6rbxxxxxxxxxxxperiod6formulae;
		this.l3xxul7rbvxxxxxxxxxxperiod7label = l3xxul7rbvxxxxxxxxxxperiod7label;
		this.l3xxzb7rbvxxxxxxxxxxperiod7b = l3xxzb7rbvxxxxxxxxxxperiod7b;
		this.l4xxza7rbvxxxxxxxxxxperiod7 = l4xxza7rbvxxxxxxxxxxperiod7;
		this.l5xxzc7rbxxxxxxxxxxxperiod7formulae = l5xxzc7rbxxxxxxxxxxxperiod7formulae;
		this.m3xxul8rbvxxxxxxxxxxperiod8label = m3xxul8rbvxxxxxxxxxxperiod8label;
		this.m3xxzb8rbvxxxxxxxxxxperiod8b = m3xxzb8rbvxxxxxxxxxxperiod8b;
		this.m4xxza8rbvxxxxxxxxxxperiod8 = m4xxza8rbvxxxxxxxxxxperiod8;
		this.m5xxzc8rbxxxxxxxxxxxperiod8formulae = m5xxzc8rbxxxxxxxxxxxperiod8formulae;
		this.n3xxul9rbvxxxxxxxxxxperiod9label = n3xxul9rbvxxxxxxxxxxperiod9label;
		this.n3xxzb9rbvxxxxxxxxxxperiod9b = n3xxzb9rbvxxxxxxxxxxperiod9b;
		this.n4xxza9rbvxxxxxxxxxxperiod9 = n4xxza9rbvxxxxxxxxxxperiod9;
		this.n5xxzc9rbxxxxxxxxxxxperiod9formulae = n5xxzc9rbxxxxxxxxxxxperiod9formulae;
		this.o3xxularbvxxxxxxxxxxperiod10label = o3xxularbvxxxxxxxxxxperiod10label;
		this.o3xxzbarbvxxxxxxxxxxperiod10b = o3xxzbarbvxxxxxxxxxxperiod10b;
		this.o4xxzaarbvxxxxxxxxxxperiod10 = o4xxzaarbvxxxxxxxxxxperiod10;
		this.o5xxzcarbxxxxxxxxxxxperiod10formulae = o5xxzcarbxxxxxxxxxxxperiod10formulae;
		this.p3xxulbrbvxxxxxxxxxxperiod11label = p3xxulbrbvxxxxxxxxxxperiod11label;
		this.p3xxzbbrbvxxxxxxxxxxperiod11b = p3xxzbbrbvxxxxxxxxxxperiod11b;
		this.p4xxzabrbvxxxxxxxxxxperiod11 = p4xxzabrbvxxxxxxxxxxperiod11;
		this.p5xxzcbrbxxxxxxxxxxxperiod11formulae = p5xxzcbrbxxxxxxxxxxxperiod11formulae;
		this.q3xxulcrbvxxxxxxxxxxperiod12label = q3xxulcrbvxxxxxxxxxxperiod12label;
		this.q3xxzbcrbvxxxxxxxxxxperiod12b = q3xxzbcrbvxxxxxxxxxxperiod12b;
		this.q4xxzacrbvxxxxxxxxxxperiod12 = q4xxzacrbvxxxxxxxxxxperiod12;
		this.q5xxzccrbxxxxxxxxxxxperiod12formulae = q5xxzccrbxxxxxxxxxxxperiod12formulae;
		this.r3xxuldrbvxxxxxxxxxxperiodnlabel = r3xxuldrbvxxxxxxxxxxperiodnlabel;
		this.r3xxzbdrbvxxxxxxxxxxperiodnb = r3xxzbdrbvxxxxxxxxxxperiodnb;
		this.r4xxzadrbvxxxxxxxxxxperiodn = r4xxzadrbvxxxxxxxxxxperiodn;
		this.r5xxzxxrbxxxxxxxxxxxperiodnformulae = r5xxzxxrbxxxxxxxxxxxperiodnformulae;
		this.y1xxuxznbvxxxxxxxxxxnotes = y1xxuxznbvxxxxxxxxxxnotes;
		this.zixxzzfxhhxxxxxxxxxxstatusfl = zixxzzfxhhxxxxxxxxxxstatusfl;
		this.zjxxcztxlxxxxxxxxxxxstatusfldt = zjxxcztxlxxxxxxxxxxxstatusfldt;
		this.zjxxutoxlhxxxxxxxxxxowner = zjxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matcode")
	public Fpxxfq1a5xwwqqhxxxxxitem getFpxxfq1a5xwwqqhxxxxxitem() {
		return this.fpxxfq1a5xwwqqhxxxxxitem;
	}

	public void setFpxxfq1a5xwwqqhxxxxxitem(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupcode")
	public Jxxxuq53dxwwqqhxxxxxrollupgroup getJxxxuq53dxwwqqhxxxxxrollupgroup() {
		return this.jxxxuq53dxwwqqhxxxxxrollupgroup;
	}

	public void setJxxxuq53dxwwqqhxxxxxrollupgroup(
			Jxxxuq53dxwwqqhxxxxxrollupgroup jxxxuq53dxwwqqhxxxxxrollupgroup) {
		this.jxxxuq53dxwwqqhxxxxxrollupgroup = jxxxuq53dxwwqqhxxxxxrollupgroup;
	}

	@Column(name = "usagetrackerid", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukupbvxxxxxxxxxxusagetrackerid() {
		return this.a0xxukupbvxxxxxxxxxxusagetrackerid;
	}

	public void setA0xxukupbvxxxxxxxxxxusagetrackerid(
			String a0xxukupbvxxxxxxxxxxusagetrackerid) {
		this.a0xxukupbvxxxxxxxxxxusagetrackerid = a0xxukupbvxxxxxxxxxxusagetrackerid;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getA1xxuszsbxxxxxxxxxxxdescript() {
		return this.a1xxuszsbxxxxxxxxxxxdescript;
	}

	public void setA1xxuszsbxxxxxxxxxxxdescript(
			String a1xxuszsbxxxxxxxxxxxdescript) {
		this.a1xxuszsbxxxxxxxxxxxdescript = a1xxuszsbxxxxxxxxxxxdescript;
	}

	@Column(name = "currency", length = 3)
	@Size(max = 3)
	public String getB2xxuxxrbxxxxxxxxxxxcurrency() {
		return this.b2xxuxxrbxxxxxxxxxxxcurrency;
	}

	public void setB2xxuxxrbxxxxxxxxxxxcurrency(
			String b2xxuxxrbxxxxxxxxxxxcurrency) {
		this.b2xxuxxrbxxxxxxxxxxxcurrency = b2xxuxxrbxxxxxxxxxxxcurrency;
	}

	@Column(name = "period0label", length = 20)
	@Size(max = 20)
	public String getD3xxul0rbvxxxxxxxxxxperiod0label() {
		return this.d3xxul0rbvxxxxxxxxxxperiod0label;
	}

	public void setD3xxul0rbvxxxxxxxxxxperiod0label(
			String d3xxul0rbvxxxxxxxxxxperiod0label) {
		this.d3xxul0rbvxxxxxxxxxxperiod0label = d3xxul0rbvxxxxxxxxxxperiod0label;
	}

	@Column(name = "period0b", precision = 14)
	public BigDecimal getD3xxzb0rbvxxxxxxxxxxperiod0b() {
		return this.d3xxzb0rbvxxxxxxxxxxperiod0b;
	}

	public void setD3xxzb0rbvxxxxxxxxxxperiod0b(
			BigDecimal d3xxzb0rbvxxxxxxxxxxperiod0b) {
		this.d3xxzb0rbvxxxxxxxxxxperiod0b = d3xxzb0rbvxxxxxxxxxxperiod0b;
	}

	@Column(name = "period0", precision = 14)
	public BigDecimal getD4xxza0rbvxxxxxxxxxxperiod0() {
		return this.d4xxza0rbvxxxxxxxxxxperiod0;
	}

	public void setD4xxza0rbvxxxxxxxxxxperiod0(
			BigDecimal d4xxza0rbvxxxxxxxxxxperiod0) {
		this.d4xxza0rbvxxxxxxxxxxperiod0 = d4xxza0rbvxxxxxxxxxxperiod0;
	}

	@Column(name = "period0formulae", length = 159)
	@Size(max = 159)
	public String getD5xxzc0rbxxxxxxxxxxxperiod0formulae() {
		return this.d5xxzc0rbxxxxxxxxxxxperiod0formulae;
	}

	public void setD5xxzc0rbxxxxxxxxxxxperiod0formulae(
			String d5xxzc0rbxxxxxxxxxxxperiod0formulae) {
		this.d5xxzc0rbxxxxxxxxxxxperiod0formulae = d5xxzc0rbxxxxxxxxxxxperiod0formulae;
	}

	@Column(name = "periodtotalslabel", length = 20)
	@Size(max = 20)
	public String getE3xxul0rbvxxxxxxxxxxperiodtotalslabel() {
		return this.e3xxul0rbvxxxxxxxxxxperiodtotalslabel;
	}

	public void setE3xxul0rbvxxxxxxxxxxperiodtotalslabel(
			String e3xxul0rbvxxxxxxxxxxperiodtotalslabel) {
		this.e3xxul0rbvxxxxxxxxxxperiodtotalslabel = e3xxul0rbvxxxxxxxxxxperiodtotalslabel;
	}

	@Column(name = "periodtotalsb", precision = 14)
	public BigDecimal getE3xxzbtrbvxxxxxxxxxxperiodtotalsb() {
		return this.e3xxzbtrbvxxxxxxxxxxperiodtotalsb;
	}

	public void setE3xxzbtrbvxxxxxxxxxxperiodtotalsb(
			BigDecimal e3xxzbtrbvxxxxxxxxxxperiodtotalsb) {
		this.e3xxzbtrbvxxxxxxxxxxperiodtotalsb = e3xxzbtrbvxxxxxxxxxxperiodtotalsb;
	}

	@Column(name = "periodtotals", precision = 14)
	public BigDecimal getE4xxzatrbvxxxxxxxxxxperiodtotals() {
		return this.e4xxzatrbvxxxxxxxxxxperiodtotals;
	}

	public void setE4xxzatrbvxxxxxxxxxxperiodtotals(
			BigDecimal e4xxzatrbvxxxxxxxxxxperiodtotals) {
		this.e4xxzatrbvxxxxxxxxxxperiodtotals = e4xxzatrbvxxxxxxxxxxperiodtotals;
	}

	@Column(name = "periodtotalsformulae", length = 159)
	@Size(max = 159)
	public String getE5xxzctrbxxxxxxxxxxxperiodtotalsformulae() {
		return this.e5xxzctrbxxxxxxxxxxxperiodtotalsformulae;
	}

	public void setE5xxzctrbxxxxxxxxxxxperiodtotalsformulae(
			String e5xxzctrbxxxxxxxxxxxperiodtotalsformulae) {
		this.e5xxzctrbxxxxxxxxxxxperiodtotalsformulae = e5xxzctrbxxxxxxxxxxxperiodtotalsformulae;
	}

	@Column(name = "period1label", length = 20)
	@Size(max = 20)
	public String getF3xxul1rbvxxxxxxxxxxperiod1label() {
		return this.f3xxul1rbvxxxxxxxxxxperiod1label;
	}

	public void setF3xxul1rbvxxxxxxxxxxperiod1label(
			String f3xxul1rbvxxxxxxxxxxperiod1label) {
		this.f3xxul1rbvxxxxxxxxxxperiod1label = f3xxul1rbvxxxxxxxxxxperiod1label;
	}

	@Column(name = "period1budget", precision = 14)
	public BigDecimal getF3xxzb1rbvxxxxxxxxxxperiod1budget() {
		return this.f3xxzb1rbvxxxxxxxxxxperiod1budget;
	}

	public void setF3xxzb1rbvxxxxxxxxxxperiod1budget(
			BigDecimal f3xxzb1rbvxxxxxxxxxxperiod1budget) {
		this.f3xxzb1rbvxxxxxxxxxxperiod1budget = f3xxzb1rbvxxxxxxxxxxperiod1budget;
	}

	@Column(name = "period1", precision = 14)
	public BigDecimal getF4xxza1rbvxxxxxxxxxxperiod1() {
		return this.f4xxza1rbvxxxxxxxxxxperiod1;
	}

	public void setF4xxza1rbvxxxxxxxxxxperiod1(
			BigDecimal f4xxza1rbvxxxxxxxxxxperiod1) {
		this.f4xxza1rbvxxxxxxxxxxperiod1 = f4xxza1rbvxxxxxxxxxxperiod1;
	}

	@Column(name = "period1formulae", length = 159)
	@Size(max = 159)
	public String getF5xxzc1rbxxxxxxxxxxxperiod1formulae() {
		return this.f5xxzc1rbxxxxxxxxxxxperiod1formulae;
	}

	public void setF5xxzc1rbxxxxxxxxxxxperiod1formulae(
			String f5xxzc1rbxxxxxxxxxxxperiod1formulae) {
		this.f5xxzc1rbxxxxxxxxxxxperiod1formulae = f5xxzc1rbxxxxxxxxxxxperiod1formulae;
	}

	@Column(name = "period2label", length = 20)
	@Size(max = 20)
	public String getG3xxul2rbvxxxxxxxxxxperiod2label() {
		return this.g3xxul2rbvxxxxxxxxxxperiod2label;
	}

	public void setG3xxul2rbvxxxxxxxxxxperiod2label(
			String g3xxul2rbvxxxxxxxxxxperiod2label) {
		this.g3xxul2rbvxxxxxxxxxxperiod2label = g3xxul2rbvxxxxxxxxxxperiod2label;
	}

	@Column(name = "period2b", precision = 14)
	public BigDecimal getG3xxzb2rbvxxxxxxxxxxperiod2b() {
		return this.g3xxzb2rbvxxxxxxxxxxperiod2b;
	}

	public void setG3xxzb2rbvxxxxxxxxxxperiod2b(
			BigDecimal g3xxzb2rbvxxxxxxxxxxperiod2b) {
		this.g3xxzb2rbvxxxxxxxxxxperiod2b = g3xxzb2rbvxxxxxxxxxxperiod2b;
	}

	@Column(name = "period2", precision = 14)
	public BigDecimal getG4xxza2rbvxxxxxxxxxxperiod2() {
		return this.g4xxza2rbvxxxxxxxxxxperiod2;
	}

	public void setG4xxza2rbvxxxxxxxxxxperiod2(
			BigDecimal g4xxza2rbvxxxxxxxxxxperiod2) {
		this.g4xxza2rbvxxxxxxxxxxperiod2 = g4xxza2rbvxxxxxxxxxxperiod2;
	}

	@Column(name = "period2formulae", length = 159)
	@Size(max = 159)
	public String getG5xxzc2rbxxxxxxxxxxxperiod2formulae() {
		return this.g5xxzc2rbxxxxxxxxxxxperiod2formulae;
	}

	public void setG5xxzc2rbxxxxxxxxxxxperiod2formulae(
			String g5xxzc2rbxxxxxxxxxxxperiod2formulae) {
		this.g5xxzc2rbxxxxxxxxxxxperiod2formulae = g5xxzc2rbxxxxxxxxxxxperiod2formulae;
	}

	@Column(name = "period3label", length = 20)
	@Size(max = 20)
	public String getH3xxul3rbvxxxxxxxxxxperiod3label() {
		return this.h3xxul3rbvxxxxxxxxxxperiod3label;
	}

	public void setH3xxul3rbvxxxxxxxxxxperiod3label(
			String h3xxul3rbvxxxxxxxxxxperiod3label) {
		this.h3xxul3rbvxxxxxxxxxxperiod3label = h3xxul3rbvxxxxxxxxxxperiod3label;
	}

	@Column(name = "period3b", precision = 14)
	public BigDecimal getH3xxzb3rbvxxxxxxxxxxperiod3b() {
		return this.h3xxzb3rbvxxxxxxxxxxperiod3b;
	}

	public void setH3xxzb3rbvxxxxxxxxxxperiod3b(
			BigDecimal h3xxzb3rbvxxxxxxxxxxperiod3b) {
		this.h3xxzb3rbvxxxxxxxxxxperiod3b = h3xxzb3rbvxxxxxxxxxxperiod3b;
	}

	@Column(name = "period3", precision = 14)
	public BigDecimal getH4xxza3rbvxxxxxxxxxxperiod3() {
		return this.h4xxza3rbvxxxxxxxxxxperiod3;
	}

	public void setH4xxza3rbvxxxxxxxxxxperiod3(
			BigDecimal h4xxza3rbvxxxxxxxxxxperiod3) {
		this.h4xxza3rbvxxxxxxxxxxperiod3 = h4xxza3rbvxxxxxxxxxxperiod3;
	}

	@Column(name = "period3formulae", length = 159)
	@Size(max = 159)
	public String getH5xxzc3rbxxxxxxxxxxxperiod3formulae() {
		return this.h5xxzc3rbxxxxxxxxxxxperiod3formulae;
	}

	public void setH5xxzc3rbxxxxxxxxxxxperiod3formulae(
			String h5xxzc3rbxxxxxxxxxxxperiod3formulae) {
		this.h5xxzc3rbxxxxxxxxxxxperiod3formulae = h5xxzc3rbxxxxxxxxxxxperiod3formulae;
	}

	@Column(name = "period4label", length = 20)
	@Size(max = 20)
	public String getI3xxul4rbvxxxxxxxxxxperiod4label() {
		return this.i3xxul4rbvxxxxxxxxxxperiod4label;
	}

	public void setI3xxul4rbvxxxxxxxxxxperiod4label(
			String i3xxul4rbvxxxxxxxxxxperiod4label) {
		this.i3xxul4rbvxxxxxxxxxxperiod4label = i3xxul4rbvxxxxxxxxxxperiod4label;
	}

	@Column(name = "period4b", precision = 14)
	public BigDecimal getI3xxzb4rbvxxxxxxxxxxperiod4b() {
		return this.i3xxzb4rbvxxxxxxxxxxperiod4b;
	}

	public void setI3xxzb4rbvxxxxxxxxxxperiod4b(
			BigDecimal i3xxzb4rbvxxxxxxxxxxperiod4b) {
		this.i3xxzb4rbvxxxxxxxxxxperiod4b = i3xxzb4rbvxxxxxxxxxxperiod4b;
	}

	@Column(name = "period4", precision = 14)
	public BigDecimal getI4xxza4rbvxxxxxxxxxxperiod4() {
		return this.i4xxza4rbvxxxxxxxxxxperiod4;
	}

	public void setI4xxza4rbvxxxxxxxxxxperiod4(
			BigDecimal i4xxza4rbvxxxxxxxxxxperiod4) {
		this.i4xxza4rbvxxxxxxxxxxperiod4 = i4xxza4rbvxxxxxxxxxxperiod4;
	}

	@Column(name = "period4formulae", length = 159)
	@Size(max = 159)
	public String getI5xxzc4rbxxxxxxxxxxxperiod4formulae() {
		return this.i5xxzc4rbxxxxxxxxxxxperiod4formulae;
	}

	public void setI5xxzc4rbxxxxxxxxxxxperiod4formulae(
			String i5xxzc4rbxxxxxxxxxxxperiod4formulae) {
		this.i5xxzc4rbxxxxxxxxxxxperiod4formulae = i5xxzc4rbxxxxxxxxxxxperiod4formulae;
	}

	@Column(name = "period5label", length = 20)
	@Size(max = 20)
	public String getJ3xxul5rbvxxxxxxxxxxperiod5label() {
		return this.j3xxul5rbvxxxxxxxxxxperiod5label;
	}

	public void setJ3xxul5rbvxxxxxxxxxxperiod5label(
			String j3xxul5rbvxxxxxxxxxxperiod5label) {
		this.j3xxul5rbvxxxxxxxxxxperiod5label = j3xxul5rbvxxxxxxxxxxperiod5label;
	}

	@Column(name = "period5b", precision = 14)
	public BigDecimal getJ3xxzb5rbvxxxxxxxxxxperiod5b() {
		return this.j3xxzb5rbvxxxxxxxxxxperiod5b;
	}

	public void setJ3xxzb5rbvxxxxxxxxxxperiod5b(
			BigDecimal j3xxzb5rbvxxxxxxxxxxperiod5b) {
		this.j3xxzb5rbvxxxxxxxxxxperiod5b = j3xxzb5rbvxxxxxxxxxxperiod5b;
	}

	@Column(name = "period5", precision = 14)
	public BigDecimal getJ4xxza5rbvxxxxxxxxxxperiod5() {
		return this.j4xxza5rbvxxxxxxxxxxperiod5;
	}

	public void setJ4xxza5rbvxxxxxxxxxxperiod5(
			BigDecimal j4xxza5rbvxxxxxxxxxxperiod5) {
		this.j4xxza5rbvxxxxxxxxxxperiod5 = j4xxza5rbvxxxxxxxxxxperiod5;
	}

	@Column(name = "period5formulae", length = 159)
	@Size(max = 159)
	public String getJ5xxzc5rbxxxxxxxxxxxperiod5formulae() {
		return this.j5xxzc5rbxxxxxxxxxxxperiod5formulae;
	}

	public void setJ5xxzc5rbxxxxxxxxxxxperiod5formulae(
			String j5xxzc5rbxxxxxxxxxxxperiod5formulae) {
		this.j5xxzc5rbxxxxxxxxxxxperiod5formulae = j5xxzc5rbxxxxxxxxxxxperiod5formulae;
	}

	@Column(name = "period6label", length = 20)
	@Size(max = 20)
	public String getK3xxul6rbvxxxxxxxxxxperiod6label() {
		return this.k3xxul6rbvxxxxxxxxxxperiod6label;
	}

	public void setK3xxul6rbvxxxxxxxxxxperiod6label(
			String k3xxul6rbvxxxxxxxxxxperiod6label) {
		this.k3xxul6rbvxxxxxxxxxxperiod6label = k3xxul6rbvxxxxxxxxxxperiod6label;
	}

	@Column(name = "period6b", precision = 14)
	public BigDecimal getK3xxzb6rbvxxxxxxxxxxperiod6b() {
		return this.k3xxzb6rbvxxxxxxxxxxperiod6b;
	}

	public void setK3xxzb6rbvxxxxxxxxxxperiod6b(
			BigDecimal k3xxzb6rbvxxxxxxxxxxperiod6b) {
		this.k3xxzb6rbvxxxxxxxxxxperiod6b = k3xxzb6rbvxxxxxxxxxxperiod6b;
	}

	@Column(name = "period6", precision = 14)
	public BigDecimal getK4xxza6rbvxxxxxxxxxxperiod6() {
		return this.k4xxza6rbvxxxxxxxxxxperiod6;
	}

	public void setK4xxza6rbvxxxxxxxxxxperiod6(
			BigDecimal k4xxza6rbvxxxxxxxxxxperiod6) {
		this.k4xxza6rbvxxxxxxxxxxperiod6 = k4xxza6rbvxxxxxxxxxxperiod6;
	}

	@Column(name = "period6formulae", length = 159)
	@Size(max = 159)
	public String getK5xxzc6rbxxxxxxxxxxxperiod6formulae() {
		return this.k5xxzc6rbxxxxxxxxxxxperiod6formulae;
	}

	public void setK5xxzc6rbxxxxxxxxxxxperiod6formulae(
			String k5xxzc6rbxxxxxxxxxxxperiod6formulae) {
		this.k5xxzc6rbxxxxxxxxxxxperiod6formulae = k5xxzc6rbxxxxxxxxxxxperiod6formulae;
	}

	@Column(name = "period7label", length = 20)
	@Size(max = 20)
	public String getL3xxul7rbvxxxxxxxxxxperiod7label() {
		return this.l3xxul7rbvxxxxxxxxxxperiod7label;
	}

	public void setL3xxul7rbvxxxxxxxxxxperiod7label(
			String l3xxul7rbvxxxxxxxxxxperiod7label) {
		this.l3xxul7rbvxxxxxxxxxxperiod7label = l3xxul7rbvxxxxxxxxxxperiod7label;
	}

	@Column(name = "period7b", precision = 14)
	public BigDecimal getL3xxzb7rbvxxxxxxxxxxperiod7b() {
		return this.l3xxzb7rbvxxxxxxxxxxperiod7b;
	}

	public void setL3xxzb7rbvxxxxxxxxxxperiod7b(
			BigDecimal l3xxzb7rbvxxxxxxxxxxperiod7b) {
		this.l3xxzb7rbvxxxxxxxxxxperiod7b = l3xxzb7rbvxxxxxxxxxxperiod7b;
	}

	@Column(name = "period7", precision = 14)
	public BigDecimal getL4xxza7rbvxxxxxxxxxxperiod7() {
		return this.l4xxza7rbvxxxxxxxxxxperiod7;
	}

	public void setL4xxza7rbvxxxxxxxxxxperiod7(
			BigDecimal l4xxza7rbvxxxxxxxxxxperiod7) {
		this.l4xxza7rbvxxxxxxxxxxperiod7 = l4xxza7rbvxxxxxxxxxxperiod7;
	}

	@Column(name = "period7formulae", length = 159)
	@Size(max = 159)
	public String getL5xxzc7rbxxxxxxxxxxxperiod7formulae() {
		return this.l5xxzc7rbxxxxxxxxxxxperiod7formulae;
	}

	public void setL5xxzc7rbxxxxxxxxxxxperiod7formulae(
			String l5xxzc7rbxxxxxxxxxxxperiod7formulae) {
		this.l5xxzc7rbxxxxxxxxxxxperiod7formulae = l5xxzc7rbxxxxxxxxxxxperiod7formulae;
	}

	@Column(name = "period8label", length = 20)
	@Size(max = 20)
	public String getM3xxul8rbvxxxxxxxxxxperiod8label() {
		return this.m3xxul8rbvxxxxxxxxxxperiod8label;
	}

	public void setM3xxul8rbvxxxxxxxxxxperiod8label(
			String m3xxul8rbvxxxxxxxxxxperiod8label) {
		this.m3xxul8rbvxxxxxxxxxxperiod8label = m3xxul8rbvxxxxxxxxxxperiod8label;
	}

	@Column(name = "period8b", precision = 14)
	public BigDecimal getM3xxzb8rbvxxxxxxxxxxperiod8b() {
		return this.m3xxzb8rbvxxxxxxxxxxperiod8b;
	}

	public void setM3xxzb8rbvxxxxxxxxxxperiod8b(
			BigDecimal m3xxzb8rbvxxxxxxxxxxperiod8b) {
		this.m3xxzb8rbvxxxxxxxxxxperiod8b = m3xxzb8rbvxxxxxxxxxxperiod8b;
	}

	@Column(name = "period8", precision = 14)
	public BigDecimal getM4xxza8rbvxxxxxxxxxxperiod8() {
		return this.m4xxza8rbvxxxxxxxxxxperiod8;
	}

	public void setM4xxza8rbvxxxxxxxxxxperiod8(
			BigDecimal m4xxza8rbvxxxxxxxxxxperiod8) {
		this.m4xxza8rbvxxxxxxxxxxperiod8 = m4xxza8rbvxxxxxxxxxxperiod8;
	}

	@Column(name = "period8formulae", length = 159)
	@Size(max = 159)
	public String getM5xxzc8rbxxxxxxxxxxxperiod8formulae() {
		return this.m5xxzc8rbxxxxxxxxxxxperiod8formulae;
	}

	public void setM5xxzc8rbxxxxxxxxxxxperiod8formulae(
			String m5xxzc8rbxxxxxxxxxxxperiod8formulae) {
		this.m5xxzc8rbxxxxxxxxxxxperiod8formulae = m5xxzc8rbxxxxxxxxxxxperiod8formulae;
	}

	@Column(name = "period9label", length = 20)
	@Size(max = 20)
	public String getN3xxul9rbvxxxxxxxxxxperiod9label() {
		return this.n3xxul9rbvxxxxxxxxxxperiod9label;
	}

	public void setN3xxul9rbvxxxxxxxxxxperiod9label(
			String n3xxul9rbvxxxxxxxxxxperiod9label) {
		this.n3xxul9rbvxxxxxxxxxxperiod9label = n3xxul9rbvxxxxxxxxxxperiod9label;
	}

	@Column(name = "period9b", precision = 14)
	public BigDecimal getN3xxzb9rbvxxxxxxxxxxperiod9b() {
		return this.n3xxzb9rbvxxxxxxxxxxperiod9b;
	}

	public void setN3xxzb9rbvxxxxxxxxxxperiod9b(
			BigDecimal n3xxzb9rbvxxxxxxxxxxperiod9b) {
		this.n3xxzb9rbvxxxxxxxxxxperiod9b = n3xxzb9rbvxxxxxxxxxxperiod9b;
	}

	@Column(name = "period9", precision = 14)
	public BigDecimal getN4xxza9rbvxxxxxxxxxxperiod9() {
		return this.n4xxza9rbvxxxxxxxxxxperiod9;
	}

	public void setN4xxza9rbvxxxxxxxxxxperiod9(
			BigDecimal n4xxza9rbvxxxxxxxxxxperiod9) {
		this.n4xxza9rbvxxxxxxxxxxperiod9 = n4xxza9rbvxxxxxxxxxxperiod9;
	}

	@Column(name = "period9formulae", length = 159)
	@Size(max = 159)
	public String getN5xxzc9rbxxxxxxxxxxxperiod9formulae() {
		return this.n5xxzc9rbxxxxxxxxxxxperiod9formulae;
	}

	public void setN5xxzc9rbxxxxxxxxxxxperiod9formulae(
			String n5xxzc9rbxxxxxxxxxxxperiod9formulae) {
		this.n5xxzc9rbxxxxxxxxxxxperiod9formulae = n5xxzc9rbxxxxxxxxxxxperiod9formulae;
	}

	@Column(name = "period10label", length = 20)
	@Size(max = 20)
	public String getO3xxularbvxxxxxxxxxxperiod10label() {
		return this.o3xxularbvxxxxxxxxxxperiod10label;
	}

	public void setO3xxularbvxxxxxxxxxxperiod10label(
			String o3xxularbvxxxxxxxxxxperiod10label) {
		this.o3xxularbvxxxxxxxxxxperiod10label = o3xxularbvxxxxxxxxxxperiod10label;
	}

	@Column(name = "period10b", precision = 14)
	public BigDecimal getO3xxzbarbvxxxxxxxxxxperiod10b() {
		return this.o3xxzbarbvxxxxxxxxxxperiod10b;
	}

	public void setO3xxzbarbvxxxxxxxxxxperiod10b(
			BigDecimal o3xxzbarbvxxxxxxxxxxperiod10b) {
		this.o3xxzbarbvxxxxxxxxxxperiod10b = o3xxzbarbvxxxxxxxxxxperiod10b;
	}

	@Column(name = "period10", precision = 14)
	public BigDecimal getO4xxzaarbvxxxxxxxxxxperiod10() {
		return this.o4xxzaarbvxxxxxxxxxxperiod10;
	}

	public void setO4xxzaarbvxxxxxxxxxxperiod10(
			BigDecimal o4xxzaarbvxxxxxxxxxxperiod10) {
		this.o4xxzaarbvxxxxxxxxxxperiod10 = o4xxzaarbvxxxxxxxxxxperiod10;
	}

	@Column(name = "period10formulae", length = 159)
	@Size(max = 159)
	public String getO5xxzcarbxxxxxxxxxxxperiod10formulae() {
		return this.o5xxzcarbxxxxxxxxxxxperiod10formulae;
	}

	public void setO5xxzcarbxxxxxxxxxxxperiod10formulae(
			String o5xxzcarbxxxxxxxxxxxperiod10formulae) {
		this.o5xxzcarbxxxxxxxxxxxperiod10formulae = o5xxzcarbxxxxxxxxxxxperiod10formulae;
	}

	@Column(name = "period11label", length = 20)
	@Size(max = 20)
	public String getP3xxulbrbvxxxxxxxxxxperiod11label() {
		return this.p3xxulbrbvxxxxxxxxxxperiod11label;
	}

	public void setP3xxulbrbvxxxxxxxxxxperiod11label(
			String p3xxulbrbvxxxxxxxxxxperiod11label) {
		this.p3xxulbrbvxxxxxxxxxxperiod11label = p3xxulbrbvxxxxxxxxxxperiod11label;
	}

	@Column(name = "period11b", precision = 14)
	public BigDecimal getP3xxzbbrbvxxxxxxxxxxperiod11b() {
		return this.p3xxzbbrbvxxxxxxxxxxperiod11b;
	}

	public void setP3xxzbbrbvxxxxxxxxxxperiod11b(
			BigDecimal p3xxzbbrbvxxxxxxxxxxperiod11b) {
		this.p3xxzbbrbvxxxxxxxxxxperiod11b = p3xxzbbrbvxxxxxxxxxxperiod11b;
	}

	@Column(name = "period11", precision = 14)
	public BigDecimal getP4xxzabrbvxxxxxxxxxxperiod11() {
		return this.p4xxzabrbvxxxxxxxxxxperiod11;
	}

	public void setP4xxzabrbvxxxxxxxxxxperiod11(
			BigDecimal p4xxzabrbvxxxxxxxxxxperiod11) {
		this.p4xxzabrbvxxxxxxxxxxperiod11 = p4xxzabrbvxxxxxxxxxxperiod11;
	}

	@Column(name = "period11formulae", length = 159)
	@Size(max = 159)
	public String getP5xxzcbrbxxxxxxxxxxxperiod11formulae() {
		return this.p5xxzcbrbxxxxxxxxxxxperiod11formulae;
	}

	public void setP5xxzcbrbxxxxxxxxxxxperiod11formulae(
			String p5xxzcbrbxxxxxxxxxxxperiod11formulae) {
		this.p5xxzcbrbxxxxxxxxxxxperiod11formulae = p5xxzcbrbxxxxxxxxxxxperiod11formulae;
	}

	@Column(name = "period12label", length = 20)
	@Size(max = 20)
	public String getQ3xxulcrbvxxxxxxxxxxperiod12label() {
		return this.q3xxulcrbvxxxxxxxxxxperiod12label;
	}

	public void setQ3xxulcrbvxxxxxxxxxxperiod12label(
			String q3xxulcrbvxxxxxxxxxxperiod12label) {
		this.q3xxulcrbvxxxxxxxxxxperiod12label = q3xxulcrbvxxxxxxxxxxperiod12label;
	}

	@Column(name = "period12b", precision = 14)
	public BigDecimal getQ3xxzbcrbvxxxxxxxxxxperiod12b() {
		return this.q3xxzbcrbvxxxxxxxxxxperiod12b;
	}

	public void setQ3xxzbcrbvxxxxxxxxxxperiod12b(
			BigDecimal q3xxzbcrbvxxxxxxxxxxperiod12b) {
		this.q3xxzbcrbvxxxxxxxxxxperiod12b = q3xxzbcrbvxxxxxxxxxxperiod12b;
	}

	@Column(name = "period12", precision = 14)
	public BigDecimal getQ4xxzacrbvxxxxxxxxxxperiod12() {
		return this.q4xxzacrbvxxxxxxxxxxperiod12;
	}

	public void setQ4xxzacrbvxxxxxxxxxxperiod12(
			BigDecimal q4xxzacrbvxxxxxxxxxxperiod12) {
		this.q4xxzacrbvxxxxxxxxxxperiod12 = q4xxzacrbvxxxxxxxxxxperiod12;
	}

	@Column(name = "period12formulae", length = 159)
	@Size(max = 159)
	public String getQ5xxzccrbxxxxxxxxxxxperiod12formulae() {
		return this.q5xxzccrbxxxxxxxxxxxperiod12formulae;
	}

	public void setQ5xxzccrbxxxxxxxxxxxperiod12formulae(
			String q5xxzccrbxxxxxxxxxxxperiod12formulae) {
		this.q5xxzccrbxxxxxxxxxxxperiod12formulae = q5xxzccrbxxxxxxxxxxxperiod12formulae;
	}

	@Column(name = "periodnlabel", length = 20)
	@Size(max = 20)
	public String getR3xxuldrbvxxxxxxxxxxperiodnlabel() {
		return this.r3xxuldrbvxxxxxxxxxxperiodnlabel;
	}

	public void setR3xxuldrbvxxxxxxxxxxperiodnlabel(
			String r3xxuldrbvxxxxxxxxxxperiodnlabel) {
		this.r3xxuldrbvxxxxxxxxxxperiodnlabel = r3xxuldrbvxxxxxxxxxxperiodnlabel;
	}

	@Column(name = "periodnb", precision = 14)
	public BigDecimal getR3xxzbdrbvxxxxxxxxxxperiodnb() {
		return this.r3xxzbdrbvxxxxxxxxxxperiodnb;
	}

	public void setR3xxzbdrbvxxxxxxxxxxperiodnb(
			BigDecimal r3xxzbdrbvxxxxxxxxxxperiodnb) {
		this.r3xxzbdrbvxxxxxxxxxxperiodnb = r3xxzbdrbvxxxxxxxxxxperiodnb;
	}

	@Column(name = "periodn", precision = 14)
	public BigDecimal getR4xxzadrbvxxxxxxxxxxperiodn() {
		return this.r4xxzadrbvxxxxxxxxxxperiodn;
	}

	public void setR4xxzadrbvxxxxxxxxxxperiodn(
			BigDecimal r4xxzadrbvxxxxxxxxxxperiodn) {
		this.r4xxzadrbvxxxxxxxxxxperiodn = r4xxzadrbvxxxxxxxxxxperiodn;
	}

	@Column(name = "periodnformulae", length = 159)
	@Size(max = 159)
	public String getR5xxzxxrbxxxxxxxxxxxperiodnformulae() {
		return this.r5xxzxxrbxxxxxxxxxxxperiodnformulae;
	}

	public void setR5xxzxxrbxxxxxxxxxxxperiodnformulae(
			String r5xxzxxrbxxxxxxxxxxxperiodnformulae) {
		this.r5xxzxxrbxxxxxxxxxxxperiodnformulae = r5xxzxxrbxxxxxxxxxxxperiodnformulae;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY1xxuxznbvxxxxxxxxxxnotes() {
		return this.y1xxuxznbvxxxxxxxxxxnotes;
	}

	public void setY1xxuxznbvxxxxxxxxxxnotes(String y1xxuxznbvxxxxxxxxxxnotes) {
		this.y1xxuxznbvxxxxxxxxxxnotes = y1xxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "statusfl")
	public Integer getZixxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zixxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZixxzzfxhhxxxxxxxxxxstatusfl(
			Integer zixxzzfxhhxxxxxxxxxxstatusfl) {
		this.zixxzzfxhhxxxxxxxxxxstatusfl = zixxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZjxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zjxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZjxxcztxlxxxxxxxxxxxstatusfldt(
			Date zjxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zjxxcztxlxxxxxxxxxxxstatusfldt = zjxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZjxxutoxlhxxxxxxxxxxowner() {
		return this.zjxxutoxlhxxxxxxxxxxowner;
	}

	public void setZjxxutoxlhxxxxxxxxxxowner(String zjxxutoxlhxxxxxxxxxxowner) {
		this.zjxxutoxlhxxxxxxxxxxowner = zjxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
