package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Jxxxbh400xwwqqhxxxxxemployee generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "employee")
public class Jxxxbh400xwwqqhxxxxxemployee implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation;
	private Fxxxch133xhhxqhxxlxxdivision fxxxch133xhhxqhxxlxxdivision;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	private Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount;
	private Dxxxiq155xwwqqhxxxxxresidency dxxxiq155xwwqqhxxxxxresidency;
	private Fxxxch122xhhxqhxxlxxdepartment fxxxch122xhhxqhxxlxxdepartment;
	private Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	private String a0xxuktxbvxxxxxxxxxxemployee;
	private String y0xxuzsxbvxxxxxxxxxxdescript;
	private String b1xxuxxxbv21xxxxxxxxtitle;
	private String b2xxuxxrbx22xxxxxxxxjobtitle;
	private String b3xxuslnbvixxxxxxxxxlastname;
	private String b4xxu2fnbvxxxxxxxxxxfirstname;
	private String b5xxuxxrbvxxxxxxxxxxmiddlenam;
	private BigDecimal z1xxztpxlvxxxxxxxxxxempltotl;
	private BigDecimal z2xxztqxlvxxxxxxxxxxempltqty;
	private Boolean c1xxfxz1bxxxxxxxxxxxtax1;
	private Boolean z2xxfxz2bxxxxxxxxxxxtax2;
	private Boolean z3xxfxz3bxxxxxxxxxxxtax3;
	private String c4xxuz1xbv04xxxxxxxxcusttax1;
	private String c5xxuz2xbv05xxxxxxxxcusttax2;
	private String y6xxuz3xxvxxxxxxxxxxcusttax3;
	private String m1xxh3pobv27xxxxxxxxphoneo;
	private String m2xxh4phbv27xxxxxxxxphoneh;
	private String m3xxh5pcbv27xxxxxxxxphonec;
	private String m4xxhxxrbx27xxxxxxxxphonex;
	private String n1xxhxxrbx19xxxxxxxxlanaddr;
	private String n2xxhxxrbx25xxxxxxxxwanaddr;
	private String n3xxhxxrbx44xxxxxxxxlmailaddr;
	private String n4xxhxxrbv24xxxxxxxximailaddr;
	private String n5xxuxxrbxxxxxxxxxxxrmailaddr;
	private String n6xxhxxrbx23xxxxxxxxintaddr;
	private String n7xxuxxrbxxxxxxxxxxxinraddr;
	private BigDecimal z5xxztrplvxxxxxxxxxxemprtotl;
	private BigDecimal z6xxztrqlvxxxxxxxxxxemprtqty;
	private BigDecimal z7xxztmplvxxxxxxxxxxempmtotl;
	private BigDecimal z8xxztdplvxxxxxxxxxxempdtotl;
	private String z9xxutlqlvxxxxxxxxxxlastquote;
	private String z9xxutlolvxxxxxxxxxxlastorder;
	private String zaxxutlilvxxxxxxxxxxlastinvoic;
	private BigDecimal zbxxztlplvxxxxxxxxxxlastpaymq;
	private Integer zcxxzzprhvxxxxxxxxxxprintmstat;
	private Date zdxxczqxlhxxxxxxxxxxprinmtfldt;
	private Boolean y6xxfxxrbvxxxxxxxxxxshiplabel;
	private String o1xxuxxrbv45xxxxxxxxtype;
	private String o2xxuwmrbv40xxxxxxxxintegrset;
	private Integer zexxzzfxhhxxxxxxxxxxstatusfl;
	private Date zfxxcztxlxxxxxxxxxxxstatusfldt;
	private Date y8xxcxxrbvxxxxxxxxxxcontacted;
	private String y9xxuxxrbvxxxxxxxxxxbywho;
	private String yaxxuzkybvxxxxxxxxxxkeywords;
	private String ybxxuznybvxxxxxxxxxxnotes;
	private String zexxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String ycxxuzdrbvxxxxxxxxxxdocmnt;
	private Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplordersesForAgent = new HashSet<Trexuq444xwwqqhxxxxxemplorders>(
			0);
	private Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplordersesForEmployee = new HashSet<Trexuq444xwwqqhxxxxxemplorders>(
			0);
	private Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules = new HashSet<Fxxxuq89bxwwqqhxxxxxschedule>(
			0);
	private Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses = new HashSet<Trexuq344xwwqqhxxxxxvendorders>(
			0);
	private Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices = new HashSet<Trexuq266xwwqqhxxxxxcuinvoice>(
			0);
	private Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers = new HashSet<Yxxxuh566xwwqqwxxxxxuser>(
			0);
	private Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices = new HashSet<Trexuq3a6xwwqqhxxxxxvinvoice>(
			0);
	private Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes = new HashSet<Trexuq333xwwqqhxxxxxvenquote>(
			0);
	private Set<Xxxxiq711xwwqqhxxxxxwageearner> xxxxiq711xwwqqhxxxxxwageearners = new HashSet<Xxxxiq711xwwqqhxxxxxwageearner>(
			0);
	private Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses = new HashSet<Xorxeh8cexwwqqhxxxxxscheduledetails>(
			0);
	private Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses = new HashSet<Jxxxuq54exwwqqhxxxxxgroupmembers>(
			0);
	private Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes = new HashSet<Trexuq233xwwqqhxxxxxcuquote>(
			0);
	private Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses = new HashSet<Trexuq244xwwqqhxxxxxcuorders>(
			0);
	private Set<Yxxxiq555xwwqqhxxxxxholiday> yxxxiq555xwwqqhxxxxxholidaies = new HashSet<Yxxxiq555xwwqqhxxxxxholiday>(
			0);

	public Jxxxbh400xwwqqhxxxxxemployee() {
	}

	public Jxxxbh400xwwqqhxxxxxemployee(String a0xxuktxbvxxxxxxxxxxemployee) {
		this.a0xxuktxbvxxxxxxxxxxemployee = a0xxuktxbvxxxxxxxxxxemployee;
	}
	public Jxxxbh400xwwqqhxxxxxemployee(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation,
			Fxxxch133xhhxqhxxlxxdivision fxxxch133xhhxqhxxlxxdivision,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode,
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount,
			Dxxxiq155xwwqqhxxxxxresidency dxxxiq155xwwqqhxxxxxresidency,
			Fxxxch122xhhxqhxxlxxdepartment fxxxch122xhhxqhxxlxxdepartment,
			Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode,
			String a0xxuktxbvxxxxxxxxxxemployee,
			String y0xxuzsxbvxxxxxxxxxxdescript,
			String b1xxuxxxbv21xxxxxxxxtitle,
			String b2xxuxxrbx22xxxxxxxxjobtitle,
			String b3xxuslnbvixxxxxxxxxlastname,
			String b4xxu2fnbvxxxxxxxxxxfirstname,
			String b5xxuxxrbvxxxxxxxxxxmiddlenam,
			BigDecimal z1xxztpxlvxxxxxxxxxxempltotl,
			BigDecimal z2xxztqxlvxxxxxxxxxxempltqty,
			Boolean c1xxfxz1bxxxxxxxxxxxtax1,
			Boolean z2xxfxz2bxxxxxxxxxxxtax2,
			Boolean z3xxfxz3bxxxxxxxxxxxtax3,
			String c4xxuz1xbv04xxxxxxxxcusttax1,
			String c5xxuz2xbv05xxxxxxxxcusttax2,
			String y6xxuz3xxvxxxxxxxxxxcusttax3,
			String m1xxh3pobv27xxxxxxxxphoneo,
			String m2xxh4phbv27xxxxxxxxphoneh,
			String m3xxh5pcbv27xxxxxxxxphonec,
			String m4xxhxxrbx27xxxxxxxxphonex,
			String n1xxhxxrbx19xxxxxxxxlanaddr,
			String n2xxhxxrbx25xxxxxxxxwanaddr,
			String n3xxhxxrbx44xxxxxxxxlmailaddr,
			String n4xxhxxrbv24xxxxxxxximailaddr,
			String n5xxuxxrbxxxxxxxxxxxrmailaddr,
			String n6xxhxxrbx23xxxxxxxxintaddr,
			String n7xxuxxrbxxxxxxxxxxxinraddr,
			BigDecimal z5xxztrplvxxxxxxxxxxemprtotl,
			BigDecimal z6xxztrqlvxxxxxxxxxxemprtqty,
			BigDecimal z7xxztmplvxxxxxxxxxxempmtotl,
			BigDecimal z8xxztdplvxxxxxxxxxxempdtotl,
			String z9xxutlqlvxxxxxxxxxxlastquote,
			String z9xxutlolvxxxxxxxxxxlastorder,
			String zaxxutlilvxxxxxxxxxxlastinvoic,
			BigDecimal zbxxztlplvxxxxxxxxxxlastpaymq,
			Integer zcxxzzprhvxxxxxxxxxxprintmstat,
			Date zdxxczqxlhxxxxxxxxxxprinmtfldt,
			Boolean y6xxfxxrbvxxxxxxxxxxshiplabel,
			String o1xxuxxrbv45xxxxxxxxtype,
			String o2xxuwmrbv40xxxxxxxxintegrset,
			Integer zexxzzfxhhxxxxxxxxxxstatusfl,
			Date zfxxcztxlxxxxxxxxxxxstatusfldt,
			Date y8xxcxxrbvxxxxxxxxxxcontacted,
			String y9xxuxxrbvxxxxxxxxxxbywho,
			String yaxxuzkybvxxxxxxxxxxkeywords,
			String ybxxuznybvxxxxxxxxxxnotes,
			String zexxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String ycxxuzdrbvxxxxxxxxxxdocmnt,
			Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplordersesForAgent,
			Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplordersesForEmployee,
			Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules,
			Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses,
			Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices,
			Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers,
			Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices,
			Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes,
			Set<Xxxxiq711xwwqqhxxxxxwageearner> xxxxiq711xwwqqhxxxxxwageearners,
			Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses,
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses,
			Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes,
			Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses,
			Set<Yxxxiq555xwwqqhxxxxxholiday> yxxxiq555xwwqqhxxxxxholidaies) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
		this.fxxxch133xhhxqhxxlxxdivision = fxxxch133xhhxqhxxlxxdivision;
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
		this.dxxxiq155xwwqqhxxxxxresidency = dxxxiq155xwwqqhxxxxxresidency;
		this.fxxxch122xhhxqhxxlxxdepartment = fxxxch122xhhxqhxxlxxdepartment;
		this.dxxxch1d3xwwqqhxxlxxcompany = dxxxch1d3xwwqqhxxlxxcompany;
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
		this.a0xxuktxbvxxxxxxxxxxemployee = a0xxuktxbvxxxxxxxxxxemployee;
		this.y0xxuzsxbvxxxxxxxxxxdescript = y0xxuzsxbvxxxxxxxxxxdescript;
		this.b1xxuxxxbv21xxxxxxxxtitle = b1xxuxxxbv21xxxxxxxxtitle;
		this.b2xxuxxrbx22xxxxxxxxjobtitle = b2xxuxxrbx22xxxxxxxxjobtitle;
		this.b3xxuslnbvixxxxxxxxxlastname = b3xxuslnbvixxxxxxxxxlastname;
		this.b4xxu2fnbvxxxxxxxxxxfirstname = b4xxu2fnbvxxxxxxxxxxfirstname;
		this.b5xxuxxrbvxxxxxxxxxxmiddlenam = b5xxuxxrbvxxxxxxxxxxmiddlenam;
		this.z1xxztpxlvxxxxxxxxxxempltotl = z1xxztpxlvxxxxxxxxxxempltotl;
		this.z2xxztqxlvxxxxxxxxxxempltqty = z2xxztqxlvxxxxxxxxxxempltqty;
		this.c1xxfxz1bxxxxxxxxxxxtax1 = c1xxfxz1bxxxxxxxxxxxtax1;
		this.z2xxfxz2bxxxxxxxxxxxtax2 = z2xxfxz2bxxxxxxxxxxxtax2;
		this.z3xxfxz3bxxxxxxxxxxxtax3 = z3xxfxz3bxxxxxxxxxxxtax3;
		this.c4xxuz1xbv04xxxxxxxxcusttax1 = c4xxuz1xbv04xxxxxxxxcusttax1;
		this.c5xxuz2xbv05xxxxxxxxcusttax2 = c5xxuz2xbv05xxxxxxxxcusttax2;
		this.y6xxuz3xxvxxxxxxxxxxcusttax3 = y6xxuz3xxvxxxxxxxxxxcusttax3;
		this.m1xxh3pobv27xxxxxxxxphoneo = m1xxh3pobv27xxxxxxxxphoneo;
		this.m2xxh4phbv27xxxxxxxxphoneh = m2xxh4phbv27xxxxxxxxphoneh;
		this.m3xxh5pcbv27xxxxxxxxphonec = m3xxh5pcbv27xxxxxxxxphonec;
		this.m4xxhxxrbx27xxxxxxxxphonex = m4xxhxxrbx27xxxxxxxxphonex;
		this.n1xxhxxrbx19xxxxxxxxlanaddr = n1xxhxxrbx19xxxxxxxxlanaddr;
		this.n2xxhxxrbx25xxxxxxxxwanaddr = n2xxhxxrbx25xxxxxxxxwanaddr;
		this.n3xxhxxrbx44xxxxxxxxlmailaddr = n3xxhxxrbx44xxxxxxxxlmailaddr;
		this.n4xxhxxrbv24xxxxxxxximailaddr = n4xxhxxrbv24xxxxxxxximailaddr;
		this.n5xxuxxrbxxxxxxxxxxxrmailaddr = n5xxuxxrbxxxxxxxxxxxrmailaddr;
		this.n6xxhxxrbx23xxxxxxxxintaddr = n6xxhxxrbx23xxxxxxxxintaddr;
		this.n7xxuxxrbxxxxxxxxxxxinraddr = n7xxuxxrbxxxxxxxxxxxinraddr;
		this.z5xxztrplvxxxxxxxxxxemprtotl = z5xxztrplvxxxxxxxxxxemprtotl;
		this.z6xxztrqlvxxxxxxxxxxemprtqty = z6xxztrqlvxxxxxxxxxxemprtqty;
		this.z7xxztmplvxxxxxxxxxxempmtotl = z7xxztmplvxxxxxxxxxxempmtotl;
		this.z8xxztdplvxxxxxxxxxxempdtotl = z8xxztdplvxxxxxxxxxxempdtotl;
		this.z9xxutlqlvxxxxxxxxxxlastquote = z9xxutlqlvxxxxxxxxxxlastquote;
		this.z9xxutlolvxxxxxxxxxxlastorder = z9xxutlolvxxxxxxxxxxlastorder;
		this.zaxxutlilvxxxxxxxxxxlastinvoic = zaxxutlilvxxxxxxxxxxlastinvoic;
		this.zbxxztlplvxxxxxxxxxxlastpaymq = zbxxztlplvxxxxxxxxxxlastpaymq;
		this.zcxxzzprhvxxxxxxxxxxprintmstat = zcxxzzprhvxxxxxxxxxxprintmstat;
		this.zdxxczqxlhxxxxxxxxxxprinmtfldt = zdxxczqxlhxxxxxxxxxxprinmtfldt;
		this.y6xxfxxrbvxxxxxxxxxxshiplabel = y6xxfxxrbvxxxxxxxxxxshiplabel;
		this.o1xxuxxrbv45xxxxxxxxtype = o1xxuxxrbv45xxxxxxxxtype;
		this.o2xxuwmrbv40xxxxxxxxintegrset = o2xxuwmrbv40xxxxxxxxintegrset;
		this.zexxzzfxhhxxxxxxxxxxstatusfl = zexxzzfxhhxxxxxxxxxxstatusfl;
		this.zfxxcztxlxxxxxxxxxxxstatusfldt = zfxxcztxlxxxxxxxxxxxstatusfldt;
		this.y8xxcxxrbvxxxxxxxxxxcontacted = y8xxcxxrbvxxxxxxxxxxcontacted;
		this.y9xxuxxrbvxxxxxxxxxxbywho = y9xxuxxrbvxxxxxxxxxxbywho;
		this.yaxxuzkybvxxxxxxxxxxkeywords = yaxxuzkybvxxxxxxxxxxkeywords;
		this.ybxxuznybvxxxxxxxxxxnotes = ybxxuznybvxxxxxxxxxxnotes;
		this.zexxutoxlhxxxxxxxxxxowner = zexxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.ycxxuzdrbvxxxxxxxxxxdocmnt = ycxxuzdrbvxxxxxxxxxxdocmnt;
		this.trexuq444xwwqqhxxxxxemplordersesForAgent = trexuq444xwwqqhxxxxxemplordersesForAgent;
		this.trexuq444xwwqqhxxxxxemplordersesForEmployee = trexuq444xwwqqhxxxxxemplordersesForEmployee;
		this.fxxxuq89bxwwqqhxxxxxschedules = fxxxuq89bxwwqqhxxxxxschedules;
		this.trexuq344xwwqqhxxxxxvendorderses = trexuq344xwwqqhxxxxxvendorderses;
		this.trexuq266xwwqqhxxxxxcuinvoices = trexuq266xwwqqhxxxxxcuinvoices;
		this.yxxxuh566xwwqqwxxxxxusers = yxxxuh566xwwqqwxxxxxusers;
		this.trexuq3a6xwwqqhxxxxxvinvoices = trexuq3a6xwwqqhxxxxxvinvoices;
		this.trexuq333xwwqqhxxxxxvenquotes = trexuq333xwwqqhxxxxxvenquotes;
		this.xxxxiq711xwwqqhxxxxxwageearners = xxxxiq711xwwqqhxxxxxwageearners;
		this.xorxeh8cexwwqqhxxxxxscheduledetailses = xorxeh8cexwwqqhxxxxxscheduledetailses;
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
		this.trexuq233xwwqqhxxxxxcuquotes = trexuq233xwwqqhxxxxxcuquotes;
		this.trexuq244xwwqqhxxxxxcuorderses = trexuq244xwwqqhxxxxxcuorderses;
		this.yxxxiq555xwwqqhxxxxxholidaies = yxxxiq555xwwqqhxxxxxholidaies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public Fxxxcq144xwwqqhxxxxxlocation getFxxxcq144xwwqqhxxxxxlocation() {
		return this.fxxxcq144xwwqqhxxxxxlocation;
	}

	public void setFxxxcq144xwwqqhxxxxxlocation(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "divcode")
	public Fxxxch133xhhxqhxxlxxdivision getFxxxch133xhhxqhxxlxxdivision() {
		return this.fxxxch133xhhxqhxxlxxdivision;
	}

	public void setFxxxch133xhhxqhxxlxxdivision(
			Fxxxch133xhhxqhxxlxxdivision fxxxch133xhhxqhxxlxxdivision) {
		this.fxxxch133xhhxqhxxlxxdivision = fxxxch133xhhxqhxxlxxdivision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailtocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByMailtocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByMailtocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "defaultglac")
	public Yxxxch601xwwqqhxxxxxaccount getYxxxch601xwwqqhxxxxxaccount() {
		return this.yxxxch601xwwqqhxxxxxaccount;
	}

	public void setYxxxch601xwwqqhxxxxxaccount(
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount) {
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "residency")
	public Dxxxiq155xwwqqhxxxxxresidency getDxxxiq155xwwqqhxxxxxresidency() {
		return this.dxxxiq155xwwqqhxxxxxresidency;
	}

	public void setDxxxiq155xwwqqhxxxxxresidency(
			Dxxxiq155xwwqqhxxxxxresidency dxxxiq155xwwqqhxxxxxresidency) {
		this.dxxxiq155xwwqqhxxxxxresidency = dxxxiq155xwwqqhxxxxxresidency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depcode")
	public Fxxxch122xhhxqhxxlxxdepartment getFxxxch122xhhxqhxxlxxdepartment() {
		return this.fxxxch122xhhxqhxxlxxdepartment;
	}

	public void setFxxxch122xhhxqhxxlxxdepartment(
			Fxxxch122xhhxqhxxlxxdepartment fxxxch122xhhxqhxxlxxdepartment) {
		this.fxxxch122xhhxqhxxlxxdepartment = fxxxch122xhhxqhxxlxxdepartment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companycode")
	public Dxxxch1d3xwwqqhxxlxxcompany getDxxxch1d3xwwqqhxxlxxcompany() {
		return this.dxxxch1d3xwwqqhxxlxxcompany;
	}

	public void setDxxxch1d3xwwqqhxxlxxcompany(
			Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany) {
		this.dxxxch1d3xwwqqhxxlxxcompany = dxxxch1d3xwwqqhxxlxxcompany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shiptocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByShiptocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByShiptocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	@Column(name = "employee", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxuktxbvxxxxxxxxxxemployee() {
		return this.a0xxuktxbvxxxxxxxxxxemployee;
	}

	public void setA0xxuktxbvxxxxxxxxxxemployee(
			String a0xxuktxbvxxxxxxxxxxemployee) {
		this.a0xxuktxbvxxxxxxxxxxemployee = a0xxuktxbvxxxxxxxxxxemployee;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getY0xxuzsxbvxxxxxxxxxxdescript() {
		return this.y0xxuzsxbvxxxxxxxxxxdescript;
	}

	public void setY0xxuzsxbvxxxxxxxxxxdescript(
			String y0xxuzsxbvxxxxxxxxxxdescript) {
		this.y0xxuzsxbvxxxxxxxxxxdescript = y0xxuzsxbvxxxxxxxxxxdescript;
	}

	@Column(name = "title", length = 20)
	@Size(max = 20)
	public String getB1xxuxxxbv21xxxxxxxxtitle() {
		return this.b1xxuxxxbv21xxxxxxxxtitle;
	}

	public void setB1xxuxxxbv21xxxxxxxxtitle(String b1xxuxxxbv21xxxxxxxxtitle) {
		this.b1xxuxxxbv21xxxxxxxxtitle = b1xxuxxxbv21xxxxxxxxtitle;
	}

	@Column(name = "jobtitle", length = 20)
	@Size(max = 20)
	public String getB2xxuxxrbx22xxxxxxxxjobtitle() {
		return this.b2xxuxxrbx22xxxxxxxxjobtitle;
	}

	public void setB2xxuxxrbx22xxxxxxxxjobtitle(
			String b2xxuxxrbx22xxxxxxxxjobtitle) {
		this.b2xxuxxrbx22xxxxxxxxjobtitle = b2xxuxxrbx22xxxxxxxxjobtitle;
	}

	@Column(name = "lastname", length = 25)
	@Size(max = 25)
	public String getB3xxuslnbvixxxxxxxxxlastname() {
		return this.b3xxuslnbvixxxxxxxxxlastname;
	}

	public void setB3xxuslnbvixxxxxxxxxlastname(
			String b3xxuslnbvixxxxxxxxxlastname) {
		this.b3xxuslnbvixxxxxxxxxlastname = b3xxuslnbvixxxxxxxxxlastname;
	}

	@Column(name = "firstname", length = 25)
	@Size(max = 25)
	public String getB4xxu2fnbvxxxxxxxxxxfirstname() {
		return this.b4xxu2fnbvxxxxxxxxxxfirstname;
	}

	public void setB4xxu2fnbvxxxxxxxxxxfirstname(
			String b4xxu2fnbvxxxxxxxxxxfirstname) {
		this.b4xxu2fnbvxxxxxxxxxxfirstname = b4xxu2fnbvxxxxxxxxxxfirstname;
	}

	@Column(name = "middlenam", length = 20)
	@Size(max = 20)
	public String getB5xxuxxrbvxxxxxxxxxxmiddlenam() {
		return this.b5xxuxxrbvxxxxxxxxxxmiddlenam;
	}

	public void setB5xxuxxrbvxxxxxxxxxxmiddlenam(
			String b5xxuxxrbvxxxxxxxxxxmiddlenam) {
		this.b5xxuxxrbvxxxxxxxxxxmiddlenam = b5xxuxxrbvxxxxxxxxxxmiddlenam;
	}

	@Column(name = "empltotl", precision = 14)
	public BigDecimal getZ1xxztpxlvxxxxxxxxxxempltotl() {
		return this.z1xxztpxlvxxxxxxxxxxempltotl;
	}

	public void setZ1xxztpxlvxxxxxxxxxxempltotl(
			BigDecimal z1xxztpxlvxxxxxxxxxxempltotl) {
		this.z1xxztpxlvxxxxxxxxxxempltotl = z1xxztpxlvxxxxxxxxxxempltotl;
	}

	@Column(name = "empltqty", precision = 14)
	public BigDecimal getZ2xxztqxlvxxxxxxxxxxempltqty() {
		return this.z2xxztqxlvxxxxxxxxxxempltqty;
	}

	public void setZ2xxztqxlvxxxxxxxxxxempltqty(
			BigDecimal z2xxztqxlvxxxxxxxxxxempltqty) {
		this.z2xxztqxlvxxxxxxxxxxempltqty = z2xxztqxlvxxxxxxxxxxempltqty;
	}

	@Column(name = "tax1")
	public Boolean getC1xxfxz1bxxxxxxxxxxxtax1() {
		return this.c1xxfxz1bxxxxxxxxxxxtax1;
	}

	public void setC1xxfxz1bxxxxxxxxxxxtax1(Boolean c1xxfxz1bxxxxxxxxxxxtax1) {
		this.c1xxfxz1bxxxxxxxxxxxtax1 = c1xxfxz1bxxxxxxxxxxxtax1;
	}

	@Column(name = "tax2")
	public Boolean getZ2xxfxz2bxxxxxxxxxxxtax2() {
		return this.z2xxfxz2bxxxxxxxxxxxtax2;
	}

	public void setZ2xxfxz2bxxxxxxxxxxxtax2(Boolean z2xxfxz2bxxxxxxxxxxxtax2) {
		this.z2xxfxz2bxxxxxxxxxxxtax2 = z2xxfxz2bxxxxxxxxxxxtax2;
	}

	@Column(name = "tax3")
	public Boolean getZ3xxfxz3bxxxxxxxxxxxtax3() {
		return this.z3xxfxz3bxxxxxxxxxxxtax3;
	}

	public void setZ3xxfxz3bxxxxxxxxxxxtax3(Boolean z3xxfxz3bxxxxxxxxxxxtax3) {
		this.z3xxfxz3bxxxxxxxxxxxtax3 = z3xxfxz3bxxxxxxxxxxxtax3;
	}

	@Column(name = "custtax1", length = 25)
	@Size(max = 25)
	public String getC4xxuz1xbv04xxxxxxxxcusttax1() {
		return this.c4xxuz1xbv04xxxxxxxxcusttax1;
	}

	public void setC4xxuz1xbv04xxxxxxxxcusttax1(
			String c4xxuz1xbv04xxxxxxxxcusttax1) {
		this.c4xxuz1xbv04xxxxxxxxcusttax1 = c4xxuz1xbv04xxxxxxxxcusttax1;
	}

	@Column(name = "custtax2", length = 25)
	@Size(max = 25)
	public String getC5xxuz2xbv05xxxxxxxxcusttax2() {
		return this.c5xxuz2xbv05xxxxxxxxcusttax2;
	}

	public void setC5xxuz2xbv05xxxxxxxxcusttax2(
			String c5xxuz2xbv05xxxxxxxxcusttax2) {
		this.c5xxuz2xbv05xxxxxxxxcusttax2 = c5xxuz2xbv05xxxxxxxxcusttax2;
	}

	@Column(name = "custtax3", length = 25)
	@Size(max = 25)
	public String getY6xxuz3xxvxxxxxxxxxxcusttax3() {
		return this.y6xxuz3xxvxxxxxxxxxxcusttax3;
	}

	public void setY6xxuz3xxvxxxxxxxxxxcusttax3(
			String y6xxuz3xxvxxxxxxxxxxcusttax3) {
		this.y6xxuz3xxvxxxxxxxxxxcusttax3 = y6xxuz3xxvxxxxxxxxxxcusttax3;
	}

	@Column(name = "phoneo", length = 30)
	@Size(max = 30)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM1xxh3pobv27xxxxxxxxphoneo() {
		return this.m1xxh3pobv27xxxxxxxxphoneo;
	}

	public void setM1xxh3pobv27xxxxxxxxphoneo(String m1xxh3pobv27xxxxxxxxphoneo) {
		this.m1xxh3pobv27xxxxxxxxphoneo = m1xxh3pobv27xxxxxxxxphoneo;
	}

	@Column(name = "phoneh", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM2xxh4phbv27xxxxxxxxphoneh() {
		return this.m2xxh4phbv27xxxxxxxxphoneh;
	}

	public void setM2xxh4phbv27xxxxxxxxphoneh(String m2xxh4phbv27xxxxxxxxphoneh) {
		this.m2xxh4phbv27xxxxxxxxphoneh = m2xxh4phbv27xxxxxxxxphoneh;
	}

	@Column(name = "phonec", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM3xxh5pcbv27xxxxxxxxphonec() {
		return this.m3xxh5pcbv27xxxxxxxxphonec;
	}

	public void setM3xxh5pcbv27xxxxxxxxphonec(String m3xxh5pcbv27xxxxxxxxphonec) {
		this.m3xxh5pcbv27xxxxxxxxphonec = m3xxh5pcbv27xxxxxxxxphonec;
	}

	@Column(name = "phonex", length = 30)
	@Size(max = 30)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM4xxhxxrbx27xxxxxxxxphonex() {
		return this.m4xxhxxrbx27xxxxxxxxphonex;
	}

	public void setM4xxhxxrbx27xxxxxxxxphonex(String m4xxhxxrbx27xxxxxxxxphonex) {
		this.m4xxhxxrbx27xxxxxxxxphonex = m4xxhxxrbx27xxxxxxxxphonex;
	}

	@Column(name = "lanaddr", length = 35)
	@Size(max = 35)
	public String getN1xxhxxrbx19xxxxxxxxlanaddr() {
		return this.n1xxhxxrbx19xxxxxxxxlanaddr;
	}

	public void setN1xxhxxrbx19xxxxxxxxlanaddr(
			String n1xxhxxrbx19xxxxxxxxlanaddr) {
		this.n1xxhxxrbx19xxxxxxxxlanaddr = n1xxhxxrbx19xxxxxxxxlanaddr;
	}

	@Column(name = "wanaddr", length = 35)
	@Size(max = 35)
	public String getN2xxhxxrbx25xxxxxxxxwanaddr() {
		return this.n2xxhxxrbx25xxxxxxxxwanaddr;
	}

	public void setN2xxhxxrbx25xxxxxxxxwanaddr(
			String n2xxhxxrbx25xxxxxxxxwanaddr) {
		this.n2xxhxxrbx25xxxxxxxxwanaddr = n2xxhxxrbx25xxxxxxxxwanaddr;
	}

	@Column(name = "lmailaddr", length = 35)
	@Size(max = 35)
	public String getN3xxhxxrbx44xxxxxxxxlmailaddr() {
		return this.n3xxhxxrbx44xxxxxxxxlmailaddr;
	}

	public void setN3xxhxxrbx44xxxxxxxxlmailaddr(
			String n3xxhxxrbx44xxxxxxxxlmailaddr) {
		this.n3xxhxxrbx44xxxxxxxxlmailaddr = n3xxhxxrbx44xxxxxxxxlmailaddr;
	}

	@Column(name = "imailaddr", length = 60)
	@Size(max = 60)
	@Pattern.List({
			@Pattern(regexp = "(^$|.+@.+\\..+)", message = "Bad email value"),
			@Pattern(regexp = "(^$)|(^\\S+$)", message = "email has space character")})
	public String getN4xxhxxrbv24xxxxxxxximailaddr() {
		return this.n4xxhxxrbv24xxxxxxxximailaddr;
	}

	public void setN4xxhxxrbv24xxxxxxxximailaddr(
			String n4xxhxxrbv24xxxxxxxximailaddr) {
		this.n4xxhxxrbv24xxxxxxxximailaddr = n4xxhxxrbv24xxxxxxxximailaddr;
	}

	@Column(name = "rmailaddr", length = 35)
	@Size(max = 35)
	public String getN5xxuxxrbxxxxxxxxxxxrmailaddr() {
		return this.n5xxuxxrbxxxxxxxxxxxrmailaddr;
	}

	public void setN5xxuxxrbxxxxxxxxxxxrmailaddr(
			String n5xxuxxrbxxxxxxxxxxxrmailaddr) {
		this.n5xxuxxrbxxxxxxxxxxxrmailaddr = n5xxuxxrbxxxxxxxxxxxrmailaddr;
	}

	@Column(name = "intaddr", length = 60)
	@Size(max = 60)
	public String getN6xxhxxrbx23xxxxxxxxintaddr() {
		return this.n6xxhxxrbx23xxxxxxxxintaddr;
	}

	public void setN6xxhxxrbx23xxxxxxxxintaddr(
			String n6xxhxxrbx23xxxxxxxxintaddr) {
		this.n6xxhxxrbx23xxxxxxxxintaddr = n6xxhxxrbx23xxxxxxxxintaddr;
	}

	@Column(name = "inraddr", length = 35)
	@Size(max = 35)
	public String getN7xxuxxrbxxxxxxxxxxxinraddr() {
		return this.n7xxuxxrbxxxxxxxxxxxinraddr;
	}

	public void setN7xxuxxrbxxxxxxxxxxxinraddr(
			String n7xxuxxrbxxxxxxxxxxxinraddr) {
		this.n7xxuxxrbxxxxxxxxxxxinraddr = n7xxuxxrbxxxxxxxxxxxinraddr;
	}

	@Column(name = "emprtotl", precision = 14)
	public BigDecimal getZ5xxztrplvxxxxxxxxxxemprtotl() {
		return this.z5xxztrplvxxxxxxxxxxemprtotl;
	}

	public void setZ5xxztrplvxxxxxxxxxxemprtotl(
			BigDecimal z5xxztrplvxxxxxxxxxxemprtotl) {
		this.z5xxztrplvxxxxxxxxxxemprtotl = z5xxztrplvxxxxxxxxxxemprtotl;
	}

	@Column(name = "emprtqty", precision = 14)
	public BigDecimal getZ6xxztrqlvxxxxxxxxxxemprtqty() {
		return this.z6xxztrqlvxxxxxxxxxxemprtqty;
	}

	public void setZ6xxztrqlvxxxxxxxxxxemprtqty(
			BigDecimal z6xxztrqlvxxxxxxxxxxemprtqty) {
		this.z6xxztrqlvxxxxxxxxxxemprtqty = z6xxztrqlvxxxxxxxxxxemprtqty;
	}

	@Column(name = "empmtotl", precision = 14)
	public BigDecimal getZ7xxztmplvxxxxxxxxxxempmtotl() {
		return this.z7xxztmplvxxxxxxxxxxempmtotl;
	}

	public void setZ7xxztmplvxxxxxxxxxxempmtotl(
			BigDecimal z7xxztmplvxxxxxxxxxxempmtotl) {
		this.z7xxztmplvxxxxxxxxxxempmtotl = z7xxztmplvxxxxxxxxxxempmtotl;
	}

	@Column(name = "empdtotl", precision = 14)
	public BigDecimal getZ8xxztdplvxxxxxxxxxxempdtotl() {
		return this.z8xxztdplvxxxxxxxxxxempdtotl;
	}

	public void setZ8xxztdplvxxxxxxxxxxempdtotl(
			BigDecimal z8xxztdplvxxxxxxxxxxempdtotl) {
		this.z8xxztdplvxxxxxxxxxxempdtotl = z8xxztdplvxxxxxxxxxxempdtotl;
	}

	@Column(name = "lastquote", length = 20)
	@Size(max = 20)
	public String getZ9xxutlqlvxxxxxxxxxxlastquote() {
		return this.z9xxutlqlvxxxxxxxxxxlastquote;
	}

	public void setZ9xxutlqlvxxxxxxxxxxlastquote(
			String z9xxutlqlvxxxxxxxxxxlastquote) {
		this.z9xxutlqlvxxxxxxxxxxlastquote = z9xxutlqlvxxxxxxxxxxlastquote;
	}

	@Column(name = "lastorder", length = 20)
	@Size(max = 20)
	public String getZ9xxutlolvxxxxxxxxxxlastorder() {
		return this.z9xxutlolvxxxxxxxxxxlastorder;
	}

	public void setZ9xxutlolvxxxxxxxxxxlastorder(
			String z9xxutlolvxxxxxxxxxxlastorder) {
		this.z9xxutlolvxxxxxxxxxxlastorder = z9xxutlolvxxxxxxxxxxlastorder;
	}

	@Column(name = "lastinvoic", length = 20)
	@Size(max = 20)
	public String getZaxxutlilvxxxxxxxxxxlastinvoic() {
		return this.zaxxutlilvxxxxxxxxxxlastinvoic;
	}

	public void setZaxxutlilvxxxxxxxxxxlastinvoic(
			String zaxxutlilvxxxxxxxxxxlastinvoic) {
		this.zaxxutlilvxxxxxxxxxxlastinvoic = zaxxutlilvxxxxxxxxxxlastinvoic;
	}

	@Column(name = "lastpaymq", precision = 14)
	public BigDecimal getZbxxztlplvxxxxxxxxxxlastpaymq() {
		return this.zbxxztlplvxxxxxxxxxxlastpaymq;
	}

	public void setZbxxztlplvxxxxxxxxxxlastpaymq(
			BigDecimal zbxxztlplvxxxxxxxxxxlastpaymq) {
		this.zbxxztlplvxxxxxxxxxxlastpaymq = zbxxztlplvxxxxxxxxxxlastpaymq;
	}

	@Column(name = "printmstat")
	public Integer getZcxxzzprhvxxxxxxxxxxprintmstat() {
		return this.zcxxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZcxxzzprhvxxxxxxxxxxprintmstat(
			Integer zcxxzzprhvxxxxxxxxxxprintmstat) {
		this.zcxxzzprhvxxxxxxxxxxprintmstat = zcxxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZdxxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.zdxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZdxxczqxlhxxxxxxxxxxprinmtfldt(
			Date zdxxczqxlhxxxxxxxxxxprinmtfldt) {
		this.zdxxczqxlhxxxxxxxxxxprinmtfldt = zdxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "shiplabel")
	public Boolean getY6xxfxxrbvxxxxxxxxxxshiplabel() {
		return this.y6xxfxxrbvxxxxxxxxxxshiplabel;
	}

	public void setY6xxfxxrbvxxxxxxxxxxshiplabel(
			Boolean y6xxfxxrbvxxxxxxxxxxshiplabel) {
		this.y6xxfxxrbvxxxxxxxxxxshiplabel = y6xxfxxrbvxxxxxxxxxxshiplabel;
	}

	@Column(name = "type", length = 12)
	@Size(max = 12)
	public String getO1xxuxxrbv45xxxxxxxxtype() {
		return this.o1xxuxxrbv45xxxxxxxxtype;
	}

	public void setO1xxuxxrbv45xxxxxxxxtype(String o1xxuxxrbv45xxxxxxxxtype) {
		this.o1xxuxxrbv45xxxxxxxxtype = o1xxuxxrbv45xxxxxxxxtype;
	}

	@Column(name = "integrset", length = 20)
	@Size(max = 20)
	public String getO2xxuwmrbv40xxxxxxxxintegrset() {
		return this.o2xxuwmrbv40xxxxxxxxintegrset;
	}

	public void setO2xxuwmrbv40xxxxxxxxintegrset(
			String o2xxuwmrbv40xxxxxxxxintegrset) {
		this.o2xxuwmrbv40xxxxxxxxintegrset = o2xxuwmrbv40xxxxxxxxintegrset;
	}

	@Column(name = "statusfl")
	public Integer getZexxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zexxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZexxzzfxhhxxxxxxxxxxstatusfl(
			Integer zexxzzfxhhxxxxxxxxxxstatusfl) {
		this.zexxzzfxhhxxxxxxxxxxstatusfl = zexxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZfxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zfxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZfxxcztxlxxxxxxxxxxxstatusfldt(
			Date zfxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zfxxcztxlxxxxxxxxxxxstatusfldt = zfxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contacted", length = 29)
	public Date getY8xxcxxrbvxxxxxxxxxxcontacted() {
		return this.y8xxcxxrbvxxxxxxxxxxcontacted;
	}

	public void setY8xxcxxrbvxxxxxxxxxxcontacted(
			Date y8xxcxxrbvxxxxxxxxxxcontacted) {
		this.y8xxcxxrbvxxxxxxxxxxcontacted = y8xxcxxrbvxxxxxxxxxxcontacted;
	}

	@Column(name = "bywho", length = 20)
	@Size(max = 20)
	public String getY9xxuxxrbvxxxxxxxxxxbywho() {
		return this.y9xxuxxrbvxxxxxxxxxxbywho;
	}

	public void setY9xxuxxrbvxxxxxxxxxxbywho(String y9xxuxxrbvxxxxxxxxxxbywho) {
		this.y9xxuxxrbvxxxxxxxxxxbywho = y9xxuxxrbvxxxxxxxxxxbywho;
	}

	@Column(name = "keywords", length = 30)
	@Size(max = 30)
	public String getYaxxuzkybvxxxxxxxxxxkeywords() {
		return this.yaxxuzkybvxxxxxxxxxxkeywords;
	}

	public void setYaxxuzkybvxxxxxxxxxxkeywords(
			String yaxxuzkybvxxxxxxxxxxkeywords) {
		this.yaxxuzkybvxxxxxxxxxxkeywords = yaxxuzkybvxxxxxxxxxxkeywords;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getYbxxuznybvxxxxxxxxxxnotes() {
		return this.ybxxuznybvxxxxxxxxxxnotes;
	}

	public void setYbxxuznybvxxxxxxxxxxnotes(String ybxxuznybvxxxxxxxxxxnotes) {
		this.ybxxuznybvxxxxxxxxxxnotes = ybxxuznybvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZexxutoxlhxxxxxxxxxxowner() {
		return this.zexxutoxlhxxxxxxxxxxowner;
	}

	public void setZexxutoxlhxxxxxxxxxxowner(String zexxutoxlhxxxxxxxxxxowner) {
		this.zexxutoxlhxxxxxxxxxxowner = zexxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "docmnt", length = 90)
	@Size(max = 90)
	public String getYcxxuzdrbvxxxxxxxxxxdocmnt() {
		return this.ycxxuzdrbvxxxxxxxxxxdocmnt;
	}

	public void setYcxxuzdrbvxxxxxxxxxxdocmnt(String ycxxuzdrbvxxxxxxxxxxdocmnt) {
		this.ycxxuzdrbvxxxxxxxxxxdocmnt = ycxxuzdrbvxxxxxxxxxxdocmnt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployeeByAgent")
	public Set<Trexuq444xwwqqhxxxxxemplorders> getTrexuq444xwwqqhxxxxxemplordersesForAgent() {
		return this.trexuq444xwwqqhxxxxxemplordersesForAgent;
	}

	public void setTrexuq444xwwqqhxxxxxemplordersesForAgent(
			Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplordersesForAgent) {
		this.trexuq444xwwqqhxxxxxemplordersesForAgent = trexuq444xwwqqhxxxxxemplordersesForAgent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployeeByEmployee")
	public Set<Trexuq444xwwqqhxxxxxemplorders> getTrexuq444xwwqqhxxxxxemplordersesForEmployee() {
		return this.trexuq444xwwqqhxxxxxemplordersesForEmployee;
	}

	public void setTrexuq444xwwqqhxxxxxemplordersesForEmployee(
			Set<Trexuq444xwwqqhxxxxxemplorders> trexuq444xwwqqhxxxxxemplordersesForEmployee) {
		this.trexuq444xwwqqhxxxxxemplordersesForEmployee = trexuq444xwwqqhxxxxxemplordersesForEmployee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Fxxxuq89bxwwqqhxxxxxschedule> getFxxxuq89bxwwqqhxxxxxschedules() {
		return this.fxxxuq89bxwwqqhxxxxxschedules;
	}

	public void setFxxxuq89bxwwqqhxxxxxschedules(
			Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules) {
		this.fxxxuq89bxwwqqhxxxxxschedules = fxxxuq89bxwwqqhxxxxxschedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Trexuq344xwwqqhxxxxxvendorders> getTrexuq344xwwqqhxxxxxvendorderses() {
		return this.trexuq344xwwqqhxxxxxvendorderses;
	}

	public void setTrexuq344xwwqqhxxxxxvendorderses(
			Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses) {
		this.trexuq344xwwqqhxxxxxvendorderses = trexuq344xwwqqhxxxxxvendorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Trexuq266xwwqqhxxxxxcuinvoice> getTrexuq266xwwqqhxxxxxcuinvoices() {
		return this.trexuq266xwwqqhxxxxxcuinvoices;
	}

	public void setTrexuq266xwwqqhxxxxxcuinvoices(
			Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices) {
		this.trexuq266xwwqqhxxxxxcuinvoices = trexuq266xwwqqhxxxxxcuinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Yxxxuh566xwwqqwxxxxxuser> getYxxxuh566xwwqqwxxxxxusers() {
		return this.yxxxuh566xwwqqwxxxxxusers;
	}

	public void setYxxxuh566xwwqqwxxxxxusers(
			Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers) {
		this.yxxxuh566xwwqqwxxxxxusers = yxxxuh566xwwqqwxxxxxusers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Trexuq3a6xwwqqhxxxxxvinvoice> getTrexuq3a6xwwqqhxxxxxvinvoices() {
		return this.trexuq3a6xwwqqhxxxxxvinvoices;
	}

	public void setTrexuq3a6xwwqqhxxxxxvinvoices(
			Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices) {
		this.trexuq3a6xwwqqhxxxxxvinvoices = trexuq3a6xwwqqhxxxxxvinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Trexuq333xwwqqhxxxxxvenquote> getTrexuq333xwwqqhxxxxxvenquotes() {
		return this.trexuq333xwwqqhxxxxxvenquotes;
	}

	public void setTrexuq333xwwqqhxxxxxvenquotes(
			Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes) {
		this.trexuq333xwwqqhxxxxxvenquotes = trexuq333xwwqqhxxxxxvenquotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Xxxxiq711xwwqqhxxxxxwageearner> getXxxxiq711xwwqqhxxxxxwageearners() {
		return this.xxxxiq711xwwqqhxxxxxwageearners;
	}

	public void setXxxxiq711xwwqqhxxxxxwageearners(
			Set<Xxxxiq711xwwqqhxxxxxwageearner> xxxxiq711xwwqqhxxxxxwageearners) {
		this.xxxxiq711xwwqqhxxxxxwageearners = xxxxiq711xwwqqhxxxxxwageearners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Xorxeh8cexwwqqhxxxxxscheduledetails> getXorxeh8cexwwqqhxxxxxscheduledetailses() {
		return this.xorxeh8cexwwqqhxxxxxscheduledetailses;
	}

	public void setXorxeh8cexwwqqhxxxxxscheduledetailses(
			Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses) {
		this.xorxeh8cexwwqqhxxxxxscheduledetailses = xorxeh8cexwwqqhxxxxxscheduledetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Jxxxuq54exwwqqhxxxxxgroupmembers> getJxxxuq54exwwqqhxxxxxgroupmemberses() {
		return this.jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	public void setJxxxuq54exwwqqhxxxxxgroupmemberses(
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses) {
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Trexuq233xwwqqhxxxxxcuquote> getTrexuq233xwwqqhxxxxxcuquotes() {
		return this.trexuq233xwwqqhxxxxxcuquotes;
	}

	public void setTrexuq233xwwqqhxxxxxcuquotes(
			Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes) {
		this.trexuq233xwwqqhxxxxxcuquotes = trexuq233xwwqqhxxxxxcuquotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Trexuq244xwwqqhxxxxxcuorders> getTrexuq244xwwqqhxxxxxcuorderses() {
		return this.trexuq244xwwqqhxxxxxcuorderses;
	}

	public void setTrexuq244xwwqqhxxxxxcuorderses(
			Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses) {
		this.trexuq244xwwqqhxxxxxcuorderses = trexuq244xwwqqhxxxxxcuorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxbh400xwwqqhxxxxxemployee")
	public Set<Yxxxiq555xwwqqhxxxxxholiday> getYxxxiq555xwwqqhxxxxxholidaies() {
		return this.yxxxiq555xwwqqhxxxxxholidaies;
	}

	public void setYxxxiq555xwwqqhxxxxxholidaies(
			Set<Yxxxiq555xwwqqhxxxxxholiday> yxxxiq555xwwqqhxxxxxholidaies) {
		this.yxxxiq555xwwqqhxxxxxholidaies = yxxxiq555xwwqqhxxxxxholidaies;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
