package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Jxxxuq300xwwqqhxxxxxvendor generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "vendor")
public class Jxxxuq300xwwqqhxxxxxvendor implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	private Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount;
	private Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	private String a0xxukxxbvxxxxxxxxxxvendor;
	private String y0xxuzsxbvxxxxxxxxxxdescript;
	private String b1xxuxxrbv21xxxxxxxxtitle;
	private String b2xxuxxrbv22xxxxxxxxjobtitle;
	private String b3xxuslnbvxxxxxxxxxxlastname;
	private String b4xxu2fnbvxxxxxxxxxxfirstname;
	private String b5xxuxxrbvxxxxxxxxxxmiddlenam;
	private String d1xxu3cnbvxxxxxxxxxxvendorascompanyname;
	private BigDecimal z1xxzvpxlvxxxxxxxxxxvendtotl;
	private BigDecimal z2xxzvpxlvxxxxxxxxxxvendtqty;
	private String m1xxh4pobv27xxxxxxxxphoneo;
	private String m2xxh5phbv27xxxxxxxxphoneh;
	private String m3xxhxxrbv27xxxxxxxxphonec;
	private String m4xxhxxrbv27xxxxxxxxphonex;
	private String n1xxhxxrbv19xxxxxxxxlanaddr;
	private String n2xxhxxrbv25xxxxxxxxwanaddr;
	private String n3xxhxxrbv44xxxxxxxxlmailaddr;
	private String n4xxhxxrbv24xxxxxxxximailaddr;
	private String n5xxuxxrbvxxxxxxxxxxrmailaddr;
	private String n6xxuxxrbvxxxxxxxxxxintaddr;
	private String n7xxuxxrbvxxxxxxxxxxinraddr;
	private BigDecimal z3xxzvrplvxxxxxxxxxxvenrtotl;
	private BigDecimal z4xxzvrqlvxxxxxxxxxxvenrtqty;
	private BigDecimal z5xxzvmplvxxxxxxxxxxvenmtotl;
	private BigDecimal z6xxzvdplvxxxxxxxxxxvenddtotl;
	private String z7xxuvlqlvxxxxxxxxxxlastquote;
	private String z7xxuvlolvxxxxxxxxxxlastorder;
	private String z8xxuvlilvxxxxxxxxxxlastinvoic;
	private BigDecimal z9xxzvlplvxxxxxxxxxxlastpaymq;
	private Integer zaxxzzprhvxxxxxxxxxxprintmstat;
	private Date zbxxczqxlhxxxxxxxxxxprinmtfldt;
	private Boolean y4xxfxxrbvxxxxxxxxxxshiplabel;
	private String y5xxuxxrbv29xxxxxxxxtype;
	private String o1xxuwmrbv40xxxxxxxxintegrset;
	private Integer zdxxzzfxhhxxxxxxxxxxstatusfl;
	private Date zexxcztxlxxxxxxxxxxxstatusfldt;
	private BigDecimal zfxxzxxrlvxxxxxxxxxxtotlpaid;
	private Date o3xxuxxrbvxxxxxxxxxxcontacted;
	private String o4xxuxxrbvxxxxxxxxxxbywho;
	private String o5xxuzkybvxxxxxxxxxxkeywords;
	private String y7xxuznxbvxxxxxxxxxxnotes;
	private String zhxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String ycxxuzdrbvxxxxxxxxxxdocmnt;
	private Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes = new HashSet<Trexuq333xwwqqhxxxxxvenquote>(
			0);
	private Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses = new HashSet<Trexuq344xwwqqhxxxxxvendorders>(
			0);
	private Set<Trexuq388xwwqqhxxxxxvpayment> trexuq388xwwqqhxxxxxvpayments = new HashSet<Trexuq388xwwqqhxxxxxvpayment>(
			0);
	private Set<Xoxxuq454xwwqqhxxxxxemplodetails> xoxxuq454xwwqqhxxxxxemplodetailses = new HashSet<Xoxxuq454xwwqqhxxxxxemplodetails>(
			0);
	private Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses = new HashSet<Jxxxuq54exwwqqhxxxxxgroupmembers>(
			0);
	private Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens = new HashSet<Trexuq377xwwqqhxxxxxvshipmen>(
			0);
	private Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> xoxxuq2a4xwwqqhxxxxxcuidetailses = new HashSet<Xoxxuq2a4xwwqqhxxxxxcuidetails>(
			0);
	private Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments = new HashSet<Trxxuq9aaxwwqqhefxxxjobassignment>(
			0);
	private Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = new HashSet<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails>(
			0);
	private Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> xoxxuq3b4xwwqqhxxxxxvendpdetailses = new HashSet<Xoxxuq3b4xwwqqhxxxxxvendpdetails>(
			0);
	private Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules = new HashSet<Fxxxuq89bxwwqqhxxxxxschedule>(
			0);
	private Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> xoxxuq2b4xwwqqhxxxxxcuodetailses = new HashSet<Xoxxuq2b4xwwqqhxxxxxcuodetails>(
			0);
	private Set<Jxxxuq31bxwwqqhxxxxxvcontact> jxxxuq31bxwwqqhxxxxxvcontacts = new HashSet<Jxxxuq31bxwwqqhxxxxxvcontact>(
			0);
	private Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers = new HashSet<Yxxxuh566xwwqqwxxxxxuser>(
			0);
	private Set<Txxxuq366xwwqqhxxxxxvenartha> txxxuq366xwwqqhxxxxxvenarthas = new HashSet<Txxxuq366xwwqqhxxxxxvenartha>(
			0);
	private Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses = new HashSet<Xorxeh8cexwwqqhxxxxxscheduledetails>(
			0);
	private Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices = new HashSet<Trexuq3a6xwwqqhxxxxxvinvoice>(
			0);
	private Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipmentsForCarrier = new HashSet<Trexuq255xwwqqhxxxxxshipment>(
			0);
	private Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> xoxxuq2c4xwwqqhxxxxxcuqdetailses = new HashSet<Xoxxuq2c4xwwqqhxxxxxcuqdetails>(
			0);
	private Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipmentsForShipper = new HashSet<Trexuq255xwwqqhxxxxxshipment>(
			0);

	public Jxxxuq300xwwqqhxxxxxvendor() {
	}

	public Jxxxuq300xwwqqhxxxxxvendor(String a0xxukxxbvxxxxxxxxxxvendor) {
		this.a0xxukxxbvxxxxxxxxxxvendor = a0xxukxxbvxxxxxxxxxxvendor;
	}
	public Jxxxuq300xwwqqhxxxxxvendor(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode,
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount,
			Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode,
			String a0xxukxxbvxxxxxxxxxxvendor,
			String y0xxuzsxbvxxxxxxxxxxdescript,
			String b1xxuxxrbv21xxxxxxxxtitle,
			String b2xxuxxrbv22xxxxxxxxjobtitle,
			String b3xxuslnbvxxxxxxxxxxlastname,
			String b4xxu2fnbvxxxxxxxxxxfirstname,
			String b5xxuxxrbvxxxxxxxxxxmiddlenam,
			String d1xxu3cnbvxxxxxxxxxxvendorascompanyname,
			BigDecimal z1xxzvpxlvxxxxxxxxxxvendtotl,
			BigDecimal z2xxzvpxlvxxxxxxxxxxvendtqty,
			String m1xxh4pobv27xxxxxxxxphoneo,
			String m2xxh5phbv27xxxxxxxxphoneh,
			String m3xxhxxrbv27xxxxxxxxphonec,
			String m4xxhxxrbv27xxxxxxxxphonex,
			String n1xxhxxrbv19xxxxxxxxlanaddr,
			String n2xxhxxrbv25xxxxxxxxwanaddr,
			String n3xxhxxrbv44xxxxxxxxlmailaddr,
			String n4xxhxxrbv24xxxxxxxximailaddr,
			String n5xxuxxrbvxxxxxxxxxxrmailaddr,
			String n6xxuxxrbvxxxxxxxxxxintaddr,
			String n7xxuxxrbvxxxxxxxxxxinraddr,
			BigDecimal z3xxzvrplvxxxxxxxxxxvenrtotl,
			BigDecimal z4xxzvrqlvxxxxxxxxxxvenrtqty,
			BigDecimal z5xxzvmplvxxxxxxxxxxvenmtotl,
			BigDecimal z6xxzvdplvxxxxxxxxxxvenddtotl,
			String z7xxuvlqlvxxxxxxxxxxlastquote,
			String z7xxuvlolvxxxxxxxxxxlastorder,
			String z8xxuvlilvxxxxxxxxxxlastinvoic,
			BigDecimal z9xxzvlplvxxxxxxxxxxlastpaymq,
			Integer zaxxzzprhvxxxxxxxxxxprintmstat,
			Date zbxxczqxlhxxxxxxxxxxprinmtfldt,
			Boolean y4xxfxxrbvxxxxxxxxxxshiplabel,
			String y5xxuxxrbv29xxxxxxxxtype,
			String o1xxuwmrbv40xxxxxxxxintegrset,
			Integer zdxxzzfxhhxxxxxxxxxxstatusfl,
			Date zexxcztxlxxxxxxxxxxxstatusfldt,
			BigDecimal zfxxzxxrlvxxxxxxxxxxtotlpaid,
			Date o3xxuxxrbvxxxxxxxxxxcontacted,
			String o4xxuxxrbvxxxxxxxxxxbywho,
			String o5xxuzkybvxxxxxxxxxxkeywords,
			String y7xxuznxbvxxxxxxxxxxnotes,
			String zhxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String ycxxuzdrbvxxxxxxxxxxdocmnt,
			Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes,
			Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses,
			Set<Trexuq388xwwqqhxxxxxvpayment> trexuq388xwwqqhxxxxxvpayments,
			Set<Xoxxuq454xwwqqhxxxxxemplodetails> xoxxuq454xwwqqhxxxxxemplodetailses,
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses,
			Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens,
			Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> xoxxuq2a4xwwqqhxxxxxcuidetailses,
			Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments,
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses,
			Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> xoxxuq3b4xwwqqhxxxxxvendpdetailses,
			Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules,
			Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> xoxxuq2b4xwwqqhxxxxxcuodetailses,
			Set<Jxxxuq31bxwwqqhxxxxxvcontact> jxxxuq31bxwwqqhxxxxxvcontacts,
			Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers,
			Set<Txxxuq366xwwqqhxxxxxvenartha> txxxuq366xwwqqhxxxxxvenarthas,
			Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses,
			Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices,
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipmentsForCarrier,
			Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> xoxxuq2c4xwwqqhxxxxxcuqdetailses,
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipmentsForShipper) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
		this.dxxxch1d3xwwqqhxxlxxcompany = dxxxch1d3xwwqqhxxlxxcompany;
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
		this.a0xxukxxbvxxxxxxxxxxvendor = a0xxukxxbvxxxxxxxxxxvendor;
		this.y0xxuzsxbvxxxxxxxxxxdescript = y0xxuzsxbvxxxxxxxxxxdescript;
		this.b1xxuxxrbv21xxxxxxxxtitle = b1xxuxxrbv21xxxxxxxxtitle;
		this.b2xxuxxrbv22xxxxxxxxjobtitle = b2xxuxxrbv22xxxxxxxxjobtitle;
		this.b3xxuslnbvxxxxxxxxxxlastname = b3xxuslnbvxxxxxxxxxxlastname;
		this.b4xxu2fnbvxxxxxxxxxxfirstname = b4xxu2fnbvxxxxxxxxxxfirstname;
		this.b5xxuxxrbvxxxxxxxxxxmiddlenam = b5xxuxxrbvxxxxxxxxxxmiddlenam;
		this.d1xxu3cnbvxxxxxxxxxxvendorascompanyname = d1xxu3cnbvxxxxxxxxxxvendorascompanyname;
		this.z1xxzvpxlvxxxxxxxxxxvendtotl = z1xxzvpxlvxxxxxxxxxxvendtotl;
		this.z2xxzvpxlvxxxxxxxxxxvendtqty = z2xxzvpxlvxxxxxxxxxxvendtqty;
		this.m1xxh4pobv27xxxxxxxxphoneo = m1xxh4pobv27xxxxxxxxphoneo;
		this.m2xxh5phbv27xxxxxxxxphoneh = m2xxh5phbv27xxxxxxxxphoneh;
		this.m3xxhxxrbv27xxxxxxxxphonec = m3xxhxxrbv27xxxxxxxxphonec;
		this.m4xxhxxrbv27xxxxxxxxphonex = m4xxhxxrbv27xxxxxxxxphonex;
		this.n1xxhxxrbv19xxxxxxxxlanaddr = n1xxhxxrbv19xxxxxxxxlanaddr;
		this.n2xxhxxrbv25xxxxxxxxwanaddr = n2xxhxxrbv25xxxxxxxxwanaddr;
		this.n3xxhxxrbv44xxxxxxxxlmailaddr = n3xxhxxrbv44xxxxxxxxlmailaddr;
		this.n4xxhxxrbv24xxxxxxxximailaddr = n4xxhxxrbv24xxxxxxxximailaddr;
		this.n5xxuxxrbvxxxxxxxxxxrmailaddr = n5xxuxxrbvxxxxxxxxxxrmailaddr;
		this.n6xxuxxrbvxxxxxxxxxxintaddr = n6xxuxxrbvxxxxxxxxxxintaddr;
		this.n7xxuxxrbvxxxxxxxxxxinraddr = n7xxuxxrbvxxxxxxxxxxinraddr;
		this.z3xxzvrplvxxxxxxxxxxvenrtotl = z3xxzvrplvxxxxxxxxxxvenrtotl;
		this.z4xxzvrqlvxxxxxxxxxxvenrtqty = z4xxzvrqlvxxxxxxxxxxvenrtqty;
		this.z5xxzvmplvxxxxxxxxxxvenmtotl = z5xxzvmplvxxxxxxxxxxvenmtotl;
		this.z6xxzvdplvxxxxxxxxxxvenddtotl = z6xxzvdplvxxxxxxxxxxvenddtotl;
		this.z7xxuvlqlvxxxxxxxxxxlastquote = z7xxuvlqlvxxxxxxxxxxlastquote;
		this.z7xxuvlolvxxxxxxxxxxlastorder = z7xxuvlolvxxxxxxxxxxlastorder;
		this.z8xxuvlilvxxxxxxxxxxlastinvoic = z8xxuvlilvxxxxxxxxxxlastinvoic;
		this.z9xxzvlplvxxxxxxxxxxlastpaymq = z9xxzvlplvxxxxxxxxxxlastpaymq;
		this.zaxxzzprhvxxxxxxxxxxprintmstat = zaxxzzprhvxxxxxxxxxxprintmstat;
		this.zbxxczqxlhxxxxxxxxxxprinmtfldt = zbxxczqxlhxxxxxxxxxxprinmtfldt;
		this.y4xxfxxrbvxxxxxxxxxxshiplabel = y4xxfxxrbvxxxxxxxxxxshiplabel;
		this.y5xxuxxrbv29xxxxxxxxtype = y5xxuxxrbv29xxxxxxxxtype;
		this.o1xxuwmrbv40xxxxxxxxintegrset = o1xxuwmrbv40xxxxxxxxintegrset;
		this.zdxxzzfxhhxxxxxxxxxxstatusfl = zdxxzzfxhhxxxxxxxxxxstatusfl;
		this.zexxcztxlxxxxxxxxxxxstatusfldt = zexxcztxlxxxxxxxxxxxstatusfldt;
		this.zfxxzxxrlvxxxxxxxxxxtotlpaid = zfxxzxxrlvxxxxxxxxxxtotlpaid;
		this.o3xxuxxrbvxxxxxxxxxxcontacted = o3xxuxxrbvxxxxxxxxxxcontacted;
		this.o4xxuxxrbvxxxxxxxxxxbywho = o4xxuxxrbvxxxxxxxxxxbywho;
		this.o5xxuzkybvxxxxxxxxxxkeywords = o5xxuzkybvxxxxxxxxxxkeywords;
		this.y7xxuznxbvxxxxxxxxxxnotes = y7xxuznxbvxxxxxxxxxxnotes;
		this.zhxxutoxlhxxxxxxxxxxowner = zhxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.ycxxuzdrbvxxxxxxxxxxdocmnt = ycxxuzdrbvxxxxxxxxxxdocmnt;
		this.trexuq333xwwqqhxxxxxvenquotes = trexuq333xwwqqhxxxxxvenquotes;
		this.trexuq344xwwqqhxxxxxvendorderses = trexuq344xwwqqhxxxxxvendorderses;
		this.trexuq388xwwqqhxxxxxvpayments = trexuq388xwwqqhxxxxxvpayments;
		this.xoxxuq454xwwqqhxxxxxemplodetailses = xoxxuq454xwwqqhxxxxxemplodetailses;
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
		this.trexuq377xwwqqhxxxxxvshipmens = trexuq377xwwqqhxxxxxvshipmens;
		this.xoxxuq2a4xwwqqhxxxxxcuidetailses = xoxxuq2a4xwwqqhxxxxxcuidetailses;
		this.trxxuq9aaxwwqqhefxxxjobassignments = trxxuq9aaxwwqqhefxxxjobassignments;
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
		this.xoxxuq3b4xwwqqhxxxxxvendpdetailses = xoxxuq3b4xwwqqhxxxxxvendpdetailses;
		this.fxxxuq89bxwwqqhxxxxxschedules = fxxxuq89bxwwqqhxxxxxschedules;
		this.xoxxuq2b4xwwqqhxxxxxcuodetailses = xoxxuq2b4xwwqqhxxxxxcuodetailses;
		this.jxxxuq31bxwwqqhxxxxxvcontacts = jxxxuq31bxwwqqhxxxxxvcontacts;
		this.yxxxuh566xwwqqwxxxxxusers = yxxxuh566xwwqqwxxxxxusers;
		this.txxxuq366xwwqqhxxxxxvenarthas = txxxuq366xwwqqhxxxxxvenarthas;
		this.xorxeh8cexwwqqhxxxxxscheduledetailses = xorxeh8cexwwqqhxxxxxscheduledetailses;
		this.trexuq3a6xwwqqhxxxxxvinvoices = trexuq3a6xwwqqhxxxxxvinvoices;
		this.trexuq255xwwqqhxxxxxshipmentsForCarrier = trexuq255xwwqqhxxxxxshipmentsForCarrier;
		this.xoxxuq2c4xwwqqhxxxxxcuqdetailses = xoxxuq2c4xwwqqhxxxxxcuqdetailses;
		this.trexuq255xwwqqhxxxxxshipmentsForShipper = trexuq255xwwqqhxxxxxshipmentsForShipper;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public Fxxxcq144xwwqqhxxxxxlocation getFxxxcq144xwwqqhxxxxxlocation() {
		return this.fxxxcq144xwwqqhxxxxxlocation;
	}

	public void setFxxxcq144xwwqqhxxxxxlocation(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailtocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByMailtocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByMailtocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "defaultglac")
	public Yxxxch601xwwqqhxxxxxaccount getYxxxch601xwwqqhxxxxxaccount() {
		return this.yxxxch601xwwqqhxxxxxaccount;
	}

	public void setYxxxch601xwwqqhxxxxxaccount(
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount) {
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companycode")
	public Dxxxch1d3xwwqqhxxlxxcompany getDxxxch1d3xwwqqhxxlxxcompany() {
		return this.dxxxch1d3xwwqqhxxlxxcompany;
	}

	public void setDxxxch1d3xwwqqhxxlxxcompany(
			Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany) {
		this.dxxxch1d3xwwqqhxxlxxcompany = dxxxch1d3xwwqqhxxlxxcompany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shiptocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByShiptocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByShiptocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	@Column(name = "vendor", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukxxbvxxxxxxxxxxvendor() {
		return this.a0xxukxxbvxxxxxxxxxxvendor;
	}

	public void setA0xxukxxbvxxxxxxxxxxvendor(String a0xxukxxbvxxxxxxxxxxvendor) {
		this.a0xxukxxbvxxxxxxxxxxvendor = a0xxukxxbvxxxxxxxxxxvendor;
	}

	@Column(name = "descript", length = 60)
	@Size(max = 60)
	public String getY0xxuzsxbvxxxxxxxxxxdescript() {
		return this.y0xxuzsxbvxxxxxxxxxxdescript;
	}

	public void setY0xxuzsxbvxxxxxxxxxxdescript(
			String y0xxuzsxbvxxxxxxxxxxdescript) {
		this.y0xxuzsxbvxxxxxxxxxxdescript = y0xxuzsxbvxxxxxxxxxxdescript;
	}

	@Column(name = "title", length = 20)
	@Size(max = 20)
	public String getB1xxuxxrbv21xxxxxxxxtitle() {
		return this.b1xxuxxrbv21xxxxxxxxtitle;
	}

	public void setB1xxuxxrbv21xxxxxxxxtitle(String b1xxuxxrbv21xxxxxxxxtitle) {
		this.b1xxuxxrbv21xxxxxxxxtitle = b1xxuxxrbv21xxxxxxxxtitle;
	}

	@Column(name = "jobtitle", length = 20)
	@Size(max = 20)
	public String getB2xxuxxrbv22xxxxxxxxjobtitle() {
		return this.b2xxuxxrbv22xxxxxxxxjobtitle;
	}

	public void setB2xxuxxrbv22xxxxxxxxjobtitle(
			String b2xxuxxrbv22xxxxxxxxjobtitle) {
		this.b2xxuxxrbv22xxxxxxxxjobtitle = b2xxuxxrbv22xxxxxxxxjobtitle;
	}

	@Column(name = "lastname", length = 25)
	@Size(max = 25)
	public String getB3xxuslnbvxxxxxxxxxxlastname() {
		return this.b3xxuslnbvxxxxxxxxxxlastname;
	}

	public void setB3xxuslnbvxxxxxxxxxxlastname(
			String b3xxuslnbvxxxxxxxxxxlastname) {
		this.b3xxuslnbvxxxxxxxxxxlastname = b3xxuslnbvxxxxxxxxxxlastname;
	}

	@Column(name = "firstname", length = 25)
	@Size(max = 25)
	public String getB4xxu2fnbvxxxxxxxxxxfirstname() {
		return this.b4xxu2fnbvxxxxxxxxxxfirstname;
	}

	public void setB4xxu2fnbvxxxxxxxxxxfirstname(
			String b4xxu2fnbvxxxxxxxxxxfirstname) {
		this.b4xxu2fnbvxxxxxxxxxxfirstname = b4xxu2fnbvxxxxxxxxxxfirstname;
	}

	@Column(name = "middlenam", length = 20)
	@Size(max = 20)
	public String getB5xxuxxrbvxxxxxxxxxxmiddlenam() {
		return this.b5xxuxxrbvxxxxxxxxxxmiddlenam;
	}

	public void setB5xxuxxrbvxxxxxxxxxxmiddlenam(
			String b5xxuxxrbvxxxxxxxxxxmiddlenam) {
		this.b5xxuxxrbvxxxxxxxxxxmiddlenam = b5xxuxxrbvxxxxxxxxxxmiddlenam;
	}

	@Column(name = "vendorascompanyname", length = 25)
	@Size(max = 25)
	public String getD1xxu3cnbvxxxxxxxxxxvendorascompanyname() {
		return this.d1xxu3cnbvxxxxxxxxxxvendorascompanyname;
	}

	public void setD1xxu3cnbvxxxxxxxxxxvendorascompanyname(
			String d1xxu3cnbvxxxxxxxxxxvendorascompanyname) {
		this.d1xxu3cnbvxxxxxxxxxxvendorascompanyname = d1xxu3cnbvxxxxxxxxxxvendorascompanyname;
	}

	@Column(name = "vendtotl", precision = 14)
	public BigDecimal getZ1xxzvpxlvxxxxxxxxxxvendtotl() {
		return this.z1xxzvpxlvxxxxxxxxxxvendtotl;
	}

	public void setZ1xxzvpxlvxxxxxxxxxxvendtotl(
			BigDecimal z1xxzvpxlvxxxxxxxxxxvendtotl) {
		this.z1xxzvpxlvxxxxxxxxxxvendtotl = z1xxzvpxlvxxxxxxxxxxvendtotl;
	}

	@Column(name = "vendtqty", precision = 14)
	public BigDecimal getZ2xxzvpxlvxxxxxxxxxxvendtqty() {
		return this.z2xxzvpxlvxxxxxxxxxxvendtqty;
	}

	public void setZ2xxzvpxlvxxxxxxxxxxvendtqty(
			BigDecimal z2xxzvpxlvxxxxxxxxxxvendtqty) {
		this.z2xxzvpxlvxxxxxxxxxxvendtqty = z2xxzvpxlvxxxxxxxxxxvendtqty;
	}

	@Column(name = "phoneo", length = 30)
	@Size(max = 30)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM1xxh4pobv27xxxxxxxxphoneo() {
		return this.m1xxh4pobv27xxxxxxxxphoneo;
	}

	public void setM1xxh4pobv27xxxxxxxxphoneo(String m1xxh4pobv27xxxxxxxxphoneo) {
		this.m1xxh4pobv27xxxxxxxxphoneo = m1xxh4pobv27xxxxxxxxphoneo;
	}

	@Column(name = "phoneh", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM2xxh5phbv27xxxxxxxxphoneh() {
		return this.m2xxh5phbv27xxxxxxxxphoneh;
	}

	public void setM2xxh5phbv27xxxxxxxxphoneh(String m2xxh5phbv27xxxxxxxxphoneh) {
		this.m2xxh5phbv27xxxxxxxxphoneh = m2xxh5phbv27xxxxxxxxphoneh;
	}

	@Column(name = "phonec", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM3xxhxxrbv27xxxxxxxxphonec() {
		return this.m3xxhxxrbv27xxxxxxxxphonec;
	}

	public void setM3xxhxxrbv27xxxxxxxxphonec(String m3xxhxxrbv27xxxxxxxxphonec) {
		this.m3xxhxxrbv27xxxxxxxxphonec = m3xxhxxrbv27xxxxxxxxphonec;
	}

	@Column(name = "phonex", length = 30)
	@Size(max = 30)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getM4xxhxxrbv27xxxxxxxxphonex() {
		return this.m4xxhxxrbv27xxxxxxxxphonex;
	}

	public void setM4xxhxxrbv27xxxxxxxxphonex(String m4xxhxxrbv27xxxxxxxxphonex) {
		this.m4xxhxxrbv27xxxxxxxxphonex = m4xxhxxrbv27xxxxxxxxphonex;
	}

	@Column(name = "lanaddr", length = 35)
	@Size(max = 35)
	public String getN1xxhxxrbv19xxxxxxxxlanaddr() {
		return this.n1xxhxxrbv19xxxxxxxxlanaddr;
	}

	public void setN1xxhxxrbv19xxxxxxxxlanaddr(
			String n1xxhxxrbv19xxxxxxxxlanaddr) {
		this.n1xxhxxrbv19xxxxxxxxlanaddr = n1xxhxxrbv19xxxxxxxxlanaddr;
	}

	@Column(name = "wanaddr", length = 35)
	@Size(max = 35)
	public String getN2xxhxxrbv25xxxxxxxxwanaddr() {
		return this.n2xxhxxrbv25xxxxxxxxwanaddr;
	}

	public void setN2xxhxxrbv25xxxxxxxxwanaddr(
			String n2xxhxxrbv25xxxxxxxxwanaddr) {
		this.n2xxhxxrbv25xxxxxxxxwanaddr = n2xxhxxrbv25xxxxxxxxwanaddr;
	}

	@Column(name = "lmailaddr", length = 35)
	@Size(max = 35)
	public String getN3xxhxxrbv44xxxxxxxxlmailaddr() {
		return this.n3xxhxxrbv44xxxxxxxxlmailaddr;
	}

	public void setN3xxhxxrbv44xxxxxxxxlmailaddr(
			String n3xxhxxrbv44xxxxxxxxlmailaddr) {
		this.n3xxhxxrbv44xxxxxxxxlmailaddr = n3xxhxxrbv44xxxxxxxxlmailaddr;
	}

	@Column(name = "imailaddr", length = 60)
	@Size(max = 60)
	@Pattern.List({
			@Pattern(regexp = "(^$|.+@.+\\..+)", message = "Bad email value"),
			@Pattern(regexp = "(^$)|(^\\S+$)", message = "email has space character")})
	public String getN4xxhxxrbv24xxxxxxxximailaddr() {
		return this.n4xxhxxrbv24xxxxxxxximailaddr;
	}

	public void setN4xxhxxrbv24xxxxxxxximailaddr(
			String n4xxhxxrbv24xxxxxxxximailaddr) {
		this.n4xxhxxrbv24xxxxxxxximailaddr = n4xxhxxrbv24xxxxxxxximailaddr;
	}

	@Column(name = "rmailaddr", length = 35)
	@Size(max = 35)
	public String getN5xxuxxrbvxxxxxxxxxxrmailaddr() {
		return this.n5xxuxxrbvxxxxxxxxxxrmailaddr;
	}

	public void setN5xxuxxrbvxxxxxxxxxxrmailaddr(
			String n5xxuxxrbvxxxxxxxxxxrmailaddr) {
		this.n5xxuxxrbvxxxxxxxxxxrmailaddr = n5xxuxxrbvxxxxxxxxxxrmailaddr;
	}

	@Column(name = "intaddr", length = 60)
	@Size(max = 60)
	public String getN6xxuxxrbvxxxxxxxxxxintaddr() {
		return this.n6xxuxxrbvxxxxxxxxxxintaddr;
	}

	public void setN6xxuxxrbvxxxxxxxxxxintaddr(
			String n6xxuxxrbvxxxxxxxxxxintaddr) {
		this.n6xxuxxrbvxxxxxxxxxxintaddr = n6xxuxxrbvxxxxxxxxxxintaddr;
	}

	@Column(name = "inraddr", length = 35)
	@Size(max = 35)
	public String getN7xxuxxrbvxxxxxxxxxxinraddr() {
		return this.n7xxuxxrbvxxxxxxxxxxinraddr;
	}

	public void setN7xxuxxrbvxxxxxxxxxxinraddr(
			String n7xxuxxrbvxxxxxxxxxxinraddr) {
		this.n7xxuxxrbvxxxxxxxxxxinraddr = n7xxuxxrbvxxxxxxxxxxinraddr;
	}

	@Column(name = "venrtotl", precision = 14)
	public BigDecimal getZ3xxzvrplvxxxxxxxxxxvenrtotl() {
		return this.z3xxzvrplvxxxxxxxxxxvenrtotl;
	}

	public void setZ3xxzvrplvxxxxxxxxxxvenrtotl(
			BigDecimal z3xxzvrplvxxxxxxxxxxvenrtotl) {
		this.z3xxzvrplvxxxxxxxxxxvenrtotl = z3xxzvrplvxxxxxxxxxxvenrtotl;
	}

	@Column(name = "venrtqty", precision = 14)
	public BigDecimal getZ4xxzvrqlvxxxxxxxxxxvenrtqty() {
		return this.z4xxzvrqlvxxxxxxxxxxvenrtqty;
	}

	public void setZ4xxzvrqlvxxxxxxxxxxvenrtqty(
			BigDecimal z4xxzvrqlvxxxxxxxxxxvenrtqty) {
		this.z4xxzvrqlvxxxxxxxxxxvenrtqty = z4xxzvrqlvxxxxxxxxxxvenrtqty;
	}

	@Column(name = "venmtotl", precision = 14)
	public BigDecimal getZ5xxzvmplvxxxxxxxxxxvenmtotl() {
		return this.z5xxzvmplvxxxxxxxxxxvenmtotl;
	}

	public void setZ5xxzvmplvxxxxxxxxxxvenmtotl(
			BigDecimal z5xxzvmplvxxxxxxxxxxvenmtotl) {
		this.z5xxzvmplvxxxxxxxxxxvenmtotl = z5xxzvmplvxxxxxxxxxxvenmtotl;
	}

	@Column(name = "venddtotl", precision = 14)
	public BigDecimal getZ6xxzvdplvxxxxxxxxxxvenddtotl() {
		return this.z6xxzvdplvxxxxxxxxxxvenddtotl;
	}

	public void setZ6xxzvdplvxxxxxxxxxxvenddtotl(
			BigDecimal z6xxzvdplvxxxxxxxxxxvenddtotl) {
		this.z6xxzvdplvxxxxxxxxxxvenddtotl = z6xxzvdplvxxxxxxxxxxvenddtotl;
	}

	@Column(name = "lastquote", length = 20)
	@Size(max = 20)
	public String getZ7xxuvlqlvxxxxxxxxxxlastquote() {
		return this.z7xxuvlqlvxxxxxxxxxxlastquote;
	}

	public void setZ7xxuvlqlvxxxxxxxxxxlastquote(
			String z7xxuvlqlvxxxxxxxxxxlastquote) {
		this.z7xxuvlqlvxxxxxxxxxxlastquote = z7xxuvlqlvxxxxxxxxxxlastquote;
	}

	@Column(name = "lastorder", length = 20)
	@Size(max = 20)
	public String getZ7xxuvlolvxxxxxxxxxxlastorder() {
		return this.z7xxuvlolvxxxxxxxxxxlastorder;
	}

	public void setZ7xxuvlolvxxxxxxxxxxlastorder(
			String z7xxuvlolvxxxxxxxxxxlastorder) {
		this.z7xxuvlolvxxxxxxxxxxlastorder = z7xxuvlolvxxxxxxxxxxlastorder;
	}

	@Column(name = "lastinvoic", length = 20)
	@Size(max = 20)
	public String getZ8xxuvlilvxxxxxxxxxxlastinvoic() {
		return this.z8xxuvlilvxxxxxxxxxxlastinvoic;
	}

	public void setZ8xxuvlilvxxxxxxxxxxlastinvoic(
			String z8xxuvlilvxxxxxxxxxxlastinvoic) {
		this.z8xxuvlilvxxxxxxxxxxlastinvoic = z8xxuvlilvxxxxxxxxxxlastinvoic;
	}

	@Column(name = "lastpaymq", precision = 14)
	public BigDecimal getZ9xxzvlplvxxxxxxxxxxlastpaymq() {
		return this.z9xxzvlplvxxxxxxxxxxlastpaymq;
	}

	public void setZ9xxzvlplvxxxxxxxxxxlastpaymq(
			BigDecimal z9xxzvlplvxxxxxxxxxxlastpaymq) {
		this.z9xxzvlplvxxxxxxxxxxlastpaymq = z9xxzvlplvxxxxxxxxxxlastpaymq;
	}

	@Column(name = "printmstat")
	public Integer getZaxxzzprhvxxxxxxxxxxprintmstat() {
		return this.zaxxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZaxxzzprhvxxxxxxxxxxprintmstat(
			Integer zaxxzzprhvxxxxxxxxxxprintmstat) {
		this.zaxxzzprhvxxxxxxxxxxprintmstat = zaxxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZbxxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.zbxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZbxxczqxlhxxxxxxxxxxprinmtfldt(
			Date zbxxczqxlhxxxxxxxxxxprinmtfldt) {
		this.zbxxczqxlhxxxxxxxxxxprinmtfldt = zbxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "shiplabel")
	public Boolean getY4xxfxxrbvxxxxxxxxxxshiplabel() {
		return this.y4xxfxxrbvxxxxxxxxxxshiplabel;
	}

	public void setY4xxfxxrbvxxxxxxxxxxshiplabel(
			Boolean y4xxfxxrbvxxxxxxxxxxshiplabel) {
		this.y4xxfxxrbvxxxxxxxxxxshiplabel = y4xxfxxrbvxxxxxxxxxxshiplabel;
	}

	@Column(name = "type", length = 10)
	@Size(max = 10)
	public String getY5xxuxxrbv29xxxxxxxxtype() {
		return this.y5xxuxxrbv29xxxxxxxxtype;
	}

	public void setY5xxuxxrbv29xxxxxxxxtype(String y5xxuxxrbv29xxxxxxxxtype) {
		this.y5xxuxxrbv29xxxxxxxxtype = y5xxuxxrbv29xxxxxxxxtype;
	}

	@Column(name = "integrset", length = 20)
	@Size(max = 20)
	public String getO1xxuwmrbv40xxxxxxxxintegrset() {
		return this.o1xxuwmrbv40xxxxxxxxintegrset;
	}

	public void setO1xxuwmrbv40xxxxxxxxintegrset(
			String o1xxuwmrbv40xxxxxxxxintegrset) {
		this.o1xxuwmrbv40xxxxxxxxintegrset = o1xxuwmrbv40xxxxxxxxintegrset;
	}

	@Column(name = "statusfl")
	public Integer getZdxxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zdxxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZdxxzzfxhhxxxxxxxxxxstatusfl(
			Integer zdxxzzfxhhxxxxxxxxxxstatusfl) {
		this.zdxxzzfxhhxxxxxxxxxxstatusfl = zdxxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZexxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zexxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZexxcztxlxxxxxxxxxxxstatusfldt(
			Date zexxcztxlxxxxxxxxxxxstatusfldt) {
		this.zexxcztxlxxxxxxxxxxxstatusfldt = zexxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "totlpaid", precision = 14)
	public BigDecimal getZfxxzxxrlvxxxxxxxxxxtotlpaid() {
		return this.zfxxzxxrlvxxxxxxxxxxtotlpaid;
	}

	public void setZfxxzxxrlvxxxxxxxxxxtotlpaid(
			BigDecimal zfxxzxxrlvxxxxxxxxxxtotlpaid) {
		this.zfxxzxxrlvxxxxxxxxxxtotlpaid = zfxxzxxrlvxxxxxxxxxxtotlpaid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contacted", length = 29)
	public Date getO3xxuxxrbvxxxxxxxxxxcontacted() {
		return this.o3xxuxxrbvxxxxxxxxxxcontacted;
	}

	public void setO3xxuxxrbvxxxxxxxxxxcontacted(
			Date o3xxuxxrbvxxxxxxxxxxcontacted) {
		this.o3xxuxxrbvxxxxxxxxxxcontacted = o3xxuxxrbvxxxxxxxxxxcontacted;
	}

	@Column(name = "bywho", length = 20)
	@Size(max = 20)
	public String getO4xxuxxrbvxxxxxxxxxxbywho() {
		return this.o4xxuxxrbvxxxxxxxxxxbywho;
	}

	public void setO4xxuxxrbvxxxxxxxxxxbywho(String o4xxuxxrbvxxxxxxxxxxbywho) {
		this.o4xxuxxrbvxxxxxxxxxxbywho = o4xxuxxrbvxxxxxxxxxxbywho;
	}

	@Column(name = "keywords", length = 30)
	@Size(max = 30)
	public String getO5xxuzkybvxxxxxxxxxxkeywords() {
		return this.o5xxuzkybvxxxxxxxxxxkeywords;
	}

	public void setO5xxuzkybvxxxxxxxxxxkeywords(
			String o5xxuzkybvxxxxxxxxxxkeywords) {
		this.o5xxuzkybvxxxxxxxxxxkeywords = o5xxuzkybvxxxxxxxxxxkeywords;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY7xxuznxbvxxxxxxxxxxnotes() {
		return this.y7xxuznxbvxxxxxxxxxxnotes;
	}

	public void setY7xxuznxbvxxxxxxxxxxnotes(String y7xxuznxbvxxxxxxxxxxnotes) {
		this.y7xxuznxbvxxxxxxxxxxnotes = y7xxuznxbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZhxxutoxlhxxxxxxxxxxowner() {
		return this.zhxxutoxlhxxxxxxxxxxowner;
	}

	public void setZhxxutoxlhxxxxxxxxxxowner(String zhxxutoxlhxxxxxxxxxxowner) {
		this.zhxxutoxlhxxxxxxxxxxowner = zhxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "docmnt", length = 90)
	@Size(max = 90)
	public String getYcxxuzdrbvxxxxxxxxxxdocmnt() {
		return this.ycxxuzdrbvxxxxxxxxxxdocmnt;
	}

	public void setYcxxuzdrbvxxxxxxxxxxdocmnt(String ycxxuzdrbvxxxxxxxxxxdocmnt) {
		this.ycxxuzdrbvxxxxxxxxxxdocmnt = ycxxuzdrbvxxxxxxxxxxdocmnt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Trexuq333xwwqqhxxxxxvenquote> getTrexuq333xwwqqhxxxxxvenquotes() {
		return this.trexuq333xwwqqhxxxxxvenquotes;
	}

	public void setTrexuq333xwwqqhxxxxxvenquotes(
			Set<Trexuq333xwwqqhxxxxxvenquote> trexuq333xwwqqhxxxxxvenquotes) {
		this.trexuq333xwwqqhxxxxxvenquotes = trexuq333xwwqqhxxxxxvenquotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Trexuq344xwwqqhxxxxxvendorders> getTrexuq344xwwqqhxxxxxvendorderses() {
		return this.trexuq344xwwqqhxxxxxvendorderses;
	}

	public void setTrexuq344xwwqqhxxxxxvendorderses(
			Set<Trexuq344xwwqqhxxxxxvendorders> trexuq344xwwqqhxxxxxvendorderses) {
		this.trexuq344xwwqqhxxxxxvendorderses = trexuq344xwwqqhxxxxxvendorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Trexuq388xwwqqhxxxxxvpayment> getTrexuq388xwwqqhxxxxxvpayments() {
		return this.trexuq388xwwqqhxxxxxvpayments;
	}

	public void setTrexuq388xwwqqhxxxxxvpayments(
			Set<Trexuq388xwwqqhxxxxxvpayment> trexuq388xwwqqhxxxxxvpayments) {
		this.trexuq388xwwqqhxxxxxvpayments = trexuq388xwwqqhxxxxxvpayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xoxxuq454xwwqqhxxxxxemplodetails> getXoxxuq454xwwqqhxxxxxemplodetailses() {
		return this.xoxxuq454xwwqqhxxxxxemplodetailses;
	}

	public void setXoxxuq454xwwqqhxxxxxemplodetailses(
			Set<Xoxxuq454xwwqqhxxxxxemplodetails> xoxxuq454xwwqqhxxxxxemplodetailses) {
		this.xoxxuq454xwwqqhxxxxxemplodetailses = xoxxuq454xwwqqhxxxxxemplodetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Jxxxuq54exwwqqhxxxxxgroupmembers> getJxxxuq54exwwqqhxxxxxgroupmemberses() {
		return this.jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	public void setJxxxuq54exwwqqhxxxxxgroupmemberses(
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses) {
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Trexuq377xwwqqhxxxxxvshipmen> getTrexuq377xwwqqhxxxxxvshipmens() {
		return this.trexuq377xwwqqhxxxxxvshipmens;
	}

	public void setTrexuq377xwwqqhxxxxxvshipmens(
			Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens) {
		this.trexuq377xwwqqhxxxxxvshipmens = trexuq377xwwqqhxxxxxvshipmens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> getXoxxuq2a4xwwqqhxxxxxcuidetailses() {
		return this.xoxxuq2a4xwwqqhxxxxxcuidetailses;
	}

	public void setXoxxuq2a4xwwqqhxxxxxcuidetailses(
			Set<Xoxxuq2a4xwwqqhxxxxxcuidetails> xoxxuq2a4xwwqqhxxxxxcuidetailses) {
		this.xoxxuq2a4xwwqqhxxxxxcuidetailses = xoxxuq2a4xwwqqhxxxxxcuidetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Trxxuq9aaxwwqqhefxxxjobassignment> getTrxxuq9aaxwwqqhefxxxjobassignments() {
		return this.trxxuq9aaxwwqqhefxxxjobassignments;
	}

	public void setTrxxuq9aaxwwqqhefxxxjobassignments(
			Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments) {
		this.trxxuq9aaxwwqqhefxxxjobassignments = trxxuq9aaxwwqqhefxxxjobassignments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> getXoxxuq9bfxwwqqhexxxxjobassignmentdetailses() {
		return this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	public void setXoxxuq9bfxwwqqhexxxxjobassignmentdetailses(
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses) {
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> getXoxxuq3b4xwwqqhxxxxxvendpdetailses() {
		return this.xoxxuq3b4xwwqqhxxxxxvendpdetailses;
	}

	public void setXoxxuq3b4xwwqqhxxxxxvendpdetailses(
			Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> xoxxuq3b4xwwqqhxxxxxvendpdetailses) {
		this.xoxxuq3b4xwwqqhxxxxxvendpdetailses = xoxxuq3b4xwwqqhxxxxxvendpdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Fxxxuq89bxwwqqhxxxxxschedule> getFxxxuq89bxwwqqhxxxxxschedules() {
		return this.fxxxuq89bxwwqqhxxxxxschedules;
	}

	public void setFxxxuq89bxwwqqhxxxxxschedules(
			Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules) {
		this.fxxxuq89bxwwqqhxxxxxschedules = fxxxuq89bxwwqqhxxxxxschedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> getXoxxuq2b4xwwqqhxxxxxcuodetailses() {
		return this.xoxxuq2b4xwwqqhxxxxxcuodetailses;
	}

	public void setXoxxuq2b4xwwqqhxxxxxcuodetailses(
			Set<Xoxxuq2b4xwwqqhxxxxxcuodetails> xoxxuq2b4xwwqqhxxxxxcuodetailses) {
		this.xoxxuq2b4xwwqqhxxxxxcuodetailses = xoxxuq2b4xwwqqhxxxxxcuodetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Jxxxuq31bxwwqqhxxxxxvcontact> getJxxxuq31bxwwqqhxxxxxvcontacts() {
		return this.jxxxuq31bxwwqqhxxxxxvcontacts;
	}

	public void setJxxxuq31bxwwqqhxxxxxvcontacts(
			Set<Jxxxuq31bxwwqqhxxxxxvcontact> jxxxuq31bxwwqqhxxxxxvcontacts) {
		this.jxxxuq31bxwwqqhxxxxxvcontacts = jxxxuq31bxwwqqhxxxxxvcontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Yxxxuh566xwwqqwxxxxxuser> getYxxxuh566xwwqqwxxxxxusers() {
		return this.yxxxuh566xwwqqwxxxxxusers;
	}

	public void setYxxxuh566xwwqqwxxxxxusers(
			Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers) {
		this.yxxxuh566xwwqqwxxxxxusers = yxxxuh566xwwqqwxxxxxusers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Txxxuq366xwwqqhxxxxxvenartha> getTxxxuq366xwwqqhxxxxxvenarthas() {
		return this.txxxuq366xwwqqhxxxxxvenarthas;
	}

	public void setTxxxuq366xwwqqhxxxxxvenarthas(
			Set<Txxxuq366xwwqqhxxxxxvenartha> txxxuq366xwwqqhxxxxxvenarthas) {
		this.txxxuq366xwwqqhxxxxxvenarthas = txxxuq366xwwqqhxxxxxvenarthas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xorxeh8cexwwqqhxxxxxscheduledetails> getXorxeh8cexwwqqhxxxxxscheduledetailses() {
		return this.xorxeh8cexwwqqhxxxxxscheduledetailses;
	}

	public void setXorxeh8cexwwqqhxxxxxscheduledetailses(
			Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses) {
		this.xorxeh8cexwwqqhxxxxxscheduledetailses = xorxeh8cexwwqqhxxxxxscheduledetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Trexuq3a6xwwqqhxxxxxvinvoice> getTrexuq3a6xwwqqhxxxxxvinvoices() {
		return this.trexuq3a6xwwqqhxxxxxvinvoices;
	}

	public void setTrexuq3a6xwwqqhxxxxxvinvoices(
			Set<Trexuq3a6xwwqqhxxxxxvinvoice> trexuq3a6xwwqqhxxxxxvinvoices) {
		this.trexuq3a6xwwqqhxxxxxvinvoices = trexuq3a6xwwqqhxxxxxvinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendorByCarrier")
	public Set<Trexuq255xwwqqhxxxxxshipment> getTrexuq255xwwqqhxxxxxshipmentsForCarrier() {
		return this.trexuq255xwwqqhxxxxxshipmentsForCarrier;
	}

	public void setTrexuq255xwwqqhxxxxxshipmentsForCarrier(
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipmentsForCarrier) {
		this.trexuq255xwwqqhxxxxxshipmentsForCarrier = trexuq255xwwqqhxxxxxshipmentsForCarrier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendor")
	public Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> getXoxxuq2c4xwwqqhxxxxxcuqdetailses() {
		return this.xoxxuq2c4xwwqqhxxxxxcuqdetailses;
	}

	public void setXoxxuq2c4xwwqqhxxxxxcuqdetailses(
			Set<Xoxxuq2c4xwwqqhxxxxxcuqdetails> xoxxuq2c4xwwqqhxxxxxcuqdetailses) {
		this.xoxxuq2c4xwwqqhxxxxxcuqdetailses = xoxxuq2c4xwwqqhxxxxxcuqdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq300xwwqqhxxxxxvendorByShipper")
	public Set<Trexuq255xwwqqhxxxxxshipment> getTrexuq255xwwqqhxxxxxshipmentsForShipper() {
		return this.trexuq255xwwqqhxxxxxshipmentsForShipper;
	}

	public void setTrexuq255xwwqqhxxxxxshipmentsForShipper(
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipmentsForShipper) {
		this.trexuq255xwwqqhxxxxxshipmentsForShipper = trexuq255xwwqqhxxxxxshipmentsForShipper;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
