package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Jxxxuq31bxwwqqhxxxxxvcontact generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "vcontact")
public class Jxxxuq31bxwwqqhxxxxxvcontact implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation;
	private Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	private String a0xxukxxbvxxxxxxxxxxcontact;
	private String b1xxuxxxbv21xxxxxxxxtitle;
	private String b2xxuxxxbv22xxxxxxxxjobtitle;
	private String b3xxuslrbvixxxxxxxxxlastname;
	private String b4xxu3frbvixxxxxxxxxfirstname;
	private String b5xxuxxrbvixxxxxxxxxmiddlenam;
	private String b6xxh4pobv27xxxxxxxxphoneo;
	private String b7xxh5phbv27xxxxxxxxphoneh;
	private String b8xxhxxxbv27xxxxxxxxphonec;
	private String b9xxhxxxbv27xxxxxxxxphonex;
	private String l1xxhxxrbv19xxxxxxxxlanaddr;
	private String l2xxhxxrbv25xxxxxxxxwanaddr;
	private String l3xxhxxrbv44xxxxxxxxlmailaddr;
	private String l4xxhxxrbv24xxxxxxxximailaddr;
	private String l5xxhxxrbvxxxxxxxxxxrmailaddr;
	private String l6xxhxxrbv23xxxxxxxxintaddr;
	private String l7xxuxxrbvxxxxxxxxxxinraddr;
	private Integer z1xxzxxxbvxxxxxxxxxxprintsta;
	private Boolean y1xxfxxrbvxxxxxxxxxxshiplabel;
	private String n1xxuxxrbv29xxxxxxxxtype;
	private Integer z2xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z3xxcztxlxxxxxxxxxxxstatusfldt;
	private String y2xxuzkybvxxxxxxxxxxkeywords;
	private String y3xxuznxbvxxxxxxxxxxnotes;
	private String z4xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String y4xxuzdrbvxxxxxxxxxxdocmnt;

	public Jxxxuq31bxwwqqhxxxxxvcontact() {
	}

	public Jxxxuq31bxwwqqhxxxxxvcontact(String a0xxukxxbvxxxxxxxxxxcontact) {
		this.a0xxukxxbvxxxxxxxxxxcontact = a0xxukxxbvxxxxxxxxxxcontact;
	}
	public Jxxxuq31bxwwqqhxxxxxvcontact(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation,
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode,
			String a0xxukxxbvxxxxxxxxxxcontact,
			String b1xxuxxxbv21xxxxxxxxtitle,
			String b2xxuxxxbv22xxxxxxxxjobtitle,
			String b3xxuslrbvixxxxxxxxxlastname,
			String b4xxu3frbvixxxxxxxxxfirstname,
			String b5xxuxxrbvixxxxxxxxxmiddlenam,
			String b6xxh4pobv27xxxxxxxxphoneo,
			String b7xxh5phbv27xxxxxxxxphoneh,
			String b8xxhxxxbv27xxxxxxxxphonec,
			String b9xxhxxxbv27xxxxxxxxphonex,
			String l1xxhxxrbv19xxxxxxxxlanaddr,
			String l2xxhxxrbv25xxxxxxxxwanaddr,
			String l3xxhxxrbv44xxxxxxxxlmailaddr,
			String l4xxhxxrbv24xxxxxxxximailaddr,
			String l5xxhxxrbvxxxxxxxxxxrmailaddr,
			String l6xxhxxrbv23xxxxxxxxintaddr,
			String l7xxuxxrbvxxxxxxxxxxinraddr,
			Integer z1xxzxxxbvxxxxxxxxxxprintsta,
			Boolean y1xxfxxrbvxxxxxxxxxxshiplabel,
			String n1xxuxxrbv29xxxxxxxxtype,
			Integer z2xxzzfxhhxxxxxxxxxxstatusfl,
			Date z3xxcztxlxxxxxxxxxxxstatusfldt,
			String y2xxuzkybvxxxxxxxxxxkeywords,
			String y3xxuznxbvxxxxxxxxxxnotes, String z4xxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2, String y4xxuzdrbvxxxxxxxxxxdocmnt) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
		this.a0xxukxxbvxxxxxxxxxxcontact = a0xxukxxbvxxxxxxxxxxcontact;
		this.b1xxuxxxbv21xxxxxxxxtitle = b1xxuxxxbv21xxxxxxxxtitle;
		this.b2xxuxxxbv22xxxxxxxxjobtitle = b2xxuxxxbv22xxxxxxxxjobtitle;
		this.b3xxuslrbvixxxxxxxxxlastname = b3xxuslrbvixxxxxxxxxlastname;
		this.b4xxu3frbvixxxxxxxxxfirstname = b4xxu3frbvixxxxxxxxxfirstname;
		this.b5xxuxxrbvixxxxxxxxxmiddlenam = b5xxuxxrbvixxxxxxxxxmiddlenam;
		this.b6xxh4pobv27xxxxxxxxphoneo = b6xxh4pobv27xxxxxxxxphoneo;
		this.b7xxh5phbv27xxxxxxxxphoneh = b7xxh5phbv27xxxxxxxxphoneh;
		this.b8xxhxxxbv27xxxxxxxxphonec = b8xxhxxxbv27xxxxxxxxphonec;
		this.b9xxhxxxbv27xxxxxxxxphonex = b9xxhxxxbv27xxxxxxxxphonex;
		this.l1xxhxxrbv19xxxxxxxxlanaddr = l1xxhxxrbv19xxxxxxxxlanaddr;
		this.l2xxhxxrbv25xxxxxxxxwanaddr = l2xxhxxrbv25xxxxxxxxwanaddr;
		this.l3xxhxxrbv44xxxxxxxxlmailaddr = l3xxhxxrbv44xxxxxxxxlmailaddr;
		this.l4xxhxxrbv24xxxxxxxximailaddr = l4xxhxxrbv24xxxxxxxximailaddr;
		this.l5xxhxxrbvxxxxxxxxxxrmailaddr = l5xxhxxrbvxxxxxxxxxxrmailaddr;
		this.l6xxhxxrbv23xxxxxxxxintaddr = l6xxhxxrbv23xxxxxxxxintaddr;
		this.l7xxuxxrbvxxxxxxxxxxinraddr = l7xxuxxrbvxxxxxxxxxxinraddr;
		this.z1xxzxxxbvxxxxxxxxxxprintsta = z1xxzxxxbvxxxxxxxxxxprintsta;
		this.y1xxfxxrbvxxxxxxxxxxshiplabel = y1xxfxxrbvxxxxxxxxxxshiplabel;
		this.n1xxuxxrbv29xxxxxxxxtype = n1xxuxxrbv29xxxxxxxxtype;
		this.z2xxzzfxhhxxxxxxxxxxstatusfl = z2xxzzfxhhxxxxxxxxxxstatusfl;
		this.z3xxcztxlxxxxxxxxxxxstatusfldt = z3xxcztxlxxxxxxxxxxxstatusfldt;
		this.y2xxuzkybvxxxxxxxxxxkeywords = y2xxuzkybvxxxxxxxxxxkeywords;
		this.y3xxuznxbvxxxxxxxxxxnotes = y3xxuznxbvxxxxxxxxxxnotes;
		this.z4xxutoxlhxxxxxxxxxxowner = z4xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.y4xxuzdrbvxxxxxxxxxxdocmnt = y4xxuzdrbvxxxxxxxxxxdocmnt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public Fxxxcq144xwwqqhxxxxxlocation getFxxxcq144xwwqqhxxxxxlocation() {
		return this.fxxxcq144xwwqqhxxxxxlocation;
	}

	public void setFxxxcq144xwwqqhxxxxxlocation(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor")
	public Jxxxuq300xwwqqhxxxxxvendor getJxxxuq300xwwqqhxxxxxvendor() {
		return this.jxxxuq300xwwqqhxxxxxvendor;
	}

	public void setJxxxuq300xwwqqhxxxxxvendor(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor) {
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailtocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByMailtocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByMailtocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shiptocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByShiptocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByShiptocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	@Column(name = "contact", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getA0xxukxxbvxxxxxxxxxxcontact() {
		return this.a0xxukxxbvxxxxxxxxxxcontact;
	}

	public void setA0xxukxxbvxxxxxxxxxxcontact(
			String a0xxukxxbvxxxxxxxxxxcontact) {
		this.a0xxukxxbvxxxxxxxxxxcontact = a0xxukxxbvxxxxxxxxxxcontact;
	}

	@Column(name = "title", length = 20)
	@Size(max = 20)
	public String getB1xxuxxxbv21xxxxxxxxtitle() {
		return this.b1xxuxxxbv21xxxxxxxxtitle;
	}

	public void setB1xxuxxxbv21xxxxxxxxtitle(String b1xxuxxxbv21xxxxxxxxtitle) {
		this.b1xxuxxxbv21xxxxxxxxtitle = b1xxuxxxbv21xxxxxxxxtitle;
	}

	@Column(name = "jobtitle", length = 20)
	@Size(max = 20)
	public String getB2xxuxxxbv22xxxxxxxxjobtitle() {
		return this.b2xxuxxxbv22xxxxxxxxjobtitle;
	}

	public void setB2xxuxxxbv22xxxxxxxxjobtitle(
			String b2xxuxxxbv22xxxxxxxxjobtitle) {
		this.b2xxuxxxbv22xxxxxxxxjobtitle = b2xxuxxxbv22xxxxxxxxjobtitle;
	}

	@Column(name = "lastname", length = 25)
	@Size(max = 25)
	public String getB3xxuslrbvixxxxxxxxxlastname() {
		return this.b3xxuslrbvixxxxxxxxxlastname;
	}

	public void setB3xxuslrbvixxxxxxxxxlastname(
			String b3xxuslrbvixxxxxxxxxlastname) {
		this.b3xxuslrbvixxxxxxxxxlastname = b3xxuslrbvixxxxxxxxxlastname;
	}

	@Column(name = "firstname", length = 25)
	@Size(max = 25)
	public String getB4xxu3frbvixxxxxxxxxfirstname() {
		return this.b4xxu3frbvixxxxxxxxxfirstname;
	}

	public void setB4xxu3frbvixxxxxxxxxfirstname(
			String b4xxu3frbvixxxxxxxxxfirstname) {
		this.b4xxu3frbvixxxxxxxxxfirstname = b4xxu3frbvixxxxxxxxxfirstname;
	}

	@Column(name = "middlenam", length = 20)
	@Size(max = 20)
	public String getB5xxuxxrbvixxxxxxxxxmiddlenam() {
		return this.b5xxuxxrbvixxxxxxxxxmiddlenam;
	}

	public void setB5xxuxxrbvixxxxxxxxxmiddlenam(
			String b5xxuxxrbvixxxxxxxxxmiddlenam) {
		this.b5xxuxxrbvixxxxxxxxxmiddlenam = b5xxuxxrbvixxxxxxxxxmiddlenam;
	}

	@Column(name = "phoneo", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getB6xxh4pobv27xxxxxxxxphoneo() {
		return this.b6xxh4pobv27xxxxxxxxphoneo;
	}

	public void setB6xxh4pobv27xxxxxxxxphoneo(String b6xxh4pobv27xxxxxxxxphoneo) {
		this.b6xxh4pobv27xxxxxxxxphoneo = b6xxh4pobv27xxxxxxxxphoneo;
	}

	@Column(name = "phoneh", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getB7xxh5phbv27xxxxxxxxphoneh() {
		return this.b7xxh5phbv27xxxxxxxxphoneh;
	}

	public void setB7xxh5phbv27xxxxxxxxphoneh(String b7xxh5phbv27xxxxxxxxphoneh) {
		this.b7xxh5phbv27xxxxxxxxphoneh = b7xxh5phbv27xxxxxxxxphoneh;
	}

	@Column(name = "phonec", length = 25)
	@Size(max = 25)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getB8xxhxxxbv27xxxxxxxxphonec() {
		return this.b8xxhxxxbv27xxxxxxxxphonec;
	}

	public void setB8xxhxxxbv27xxxxxxxxphonec(String b8xxhxxxbv27xxxxxxxxphonec) {
		this.b8xxhxxxbv27xxxxxxxxphonec = b8xxhxxxbv27xxxxxxxxphonec;
	}

	@Column(name = "phonex", length = 20)
	@Size(max = 20)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getB9xxhxxxbv27xxxxxxxxphonex() {
		return this.b9xxhxxxbv27xxxxxxxxphonex;
	}

	public void setB9xxhxxxbv27xxxxxxxxphonex(String b9xxhxxxbv27xxxxxxxxphonex) {
		this.b9xxhxxxbv27xxxxxxxxphonex = b9xxhxxxbv27xxxxxxxxphonex;
	}

	@Column(name = "lanaddr", length = 35)
	@Size(max = 35)
	public String getL1xxhxxrbv19xxxxxxxxlanaddr() {
		return this.l1xxhxxrbv19xxxxxxxxlanaddr;
	}

	public void setL1xxhxxrbv19xxxxxxxxlanaddr(
			String l1xxhxxrbv19xxxxxxxxlanaddr) {
		this.l1xxhxxrbv19xxxxxxxxlanaddr = l1xxhxxrbv19xxxxxxxxlanaddr;
	}

	@Column(name = "wanaddr", length = 35)
	@Size(max = 35)
	public String getL2xxhxxrbv25xxxxxxxxwanaddr() {
		return this.l2xxhxxrbv25xxxxxxxxwanaddr;
	}

	public void setL2xxhxxrbv25xxxxxxxxwanaddr(
			String l2xxhxxrbv25xxxxxxxxwanaddr) {
		this.l2xxhxxrbv25xxxxxxxxwanaddr = l2xxhxxrbv25xxxxxxxxwanaddr;
	}

	@Column(name = "lmailaddr", length = 35)
	@Size(max = 35)
	public String getL3xxhxxrbv44xxxxxxxxlmailaddr() {
		return this.l3xxhxxrbv44xxxxxxxxlmailaddr;
	}

	public void setL3xxhxxrbv44xxxxxxxxlmailaddr(
			String l3xxhxxrbv44xxxxxxxxlmailaddr) {
		this.l3xxhxxrbv44xxxxxxxxlmailaddr = l3xxhxxrbv44xxxxxxxxlmailaddr;
	}

	@Column(name = "imailaddr", length = 60)
	@Size(max = 60)
	@Pattern.List({
			@Pattern(regexp = "(^$|.+@.+\\..+)", message = "Bad email value"),
			@Pattern(regexp = "(^$)|(^\\S+$)", message = "email has space character")})
	public String getL4xxhxxrbv24xxxxxxxximailaddr() {
		return this.l4xxhxxrbv24xxxxxxxximailaddr;
	}

	public void setL4xxhxxrbv24xxxxxxxximailaddr(
			String l4xxhxxrbv24xxxxxxxximailaddr) {
		this.l4xxhxxrbv24xxxxxxxximailaddr = l4xxhxxrbv24xxxxxxxximailaddr;
	}

	@Column(name = "rmailaddr", length = 35)
	@Size(max = 35)
	public String getL5xxhxxrbvxxxxxxxxxxrmailaddr() {
		return this.l5xxhxxrbvxxxxxxxxxxrmailaddr;
	}

	public void setL5xxhxxrbvxxxxxxxxxxrmailaddr(
			String l5xxhxxrbvxxxxxxxxxxrmailaddr) {
		this.l5xxhxxrbvxxxxxxxxxxrmailaddr = l5xxhxxrbvxxxxxxxxxxrmailaddr;
	}

	@Column(name = "intaddr", length = 60)
	@Size(max = 60)
	public String getL6xxhxxrbv23xxxxxxxxintaddr() {
		return this.l6xxhxxrbv23xxxxxxxxintaddr;
	}

	public void setL6xxhxxrbv23xxxxxxxxintaddr(
			String l6xxhxxrbv23xxxxxxxxintaddr) {
		this.l6xxhxxrbv23xxxxxxxxintaddr = l6xxhxxrbv23xxxxxxxxintaddr;
	}

	@Column(name = "inraddr", length = 35)
	@Size(max = 35)
	public String getL7xxuxxrbvxxxxxxxxxxinraddr() {
		return this.l7xxuxxrbvxxxxxxxxxxinraddr;
	}

	public void setL7xxuxxrbvxxxxxxxxxxinraddr(
			String l7xxuxxrbvxxxxxxxxxxinraddr) {
		this.l7xxuxxrbvxxxxxxxxxxinraddr = l7xxuxxrbvxxxxxxxxxxinraddr;
	}

	@Column(name = "printsta")
	public Integer getZ1xxzxxxbvxxxxxxxxxxprintsta() {
		return this.z1xxzxxxbvxxxxxxxxxxprintsta;
	}

	public void setZ1xxzxxxbvxxxxxxxxxxprintsta(
			Integer z1xxzxxxbvxxxxxxxxxxprintsta) {
		this.z1xxzxxxbvxxxxxxxxxxprintsta = z1xxzxxxbvxxxxxxxxxxprintsta;
	}

	@Column(name = "shiplabel")
	public Boolean getY1xxfxxrbvxxxxxxxxxxshiplabel() {
		return this.y1xxfxxrbvxxxxxxxxxxshiplabel;
	}

	public void setY1xxfxxrbvxxxxxxxxxxshiplabel(
			Boolean y1xxfxxrbvxxxxxxxxxxshiplabel) {
		this.y1xxfxxrbvxxxxxxxxxxshiplabel = y1xxfxxrbvxxxxxxxxxxshiplabel;
	}

	@Column(name = "type", length = 12)
	@Size(max = 12)
	public String getN1xxuxxrbv29xxxxxxxxtype() {
		return this.n1xxuxxrbv29xxxxxxxxtype;
	}

	public void setN1xxuxxrbv29xxxxxxxxtype(String n1xxuxxrbv29xxxxxxxxtype) {
		this.n1xxuxxrbv29xxxxxxxxtype = n1xxuxxrbv29xxxxxxxxtype;
	}

	@Column(name = "statusfl")
	public Integer getZ2xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z2xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ2xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z2xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z2xxzzfxhhxxxxxxxxxxstatusfl = z2xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ3xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z3xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ3xxcztxlxxxxxxxxxxxstatusfldt(
			Date z3xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z3xxcztxlxxxxxxxxxxxstatusfldt = z3xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "keywords", length = 30)
	@Size(max = 30)
	public String getY2xxuzkybvxxxxxxxxxxkeywords() {
		return this.y2xxuzkybvxxxxxxxxxxkeywords;
	}

	public void setY2xxuzkybvxxxxxxxxxxkeywords(
			String y2xxuzkybvxxxxxxxxxxkeywords) {
		this.y2xxuzkybvxxxxxxxxxxkeywords = y2xxuzkybvxxxxxxxxxxkeywords;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY3xxuznxbvxxxxxxxxxxnotes() {
		return this.y3xxuznxbvxxxxxxxxxxnotes;
	}

	public void setY3xxuznxbvxxxxxxxxxxnotes(String y3xxuznxbvxxxxxxxxxxnotes) {
		this.y3xxuznxbvxxxxxxxxxxnotes = y3xxuznxbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ4xxutoxlhxxxxxxxxxxowner() {
		return this.z4xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ4xxutoxlhxxxxxxxxxxowner(String z4xxutoxlhxxxxxxxxxxowner) {
		this.z4xxutoxlhxxxxxxxxxxowner = z4xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "docmnt", length = 90)
	@Size(max = 90)
	public String getY4xxuzdrbvxxxxxxxxxxdocmnt() {
		return this.y4xxuzdrbvxxxxxxxxxxdocmnt;
	}

	public void setY4xxuzdrbvxxxxxxxxxxdocmnt(String y4xxuzdrbvxxxxxxxxxxdocmnt) {
		this.y4xxuzdrbvxxxxxxxxxxdocmnt = y4xxuzdrbvxxxxxxxxxxdocmnt;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
