package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Jxxxuq201xwwqqhxxxxxcustomer generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "customer")
public class Jxxxuq201xwwqqhxxxxxcustomer implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	private Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount;
	private Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	private String a0xxukxxbvxxxxxxxxxxcustomer;
	private String y0xxuzsxbvxxxxxxxxxxdescript;
	private String b1xxuxxxbv21xxxxxxxxtitle;
	private String b2xxuxxxbx22xxxxxxxxjobtitle;
	private String c1xxuslnbvixxxxxxxxxlastname;
	private String c2xxu2fnbvixxxxxxxxxfirstname;
	private String c3xxuxxxbxxxxxxxxxxxmiddlenam;
	private String d1xxu3cnbvixxxxxxxxxcustomerascompanyname;
	private BigDecimal z1xxzrpxlexxxxxxxxxxcusttotl;
	private BigDecimal z2xxzrqxlexxxxxxxxxxcusttqty;
	private Boolean y6xxfxz1bvxxxxxxxxxxtax1;
	private Boolean y7xxfxz2bvxxxxxxxxxxtax2;
	private Boolean y8xxfxz3bvxxxxxxxxxxtax3;
	private String y9xxuxz1bv04xxxxxxxxcusttax1;
	private String yaxxuxz2bv05xxxxxxxxcusttax2;
	private String ybxxuxz3xv06xxxxxxxxcusttax3;
	private String p1xxh4pobv27xxxxxxxxphoneo;
	private String p2xxh5phbv27xxxxxxxxphoneh;
	private String p3xxhxxxbv27xxxxxxxxphonec;
	private String p4xxhxxxbx27xxxxxxxxphonex;
	private String q1xxhxxxbx19xxxxxxxxlanaddr;
	private String q2xxhxxxbx25xxxxxxxxwanaddr;
	private String q3xxhxxxbv44xxxxxxxxlmailaddr;
	private String q4xxhxxxbv24xxxxxxxximailaddr;
	private String q5xxuxxxbxxxxxxxxxxxrmailaddr;
	private String q6xxhxxxbx23xxxxxxxxintaddr;
	private String q7xxhxxxbxxxxxxxxxxxinraddr;
	private Date q7xxdxtdbvxxxxxxxxxxdob;
	private String q7xxhxxxbvxxxxxxxxxxplaceofbirth;
	private String q7xxtxsebvxxxxxxxxxxsex;
	private Integer q7xxhxxxlvxxxxxxxxxxage;
	private BigDecimal z1xxzrrplexxxxxxxxxxcusrtotl;
	private BigDecimal z2xxzrrqlexxxxxxxxxxcusrtqty;
	private BigDecimal z3xxzrmplexxxxxxxxxxcusmtotl;
	private BigDecimal z4xxzrdplexxxxxxxxxxcusdtotl;
	private String z5xxutlolexxxxxxxxxxlastorder;
	private String z6xxuxxxbexxxxxxxxxxlastinvoic;
	private BigDecimal z7xxzxxxlexxxxxxxxxxlastpaymnq;
	private Integer z8xxzzprhvxxxxxxxxxxprintmstat;
	private Date z9xxczqxlhxxxxxxxxxxprinmtfldt;
	private Boolean r1xxfxxxbexxxxxxxxxxshiplabel;
	private String f1xxuxxxav28xxxxxxxxtype;
	private String f2xxuwmxbv40xxxxxxxxintegrset;
	private Integer zaxxzzfxhhxxxxxxxxxxstatusfl;
	private Date zbxxcztxlxxxxxxxxxxxstatusfldt;
	private BigDecimal zcxxzxxxlvxxxxxxxxxxtotlpaid;
	private Date ydxxuxxybvxxxxxxxxxxcontacted;
	private String yexxuxxybvxxxxxxxxxxbywho;
	private Date yfxxcxxybvxxxxxxxxxxnxtcontact;
	private String ygxxuxxybv30xxxxxxxxvia;
	private String yhxxuzkybvxxxxxxxxxxkeywords;
	private String yixxuznybvxxxxxxxxxxnotes;
	private String zdxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String ycxxuzdrbvxxxxxxxxxxdocmnt;
	private Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses = new HashSet<Xorxeh8cexwwqqhxxxxxscheduledetails>(
			0);
	private Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses = new HashSet<Trexuq244xwwqqhxxxxxcuorders>(
			0);
	private Set<Txxxuq932xwwqqhspxxxactivityjob> txxxuq932xwwqqhspxxxactivityjobs = new HashSet<Txxxuq932xwwqqhspxxxactivityjob>(
			0);
	private Set<Trexuq277xwwqqhxxxxxcpayment> trexuq277xwwqqhxxxxxcpayments = new HashSet<Trexuq277xwwqqhxxxxxcpayment>(
			0);
	private Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> xxxxuq9ccxwwqqhxxxxxprocessdetailses = new HashSet<Xxxxuq9ccxwwqqhxxxxxprocessdetails>(
			0);
	private Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses = new HashSet<Xoxxuq3c4xwwqqhxxxxxvendidetails>(
			0);
	private Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses = new HashSet<Jxxxuq54exwwqqhxxxxxgroupmembers>(
			0);
	private Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens = new HashSet<Trexuq377xwwqqhxxxxxvshipmen>(
			0);
	private Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipments = new HashSet<Trexuq255xwwqqhxxxxxshipment>(
			0);
	private Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments = new HashSet<Trxxuq9aaxwwqqhefxxxjobassignment>(
			0);
	private Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> xoxxuq3d4xwwqqhxxxxxvendodetailses = new HashSet<Xoxxuq3d4xwwqqhxxxxxvendodetails>(
			0);
	private Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = new HashSet<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails>(
			0);
	private Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices = new HashSet<Trexuq266xwwqqhxxxxxcuinvoice>(
			0);
	private Set<Jxxxuq21bxwwqqhxxxxxccontact> jxxxuq21bxwwqqhxxxxxccontacts = new HashSet<Jxxxuq21bxwwqqhxxxxxccontact>(
			0);
	private Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes = new HashSet<Trexuq233xwwqqhxxxxxcuquote>(
			0);
	private Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers = new HashSet<Yxxxuh566xwwqqwxxxxxuser>(
			0);
	private Set<Dxxxuq92bxwwqqhefxxxitemjob> dxxxuq92bxwwqqhefxxxitemjobs = new HashSet<Dxxxuq92bxwwqqhefxxxitemjob>(
			0);
	private Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> xoxxuq3e4xwwqqhxxxxxvendqdetailses = new HashSet<Xoxxuq3e4xwwqqhxxxxxvendqdetails>(
			0);
	private Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules = new HashSet<Fxxxuq89bxwwqqhxxxxxschedule>(
			0);

	public Jxxxuq201xwwqqhxxxxxcustomer() {
	}

	public Jxxxuq201xwwqqhxxxxxcustomer(String a0xxukxxbvxxxxxxxxxxcustomer) {
		this.a0xxukxxbvxxxxxxxxxxcustomer = a0xxukxxbvxxxxxxxxxxcustomer;
	}
	public Jxxxuq201xwwqqhxxxxxcustomer(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode,
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount,
			Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode,
			String a0xxukxxbvxxxxxxxxxxcustomer,
			String y0xxuzsxbvxxxxxxxxxxdescript,
			String b1xxuxxxbv21xxxxxxxxtitle,
			String b2xxuxxxbx22xxxxxxxxjobtitle,
			String c1xxuslnbvixxxxxxxxxlastname,
			String c2xxu2fnbvixxxxxxxxxfirstname,
			String c3xxuxxxbxxxxxxxxxxxmiddlenam,
			String d1xxu3cnbvixxxxxxxxxcustomerascompanyname,
			BigDecimal z1xxzrpxlexxxxxxxxxxcusttotl,
			BigDecimal z2xxzrqxlexxxxxxxxxxcusttqty,
			Boolean y6xxfxz1bvxxxxxxxxxxtax1,
			Boolean y7xxfxz2bvxxxxxxxxxxtax2,
			Boolean y8xxfxz3bvxxxxxxxxxxtax3,
			String y9xxuxz1bv04xxxxxxxxcusttax1,
			String yaxxuxz2bv05xxxxxxxxcusttax2,
			String ybxxuxz3xv06xxxxxxxxcusttax3,
			String p1xxh4pobv27xxxxxxxxphoneo,
			String p2xxh5phbv27xxxxxxxxphoneh,
			String p3xxhxxxbv27xxxxxxxxphonec,
			String p4xxhxxxbx27xxxxxxxxphonex,
			String q1xxhxxxbx19xxxxxxxxlanaddr,
			String q2xxhxxxbx25xxxxxxxxwanaddr,
			String q3xxhxxxbv44xxxxxxxxlmailaddr,
			String q4xxhxxxbv24xxxxxxxximailaddr,
			String q5xxuxxxbxxxxxxxxxxxrmailaddr,
			String q6xxhxxxbx23xxxxxxxxintaddr,
			String q7xxhxxxbxxxxxxxxxxxinraddr,
			Date q7xxdxtdbvxxxxxxxxxxdob,
			String q7xxhxxxbvxxxxxxxxxxplaceofbirth,
			String q7xxtxsebvxxxxxxxxxxsex,
			Integer q7xxhxxxlvxxxxxxxxxxage,
			BigDecimal z1xxzrrplexxxxxxxxxxcusrtotl,
			BigDecimal z2xxzrrqlexxxxxxxxxxcusrtqty,
			BigDecimal z3xxzrmplexxxxxxxxxxcusmtotl,
			BigDecimal z4xxzrdplexxxxxxxxxxcusdtotl,
			String z5xxutlolexxxxxxxxxxlastorder,
			String z6xxuxxxbexxxxxxxxxxlastinvoic,
			BigDecimal z7xxzxxxlexxxxxxxxxxlastpaymnq,
			Integer z8xxzzprhvxxxxxxxxxxprintmstat,
			Date z9xxczqxlhxxxxxxxxxxprinmtfldt,
			Boolean r1xxfxxxbexxxxxxxxxxshiplabel,
			String f1xxuxxxav28xxxxxxxxtype,
			String f2xxuwmxbv40xxxxxxxxintegrset,
			Integer zaxxzzfxhhxxxxxxxxxxstatusfl,
			Date zbxxcztxlxxxxxxxxxxxstatusfldt,
			BigDecimal zcxxzxxxlvxxxxxxxxxxtotlpaid,
			Date ydxxuxxybvxxxxxxxxxxcontacted,
			String yexxuxxybvxxxxxxxxxxbywho,
			Date yfxxcxxybvxxxxxxxxxxnxtcontact,
			String ygxxuxxybv30xxxxxxxxvia,
			String yhxxuzkybvxxxxxxxxxxkeywords,
			String yixxuznybvxxxxxxxxxxnotes,
			String zdxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String ycxxuzdrbvxxxxxxxxxxdocmnt,
			Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses,
			Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses,
			Set<Txxxuq932xwwqqhspxxxactivityjob> txxxuq932xwwqqhspxxxactivityjobs,
			Set<Trexuq277xwwqqhxxxxxcpayment> trexuq277xwwqqhxxxxxcpayments,
			Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> xxxxuq9ccxwwqqhxxxxxprocessdetailses,
			Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses,
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses,
			Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens,
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipments,
			Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments,
			Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> xoxxuq3d4xwwqqhxxxxxvendodetailses,
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses,
			Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices,
			Set<Jxxxuq21bxwwqqhxxxxxccontact> jxxxuq21bxwwqqhxxxxxccontacts,
			Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes,
			Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers,
			Set<Dxxxuq92bxwwqqhefxxxitemjob> dxxxuq92bxwwqqhefxxxitemjobs,
			Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> xoxxuq3e4xwwqqhxxxxxvendqdetailses,
			Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
		this.dxxxch1d3xwwqqhxxlxxcompany = dxxxch1d3xwwqqhxxlxxcompany;
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
		this.a0xxukxxbvxxxxxxxxxxcustomer = a0xxukxxbvxxxxxxxxxxcustomer;
		this.y0xxuzsxbvxxxxxxxxxxdescript = y0xxuzsxbvxxxxxxxxxxdescript;
		this.b1xxuxxxbv21xxxxxxxxtitle = b1xxuxxxbv21xxxxxxxxtitle;
		this.b2xxuxxxbx22xxxxxxxxjobtitle = b2xxuxxxbx22xxxxxxxxjobtitle;
		this.c1xxuslnbvixxxxxxxxxlastname = c1xxuslnbvixxxxxxxxxlastname;
		this.c2xxu2fnbvixxxxxxxxxfirstname = c2xxu2fnbvixxxxxxxxxfirstname;
		this.c3xxuxxxbxxxxxxxxxxxmiddlenam = c3xxuxxxbxxxxxxxxxxxmiddlenam;
		this.d1xxu3cnbvixxxxxxxxxcustomerascompanyname = d1xxu3cnbvixxxxxxxxxcustomerascompanyname;
		this.z1xxzrpxlexxxxxxxxxxcusttotl = z1xxzrpxlexxxxxxxxxxcusttotl;
		this.z2xxzrqxlexxxxxxxxxxcusttqty = z2xxzrqxlexxxxxxxxxxcusttqty;
		this.y6xxfxz1bvxxxxxxxxxxtax1 = y6xxfxz1bvxxxxxxxxxxtax1;
		this.y7xxfxz2bvxxxxxxxxxxtax2 = y7xxfxz2bvxxxxxxxxxxtax2;
		this.y8xxfxz3bvxxxxxxxxxxtax3 = y8xxfxz3bvxxxxxxxxxxtax3;
		this.y9xxuxz1bv04xxxxxxxxcusttax1 = y9xxuxz1bv04xxxxxxxxcusttax1;
		this.yaxxuxz2bv05xxxxxxxxcusttax2 = yaxxuxz2bv05xxxxxxxxcusttax2;
		this.ybxxuxz3xv06xxxxxxxxcusttax3 = ybxxuxz3xv06xxxxxxxxcusttax3;
		this.p1xxh4pobv27xxxxxxxxphoneo = p1xxh4pobv27xxxxxxxxphoneo;
		this.p2xxh5phbv27xxxxxxxxphoneh = p2xxh5phbv27xxxxxxxxphoneh;
		this.p3xxhxxxbv27xxxxxxxxphonec = p3xxhxxxbv27xxxxxxxxphonec;
		this.p4xxhxxxbx27xxxxxxxxphonex = p4xxhxxxbx27xxxxxxxxphonex;
		this.q1xxhxxxbx19xxxxxxxxlanaddr = q1xxhxxxbx19xxxxxxxxlanaddr;
		this.q2xxhxxxbx25xxxxxxxxwanaddr = q2xxhxxxbx25xxxxxxxxwanaddr;
		this.q3xxhxxxbv44xxxxxxxxlmailaddr = q3xxhxxxbv44xxxxxxxxlmailaddr;
		this.q4xxhxxxbv24xxxxxxxximailaddr = q4xxhxxxbv24xxxxxxxximailaddr;
		this.q5xxuxxxbxxxxxxxxxxxrmailaddr = q5xxuxxxbxxxxxxxxxxxrmailaddr;
		this.q6xxhxxxbx23xxxxxxxxintaddr = q6xxhxxxbx23xxxxxxxxintaddr;
		this.q7xxhxxxbxxxxxxxxxxxinraddr = q7xxhxxxbxxxxxxxxxxxinraddr;
		this.q7xxdxtdbvxxxxxxxxxxdob = q7xxdxtdbvxxxxxxxxxxdob;
		this.q7xxhxxxbvxxxxxxxxxxplaceofbirth = q7xxhxxxbvxxxxxxxxxxplaceofbirth;
		this.q7xxtxsebvxxxxxxxxxxsex = q7xxtxsebvxxxxxxxxxxsex;
		this.q7xxhxxxlvxxxxxxxxxxage = q7xxhxxxlvxxxxxxxxxxage;
		this.z1xxzrrplexxxxxxxxxxcusrtotl = z1xxzrrplexxxxxxxxxxcusrtotl;
		this.z2xxzrrqlexxxxxxxxxxcusrtqty = z2xxzrrqlexxxxxxxxxxcusrtqty;
		this.z3xxzrmplexxxxxxxxxxcusmtotl = z3xxzrmplexxxxxxxxxxcusmtotl;
		this.z4xxzrdplexxxxxxxxxxcusdtotl = z4xxzrdplexxxxxxxxxxcusdtotl;
		this.z5xxutlolexxxxxxxxxxlastorder = z5xxutlolexxxxxxxxxxlastorder;
		this.z6xxuxxxbexxxxxxxxxxlastinvoic = z6xxuxxxbexxxxxxxxxxlastinvoic;
		this.z7xxzxxxlexxxxxxxxxxlastpaymnq = z7xxzxxxlexxxxxxxxxxlastpaymnq;
		this.z8xxzzprhvxxxxxxxxxxprintmstat = z8xxzzprhvxxxxxxxxxxprintmstat;
		this.z9xxczqxlhxxxxxxxxxxprinmtfldt = z9xxczqxlhxxxxxxxxxxprinmtfldt;
		this.r1xxfxxxbexxxxxxxxxxshiplabel = r1xxfxxxbexxxxxxxxxxshiplabel;
		this.f1xxuxxxav28xxxxxxxxtype = f1xxuxxxav28xxxxxxxxtype;
		this.f2xxuwmxbv40xxxxxxxxintegrset = f2xxuwmxbv40xxxxxxxxintegrset;
		this.zaxxzzfxhhxxxxxxxxxxstatusfl = zaxxzzfxhhxxxxxxxxxxstatusfl;
		this.zbxxcztxlxxxxxxxxxxxstatusfldt = zbxxcztxlxxxxxxxxxxxstatusfldt;
		this.zcxxzxxxlvxxxxxxxxxxtotlpaid = zcxxzxxxlvxxxxxxxxxxtotlpaid;
		this.ydxxuxxybvxxxxxxxxxxcontacted = ydxxuxxybvxxxxxxxxxxcontacted;
		this.yexxuxxybvxxxxxxxxxxbywho = yexxuxxybvxxxxxxxxxxbywho;
		this.yfxxcxxybvxxxxxxxxxxnxtcontact = yfxxcxxybvxxxxxxxxxxnxtcontact;
		this.ygxxuxxybv30xxxxxxxxvia = ygxxuxxybv30xxxxxxxxvia;
		this.yhxxuzkybvxxxxxxxxxxkeywords = yhxxuzkybvxxxxxxxxxxkeywords;
		this.yixxuznybvxxxxxxxxxxnotes = yixxuznybvxxxxxxxxxxnotes;
		this.zdxxutoxlhxxxxxxxxxxowner = zdxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.ycxxuzdrbvxxxxxxxxxxdocmnt = ycxxuzdrbvxxxxxxxxxxdocmnt;
		this.xorxeh8cexwwqqhxxxxxscheduledetailses = xorxeh8cexwwqqhxxxxxscheduledetailses;
		this.trexuq244xwwqqhxxxxxcuorderses = trexuq244xwwqqhxxxxxcuorderses;
		this.txxxuq932xwwqqhspxxxactivityjobs = txxxuq932xwwqqhspxxxactivityjobs;
		this.trexuq277xwwqqhxxxxxcpayments = trexuq277xwwqqhxxxxxcpayments;
		this.xxxxuq9ccxwwqqhxxxxxprocessdetailses = xxxxuq9ccxwwqqhxxxxxprocessdetailses;
		this.xoxxuq3c4xwwqqhxxxxxvendidetailses = xoxxuq3c4xwwqqhxxxxxvendidetailses;
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
		this.trexuq377xwwqqhxxxxxvshipmens = trexuq377xwwqqhxxxxxvshipmens;
		this.trexuq255xwwqqhxxxxxshipments = trexuq255xwwqqhxxxxxshipments;
		this.trxxuq9aaxwwqqhefxxxjobassignments = trxxuq9aaxwwqqhefxxxjobassignments;
		this.xoxxuq3d4xwwqqhxxxxxvendodetailses = xoxxuq3d4xwwqqhxxxxxvendodetailses;
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
		this.trexuq266xwwqqhxxxxxcuinvoices = trexuq266xwwqqhxxxxxcuinvoices;
		this.jxxxuq21bxwwqqhxxxxxccontacts = jxxxuq21bxwwqqhxxxxxccontacts;
		this.trexuq233xwwqqhxxxxxcuquotes = trexuq233xwwqqhxxxxxcuquotes;
		this.yxxxuh566xwwqqwxxxxxusers = yxxxuh566xwwqqwxxxxxusers;
		this.dxxxuq92bxwwqqhefxxxitemjobs = dxxxuq92bxwwqqhefxxxitemjobs;
		this.xoxxuq3e4xwwqqhxxxxxvendqdetailses = xoxxuq3e4xwwqqhxxxxxvendqdetailses;
		this.fxxxuq89bxwwqqhxxxxxschedules = fxxxuq89bxwwqqhxxxxxschedules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public Fxxxcq144xwwqqhxxxxxlocation getFxxxcq144xwwqqhxxxxxlocation() {
		return this.fxxxcq144xwwqqhxxxxxlocation;
	}

	public void setFxxxcq144xwwqqhxxxxxlocation(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailtocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByMailtocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByMailtocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByMailtocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByMailtocode = fxxxuq111xwwqqhxxxxxaddressByMailtocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "defaultglac")
	public Yxxxch601xwwqqhxxxxxaccount getYxxxch601xwwqqhxxxxxaccount() {
		return this.yxxxch601xwwqqhxxxxxaccount;
	}

	public void setYxxxch601xwwqqhxxxxxaccount(
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount) {
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companycode")
	public Dxxxch1d3xwwqqhxxlxxcompany getDxxxch1d3xwwqqhxxlxxcompany() {
		return this.dxxxch1d3xwwqqhxxlxxcompany;
	}

	public void setDxxxch1d3xwwqqhxxlxxcompany(
			Dxxxch1d3xwwqqhxxlxxcompany dxxxch1d3xwwqqhxxlxxcompany) {
		this.dxxxch1d3xwwqqhxxlxxcompany = dxxxch1d3xwwqqhxxlxxcompany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shiptocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByShiptocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByShiptocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	@Column(name = "customer", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukxxbvxxxxxxxxxxcustomer() {
		return this.a0xxukxxbvxxxxxxxxxxcustomer;
	}

	public void setA0xxukxxbvxxxxxxxxxxcustomer(
			String a0xxukxxbvxxxxxxxxxxcustomer) {
		this.a0xxukxxbvxxxxxxxxxxcustomer = a0xxukxxbvxxxxxxxxxxcustomer;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getY0xxuzsxbvxxxxxxxxxxdescript() {
		return this.y0xxuzsxbvxxxxxxxxxxdescript;
	}

	public void setY0xxuzsxbvxxxxxxxxxxdescript(
			String y0xxuzsxbvxxxxxxxxxxdescript) {
		this.y0xxuzsxbvxxxxxxxxxxdescript = y0xxuzsxbvxxxxxxxxxxdescript;
	}

	@Column(name = "title", length = 12)
	@Size(max = 12)
	public String getB1xxuxxxbv21xxxxxxxxtitle() {
		return this.b1xxuxxxbv21xxxxxxxxtitle;
	}

	public void setB1xxuxxxbv21xxxxxxxxtitle(String b1xxuxxxbv21xxxxxxxxtitle) {
		this.b1xxuxxxbv21xxxxxxxxtitle = b1xxuxxxbv21xxxxxxxxtitle;
	}

	@Column(name = "jobtitle", length = 20)
	@Size(max = 20)
	public String getB2xxuxxxbx22xxxxxxxxjobtitle() {
		return this.b2xxuxxxbx22xxxxxxxxjobtitle;
	}

	public void setB2xxuxxxbx22xxxxxxxxjobtitle(
			String b2xxuxxxbx22xxxxxxxxjobtitle) {
		this.b2xxuxxxbx22xxxxxxxxjobtitle = b2xxuxxxbx22xxxxxxxxjobtitle;
	}

	@Column(name = "lastname", length = 25)
	@Size(max = 25)
	public String getC1xxuslnbvixxxxxxxxxlastname() {
		return this.c1xxuslnbvixxxxxxxxxlastname;
	}

	public void setC1xxuslnbvixxxxxxxxxlastname(
			String c1xxuslnbvixxxxxxxxxlastname) {
		this.c1xxuslnbvixxxxxxxxxlastname = c1xxuslnbvixxxxxxxxxlastname;
	}

	@Column(name = "firstname", length = 25)
	@Size(max = 25)
	public String getC2xxu2fnbvixxxxxxxxxfirstname() {
		return this.c2xxu2fnbvixxxxxxxxxfirstname;
	}

	public void setC2xxu2fnbvixxxxxxxxxfirstname(
			String c2xxu2fnbvixxxxxxxxxfirstname) {
		this.c2xxu2fnbvixxxxxxxxxfirstname = c2xxu2fnbvixxxxxxxxxfirstname;
	}

	@Column(name = "middlenam", length = 20)
	@Size(max = 20)
	public String getC3xxuxxxbxxxxxxxxxxxmiddlenam() {
		return this.c3xxuxxxbxxxxxxxxxxxmiddlenam;
	}

	public void setC3xxuxxxbxxxxxxxxxxxmiddlenam(
			String c3xxuxxxbxxxxxxxxxxxmiddlenam) {
		this.c3xxuxxxbxxxxxxxxxxxmiddlenam = c3xxuxxxbxxxxxxxxxxxmiddlenam;
	}

	@Column(name = "customerascompanyname", length = 25)
	@Size(max = 25)
	public String getD1xxu3cnbvixxxxxxxxxcustomerascompanyname() {
		return this.d1xxu3cnbvixxxxxxxxxcustomerascompanyname;
	}

	public void setD1xxu3cnbvixxxxxxxxxcustomerascompanyname(
			String d1xxu3cnbvixxxxxxxxxcustomerascompanyname) {
		this.d1xxu3cnbvixxxxxxxxxcustomerascompanyname = d1xxu3cnbvixxxxxxxxxcustomerascompanyname;
	}

	@Column(name = "custtotl", precision = 14)
	public BigDecimal getZ1xxzrpxlexxxxxxxxxxcusttotl() {
		return this.z1xxzrpxlexxxxxxxxxxcusttotl;
	}

	public void setZ1xxzrpxlexxxxxxxxxxcusttotl(
			BigDecimal z1xxzrpxlexxxxxxxxxxcusttotl) {
		this.z1xxzrpxlexxxxxxxxxxcusttotl = z1xxzrpxlexxxxxxxxxxcusttotl;
	}

	@Column(name = "custtqty", precision = 14)
	public BigDecimal getZ2xxzrqxlexxxxxxxxxxcusttqty() {
		return this.z2xxzrqxlexxxxxxxxxxcusttqty;
	}

	public void setZ2xxzrqxlexxxxxxxxxxcusttqty(
			BigDecimal z2xxzrqxlexxxxxxxxxxcusttqty) {
		this.z2xxzrqxlexxxxxxxxxxcusttqty = z2xxzrqxlexxxxxxxxxxcusttqty;
	}

	@Column(name = "tax1")
	public Boolean getY6xxfxz1bvxxxxxxxxxxtax1() {
		return this.y6xxfxz1bvxxxxxxxxxxtax1;
	}

	public void setY6xxfxz1bvxxxxxxxxxxtax1(Boolean y6xxfxz1bvxxxxxxxxxxtax1) {
		this.y6xxfxz1bvxxxxxxxxxxtax1 = y6xxfxz1bvxxxxxxxxxxtax1;
	}

	@Column(name = "tax2")
	public Boolean getY7xxfxz2bvxxxxxxxxxxtax2() {
		return this.y7xxfxz2bvxxxxxxxxxxtax2;
	}

	public void setY7xxfxz2bvxxxxxxxxxxtax2(Boolean y7xxfxz2bvxxxxxxxxxxtax2) {
		this.y7xxfxz2bvxxxxxxxxxxtax2 = y7xxfxz2bvxxxxxxxxxxtax2;
	}

	@Column(name = "tax3")
	public Boolean getY8xxfxz3bvxxxxxxxxxxtax3() {
		return this.y8xxfxz3bvxxxxxxxxxxtax3;
	}

	public void setY8xxfxz3bvxxxxxxxxxxtax3(Boolean y8xxfxz3bvxxxxxxxxxxtax3) {
		this.y8xxfxz3bvxxxxxxxxxxtax3 = y8xxfxz3bvxxxxxxxxxxtax3;
	}

	@Column(name = "custtax1", length = 25)
	@Size(max = 25)
	public String getY9xxuxz1bv04xxxxxxxxcusttax1() {
		return this.y9xxuxz1bv04xxxxxxxxcusttax1;
	}

	public void setY9xxuxz1bv04xxxxxxxxcusttax1(
			String y9xxuxz1bv04xxxxxxxxcusttax1) {
		this.y9xxuxz1bv04xxxxxxxxcusttax1 = y9xxuxz1bv04xxxxxxxxcusttax1;
	}

	@Column(name = "custtax2", length = 25)
	@Size(max = 25)
	public String getYaxxuxz2bv05xxxxxxxxcusttax2() {
		return this.yaxxuxz2bv05xxxxxxxxcusttax2;
	}

	public void setYaxxuxz2bv05xxxxxxxxcusttax2(
			String yaxxuxz2bv05xxxxxxxxcusttax2) {
		this.yaxxuxz2bv05xxxxxxxxcusttax2 = yaxxuxz2bv05xxxxxxxxcusttax2;
	}

	@Column(name = "custtax3", length = 25)
	@Size(max = 25)
	public String getYbxxuxz3xv06xxxxxxxxcusttax3() {
		return this.ybxxuxz3xv06xxxxxxxxcusttax3;
	}

	public void setYbxxuxz3xv06xxxxxxxxcusttax3(
			String ybxxuxz3xv06xxxxxxxxcusttax3) {
		this.ybxxuxz3xv06xxxxxxxxcusttax3 = ybxxuxz3xv06xxxxxxxxcusttax3;
	}

	@Column(name = "phoneo", length = 20)
	@Size(max = 20)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getP1xxh4pobv27xxxxxxxxphoneo() {
		return this.p1xxh4pobv27xxxxxxxxphoneo;
	}

	public void setP1xxh4pobv27xxxxxxxxphoneo(String p1xxh4pobv27xxxxxxxxphoneo) {
		this.p1xxh4pobv27xxxxxxxxphoneo = p1xxh4pobv27xxxxxxxxphoneo;
	}

	@Column(name = "phoneh", length = 16)
	@Size(max = 16)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getP2xxh5phbv27xxxxxxxxphoneh() {
		return this.p2xxh5phbv27xxxxxxxxphoneh;
	}

	public void setP2xxh5phbv27xxxxxxxxphoneh(String p2xxh5phbv27xxxxxxxxphoneh) {
		this.p2xxh5phbv27xxxxxxxxphoneh = p2xxh5phbv27xxxxxxxxphoneh;
	}

	@Column(name = "phonec", length = 16)
	@Size(max = 16)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getP3xxhxxxbv27xxxxxxxxphonec() {
		return this.p3xxhxxxbv27xxxxxxxxphonec;
	}

	public void setP3xxhxxxbv27xxxxxxxxphonec(String p3xxhxxxbv27xxxxxxxxphonec) {
		this.p3xxhxxxbv27xxxxxxxxphonec = p3xxhxxxbv27xxxxxxxxphonec;
	}

	@Column(name = "phonex", length = 20)
	@Size(max = 20)
	@Pattern(regexp = "^$|^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$", message = "Code must be phone # pattern and digits and - . space")
	public String getP4xxhxxxbx27xxxxxxxxphonex() {
		return this.p4xxhxxxbx27xxxxxxxxphonex;
	}

	public void setP4xxhxxxbx27xxxxxxxxphonex(String p4xxhxxxbx27xxxxxxxxphonex) {
		this.p4xxhxxxbx27xxxxxxxxphonex = p4xxhxxxbx27xxxxxxxxphonex;
	}

	@Column(name = "lanaddr", length = 35)
	@Size(max = 35)
	public String getQ1xxhxxxbx19xxxxxxxxlanaddr() {
		return this.q1xxhxxxbx19xxxxxxxxlanaddr;
	}

	public void setQ1xxhxxxbx19xxxxxxxxlanaddr(
			String q1xxhxxxbx19xxxxxxxxlanaddr) {
		this.q1xxhxxxbx19xxxxxxxxlanaddr = q1xxhxxxbx19xxxxxxxxlanaddr;
	}

	@Column(name = "wanaddr", length = 35)
	@Size(max = 35)
	public String getQ2xxhxxxbx25xxxxxxxxwanaddr() {
		return this.q2xxhxxxbx25xxxxxxxxwanaddr;
	}

	public void setQ2xxhxxxbx25xxxxxxxxwanaddr(
			String q2xxhxxxbx25xxxxxxxxwanaddr) {
		this.q2xxhxxxbx25xxxxxxxxwanaddr = q2xxhxxxbx25xxxxxxxxwanaddr;
	}

	@Column(name = "lmailaddr", length = 35)
	@Size(max = 35)
	public String getQ3xxhxxxbv44xxxxxxxxlmailaddr() {
		return this.q3xxhxxxbv44xxxxxxxxlmailaddr;
	}

	public void setQ3xxhxxxbv44xxxxxxxxlmailaddr(
			String q3xxhxxxbv44xxxxxxxxlmailaddr) {
		this.q3xxhxxxbv44xxxxxxxxlmailaddr = q3xxhxxxbv44xxxxxxxxlmailaddr;
	}

	@Column(name = "imailaddr", length = 60)
	@Size(max = 60)
	@Pattern.List({
			@Pattern(regexp = "(^$|.+@.+\\..+)", message = "Bad email value"),
			@Pattern(regexp = "(^$)|(^\\S+$)", message = "email has space character")})
	public String getQ4xxhxxxbv24xxxxxxxximailaddr() {
		return this.q4xxhxxxbv24xxxxxxxximailaddr;
	}

	public void setQ4xxhxxxbv24xxxxxxxximailaddr(
			String q4xxhxxxbv24xxxxxxxximailaddr) {
		this.q4xxhxxxbv24xxxxxxxximailaddr = q4xxhxxxbv24xxxxxxxximailaddr;
	}

	@Column(name = "rmailaddr", length = 35)
	@Size(max = 35)
	public String getQ5xxuxxxbxxxxxxxxxxxrmailaddr() {
		return this.q5xxuxxxbxxxxxxxxxxxrmailaddr;
	}

	public void setQ5xxuxxxbxxxxxxxxxxxrmailaddr(
			String q5xxuxxxbxxxxxxxxxxxrmailaddr) {
		this.q5xxuxxxbxxxxxxxxxxxrmailaddr = q5xxuxxxbxxxxxxxxxxxrmailaddr;
	}

	@Column(name = "intaddr", length = 60)
	@Size(max = 60)
	public String getQ6xxhxxxbx23xxxxxxxxintaddr() {
		return this.q6xxhxxxbx23xxxxxxxxintaddr;
	}

	public void setQ6xxhxxxbx23xxxxxxxxintaddr(
			String q6xxhxxxbx23xxxxxxxxintaddr) {
		this.q6xxhxxxbx23xxxxxxxxintaddr = q6xxhxxxbx23xxxxxxxxintaddr;
	}

	@Column(name = "inraddr", length = 35)
	@Size(max = 35)
	public String getQ7xxhxxxbxxxxxxxxxxxinraddr() {
		return this.q7xxhxxxbxxxxxxxxxxxinraddr;
	}

	public void setQ7xxhxxxbxxxxxxxxxxxinraddr(
			String q7xxhxxxbxxxxxxxxxxxinraddr) {
		this.q7xxhxxxbxxxxxxxxxxxinraddr = q7xxhxxxbxxxxxxxxxxxinraddr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 29)
	public Date getQ7xxdxtdbvxxxxxxxxxxdob() {
		return this.q7xxdxtdbvxxxxxxxxxxdob;
	}

	public void setQ7xxdxtdbvxxxxxxxxxxdob(Date q7xxdxtdbvxxxxxxxxxxdob) {
		this.q7xxdxtdbvxxxxxxxxxxdob = q7xxdxtdbvxxxxxxxxxxdob;
	}

	@Column(name = "placeofbirth", length = 60)
	@Size(max = 60)
	public String getQ7xxhxxxbvxxxxxxxxxxplaceofbirth() {
		return this.q7xxhxxxbvxxxxxxxxxxplaceofbirth;
	}

	public void setQ7xxhxxxbvxxxxxxxxxxplaceofbirth(
			String q7xxhxxxbvxxxxxxxxxxplaceofbirth) {
		this.q7xxhxxxbvxxxxxxxxxxplaceofbirth = q7xxhxxxbvxxxxxxxxxxplaceofbirth;
	}

	@Column(name = "sex", length = 1)
	@Size(max = 1)
	public String getQ7xxtxsebvxxxxxxxxxxsex() {
		return this.q7xxtxsebvxxxxxxxxxxsex;
	}

	public void setQ7xxtxsebvxxxxxxxxxxsex(String q7xxtxsebvxxxxxxxxxxsex) {
		this.q7xxtxsebvxxxxxxxxxxsex = q7xxtxsebvxxxxxxxxxxsex;
	}

	@Column(name = "age")
	public Integer getQ7xxhxxxlvxxxxxxxxxxage() {
		return this.q7xxhxxxlvxxxxxxxxxxage;
	}

	public void setQ7xxhxxxlvxxxxxxxxxxage(Integer q7xxhxxxlvxxxxxxxxxxage) {
		this.q7xxhxxxlvxxxxxxxxxxage = q7xxhxxxlvxxxxxxxxxxage;
	}

	@Column(name = "cusrtotl", precision = 14)
	public BigDecimal getZ1xxzrrplexxxxxxxxxxcusrtotl() {
		return this.z1xxzrrplexxxxxxxxxxcusrtotl;
	}

	public void setZ1xxzrrplexxxxxxxxxxcusrtotl(
			BigDecimal z1xxzrrplexxxxxxxxxxcusrtotl) {
		this.z1xxzrrplexxxxxxxxxxcusrtotl = z1xxzrrplexxxxxxxxxxcusrtotl;
	}

	@Column(name = "cusrtqty", precision = 14)
	public BigDecimal getZ2xxzrrqlexxxxxxxxxxcusrtqty() {
		return this.z2xxzrrqlexxxxxxxxxxcusrtqty;
	}

	public void setZ2xxzrrqlexxxxxxxxxxcusrtqty(
			BigDecimal z2xxzrrqlexxxxxxxxxxcusrtqty) {
		this.z2xxzrrqlexxxxxxxxxxcusrtqty = z2xxzrrqlexxxxxxxxxxcusrtqty;
	}

	@Column(name = "cusmtotl", precision = 14)
	public BigDecimal getZ3xxzrmplexxxxxxxxxxcusmtotl() {
		return this.z3xxzrmplexxxxxxxxxxcusmtotl;
	}

	public void setZ3xxzrmplexxxxxxxxxxcusmtotl(
			BigDecimal z3xxzrmplexxxxxxxxxxcusmtotl) {
		this.z3xxzrmplexxxxxxxxxxcusmtotl = z3xxzrmplexxxxxxxxxxcusmtotl;
	}

	@Column(name = "cusdtotl", precision = 14)
	public BigDecimal getZ4xxzrdplexxxxxxxxxxcusdtotl() {
		return this.z4xxzrdplexxxxxxxxxxcusdtotl;
	}

	public void setZ4xxzrdplexxxxxxxxxxcusdtotl(
			BigDecimal z4xxzrdplexxxxxxxxxxcusdtotl) {
		this.z4xxzrdplexxxxxxxxxxcusdtotl = z4xxzrdplexxxxxxxxxxcusdtotl;
	}

	@Column(name = "lastorder", length = 20)
	@Size(max = 20)
	public String getZ5xxutlolexxxxxxxxxxlastorder() {
		return this.z5xxutlolexxxxxxxxxxlastorder;
	}

	public void setZ5xxutlolexxxxxxxxxxlastorder(
			String z5xxutlolexxxxxxxxxxlastorder) {
		this.z5xxutlolexxxxxxxxxxlastorder = z5xxutlolexxxxxxxxxxlastorder;
	}

	@Column(name = "lastinvoic", length = 20)
	@Size(max = 20)
	public String getZ6xxuxxxbexxxxxxxxxxlastinvoic() {
		return this.z6xxuxxxbexxxxxxxxxxlastinvoic;
	}

	public void setZ6xxuxxxbexxxxxxxxxxlastinvoic(
			String z6xxuxxxbexxxxxxxxxxlastinvoic) {
		this.z6xxuxxxbexxxxxxxxxxlastinvoic = z6xxuxxxbexxxxxxxxxxlastinvoic;
	}

	@Column(name = "lastpaymnq", precision = 14)
	public BigDecimal getZ7xxzxxxlexxxxxxxxxxlastpaymnq() {
		return this.z7xxzxxxlexxxxxxxxxxlastpaymnq;
	}

	public void setZ7xxzxxxlexxxxxxxxxxlastpaymnq(
			BigDecimal z7xxzxxxlexxxxxxxxxxlastpaymnq) {
		this.z7xxzxxxlexxxxxxxxxxlastpaymnq = z7xxzxxxlexxxxxxxxxxlastpaymnq;
	}

	@Column(name = "printmstat")
	public Integer getZ8xxzzprhvxxxxxxxxxxprintmstat() {
		return this.z8xxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZ8xxzzprhvxxxxxxxxxxprintmstat(
			Integer z8xxzzprhvxxxxxxxxxxprintmstat) {
		this.z8xxzzprhvxxxxxxxxxxprintmstat = z8xxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZ9xxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.z9xxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZ9xxczqxlhxxxxxxxxxxprinmtfldt(
			Date z9xxczqxlhxxxxxxxxxxprinmtfldt) {
		this.z9xxczqxlhxxxxxxxxxxprinmtfldt = z9xxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "shiplabel")
	public Boolean getR1xxfxxxbexxxxxxxxxxshiplabel() {
		return this.r1xxfxxxbexxxxxxxxxxshiplabel;
	}

	public void setR1xxfxxxbexxxxxxxxxxshiplabel(
			Boolean r1xxfxxxbexxxxxxxxxxshiplabel) {
		this.r1xxfxxxbexxxxxxxxxxshiplabel = r1xxfxxxbexxxxxxxxxxshiplabel;
	}

	@Column(name = "type", length = 10)
	@Size(max = 10)
	public String getF1xxuxxxav28xxxxxxxxtype() {
		return this.f1xxuxxxav28xxxxxxxxtype;
	}

	public void setF1xxuxxxav28xxxxxxxxtype(String f1xxuxxxav28xxxxxxxxtype) {
		this.f1xxuxxxav28xxxxxxxxtype = f1xxuxxxav28xxxxxxxxtype;
	}

	@Column(name = "integrset", length = 20)
	@Size(max = 20)
	public String getF2xxuwmxbv40xxxxxxxxintegrset() {
		return this.f2xxuwmxbv40xxxxxxxxintegrset;
	}

	public void setF2xxuwmxbv40xxxxxxxxintegrset(
			String f2xxuwmxbv40xxxxxxxxintegrset) {
		this.f2xxuwmxbv40xxxxxxxxintegrset = f2xxuwmxbv40xxxxxxxxintegrset;
	}

	@Column(name = "statusfl")
	public Integer getZaxxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zaxxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZaxxzzfxhhxxxxxxxxxxstatusfl(
			Integer zaxxzzfxhhxxxxxxxxxxstatusfl) {
		this.zaxxzzfxhhxxxxxxxxxxstatusfl = zaxxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZbxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zbxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZbxxcztxlxxxxxxxxxxxstatusfldt(
			Date zbxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zbxxcztxlxxxxxxxxxxxstatusfldt = zbxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "totlpaid", precision = 14)
	public BigDecimal getZcxxzxxxlvxxxxxxxxxxtotlpaid() {
		return this.zcxxzxxxlvxxxxxxxxxxtotlpaid;
	}

	public void setZcxxzxxxlvxxxxxxxxxxtotlpaid(
			BigDecimal zcxxzxxxlvxxxxxxxxxxtotlpaid) {
		this.zcxxzxxxlvxxxxxxxxxxtotlpaid = zcxxzxxxlvxxxxxxxxxxtotlpaid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contacted", length = 29)
	public Date getYdxxuxxybvxxxxxxxxxxcontacted() {
		return this.ydxxuxxybvxxxxxxxxxxcontacted;
	}

	public void setYdxxuxxybvxxxxxxxxxxcontacted(
			Date ydxxuxxybvxxxxxxxxxxcontacted) {
		this.ydxxuxxybvxxxxxxxxxxcontacted = ydxxuxxybvxxxxxxxxxxcontacted;
	}

	@Column(name = "bywho", length = 20)
	@Size(max = 20)
	public String getYexxuxxybvxxxxxxxxxxbywho() {
		return this.yexxuxxybvxxxxxxxxxxbywho;
	}

	public void setYexxuxxybvxxxxxxxxxxbywho(String yexxuxxybvxxxxxxxxxxbywho) {
		this.yexxuxxybvxxxxxxxxxxbywho = yexxuxxybvxxxxxxxxxxbywho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "nxtcontact", length = 29)
	public Date getYfxxcxxybvxxxxxxxxxxnxtcontact() {
		return this.yfxxcxxybvxxxxxxxxxxnxtcontact;
	}

	public void setYfxxcxxybvxxxxxxxxxxnxtcontact(
			Date yfxxcxxybvxxxxxxxxxxnxtcontact) {
		this.yfxxcxxybvxxxxxxxxxxnxtcontact = yfxxcxxybvxxxxxxxxxxnxtcontact;
	}

	@Column(name = "via", length = 11)
	@Size(max = 11)
	public String getYgxxuxxybv30xxxxxxxxvia() {
		return this.ygxxuxxybv30xxxxxxxxvia;
	}

	public void setYgxxuxxybv30xxxxxxxxvia(String ygxxuxxybv30xxxxxxxxvia) {
		this.ygxxuxxybv30xxxxxxxxvia = ygxxuxxybv30xxxxxxxxvia;
	}

	@Column(name = "keywords", length = 30)
	@Size(max = 30)
	public String getYhxxuzkybvxxxxxxxxxxkeywords() {
		return this.yhxxuzkybvxxxxxxxxxxkeywords;
	}

	public void setYhxxuzkybvxxxxxxxxxxkeywords(
			String yhxxuzkybvxxxxxxxxxxkeywords) {
		this.yhxxuzkybvxxxxxxxxxxkeywords = yhxxuzkybvxxxxxxxxxxkeywords;
	}

	@Column(name = "notes", length = 159)
	@Size(max = 159)
	public String getYixxuznybvxxxxxxxxxxnotes() {
		return this.yixxuznybvxxxxxxxxxxnotes;
	}

	public void setYixxuznybvxxxxxxxxxxnotes(String yixxuznybvxxxxxxxxxxnotes) {
		this.yixxuznybvxxxxxxxxxxnotes = yixxuznybvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZdxxutoxlhxxxxxxxxxxowner() {
		return this.zdxxutoxlhxxxxxxxxxxowner;
	}

	public void setZdxxutoxlhxxxxxxxxxxowner(String zdxxutoxlhxxxxxxxxxxowner) {
		this.zdxxutoxlhxxxxxxxxxxowner = zdxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "docmnt", length = 90)
	@Size(max = 90)
	public String getYcxxuzdrbvxxxxxxxxxxdocmnt() {
		return this.ycxxuzdrbvxxxxxxxxxxdocmnt;
	}

	public void setYcxxuzdrbvxxxxxxxxxxdocmnt(String ycxxuzdrbvxxxxxxxxxxdocmnt) {
		this.ycxxuzdrbvxxxxxxxxxxdocmnt = ycxxuzdrbvxxxxxxxxxxdocmnt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Xorxeh8cexwwqqhxxxxxscheduledetails> getXorxeh8cexwwqqhxxxxxscheduledetailses() {
		return this.xorxeh8cexwwqqhxxxxxscheduledetailses;
	}

	public void setXorxeh8cexwwqqhxxxxxscheduledetailses(
			Set<Xorxeh8cexwwqqhxxxxxscheduledetails> xorxeh8cexwwqqhxxxxxscheduledetailses) {
		this.xorxeh8cexwwqqhxxxxxscheduledetailses = xorxeh8cexwwqqhxxxxxscheduledetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trexuq244xwwqqhxxxxxcuorders> getTrexuq244xwwqqhxxxxxcuorderses() {
		return this.trexuq244xwwqqhxxxxxcuorderses;
	}

	public void setTrexuq244xwwqqhxxxxxcuorderses(
			Set<Trexuq244xwwqqhxxxxxcuorders> trexuq244xwwqqhxxxxxcuorderses) {
		this.trexuq244xwwqqhxxxxxcuorderses = trexuq244xwwqqhxxxxxcuorderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Txxxuq932xwwqqhspxxxactivityjob> getTxxxuq932xwwqqhspxxxactivityjobs() {
		return this.txxxuq932xwwqqhspxxxactivityjobs;
	}

	public void setTxxxuq932xwwqqhspxxxactivityjobs(
			Set<Txxxuq932xwwqqhspxxxactivityjob> txxxuq932xwwqqhspxxxactivityjobs) {
		this.txxxuq932xwwqqhspxxxactivityjobs = txxxuq932xwwqqhspxxxactivityjobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trexuq277xwwqqhxxxxxcpayment> getTrexuq277xwwqqhxxxxxcpayments() {
		return this.trexuq277xwwqqhxxxxxcpayments;
	}

	public void setTrexuq277xwwqqhxxxxxcpayments(
			Set<Trexuq277xwwqqhxxxxxcpayment> trexuq277xwwqqhxxxxxcpayments) {
		this.trexuq277xwwqqhxxxxxcpayments = trexuq277xwwqqhxxxxxcpayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> getXxxxuq9ccxwwqqhxxxxxprocessdetailses() {
		return this.xxxxuq9ccxwwqqhxxxxxprocessdetailses;
	}

	public void setXxxxuq9ccxwwqqhxxxxxprocessdetailses(
			Set<Xxxxuq9ccxwwqqhxxxxxprocessdetails> xxxxuq9ccxwwqqhxxxxxprocessdetailses) {
		this.xxxxuq9ccxwwqqhxxxxxprocessdetailses = xxxxuq9ccxwwqqhxxxxxprocessdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> getXoxxuq3c4xwwqqhxxxxxvendidetailses() {
		return this.xoxxuq3c4xwwqqhxxxxxvendidetailses;
	}

	public void setXoxxuq3c4xwwqqhxxxxxvendidetailses(
			Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses) {
		this.xoxxuq3c4xwwqqhxxxxxvendidetailses = xoxxuq3c4xwwqqhxxxxxvendidetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Jxxxuq54exwwqqhxxxxxgroupmembers> getJxxxuq54exwwqqhxxxxxgroupmemberses() {
		return this.jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	public void setJxxxuq54exwwqqhxxxxxgroupmemberses(
			Set<Jxxxuq54exwwqqhxxxxxgroupmembers> jxxxuq54exwwqqhxxxxxgroupmemberses) {
		this.jxxxuq54exwwqqhxxxxxgroupmemberses = jxxxuq54exwwqqhxxxxxgroupmemberses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trexuq377xwwqqhxxxxxvshipmen> getTrexuq377xwwqqhxxxxxvshipmens() {
		return this.trexuq377xwwqqhxxxxxvshipmens;
	}

	public void setTrexuq377xwwqqhxxxxxvshipmens(
			Set<Trexuq377xwwqqhxxxxxvshipmen> trexuq377xwwqqhxxxxxvshipmens) {
		this.trexuq377xwwqqhxxxxxvshipmens = trexuq377xwwqqhxxxxxvshipmens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trexuq255xwwqqhxxxxxshipment> getTrexuq255xwwqqhxxxxxshipments() {
		return this.trexuq255xwwqqhxxxxxshipments;
	}

	public void setTrexuq255xwwqqhxxxxxshipments(
			Set<Trexuq255xwwqqhxxxxxshipment> trexuq255xwwqqhxxxxxshipments) {
		this.trexuq255xwwqqhxxxxxshipments = trexuq255xwwqqhxxxxxshipments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trxxuq9aaxwwqqhefxxxjobassignment> getTrxxuq9aaxwwqqhefxxxjobassignments() {
		return this.trxxuq9aaxwwqqhefxxxjobassignments;
	}

	public void setTrxxuq9aaxwwqqhefxxxjobassignments(
			Set<Trxxuq9aaxwwqqhefxxxjobassignment> trxxuq9aaxwwqqhefxxxjobassignments) {
		this.trxxuq9aaxwwqqhefxxxjobassignments = trxxuq9aaxwwqqhefxxxjobassignments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> getXoxxuq3d4xwwqqhxxxxxvendodetailses() {
		return this.xoxxuq3d4xwwqqhxxxxxvendodetailses;
	}

	public void setXoxxuq3d4xwwqqhxxxxxvendodetailses(
			Set<Xoxxuq3d4xwwqqhxxxxxvendodetails> xoxxuq3d4xwwqqhxxxxxvendodetailses) {
		this.xoxxuq3d4xwwqqhxxxxxvendodetailses = xoxxuq3d4xwwqqhxxxxxvendodetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> getXoxxuq9bfxwwqqhexxxxjobassignmentdetailses() {
		return this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	public void setXoxxuq9bfxwwqqhexxxxjobassignmentdetailses(
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses) {
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trexuq266xwwqqhxxxxxcuinvoice> getTrexuq266xwwqqhxxxxxcuinvoices() {
		return this.trexuq266xwwqqhxxxxxcuinvoices;
	}

	public void setTrexuq266xwwqqhxxxxxcuinvoices(
			Set<Trexuq266xwwqqhxxxxxcuinvoice> trexuq266xwwqqhxxxxxcuinvoices) {
		this.trexuq266xwwqqhxxxxxcuinvoices = trexuq266xwwqqhxxxxxcuinvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Jxxxuq21bxwwqqhxxxxxccontact> getJxxxuq21bxwwqqhxxxxxccontacts() {
		return this.jxxxuq21bxwwqqhxxxxxccontacts;
	}

	public void setJxxxuq21bxwwqqhxxxxxccontacts(
			Set<Jxxxuq21bxwwqqhxxxxxccontact> jxxxuq21bxwwqqhxxxxxccontacts) {
		this.jxxxuq21bxwwqqhxxxxxccontacts = jxxxuq21bxwwqqhxxxxxccontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Trexuq233xwwqqhxxxxxcuquote> getTrexuq233xwwqqhxxxxxcuquotes() {
		return this.trexuq233xwwqqhxxxxxcuquotes;
	}

	public void setTrexuq233xwwqqhxxxxxcuquotes(
			Set<Trexuq233xwwqqhxxxxxcuquote> trexuq233xwwqqhxxxxxcuquotes) {
		this.trexuq233xwwqqhxxxxxcuquotes = trexuq233xwwqqhxxxxxcuquotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Yxxxuh566xwwqqwxxxxxuser> getYxxxuh566xwwqqwxxxxxusers() {
		return this.yxxxuh566xwwqqwxxxxxusers;
	}

	public void setYxxxuh566xwwqqwxxxxxusers(
			Set<Yxxxuh566xwwqqwxxxxxuser> yxxxuh566xwwqqwxxxxxusers) {
		this.yxxxuh566xwwqqwxxxxxusers = yxxxuh566xwwqqwxxxxxusers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Dxxxuq92bxwwqqhefxxxitemjob> getDxxxuq92bxwwqqhefxxxitemjobs() {
		return this.dxxxuq92bxwwqqhefxxxitemjobs;
	}

	public void setDxxxuq92bxwwqqhefxxxitemjobs(
			Set<Dxxxuq92bxwwqqhefxxxitemjob> dxxxuq92bxwwqqhefxxxitemjobs) {
		this.dxxxuq92bxwwqqhefxxxitemjobs = dxxxuq92bxwwqqhefxxxitemjobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> getXoxxuq3e4xwwqqhxxxxxvendqdetailses() {
		return this.xoxxuq3e4xwwqqhxxxxxvendqdetailses;
	}

	public void setXoxxuq3e4xwwqqhxxxxxvendqdetailses(
			Set<Xoxxuq3e4xwwqqhxxxxxvendqdetails> xoxxuq3e4xwwqqhxxxxxvendqdetailses) {
		this.xoxxuq3e4xwwqqhxxxxxvendqdetailses = xoxxuq3e4xwwqqhxxxxxvendqdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jxxxuq201xwwqqhxxxxxcustomer")
	public Set<Fxxxuq89bxwwqqhxxxxxschedule> getFxxxuq89bxwwqqhxxxxxschedules() {
		return this.fxxxuq89bxwwqqhxxxxxschedules;
	}

	public void setFxxxuq89bxwwqqhxxxxxschedules(
			Set<Fxxxuq89bxwwqqhxxxxxschedule> fxxxuq89bxwwqqhxxxxxschedules) {
		this.fxxxuq89bxwwqqhxxxxxschedules = fxxxuq89bxwwqqhxxxxxschedules;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
