package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Lxxxeh177xwwqqhxxxxxcontrolusagebyperiods generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "controlusagebyperiods")
public class Lxxxeh177xwwqqhxxxxxcontrolusagebyperiods
		implements
			java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Xxxxiq1c3xwwqqhxxxxxcontrol xxxxiq1c3xwwqqhxxxxxcontrol;
	private String a0xxukupbvxxxxxxxxxxctlusagetrackerid;
	private String b1xxuszsbvxxxxxxxxxxdescript;
	private String b2xxuxxrbvxxxxxxxxxxcurrency;
	private String b3xxul0rbvxxxxxxxxxxperiod0label;
	private BigDecimal b3xxzxxrlvxxxxxxxxxxperiod0b;
	private BigDecimal z1xxzxxrlvxxxxxxxxxxperiod0;
	private String b4xxul0rbvxxxxxxxxxxperiodtotalslabel;
	private BigDecimal b4xxzxxrlvxxxxxxxxxxperiodtotalsb;
	private BigDecimal z2xxzxxrlvxxxxxxxxxxperiodtotals;
	private String b5xxul0rbvxxxxxxxxxxperiod1label;
	private BigDecimal b5xxzxxrlvxxxxxxxxxxperiod1budget;
	private BigDecimal z5xxzxxrlvxxxxxxxxxxperiod1actual;
	private String b6xxul0rbvxxxxxxxxxxperiod2label;
	private BigDecimal b6xxzxxrlvxxxxxxxxxxperiod2b;
	private BigDecimal z6xxzxxrlvxxxxxxxxxxperiod2;
	private String b7xxul0rbvxxxxxxxxxxperiod3label;
	private BigDecimal b7xxzxxrlvxxxxxxxxxxperiod3b;
	private BigDecimal z7xxzxxrlvxxxxxxxxxxperiod3;
	private String b8xxul0rbvxxxxxxxxxxperiod4label;
	private BigDecimal b8xxzxxrlvxxxxxxxxxxperiod4b;
	private BigDecimal z8xxzxxrlvxxxxxxxxxxperiod4;
	private String b9xxul0rbvxxxxxxxxxxperiod5label;
	private BigDecimal b9xxzxxrlvxxxxxxxxxxperiod5b;
	private BigDecimal z9xxzxxrlvxxxxxxxxxxperiod5;
	private String baxxul0rbvxxxxxxxxxxperiod6label;
	private BigDecimal baxxzxxrlvxxxxxxxxxxperiod6b;
	private BigDecimal zbxxzxxrlvxxxxxxxxxxperiod6;
	private String bbxxul0rbvxxxxxxxxxxperiod7label;
	private BigDecimal bbxxzxxrlvxxxxxxxxxxperiod7b;
	private BigDecimal zbxxzxxrlvxxxxxxxxxxperiod7;
	private String bcxxul0rbvxxxxxxxxxxperiod8label;
	private BigDecimal bcxxzxxrlvxxxxxxxxxxperiod8b;
	private BigDecimal zcxxzxxrlvxxxxxxxxxxperiod8;
	private String bdxxul0rbvxxxxxxxxxxperiod9label;
	private BigDecimal bdxxzxxrlvxxxxxxxxxxperiod9b;
	private BigDecimal zdxxzxxrlvxxxxxxxxxxperiod9;
	private String bexxul0rbvxxxxxxxxxxperiod10label;
	private BigDecimal bexxzxxrlvxxxxxxxxxxperiod10b;
	private BigDecimal zexxzxxrlvxxxxxxxxxxperiod10;
	private String vfxxul0rbvxxxxxxxxxxperiod11label;
	private BigDecimal bfxxzxxrlvxxxxxxxxxxperiod11b;
	private BigDecimal zfxxzxxrlvxxxxxxxxxxperiod11;
	private String bgxxul0rbvxxxxxxxxxxperiod12label;
	private BigDecimal bgxxzxxrlvxxxxxxxxxxperiod12b;
	private BigDecimal zgxxzxxrlvxxxxxxxxxxperiod12;
	private String bnxxul0rbvxxxxxxxxxxperiodnlabel;
	private BigDecimal bhxxzxxrlvxxxxxxxxxxperiodnb;
	private BigDecimal zhxxuxxrbvxxxxxxxxxxperiodn;
	private String y1xxuxznbvxxxxxxxxxxnotes;
	private Integer zixxzzfxhhxxxxxxxxxxstatusfl;
	private Date zjxxcztxlxxxxxxxxxxxstatusfldt;
	private String zjxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Lxxxeh177xwwqqhxxxxxcontrolusagebyperiods() {
	}

	public Lxxxeh177xwwqqhxxxxxcontrolusagebyperiods(
			String a0xxukupbvxxxxxxxxxxctlusagetrackerid) {
		this.a0xxukupbvxxxxxxxxxxctlusagetrackerid = a0xxukupbvxxxxxxxxxxctlusagetrackerid;
	}
	public Lxxxeh177xwwqqhxxxxxcontrolusagebyperiods(
			Xxxxiq1c3xwwqqhxxxxxcontrol xxxxiq1c3xwwqqhxxxxxcontrol,
			String a0xxukupbvxxxxxxxxxxctlusagetrackerid,
			String b1xxuszsbvxxxxxxxxxxdescript,
			String b2xxuxxrbvxxxxxxxxxxcurrency,
			String b3xxul0rbvxxxxxxxxxxperiod0label,
			BigDecimal b3xxzxxrlvxxxxxxxxxxperiod0b,
			BigDecimal z1xxzxxrlvxxxxxxxxxxperiod0,
			String b4xxul0rbvxxxxxxxxxxperiodtotalslabel,
			BigDecimal b4xxzxxrlvxxxxxxxxxxperiodtotalsb,
			BigDecimal z2xxzxxrlvxxxxxxxxxxperiodtotals,
			String b5xxul0rbvxxxxxxxxxxperiod1label,
			BigDecimal b5xxzxxrlvxxxxxxxxxxperiod1budget,
			BigDecimal z5xxzxxrlvxxxxxxxxxxperiod1actual,
			String b6xxul0rbvxxxxxxxxxxperiod2label,
			BigDecimal b6xxzxxrlvxxxxxxxxxxperiod2b,
			BigDecimal z6xxzxxrlvxxxxxxxxxxperiod2,
			String b7xxul0rbvxxxxxxxxxxperiod3label,
			BigDecimal b7xxzxxrlvxxxxxxxxxxperiod3b,
			BigDecimal z7xxzxxrlvxxxxxxxxxxperiod3,
			String b8xxul0rbvxxxxxxxxxxperiod4label,
			BigDecimal b8xxzxxrlvxxxxxxxxxxperiod4b,
			BigDecimal z8xxzxxrlvxxxxxxxxxxperiod4,
			String b9xxul0rbvxxxxxxxxxxperiod5label,
			BigDecimal b9xxzxxrlvxxxxxxxxxxperiod5b,
			BigDecimal z9xxzxxrlvxxxxxxxxxxperiod5,
			String baxxul0rbvxxxxxxxxxxperiod6label,
			BigDecimal baxxzxxrlvxxxxxxxxxxperiod6b,
			BigDecimal zbxxzxxrlvxxxxxxxxxxperiod6,
			String bbxxul0rbvxxxxxxxxxxperiod7label,
			BigDecimal bbxxzxxrlvxxxxxxxxxxperiod7b,
			BigDecimal zbxxzxxrlvxxxxxxxxxxperiod7,
			String bcxxul0rbvxxxxxxxxxxperiod8label,
			BigDecimal bcxxzxxrlvxxxxxxxxxxperiod8b,
			BigDecimal zcxxzxxrlvxxxxxxxxxxperiod8,
			String bdxxul0rbvxxxxxxxxxxperiod9label,
			BigDecimal bdxxzxxrlvxxxxxxxxxxperiod9b,
			BigDecimal zdxxzxxrlvxxxxxxxxxxperiod9,
			String bexxul0rbvxxxxxxxxxxperiod10label,
			BigDecimal bexxzxxrlvxxxxxxxxxxperiod10b,
			BigDecimal zexxzxxrlvxxxxxxxxxxperiod10,
			String vfxxul0rbvxxxxxxxxxxperiod11label,
			BigDecimal bfxxzxxrlvxxxxxxxxxxperiod11b,
			BigDecimal zfxxzxxrlvxxxxxxxxxxperiod11,
			String bgxxul0rbvxxxxxxxxxxperiod12label,
			BigDecimal bgxxzxxrlvxxxxxxxxxxperiod12b,
			BigDecimal zgxxzxxrlvxxxxxxxxxxperiod12,
			String bnxxul0rbvxxxxxxxxxxperiodnlabel,
			BigDecimal bhxxzxxrlvxxxxxxxxxxperiodnb,
			BigDecimal zhxxuxxrbvxxxxxxxxxxperiodn,
			String y1xxuxznbvxxxxxxxxxxnotes,
			Integer zixxzzfxhhxxxxxxxxxxstatusfl,
			Date zjxxcztxlxxxxxxxxxxxstatusfldt,
			String zjxxutoxlhxxxxxxxxxxowner, String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.xxxxiq1c3xwwqqhxxxxxcontrol = xxxxiq1c3xwwqqhxxxxxcontrol;
		this.a0xxukupbvxxxxxxxxxxctlusagetrackerid = a0xxukupbvxxxxxxxxxxctlusagetrackerid;
		this.b1xxuszsbvxxxxxxxxxxdescript = b1xxuszsbvxxxxxxxxxxdescript;
		this.b2xxuxxrbvxxxxxxxxxxcurrency = b2xxuxxrbvxxxxxxxxxxcurrency;
		this.b3xxul0rbvxxxxxxxxxxperiod0label = b3xxul0rbvxxxxxxxxxxperiod0label;
		this.b3xxzxxrlvxxxxxxxxxxperiod0b = b3xxzxxrlvxxxxxxxxxxperiod0b;
		this.z1xxzxxrlvxxxxxxxxxxperiod0 = z1xxzxxrlvxxxxxxxxxxperiod0;
		this.b4xxul0rbvxxxxxxxxxxperiodtotalslabel = b4xxul0rbvxxxxxxxxxxperiodtotalslabel;
		this.b4xxzxxrlvxxxxxxxxxxperiodtotalsb = b4xxzxxrlvxxxxxxxxxxperiodtotalsb;
		this.z2xxzxxrlvxxxxxxxxxxperiodtotals = z2xxzxxrlvxxxxxxxxxxperiodtotals;
		this.b5xxul0rbvxxxxxxxxxxperiod1label = b5xxul0rbvxxxxxxxxxxperiod1label;
		this.b5xxzxxrlvxxxxxxxxxxperiod1budget = b5xxzxxrlvxxxxxxxxxxperiod1budget;
		this.z5xxzxxrlvxxxxxxxxxxperiod1actual = z5xxzxxrlvxxxxxxxxxxperiod1actual;
		this.b6xxul0rbvxxxxxxxxxxperiod2label = b6xxul0rbvxxxxxxxxxxperiod2label;
		this.b6xxzxxrlvxxxxxxxxxxperiod2b = b6xxzxxrlvxxxxxxxxxxperiod2b;
		this.z6xxzxxrlvxxxxxxxxxxperiod2 = z6xxzxxrlvxxxxxxxxxxperiod2;
		this.b7xxul0rbvxxxxxxxxxxperiod3label = b7xxul0rbvxxxxxxxxxxperiod3label;
		this.b7xxzxxrlvxxxxxxxxxxperiod3b = b7xxzxxrlvxxxxxxxxxxperiod3b;
		this.z7xxzxxrlvxxxxxxxxxxperiod3 = z7xxzxxrlvxxxxxxxxxxperiod3;
		this.b8xxul0rbvxxxxxxxxxxperiod4label = b8xxul0rbvxxxxxxxxxxperiod4label;
		this.b8xxzxxrlvxxxxxxxxxxperiod4b = b8xxzxxrlvxxxxxxxxxxperiod4b;
		this.z8xxzxxrlvxxxxxxxxxxperiod4 = z8xxzxxrlvxxxxxxxxxxperiod4;
		this.b9xxul0rbvxxxxxxxxxxperiod5label = b9xxul0rbvxxxxxxxxxxperiod5label;
		this.b9xxzxxrlvxxxxxxxxxxperiod5b = b9xxzxxrlvxxxxxxxxxxperiod5b;
		this.z9xxzxxrlvxxxxxxxxxxperiod5 = z9xxzxxrlvxxxxxxxxxxperiod5;
		this.baxxul0rbvxxxxxxxxxxperiod6label = baxxul0rbvxxxxxxxxxxperiod6label;
		this.baxxzxxrlvxxxxxxxxxxperiod6b = baxxzxxrlvxxxxxxxxxxperiod6b;
		this.zbxxzxxrlvxxxxxxxxxxperiod6 = zbxxzxxrlvxxxxxxxxxxperiod6;
		this.bbxxul0rbvxxxxxxxxxxperiod7label = bbxxul0rbvxxxxxxxxxxperiod7label;
		this.bbxxzxxrlvxxxxxxxxxxperiod7b = bbxxzxxrlvxxxxxxxxxxperiod7b;
		this.zbxxzxxrlvxxxxxxxxxxperiod7 = zbxxzxxrlvxxxxxxxxxxperiod7;
		this.bcxxul0rbvxxxxxxxxxxperiod8label = bcxxul0rbvxxxxxxxxxxperiod8label;
		this.bcxxzxxrlvxxxxxxxxxxperiod8b = bcxxzxxrlvxxxxxxxxxxperiod8b;
		this.zcxxzxxrlvxxxxxxxxxxperiod8 = zcxxzxxrlvxxxxxxxxxxperiod8;
		this.bdxxul0rbvxxxxxxxxxxperiod9label = bdxxul0rbvxxxxxxxxxxperiod9label;
		this.bdxxzxxrlvxxxxxxxxxxperiod9b = bdxxzxxrlvxxxxxxxxxxperiod9b;
		this.zdxxzxxrlvxxxxxxxxxxperiod9 = zdxxzxxrlvxxxxxxxxxxperiod9;
		this.bexxul0rbvxxxxxxxxxxperiod10label = bexxul0rbvxxxxxxxxxxperiod10label;
		this.bexxzxxrlvxxxxxxxxxxperiod10b = bexxzxxrlvxxxxxxxxxxperiod10b;
		this.zexxzxxrlvxxxxxxxxxxperiod10 = zexxzxxrlvxxxxxxxxxxperiod10;
		this.vfxxul0rbvxxxxxxxxxxperiod11label = vfxxul0rbvxxxxxxxxxxperiod11label;
		this.bfxxzxxrlvxxxxxxxxxxperiod11b = bfxxzxxrlvxxxxxxxxxxperiod11b;
		this.zfxxzxxrlvxxxxxxxxxxperiod11 = zfxxzxxrlvxxxxxxxxxxperiod11;
		this.bgxxul0rbvxxxxxxxxxxperiod12label = bgxxul0rbvxxxxxxxxxxperiod12label;
		this.bgxxzxxrlvxxxxxxxxxxperiod12b = bgxxzxxrlvxxxxxxxxxxperiod12b;
		this.zgxxzxxrlvxxxxxxxxxxperiod12 = zgxxzxxrlvxxxxxxxxxxperiod12;
		this.bnxxul0rbvxxxxxxxxxxperiodnlabel = bnxxul0rbvxxxxxxxxxxperiodnlabel;
		this.bhxxzxxrlvxxxxxxxxxxperiodnb = bhxxzxxrlvxxxxxxxxxxperiodnb;
		this.zhxxuxxrbvxxxxxxxxxxperiodn = zhxxuxxrbvxxxxxxxxxxperiodn;
		this.y1xxuxznbvxxxxxxxxxxnotes = y1xxuxznbvxxxxxxxxxxnotes;
		this.zixxzzfxhhxxxxxxxxxxstatusfl = zixxzzfxhhxxxxxxxxxxstatusfl;
		this.zjxxcztxlxxxxxxxxxxxstatusfldt = zjxxcztxlxxxxxxxxxxxstatusfldt;
		this.zjxxutoxlhxxxxxxxxxxowner = zjxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "controlcode")
	public Xxxxiq1c3xwwqqhxxxxxcontrol getXxxxiq1c3xwwqqhxxxxxcontrol() {
		return this.xxxxiq1c3xwwqqhxxxxxcontrol;
	}

	public void setXxxxiq1c3xwwqqhxxxxxcontrol(
			Xxxxiq1c3xwwqqhxxxxxcontrol xxxxiq1c3xwwqqhxxxxxcontrol) {
		this.xxxxiq1c3xwwqqhxxxxxcontrol = xxxxiq1c3xwwqqhxxxxxcontrol;
	}

	@Column(name = "ctlusagetrackerid", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukupbvxxxxxxxxxxctlusagetrackerid() {
		return this.a0xxukupbvxxxxxxxxxxctlusagetrackerid;
	}

	public void setA0xxukupbvxxxxxxxxxxctlusagetrackerid(
			String a0xxukupbvxxxxxxxxxxctlusagetrackerid) {
		this.a0xxukupbvxxxxxxxxxxctlusagetrackerid = a0xxukupbvxxxxxxxxxxctlusagetrackerid;
	}

	@Column(name = "descript", length = 120)
	@Size(max = 120)
	public String getB1xxuszsbvxxxxxxxxxxdescript() {
		return this.b1xxuszsbvxxxxxxxxxxdescript;
	}

	public void setB1xxuszsbvxxxxxxxxxxdescript(
			String b1xxuszsbvxxxxxxxxxxdescript) {
		this.b1xxuszsbvxxxxxxxxxxdescript = b1xxuszsbvxxxxxxxxxxdescript;
	}

	@Column(name = "currency", length = 3)
	@Size(max = 3)
	public String getB2xxuxxrbvxxxxxxxxxxcurrency() {
		return this.b2xxuxxrbvxxxxxxxxxxcurrency;
	}

	public void setB2xxuxxrbvxxxxxxxxxxcurrency(
			String b2xxuxxrbvxxxxxxxxxxcurrency) {
		this.b2xxuxxrbvxxxxxxxxxxcurrency = b2xxuxxrbvxxxxxxxxxxcurrency;
	}

	@Column(name = "period0label", length = 20)
	@Size(max = 20)
	public String getB3xxul0rbvxxxxxxxxxxperiod0label() {
		return this.b3xxul0rbvxxxxxxxxxxperiod0label;
	}

	public void setB3xxul0rbvxxxxxxxxxxperiod0label(
			String b3xxul0rbvxxxxxxxxxxperiod0label) {
		this.b3xxul0rbvxxxxxxxxxxperiod0label = b3xxul0rbvxxxxxxxxxxperiod0label;
	}

	@Column(name = "period0b", precision = 14)
	public BigDecimal getB3xxzxxrlvxxxxxxxxxxperiod0b() {
		return this.b3xxzxxrlvxxxxxxxxxxperiod0b;
	}

	public void setB3xxzxxrlvxxxxxxxxxxperiod0b(
			BigDecimal b3xxzxxrlvxxxxxxxxxxperiod0b) {
		this.b3xxzxxrlvxxxxxxxxxxperiod0b = b3xxzxxrlvxxxxxxxxxxperiod0b;
	}

	@Column(name = "period0", precision = 14)
	public BigDecimal getZ1xxzxxrlvxxxxxxxxxxperiod0() {
		return this.z1xxzxxrlvxxxxxxxxxxperiod0;
	}

	public void setZ1xxzxxrlvxxxxxxxxxxperiod0(
			BigDecimal z1xxzxxrlvxxxxxxxxxxperiod0) {
		this.z1xxzxxrlvxxxxxxxxxxperiod0 = z1xxzxxrlvxxxxxxxxxxperiod0;
	}

	@Column(name = "periodtotalslabel", length = 20)
	@Size(max = 20)
	public String getB4xxul0rbvxxxxxxxxxxperiodtotalslabel() {
		return this.b4xxul0rbvxxxxxxxxxxperiodtotalslabel;
	}

	public void setB4xxul0rbvxxxxxxxxxxperiodtotalslabel(
			String b4xxul0rbvxxxxxxxxxxperiodtotalslabel) {
		this.b4xxul0rbvxxxxxxxxxxperiodtotalslabel = b4xxul0rbvxxxxxxxxxxperiodtotalslabel;
	}

	@Column(name = "periodtotalsb", precision = 14)
	public BigDecimal getB4xxzxxrlvxxxxxxxxxxperiodtotalsb() {
		return this.b4xxzxxrlvxxxxxxxxxxperiodtotalsb;
	}

	public void setB4xxzxxrlvxxxxxxxxxxperiodtotalsb(
			BigDecimal b4xxzxxrlvxxxxxxxxxxperiodtotalsb) {
		this.b4xxzxxrlvxxxxxxxxxxperiodtotalsb = b4xxzxxrlvxxxxxxxxxxperiodtotalsb;
	}

	@Column(name = "periodtotals", precision = 14)
	public BigDecimal getZ2xxzxxrlvxxxxxxxxxxperiodtotals() {
		return this.z2xxzxxrlvxxxxxxxxxxperiodtotals;
	}

	public void setZ2xxzxxrlvxxxxxxxxxxperiodtotals(
			BigDecimal z2xxzxxrlvxxxxxxxxxxperiodtotals) {
		this.z2xxzxxrlvxxxxxxxxxxperiodtotals = z2xxzxxrlvxxxxxxxxxxperiodtotals;
	}

	@Column(name = "period1label", length = 20)
	@Size(max = 20)
	public String getB5xxul0rbvxxxxxxxxxxperiod1label() {
		return this.b5xxul0rbvxxxxxxxxxxperiod1label;
	}

	public void setB5xxul0rbvxxxxxxxxxxperiod1label(
			String b5xxul0rbvxxxxxxxxxxperiod1label) {
		this.b5xxul0rbvxxxxxxxxxxperiod1label = b5xxul0rbvxxxxxxxxxxperiod1label;
	}

	@Column(name = "period1budget", precision = 14)
	public BigDecimal getB5xxzxxrlvxxxxxxxxxxperiod1budget() {
		return this.b5xxzxxrlvxxxxxxxxxxperiod1budget;
	}

	public void setB5xxzxxrlvxxxxxxxxxxperiod1budget(
			BigDecimal b5xxzxxrlvxxxxxxxxxxperiod1budget) {
		this.b5xxzxxrlvxxxxxxxxxxperiod1budget = b5xxzxxrlvxxxxxxxxxxperiod1budget;
	}

	@Column(name = "period1actual", precision = 14)
	public BigDecimal getZ5xxzxxrlvxxxxxxxxxxperiod1actual() {
		return this.z5xxzxxrlvxxxxxxxxxxperiod1actual;
	}

	public void setZ5xxzxxrlvxxxxxxxxxxperiod1actual(
			BigDecimal z5xxzxxrlvxxxxxxxxxxperiod1actual) {
		this.z5xxzxxrlvxxxxxxxxxxperiod1actual = z5xxzxxrlvxxxxxxxxxxperiod1actual;
	}

	@Column(name = "period2label", length = 20)
	@Size(max = 20)
	public String getB6xxul0rbvxxxxxxxxxxperiod2label() {
		return this.b6xxul0rbvxxxxxxxxxxperiod2label;
	}

	public void setB6xxul0rbvxxxxxxxxxxperiod2label(
			String b6xxul0rbvxxxxxxxxxxperiod2label) {
		this.b6xxul0rbvxxxxxxxxxxperiod2label = b6xxul0rbvxxxxxxxxxxperiod2label;
	}

	@Column(name = "period2b", precision = 14)
	public BigDecimal getB6xxzxxrlvxxxxxxxxxxperiod2b() {
		return this.b6xxzxxrlvxxxxxxxxxxperiod2b;
	}

	public void setB6xxzxxrlvxxxxxxxxxxperiod2b(
			BigDecimal b6xxzxxrlvxxxxxxxxxxperiod2b) {
		this.b6xxzxxrlvxxxxxxxxxxperiod2b = b6xxzxxrlvxxxxxxxxxxperiod2b;
	}

	@Column(name = "period2", precision = 14)
	public BigDecimal getZ6xxzxxrlvxxxxxxxxxxperiod2() {
		return this.z6xxzxxrlvxxxxxxxxxxperiod2;
	}

	public void setZ6xxzxxrlvxxxxxxxxxxperiod2(
			BigDecimal z6xxzxxrlvxxxxxxxxxxperiod2) {
		this.z6xxzxxrlvxxxxxxxxxxperiod2 = z6xxzxxrlvxxxxxxxxxxperiod2;
	}

	@Column(name = "period3label", length = 20)
	@Size(max = 20)
	public String getB7xxul0rbvxxxxxxxxxxperiod3label() {
		return this.b7xxul0rbvxxxxxxxxxxperiod3label;
	}

	public void setB7xxul0rbvxxxxxxxxxxperiod3label(
			String b7xxul0rbvxxxxxxxxxxperiod3label) {
		this.b7xxul0rbvxxxxxxxxxxperiod3label = b7xxul0rbvxxxxxxxxxxperiod3label;
	}

	@Column(name = "period3b", precision = 14)
	public BigDecimal getB7xxzxxrlvxxxxxxxxxxperiod3b() {
		return this.b7xxzxxrlvxxxxxxxxxxperiod3b;
	}

	public void setB7xxzxxrlvxxxxxxxxxxperiod3b(
			BigDecimal b7xxzxxrlvxxxxxxxxxxperiod3b) {
		this.b7xxzxxrlvxxxxxxxxxxperiod3b = b7xxzxxrlvxxxxxxxxxxperiod3b;
	}

	@Column(name = "period3", precision = 14)
	public BigDecimal getZ7xxzxxrlvxxxxxxxxxxperiod3() {
		return this.z7xxzxxrlvxxxxxxxxxxperiod3;
	}

	public void setZ7xxzxxrlvxxxxxxxxxxperiod3(
			BigDecimal z7xxzxxrlvxxxxxxxxxxperiod3) {
		this.z7xxzxxrlvxxxxxxxxxxperiod3 = z7xxzxxrlvxxxxxxxxxxperiod3;
	}

	@Column(name = "period4label", length = 20)
	@Size(max = 20)
	public String getB8xxul0rbvxxxxxxxxxxperiod4label() {
		return this.b8xxul0rbvxxxxxxxxxxperiod4label;
	}

	public void setB8xxul0rbvxxxxxxxxxxperiod4label(
			String b8xxul0rbvxxxxxxxxxxperiod4label) {
		this.b8xxul0rbvxxxxxxxxxxperiod4label = b8xxul0rbvxxxxxxxxxxperiod4label;
	}

	@Column(name = "period4b", precision = 14)
	public BigDecimal getB8xxzxxrlvxxxxxxxxxxperiod4b() {
		return this.b8xxzxxrlvxxxxxxxxxxperiod4b;
	}

	public void setB8xxzxxrlvxxxxxxxxxxperiod4b(
			BigDecimal b8xxzxxrlvxxxxxxxxxxperiod4b) {
		this.b8xxzxxrlvxxxxxxxxxxperiod4b = b8xxzxxrlvxxxxxxxxxxperiod4b;
	}

	@Column(name = "period4", precision = 14)
	public BigDecimal getZ8xxzxxrlvxxxxxxxxxxperiod4() {
		return this.z8xxzxxrlvxxxxxxxxxxperiod4;
	}

	public void setZ8xxzxxrlvxxxxxxxxxxperiod4(
			BigDecimal z8xxzxxrlvxxxxxxxxxxperiod4) {
		this.z8xxzxxrlvxxxxxxxxxxperiod4 = z8xxzxxrlvxxxxxxxxxxperiod4;
	}

	@Column(name = "period5label", length = 20)
	@Size(max = 20)
	public String getB9xxul0rbvxxxxxxxxxxperiod5label() {
		return this.b9xxul0rbvxxxxxxxxxxperiod5label;
	}

	public void setB9xxul0rbvxxxxxxxxxxperiod5label(
			String b9xxul0rbvxxxxxxxxxxperiod5label) {
		this.b9xxul0rbvxxxxxxxxxxperiod5label = b9xxul0rbvxxxxxxxxxxperiod5label;
	}

	@Column(name = "period5b", precision = 14)
	public BigDecimal getB9xxzxxrlvxxxxxxxxxxperiod5b() {
		return this.b9xxzxxrlvxxxxxxxxxxperiod5b;
	}

	public void setB9xxzxxrlvxxxxxxxxxxperiod5b(
			BigDecimal b9xxzxxrlvxxxxxxxxxxperiod5b) {
		this.b9xxzxxrlvxxxxxxxxxxperiod5b = b9xxzxxrlvxxxxxxxxxxperiod5b;
	}

	@Column(name = "period5", precision = 14)
	public BigDecimal getZ9xxzxxrlvxxxxxxxxxxperiod5() {
		return this.z9xxzxxrlvxxxxxxxxxxperiod5;
	}

	public void setZ9xxzxxrlvxxxxxxxxxxperiod5(
			BigDecimal z9xxzxxrlvxxxxxxxxxxperiod5) {
		this.z9xxzxxrlvxxxxxxxxxxperiod5 = z9xxzxxrlvxxxxxxxxxxperiod5;
	}

	@Column(name = "period6label", length = 20)
	@Size(max = 20)
	public String getBaxxul0rbvxxxxxxxxxxperiod6label() {
		return this.baxxul0rbvxxxxxxxxxxperiod6label;
	}

	public void setBaxxul0rbvxxxxxxxxxxperiod6label(
			String baxxul0rbvxxxxxxxxxxperiod6label) {
		this.baxxul0rbvxxxxxxxxxxperiod6label = baxxul0rbvxxxxxxxxxxperiod6label;
	}

	@Column(name = "period6b", precision = 14)
	public BigDecimal getBaxxzxxrlvxxxxxxxxxxperiod6b() {
		return this.baxxzxxrlvxxxxxxxxxxperiod6b;
	}

	public void setBaxxzxxrlvxxxxxxxxxxperiod6b(
			BigDecimal baxxzxxrlvxxxxxxxxxxperiod6b) {
		this.baxxzxxrlvxxxxxxxxxxperiod6b = baxxzxxrlvxxxxxxxxxxperiod6b;
	}

	@Column(name = "period6", precision = 14)
	public BigDecimal getZbxxzxxrlvxxxxxxxxxxperiod6() {
		return this.zbxxzxxrlvxxxxxxxxxxperiod6;
	}

	public void setZbxxzxxrlvxxxxxxxxxxperiod6(
			BigDecimal zbxxzxxrlvxxxxxxxxxxperiod6) {
		this.zbxxzxxrlvxxxxxxxxxxperiod6 = zbxxzxxrlvxxxxxxxxxxperiod6;
	}

	@Column(name = "period7label", length = 20)
	@Size(max = 20)
	public String getBbxxul0rbvxxxxxxxxxxperiod7label() {
		return this.bbxxul0rbvxxxxxxxxxxperiod7label;
	}

	public void setBbxxul0rbvxxxxxxxxxxperiod7label(
			String bbxxul0rbvxxxxxxxxxxperiod7label) {
		this.bbxxul0rbvxxxxxxxxxxperiod7label = bbxxul0rbvxxxxxxxxxxperiod7label;
	}

	@Column(name = "period7b", precision = 14)
	public BigDecimal getBbxxzxxrlvxxxxxxxxxxperiod7b() {
		return this.bbxxzxxrlvxxxxxxxxxxperiod7b;
	}

	public void setBbxxzxxrlvxxxxxxxxxxperiod7b(
			BigDecimal bbxxzxxrlvxxxxxxxxxxperiod7b) {
		this.bbxxzxxrlvxxxxxxxxxxperiod7b = bbxxzxxrlvxxxxxxxxxxperiod7b;
	}

	@Column(name = "period7", precision = 14)
	public BigDecimal getZbxxzxxrlvxxxxxxxxxxperiod7() {
		return this.zbxxzxxrlvxxxxxxxxxxperiod7;
	}

	public void setZbxxzxxrlvxxxxxxxxxxperiod7(
			BigDecimal zbxxzxxrlvxxxxxxxxxxperiod7) {
		this.zbxxzxxrlvxxxxxxxxxxperiod7 = zbxxzxxrlvxxxxxxxxxxperiod7;
	}

	@Column(name = "period8label", length = 20)
	@Size(max = 20)
	public String getBcxxul0rbvxxxxxxxxxxperiod8label() {
		return this.bcxxul0rbvxxxxxxxxxxperiod8label;
	}

	public void setBcxxul0rbvxxxxxxxxxxperiod8label(
			String bcxxul0rbvxxxxxxxxxxperiod8label) {
		this.bcxxul0rbvxxxxxxxxxxperiod8label = bcxxul0rbvxxxxxxxxxxperiod8label;
	}

	@Column(name = "period8b", precision = 14)
	public BigDecimal getBcxxzxxrlvxxxxxxxxxxperiod8b() {
		return this.bcxxzxxrlvxxxxxxxxxxperiod8b;
	}

	public void setBcxxzxxrlvxxxxxxxxxxperiod8b(
			BigDecimal bcxxzxxrlvxxxxxxxxxxperiod8b) {
		this.bcxxzxxrlvxxxxxxxxxxperiod8b = bcxxzxxrlvxxxxxxxxxxperiod8b;
	}

	@Column(name = "period8", precision = 14)
	public BigDecimal getZcxxzxxrlvxxxxxxxxxxperiod8() {
		return this.zcxxzxxrlvxxxxxxxxxxperiod8;
	}

	public void setZcxxzxxrlvxxxxxxxxxxperiod8(
			BigDecimal zcxxzxxrlvxxxxxxxxxxperiod8) {
		this.zcxxzxxrlvxxxxxxxxxxperiod8 = zcxxzxxrlvxxxxxxxxxxperiod8;
	}

	@Column(name = "period9label", length = 20)
	@Size(max = 20)
	public String getBdxxul0rbvxxxxxxxxxxperiod9label() {
		return this.bdxxul0rbvxxxxxxxxxxperiod9label;
	}

	public void setBdxxul0rbvxxxxxxxxxxperiod9label(
			String bdxxul0rbvxxxxxxxxxxperiod9label) {
		this.bdxxul0rbvxxxxxxxxxxperiod9label = bdxxul0rbvxxxxxxxxxxperiod9label;
	}

	@Column(name = "period9b", precision = 14)
	public BigDecimal getBdxxzxxrlvxxxxxxxxxxperiod9b() {
		return this.bdxxzxxrlvxxxxxxxxxxperiod9b;
	}

	public void setBdxxzxxrlvxxxxxxxxxxperiod9b(
			BigDecimal bdxxzxxrlvxxxxxxxxxxperiod9b) {
		this.bdxxzxxrlvxxxxxxxxxxperiod9b = bdxxzxxrlvxxxxxxxxxxperiod9b;
	}

	@Column(name = "period9", precision = 14)
	public BigDecimal getZdxxzxxrlvxxxxxxxxxxperiod9() {
		return this.zdxxzxxrlvxxxxxxxxxxperiod9;
	}

	public void setZdxxzxxrlvxxxxxxxxxxperiod9(
			BigDecimal zdxxzxxrlvxxxxxxxxxxperiod9) {
		this.zdxxzxxrlvxxxxxxxxxxperiod9 = zdxxzxxrlvxxxxxxxxxxperiod9;
	}

	@Column(name = "period10label", length = 20)
	@Size(max = 20)
	public String getBexxul0rbvxxxxxxxxxxperiod10label() {
		return this.bexxul0rbvxxxxxxxxxxperiod10label;
	}

	public void setBexxul0rbvxxxxxxxxxxperiod10label(
			String bexxul0rbvxxxxxxxxxxperiod10label) {
		this.bexxul0rbvxxxxxxxxxxperiod10label = bexxul0rbvxxxxxxxxxxperiod10label;
	}

	@Column(name = "period10b", precision = 14)
	public BigDecimal getBexxzxxrlvxxxxxxxxxxperiod10b() {
		return this.bexxzxxrlvxxxxxxxxxxperiod10b;
	}

	public void setBexxzxxrlvxxxxxxxxxxperiod10b(
			BigDecimal bexxzxxrlvxxxxxxxxxxperiod10b) {
		this.bexxzxxrlvxxxxxxxxxxperiod10b = bexxzxxrlvxxxxxxxxxxperiod10b;
	}

	@Column(name = "period10", precision = 14)
	public BigDecimal getZexxzxxrlvxxxxxxxxxxperiod10() {
		return this.zexxzxxrlvxxxxxxxxxxperiod10;
	}

	public void setZexxzxxrlvxxxxxxxxxxperiod10(
			BigDecimal zexxzxxrlvxxxxxxxxxxperiod10) {
		this.zexxzxxrlvxxxxxxxxxxperiod10 = zexxzxxrlvxxxxxxxxxxperiod10;
	}

	@Column(name = "period11label", length = 20)
	@Size(max = 20)
	public String getVfxxul0rbvxxxxxxxxxxperiod11label() {
		return this.vfxxul0rbvxxxxxxxxxxperiod11label;
	}

	public void setVfxxul0rbvxxxxxxxxxxperiod11label(
			String vfxxul0rbvxxxxxxxxxxperiod11label) {
		this.vfxxul0rbvxxxxxxxxxxperiod11label = vfxxul0rbvxxxxxxxxxxperiod11label;
	}

	@Column(name = "period11b", precision = 14)
	public BigDecimal getBfxxzxxrlvxxxxxxxxxxperiod11b() {
		return this.bfxxzxxrlvxxxxxxxxxxperiod11b;
	}

	public void setBfxxzxxrlvxxxxxxxxxxperiod11b(
			BigDecimal bfxxzxxrlvxxxxxxxxxxperiod11b) {
		this.bfxxzxxrlvxxxxxxxxxxperiod11b = bfxxzxxrlvxxxxxxxxxxperiod11b;
	}

	@Column(name = "period11", precision = 14)
	public BigDecimal getZfxxzxxrlvxxxxxxxxxxperiod11() {
		return this.zfxxzxxrlvxxxxxxxxxxperiod11;
	}

	public void setZfxxzxxrlvxxxxxxxxxxperiod11(
			BigDecimal zfxxzxxrlvxxxxxxxxxxperiod11) {
		this.zfxxzxxrlvxxxxxxxxxxperiod11 = zfxxzxxrlvxxxxxxxxxxperiod11;
	}

	@Column(name = "period12label", length = 20)
	@Size(max = 20)
	public String getBgxxul0rbvxxxxxxxxxxperiod12label() {
		return this.bgxxul0rbvxxxxxxxxxxperiod12label;
	}

	public void setBgxxul0rbvxxxxxxxxxxperiod12label(
			String bgxxul0rbvxxxxxxxxxxperiod12label) {
		this.bgxxul0rbvxxxxxxxxxxperiod12label = bgxxul0rbvxxxxxxxxxxperiod12label;
	}

	@Column(name = "period12b", precision = 14)
	public BigDecimal getBgxxzxxrlvxxxxxxxxxxperiod12b() {
		return this.bgxxzxxrlvxxxxxxxxxxperiod12b;
	}

	public void setBgxxzxxrlvxxxxxxxxxxperiod12b(
			BigDecimal bgxxzxxrlvxxxxxxxxxxperiod12b) {
		this.bgxxzxxrlvxxxxxxxxxxperiod12b = bgxxzxxrlvxxxxxxxxxxperiod12b;
	}

	@Column(name = "period12", precision = 14)
	public BigDecimal getZgxxzxxrlvxxxxxxxxxxperiod12() {
		return this.zgxxzxxrlvxxxxxxxxxxperiod12;
	}

	public void setZgxxzxxrlvxxxxxxxxxxperiod12(
			BigDecimal zgxxzxxrlvxxxxxxxxxxperiod12) {
		this.zgxxzxxrlvxxxxxxxxxxperiod12 = zgxxzxxrlvxxxxxxxxxxperiod12;
	}

	@Column(name = "periodnlabel", length = 20)
	@Size(max = 20)
	public String getBnxxul0rbvxxxxxxxxxxperiodnlabel() {
		return this.bnxxul0rbvxxxxxxxxxxperiodnlabel;
	}

	public void setBnxxul0rbvxxxxxxxxxxperiodnlabel(
			String bnxxul0rbvxxxxxxxxxxperiodnlabel) {
		this.bnxxul0rbvxxxxxxxxxxperiodnlabel = bnxxul0rbvxxxxxxxxxxperiodnlabel;
	}

	@Column(name = "periodnb", precision = 14)
	public BigDecimal getBhxxzxxrlvxxxxxxxxxxperiodnb() {
		return this.bhxxzxxrlvxxxxxxxxxxperiodnb;
	}

	public void setBhxxzxxrlvxxxxxxxxxxperiodnb(
			BigDecimal bhxxzxxrlvxxxxxxxxxxperiodnb) {
		this.bhxxzxxrlvxxxxxxxxxxperiodnb = bhxxzxxrlvxxxxxxxxxxperiodnb;
	}

	@Column(name = "periodn", precision = 14)
	public BigDecimal getZhxxuxxrbvxxxxxxxxxxperiodn() {
		return this.zhxxuxxrbvxxxxxxxxxxperiodn;
	}

	public void setZhxxuxxrbvxxxxxxxxxxperiodn(
			BigDecimal zhxxuxxrbvxxxxxxxxxxperiodn) {
		this.zhxxuxxrbvxxxxxxxxxxperiodn = zhxxuxxrbvxxxxxxxxxxperiodn;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY1xxuxznbvxxxxxxxxxxnotes() {
		return this.y1xxuxznbvxxxxxxxxxxnotes;
	}

	public void setY1xxuxznbvxxxxxxxxxxnotes(String y1xxuxznbvxxxxxxxxxxnotes) {
		this.y1xxuxznbvxxxxxxxxxxnotes = y1xxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "statusfl")
	public Integer getZixxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zixxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZixxzzfxhhxxxxxxxxxxstatusfl(
			Integer zixxzzfxhhxxxxxxxxxxstatusfl) {
		this.zixxzzfxhhxxxxxxxxxxstatusfl = zixxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZjxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zjxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZjxxcztxlxxxxxxxxxxxstatusfldt(
			Date zjxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zjxxcztxlxxxxxxxxxxxstatusfldt = zjxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZjxxutoxlhxxxxxxxxxxowner() {
		return this.zjxxutoxlhxxxxxxxxxxowner;
	}

	public void setZjxxutoxlhxxxxxxxxxxowner(String zjxxutoxlhxxxxxxxxxxowner) {
		this.zjxxutoxlhxxxxxxxxxxowner = zjxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
