package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Nxxxiha4rxwwqqhxxxxxgenfields generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "rgenfields")
public class Nxxxiha4rxwwqqhxxxxxgenfields implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Nxxxiha3rxwwqqhxxxxxgentable nxxxiha3rxwwqqhxxxxxgentable;
	private Nxxxiha2rxwwqqhxxxxxgendb nxxxiha2rxwwqqhxxxxxgendb;
	private String a0xxukxxbxxxxxxxxxxxfieldname;
	private String b2xxgxxxbvxxxxxxxxxxfieldtype;
	private String b2xxgxxxbv10xxxxxxxxfieldlength;
	private String b2xxgxxxbv08xxxxxxxxingroup;
	private Integer b3xxgxxxbv09xxxxxxxxseqwithingroup;
	private Integer b4xxgxxxbv10xxxxxxxxfocusseq;
	private String c1xxuxxxbvxxxxxxxxxxfuture1;
	private String c2xxgxxxbv12xxxxxxxxinitialvalue;
	private String d1xxgxxxbv13xxxxxxxxkeyoradditional;
	private String d2xxgxxxbv14xxxxxxxxkeyoradditional2;
	private String d3xxgxxxbv15xxxxxxxxkeyoradditional3;
	private String e1xxgxxxbv16xxxxxxxxshowinmenu;
	private String e2xxgxxxbv17xxxxxxxxshowinreport;
	private String f1xxgxxxbv18xxxxxxxxprocessoption1;
	private String f2xxuxxxbvxxxxxxxxxxprocessoption2;
	private String f3xxuhxxbvxxxxxxxxxxfdbcode;
	private String f4xxuhxxbvxxxxxxxxxxftablename;
	private String f6xxuxxxbvxxxxxxxxxxffieldkeyname1;
	private String f6xxuxxxbvxxxxxxxxxxffieldkeyname2;
	private String f6xxuxxxbvxxxxxxxxxxffieldkeyname3;
	private Integer zexxzzfxhhxxxxxxxxxxstatusfl;
	private Date zfxxcztxlxxxxxxxxxxxstatusfldt;
	private String zgxxuxznbvxxxxxxxxxxnotes;
	private String zhxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Nxxxiha4rxwwqqhxxxxxgenfields() {
	}

	public Nxxxiha4rxwwqqhxxxxxgenfields(String a0xxukxxbxxxxxxxxxxxfieldname) {
		this.a0xxukxxbxxxxxxxxxxxfieldname = a0xxukxxbxxxxxxxxxxxfieldname;
	}
	public Nxxxiha4rxwwqqhxxxxxgenfields(
			Nxxxiha3rxwwqqhxxxxxgentable nxxxiha3rxwwqqhxxxxxgentable,
			Nxxxiha2rxwwqqhxxxxxgendb nxxxiha2rxwwqqhxxxxxgendb,
			String a0xxukxxbxxxxxxxxxxxfieldname,
			String b2xxgxxxbvxxxxxxxxxxfieldtype,
			String b2xxgxxxbv10xxxxxxxxfieldlength,
			String b2xxgxxxbv08xxxxxxxxingroup,
			Integer b3xxgxxxbv09xxxxxxxxseqwithingroup,
			Integer b4xxgxxxbv10xxxxxxxxfocusseq,
			String c1xxuxxxbvxxxxxxxxxxfuture1,
			String c2xxgxxxbv12xxxxxxxxinitialvalue,
			String d1xxgxxxbv13xxxxxxxxkeyoradditional,
			String d2xxgxxxbv14xxxxxxxxkeyoradditional2,
			String d3xxgxxxbv15xxxxxxxxkeyoradditional3,
			String e1xxgxxxbv16xxxxxxxxshowinmenu,
			String e2xxgxxxbv17xxxxxxxxshowinreport,
			String f1xxgxxxbv18xxxxxxxxprocessoption1,
			String f2xxuxxxbvxxxxxxxxxxprocessoption2,
			String f3xxuhxxbvxxxxxxxxxxfdbcode,
			String f4xxuhxxbvxxxxxxxxxxftablename,
			String f6xxuxxxbvxxxxxxxxxxffieldkeyname1,
			String f6xxuxxxbvxxxxxxxxxxffieldkeyname2,
			String f6xxuxxxbvxxxxxxxxxxffieldkeyname3,
			Integer zexxzzfxhhxxxxxxxxxxstatusfl,
			Date zfxxcztxlxxxxxxxxxxxstatusfldt,
			String zgxxuxznbvxxxxxxxxxxnotes, String zhxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.nxxxiha3rxwwqqhxxxxxgentable = nxxxiha3rxwwqqhxxxxxgentable;
		this.nxxxiha2rxwwqqhxxxxxgendb = nxxxiha2rxwwqqhxxxxxgendb;
		this.a0xxukxxbxxxxxxxxxxxfieldname = a0xxukxxbxxxxxxxxxxxfieldname;
		this.b2xxgxxxbvxxxxxxxxxxfieldtype = b2xxgxxxbvxxxxxxxxxxfieldtype;
		this.b2xxgxxxbv10xxxxxxxxfieldlength = b2xxgxxxbv10xxxxxxxxfieldlength;
		this.b2xxgxxxbv08xxxxxxxxingroup = b2xxgxxxbv08xxxxxxxxingroup;
		this.b3xxgxxxbv09xxxxxxxxseqwithingroup = b3xxgxxxbv09xxxxxxxxseqwithingroup;
		this.b4xxgxxxbv10xxxxxxxxfocusseq = b4xxgxxxbv10xxxxxxxxfocusseq;
		this.c1xxuxxxbvxxxxxxxxxxfuture1 = c1xxuxxxbvxxxxxxxxxxfuture1;
		this.c2xxgxxxbv12xxxxxxxxinitialvalue = c2xxgxxxbv12xxxxxxxxinitialvalue;
		this.d1xxgxxxbv13xxxxxxxxkeyoradditional = d1xxgxxxbv13xxxxxxxxkeyoradditional;
		this.d2xxgxxxbv14xxxxxxxxkeyoradditional2 = d2xxgxxxbv14xxxxxxxxkeyoradditional2;
		this.d3xxgxxxbv15xxxxxxxxkeyoradditional3 = d3xxgxxxbv15xxxxxxxxkeyoradditional3;
		this.e1xxgxxxbv16xxxxxxxxshowinmenu = e1xxgxxxbv16xxxxxxxxshowinmenu;
		this.e2xxgxxxbv17xxxxxxxxshowinreport = e2xxgxxxbv17xxxxxxxxshowinreport;
		this.f1xxgxxxbv18xxxxxxxxprocessoption1 = f1xxgxxxbv18xxxxxxxxprocessoption1;
		this.f2xxuxxxbvxxxxxxxxxxprocessoption2 = f2xxuxxxbvxxxxxxxxxxprocessoption2;
		this.f3xxuhxxbvxxxxxxxxxxfdbcode = f3xxuhxxbvxxxxxxxxxxfdbcode;
		this.f4xxuhxxbvxxxxxxxxxxftablename = f4xxuhxxbvxxxxxxxxxxftablename;
		this.f6xxuxxxbvxxxxxxxxxxffieldkeyname1 = f6xxuxxxbvxxxxxxxxxxffieldkeyname1;
		this.f6xxuxxxbvxxxxxxxxxxffieldkeyname2 = f6xxuxxxbvxxxxxxxxxxffieldkeyname2;
		this.f6xxuxxxbvxxxxxxxxxxffieldkeyname3 = f6xxuxxxbvxxxxxxxxxxffieldkeyname3;
		this.zexxzzfxhhxxxxxxxxxxstatusfl = zexxzzfxhhxxxxxxxxxxstatusfl;
		this.zfxxcztxlxxxxxxxxxxxstatusfldt = zfxxcztxlxxxxxxxxxxxstatusfldt;
		this.zgxxuxznbvxxxxxxxxxxnotes = zgxxuxznbvxxxxxxxxxxnotes;
		this.zhxxutoxlhxxxxxxxxxxowner = zhxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tablename")
	public Nxxxiha3rxwwqqhxxxxxgentable getNxxxiha3rxwwqqhxxxxxgentable() {
		return this.nxxxiha3rxwwqqhxxxxxgentable;
	}

	public void setNxxxiha3rxwwqqhxxxxxgentable(
			Nxxxiha3rxwwqqhxxxxxgentable nxxxiha3rxwwqqhxxxxxgentable) {
		this.nxxxiha3rxwwqqhxxxxxgentable = nxxxiha3rxwwqqhxxxxxgentable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dbcode")
	public Nxxxiha2rxwwqqhxxxxxgendb getNxxxiha2rxwwqqhxxxxxgendb() {
		return this.nxxxiha2rxwwqqhxxxxxgendb;
	}

	public void setNxxxiha2rxwwqqhxxxxxgendb(
			Nxxxiha2rxwwqqhxxxxxgendb nxxxiha2rxwwqqhxxxxxgendb) {
		this.nxxxiha2rxwwqqhxxxxxgendb = nxxxiha2rxwwqqhxxxxxgendb;
	}

	@Column(name = "fieldname", nullable = false, length = 60)
	@NotNull
	@Size(max = 60)
	public String getA0xxukxxbxxxxxxxxxxxfieldname() {
		return this.a0xxukxxbxxxxxxxxxxxfieldname;
	}

	public void setA0xxukxxbxxxxxxxxxxxfieldname(
			String a0xxukxxbxxxxxxxxxxxfieldname) {
		this.a0xxukxxbxxxxxxxxxxxfieldname = a0xxukxxbxxxxxxxxxxxfieldname;
	}

	@Column(name = "fieldtype", length = 20)
	@Size(max = 20)
	public String getB2xxgxxxbvxxxxxxxxxxfieldtype() {
		return this.b2xxgxxxbvxxxxxxxxxxfieldtype;
	}

	public void setB2xxgxxxbvxxxxxxxxxxfieldtype(
			String b2xxgxxxbvxxxxxxxxxxfieldtype) {
		this.b2xxgxxxbvxxxxxxxxxxfieldtype = b2xxgxxxbvxxxxxxxxxxfieldtype;
	}

	@Column(name = "fieldlength", length = 2)
	@Size(max = 2)
	public String getB2xxgxxxbv10xxxxxxxxfieldlength() {
		return this.b2xxgxxxbv10xxxxxxxxfieldlength;
	}

	public void setB2xxgxxxbv10xxxxxxxxfieldlength(
			String b2xxgxxxbv10xxxxxxxxfieldlength) {
		this.b2xxgxxxbv10xxxxxxxxfieldlength = b2xxgxxxbv10xxxxxxxxfieldlength;
	}

	@Column(name = "ingroup", length = 20)
	@Size(max = 20)
	public String getB2xxgxxxbv08xxxxxxxxingroup() {
		return this.b2xxgxxxbv08xxxxxxxxingroup;
	}

	public void setB2xxgxxxbv08xxxxxxxxingroup(
			String b2xxgxxxbv08xxxxxxxxingroup) {
		this.b2xxgxxxbv08xxxxxxxxingroup = b2xxgxxxbv08xxxxxxxxingroup;
	}

	@Column(name = "seqwithingroup")
	public Integer getB3xxgxxxbv09xxxxxxxxseqwithingroup() {
		return this.b3xxgxxxbv09xxxxxxxxseqwithingroup;
	}

	public void setB3xxgxxxbv09xxxxxxxxseqwithingroup(
			Integer b3xxgxxxbv09xxxxxxxxseqwithingroup) {
		this.b3xxgxxxbv09xxxxxxxxseqwithingroup = b3xxgxxxbv09xxxxxxxxseqwithingroup;
	}

	@Column(name = "focusseq")
	public Integer getB4xxgxxxbv10xxxxxxxxfocusseq() {
		return this.b4xxgxxxbv10xxxxxxxxfocusseq;
	}

	public void setB4xxgxxxbv10xxxxxxxxfocusseq(
			Integer b4xxgxxxbv10xxxxxxxxfocusseq) {
		this.b4xxgxxxbv10xxxxxxxxfocusseq = b4xxgxxxbv10xxxxxxxxfocusseq;
	}

	@Column(name = "future1", length = 20)
	@Size(max = 20)
	public String getC1xxuxxxbvxxxxxxxxxxfuture1() {
		return this.c1xxuxxxbvxxxxxxxxxxfuture1;
	}

	public void setC1xxuxxxbvxxxxxxxxxxfuture1(
			String c1xxuxxxbvxxxxxxxxxxfuture1) {
		this.c1xxuxxxbvxxxxxxxxxxfuture1 = c1xxuxxxbvxxxxxxxxxxfuture1;
	}

	@Column(name = "initialvalue", length = 12)
	@Size(max = 12)
	public String getC2xxgxxxbv12xxxxxxxxinitialvalue() {
		return this.c2xxgxxxbv12xxxxxxxxinitialvalue;
	}

	public void setC2xxgxxxbv12xxxxxxxxinitialvalue(
			String c2xxgxxxbv12xxxxxxxxinitialvalue) {
		this.c2xxgxxxbv12xxxxxxxxinitialvalue = c2xxgxxxbv12xxxxxxxxinitialvalue;
	}

	@Column(name = "keyoradditional", length = 12)
	@Size(max = 12)
	public String getD1xxgxxxbv13xxxxxxxxkeyoradditional() {
		return this.d1xxgxxxbv13xxxxxxxxkeyoradditional;
	}

	public void setD1xxgxxxbv13xxxxxxxxkeyoradditional(
			String d1xxgxxxbv13xxxxxxxxkeyoradditional) {
		this.d1xxgxxxbv13xxxxxxxxkeyoradditional = d1xxgxxxbv13xxxxxxxxkeyoradditional;
	}

	@Column(name = "keyoradditional2", length = 12)
	@Size(max = 12)
	public String getD2xxgxxxbv14xxxxxxxxkeyoradditional2() {
		return this.d2xxgxxxbv14xxxxxxxxkeyoradditional2;
	}

	public void setD2xxgxxxbv14xxxxxxxxkeyoradditional2(
			String d2xxgxxxbv14xxxxxxxxkeyoradditional2) {
		this.d2xxgxxxbv14xxxxxxxxkeyoradditional2 = d2xxgxxxbv14xxxxxxxxkeyoradditional2;
	}

	@Column(name = "keyoradditional3", length = 12)
	@Size(max = 12)
	public String getD3xxgxxxbv15xxxxxxxxkeyoradditional3() {
		return this.d3xxgxxxbv15xxxxxxxxkeyoradditional3;
	}

	public void setD3xxgxxxbv15xxxxxxxxkeyoradditional3(
			String d3xxgxxxbv15xxxxxxxxkeyoradditional3) {
		this.d3xxgxxxbv15xxxxxxxxkeyoradditional3 = d3xxgxxxbv15xxxxxxxxkeyoradditional3;
	}

	@Column(name = "showinmenu", length = 20)
	@Size(max = 20)
	public String getE1xxgxxxbv16xxxxxxxxshowinmenu() {
		return this.e1xxgxxxbv16xxxxxxxxshowinmenu;
	}

	public void setE1xxgxxxbv16xxxxxxxxshowinmenu(
			String e1xxgxxxbv16xxxxxxxxshowinmenu) {
		this.e1xxgxxxbv16xxxxxxxxshowinmenu = e1xxgxxxbv16xxxxxxxxshowinmenu;
	}

	@Column(name = "showinreport", length = 20)
	@Size(max = 20)
	public String getE2xxgxxxbv17xxxxxxxxshowinreport() {
		return this.e2xxgxxxbv17xxxxxxxxshowinreport;
	}

	public void setE2xxgxxxbv17xxxxxxxxshowinreport(
			String e2xxgxxxbv17xxxxxxxxshowinreport) {
		this.e2xxgxxxbv17xxxxxxxxshowinreport = e2xxgxxxbv17xxxxxxxxshowinreport;
	}

	@Column(name = "processoption1", length = 20)
	@Size(max = 20)
	public String getF1xxgxxxbv18xxxxxxxxprocessoption1() {
		return this.f1xxgxxxbv18xxxxxxxxprocessoption1;
	}

	public void setF1xxgxxxbv18xxxxxxxxprocessoption1(
			String f1xxgxxxbv18xxxxxxxxprocessoption1) {
		this.f1xxgxxxbv18xxxxxxxxprocessoption1 = f1xxgxxxbv18xxxxxxxxprocessoption1;
	}

	@Column(name = "processoption2", length = 20)
	@Size(max = 20)
	public String getF2xxuxxxbvxxxxxxxxxxprocessoption2() {
		return this.f2xxuxxxbvxxxxxxxxxxprocessoption2;
	}

	public void setF2xxuxxxbvxxxxxxxxxxprocessoption2(
			String f2xxuxxxbvxxxxxxxxxxprocessoption2) {
		this.f2xxuxxxbvxxxxxxxxxxprocessoption2 = f2xxuxxxbvxxxxxxxxxxprocessoption2;
	}

	@Column(name = "fdbcode", length = 40)
	@Size(max = 40)
	public String getF3xxuhxxbvxxxxxxxxxxfdbcode() {
		return this.f3xxuhxxbvxxxxxxxxxxfdbcode;
	}

	public void setF3xxuhxxbvxxxxxxxxxxfdbcode(
			String f3xxuhxxbvxxxxxxxxxxfdbcode) {
		this.f3xxuhxxbvxxxxxxxxxxfdbcode = f3xxuhxxbvxxxxxxxxxxfdbcode;
	}

	@Column(name = "ftablename", length = 60)
	@Size(max = 60)
	public String getF4xxuhxxbvxxxxxxxxxxftablename() {
		return this.f4xxuhxxbvxxxxxxxxxxftablename;
	}

	public void setF4xxuhxxbvxxxxxxxxxxftablename(
			String f4xxuhxxbvxxxxxxxxxxftablename) {
		this.f4xxuhxxbvxxxxxxxxxxftablename = f4xxuhxxbvxxxxxxxxxxftablename;
	}

	@Column(name = "ffieldkeyname1", length = 60)
	@Size(max = 60)
	public String getF6xxuxxxbvxxxxxxxxxxffieldkeyname1() {
		return this.f6xxuxxxbvxxxxxxxxxxffieldkeyname1;
	}

	public void setF6xxuxxxbvxxxxxxxxxxffieldkeyname1(
			String f6xxuxxxbvxxxxxxxxxxffieldkeyname1) {
		this.f6xxuxxxbvxxxxxxxxxxffieldkeyname1 = f6xxuxxxbvxxxxxxxxxxffieldkeyname1;
	}

	@Column(name = "ffieldkeyname2", length = 60)
	@Size(max = 60)
	public String getF6xxuxxxbvxxxxxxxxxxffieldkeyname2() {
		return this.f6xxuxxxbvxxxxxxxxxxffieldkeyname2;
	}

	public void setF6xxuxxxbvxxxxxxxxxxffieldkeyname2(
			String f6xxuxxxbvxxxxxxxxxxffieldkeyname2) {
		this.f6xxuxxxbvxxxxxxxxxxffieldkeyname2 = f6xxuxxxbvxxxxxxxxxxffieldkeyname2;
	}

	@Column(name = "ffieldkeyname3", length = 60)
	@Size(max = 60)
	public String getF6xxuxxxbvxxxxxxxxxxffieldkeyname3() {
		return this.f6xxuxxxbvxxxxxxxxxxffieldkeyname3;
	}

	public void setF6xxuxxxbvxxxxxxxxxxffieldkeyname3(
			String f6xxuxxxbvxxxxxxxxxxffieldkeyname3) {
		this.f6xxuxxxbvxxxxxxxxxxffieldkeyname3 = f6xxuxxxbvxxxxxxxxxxffieldkeyname3;
	}

	@Column(name = "statusfl")
	public Integer getZexxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zexxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZexxzzfxhhxxxxxxxxxxstatusfl(
			Integer zexxzzfxhhxxxxxxxxxxstatusfl) {
		this.zexxzzfxhhxxxxxxxxxxstatusfl = zexxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZfxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zfxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZfxxcztxlxxxxxxxxxxxstatusfldt(
			Date zfxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zfxxcztxlxxxxxxxxxxxstatusfldt = zfxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getZgxxuxznbvxxxxxxxxxxnotes() {
		return this.zgxxuxznbvxxxxxxxxxxnotes;
	}

	public void setZgxxuxznbvxxxxxxxxxxnotes(String zgxxuxznbvxxxxxxxxxxnotes) {
		this.zgxxuxznbvxxxxxxxxxxnotes = zgxxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZhxxutoxlhxxxxxxxxxxowner() {
		return this.zhxxutoxlhxxxxxxxxxxowner;
	}

	public void setZhxxutoxlhxxxxxxxxxxowner(String zhxxutoxlhxxxxxxxxxxowner) {
		this.zhxxutoxlhxxxxxxxxxxowner = zhxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
