package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Nxxxiha3rxwwqqhxxxxxgentable generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "rgentable")
public class Nxxxiha3rxwwqqhxxxxxgentable implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Nxxxiha2rxwwqqhxxxxxgendb nxxxiha2rxwwqqhxxxxxgendb;
	private String a0xxukxxbvxxxxxxxxxxtablename;
	private Boolean a2xxfxxxbvxxxxxxxxxxinaddmenu;
	private Boolean a3xxfxxxbvxxxxxxxxxxinlistmenu;
	private Boolean a4xxfxxxbvxxxxxxxxxxintransactionmenu;
	private Boolean a5xxfxxrbvxxxxxxxxxxinreportmenu;
	private Boolean a6xxfxxrbvxxxxxxxxxxingraphsmenu;
	private Boolean a7xxfxxrbvxxxxxxxxxxinmailingmenu;
	private Boolean a8xxfxxrbvxxxxxxxxxxingeneratemenu;
	private Boolean a9xxfxxrbvxxxxxxxxxxinadminmenu;
	private Boolean aaxxfxxrbvxxxxxxxxxxinmaintenancemenu;
	private Boolean abxxfxxrbvxxxxxxxxxxinlabelsmenu;
	private Boolean acxxfxxrbvxxxxxxxxxxinskipmenu;
	private Boolean adxxfxxrbvxxxxxxxxxxincustom1menu;
	private String b1xxgxxxbv01xxxxxxxxmenulevel;
	private String c1xxgxxxbv02xxxxxxxxmenurole;
	private String d1xxgxxxbv03xxxxxxxxmenulabelgroup;
	private Integer d2xxgxxxbv04xxxxxxxxsubmenusequence;
	private String d4xxgxxxbv04xxxxxxxxusagescope;
	private Integer zexxzzfxhhxxxxxxxxxxstatusfl;
	private Date zfxxcztxlxxxxxxxxxxxstatusfldt;
	private String zgxxuxznbvxxxxxxxxxxnotes;
	private String zhxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private Set<Nxxxiha4rxwwqqhxxxxxgenfields> nxxxiha4rxwwqqhxxxxxgenfieldses = new HashSet<Nxxxiha4rxwwqqhxxxxxgenfields>(
			0);

	public Nxxxiha3rxwwqqhxxxxxgentable() {
	}

	public Nxxxiha3rxwwqqhxxxxxgentable(String a0xxukxxbvxxxxxxxxxxtablename) {
		this.a0xxukxxbvxxxxxxxxxxtablename = a0xxukxxbvxxxxxxxxxxtablename;
	}
	public Nxxxiha3rxwwqqhxxxxxgentable(
			Nxxxiha2rxwwqqhxxxxxgendb nxxxiha2rxwwqqhxxxxxgendb,
			String a0xxukxxbvxxxxxxxxxxtablename,
			Boolean a2xxfxxxbvxxxxxxxxxxinaddmenu,
			Boolean a3xxfxxxbvxxxxxxxxxxinlistmenu,
			Boolean a4xxfxxxbvxxxxxxxxxxintransactionmenu,
			Boolean a5xxfxxrbvxxxxxxxxxxinreportmenu,
			Boolean a6xxfxxrbvxxxxxxxxxxingraphsmenu,
			Boolean a7xxfxxrbvxxxxxxxxxxinmailingmenu,
			Boolean a8xxfxxrbvxxxxxxxxxxingeneratemenu,
			Boolean a9xxfxxrbvxxxxxxxxxxinadminmenu,
			Boolean aaxxfxxrbvxxxxxxxxxxinmaintenancemenu,
			Boolean abxxfxxrbvxxxxxxxxxxinlabelsmenu,
			Boolean acxxfxxrbvxxxxxxxxxxinskipmenu,
			Boolean adxxfxxrbvxxxxxxxxxxincustom1menu,
			String b1xxgxxxbv01xxxxxxxxmenulevel,
			String c1xxgxxxbv02xxxxxxxxmenurole,
			String d1xxgxxxbv03xxxxxxxxmenulabelgroup,
			Integer d2xxgxxxbv04xxxxxxxxsubmenusequence,
			String d4xxgxxxbv04xxxxxxxxusagescope,
			Integer zexxzzfxhhxxxxxxxxxxstatusfl,
			Date zfxxcztxlxxxxxxxxxxxstatusfldt,
			String zgxxuxznbvxxxxxxxxxxnotes, String zhxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			Set<Nxxxiha4rxwwqqhxxxxxgenfields> nxxxiha4rxwwqqhxxxxxgenfieldses) {
		this.nxxxiha2rxwwqqhxxxxxgendb = nxxxiha2rxwwqqhxxxxxgendb;
		this.a0xxukxxbvxxxxxxxxxxtablename = a0xxukxxbvxxxxxxxxxxtablename;
		this.a2xxfxxxbvxxxxxxxxxxinaddmenu = a2xxfxxxbvxxxxxxxxxxinaddmenu;
		this.a3xxfxxxbvxxxxxxxxxxinlistmenu = a3xxfxxxbvxxxxxxxxxxinlistmenu;
		this.a4xxfxxxbvxxxxxxxxxxintransactionmenu = a4xxfxxxbvxxxxxxxxxxintransactionmenu;
		this.a5xxfxxrbvxxxxxxxxxxinreportmenu = a5xxfxxrbvxxxxxxxxxxinreportmenu;
		this.a6xxfxxrbvxxxxxxxxxxingraphsmenu = a6xxfxxrbvxxxxxxxxxxingraphsmenu;
		this.a7xxfxxrbvxxxxxxxxxxinmailingmenu = a7xxfxxrbvxxxxxxxxxxinmailingmenu;
		this.a8xxfxxrbvxxxxxxxxxxingeneratemenu = a8xxfxxrbvxxxxxxxxxxingeneratemenu;
		this.a9xxfxxrbvxxxxxxxxxxinadminmenu = a9xxfxxrbvxxxxxxxxxxinadminmenu;
		this.aaxxfxxrbvxxxxxxxxxxinmaintenancemenu = aaxxfxxrbvxxxxxxxxxxinmaintenancemenu;
		this.abxxfxxrbvxxxxxxxxxxinlabelsmenu = abxxfxxrbvxxxxxxxxxxinlabelsmenu;
		this.acxxfxxrbvxxxxxxxxxxinskipmenu = acxxfxxrbvxxxxxxxxxxinskipmenu;
		this.adxxfxxrbvxxxxxxxxxxincustom1menu = adxxfxxrbvxxxxxxxxxxincustom1menu;
		this.b1xxgxxxbv01xxxxxxxxmenulevel = b1xxgxxxbv01xxxxxxxxmenulevel;
		this.c1xxgxxxbv02xxxxxxxxmenurole = c1xxgxxxbv02xxxxxxxxmenurole;
		this.d1xxgxxxbv03xxxxxxxxmenulabelgroup = d1xxgxxxbv03xxxxxxxxmenulabelgroup;
		this.d2xxgxxxbv04xxxxxxxxsubmenusequence = d2xxgxxxbv04xxxxxxxxsubmenusequence;
		this.d4xxgxxxbv04xxxxxxxxusagescope = d4xxgxxxbv04xxxxxxxxusagescope;
		this.zexxzzfxhhxxxxxxxxxxstatusfl = zexxzzfxhhxxxxxxxxxxstatusfl;
		this.zfxxcztxlxxxxxxxxxxxstatusfldt = zfxxcztxlxxxxxxxxxxxstatusfldt;
		this.zgxxuxznbvxxxxxxxxxxnotes = zgxxuxznbvxxxxxxxxxxnotes;
		this.zhxxutoxlhxxxxxxxxxxowner = zhxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.nxxxiha4rxwwqqhxxxxxgenfieldses = nxxxiha4rxwwqqhxxxxxgenfieldses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dbcode")
	public Nxxxiha2rxwwqqhxxxxxgendb getNxxxiha2rxwwqqhxxxxxgendb() {
		return this.nxxxiha2rxwwqqhxxxxxgendb;
	}

	public void setNxxxiha2rxwwqqhxxxxxgendb(
			Nxxxiha2rxwwqqhxxxxxgendb nxxxiha2rxwwqqhxxxxxgendb) {
		this.nxxxiha2rxwwqqhxxxxxgendb = nxxxiha2rxwwqqhxxxxxgendb;
	}

	@Column(name = "tablename", nullable = false, length = 40)
	@NotNull
	@Size(max = 40)
	public String getA0xxukxxbvxxxxxxxxxxtablename() {
		return this.a0xxukxxbvxxxxxxxxxxtablename;
	}

	public void setA0xxukxxbvxxxxxxxxxxtablename(
			String a0xxukxxbvxxxxxxxxxxtablename) {
		this.a0xxukxxbvxxxxxxxxxxtablename = a0xxukxxbvxxxxxxxxxxtablename;
	}

	@Column(name = "inaddmenu")
	public Boolean getA2xxfxxxbvxxxxxxxxxxinaddmenu() {
		return this.a2xxfxxxbvxxxxxxxxxxinaddmenu;
	}

	public void setA2xxfxxxbvxxxxxxxxxxinaddmenu(
			Boolean a2xxfxxxbvxxxxxxxxxxinaddmenu) {
		this.a2xxfxxxbvxxxxxxxxxxinaddmenu = a2xxfxxxbvxxxxxxxxxxinaddmenu;
	}

	@Column(name = "inlistmenu")
	public Boolean getA3xxfxxxbvxxxxxxxxxxinlistmenu() {
		return this.a3xxfxxxbvxxxxxxxxxxinlistmenu;
	}

	public void setA3xxfxxxbvxxxxxxxxxxinlistmenu(
			Boolean a3xxfxxxbvxxxxxxxxxxinlistmenu) {
		this.a3xxfxxxbvxxxxxxxxxxinlistmenu = a3xxfxxxbvxxxxxxxxxxinlistmenu;
	}

	@Column(name = "intransactionmenu")
	public Boolean getA4xxfxxxbvxxxxxxxxxxintransactionmenu() {
		return this.a4xxfxxxbvxxxxxxxxxxintransactionmenu;
	}

	public void setA4xxfxxxbvxxxxxxxxxxintransactionmenu(
			Boolean a4xxfxxxbvxxxxxxxxxxintransactionmenu) {
		this.a4xxfxxxbvxxxxxxxxxxintransactionmenu = a4xxfxxxbvxxxxxxxxxxintransactionmenu;
	}

	@Column(name = "inreportmenu")
	public Boolean getA5xxfxxrbvxxxxxxxxxxinreportmenu() {
		return this.a5xxfxxrbvxxxxxxxxxxinreportmenu;
	}

	public void setA5xxfxxrbvxxxxxxxxxxinreportmenu(
			Boolean a5xxfxxrbvxxxxxxxxxxinreportmenu) {
		this.a5xxfxxrbvxxxxxxxxxxinreportmenu = a5xxfxxrbvxxxxxxxxxxinreportmenu;
	}

	@Column(name = "ingraphsmenu")
	public Boolean getA6xxfxxrbvxxxxxxxxxxingraphsmenu() {
		return this.a6xxfxxrbvxxxxxxxxxxingraphsmenu;
	}

	public void setA6xxfxxrbvxxxxxxxxxxingraphsmenu(
			Boolean a6xxfxxrbvxxxxxxxxxxingraphsmenu) {
		this.a6xxfxxrbvxxxxxxxxxxingraphsmenu = a6xxfxxrbvxxxxxxxxxxingraphsmenu;
	}

	@Column(name = "inmailingmenu")
	public Boolean getA7xxfxxrbvxxxxxxxxxxinmailingmenu() {
		return this.a7xxfxxrbvxxxxxxxxxxinmailingmenu;
	}

	public void setA7xxfxxrbvxxxxxxxxxxinmailingmenu(
			Boolean a7xxfxxrbvxxxxxxxxxxinmailingmenu) {
		this.a7xxfxxrbvxxxxxxxxxxinmailingmenu = a7xxfxxrbvxxxxxxxxxxinmailingmenu;
	}

	@Column(name = "ingeneratemenu")
	public Boolean getA8xxfxxrbvxxxxxxxxxxingeneratemenu() {
		return this.a8xxfxxrbvxxxxxxxxxxingeneratemenu;
	}

	public void setA8xxfxxrbvxxxxxxxxxxingeneratemenu(
			Boolean a8xxfxxrbvxxxxxxxxxxingeneratemenu) {
		this.a8xxfxxrbvxxxxxxxxxxingeneratemenu = a8xxfxxrbvxxxxxxxxxxingeneratemenu;
	}

	@Column(name = "inadminmenu")
	public Boolean getA9xxfxxrbvxxxxxxxxxxinadminmenu() {
		return this.a9xxfxxrbvxxxxxxxxxxinadminmenu;
	}

	public void setA9xxfxxrbvxxxxxxxxxxinadminmenu(
			Boolean a9xxfxxrbvxxxxxxxxxxinadminmenu) {
		this.a9xxfxxrbvxxxxxxxxxxinadminmenu = a9xxfxxrbvxxxxxxxxxxinadminmenu;
	}

	@Column(name = "inmaintenancemenu")
	public Boolean getAaxxfxxrbvxxxxxxxxxxinmaintenancemenu() {
		return this.aaxxfxxrbvxxxxxxxxxxinmaintenancemenu;
	}

	public void setAaxxfxxrbvxxxxxxxxxxinmaintenancemenu(
			Boolean aaxxfxxrbvxxxxxxxxxxinmaintenancemenu) {
		this.aaxxfxxrbvxxxxxxxxxxinmaintenancemenu = aaxxfxxrbvxxxxxxxxxxinmaintenancemenu;
	}

	@Column(name = "inlabelsmenu")
	public Boolean getAbxxfxxrbvxxxxxxxxxxinlabelsmenu() {
		return this.abxxfxxrbvxxxxxxxxxxinlabelsmenu;
	}

	public void setAbxxfxxrbvxxxxxxxxxxinlabelsmenu(
			Boolean abxxfxxrbvxxxxxxxxxxinlabelsmenu) {
		this.abxxfxxrbvxxxxxxxxxxinlabelsmenu = abxxfxxrbvxxxxxxxxxxinlabelsmenu;
	}

	@Column(name = "inskipmenu")
	public Boolean getAcxxfxxrbvxxxxxxxxxxinskipmenu() {
		return this.acxxfxxrbvxxxxxxxxxxinskipmenu;
	}

	public void setAcxxfxxrbvxxxxxxxxxxinskipmenu(
			Boolean acxxfxxrbvxxxxxxxxxxinskipmenu) {
		this.acxxfxxrbvxxxxxxxxxxinskipmenu = acxxfxxrbvxxxxxxxxxxinskipmenu;
	}

	@Column(name = "incustom1menu")
	public Boolean getAdxxfxxrbvxxxxxxxxxxincustom1menu() {
		return this.adxxfxxrbvxxxxxxxxxxincustom1menu;
	}

	public void setAdxxfxxrbvxxxxxxxxxxincustom1menu(
			Boolean adxxfxxrbvxxxxxxxxxxincustom1menu) {
		this.adxxfxxrbvxxxxxxxxxxincustom1menu = adxxfxxrbvxxxxxxxxxxincustom1menu;
	}

	@Column(name = "menulevel", length = 12)
	@Size(max = 12)
	public String getB1xxgxxxbv01xxxxxxxxmenulevel() {
		return this.b1xxgxxxbv01xxxxxxxxmenulevel;
	}

	public void setB1xxgxxxbv01xxxxxxxxmenulevel(
			String b1xxgxxxbv01xxxxxxxxmenulevel) {
		this.b1xxgxxxbv01xxxxxxxxmenulevel = b1xxgxxxbv01xxxxxxxxmenulevel;
	}

	@Column(name = "menurole", length = 12)
	@Size(max = 12)
	public String getC1xxgxxxbv02xxxxxxxxmenurole() {
		return this.c1xxgxxxbv02xxxxxxxxmenurole;
	}

	public void setC1xxgxxxbv02xxxxxxxxmenurole(
			String c1xxgxxxbv02xxxxxxxxmenurole) {
		this.c1xxgxxxbv02xxxxxxxxmenurole = c1xxgxxxbv02xxxxxxxxmenurole;
	}

	@Column(name = "menulabelgroup", length = 20)
	@Size(max = 20)
	public String getD1xxgxxxbv03xxxxxxxxmenulabelgroup() {
		return this.d1xxgxxxbv03xxxxxxxxmenulabelgroup;
	}

	public void setD1xxgxxxbv03xxxxxxxxmenulabelgroup(
			String d1xxgxxxbv03xxxxxxxxmenulabelgroup) {
		this.d1xxgxxxbv03xxxxxxxxmenulabelgroup = d1xxgxxxbv03xxxxxxxxmenulabelgroup;
	}

	@Column(name = "submenusequence")
	public Integer getD2xxgxxxbv04xxxxxxxxsubmenusequence() {
		return this.d2xxgxxxbv04xxxxxxxxsubmenusequence;
	}

	public void setD2xxgxxxbv04xxxxxxxxsubmenusequence(
			Integer d2xxgxxxbv04xxxxxxxxsubmenusequence) {
		this.d2xxgxxxbv04xxxxxxxxsubmenusequence = d2xxgxxxbv04xxxxxxxxsubmenusequence;
	}

	@Column(name = "usagescope", length = 12)
	@Size(max = 12)
	public String getD4xxgxxxbv04xxxxxxxxusagescope() {
		return this.d4xxgxxxbv04xxxxxxxxusagescope;
	}

	public void setD4xxgxxxbv04xxxxxxxxusagescope(
			String d4xxgxxxbv04xxxxxxxxusagescope) {
		this.d4xxgxxxbv04xxxxxxxxusagescope = d4xxgxxxbv04xxxxxxxxusagescope;
	}

	@Column(name = "statusfl")
	public Integer getZexxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zexxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZexxzzfxhhxxxxxxxxxxstatusfl(
			Integer zexxzzfxhhxxxxxxxxxxstatusfl) {
		this.zexxzzfxhhxxxxxxxxxxstatusfl = zexxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZfxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zfxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZfxxcztxlxxxxxxxxxxxstatusfldt(
			Date zfxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zfxxcztxlxxxxxxxxxxxstatusfldt = zfxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getZgxxuxznbvxxxxxxxxxxnotes() {
		return this.zgxxuxznbvxxxxxxxxxxnotes;
	}

	public void setZgxxuxznbvxxxxxxxxxxnotes(String zgxxuxznbvxxxxxxxxxxnotes) {
		this.zgxxuxznbvxxxxxxxxxxnotes = zgxxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZhxxutoxlhxxxxxxxxxxowner() {
		return this.zhxxutoxlhxxxxxxxxxxowner;
	}

	public void setZhxxutoxlhxxxxxxxxxxowner(String zhxxutoxlhxxxxxxxxxxowner) {
		this.zhxxutoxlhxxxxxxxxxxowner = zhxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nxxxiha3rxwwqqhxxxxxgentable")
	public Set<Nxxxiha4rxwwqqhxxxxxgenfields> getNxxxiha4rxwwqqhxxxxxgenfieldses() {
		return this.nxxxiha4rxwwqqhxxxxxgenfieldses;
	}

	public void setNxxxiha4rxwwqqhxxxxxgenfieldses(
			Set<Nxxxiha4rxwwqqhxxxxxgenfields> nxxxiha4rxwwqqhxxxxxgenfieldses) {
		this.nxxxiha4rxwwqqhxxxxxgenfieldses = nxxxiha4rxwwqqhxxxxxgenfieldses;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
