package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Trexuq3a6xwwqqhxxxxxvinvoice generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "vinvoice")
public class Trexuq3a6xwwqqhxxxxxvinvoice implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Trexuq377xwwqqhxxxxxvshipmen trexuq377xwwqqhxxxxxvshipmen;
	private Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor;
	private Jxxxbh400xwwqqhxxxxxemployee jxxxbh400xwwqqhxxxxxemployee;
	private Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem;
	private Trexuq344xwwqqhxxxxxvendorders trexuq344xwwqqhxxxxxvendorders;
	private String a0xxunvibvxxxxxxxxxxinvoice;
	private String y2xxuwmxbv40xxxxxxxxintegrset;
	private Date b3xxuxxrbvxxxxxxxxxxinvodate;
	private BigDecimal b3xxztprlxxxxxxxxxxxamounttotal;
	private BigDecimal z1xxzyprlxxxxxxxxxxxamountostndt;
	private BigDecimal z2xxztqrlxxxxxxxxxxxqtytotal;
	private BigDecimal z3xxzyqrlxxxxxxxxxxxqtyostndt;
	private String y4xxuxxrbvxxxxxxxxxxref1typ;
	private String y5xxuxxrbvxxxxxxxxxxref1code;
	private Date y6xxcxxrlxxxxxxxxxxxshipdatet;
	private String y7xxuxxrbv51xxxxxxxxshiptype;
	private String b4xxuxxrbv09xxxxxxxxterms;
	private Integer z4xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z5xxcztxlxxxxxxxxxxxstatusfldt;
	private Date z6xxcxxrlxxxxxxxxxxxtermsdat;
	private BigDecimal c1xxzixrbvxxxxxxxxxxdiscounp;
	private Date c2xxcxxrlxxxxxxxxxxxdiscoudt;
	private BigDecimal c3xxzxxrlvxxxxxxxxxxdiscouds;
	private Date c4xxcxxrlxxxxxxxxxxxnetddat;
	private Integer c5xxzxxrbvxxxxxxxxxxnetddys;
	private String c6xxuxxrbvxxxxxxxxxxfob;
	private String c7xxuxxrbv10xxxxxxxxtype;
	private String ydxxuxxrbvxxxxxxxxxxattach;
	private BigDecimal z7xxzbtxavxxxxxxxxxxbaseamountt;
	private BigDecimal z7xxzltxavxxxxxxxxxxdelivchrgt;
	private BigDecimal z8xxzmtxavxxxxxxxxxxmiscchrgt;
	private BigDecimal z9xxzxz1avxxxxxxxxxxtax1amtt;
	private BigDecimal zaxxzxz2avxxxxxxxxxxtax2amtt;
	private BigDecimal zbxxzxz3avxxxxxxxxxxtax3amtt;
	private String yexxuznybvxxxxxxxxxxnotes;
	private Integer zcxxzzprhvxxxxxxxxxxprintmstat;
	private Date zdxxczqxlhxxxxxxxxxxprinmtfldt;
	private String zexxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String yfxxuzdrbvxxxxxxxxxxdocmnt;
	private Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> xoxxuq3b4xwwqqhxxxxxvendpdetailses = new HashSet<Xoxxuq3b4xwwqqhxxxxxvendpdetails>(
			0);
	private Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses = new HashSet<Xoxxuq3c4xwwqqhxxxxxvendidetails>(
			0);
	private Set<Trexuq388xwwqqhxxxxxvpayment> trexuq388xwwqqhxxxxxvpayments = new HashSet<Trexuq388xwwqqhxxxxxvpayment>(
			0);

	public Trexuq3a6xwwqqhxxxxxvinvoice() {
	}

	public Trexuq3a6xwwqqhxxxxxvinvoice(String a0xxunvibvxxxxxxxxxxinvoice) {
		this.a0xxunvibvxxxxxxxxxxinvoice = a0xxunvibvxxxxxxxxxxinvoice;
	}
	public Trexuq3a6xwwqqhxxxxxvinvoice(
			Trexuq377xwwqqhxxxxxvshipmen trexuq377xwwqqhxxxxxvshipmen,
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor,
			Jxxxbh400xwwqqhxxxxxemployee jxxxbh400xwwqqhxxxxxemployee,
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem,
			Trexuq344xwwqqhxxxxxvendorders trexuq344xwwqqhxxxxxvendorders,
			String a0xxunvibvxxxxxxxxxxinvoice,
			String y2xxuwmxbv40xxxxxxxxintegrset,
			Date b3xxuxxrbvxxxxxxxxxxinvodate,
			BigDecimal b3xxztprlxxxxxxxxxxxamounttotal,
			BigDecimal z1xxzyprlxxxxxxxxxxxamountostndt,
			BigDecimal z2xxztqrlxxxxxxxxxxxqtytotal,
			BigDecimal z3xxzyqrlxxxxxxxxxxxqtyostndt,
			String y4xxuxxrbvxxxxxxxxxxref1typ,
			String y5xxuxxrbvxxxxxxxxxxref1code,
			Date y6xxcxxrlxxxxxxxxxxxshipdatet,
			String y7xxuxxrbv51xxxxxxxxshiptype,
			String b4xxuxxrbv09xxxxxxxxterms,
			Integer z4xxzzfxhhxxxxxxxxxxstatusfl,
			Date z5xxcztxlxxxxxxxxxxxstatusfldt,
			Date z6xxcxxrlxxxxxxxxxxxtermsdat,
			BigDecimal c1xxzixrbvxxxxxxxxxxdiscounp,
			Date c2xxcxxrlxxxxxxxxxxxdiscoudt,
			BigDecimal c3xxzxxrlvxxxxxxxxxxdiscouds,
			Date c4xxcxxrlxxxxxxxxxxxnetddat,
			Integer c5xxzxxrbvxxxxxxxxxxnetddys,
			String c6xxuxxrbvxxxxxxxxxxfob,
			String c7xxuxxrbv10xxxxxxxxtype,
			String ydxxuxxrbvxxxxxxxxxxattach,
			BigDecimal z7xxzbtxavxxxxxxxxxxbaseamountt,
			BigDecimal z7xxzltxavxxxxxxxxxxdelivchrgt,
			BigDecimal z8xxzmtxavxxxxxxxxxxmiscchrgt,
			BigDecimal z9xxzxz1avxxxxxxxxxxtax1amtt,
			BigDecimal zaxxzxz2avxxxxxxxxxxtax2amtt,
			BigDecimal zbxxzxz3avxxxxxxxxxxtax3amtt,
			String yexxuznybvxxxxxxxxxxnotes,
			Integer zcxxzzprhvxxxxxxxxxxprintmstat,
			Date zdxxczqxlhxxxxxxxxxxprinmtfldt,
			String zexxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String yfxxuzdrbvxxxxxxxxxxdocmnt,
			Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> xoxxuq3b4xwwqqhxxxxxvendpdetailses,
			Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses,
			Set<Trexuq388xwwqqhxxxxxvpayment> trexuq388xwwqqhxxxxxvpayments) {
		this.trexuq377xwwqqhxxxxxvshipmen = trexuq377xwwqqhxxxxxvshipmen;
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
		this.jxxxbh400xwwqqhxxxxxemployee = jxxxbh400xwwqqhxxxxxemployee;
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
		this.trexuq344xwwqqhxxxxxvendorders = trexuq344xwwqqhxxxxxvendorders;
		this.a0xxunvibvxxxxxxxxxxinvoice = a0xxunvibvxxxxxxxxxxinvoice;
		this.y2xxuwmxbv40xxxxxxxxintegrset = y2xxuwmxbv40xxxxxxxxintegrset;
		this.b3xxuxxrbvxxxxxxxxxxinvodate = b3xxuxxrbvxxxxxxxxxxinvodate;
		this.b3xxztprlxxxxxxxxxxxamounttotal = b3xxztprlxxxxxxxxxxxamounttotal;
		this.z1xxzyprlxxxxxxxxxxxamountostndt = z1xxzyprlxxxxxxxxxxxamountostndt;
		this.z2xxztqrlxxxxxxxxxxxqtytotal = z2xxztqrlxxxxxxxxxxxqtytotal;
		this.z3xxzyqrlxxxxxxxxxxxqtyostndt = z3xxzyqrlxxxxxxxxxxxqtyostndt;
		this.y4xxuxxrbvxxxxxxxxxxref1typ = y4xxuxxrbvxxxxxxxxxxref1typ;
		this.y5xxuxxrbvxxxxxxxxxxref1code = y5xxuxxrbvxxxxxxxxxxref1code;
		this.y6xxcxxrlxxxxxxxxxxxshipdatet = y6xxcxxrlxxxxxxxxxxxshipdatet;
		this.y7xxuxxrbv51xxxxxxxxshiptype = y7xxuxxrbv51xxxxxxxxshiptype;
		this.b4xxuxxrbv09xxxxxxxxterms = b4xxuxxrbv09xxxxxxxxterms;
		this.z4xxzzfxhhxxxxxxxxxxstatusfl = z4xxzzfxhhxxxxxxxxxxstatusfl;
		this.z5xxcztxlxxxxxxxxxxxstatusfldt = z5xxcztxlxxxxxxxxxxxstatusfldt;
		this.z6xxcxxrlxxxxxxxxxxxtermsdat = z6xxcxxrlxxxxxxxxxxxtermsdat;
		this.c1xxzixrbvxxxxxxxxxxdiscounp = c1xxzixrbvxxxxxxxxxxdiscounp;
		this.c2xxcxxrlxxxxxxxxxxxdiscoudt = c2xxcxxrlxxxxxxxxxxxdiscoudt;
		this.c3xxzxxrlvxxxxxxxxxxdiscouds = c3xxzxxrlvxxxxxxxxxxdiscouds;
		this.c4xxcxxrlxxxxxxxxxxxnetddat = c4xxcxxrlxxxxxxxxxxxnetddat;
		this.c5xxzxxrbvxxxxxxxxxxnetddys = c5xxzxxrbvxxxxxxxxxxnetddys;
		this.c6xxuxxrbvxxxxxxxxxxfob = c6xxuxxrbvxxxxxxxxxxfob;
		this.c7xxuxxrbv10xxxxxxxxtype = c7xxuxxrbv10xxxxxxxxtype;
		this.ydxxuxxrbvxxxxxxxxxxattach = ydxxuxxrbvxxxxxxxxxxattach;
		this.z7xxzbtxavxxxxxxxxxxbaseamountt = z7xxzbtxavxxxxxxxxxxbaseamountt;
		this.z7xxzltxavxxxxxxxxxxdelivchrgt = z7xxzltxavxxxxxxxxxxdelivchrgt;
		this.z8xxzmtxavxxxxxxxxxxmiscchrgt = z8xxzmtxavxxxxxxxxxxmiscchrgt;
		this.z9xxzxz1avxxxxxxxxxxtax1amtt = z9xxzxz1avxxxxxxxxxxtax1amtt;
		this.zaxxzxz2avxxxxxxxxxxtax2amtt = zaxxzxz2avxxxxxxxxxxtax2amtt;
		this.zbxxzxz3avxxxxxxxxxxtax3amtt = zbxxzxz3avxxxxxxxxxxtax3amtt;
		this.yexxuznybvxxxxxxxxxxnotes = yexxuznybvxxxxxxxxxxnotes;
		this.zcxxzzprhvxxxxxxxxxxprintmstat = zcxxzzprhvxxxxxxxxxxprintmstat;
		this.zdxxczqxlhxxxxxxxxxxprinmtfldt = zdxxczqxlhxxxxxxxxxxprinmtfldt;
		this.zexxutoxlhxxxxxxxxxxowner = zexxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.yfxxuzdrbvxxxxxxxxxxdocmnt = yfxxuzdrbvxxxxxxxxxxdocmnt;
		this.xoxxuq3b4xwwqqhxxxxxvendpdetailses = xoxxuq3b4xwwqqhxxxxxvendpdetailses;
		this.xoxxuq3c4xwwqqhxxxxxvendidetailses = xoxxuq3c4xwwqqhxxxxxvendidetailses;
		this.trexuq388xwwqqhxxxxxvpayments = trexuq388xwwqqhxxxxxvpayments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipcode")
	public Trexuq377xwwqqhxxxxxvshipmen getTrexuq377xwwqqhxxxxxvshipmen() {
		return this.trexuq377xwwqqhxxxxxvshipmen;
	}

	public void setTrexuq377xwwqqhxxxxxvshipmen(
			Trexuq377xwwqqhxxxxxvshipmen trexuq377xwwqqhxxxxxvshipmen) {
		this.trexuq377xwwqqhxxxxxvshipmen = trexuq377xwwqqhxxxxxvshipmen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor")
	public Jxxxuq300xwwqqhxxxxxvendor getJxxxuq300xwwqqhxxxxxvendor() {
		return this.jxxxuq300xwwqqhxxxxxvendor;
	}

	public void setJxxxuq300xwwqqhxxxxxvendor(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor) {
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agent")
	public Jxxxbh400xwwqqhxxxxxemployee getJxxxbh400xwwqqhxxxxxemployee() {
		return this.jxxxbh400xwwqqhxxxxxemployee;
	}

	public void setJxxxbh400xwwqqhxxxxxemployee(
			Jxxxbh400xwwqqhxxxxxemployee jxxxbh400xwwqqhxxxxxemployee) {
		this.jxxxbh400xwwqqhxxxxxemployee = jxxxbh400xwwqqhxxxxxemployee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matcode")
	public Fpxxfq1a5xwwqqhxxxxxitem getFpxxfq1a5xwwqqhxxxxxitem() {
		return this.fpxxfq1a5xwwqqhxxxxxitem;
	}

	public void setFpxxfq1a5xwwqqhxxxxxitem(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pono")
	public Trexuq344xwwqqhxxxxxvendorders getTrexuq344xwwqqhxxxxxvendorders() {
		return this.trexuq344xwwqqhxxxxxvendorders;
	}

	public void setTrexuq344xwwqqhxxxxxvendorders(
			Trexuq344xwwqqhxxxxxvendorders trexuq344xwwqqhxxxxxvendorders) {
		this.trexuq344xwwqqhxxxxxvendorders = trexuq344xwwqqhxxxxxvendorders;
	}

	@Column(name = "invoice", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxunvibvxxxxxxxxxxinvoice() {
		return this.a0xxunvibvxxxxxxxxxxinvoice;
	}

	public void setA0xxunvibvxxxxxxxxxxinvoice(
			String a0xxunvibvxxxxxxxxxxinvoice) {
		this.a0xxunvibvxxxxxxxxxxinvoice = a0xxunvibvxxxxxxxxxxinvoice;
	}

	@Column(name = "integrset", length = 20)
	@Size(max = 20)
	public String getY2xxuwmxbv40xxxxxxxxintegrset() {
		return this.y2xxuwmxbv40xxxxxxxxintegrset;
	}

	public void setY2xxuwmxbv40xxxxxxxxintegrset(
			String y2xxuwmxbv40xxxxxxxxintegrset) {
		this.y2xxuwmxbv40xxxxxxxxintegrset = y2xxuwmxbv40xxxxxxxxintegrset;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invodate", length = 29)
	public Date getB3xxuxxrbvxxxxxxxxxxinvodate() {
		return this.b3xxuxxrbvxxxxxxxxxxinvodate;
	}

	public void setB3xxuxxrbvxxxxxxxxxxinvodate(
			Date b3xxuxxrbvxxxxxxxxxxinvodate) {
		this.b3xxuxxrbvxxxxxxxxxxinvodate = b3xxuxxrbvxxxxxxxxxxinvodate;
	}

	@Column(name = "amounttotal", precision = 14)
	public BigDecimal getB3xxztprlxxxxxxxxxxxamounttotal() {
		return this.b3xxztprlxxxxxxxxxxxamounttotal;
	}

	public void setB3xxztprlxxxxxxxxxxxamounttotal(
			BigDecimal b3xxztprlxxxxxxxxxxxamounttotal) {
		this.b3xxztprlxxxxxxxxxxxamounttotal = b3xxztprlxxxxxxxxxxxamounttotal;
	}

	@Column(name = "amountostndt", precision = 14)
	public BigDecimal getZ1xxzyprlxxxxxxxxxxxamountostndt() {
		return this.z1xxzyprlxxxxxxxxxxxamountostndt;
	}

	public void setZ1xxzyprlxxxxxxxxxxxamountostndt(
			BigDecimal z1xxzyprlxxxxxxxxxxxamountostndt) {
		this.z1xxzyprlxxxxxxxxxxxamountostndt = z1xxzyprlxxxxxxxxxxxamountostndt;
	}

	@Column(name = "qtytotal", precision = 14)
	public BigDecimal getZ2xxztqrlxxxxxxxxxxxqtytotal() {
		return this.z2xxztqrlxxxxxxxxxxxqtytotal;
	}

	public void setZ2xxztqrlxxxxxxxxxxxqtytotal(
			BigDecimal z2xxztqrlxxxxxxxxxxxqtytotal) {
		this.z2xxztqrlxxxxxxxxxxxqtytotal = z2xxztqrlxxxxxxxxxxxqtytotal;
	}

	@Column(name = "qtyostndt", precision = 14)
	public BigDecimal getZ3xxzyqrlxxxxxxxxxxxqtyostndt() {
		return this.z3xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	public void setZ3xxzyqrlxxxxxxxxxxxqtyostndt(
			BigDecimal z3xxzyqrlxxxxxxxxxxxqtyostndt) {
		this.z3xxzyqrlxxxxxxxxxxxqtyostndt = z3xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	@Column(name = "ref1typ", length = 20)
	@Size(max = 20)
	public String getY4xxuxxrbvxxxxxxxxxxref1typ() {
		return this.y4xxuxxrbvxxxxxxxxxxref1typ;
	}

	public void setY4xxuxxrbvxxxxxxxxxxref1typ(
			String y4xxuxxrbvxxxxxxxxxxref1typ) {
		this.y4xxuxxrbvxxxxxxxxxxref1typ = y4xxuxxrbvxxxxxxxxxxref1typ;
	}

	@Column(name = "ref1code", length = 35)
	@Size(max = 35)
	public String getY5xxuxxrbvxxxxxxxxxxref1code() {
		return this.y5xxuxxrbvxxxxxxxxxxref1code;
	}

	public void setY5xxuxxrbvxxxxxxxxxxref1code(
			String y5xxuxxrbvxxxxxxxxxxref1code) {
		this.y5xxuxxrbvxxxxxxxxxxref1code = y5xxuxxrbvxxxxxxxxxxref1code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shipdatet", length = 29)
	public Date getY6xxcxxrlxxxxxxxxxxxshipdatet() {
		return this.y6xxcxxrlxxxxxxxxxxxshipdatet;
	}

	public void setY6xxcxxrlxxxxxxxxxxxshipdatet(
			Date y6xxcxxrlxxxxxxxxxxxshipdatet) {
		this.y6xxcxxrlxxxxxxxxxxxshipdatet = y6xxcxxrlxxxxxxxxxxxshipdatet;
	}

	@Column(name = "shiptype", length = 12)
	@Size(max = 12)
	public String getY7xxuxxrbv51xxxxxxxxshiptype() {
		return this.y7xxuxxrbv51xxxxxxxxshiptype;
	}

	public void setY7xxuxxrbv51xxxxxxxxshiptype(
			String y7xxuxxrbv51xxxxxxxxshiptype) {
		this.y7xxuxxrbv51xxxxxxxxshiptype = y7xxuxxrbv51xxxxxxxxshiptype;
	}

	@Column(name = "terms", length = 20)
	@Size(max = 20)
	public String getB4xxuxxrbv09xxxxxxxxterms() {
		return this.b4xxuxxrbv09xxxxxxxxterms;
	}

	public void setB4xxuxxrbv09xxxxxxxxterms(String b4xxuxxrbv09xxxxxxxxterms) {
		this.b4xxuxxrbv09xxxxxxxxterms = b4xxuxxrbv09xxxxxxxxterms;
	}

	@Column(name = "statusfl")
	public Integer getZ4xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z4xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ4xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z4xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z4xxzzfxhhxxxxxxxxxxstatusfl = z4xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ5xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z5xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ5xxcztxlxxxxxxxxxxxstatusfldt(
			Date z5xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z5xxcztxlxxxxxxxxxxxstatusfldt = z5xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "termsdat", length = 29)
	public Date getZ6xxcxxrlxxxxxxxxxxxtermsdat() {
		return this.z6xxcxxrlxxxxxxxxxxxtermsdat;
	}

	public void setZ6xxcxxrlxxxxxxxxxxxtermsdat(
			Date z6xxcxxrlxxxxxxxxxxxtermsdat) {
		this.z6xxcxxrlxxxxxxxxxxxtermsdat = z6xxcxxrlxxxxxxxxxxxtermsdat;
	}

	@Column(name = "discounp", precision = 14)
	public BigDecimal getC1xxzixrbvxxxxxxxxxxdiscounp() {
		return this.c1xxzixrbvxxxxxxxxxxdiscounp;
	}

	public void setC1xxzixrbvxxxxxxxxxxdiscounp(
			BigDecimal c1xxzixrbvxxxxxxxxxxdiscounp) {
		this.c1xxzixrbvxxxxxxxxxxdiscounp = c1xxzixrbvxxxxxxxxxxdiscounp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "discoudt", length = 29)
	public Date getC2xxcxxrlxxxxxxxxxxxdiscoudt() {
		return this.c2xxcxxrlxxxxxxxxxxxdiscoudt;
	}

	public void setC2xxcxxrlxxxxxxxxxxxdiscoudt(
			Date c2xxcxxrlxxxxxxxxxxxdiscoudt) {
		this.c2xxcxxrlxxxxxxxxxxxdiscoudt = c2xxcxxrlxxxxxxxxxxxdiscoudt;
	}

	@Column(name = "discouds", precision = 14)
	public BigDecimal getC3xxzxxrlvxxxxxxxxxxdiscouds() {
		return this.c3xxzxxrlvxxxxxxxxxxdiscouds;
	}

	public void setC3xxzxxrlvxxxxxxxxxxdiscouds(
			BigDecimal c3xxzxxrlvxxxxxxxxxxdiscouds) {
		this.c3xxzxxrlvxxxxxxxxxxdiscouds = c3xxzxxrlvxxxxxxxxxxdiscouds;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "netddat", length = 29)
	public Date getC4xxcxxrlxxxxxxxxxxxnetddat() {
		return this.c4xxcxxrlxxxxxxxxxxxnetddat;
	}

	public void setC4xxcxxrlxxxxxxxxxxxnetddat(Date c4xxcxxrlxxxxxxxxxxxnetddat) {
		this.c4xxcxxrlxxxxxxxxxxxnetddat = c4xxcxxrlxxxxxxxxxxxnetddat;
	}

	@Column(name = "netddys")
	public Integer getC5xxzxxrbvxxxxxxxxxxnetddys() {
		return this.c5xxzxxrbvxxxxxxxxxxnetddys;
	}

	public void setC5xxzxxrbvxxxxxxxxxxnetddys(
			Integer c5xxzxxrbvxxxxxxxxxxnetddys) {
		this.c5xxzxxrbvxxxxxxxxxxnetddys = c5xxzxxrbvxxxxxxxxxxnetddys;
	}

	@Column(name = "fob", length = 20)
	@Size(max = 20)
	public String getC6xxuxxrbvxxxxxxxxxxfob() {
		return this.c6xxuxxrbvxxxxxxxxxxfob;
	}

	public void setC6xxuxxrbvxxxxxxxxxxfob(String c6xxuxxrbvxxxxxxxxxxfob) {
		this.c6xxuxxrbvxxxxxxxxxxfob = c6xxuxxrbvxxxxxxxxxxfob;
	}

	@Column(name = "type", length = 12)
	@Size(max = 12)
	public String getC7xxuxxrbv10xxxxxxxxtype() {
		return this.c7xxuxxrbv10xxxxxxxxtype;
	}

	public void setC7xxuxxrbv10xxxxxxxxtype(String c7xxuxxrbv10xxxxxxxxtype) {
		this.c7xxuxxrbv10xxxxxxxxtype = c7xxuxxrbv10xxxxxxxxtype;
	}

	@Column(name = "attach", length = 20)
	@Size(max = 20)
	public String getYdxxuxxrbvxxxxxxxxxxattach() {
		return this.ydxxuxxrbvxxxxxxxxxxattach;
	}

	public void setYdxxuxxrbvxxxxxxxxxxattach(String ydxxuxxrbvxxxxxxxxxxattach) {
		this.ydxxuxxrbvxxxxxxxxxxattach = ydxxuxxrbvxxxxxxxxxxattach;
	}

	@Column(name = "baseamountt", precision = 14)
	public BigDecimal getZ7xxzbtxavxxxxxxxxxxbaseamountt() {
		return this.z7xxzbtxavxxxxxxxxxxbaseamountt;
	}

	public void setZ7xxzbtxavxxxxxxxxxxbaseamountt(
			BigDecimal z7xxzbtxavxxxxxxxxxxbaseamountt) {
		this.z7xxzbtxavxxxxxxxxxxbaseamountt = z7xxzbtxavxxxxxxxxxxbaseamountt;
	}

	@Column(name = "delivchrgt", precision = 14)
	public BigDecimal getZ7xxzltxavxxxxxxxxxxdelivchrgt() {
		return this.z7xxzltxavxxxxxxxxxxdelivchrgt;
	}

	public void setZ7xxzltxavxxxxxxxxxxdelivchrgt(
			BigDecimal z7xxzltxavxxxxxxxxxxdelivchrgt) {
		this.z7xxzltxavxxxxxxxxxxdelivchrgt = z7xxzltxavxxxxxxxxxxdelivchrgt;
	}

	@Column(name = "miscchrgt", precision = 14)
	public BigDecimal getZ8xxzmtxavxxxxxxxxxxmiscchrgt() {
		return this.z8xxzmtxavxxxxxxxxxxmiscchrgt;
	}

	public void setZ8xxzmtxavxxxxxxxxxxmiscchrgt(
			BigDecimal z8xxzmtxavxxxxxxxxxxmiscchrgt) {
		this.z8xxzmtxavxxxxxxxxxxmiscchrgt = z8xxzmtxavxxxxxxxxxxmiscchrgt;
	}

	@Column(name = "tax1amtt", precision = 14)
	public BigDecimal getZ9xxzxz1avxxxxxxxxxxtax1amtt() {
		return this.z9xxzxz1avxxxxxxxxxxtax1amtt;
	}

	public void setZ9xxzxz1avxxxxxxxxxxtax1amtt(
			BigDecimal z9xxzxz1avxxxxxxxxxxtax1amtt) {
		this.z9xxzxz1avxxxxxxxxxxtax1amtt = z9xxzxz1avxxxxxxxxxxtax1amtt;
	}

	@Column(name = "tax2amtt", precision = 14)
	public BigDecimal getZaxxzxz2avxxxxxxxxxxtax2amtt() {
		return this.zaxxzxz2avxxxxxxxxxxtax2amtt;
	}

	public void setZaxxzxz2avxxxxxxxxxxtax2amtt(
			BigDecimal zaxxzxz2avxxxxxxxxxxtax2amtt) {
		this.zaxxzxz2avxxxxxxxxxxtax2amtt = zaxxzxz2avxxxxxxxxxxtax2amtt;
	}

	@Column(name = "tax3amtt", precision = 14)
	public BigDecimal getZbxxzxz3avxxxxxxxxxxtax3amtt() {
		return this.zbxxzxz3avxxxxxxxxxxtax3amtt;
	}

	public void setZbxxzxz3avxxxxxxxxxxtax3amtt(
			BigDecimal zbxxzxz3avxxxxxxxxxxtax3amtt) {
		this.zbxxzxz3avxxxxxxxxxxtax3amtt = zbxxzxz3avxxxxxxxxxxtax3amtt;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getYexxuznybvxxxxxxxxxxnotes() {
		return this.yexxuznybvxxxxxxxxxxnotes;
	}

	public void setYexxuznybvxxxxxxxxxxnotes(String yexxuznybvxxxxxxxxxxnotes) {
		this.yexxuznybvxxxxxxxxxxnotes = yexxuznybvxxxxxxxxxxnotes;
	}

	@Column(name = "printmstat")
	public Integer getZcxxzzprhvxxxxxxxxxxprintmstat() {
		return this.zcxxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZcxxzzprhvxxxxxxxxxxprintmstat(
			Integer zcxxzzprhvxxxxxxxxxxprintmstat) {
		this.zcxxzzprhvxxxxxxxxxxprintmstat = zcxxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZdxxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.zdxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZdxxczqxlhxxxxxxxxxxprinmtfldt(
			Date zdxxczqxlhxxxxxxxxxxprinmtfldt) {
		this.zdxxczqxlhxxxxxxxxxxprinmtfldt = zdxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZexxutoxlhxxxxxxxxxxowner() {
		return this.zexxutoxlhxxxxxxxxxxowner;
	}

	public void setZexxutoxlhxxxxxxxxxxowner(String zexxutoxlhxxxxxxxxxxowner) {
		this.zexxutoxlhxxxxxxxxxxowner = zexxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "docmnt", length = 90)
	@Size(max = 90)
	public String getYfxxuzdrbvxxxxxxxxxxdocmnt() {
		return this.yfxxuzdrbvxxxxxxxxxxdocmnt;
	}

	public void setYfxxuzdrbvxxxxxxxxxxdocmnt(String yfxxuzdrbvxxxxxxxxxxdocmnt) {
		this.yfxxuzdrbvxxxxxxxxxxdocmnt = yfxxuzdrbvxxxxxxxxxxdocmnt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trexuq3a6xwwqqhxxxxxvinvoice")
	public Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> getXoxxuq3b4xwwqqhxxxxxvendpdetailses() {
		return this.xoxxuq3b4xwwqqhxxxxxvendpdetailses;
	}

	public void setXoxxuq3b4xwwqqhxxxxxvendpdetailses(
			Set<Xoxxuq3b4xwwqqhxxxxxvendpdetails> xoxxuq3b4xwwqqhxxxxxvendpdetailses) {
		this.xoxxuq3b4xwwqqhxxxxxvendpdetailses = xoxxuq3b4xwwqqhxxxxxvendpdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trexuq3a6xwwqqhxxxxxvinvoice")
	public Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> getXoxxuq3c4xwwqqhxxxxxvendidetailses() {
		return this.xoxxuq3c4xwwqqhxxxxxvendidetailses;
	}

	public void setXoxxuq3c4xwwqqhxxxxxvendidetailses(
			Set<Xoxxuq3c4xwwqqhxxxxxvendidetails> xoxxuq3c4xwwqqhxxxxxvendidetailses) {
		this.xoxxuq3c4xwwqqhxxxxxvendidetailses = xoxxuq3c4xwwqqhxxxxxvendidetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trexuq3a6xwwqqhxxxxxvinvoice")
	public Set<Trexuq388xwwqqhxxxxxvpayment> getTrexuq388xwwqqhxxxxxvpayments() {
		return this.trexuq388xwwqqhxxxxxvpayments;
	}

	public void setTrexuq388xwwqqhxxxxxvpayments(
			Set<Trexuq388xwwqqhxxxxxvpayment> trexuq388xwwqqhxxxxxvpayments) {
		this.trexuq388xwwqqhxxxxxvpayments = trexuq388xwwqqhxxxxxvpayments;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
