package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Trexuq277xwwqqhxxxxxcpayment generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "cpayment")
public class Trexuq277xwwqqhxxxxxcpayment implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer;
	private Trexuq266xwwqqhxxxxxcuinvoice trexuq266xwwqqhxxxxxcuinvoice;
	private Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount;
	private String a0xxuncpbvxxxxxxxxxxpayment;
	private Date c5xxxxxrlxxxxxxxxxxxcheqdate;
	private Date c7xxxxxrlxxxxxxxxxxxpaymentduedate;
	private Integer c9xxpxiravxxxxxxxxxxpostingperiod;
	private Integer b3xxudiravxxxxxxxxxxmatcode;
	private String f1xxuwmxbv40xxxxxxxxintegrset;
	private BigDecimal z1xxztprlxxxxxxxxxxxamounttotal;
	private BigDecimal z2xxzyprlxxxxxxxxxxxamountostndt;
	private BigDecimal d1xxzyprlxxxxxxxxxxxamountin;
	private BigDecimal z3xxztqrlxxxxxxxxxxxqtytotal;
	private BigDecimal z4xxzyqrlxxxxxxxxxxxqtyostndt;
	private BigDecimal b3xxzixrbvxxxxxxxxxxdiscount;
	private BigDecimal z7xxzbtxavxxxxxxxxxxbaseamountt;
	private BigDecimal z7xxzltxavxxxxxxxxxxdelivchrgt;
	private BigDecimal z8xxzmtxavxxxxxxxxxxmiscchrgt;
	private BigDecimal b4xxzxz1avxxxxxxxxxxtax1amtt;
	private BigDecimal b5xxzxz2avxxxxxxxxxxtax2amtt;
	private BigDecimal y2xxzxz3avxxxxxxxxxxtax3amtt;
	private String b6xxuxxrbv10xxxxxxxxpaytype;
	private String z5xxuxxrbvxxxxxxxxxxpaybyid;
	private Date z6xxcxxrlxxxxxxxxxxxpaybydate;
	private String d1xxzxxrlvxxxxxxxxxxcurrency;
	private BigDecimal d2xxzxxrlvxxxxxxxxxxconvrate;
	private BigDecimal z7xxzxxrlvxxxxxxxxxxlocamountt;
	private Integer z8xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z9xxcztxlxxxxxxxxxxxstatusfldt;
	private String y2xxuxznbvxxxxxxxxxxnotes;
	private String zaxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private Set<Xoxxuq284xwwqqhxxxxxcupdetails> xoxxuq284xwwqqhxxxxxcupdetailses = new HashSet<Xoxxuq284xwwqqhxxxxxcupdetails>(
			0);

	public Trexuq277xwwqqhxxxxxcpayment() {
	}

	public Trexuq277xwwqqhxxxxxcpayment(String a0xxuncpbvxxxxxxxxxxpayment) {
		this.a0xxuncpbvxxxxxxxxxxpayment = a0xxuncpbvxxxxxxxxxxpayment;
	}
	public Trexuq277xwwqqhxxxxxcpayment(
			Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer,
			Trexuq266xwwqqhxxxxxcuinvoice trexuq266xwwqqhxxxxxcuinvoice,
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount,
			String a0xxuncpbvxxxxxxxxxxpayment,
			Date c5xxxxxrlxxxxxxxxxxxcheqdate,
			Date c7xxxxxrlxxxxxxxxxxxpaymentduedate,
			Integer c9xxpxiravxxxxxxxxxxpostingperiod,
			Integer b3xxudiravxxxxxxxxxxmatcode,
			String f1xxuwmxbv40xxxxxxxxintegrset,
			BigDecimal z1xxztprlxxxxxxxxxxxamounttotal,
			BigDecimal z2xxzyprlxxxxxxxxxxxamountostndt,
			BigDecimal d1xxzyprlxxxxxxxxxxxamountin,
			BigDecimal z3xxztqrlxxxxxxxxxxxqtytotal,
			BigDecimal z4xxzyqrlxxxxxxxxxxxqtyostndt,
			BigDecimal b3xxzixrbvxxxxxxxxxxdiscount,
			BigDecimal z7xxzbtxavxxxxxxxxxxbaseamountt,
			BigDecimal z7xxzltxavxxxxxxxxxxdelivchrgt,
			BigDecimal z8xxzmtxavxxxxxxxxxxmiscchrgt,
			BigDecimal b4xxzxz1avxxxxxxxxxxtax1amtt,
			BigDecimal b5xxzxz2avxxxxxxxxxxtax2amtt,
			BigDecimal y2xxzxz3avxxxxxxxxxxtax3amtt,
			String b6xxuxxrbv10xxxxxxxxpaytype,
			String z5xxuxxrbvxxxxxxxxxxpaybyid,
			Date z6xxcxxrlxxxxxxxxxxxpaybydate,
			String d1xxzxxrlvxxxxxxxxxxcurrency,
			BigDecimal d2xxzxxrlvxxxxxxxxxxconvrate,
			BigDecimal z7xxzxxrlvxxxxxxxxxxlocamountt,
			Integer z8xxzzfxhhxxxxxxxxxxstatusfl,
			Date z9xxcztxlxxxxxxxxxxxstatusfldt,
			String y2xxuxznbvxxxxxxxxxxnotes, String zaxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			Set<Xoxxuq284xwwqqhxxxxxcupdetails> xoxxuq284xwwqqhxxxxxcupdetailses) {
		this.jxxxuq201xwwqqhxxxxxcustomer = jxxxuq201xwwqqhxxxxxcustomer;
		this.trexuq266xwwqqhxxxxxcuinvoice = trexuq266xwwqqhxxxxxcuinvoice;
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
		this.a0xxuncpbvxxxxxxxxxxpayment = a0xxuncpbvxxxxxxxxxxpayment;
		this.c5xxxxxrlxxxxxxxxxxxcheqdate = c5xxxxxrlxxxxxxxxxxxcheqdate;
		this.c7xxxxxrlxxxxxxxxxxxpaymentduedate = c7xxxxxrlxxxxxxxxxxxpaymentduedate;
		this.c9xxpxiravxxxxxxxxxxpostingperiod = c9xxpxiravxxxxxxxxxxpostingperiod;
		this.b3xxudiravxxxxxxxxxxmatcode = b3xxudiravxxxxxxxxxxmatcode;
		this.f1xxuwmxbv40xxxxxxxxintegrset = f1xxuwmxbv40xxxxxxxxintegrset;
		this.z1xxztprlxxxxxxxxxxxamounttotal = z1xxztprlxxxxxxxxxxxamounttotal;
		this.z2xxzyprlxxxxxxxxxxxamountostndt = z2xxzyprlxxxxxxxxxxxamountostndt;
		this.d1xxzyprlxxxxxxxxxxxamountin = d1xxzyprlxxxxxxxxxxxamountin;
		this.z3xxztqrlxxxxxxxxxxxqtytotal = z3xxztqrlxxxxxxxxxxxqtytotal;
		this.z4xxzyqrlxxxxxxxxxxxqtyostndt = z4xxzyqrlxxxxxxxxxxxqtyostndt;
		this.b3xxzixrbvxxxxxxxxxxdiscount = b3xxzixrbvxxxxxxxxxxdiscount;
		this.z7xxzbtxavxxxxxxxxxxbaseamountt = z7xxzbtxavxxxxxxxxxxbaseamountt;
		this.z7xxzltxavxxxxxxxxxxdelivchrgt = z7xxzltxavxxxxxxxxxxdelivchrgt;
		this.z8xxzmtxavxxxxxxxxxxmiscchrgt = z8xxzmtxavxxxxxxxxxxmiscchrgt;
		this.b4xxzxz1avxxxxxxxxxxtax1amtt = b4xxzxz1avxxxxxxxxxxtax1amtt;
		this.b5xxzxz2avxxxxxxxxxxtax2amtt = b5xxzxz2avxxxxxxxxxxtax2amtt;
		this.y2xxzxz3avxxxxxxxxxxtax3amtt = y2xxzxz3avxxxxxxxxxxtax3amtt;
		this.b6xxuxxrbv10xxxxxxxxpaytype = b6xxuxxrbv10xxxxxxxxpaytype;
		this.z5xxuxxrbvxxxxxxxxxxpaybyid = z5xxuxxrbvxxxxxxxxxxpaybyid;
		this.z6xxcxxrlxxxxxxxxxxxpaybydate = z6xxcxxrlxxxxxxxxxxxpaybydate;
		this.d1xxzxxrlvxxxxxxxxxxcurrency = d1xxzxxrlvxxxxxxxxxxcurrency;
		this.d2xxzxxrlvxxxxxxxxxxconvrate = d2xxzxxrlvxxxxxxxxxxconvrate;
		this.z7xxzxxrlvxxxxxxxxxxlocamountt = z7xxzxxrlvxxxxxxxxxxlocamountt;
		this.z8xxzzfxhhxxxxxxxxxxstatusfl = z8xxzzfxhhxxxxxxxxxxstatusfl;
		this.z9xxcztxlxxxxxxxxxxxstatusfldt = z9xxcztxlxxxxxxxxxxxstatusfldt;
		this.y2xxuxznbvxxxxxxxxxxnotes = y2xxuxznbvxxxxxxxxxxnotes;
		this.zaxxutoxlhxxxxxxxxxxowner = zaxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.xoxxuq284xwwqqhxxxxxcupdetailses = xoxxuq284xwwqqhxxxxxcupdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer")
	public Jxxxuq201xwwqqhxxxxxcustomer getJxxxuq201xwwqqhxxxxxcustomer() {
		return this.jxxxuq201xwwqqhxxxxxcustomer;
	}

	public void setJxxxuq201xwwqqhxxxxxcustomer(
			Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer) {
		this.jxxxuq201xwwqqhxxxxxcustomer = jxxxuq201xwwqqhxxxxxcustomer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinvoice")
	public Trexuq266xwwqqhxxxxxcuinvoice getTrexuq266xwwqqhxxxxxcuinvoice() {
		return this.trexuq266xwwqqhxxxxxcuinvoice;
	}

	public void setTrexuq266xwwqqhxxxxxcuinvoice(
			Trexuq266xwwqqhxxxxxcuinvoice trexuq266xwwqqhxxxxxcuinvoice) {
		this.trexuq266xwwqqhxxxxxcuinvoice = trexuq266xwwqqhxxxxxcuinvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account")
	public Yxxxch601xwwqqhxxxxxaccount getYxxxch601xwwqqhxxxxxaccount() {
		return this.yxxxch601xwwqqhxxxxxaccount;
	}

	public void setYxxxch601xwwqqhxxxxxaccount(
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount) {
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
	}

	@Column(name = "payment", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxuncpbvxxxxxxxxxxpayment() {
		return this.a0xxuncpbvxxxxxxxxxxpayment;
	}

	public void setA0xxuncpbvxxxxxxxxxxpayment(
			String a0xxuncpbvxxxxxxxxxxpayment) {
		this.a0xxuncpbvxxxxxxxxxxpayment = a0xxuncpbvxxxxxxxxxxpayment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cheqdate", length = 29)
	public Date getC5xxxxxrlxxxxxxxxxxxcheqdate() {
		return this.c5xxxxxrlxxxxxxxxxxxcheqdate;
	}

	public void setC5xxxxxrlxxxxxxxxxxxcheqdate(
			Date c5xxxxxrlxxxxxxxxxxxcheqdate) {
		this.c5xxxxxrlxxxxxxxxxxxcheqdate = c5xxxxxrlxxxxxxxxxxxcheqdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paymentduedate", length = 29)
	public Date getC7xxxxxrlxxxxxxxxxxxpaymentduedate() {
		return this.c7xxxxxrlxxxxxxxxxxxpaymentduedate;
	}

	public void setC7xxxxxrlxxxxxxxxxxxpaymentduedate(
			Date c7xxxxxrlxxxxxxxxxxxpaymentduedate) {
		this.c7xxxxxrlxxxxxxxxxxxpaymentduedate = c7xxxxxrlxxxxxxxxxxxpaymentduedate;
	}

	@Column(name = "postingperiod")
	public Integer getC9xxpxiravxxxxxxxxxxpostingperiod() {
		return this.c9xxpxiravxxxxxxxxxxpostingperiod;
	}

	public void setC9xxpxiravxxxxxxxxxxpostingperiod(
			Integer c9xxpxiravxxxxxxxxxxpostingperiod) {
		this.c9xxpxiravxxxxxxxxxxpostingperiod = c9xxpxiravxxxxxxxxxxpostingperiod;
	}

	@Column(name = "matcode")
	public Integer getB3xxudiravxxxxxxxxxxmatcode() {
		return this.b3xxudiravxxxxxxxxxxmatcode;
	}

	public void setB3xxudiravxxxxxxxxxxmatcode(
			Integer b3xxudiravxxxxxxxxxxmatcode) {
		this.b3xxudiravxxxxxxxxxxmatcode = b3xxudiravxxxxxxxxxxmatcode;
	}

	@Column(name = "integrset", length = 20)
	@Size(max = 20)
	public String getF1xxuwmxbv40xxxxxxxxintegrset() {
		return this.f1xxuwmxbv40xxxxxxxxintegrset;
	}

	public void setF1xxuwmxbv40xxxxxxxxintegrset(
			String f1xxuwmxbv40xxxxxxxxintegrset) {
		this.f1xxuwmxbv40xxxxxxxxintegrset = f1xxuwmxbv40xxxxxxxxintegrset;
	}

	@Column(name = "amounttotal", precision = 14)
	public BigDecimal getZ1xxztprlxxxxxxxxxxxamounttotal() {
		return this.z1xxztprlxxxxxxxxxxxamounttotal;
	}

	public void setZ1xxztprlxxxxxxxxxxxamounttotal(
			BigDecimal z1xxztprlxxxxxxxxxxxamounttotal) {
		this.z1xxztprlxxxxxxxxxxxamounttotal = z1xxztprlxxxxxxxxxxxamounttotal;
	}

	@Column(name = "amountostndt", precision = 14)
	public BigDecimal getZ2xxzyprlxxxxxxxxxxxamountostndt() {
		return this.z2xxzyprlxxxxxxxxxxxamountostndt;
	}

	public void setZ2xxzyprlxxxxxxxxxxxamountostndt(
			BigDecimal z2xxzyprlxxxxxxxxxxxamountostndt) {
		this.z2xxzyprlxxxxxxxxxxxamountostndt = z2xxzyprlxxxxxxxxxxxamountostndt;
	}

	@Column(name = "amountin", precision = 14)
	public BigDecimal getD1xxzyprlxxxxxxxxxxxamountin() {
		return this.d1xxzyprlxxxxxxxxxxxamountin;
	}

	public void setD1xxzyprlxxxxxxxxxxxamountin(
			BigDecimal d1xxzyprlxxxxxxxxxxxamountin) {
		this.d1xxzyprlxxxxxxxxxxxamountin = d1xxzyprlxxxxxxxxxxxamountin;
	}

	@Column(name = "qtytotal", precision = 14)
	public BigDecimal getZ3xxztqrlxxxxxxxxxxxqtytotal() {
		return this.z3xxztqrlxxxxxxxxxxxqtytotal;
	}

	public void setZ3xxztqrlxxxxxxxxxxxqtytotal(
			BigDecimal z3xxztqrlxxxxxxxxxxxqtytotal) {
		this.z3xxztqrlxxxxxxxxxxxqtytotal = z3xxztqrlxxxxxxxxxxxqtytotal;
	}

	@Column(name = "qtyostndt", precision = 14)
	public BigDecimal getZ4xxzyqrlxxxxxxxxxxxqtyostndt() {
		return this.z4xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	public void setZ4xxzyqrlxxxxxxxxxxxqtyostndt(
			BigDecimal z4xxzyqrlxxxxxxxxxxxqtyostndt) {
		this.z4xxzyqrlxxxxxxxxxxxqtyostndt = z4xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	@Column(name = "discount", precision = 14)
	public BigDecimal getB3xxzixrbvxxxxxxxxxxdiscount() {
		return this.b3xxzixrbvxxxxxxxxxxdiscount;
	}

	public void setB3xxzixrbvxxxxxxxxxxdiscount(
			BigDecimal b3xxzixrbvxxxxxxxxxxdiscount) {
		this.b3xxzixrbvxxxxxxxxxxdiscount = b3xxzixrbvxxxxxxxxxxdiscount;
	}

	@Column(name = "baseamountt", precision = 14)
	public BigDecimal getZ7xxzbtxavxxxxxxxxxxbaseamountt() {
		return this.z7xxzbtxavxxxxxxxxxxbaseamountt;
	}

	public void setZ7xxzbtxavxxxxxxxxxxbaseamountt(
			BigDecimal z7xxzbtxavxxxxxxxxxxbaseamountt) {
		this.z7xxzbtxavxxxxxxxxxxbaseamountt = z7xxzbtxavxxxxxxxxxxbaseamountt;
	}

	@Column(name = "delivchrgt", precision = 14)
	public BigDecimal getZ7xxzltxavxxxxxxxxxxdelivchrgt() {
		return this.z7xxzltxavxxxxxxxxxxdelivchrgt;
	}

	public void setZ7xxzltxavxxxxxxxxxxdelivchrgt(
			BigDecimal z7xxzltxavxxxxxxxxxxdelivchrgt) {
		this.z7xxzltxavxxxxxxxxxxdelivchrgt = z7xxzltxavxxxxxxxxxxdelivchrgt;
	}

	@Column(name = "miscchrgt", precision = 14)
	public BigDecimal getZ8xxzmtxavxxxxxxxxxxmiscchrgt() {
		return this.z8xxzmtxavxxxxxxxxxxmiscchrgt;
	}

	public void setZ8xxzmtxavxxxxxxxxxxmiscchrgt(
			BigDecimal z8xxzmtxavxxxxxxxxxxmiscchrgt) {
		this.z8xxzmtxavxxxxxxxxxxmiscchrgt = z8xxzmtxavxxxxxxxxxxmiscchrgt;
	}

	@Column(name = "tax1amtt", precision = 14)
	public BigDecimal getB4xxzxz1avxxxxxxxxxxtax1amtt() {
		return this.b4xxzxz1avxxxxxxxxxxtax1amtt;
	}

	public void setB4xxzxz1avxxxxxxxxxxtax1amtt(
			BigDecimal b4xxzxz1avxxxxxxxxxxtax1amtt) {
		this.b4xxzxz1avxxxxxxxxxxtax1amtt = b4xxzxz1avxxxxxxxxxxtax1amtt;
	}

	@Column(name = "tax2amtt", precision = 14)
	public BigDecimal getB5xxzxz2avxxxxxxxxxxtax2amtt() {
		return this.b5xxzxz2avxxxxxxxxxxtax2amtt;
	}

	public void setB5xxzxz2avxxxxxxxxxxtax2amtt(
			BigDecimal b5xxzxz2avxxxxxxxxxxtax2amtt) {
		this.b5xxzxz2avxxxxxxxxxxtax2amtt = b5xxzxz2avxxxxxxxxxxtax2amtt;
	}

	@Column(name = "tax3amtt", precision = 14)
	public BigDecimal getY2xxzxz3avxxxxxxxxxxtax3amtt() {
		return this.y2xxzxz3avxxxxxxxxxxtax3amtt;
	}

	public void setY2xxzxz3avxxxxxxxxxxtax3amtt(
			BigDecimal y2xxzxz3avxxxxxxxxxxtax3amtt) {
		this.y2xxzxz3avxxxxxxxxxxtax3amtt = y2xxzxz3avxxxxxxxxxxtax3amtt;
	}

	@Column(name = "paytype", length = 4)
	@Size(max = 4)
	public String getB6xxuxxrbv10xxxxxxxxpaytype() {
		return this.b6xxuxxrbv10xxxxxxxxpaytype;
	}

	public void setB6xxuxxrbv10xxxxxxxxpaytype(
			String b6xxuxxrbv10xxxxxxxxpaytype) {
		this.b6xxuxxrbv10xxxxxxxxpaytype = b6xxuxxrbv10xxxxxxxxpaytype;
	}

	@Column(name = "paybyid", length = 20)
	@Size(max = 20)
	public String getZ5xxuxxrbvxxxxxxxxxxpaybyid() {
		return this.z5xxuxxrbvxxxxxxxxxxpaybyid;
	}

	public void setZ5xxuxxrbvxxxxxxxxxxpaybyid(
			String z5xxuxxrbvxxxxxxxxxxpaybyid) {
		this.z5xxuxxrbvxxxxxxxxxxpaybyid = z5xxuxxrbvxxxxxxxxxxpaybyid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paybydate", length = 29)
	public Date getZ6xxcxxrlxxxxxxxxxxxpaybydate() {
		return this.z6xxcxxrlxxxxxxxxxxxpaybydate;
	}

	public void setZ6xxcxxrlxxxxxxxxxxxpaybydate(
			Date z6xxcxxrlxxxxxxxxxxxpaybydate) {
		this.z6xxcxxrlxxxxxxxxxxxpaybydate = z6xxcxxrlxxxxxxxxxxxpaybydate;
	}

	@Column(name = "currency", length = 12)
	@Size(max = 12)
	public String getD1xxzxxrlvxxxxxxxxxxcurrency() {
		return this.d1xxzxxrlvxxxxxxxxxxcurrency;
	}

	public void setD1xxzxxrlvxxxxxxxxxxcurrency(
			String d1xxzxxrlvxxxxxxxxxxcurrency) {
		this.d1xxzxxrlvxxxxxxxxxxcurrency = d1xxzxxrlvxxxxxxxxxxcurrency;
	}

	@Column(name = "convrate", precision = 14)
	public BigDecimal getD2xxzxxrlvxxxxxxxxxxconvrate() {
		return this.d2xxzxxrlvxxxxxxxxxxconvrate;
	}

	public void setD2xxzxxrlvxxxxxxxxxxconvrate(
			BigDecimal d2xxzxxrlvxxxxxxxxxxconvrate) {
		this.d2xxzxxrlvxxxxxxxxxxconvrate = d2xxzxxrlvxxxxxxxxxxconvrate;
	}

	@Column(name = "locamountt", precision = 14)
	public BigDecimal getZ7xxzxxrlvxxxxxxxxxxlocamountt() {
		return this.z7xxzxxrlvxxxxxxxxxxlocamountt;
	}

	public void setZ7xxzxxrlvxxxxxxxxxxlocamountt(
			BigDecimal z7xxzxxrlvxxxxxxxxxxlocamountt) {
		this.z7xxzxxrlvxxxxxxxxxxlocamountt = z7xxzxxrlvxxxxxxxxxxlocamountt;
	}

	@Column(name = "statusfl")
	public Integer getZ8xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z8xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ8xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z8xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z8xxzzfxhhxxxxxxxxxxstatusfl = z8xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ9xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z9xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ9xxcztxlxxxxxxxxxxxstatusfldt(
			Date z9xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z9xxcztxlxxxxxxxxxxxstatusfldt = z9xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY2xxuxznbvxxxxxxxxxxnotes() {
		return this.y2xxuxznbvxxxxxxxxxxnotes;
	}

	public void setY2xxuxznbvxxxxxxxxxxnotes(String y2xxuxznbvxxxxxxxxxxnotes) {
		this.y2xxuxznbvxxxxxxxxxxnotes = y2xxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZaxxutoxlhxxxxxxxxxxowner() {
		return this.zaxxutoxlhxxxxxxxxxxowner;
	}

	public void setZaxxutoxlhxxxxxxxxxxowner(String zaxxutoxlhxxxxxxxxxxowner) {
		this.zaxxutoxlhxxxxxxxxxxowner = zaxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trexuq277xwwqqhxxxxxcpayment")
	public Set<Xoxxuq284xwwqqhxxxxxcupdetails> getXoxxuq284xwwqqhxxxxxcupdetailses() {
		return this.xoxxuq284xwwqqhxxxxxcupdetailses;
	}

	public void setXoxxuq284xwwqqhxxxxxcupdetailses(
			Set<Xoxxuq284xwwqqhxxxxxcupdetails> xoxxuq284xwwqqhxxxxxcupdetailses) {
		this.xoxxuq284xwwqqhxxxxxcupdetailses = xoxxuq284xwwqqhxxxxxcupdetailses;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
