package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Trexuq255xwwqqhxxxxxshipment generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "shipment")
public class Trexuq255xwwqqhxxxxxshipment implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Trexuq266xwwqqhxxxxxcuinvoice trexuq266xwwqqhxxxxxcuinvoice;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByBilltocode;
	private Trexuq244xwwqqhxxxxxcuorders trexuq244xwwqqhxxxxxcuorders;
	private Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendorByCarrier;
	private Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer;
	private Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem;
	private Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	private Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendorByShipper;
	private String a0xxunshbvxxxxxxxxxxshipcode;
	private Integer b3xxuxcobvxxxxxxxxxxpono;
	private BigDecimal z1xxztprlxxxxxxxxxxxamounttotal;
	private BigDecimal z2xxzyprlxxxxxxxxxxxamountostndt;
	private BigDecimal z3xxztqrlxxxxxxxxxxxqtytotal;
	private BigDecimal z4xxzyqrlxxxxxxxxxxxqtyostndt;
	private String c2xxuxxrbv51xxxxxxxxtype;
	private Date c3xxcxxrlxxxxxxxxxxxshipdatet;
	private Date z6xxcxxrlxxxxxxxxxxxshipdateta;
	private String y4xxuxxrbvxxxxxxxxxxtareno;
	private String u5xxuxxrbvxxxxxxxxxxpackno;
	private Boolean d2xxugbrbvxxxxxxxxxxbilltosameasshipto;
	private String y5xxuxznbvxxxxxxxxxxnotes;
	private Integer z7xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z8xxcztxlxxxxxxxxxxxstatusfldt;
	private String z9xxuxxrbvxxxxxxxxxxserialno;
	private Integer zaxxzzprhvxxxxxxxxxxprintmstat;
	private Date zbxxczqxlhxxxxxxxxxxprinmtfldt;
	private String zcxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String zdxxuxxrbvxxxxxxxxxxbarshipcod;
	private Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> xoxxuq295xwwqqhxxxxxshipmentdetailses = new HashSet<Xoxxuq295xwwqqhxxxxxshipmentdetails>(
			0);

	public Trexuq255xwwqqhxxxxxshipment() {
	}

	public Trexuq255xwwqqhxxxxxshipment(String a0xxunshbvxxxxxxxxxxshipcode) {
		this.a0xxunshbvxxxxxxxxxxshipcode = a0xxunshbvxxxxxxxxxxshipcode;
	}
	public Trexuq255xwwqqhxxxxxshipment(
			Trexuq266xwwqqhxxxxxcuinvoice trexuq266xwwqqhxxxxxcuinvoice,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByBilltocode,
			Trexuq244xwwqqhxxxxxcuorders trexuq244xwwqqhxxxxxcuorders,
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendorByCarrier,
			Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer,
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem,
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode,
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendorByShipper,
			String a0xxunshbvxxxxxxxxxxshipcode,
			Integer b3xxuxcobvxxxxxxxxxxpono,
			BigDecimal z1xxztprlxxxxxxxxxxxamounttotal,
			BigDecimal z2xxzyprlxxxxxxxxxxxamountostndt,
			BigDecimal z3xxztqrlxxxxxxxxxxxqtytotal,
			BigDecimal z4xxzyqrlxxxxxxxxxxxqtyostndt,
			String c2xxuxxrbv51xxxxxxxxtype,
			Date c3xxcxxrlxxxxxxxxxxxshipdatet,
			Date z6xxcxxrlxxxxxxxxxxxshipdateta,
			String y4xxuxxrbvxxxxxxxxxxtareno,
			String u5xxuxxrbvxxxxxxxxxxpackno,
			Boolean d2xxugbrbvxxxxxxxxxxbilltosameasshipto,
			String y5xxuxznbvxxxxxxxxxxnotes,
			Integer z7xxzzfxhhxxxxxxxxxxstatusfl,
			Date z8xxcztxlxxxxxxxxxxxstatusfldt,
			String z9xxuxxrbvxxxxxxxxxxserialno,
			Integer zaxxzzprhvxxxxxxxxxxprintmstat,
			Date zbxxczqxlhxxxxxxxxxxprinmtfldt,
			String zcxxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String zdxxuxxrbvxxxxxxxxxxbarshipcod,
			Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> xoxxuq295xwwqqhxxxxxshipmentdetailses) {
		this.trexuq266xwwqqhxxxxxcuinvoice = trexuq266xwwqqhxxxxxcuinvoice;
		this.fxxxuq111xwwqqhxxxxxaddressByBilltocode = fxxxuq111xwwqqhxxxxxaddressByBilltocode;
		this.trexuq244xwwqqhxxxxxcuorders = trexuq244xwwqqhxxxxxcuorders;
		this.jxxxuq300xwwqqhxxxxxvendorByCarrier = jxxxuq300xwwqqhxxxxxvendorByCarrier;
		this.jxxxuq201xwwqqhxxxxxcustomer = jxxxuq201xwwqqhxxxxxcustomer;
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
		this.jxxxuq300xwwqqhxxxxxvendorByShipper = jxxxuq300xwwqqhxxxxxvendorByShipper;
		this.a0xxunshbvxxxxxxxxxxshipcode = a0xxunshbvxxxxxxxxxxshipcode;
		this.b3xxuxcobvxxxxxxxxxxpono = b3xxuxcobvxxxxxxxxxxpono;
		this.z1xxztprlxxxxxxxxxxxamounttotal = z1xxztprlxxxxxxxxxxxamounttotal;
		this.z2xxzyprlxxxxxxxxxxxamountostndt = z2xxzyprlxxxxxxxxxxxamountostndt;
		this.z3xxztqrlxxxxxxxxxxxqtytotal = z3xxztqrlxxxxxxxxxxxqtytotal;
		this.z4xxzyqrlxxxxxxxxxxxqtyostndt = z4xxzyqrlxxxxxxxxxxxqtyostndt;
		this.c2xxuxxrbv51xxxxxxxxtype = c2xxuxxrbv51xxxxxxxxtype;
		this.c3xxcxxrlxxxxxxxxxxxshipdatet = c3xxcxxrlxxxxxxxxxxxshipdatet;
		this.z6xxcxxrlxxxxxxxxxxxshipdateta = z6xxcxxrlxxxxxxxxxxxshipdateta;
		this.y4xxuxxrbvxxxxxxxxxxtareno = y4xxuxxrbvxxxxxxxxxxtareno;
		this.u5xxuxxrbvxxxxxxxxxxpackno = u5xxuxxrbvxxxxxxxxxxpackno;
		this.d2xxugbrbvxxxxxxxxxxbilltosameasshipto = d2xxugbrbvxxxxxxxxxxbilltosameasshipto;
		this.y5xxuxznbvxxxxxxxxxxnotes = y5xxuxznbvxxxxxxxxxxnotes;
		this.z7xxzzfxhhxxxxxxxxxxstatusfl = z7xxzzfxhhxxxxxxxxxxstatusfl;
		this.z8xxcztxlxxxxxxxxxxxstatusfldt = z8xxcztxlxxxxxxxxxxxstatusfldt;
		this.z9xxuxxrbvxxxxxxxxxxserialno = z9xxuxxrbvxxxxxxxxxxserialno;
		this.zaxxzzprhvxxxxxxxxxxprintmstat = zaxxzzprhvxxxxxxxxxxprintmstat;
		this.zbxxczqxlhxxxxxxxxxxprinmtfldt = zbxxczqxlhxxxxxxxxxxprinmtfldt;
		this.zcxxutoxlhxxxxxxxxxxowner = zcxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.zdxxuxxrbvxxxxxxxxxxbarshipcod = zdxxuxxrbvxxxxxxxxxxbarshipcod;
		this.xoxxuq295xwwqqhxxxxxshipmentdetailses = xoxxuq295xwwqqhxxxxxshipmentdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice")
	public Trexuq266xwwqqhxxxxxcuinvoice getTrexuq266xwwqqhxxxxxcuinvoice() {
		return this.trexuq266xwwqqhxxxxxcuinvoice;
	}

	public void setTrexuq266xwwqqhxxxxxcuinvoice(
			Trexuq266xwwqqhxxxxxcuinvoice trexuq266xwwqqhxxxxxcuinvoice) {
		this.trexuq266xwwqqhxxxxxcuinvoice = trexuq266xwwqqhxxxxxcuinvoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billtocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByBilltocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByBilltocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByBilltocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByBilltocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByBilltocode = fxxxuq111xwwqqhxxxxxaddressByBilltocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cpono")
	public Trexuq244xwwqqhxxxxxcuorders getTrexuq244xwwqqhxxxxxcuorders() {
		return this.trexuq244xwwqqhxxxxxcuorders;
	}

	public void setTrexuq244xwwqqhxxxxxcuorders(
			Trexuq244xwwqqhxxxxxcuorders trexuq244xwwqqhxxxxxcuorders) {
		this.trexuq244xwwqqhxxxxxcuorders = trexuq244xwwqqhxxxxxcuorders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "carrier")
	public Jxxxuq300xwwqqhxxxxxvendor getJxxxuq300xwwqqhxxxxxvendorByCarrier() {
		return this.jxxxuq300xwwqqhxxxxxvendorByCarrier;
	}

	public void setJxxxuq300xwwqqhxxxxxvendorByCarrier(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendorByCarrier) {
		this.jxxxuq300xwwqqhxxxxxvendorByCarrier = jxxxuq300xwwqqhxxxxxvendorByCarrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer")
	public Jxxxuq201xwwqqhxxxxxcustomer getJxxxuq201xwwqqhxxxxxcustomer() {
		return this.jxxxuq201xwwqqhxxxxxcustomer;
	}

	public void setJxxxuq201xwwqqhxxxxxcustomer(
			Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer) {
		this.jxxxuq201xwwqqhxxxxxcustomer = jxxxuq201xwwqqhxxxxxcustomer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matcode")
	public Fpxxfq1a5xwwqqhxxxxxitem getFpxxfq1a5xwwqqhxxxxxitem() {
		return this.fpxxfq1a5xwwqqhxxxxxitem;
	}

	public void setFpxxfq1a5xwwqqhxxxxxitem(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shiptocode")
	public Fxxxuq111xwwqqhxxxxxaddress getFxxxuq111xwwqqhxxxxxaddressByShiptocode() {
		return this.fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	public void setFxxxuq111xwwqqhxxxxxaddressByShiptocode(
			Fxxxuq111xwwqqhxxxxxaddress fxxxuq111xwwqqhxxxxxaddressByShiptocode) {
		this.fxxxuq111xwwqqhxxxxxaddressByShiptocode = fxxxuq111xwwqqhxxxxxaddressByShiptocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipper")
	public Jxxxuq300xwwqqhxxxxxvendor getJxxxuq300xwwqqhxxxxxvendorByShipper() {
		return this.jxxxuq300xwwqqhxxxxxvendorByShipper;
	}

	public void setJxxxuq300xwwqqhxxxxxvendorByShipper(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendorByShipper) {
		this.jxxxuq300xwwqqhxxxxxvendorByShipper = jxxxuq300xwwqqhxxxxxvendorByShipper;
	}

	@Column(name = "shipcode", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxunshbvxxxxxxxxxxshipcode() {
		return this.a0xxunshbvxxxxxxxxxxshipcode;
	}

	public void setA0xxunshbvxxxxxxxxxxshipcode(
			String a0xxunshbvxxxxxxxxxxshipcode) {
		this.a0xxunshbvxxxxxxxxxxshipcode = a0xxunshbvxxxxxxxxxxshipcode;
	}

	@Column(name = "pono")
	public Integer getB3xxuxcobvxxxxxxxxxxpono() {
		return this.b3xxuxcobvxxxxxxxxxxpono;
	}

	public void setB3xxuxcobvxxxxxxxxxxpono(Integer b3xxuxcobvxxxxxxxxxxpono) {
		this.b3xxuxcobvxxxxxxxxxxpono = b3xxuxcobvxxxxxxxxxxpono;
	}

	@Column(name = "amounttotal", precision = 14)
	public BigDecimal getZ1xxztprlxxxxxxxxxxxamounttotal() {
		return this.z1xxztprlxxxxxxxxxxxamounttotal;
	}

	public void setZ1xxztprlxxxxxxxxxxxamounttotal(
			BigDecimal z1xxztprlxxxxxxxxxxxamounttotal) {
		this.z1xxztprlxxxxxxxxxxxamounttotal = z1xxztprlxxxxxxxxxxxamounttotal;
	}

	@Column(name = "amountostndt", precision = 14)
	public BigDecimal getZ2xxzyprlxxxxxxxxxxxamountostndt() {
		return this.z2xxzyprlxxxxxxxxxxxamountostndt;
	}

	public void setZ2xxzyprlxxxxxxxxxxxamountostndt(
			BigDecimal z2xxzyprlxxxxxxxxxxxamountostndt) {
		this.z2xxzyprlxxxxxxxxxxxamountostndt = z2xxzyprlxxxxxxxxxxxamountostndt;
	}

	@Column(name = "qtytotal", precision = 14)
	public BigDecimal getZ3xxztqrlxxxxxxxxxxxqtytotal() {
		return this.z3xxztqrlxxxxxxxxxxxqtytotal;
	}

	public void setZ3xxztqrlxxxxxxxxxxxqtytotal(
			BigDecimal z3xxztqrlxxxxxxxxxxxqtytotal) {
		this.z3xxztqrlxxxxxxxxxxxqtytotal = z3xxztqrlxxxxxxxxxxxqtytotal;
	}

	@Column(name = "qtyostndt", precision = 14)
	public BigDecimal getZ4xxzyqrlxxxxxxxxxxxqtyostndt() {
		return this.z4xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	public void setZ4xxzyqrlxxxxxxxxxxxqtyostndt(
			BigDecimal z4xxzyqrlxxxxxxxxxxxqtyostndt) {
		this.z4xxzyqrlxxxxxxxxxxxqtyostndt = z4xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	@Column(name = "type", length = 12)
	@Size(max = 12)
	public String getC2xxuxxrbv51xxxxxxxxtype() {
		return this.c2xxuxxrbv51xxxxxxxxtype;
	}

	public void setC2xxuxxrbv51xxxxxxxxtype(String c2xxuxxrbv51xxxxxxxxtype) {
		this.c2xxuxxrbv51xxxxxxxxtype = c2xxuxxrbv51xxxxxxxxtype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shipdatet", length = 29)
	public Date getC3xxcxxrlxxxxxxxxxxxshipdatet() {
		return this.c3xxcxxrlxxxxxxxxxxxshipdatet;
	}

	public void setC3xxcxxrlxxxxxxxxxxxshipdatet(
			Date c3xxcxxrlxxxxxxxxxxxshipdatet) {
		this.c3xxcxxrlxxxxxxxxxxxshipdatet = c3xxcxxrlxxxxxxxxxxxshipdatet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shipdateta", length = 29)
	public Date getZ6xxcxxrlxxxxxxxxxxxshipdateta() {
		return this.z6xxcxxrlxxxxxxxxxxxshipdateta;
	}

	public void setZ6xxcxxrlxxxxxxxxxxxshipdateta(
			Date z6xxcxxrlxxxxxxxxxxxshipdateta) {
		this.z6xxcxxrlxxxxxxxxxxxshipdateta = z6xxcxxrlxxxxxxxxxxxshipdateta;
	}

	@Column(name = "tareno", length = 20)
	@Size(max = 20)
	public String getY4xxuxxrbvxxxxxxxxxxtareno() {
		return this.y4xxuxxrbvxxxxxxxxxxtareno;
	}

	public void setY4xxuxxrbvxxxxxxxxxxtareno(String y4xxuxxrbvxxxxxxxxxxtareno) {
		this.y4xxuxxrbvxxxxxxxxxxtareno = y4xxuxxrbvxxxxxxxxxxtareno;
	}

	@Column(name = "packno", length = 20)
	@Size(max = 20)
	public String getU5xxuxxrbvxxxxxxxxxxpackno() {
		return this.u5xxuxxrbvxxxxxxxxxxpackno;
	}

	public void setU5xxuxxrbvxxxxxxxxxxpackno(String u5xxuxxrbvxxxxxxxxxxpackno) {
		this.u5xxuxxrbvxxxxxxxxxxpackno = u5xxuxxrbvxxxxxxxxxxpackno;
	}

	@Column(name = "billtosameasshipto")
	public Boolean getD2xxugbrbvxxxxxxxxxxbilltosameasshipto() {
		return this.d2xxugbrbvxxxxxxxxxxbilltosameasshipto;
	}

	public void setD2xxugbrbvxxxxxxxxxxbilltosameasshipto(
			Boolean d2xxugbrbvxxxxxxxxxxbilltosameasshipto) {
		this.d2xxugbrbvxxxxxxxxxxbilltosameasshipto = d2xxugbrbvxxxxxxxxxxbilltosameasshipto;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY5xxuxznbvxxxxxxxxxxnotes() {
		return this.y5xxuxznbvxxxxxxxxxxnotes;
	}

	public void setY5xxuxznbvxxxxxxxxxxnotes(String y5xxuxznbvxxxxxxxxxxnotes) {
		this.y5xxuxznbvxxxxxxxxxxnotes = y5xxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "statusfl")
	public Integer getZ7xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z7xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ7xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z7xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z7xxzzfxhhxxxxxxxxxxstatusfl = z7xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ8xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z8xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ8xxcztxlxxxxxxxxxxxstatusfldt(
			Date z8xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z8xxcztxlxxxxxxxxxxxstatusfldt = z8xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "serialno", length = 25)
	@Size(max = 25)
	public String getZ9xxuxxrbvxxxxxxxxxxserialno() {
		return this.z9xxuxxrbvxxxxxxxxxxserialno;
	}

	public void setZ9xxuxxrbvxxxxxxxxxxserialno(
			String z9xxuxxrbvxxxxxxxxxxserialno) {
		this.z9xxuxxrbvxxxxxxxxxxserialno = z9xxuxxrbvxxxxxxxxxxserialno;
	}

	@Column(name = "printmstat")
	public Integer getZaxxzzprhvxxxxxxxxxxprintmstat() {
		return this.zaxxzzprhvxxxxxxxxxxprintmstat;
	}

	public void setZaxxzzprhvxxxxxxxxxxprintmstat(
			Integer zaxxzzprhvxxxxxxxxxxprintmstat) {
		this.zaxxzzprhvxxxxxxxxxxprintmstat = zaxxzzprhvxxxxxxxxxxprintmstat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prinmtfldt", length = 29)
	public Date getZbxxczqxlhxxxxxxxxxxprinmtfldt() {
		return this.zbxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	public void setZbxxczqxlhxxxxxxxxxxprinmtfldt(
			Date zbxxczqxlhxxxxxxxxxxprinmtfldt) {
		this.zbxxczqxlhxxxxxxxxxxprinmtfldt = zbxxczqxlhxxxxxxxxxxprinmtfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZcxxutoxlhxxxxxxxxxxowner() {
		return this.zcxxutoxlhxxxxxxxxxxowner;
	}

	public void setZcxxutoxlhxxxxxxxxxxowner(String zcxxutoxlhxxxxxxxxxxowner) {
		this.zcxxutoxlhxxxxxxxxxxowner = zcxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "barshipcod", length = 30)
	@Size(max = 30)
	public String getZdxxuxxrbvxxxxxxxxxxbarshipcod() {
		return this.zdxxuxxrbvxxxxxxxxxxbarshipcod;
	}

	public void setZdxxuxxrbvxxxxxxxxxxbarshipcod(
			String zdxxuxxrbvxxxxxxxxxxbarshipcod) {
		this.zdxxuxxrbvxxxxxxxxxxbarshipcod = zdxxuxxrbvxxxxxxxxxxbarshipcod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trexuq255xwwqqhxxxxxshipment")
	public Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> getXoxxuq295xwwqqhxxxxxshipmentdetailses() {
		return this.xoxxuq295xwwqqhxxxxxshipmentdetailses;
	}

	public void setXoxxuq295xwwqqhxxxxxshipmentdetailses(
			Set<Xoxxuq295xwwqqhxxxxxshipmentdetails> xoxxuq295xwwqqhxxxxxshipmentdetailses) {
		this.xoxxuq295xwwqqhxxxxxshipmentdetailses = xoxxuq295xwwqqhxxxxxshipmentdetailses;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
