package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Trxxuq9aaxwwqqhefxxxjobassignment generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "jobassignment")
public class Trxxuq9aaxwwqqhefxxxjobassignment implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation;
	private Fpxxuq9eexwwqqhefxxxmachine fpxxuq9eexwwqqhefxxxmachine;
	private Dxxxuq92bxwwqqhefxxxitemjob dxxxuq92bxwwqqhefxxxitemjob;
	private Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor;
	private Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer;
	private Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem;
	private String a0xxukxxbvxxxxxxxxxxjobassign;
	private String b1xxuxxrbvxxxxxxxxxxsequence;
	private Date b5gxdxsdbvxxxxxxxxxxsdatet;
	private Integer b5xxexdhbvxxxxxxxxxxdurationh;
	private Integer b6xx0xdmbvxxxxxxxxxxdurationm;
	private Integer b7xxexshbvxxxxxxxxxxstimeh;
	private Integer b8bx0xsmbvxxxxxxxxxxstimem;
	private Boolean b8extxsabvxxxxxxxxxxstimeampm;
	private Date b8xxceedbvxxxxxxxxxxedatet;
	private Boolean b9xxfxxxbv08xxxxxxxxpriority;
	private BigDecimal baxxzxxrlvxxxxxxxxxxpercntdone;
	private String bgxxuxxrbv18xxxxxxxxrepeatf;
	private BigDecimal b5xxztqrlxxxxxxxxxxxqtytotal;
	private BigDecimal b6xxzyqrlxxxxxxxxxxxqtyostndt;
	private Integer y6xxuxcobvxxxxxxxxxxpono;
	private Integer y9xxuxxrbvxxxxxxxxxxcpono;
	private Integer z3xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z2xxcztxlxxxxxxxxxxxstatusfldt;
	private String z4xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;
	private String yaxxuxznbvxxxxxxxxxxnotes;
	private Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = new HashSet<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails>(
			0);

	public Trxxuq9aaxwwqqhefxxxjobassignment() {
	}

	public Trxxuq9aaxwwqqhefxxxjobassignment(
			String a0xxukxxbvxxxxxxxxxxjobassign) {
		this.a0xxukxxbvxxxxxxxxxxjobassign = a0xxukxxbvxxxxxxxxxxjobassign;
	}
	public Trxxuq9aaxwwqqhefxxxjobassignment(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation,
			Fpxxuq9eexwwqqhefxxxmachine fpxxuq9eexwwqqhefxxxmachine,
			Dxxxuq92bxwwqqhefxxxitemjob dxxxuq92bxwwqqhefxxxitemjob,
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor,
			Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer,
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem,
			String a0xxukxxbvxxxxxxxxxxjobassign,
			String b1xxuxxrbvxxxxxxxxxxsequence,
			Date b5gxdxsdbvxxxxxxxxxxsdatet,
			Integer b5xxexdhbvxxxxxxxxxxdurationh,
			Integer b6xx0xdmbvxxxxxxxxxxdurationm,
			Integer b7xxexshbvxxxxxxxxxxstimeh,
			Integer b8bx0xsmbvxxxxxxxxxxstimem,
			Boolean b8extxsabvxxxxxxxxxxstimeampm,
			Date b8xxceedbvxxxxxxxxxxedatet,
			Boolean b9xxfxxxbv08xxxxxxxxpriority,
			BigDecimal baxxzxxrlvxxxxxxxxxxpercntdone,
			String bgxxuxxrbv18xxxxxxxxrepeatf,
			BigDecimal b5xxztqrlxxxxxxxxxxxqtytotal,
			BigDecimal b6xxzyqrlxxxxxxxxxxxqtyostndt,
			Integer y6xxuxcobvxxxxxxxxxxpono,
			Integer y9xxuxxrbvxxxxxxxxxxcpono,
			Integer z3xxzzfxhhxxxxxxxxxxstatusfl,
			Date z2xxcztxlxxxxxxxxxxxstatusfldt,
			String z4xxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2,
			String yaxxuxznbvxxxxxxxxxxnotes,
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
		this.fpxxuq9eexwwqqhefxxxmachine = fpxxuq9eexwwqqhefxxxmachine;
		this.dxxxuq92bxwwqqhefxxxitemjob = dxxxuq92bxwwqqhefxxxitemjob;
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
		this.jxxxuq201xwwqqhxxxxxcustomer = jxxxuq201xwwqqhxxxxxcustomer;
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
		this.a0xxukxxbvxxxxxxxxxxjobassign = a0xxukxxbvxxxxxxxxxxjobassign;
		this.b1xxuxxrbvxxxxxxxxxxsequence = b1xxuxxrbvxxxxxxxxxxsequence;
		this.b5gxdxsdbvxxxxxxxxxxsdatet = b5gxdxsdbvxxxxxxxxxxsdatet;
		this.b5xxexdhbvxxxxxxxxxxdurationh = b5xxexdhbvxxxxxxxxxxdurationh;
		this.b6xx0xdmbvxxxxxxxxxxdurationm = b6xx0xdmbvxxxxxxxxxxdurationm;
		this.b7xxexshbvxxxxxxxxxxstimeh = b7xxexshbvxxxxxxxxxxstimeh;
		this.b8bx0xsmbvxxxxxxxxxxstimem = b8bx0xsmbvxxxxxxxxxxstimem;
		this.b8extxsabvxxxxxxxxxxstimeampm = b8extxsabvxxxxxxxxxxstimeampm;
		this.b8xxceedbvxxxxxxxxxxedatet = b8xxceedbvxxxxxxxxxxedatet;
		this.b9xxfxxxbv08xxxxxxxxpriority = b9xxfxxxbv08xxxxxxxxpriority;
		this.baxxzxxrlvxxxxxxxxxxpercntdone = baxxzxxrlvxxxxxxxxxxpercntdone;
		this.bgxxuxxrbv18xxxxxxxxrepeatf = bgxxuxxrbv18xxxxxxxxrepeatf;
		this.b5xxztqrlxxxxxxxxxxxqtytotal = b5xxztqrlxxxxxxxxxxxqtytotal;
		this.b6xxzyqrlxxxxxxxxxxxqtyostndt = b6xxzyqrlxxxxxxxxxxxqtyostndt;
		this.y6xxuxcobvxxxxxxxxxxpono = y6xxuxcobvxxxxxxxxxxpono;
		this.y9xxuxxrbvxxxxxxxxxxcpono = y9xxuxxrbvxxxxxxxxxxcpono;
		this.z3xxzzfxhhxxxxxxxxxxstatusfl = z3xxzzfxhhxxxxxxxxxxstatusfl;
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
		this.z4xxutoxlhxxxxxxxxxxowner = z4xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
		this.yaxxuxznbvxxxxxxxxxxnotes = yaxxuxznbvxxxxxxxxxxnotes;
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location")
	public Fxxxcq144xwwqqhxxxxxlocation getFxxxcq144xwwqqhxxxxxlocation() {
		return this.fxxxcq144xwwqqhxxxxxlocation;
	}

	public void setFxxxcq144xwwqqhxxxxxlocation(
			Fxxxcq144xwwqqhxxxxxlocation fxxxcq144xwwqqhxxxxxlocation) {
		this.fxxxcq144xwwqqhxxxxxlocation = fxxxcq144xwwqqhxxxxxlocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "machine")
	public Fpxxuq9eexwwqqhefxxxmachine getFpxxuq9eexwwqqhefxxxmachine() {
		return this.fpxxuq9eexwwqqhefxxxmachine;
	}

	public void setFpxxuq9eexwwqqhefxxxmachine(
			Fpxxuq9eexwwqqhefxxxmachine fpxxuq9eexwwqqhefxxxmachine) {
		this.fpxxuq9eexwwqqhefxxxmachine = fpxxuq9eexwwqqhefxxxmachine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobno")
	public Dxxxuq92bxwwqqhefxxxitemjob getDxxxuq92bxwwqqhefxxxitemjob() {
		return this.dxxxuq92bxwwqqhefxxxitemjob;
	}

	public void setDxxxuq92bxwwqqhefxxxitemjob(
			Dxxxuq92bxwwqqhefxxxitemjob dxxxuq92bxwwqqhefxxxitemjob) {
		this.dxxxuq92bxwwqqhefxxxitemjob = dxxxuq92bxwwqqhefxxxitemjob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor")
	public Jxxxuq300xwwqqhxxxxxvendor getJxxxuq300xwwqqhxxxxxvendor() {
		return this.jxxxuq300xwwqqhxxxxxvendor;
	}

	public void setJxxxuq300xwwqqhxxxxxvendor(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor) {
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer")
	public Jxxxuq201xwwqqhxxxxxcustomer getJxxxuq201xwwqqhxxxxxcustomer() {
		return this.jxxxuq201xwwqqhxxxxxcustomer;
	}

	public void setJxxxuq201xwwqqhxxxxxcustomer(
			Jxxxuq201xwwqqhxxxxxcustomer jxxxuq201xwwqqhxxxxxcustomer) {
		this.jxxxuq201xwwqqhxxxxxcustomer = jxxxuq201xwwqqhxxxxxcustomer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matcode")
	public Fpxxfq1a5xwwqqhxxxxxitem getFpxxfq1a5xwwqqhxxxxxitem() {
		return this.fpxxfq1a5xwwqqhxxxxxitem;
	}

	public void setFpxxfq1a5xwwqqhxxxxxitem(
			Fpxxfq1a5xwwqqhxxxxxitem fpxxfq1a5xwwqqhxxxxxitem) {
		this.fpxxfq1a5xwwqqhxxxxxitem = fpxxfq1a5xwwqqhxxxxxitem;
	}

	@Column(name = "jobassign", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukxxbvxxxxxxxxxxjobassign() {
		return this.a0xxukxxbvxxxxxxxxxxjobassign;
	}

	public void setA0xxukxxbvxxxxxxxxxxjobassign(
			String a0xxukxxbvxxxxxxxxxxjobassign) {
		this.a0xxukxxbvxxxxxxxxxxjobassign = a0xxukxxbvxxxxxxxxxxjobassign;
	}

	@Column(name = "sequence", length = 12)
	@Size(max = 12)
	public String getB1xxuxxrbvxxxxxxxxxxsequence() {
		return this.b1xxuxxrbvxxxxxxxxxxsequence;
	}

	public void setB1xxuxxrbvxxxxxxxxxxsequence(
			String b1xxuxxrbvxxxxxxxxxxsequence) {
		this.b1xxuxxrbvxxxxxxxxxxsequence = b1xxuxxrbvxxxxxxxxxxsequence;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sdatet", length = 29)
	public Date getB5gxdxsdbvxxxxxxxxxxsdatet() {
		return this.b5gxdxsdbvxxxxxxxxxxsdatet;
	}

	public void setB5gxdxsdbvxxxxxxxxxxsdatet(Date b5gxdxsdbvxxxxxxxxxxsdatet) {
		this.b5gxdxsdbvxxxxxxxxxxsdatet = b5gxdxsdbvxxxxxxxxxxsdatet;
	}

	@Column(name = "durationh")
	public Integer getB5xxexdhbvxxxxxxxxxxdurationh() {
		return this.b5xxexdhbvxxxxxxxxxxdurationh;
	}

	public void setB5xxexdhbvxxxxxxxxxxdurationh(
			Integer b5xxexdhbvxxxxxxxxxxdurationh) {
		this.b5xxexdhbvxxxxxxxxxxdurationh = b5xxexdhbvxxxxxxxxxxdurationh;
	}

	@Column(name = "durationm")
	public Integer getB6xx0xdmbvxxxxxxxxxxdurationm() {
		return this.b6xx0xdmbvxxxxxxxxxxdurationm;
	}

	public void setB6xx0xdmbvxxxxxxxxxxdurationm(
			Integer b6xx0xdmbvxxxxxxxxxxdurationm) {
		this.b6xx0xdmbvxxxxxxxxxxdurationm = b6xx0xdmbvxxxxxxxxxxdurationm;
	}

	@Column(name = "stimeh")
	public Integer getB7xxexshbvxxxxxxxxxxstimeh() {
		return this.b7xxexshbvxxxxxxxxxxstimeh;
	}

	public void setB7xxexshbvxxxxxxxxxxstimeh(Integer b7xxexshbvxxxxxxxxxxstimeh) {
		this.b7xxexshbvxxxxxxxxxxstimeh = b7xxexshbvxxxxxxxxxxstimeh;
	}

	@Column(name = "stimem")
	public Integer getB8bx0xsmbvxxxxxxxxxxstimem() {
		return this.b8bx0xsmbvxxxxxxxxxxstimem;
	}

	public void setB8bx0xsmbvxxxxxxxxxxstimem(Integer b8bx0xsmbvxxxxxxxxxxstimem) {
		this.b8bx0xsmbvxxxxxxxxxxstimem = b8bx0xsmbvxxxxxxxxxxstimem;
	}

	@Column(name = "stimeampm")
	public Boolean getB8extxsabvxxxxxxxxxxstimeampm() {
		return this.b8extxsabvxxxxxxxxxxstimeampm;
	}

	public void setB8extxsabvxxxxxxxxxxstimeampm(
			Boolean b8extxsabvxxxxxxxxxxstimeampm) {
		this.b8extxsabvxxxxxxxxxxstimeampm = b8extxsabvxxxxxxxxxxstimeampm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edatet", length = 29)
	public Date getB8xxceedbvxxxxxxxxxxedatet() {
		return this.b8xxceedbvxxxxxxxxxxedatet;
	}

	public void setB8xxceedbvxxxxxxxxxxedatet(Date b8xxceedbvxxxxxxxxxxedatet) {
		this.b8xxceedbvxxxxxxxxxxedatet = b8xxceedbvxxxxxxxxxxedatet;
	}

	@Column(name = "priority")
	public Boolean getB9xxfxxxbv08xxxxxxxxpriority() {
		return this.b9xxfxxxbv08xxxxxxxxpriority;
	}

	public void setB9xxfxxxbv08xxxxxxxxpriority(
			Boolean b9xxfxxxbv08xxxxxxxxpriority) {
		this.b9xxfxxxbv08xxxxxxxxpriority = b9xxfxxxbv08xxxxxxxxpriority;
	}

	@Column(name = "percntdone", precision = 14)
	public BigDecimal getBaxxzxxrlvxxxxxxxxxxpercntdone() {
		return this.baxxzxxrlvxxxxxxxxxxpercntdone;
	}

	public void setBaxxzxxrlvxxxxxxxxxxpercntdone(
			BigDecimal baxxzxxrlvxxxxxxxxxxpercntdone) {
		this.baxxzxxrlvxxxxxxxxxxpercntdone = baxxzxxrlvxxxxxxxxxxpercntdone;
	}

	@Column(name = "repeatf", length = 20)
	@Size(max = 20)
	public String getBgxxuxxrbv18xxxxxxxxrepeatf() {
		return this.bgxxuxxrbv18xxxxxxxxrepeatf;
	}

	public void setBgxxuxxrbv18xxxxxxxxrepeatf(
			String bgxxuxxrbv18xxxxxxxxrepeatf) {
		this.bgxxuxxrbv18xxxxxxxxrepeatf = bgxxuxxrbv18xxxxxxxxrepeatf;
	}

	@Column(name = "qtytotal", precision = 14)
	public BigDecimal getB5xxztqrlxxxxxxxxxxxqtytotal() {
		return this.b5xxztqrlxxxxxxxxxxxqtytotal;
	}

	public void setB5xxztqrlxxxxxxxxxxxqtytotal(
			BigDecimal b5xxztqrlxxxxxxxxxxxqtytotal) {
		this.b5xxztqrlxxxxxxxxxxxqtytotal = b5xxztqrlxxxxxxxxxxxqtytotal;
	}

	@Column(name = "qtyostndt", precision = 14)
	public BigDecimal getB6xxzyqrlxxxxxxxxxxxqtyostndt() {
		return this.b6xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	public void setB6xxzyqrlxxxxxxxxxxxqtyostndt(
			BigDecimal b6xxzyqrlxxxxxxxxxxxqtyostndt) {
		this.b6xxzyqrlxxxxxxxxxxxqtyostndt = b6xxzyqrlxxxxxxxxxxxqtyostndt;
	}

	@Column(name = "pono")
	public Integer getY6xxuxcobvxxxxxxxxxxpono() {
		return this.y6xxuxcobvxxxxxxxxxxpono;
	}

	public void setY6xxuxcobvxxxxxxxxxxpono(Integer y6xxuxcobvxxxxxxxxxxpono) {
		this.y6xxuxcobvxxxxxxxxxxpono = y6xxuxcobvxxxxxxxxxxpono;
	}

	@Column(name = "cpono")
	public Integer getY9xxuxxrbvxxxxxxxxxxcpono() {
		return this.y9xxuxxrbvxxxxxxxxxxcpono;
	}

	public void setY9xxuxxrbvxxxxxxxxxxcpono(Integer y9xxuxxrbvxxxxxxxxxxcpono) {
		this.y9xxuxxrbvxxxxxxxxxxcpono = y9xxuxxrbvxxxxxxxxxxcpono;
	}

	@Column(name = "statusfl")
	public Integer getZ3xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z3xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ3xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z3xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z3xxzzfxhhxxxxxxxxxxstatusfl = z3xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ2xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ2xxcztxlxxxxxxxxxxxstatusfldt(
			Date z2xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ4xxutoxlhxxxxxxxxxxowner() {
		return this.z4xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ4xxutoxlhxxxxxxxxxxowner(String z4xxutoxlhxxxxxxxxxxowner) {
		this.z4xxutoxlhxxxxxxxxxxowner = z4xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getYaxxuxznbvxxxxxxxxxxnotes() {
		return this.yaxxuxznbvxxxxxxxxxxnotes;
	}

	public void setYaxxuxznbvxxxxxxxxxxnotes(String yaxxuxznbvxxxxxxxxxxnotes) {
		this.yaxxuxznbvxxxxxxxxxxnotes = yaxxuxznbvxxxxxxxxxxnotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trxxuq9aaxwwqqhefxxxjobassignment")
	public Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> getXoxxuq9bfxwwqqhexxxxjobassignmentdetailses() {
		return this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	public void setXoxxuq9bfxwwqqhexxxxjobassignmentdetailses(
			Set<Xoxxuq9bfxwwqqhexxxxjobassignmentdetails> xoxxuq9bfxwwqqhexxxxjobassignmentdetailses) {
		this.xoxxuq9bfxwwqqhexxxxjobassignmentdetailses = xoxxuq9bfxwwqqhexxxxjobassignmentdetailses;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
