package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Txxxuq366xwwqqhxxxxxvenartha generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "venartha")
public class Txxxuq366xwwqqhxxxxxvenartha implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor;
	private String a0xxukvabvxxxxxxxxxxchqnumber;
	private String b1xxuxxxbvxxxxxxxxxxreconciled;
	private Date b3xxcxxxbvxxxxxxxxxxdate;
	private Integer b4xxuxxxbvxxxxxxxxxxaddrescode;
	private BigDecimal b5xx0xxrbvxxxxxxxxxxchqamt;
	private String z1xxuxxxlvxxxxxxxxxxamtverbos;
	private String y1xxuxznbvxxxxxxxxxxnotes;
	private String c1xxuxxxbvxxxxxxxxxxadvisel1;
	private String c2xxuxxxbvxxxxxxxxxxadvisel2;
	private String c3xxuxxxbvxxxxxxxxxxadvisel3;
	private Integer z2xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z3xxcztxlxxxxxxxxxxxstatusfldt;
	private String z4xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Txxxuq366xwwqqhxxxxxvenartha() {
	}

	public Txxxuq366xwwqqhxxxxxvenartha(String a0xxukvabvxxxxxxxxxxchqnumber) {
		this.a0xxukvabvxxxxxxxxxxchqnumber = a0xxukvabvxxxxxxxxxxchqnumber;
	}
	public Txxxuq366xwwqqhxxxxxvenartha(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor,
			String a0xxukvabvxxxxxxxxxxchqnumber,
			String b1xxuxxxbvxxxxxxxxxxreconciled,
			Date b3xxcxxxbvxxxxxxxxxxdate,
			Integer b4xxuxxxbvxxxxxxxxxxaddrescode,
			BigDecimal b5xx0xxrbvxxxxxxxxxxchqamt,
			String z1xxuxxxlvxxxxxxxxxxamtverbos,
			String y1xxuxznbvxxxxxxxxxxnotes,
			String c1xxuxxxbvxxxxxxxxxxadvisel1,
			String c2xxuxxxbvxxxxxxxxxxadvisel2,
			String c3xxuxxxbvxxxxxxxxxxadvisel3,
			Integer z2xxzzfxhhxxxxxxxxxxstatusfl,
			Date z3xxcztxlxxxxxxxxxxxstatusfldt,
			String z4xxutoxlhxxxxxxxxxxowner, String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
		this.a0xxukvabvxxxxxxxxxxchqnumber = a0xxukvabvxxxxxxxxxxchqnumber;
		this.b1xxuxxxbvxxxxxxxxxxreconciled = b1xxuxxxbvxxxxxxxxxxreconciled;
		this.b3xxcxxxbvxxxxxxxxxxdate = b3xxcxxxbvxxxxxxxxxxdate;
		this.b4xxuxxxbvxxxxxxxxxxaddrescode = b4xxuxxxbvxxxxxxxxxxaddrescode;
		this.b5xx0xxrbvxxxxxxxxxxchqamt = b5xx0xxrbvxxxxxxxxxxchqamt;
		this.z1xxuxxxlvxxxxxxxxxxamtverbos = z1xxuxxxlvxxxxxxxxxxamtverbos;
		this.y1xxuxznbvxxxxxxxxxxnotes = y1xxuxznbvxxxxxxxxxxnotes;
		this.c1xxuxxxbvxxxxxxxxxxadvisel1 = c1xxuxxxbvxxxxxxxxxxadvisel1;
		this.c2xxuxxxbvxxxxxxxxxxadvisel2 = c2xxuxxxbvxxxxxxxxxxadvisel2;
		this.c3xxuxxxbvxxxxxxxxxxadvisel3 = c3xxuxxxbvxxxxxxxxxxadvisel3;
		this.z2xxzzfxhhxxxxxxxxxxstatusfl = z2xxzzfxhhxxxxxxxxxxstatusfl;
		this.z3xxcztxlxxxxxxxxxxxstatusfldt = z3xxcztxlxxxxxxxxxxxstatusfldt;
		this.z4xxutoxlhxxxxxxxxxxowner = z4xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendorc")
	public Jxxxuq300xwwqqhxxxxxvendor getJxxxuq300xwwqqhxxxxxvendor() {
		return this.jxxxuq300xwwqqhxxxxxvendor;
	}

	public void setJxxxuq300xwwqqhxxxxxvendor(
			Jxxxuq300xwwqqhxxxxxvendor jxxxuq300xwwqqhxxxxxvendor) {
		this.jxxxuq300xwwqqhxxxxxvendor = jxxxuq300xwwqqhxxxxxvendor;
	}

	@Column(name = "chqnumber", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getA0xxukvabvxxxxxxxxxxchqnumber() {
		return this.a0xxukvabvxxxxxxxxxxchqnumber;
	}

	public void setA0xxukvabvxxxxxxxxxxchqnumber(
			String a0xxukvabvxxxxxxxxxxchqnumber) {
		this.a0xxukvabvxxxxxxxxxxchqnumber = a0xxukvabvxxxxxxxxxxchqnumber;
	}

	@Column(name = "reconciled", length = 12)
	@Size(max = 12)
	public String getB1xxuxxxbvxxxxxxxxxxreconciled() {
		return this.b1xxuxxxbvxxxxxxxxxxreconciled;
	}

	public void setB1xxuxxxbvxxxxxxxxxxreconciled(
			String b1xxuxxxbvxxxxxxxxxxreconciled) {
		this.b1xxuxxxbvxxxxxxxxxxreconciled = b1xxuxxxbvxxxxxxxxxxreconciled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 29)
	public Date getB3xxcxxxbvxxxxxxxxxxdate() {
		return this.b3xxcxxxbvxxxxxxxxxxdate;
	}

	public void setB3xxcxxxbvxxxxxxxxxxdate(Date b3xxcxxxbvxxxxxxxxxxdate) {
		this.b3xxcxxxbvxxxxxxxxxxdate = b3xxcxxxbvxxxxxxxxxxdate;
	}

	@Column(name = "addrescode")
	public Integer getB4xxuxxxbvxxxxxxxxxxaddrescode() {
		return this.b4xxuxxxbvxxxxxxxxxxaddrescode;
	}

	public void setB4xxuxxxbvxxxxxxxxxxaddrescode(
			Integer b4xxuxxxbvxxxxxxxxxxaddrescode) {
		this.b4xxuxxxbvxxxxxxxxxxaddrescode = b4xxuxxxbvxxxxxxxxxxaddrescode;
	}

	@Column(name = "chqamt", precision = 14)
	public BigDecimal getB5xx0xxrbvxxxxxxxxxxchqamt() {
		return this.b5xx0xxrbvxxxxxxxxxxchqamt;
	}

	public void setB5xx0xxrbvxxxxxxxxxxchqamt(
			BigDecimal b5xx0xxrbvxxxxxxxxxxchqamt) {
		this.b5xx0xxrbvxxxxxxxxxxchqamt = b5xx0xxrbvxxxxxxxxxxchqamt;
	}

	@Column(name = "amtverbos", length = 120)
	@Size(max = 120)
	public String getZ1xxuxxxlvxxxxxxxxxxamtverbos() {
		return this.z1xxuxxxlvxxxxxxxxxxamtverbos;
	}

	public void setZ1xxuxxxlvxxxxxxxxxxamtverbos(
			String z1xxuxxxlvxxxxxxxxxxamtverbos) {
		this.z1xxuxxxlvxxxxxxxxxxamtverbos = z1xxuxxxlvxxxxxxxxxxamtverbos;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY1xxuxznbvxxxxxxxxxxnotes() {
		return this.y1xxuxznbvxxxxxxxxxxnotes;
	}

	public void setY1xxuxznbvxxxxxxxxxxnotes(String y1xxuxznbvxxxxxxxxxxnotes) {
		this.y1xxuxznbvxxxxxxxxxxnotes = y1xxuxznbvxxxxxxxxxxnotes;
	}

	@Column(name = "advisel1", length = 60)
	@Size(max = 60)
	public String getC1xxuxxxbvxxxxxxxxxxadvisel1() {
		return this.c1xxuxxxbvxxxxxxxxxxadvisel1;
	}

	public void setC1xxuxxxbvxxxxxxxxxxadvisel1(
			String c1xxuxxxbvxxxxxxxxxxadvisel1) {
		this.c1xxuxxxbvxxxxxxxxxxadvisel1 = c1xxuxxxbvxxxxxxxxxxadvisel1;
	}

	@Column(name = "advisel2", length = 60)
	@Size(max = 60)
	public String getC2xxuxxxbvxxxxxxxxxxadvisel2() {
		return this.c2xxuxxxbvxxxxxxxxxxadvisel2;
	}

	public void setC2xxuxxxbvxxxxxxxxxxadvisel2(
			String c2xxuxxxbvxxxxxxxxxxadvisel2) {
		this.c2xxuxxxbvxxxxxxxxxxadvisel2 = c2xxuxxxbvxxxxxxxxxxadvisel2;
	}

	@Column(name = "advisel3", length = 60)
	@Size(max = 60)
	public String getC3xxuxxxbvxxxxxxxxxxadvisel3() {
		return this.c3xxuxxxbvxxxxxxxxxxadvisel3;
	}

	public void setC3xxuxxxbvxxxxxxxxxxadvisel3(
			String c3xxuxxxbvxxxxxxxxxxadvisel3) {
		this.c3xxuxxxbvxxxxxxxxxxadvisel3 = c3xxuxxxbvxxxxxxxxxxadvisel3;
	}

	@Column(name = "statusfl")
	public Integer getZ2xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z2xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ2xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z2xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z2xxzzfxhhxxxxxxxxxxstatusfl = z2xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ3xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z3xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ3xxcztxlxxxxxxxxxxxstatusfldt(
			Date z3xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z3xxcztxlxxxxxxxxxxxstatusfldt = z3xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ4xxutoxlhxxxxxxxxxxowner() {
		return this.z4xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ4xxutoxlhxxxxxxxxxxowner(String z4xxutoxlhxxxxxxxxxxowner) {
		this.z4xxutoxlhxxxxxxxxxxowner = z4xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
