package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Xorxeh66exwwqqhxxxxxgentriesdetails generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "gentriesdetails")
public class Xorxeh66exwwqqhxxxxxgentriesdetails
		implements
			java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Yxxxch65exwwqqhxxxxxglentries yxxxch65exwwqqhxxxxxglentries;
	private Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount;
	private Integer b1xxzo11bvlxxxxxxxxxline;
	private Integer y1xxuxexbvxxxxxxxxxxdepcode;
	private Integer y2xxuxoxbvxxxxxxxxxxdivcode;
	private BigDecimal c4xxzxxxbvxxxxxxxxxxdebitamt;
	private BigDecimal c5xxzxxxbvxxxxxxxxxxcreditamt;
	private BigDecimal c5xxzxxxbvxxxxxxxxxxlinetotl;
	private String y8xxuznxbvxxxxxxxxxxnotes;
	private Integer z1xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z2xxcztxlxxxxxxxxxxxstatusfldt;
	private String z2xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Xorxeh66exwwqqhxxxxxgentriesdetails() {
	}

	public Xorxeh66exwwqqhxxxxxgentriesdetails(
			Yxxxch65exwwqqhxxxxxglentries yxxxch65exwwqqhxxxxxglentries) {
		this.yxxxch65exwwqqhxxxxxglentries = yxxxch65exwwqqhxxxxxglentries;
	}
	public Xorxeh66exwwqqhxxxxxgentriesdetails(
			Yxxxch65exwwqqhxxxxxglentries yxxxch65exwwqqhxxxxxglentries,
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount,
			Integer b1xxzo11bvlxxxxxxxxxline,
			Integer y1xxuxexbvxxxxxxxxxxdepcode,
			Integer y2xxuxoxbvxxxxxxxxxxdivcode,
			BigDecimal c4xxzxxxbvxxxxxxxxxxdebitamt,
			BigDecimal c5xxzxxxbvxxxxxxxxxxcreditamt,
			BigDecimal c5xxzxxxbvxxxxxxxxxxlinetotl,
			String y8xxuznxbvxxxxxxxxxxnotes,
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl,
			Date z2xxcztxlxxxxxxxxxxxstatusfldt,
			String z2xxutoxlhxxxxxxxxxxowner, String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.yxxxch65exwwqqhxxxxxglentries = yxxxch65exwwqqhxxxxxglentries;
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
		this.b1xxzo11bvlxxxxxxxxxline = b1xxzo11bvlxxxxxxxxxline;
		this.y1xxuxexbvxxxxxxxxxxdepcode = y1xxuxexbvxxxxxxxxxxdepcode;
		this.y2xxuxoxbvxxxxxxxxxxdivcode = y2xxuxoxbvxxxxxxxxxxdivcode;
		this.c4xxzxxxbvxxxxxxxxxxdebitamt = c4xxzxxxbvxxxxxxxxxxdebitamt;
		this.c5xxzxxxbvxxxxxxxxxxcreditamt = c5xxzxxxbvxxxxxxxxxxcreditamt;
		this.c5xxzxxxbvxxxxxxxxxxlinetotl = c5xxzxxxbvxxxxxxxxxxlinetotl;
		this.y8xxuznxbvxxxxxxxxxxnotes = y8xxuznxbvxxxxxxxxxxnotes;
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
		this.z2xxutoxlhxxxxxxxxxxowner = z2xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "glentrysidno", nullable = false)
	@NotNull
	public Yxxxch65exwwqqhxxxxxglentries getYxxxch65exwwqqhxxxxxglentries() {
		return this.yxxxch65exwwqqhxxxxxglentries;
	}

	public void setYxxxch65exwwqqhxxxxxglentries(
			Yxxxch65exwwqqhxxxxxglentries yxxxch65exwwqqhxxxxxglentries) {
		this.yxxxch65exwwqqhxxxxxglentries = yxxxch65exwwqqhxxxxxglentries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account")
	public Yxxxch601xwwqqhxxxxxaccount getYxxxch601xwwqqhxxxxxaccount() {
		return this.yxxxch601xwwqqhxxxxxaccount;
	}

	public void setYxxxch601xwwqqhxxxxxaccount(
			Yxxxch601xwwqqhxxxxxaccount yxxxch601xwwqqhxxxxxaccount) {
		this.yxxxch601xwwqqhxxxxxaccount = yxxxch601xwwqqhxxxxxaccount;
	}

	@Column(name = "line")
	public Integer getB1xxzo11bvlxxxxxxxxxline() {
		return this.b1xxzo11bvlxxxxxxxxxline;
	}

	public void setB1xxzo11bvlxxxxxxxxxline(Integer b1xxzo11bvlxxxxxxxxxline) {
		this.b1xxzo11bvlxxxxxxxxxline = b1xxzo11bvlxxxxxxxxxline;
	}

	@Column(name = "depcode")
	public Integer getY1xxuxexbvxxxxxxxxxxdepcode() {
		return this.y1xxuxexbvxxxxxxxxxxdepcode;
	}

	public void setY1xxuxexbvxxxxxxxxxxdepcode(
			Integer y1xxuxexbvxxxxxxxxxxdepcode) {
		this.y1xxuxexbvxxxxxxxxxxdepcode = y1xxuxexbvxxxxxxxxxxdepcode;
	}

	@Column(name = "divcode")
	public Integer getY2xxuxoxbvxxxxxxxxxxdivcode() {
		return this.y2xxuxoxbvxxxxxxxxxxdivcode;
	}

	public void setY2xxuxoxbvxxxxxxxxxxdivcode(
			Integer y2xxuxoxbvxxxxxxxxxxdivcode) {
		this.y2xxuxoxbvxxxxxxxxxxdivcode = y2xxuxoxbvxxxxxxxxxxdivcode;
	}

	@Column(name = "debitamt", precision = 14)
	public BigDecimal getC4xxzxxxbvxxxxxxxxxxdebitamt() {
		return this.c4xxzxxxbvxxxxxxxxxxdebitamt;
	}

	public void setC4xxzxxxbvxxxxxxxxxxdebitamt(
			BigDecimal c4xxzxxxbvxxxxxxxxxxdebitamt) {
		this.c4xxzxxxbvxxxxxxxxxxdebitamt = c4xxzxxxbvxxxxxxxxxxdebitamt;
	}

	@Column(name = "creditamt", precision = 14)
	public BigDecimal getC5xxzxxxbvxxxxxxxxxxcreditamt() {
		return this.c5xxzxxxbvxxxxxxxxxxcreditamt;
	}

	public void setC5xxzxxxbvxxxxxxxxxxcreditamt(
			BigDecimal c5xxzxxxbvxxxxxxxxxxcreditamt) {
		this.c5xxzxxxbvxxxxxxxxxxcreditamt = c5xxzxxxbvxxxxxxxxxxcreditamt;
	}

	@Column(name = "linetotl", precision = 14)
	public BigDecimal getC5xxzxxxbvxxxxxxxxxxlinetotl() {
		return this.c5xxzxxxbvxxxxxxxxxxlinetotl;
	}

	public void setC5xxzxxxbvxxxxxxxxxxlinetotl(
			BigDecimal c5xxzxxxbvxxxxxxxxxxlinetotl) {
		this.c5xxzxxxbvxxxxxxxxxxlinetotl = c5xxzxxxbvxxxxxxxxxxlinetotl;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY8xxuznxbvxxxxxxxxxxnotes() {
		return this.y8xxuznxbvxxxxxxxxxxnotes;
	}

	public void setY8xxuznxbvxxxxxxxxxxnotes(String y8xxuznxbvxxxxxxxxxxnotes) {
		this.y8xxuznxbvxxxxxxxxxxnotes = y8xxuznxbvxxxxxxxxxxnotes;
	}

	@Column(name = "statusfl")
	public Integer getZ1xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ1xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ2xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ2xxcztxlxxxxxxxxxxxstatusfldt(
			Date z2xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ2xxutoxlhxxxxxxxxxxowner() {
		return this.z2xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ2xxutoxlhxxxxxxxxxxowner(String z2xxutoxlhxxxxxxxxxxowner) {
		this.z2xxutoxlhxxxxxxxxxxowner = z2xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
