package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Xxxxeh742xwwqqhxxxxxwageearneraux generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "wageearneraux")
public class Xxxxeh742xwwqqhxxxxxwageearneraux implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private Xxxxiq711xwwqqhxxxxxwageearner xxxxiq711xwwqqhxxxxxwageearner;
	private Integer a1xxzo11bvlxxxxxxxxxline;
	private String b1xxutsxbvxxxxxxxxxxsin;
	private BigDecimal z1xxztwllvxxxxxxxxxxwcbytdl;
	private BigDecimal z2xxztwnlvxxxxxxxxxxwcbytdn;
	private BigDecimal z3xxztellvxxxxxxxxxxinsytdl;
	private BigDecimal z4xxztenlvxxxxxxxxxxinsytdn;
	private BigDecimal z5xxztvllvxxxxxxxxxxvacatonyl;
	private BigDecimal z6xxztvnlvxxxxxxxxxxvacatonyn;
	private BigDecimal z7xxztpllvxxxxxxxxxxpayytdl;
	private BigDecimal z8xxztfllvxxxxxxxxxxfpensiytl;
	private BigDecimal z9xxztsnlvxxxxxxxxxxppensiytl;
	private BigDecimal zaxxztxllvxxxxxxxxxxitaxytdl;
	private BigDecimal zbxxztyllvnxxxxxxxxxptaxytdl;
	private BigDecimal zcxxztpnlvxxxxxxxxxxpayytdn;
	private BigDecimal zdxxztfnlvxxxxxxxxxxfpensiytn;
	private BigDecimal zexxztsnlvxxxxxxxxxxppensiytn;
	private BigDecimal zfxxztxnlvxxxxxxxxxxitaxytdn;
	private BigDecimal zgxxztynlvxxxxxxxxxxpatxytdn;
	private BigDecimal zhxxzxxxlvxxxxxxxxxxgpayytdl;
	private BigDecimal zixxzxxxlvxxxxxxxxxxgpayytdn;
	private Integer zjxxzzfxhhxxxxxxxxxxstatusfl;
	private Date zkxxcztxlxxxxxxxxxxxstatusfldt;
	private String zlxxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Xxxxeh742xwwqqhxxxxxwageearneraux() {
	}

	public Xxxxeh742xwwqqhxxxxxwageearneraux(
			Xxxxiq711xwwqqhxxxxxwageearner xxxxiq711xwwqqhxxxxxwageearner) {
		this.xxxxiq711xwwqqhxxxxxwageearner = xxxxiq711xwwqqhxxxxxwageearner;
	}
	public Xxxxeh742xwwqqhxxxxxwageearneraux(
			Xxxxiq711xwwqqhxxxxxwageearner xxxxiq711xwwqqhxxxxxwageearner,
			Integer a1xxzo11bvlxxxxxxxxxline, String b1xxutsxbvxxxxxxxxxxsin,
			BigDecimal z1xxztwllvxxxxxxxxxxwcbytdl,
			BigDecimal z2xxztwnlvxxxxxxxxxxwcbytdn,
			BigDecimal z3xxztellvxxxxxxxxxxinsytdl,
			BigDecimal z4xxztenlvxxxxxxxxxxinsytdn,
			BigDecimal z5xxztvllvxxxxxxxxxxvacatonyl,
			BigDecimal z6xxztvnlvxxxxxxxxxxvacatonyn,
			BigDecimal z7xxztpllvxxxxxxxxxxpayytdl,
			BigDecimal z8xxztfllvxxxxxxxxxxfpensiytl,
			BigDecimal z9xxztsnlvxxxxxxxxxxppensiytl,
			BigDecimal zaxxztxllvxxxxxxxxxxitaxytdl,
			BigDecimal zbxxztyllvnxxxxxxxxxptaxytdl,
			BigDecimal zcxxztpnlvxxxxxxxxxxpayytdn,
			BigDecimal zdxxztfnlvxxxxxxxxxxfpensiytn,
			BigDecimal zexxztsnlvxxxxxxxxxxppensiytn,
			BigDecimal zfxxztxnlvxxxxxxxxxxitaxytdn,
			BigDecimal zgxxztynlvxxxxxxxxxxpatxytdn,
			BigDecimal zhxxzxxxlvxxxxxxxxxxgpayytdl,
			BigDecimal zixxzxxxlvxxxxxxxxxxgpayytdn,
			Integer zjxxzzfxhhxxxxxxxxxxstatusfl,
			Date zkxxcztxlxxxxxxxxxxxstatusfldt,
			String zlxxutoxlhxxxxxxxxxxowner, String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.xxxxiq711xwwqqhxxxxxwageearner = xxxxiq711xwwqqhxxxxxwageearner;
		this.a1xxzo11bvlxxxxxxxxxline = a1xxzo11bvlxxxxxxxxxline;
		this.b1xxutsxbvxxxxxxxxxxsin = b1xxutsxbvxxxxxxxxxxsin;
		this.z1xxztwllvxxxxxxxxxxwcbytdl = z1xxztwllvxxxxxxxxxxwcbytdl;
		this.z2xxztwnlvxxxxxxxxxxwcbytdn = z2xxztwnlvxxxxxxxxxxwcbytdn;
		this.z3xxztellvxxxxxxxxxxinsytdl = z3xxztellvxxxxxxxxxxinsytdl;
		this.z4xxztenlvxxxxxxxxxxinsytdn = z4xxztenlvxxxxxxxxxxinsytdn;
		this.z5xxztvllvxxxxxxxxxxvacatonyl = z5xxztvllvxxxxxxxxxxvacatonyl;
		this.z6xxztvnlvxxxxxxxxxxvacatonyn = z6xxztvnlvxxxxxxxxxxvacatonyn;
		this.z7xxztpllvxxxxxxxxxxpayytdl = z7xxztpllvxxxxxxxxxxpayytdl;
		this.z8xxztfllvxxxxxxxxxxfpensiytl = z8xxztfllvxxxxxxxxxxfpensiytl;
		this.z9xxztsnlvxxxxxxxxxxppensiytl = z9xxztsnlvxxxxxxxxxxppensiytl;
		this.zaxxztxllvxxxxxxxxxxitaxytdl = zaxxztxllvxxxxxxxxxxitaxytdl;
		this.zbxxztyllvnxxxxxxxxxptaxytdl = zbxxztyllvnxxxxxxxxxptaxytdl;
		this.zcxxztpnlvxxxxxxxxxxpayytdn = zcxxztpnlvxxxxxxxxxxpayytdn;
		this.zdxxztfnlvxxxxxxxxxxfpensiytn = zdxxztfnlvxxxxxxxxxxfpensiytn;
		this.zexxztsnlvxxxxxxxxxxppensiytn = zexxztsnlvxxxxxxxxxxppensiytn;
		this.zfxxztxnlvxxxxxxxxxxitaxytdn = zfxxztxnlvxxxxxxxxxxitaxytdn;
		this.zgxxztynlvxxxxxxxxxxpatxytdn = zgxxztynlvxxxxxxxxxxpatxytdn;
		this.zhxxzxxxlvxxxxxxxxxxgpayytdl = zhxxzxxxlvxxxxxxxxxxgpayytdl;
		this.zixxzxxxlvxxxxxxxxxxgpayytdn = zixxzxxxlvxxxxxxxxxxgpayytdn;
		this.zjxxzzfxhhxxxxxxxxxxstatusfl = zjxxzzfxhhxxxxxxxxxxstatusfl;
		this.zkxxcztxlxxxxxxxxxxxstatusfldt = zkxxcztxlxxxxxxxxxxxstatusfldt;
		this.zlxxutoxlhxxxxxxxxxxowner = zlxxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wageearnerid", nullable = false)
	@NotNull
	public Xxxxiq711xwwqqhxxxxxwageearner getXxxxiq711xwwqqhxxxxxwageearner() {
		return this.xxxxiq711xwwqqhxxxxxwageearner;
	}

	public void setXxxxiq711xwwqqhxxxxxwageearner(
			Xxxxiq711xwwqqhxxxxxwageearner xxxxiq711xwwqqhxxxxxwageearner) {
		this.xxxxiq711xwwqqhxxxxxwageearner = xxxxiq711xwwqqhxxxxxwageearner;
	}

	@Column(name = "line")
	public Integer getA1xxzo11bvlxxxxxxxxxline() {
		return this.a1xxzo11bvlxxxxxxxxxline;
	}

	public void setA1xxzo11bvlxxxxxxxxxline(Integer a1xxzo11bvlxxxxxxxxxline) {
		this.a1xxzo11bvlxxxxxxxxxline = a1xxzo11bvlxxxxxxxxxline;
	}

	@Column(name = "sin", length = 12)
	@Size(max = 12)
	public String getB1xxutsxbvxxxxxxxxxxsin() {
		return this.b1xxutsxbvxxxxxxxxxxsin;
	}

	public void setB1xxutsxbvxxxxxxxxxxsin(String b1xxutsxbvxxxxxxxxxxsin) {
		this.b1xxutsxbvxxxxxxxxxxsin = b1xxutsxbvxxxxxxxxxxsin;
	}

	@Column(name = "wcbytdl", precision = 14)
	public BigDecimal getZ1xxztwllvxxxxxxxxxxwcbytdl() {
		return this.z1xxztwllvxxxxxxxxxxwcbytdl;
	}

	public void setZ1xxztwllvxxxxxxxxxxwcbytdl(
			BigDecimal z1xxztwllvxxxxxxxxxxwcbytdl) {
		this.z1xxztwllvxxxxxxxxxxwcbytdl = z1xxztwllvxxxxxxxxxxwcbytdl;
	}

	@Column(name = "wcbytdn", precision = 14)
	public BigDecimal getZ2xxztwnlvxxxxxxxxxxwcbytdn() {
		return this.z2xxztwnlvxxxxxxxxxxwcbytdn;
	}

	public void setZ2xxztwnlvxxxxxxxxxxwcbytdn(
			BigDecimal z2xxztwnlvxxxxxxxxxxwcbytdn) {
		this.z2xxztwnlvxxxxxxxxxxwcbytdn = z2xxztwnlvxxxxxxxxxxwcbytdn;
	}

	@Column(name = "insytdl", precision = 14)
	public BigDecimal getZ3xxztellvxxxxxxxxxxinsytdl() {
		return this.z3xxztellvxxxxxxxxxxinsytdl;
	}

	public void setZ3xxztellvxxxxxxxxxxinsytdl(
			BigDecimal z3xxztellvxxxxxxxxxxinsytdl) {
		this.z3xxztellvxxxxxxxxxxinsytdl = z3xxztellvxxxxxxxxxxinsytdl;
	}

	@Column(name = "insytdn", precision = 14)
	public BigDecimal getZ4xxztenlvxxxxxxxxxxinsytdn() {
		return this.z4xxztenlvxxxxxxxxxxinsytdn;
	}

	public void setZ4xxztenlvxxxxxxxxxxinsytdn(
			BigDecimal z4xxztenlvxxxxxxxxxxinsytdn) {
		this.z4xxztenlvxxxxxxxxxxinsytdn = z4xxztenlvxxxxxxxxxxinsytdn;
	}

	@Column(name = "vacatonyl", precision = 14)
	public BigDecimal getZ5xxztvllvxxxxxxxxxxvacatonyl() {
		return this.z5xxztvllvxxxxxxxxxxvacatonyl;
	}

	public void setZ5xxztvllvxxxxxxxxxxvacatonyl(
			BigDecimal z5xxztvllvxxxxxxxxxxvacatonyl) {
		this.z5xxztvllvxxxxxxxxxxvacatonyl = z5xxztvllvxxxxxxxxxxvacatonyl;
	}

	@Column(name = "vacatonyn", precision = 14)
	public BigDecimal getZ6xxztvnlvxxxxxxxxxxvacatonyn() {
		return this.z6xxztvnlvxxxxxxxxxxvacatonyn;
	}

	public void setZ6xxztvnlvxxxxxxxxxxvacatonyn(
			BigDecimal z6xxztvnlvxxxxxxxxxxvacatonyn) {
		this.z6xxztvnlvxxxxxxxxxxvacatonyn = z6xxztvnlvxxxxxxxxxxvacatonyn;
	}

	@Column(name = "payytdl", precision = 14)
	public BigDecimal getZ7xxztpllvxxxxxxxxxxpayytdl() {
		return this.z7xxztpllvxxxxxxxxxxpayytdl;
	}

	public void setZ7xxztpllvxxxxxxxxxxpayytdl(
			BigDecimal z7xxztpllvxxxxxxxxxxpayytdl) {
		this.z7xxztpllvxxxxxxxxxxpayytdl = z7xxztpllvxxxxxxxxxxpayytdl;
	}

	@Column(name = "fpensiytl", precision = 14)
	public BigDecimal getZ8xxztfllvxxxxxxxxxxfpensiytl() {
		return this.z8xxztfllvxxxxxxxxxxfpensiytl;
	}

	public void setZ8xxztfllvxxxxxxxxxxfpensiytl(
			BigDecimal z8xxztfllvxxxxxxxxxxfpensiytl) {
		this.z8xxztfllvxxxxxxxxxxfpensiytl = z8xxztfllvxxxxxxxxxxfpensiytl;
	}

	@Column(name = "ppensiytl", precision = 14)
	public BigDecimal getZ9xxztsnlvxxxxxxxxxxppensiytl() {
		return this.z9xxztsnlvxxxxxxxxxxppensiytl;
	}

	public void setZ9xxztsnlvxxxxxxxxxxppensiytl(
			BigDecimal z9xxztsnlvxxxxxxxxxxppensiytl) {
		this.z9xxztsnlvxxxxxxxxxxppensiytl = z9xxztsnlvxxxxxxxxxxppensiytl;
	}

	@Column(name = "itaxytdl", precision = 14)
	public BigDecimal getZaxxztxllvxxxxxxxxxxitaxytdl() {
		return this.zaxxztxllvxxxxxxxxxxitaxytdl;
	}

	public void setZaxxztxllvxxxxxxxxxxitaxytdl(
			BigDecimal zaxxztxllvxxxxxxxxxxitaxytdl) {
		this.zaxxztxllvxxxxxxxxxxitaxytdl = zaxxztxllvxxxxxxxxxxitaxytdl;
	}

	@Column(name = "ptaxytdl", precision = 14)
	public BigDecimal getZbxxztyllvnxxxxxxxxxptaxytdl() {
		return this.zbxxztyllvnxxxxxxxxxptaxytdl;
	}

	public void setZbxxztyllvnxxxxxxxxxptaxytdl(
			BigDecimal zbxxztyllvnxxxxxxxxxptaxytdl) {
		this.zbxxztyllvnxxxxxxxxxptaxytdl = zbxxztyllvnxxxxxxxxxptaxytdl;
	}

	@Column(name = "payytdn", precision = 14)
	public BigDecimal getZcxxztpnlvxxxxxxxxxxpayytdn() {
		return this.zcxxztpnlvxxxxxxxxxxpayytdn;
	}

	public void setZcxxztpnlvxxxxxxxxxxpayytdn(
			BigDecimal zcxxztpnlvxxxxxxxxxxpayytdn) {
		this.zcxxztpnlvxxxxxxxxxxpayytdn = zcxxztpnlvxxxxxxxxxxpayytdn;
	}

	@Column(name = "fpensiytn", precision = 14)
	public BigDecimal getZdxxztfnlvxxxxxxxxxxfpensiytn() {
		return this.zdxxztfnlvxxxxxxxxxxfpensiytn;
	}

	public void setZdxxztfnlvxxxxxxxxxxfpensiytn(
			BigDecimal zdxxztfnlvxxxxxxxxxxfpensiytn) {
		this.zdxxztfnlvxxxxxxxxxxfpensiytn = zdxxztfnlvxxxxxxxxxxfpensiytn;
	}

	@Column(name = "ppensiytn", precision = 14)
	public BigDecimal getZexxztsnlvxxxxxxxxxxppensiytn() {
		return this.zexxztsnlvxxxxxxxxxxppensiytn;
	}

	public void setZexxztsnlvxxxxxxxxxxppensiytn(
			BigDecimal zexxztsnlvxxxxxxxxxxppensiytn) {
		this.zexxztsnlvxxxxxxxxxxppensiytn = zexxztsnlvxxxxxxxxxxppensiytn;
	}

	@Column(name = "itaxytdn", precision = 14)
	public BigDecimal getZfxxztxnlvxxxxxxxxxxitaxytdn() {
		return this.zfxxztxnlvxxxxxxxxxxitaxytdn;
	}

	public void setZfxxztxnlvxxxxxxxxxxitaxytdn(
			BigDecimal zfxxztxnlvxxxxxxxxxxitaxytdn) {
		this.zfxxztxnlvxxxxxxxxxxitaxytdn = zfxxztxnlvxxxxxxxxxxitaxytdn;
	}

	@Column(name = "patxytdn", precision = 14)
	public BigDecimal getZgxxztynlvxxxxxxxxxxpatxytdn() {
		return this.zgxxztynlvxxxxxxxxxxpatxytdn;
	}

	public void setZgxxztynlvxxxxxxxxxxpatxytdn(
			BigDecimal zgxxztynlvxxxxxxxxxxpatxytdn) {
		this.zgxxztynlvxxxxxxxxxxpatxytdn = zgxxztynlvxxxxxxxxxxpatxytdn;
	}

	@Column(name = "gpayytdl", precision = 14)
	public BigDecimal getZhxxzxxxlvxxxxxxxxxxgpayytdl() {
		return this.zhxxzxxxlvxxxxxxxxxxgpayytdl;
	}

	public void setZhxxzxxxlvxxxxxxxxxxgpayytdl(
			BigDecimal zhxxzxxxlvxxxxxxxxxxgpayytdl) {
		this.zhxxzxxxlvxxxxxxxxxxgpayytdl = zhxxzxxxlvxxxxxxxxxxgpayytdl;
	}

	@Column(name = "gpayytdn", precision = 14)
	public BigDecimal getZixxzxxxlvxxxxxxxxxxgpayytdn() {
		return this.zixxzxxxlvxxxxxxxxxxgpayytdn;
	}

	public void setZixxzxxxlvxxxxxxxxxxgpayytdn(
			BigDecimal zixxzxxxlvxxxxxxxxxxgpayytdn) {
		this.zixxzxxxlvxxxxxxxxxxgpayytdn = zixxzxxxlvxxxxxxxxxxgpayytdn;
	}

	@Column(name = "statusfl")
	public Integer getZjxxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zjxxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZjxxzzfxhhxxxxxxxxxxstatusfl(
			Integer zjxxzzfxhhxxxxxxxxxxstatusfl) {
		this.zjxxzzfxhhxxxxxxxxxxstatusfl = zjxxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZkxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zkxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZkxxcztxlxxxxxxxxxxxstatusfldt(
			Date zkxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zkxxcztxlxxxxxxxxxxxstatusfldt = zkxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZlxxutoxlhxxxxxxxxxxowner() {
		return this.zlxxutoxlhxxxxxxxxxxowner;
	}

	public void setZlxxutoxlhxxxxxxxxxxowner(String zlxxutoxlhxxxxxxxxxxowner) {
		this.zlxxutoxlhxxxxxxxxxxowner = zlxxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	// The following is extra code specified in the hbm.xml files

	private Boolean flaggedAsEditable = false;
	private Boolean flaggedAsDeleteable = false;
	private Boolean flaggedAsNew = false;
	@Transient
	public boolean getFlaggedAsEditable() {
		return flaggedAsEditable;
	}
	public void setFlaggedAsEditable(Boolean value) {
		flaggedAsEditable = value;
	}
	@Transient
	public boolean getFlaggedAsDeleteable() {
		return flaggedAsDeleteable;
	}
	public void setFlaggedAsDeleteable(Boolean value) {
		flaggedAsDeleteable = value;
	}
	@Transient
	public boolean getFlaggedAsNew() {
		return flaggedAsNew;
	}
	public void setFlaggedAsNew(Boolean value) {
		flaggedAsNew = value;
	}

	// end of extra code specified in the hbm.xml files

}
