package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Yrxxch5b1xhhxxhxxxxximportcsv generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "importcsv", uniqueConstraints = @UniqueConstraint(columnNames = {
		"tablenm", "row", "owner2"}))
public class Yrxxch5b1xhhxxhxxxxximportcsv implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private String a1xxuxhrbvoxxxxxxxxxtablenm;
	private String a2xxukcxbvxxxxxxxxxxrow;
	private String b1xxuo01bvxxxxxxxxxxcolumn01;
	private String b4xxuo02bvxxxxxxxxxxcolumn02;
	private String b7xxuo03bvxxxxxxxxxxcolumn03;
	private String c1xxuo04bvxxxxxxxxxxcolumn04;
	private String c4xxuo05bvxxxxxxxxxxcolumn05;
	private String c7xxuo06bvxxxxxxxxxxcolumn06;
	private String d1xxuo07bvxxxxxxxxxxcolumn07;
	private String d4xxuo08bvxxxxxxxxxxcolumn08;
	private String d7xxuo09bvxxxxxxxxxxcolumn09;
	private String e1xxuo10bvxxxxxxxxxxcolumn10;
	private String e4xxuo11bvxxxxxxxxxxcolumn11;
	private String e7xxuo12bvxxxxxxxxxxcolumn12;
	private String f1xxuo13bvxxxxxxxxxxcolumn13;
	private String f4xxuo14bvxxxxxxxxxxcolumn14;
	private String f7xxuo15bvxxxxxxxxxxcolumn15;
	private String g1xxuo16bvxxxxxxxxxxcolumn16;
	private String g4xxuo17bvxxxxxxxxxxcolumn17;
	private String g7xxuo18bvxxxxxxxxxxcolumn18;
	private String h1xxuo19bvxxxxxxxxxxcolumn19;
	private String h4xxuo20bvxxxxxxxxxxcolumn20;
	private String h7xxuo21bvxxxxxxxxxxcolumn21;
	private String i1xxuo22bvxxxxxxxxxxcolumn22;
	private String i4xxuo23bvxxxxxxxxxxcolumn23;
	private String i7xxuo24bvxxxxxxxxxxcolumn24;
	private String j1xxuo25bvxxxxxxxxxxcolumn25;
	private String j4xxuo26bvxxxxxxxxxxcolumn26;
	private String j7xxuo27bvxxxxxxxxxxcolumn27;
	private String k1xxuo28bvxxxxxxxxxxcolumn28;
	private String k4xxuo29bvxxxxxxxxxxcolumn29;
	private String k7xxuo30bvxxxxxxxxxxcolumn30;
	private String l1xxuo31bvxxxxxxxxxxcolumn31;
	private String l4xxuo32bvxxxxxxxxxxcolumn32;
	private String l7xxuo33bvxxxxxxxxxxcolumn33;
	private String m1xxuo34bvxxxxxxxxxxcolumn34;
	private String m4xxuo35bvxxxxxxxxxxcolumn35;
	private String m7xxuo36bvxxxxxxxxxxcolumn36;
	private String n1xxuo37bvxxxxxxxxxxcolumn37;
	private String n4xxuo38bvxxxxxxxxxxcolumn38;
	private String n7xxuo39bvxxxxxxxxxxcolumn39;
	private String o1xxuo40bvxxxxxxxxxxcolumn40;
	private String o4xxuo41bvxxxxxxxxxxcolumn41;
	private String o7xxuo42bvxxxxxxxxxxcolumn42;
	private String p1xxuo43bvxxxxxxxxxxcolumn43;
	private String p4xxuo44bvxxxxxxxxxxcolumn44;
	private String p7xxuo45bvxxxxxxxxxxcolumn45;
	private String q1xxuo46bvxxxxxxxxxxcolumn46;
	private String q4xxuo47bvxxxxxxxxxxcolumn47;
	private String q7xxuo48bvxxxxxxxxxxcolumn48;
	private String r1xxuo49bvxxxxxxxxxxcolumn49;
	private String r4xxuo50bvxxxxxxxxxxcolumn50;
	private String r7xxuo51bvxxxxxxxxxxcolumn51;
	private String s1xxuo52bvxxxxxxxxxxcolumn52;
	private String s4xxuo53bvxxxxxxxxxxcolumn53;
	private String s7xxuo54bvxxxxxxxxxxcolumn54;
	private String t1xxuo55bvxxxxxxxxxxcolumn55;
	private String t4xxuo56bvxxxxxxxxxxcolumn56;
	private String t7xxuo57bvxxxxxxxxxxcolumn57;
	private String u1xxuo58bvxxxxxxxxxxcolumn58;
	private String u4xxuo59bvxxxxxxxxxxcolumn59;
	private String u7xxuo60bvxxxxxxxxxxcolumn60;
	private String v1xxuo61bvxxxxxxxxxxcolumn61;
	private String v4xxuo62bvxxxxxxxxxxcolumn62;
	private String v7xxuo63bvxxxxxxxxxxcolumn63;
	private String w1xxuo64bvxxxxxxxxxxcolumn64;
	private String w4xxuo65bvxxxxxxxxxxcolumn65;
	private Integer z1xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z2xxcztxlxxxxxxxxxxxstatusfldt;
	private String y9xxuznxbvxxxxxxxxxxnotes;
	private String z3xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Yrxxch5b1xhhxxhxxxxximportcsv() {
	}

	public Yrxxch5b1xhhxxhxxxxximportcsv(String a2xxukcxbvxxxxxxxxxxrow) {
		this.a2xxukcxbvxxxxxxxxxxrow = a2xxukcxbvxxxxxxxxxxrow;
	}
	public Yrxxch5b1xhhxxhxxxxximportcsv(String a1xxuxhrbvoxxxxxxxxxtablenm,
			String a2xxukcxbvxxxxxxxxxxrow,
			String b1xxuo01bvxxxxxxxxxxcolumn01,
			String b4xxuo02bvxxxxxxxxxxcolumn02,
			String b7xxuo03bvxxxxxxxxxxcolumn03,
			String c1xxuo04bvxxxxxxxxxxcolumn04,
			String c4xxuo05bvxxxxxxxxxxcolumn05,
			String c7xxuo06bvxxxxxxxxxxcolumn06,
			String d1xxuo07bvxxxxxxxxxxcolumn07,
			String d4xxuo08bvxxxxxxxxxxcolumn08,
			String d7xxuo09bvxxxxxxxxxxcolumn09,
			String e1xxuo10bvxxxxxxxxxxcolumn10,
			String e4xxuo11bvxxxxxxxxxxcolumn11,
			String e7xxuo12bvxxxxxxxxxxcolumn12,
			String f1xxuo13bvxxxxxxxxxxcolumn13,
			String f4xxuo14bvxxxxxxxxxxcolumn14,
			String f7xxuo15bvxxxxxxxxxxcolumn15,
			String g1xxuo16bvxxxxxxxxxxcolumn16,
			String g4xxuo17bvxxxxxxxxxxcolumn17,
			String g7xxuo18bvxxxxxxxxxxcolumn18,
			String h1xxuo19bvxxxxxxxxxxcolumn19,
			String h4xxuo20bvxxxxxxxxxxcolumn20,
			String h7xxuo21bvxxxxxxxxxxcolumn21,
			String i1xxuo22bvxxxxxxxxxxcolumn22,
			String i4xxuo23bvxxxxxxxxxxcolumn23,
			String i7xxuo24bvxxxxxxxxxxcolumn24,
			String j1xxuo25bvxxxxxxxxxxcolumn25,
			String j4xxuo26bvxxxxxxxxxxcolumn26,
			String j7xxuo27bvxxxxxxxxxxcolumn27,
			String k1xxuo28bvxxxxxxxxxxcolumn28,
			String k4xxuo29bvxxxxxxxxxxcolumn29,
			String k7xxuo30bvxxxxxxxxxxcolumn30,
			String l1xxuo31bvxxxxxxxxxxcolumn31,
			String l4xxuo32bvxxxxxxxxxxcolumn32,
			String l7xxuo33bvxxxxxxxxxxcolumn33,
			String m1xxuo34bvxxxxxxxxxxcolumn34,
			String m4xxuo35bvxxxxxxxxxxcolumn35,
			String m7xxuo36bvxxxxxxxxxxcolumn36,
			String n1xxuo37bvxxxxxxxxxxcolumn37,
			String n4xxuo38bvxxxxxxxxxxcolumn38,
			String n7xxuo39bvxxxxxxxxxxcolumn39,
			String o1xxuo40bvxxxxxxxxxxcolumn40,
			String o4xxuo41bvxxxxxxxxxxcolumn41,
			String o7xxuo42bvxxxxxxxxxxcolumn42,
			String p1xxuo43bvxxxxxxxxxxcolumn43,
			String p4xxuo44bvxxxxxxxxxxcolumn44,
			String p7xxuo45bvxxxxxxxxxxcolumn45,
			String q1xxuo46bvxxxxxxxxxxcolumn46,
			String q4xxuo47bvxxxxxxxxxxcolumn47,
			String q7xxuo48bvxxxxxxxxxxcolumn48,
			String r1xxuo49bvxxxxxxxxxxcolumn49,
			String r4xxuo50bvxxxxxxxxxxcolumn50,
			String r7xxuo51bvxxxxxxxxxxcolumn51,
			String s1xxuo52bvxxxxxxxxxxcolumn52,
			String s4xxuo53bvxxxxxxxxxxcolumn53,
			String s7xxuo54bvxxxxxxxxxxcolumn54,
			String t1xxuo55bvxxxxxxxxxxcolumn55,
			String t4xxuo56bvxxxxxxxxxxcolumn56,
			String t7xxuo57bvxxxxxxxxxxcolumn57,
			String u1xxuo58bvxxxxxxxxxxcolumn58,
			String u4xxuo59bvxxxxxxxxxxcolumn59,
			String u7xxuo60bvxxxxxxxxxxcolumn60,
			String v1xxuo61bvxxxxxxxxxxcolumn61,
			String v4xxuo62bvxxxxxxxxxxcolumn62,
			String v7xxuo63bvxxxxxxxxxxcolumn63,
			String w1xxuo64bvxxxxxxxxxxcolumn64,
			String w4xxuo65bvxxxxxxxxxxcolumn65,
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl,
			Date z2xxcztxlxxxxxxxxxxxstatusfldt,
			String y9xxuznxbvxxxxxxxxxxnotes, String z3xxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.a1xxuxhrbvoxxxxxxxxxtablenm = a1xxuxhrbvoxxxxxxxxxtablenm;
		this.a2xxukcxbvxxxxxxxxxxrow = a2xxukcxbvxxxxxxxxxxrow;
		this.b1xxuo01bvxxxxxxxxxxcolumn01 = b1xxuo01bvxxxxxxxxxxcolumn01;
		this.b4xxuo02bvxxxxxxxxxxcolumn02 = b4xxuo02bvxxxxxxxxxxcolumn02;
		this.b7xxuo03bvxxxxxxxxxxcolumn03 = b7xxuo03bvxxxxxxxxxxcolumn03;
		this.c1xxuo04bvxxxxxxxxxxcolumn04 = c1xxuo04bvxxxxxxxxxxcolumn04;
		this.c4xxuo05bvxxxxxxxxxxcolumn05 = c4xxuo05bvxxxxxxxxxxcolumn05;
		this.c7xxuo06bvxxxxxxxxxxcolumn06 = c7xxuo06bvxxxxxxxxxxcolumn06;
		this.d1xxuo07bvxxxxxxxxxxcolumn07 = d1xxuo07bvxxxxxxxxxxcolumn07;
		this.d4xxuo08bvxxxxxxxxxxcolumn08 = d4xxuo08bvxxxxxxxxxxcolumn08;
		this.d7xxuo09bvxxxxxxxxxxcolumn09 = d7xxuo09bvxxxxxxxxxxcolumn09;
		this.e1xxuo10bvxxxxxxxxxxcolumn10 = e1xxuo10bvxxxxxxxxxxcolumn10;
		this.e4xxuo11bvxxxxxxxxxxcolumn11 = e4xxuo11bvxxxxxxxxxxcolumn11;
		this.e7xxuo12bvxxxxxxxxxxcolumn12 = e7xxuo12bvxxxxxxxxxxcolumn12;
		this.f1xxuo13bvxxxxxxxxxxcolumn13 = f1xxuo13bvxxxxxxxxxxcolumn13;
		this.f4xxuo14bvxxxxxxxxxxcolumn14 = f4xxuo14bvxxxxxxxxxxcolumn14;
		this.f7xxuo15bvxxxxxxxxxxcolumn15 = f7xxuo15bvxxxxxxxxxxcolumn15;
		this.g1xxuo16bvxxxxxxxxxxcolumn16 = g1xxuo16bvxxxxxxxxxxcolumn16;
		this.g4xxuo17bvxxxxxxxxxxcolumn17 = g4xxuo17bvxxxxxxxxxxcolumn17;
		this.g7xxuo18bvxxxxxxxxxxcolumn18 = g7xxuo18bvxxxxxxxxxxcolumn18;
		this.h1xxuo19bvxxxxxxxxxxcolumn19 = h1xxuo19bvxxxxxxxxxxcolumn19;
		this.h4xxuo20bvxxxxxxxxxxcolumn20 = h4xxuo20bvxxxxxxxxxxcolumn20;
		this.h7xxuo21bvxxxxxxxxxxcolumn21 = h7xxuo21bvxxxxxxxxxxcolumn21;
		this.i1xxuo22bvxxxxxxxxxxcolumn22 = i1xxuo22bvxxxxxxxxxxcolumn22;
		this.i4xxuo23bvxxxxxxxxxxcolumn23 = i4xxuo23bvxxxxxxxxxxcolumn23;
		this.i7xxuo24bvxxxxxxxxxxcolumn24 = i7xxuo24bvxxxxxxxxxxcolumn24;
		this.j1xxuo25bvxxxxxxxxxxcolumn25 = j1xxuo25bvxxxxxxxxxxcolumn25;
		this.j4xxuo26bvxxxxxxxxxxcolumn26 = j4xxuo26bvxxxxxxxxxxcolumn26;
		this.j7xxuo27bvxxxxxxxxxxcolumn27 = j7xxuo27bvxxxxxxxxxxcolumn27;
		this.k1xxuo28bvxxxxxxxxxxcolumn28 = k1xxuo28bvxxxxxxxxxxcolumn28;
		this.k4xxuo29bvxxxxxxxxxxcolumn29 = k4xxuo29bvxxxxxxxxxxcolumn29;
		this.k7xxuo30bvxxxxxxxxxxcolumn30 = k7xxuo30bvxxxxxxxxxxcolumn30;
		this.l1xxuo31bvxxxxxxxxxxcolumn31 = l1xxuo31bvxxxxxxxxxxcolumn31;
		this.l4xxuo32bvxxxxxxxxxxcolumn32 = l4xxuo32bvxxxxxxxxxxcolumn32;
		this.l7xxuo33bvxxxxxxxxxxcolumn33 = l7xxuo33bvxxxxxxxxxxcolumn33;
		this.m1xxuo34bvxxxxxxxxxxcolumn34 = m1xxuo34bvxxxxxxxxxxcolumn34;
		this.m4xxuo35bvxxxxxxxxxxcolumn35 = m4xxuo35bvxxxxxxxxxxcolumn35;
		this.m7xxuo36bvxxxxxxxxxxcolumn36 = m7xxuo36bvxxxxxxxxxxcolumn36;
		this.n1xxuo37bvxxxxxxxxxxcolumn37 = n1xxuo37bvxxxxxxxxxxcolumn37;
		this.n4xxuo38bvxxxxxxxxxxcolumn38 = n4xxuo38bvxxxxxxxxxxcolumn38;
		this.n7xxuo39bvxxxxxxxxxxcolumn39 = n7xxuo39bvxxxxxxxxxxcolumn39;
		this.o1xxuo40bvxxxxxxxxxxcolumn40 = o1xxuo40bvxxxxxxxxxxcolumn40;
		this.o4xxuo41bvxxxxxxxxxxcolumn41 = o4xxuo41bvxxxxxxxxxxcolumn41;
		this.o7xxuo42bvxxxxxxxxxxcolumn42 = o7xxuo42bvxxxxxxxxxxcolumn42;
		this.p1xxuo43bvxxxxxxxxxxcolumn43 = p1xxuo43bvxxxxxxxxxxcolumn43;
		this.p4xxuo44bvxxxxxxxxxxcolumn44 = p4xxuo44bvxxxxxxxxxxcolumn44;
		this.p7xxuo45bvxxxxxxxxxxcolumn45 = p7xxuo45bvxxxxxxxxxxcolumn45;
		this.q1xxuo46bvxxxxxxxxxxcolumn46 = q1xxuo46bvxxxxxxxxxxcolumn46;
		this.q4xxuo47bvxxxxxxxxxxcolumn47 = q4xxuo47bvxxxxxxxxxxcolumn47;
		this.q7xxuo48bvxxxxxxxxxxcolumn48 = q7xxuo48bvxxxxxxxxxxcolumn48;
		this.r1xxuo49bvxxxxxxxxxxcolumn49 = r1xxuo49bvxxxxxxxxxxcolumn49;
		this.r4xxuo50bvxxxxxxxxxxcolumn50 = r4xxuo50bvxxxxxxxxxxcolumn50;
		this.r7xxuo51bvxxxxxxxxxxcolumn51 = r7xxuo51bvxxxxxxxxxxcolumn51;
		this.s1xxuo52bvxxxxxxxxxxcolumn52 = s1xxuo52bvxxxxxxxxxxcolumn52;
		this.s4xxuo53bvxxxxxxxxxxcolumn53 = s4xxuo53bvxxxxxxxxxxcolumn53;
		this.s7xxuo54bvxxxxxxxxxxcolumn54 = s7xxuo54bvxxxxxxxxxxcolumn54;
		this.t1xxuo55bvxxxxxxxxxxcolumn55 = t1xxuo55bvxxxxxxxxxxcolumn55;
		this.t4xxuo56bvxxxxxxxxxxcolumn56 = t4xxuo56bvxxxxxxxxxxcolumn56;
		this.t7xxuo57bvxxxxxxxxxxcolumn57 = t7xxuo57bvxxxxxxxxxxcolumn57;
		this.u1xxuo58bvxxxxxxxxxxcolumn58 = u1xxuo58bvxxxxxxxxxxcolumn58;
		this.u4xxuo59bvxxxxxxxxxxcolumn59 = u4xxuo59bvxxxxxxxxxxcolumn59;
		this.u7xxuo60bvxxxxxxxxxxcolumn60 = u7xxuo60bvxxxxxxxxxxcolumn60;
		this.v1xxuo61bvxxxxxxxxxxcolumn61 = v1xxuo61bvxxxxxxxxxxcolumn61;
		this.v4xxuo62bvxxxxxxxxxxcolumn62 = v4xxuo62bvxxxxxxxxxxcolumn62;
		this.v7xxuo63bvxxxxxxxxxxcolumn63 = v7xxuo63bvxxxxxxxxxxcolumn63;
		this.w1xxuo64bvxxxxxxxxxxcolumn64 = w1xxuo64bvxxxxxxxxxxcolumn64;
		this.w4xxuo65bvxxxxxxxxxxcolumn65 = w4xxuo65bvxxxxxxxxxxcolumn65;
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
		this.y9xxuznxbvxxxxxxxxxxnotes = y9xxuznxbvxxxxxxxxxxnotes;
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@Column(name = "tablenm", length = 60)
	@Size(max = 60)
	public String getA1xxuxhrbvoxxxxxxxxxtablenm() {
		return this.a1xxuxhrbvoxxxxxxxxxtablenm;
	}

	public void setA1xxuxhrbvoxxxxxxxxxtablenm(
			String a1xxuxhrbvoxxxxxxxxxtablenm) {
		this.a1xxuxhrbvoxxxxxxxxxtablenm = a1xxuxhrbvoxxxxxxxxxtablenm;
	}

	@Column(name = "row", nullable = false, length = 2)
	@NotNull
	@Size(max = 2)
	public String getA2xxukcxbvxxxxxxxxxxrow() {
		return this.a2xxukcxbvxxxxxxxxxxrow;
	}

	public void setA2xxukcxbvxxxxxxxxxxrow(String a2xxukcxbvxxxxxxxxxxrow) {
		this.a2xxukcxbvxxxxxxxxxxrow = a2xxukcxbvxxxxxxxxxxrow;
	}

	@Column(name = "column01", length = 159)
	@Size(max = 159)
	public String getB1xxuo01bvxxxxxxxxxxcolumn01() {
		return this.b1xxuo01bvxxxxxxxxxxcolumn01;
	}

	public void setB1xxuo01bvxxxxxxxxxxcolumn01(
			String b1xxuo01bvxxxxxxxxxxcolumn01) {
		this.b1xxuo01bvxxxxxxxxxxcolumn01 = b1xxuo01bvxxxxxxxxxxcolumn01;
	}

	@Column(name = "column02", length = 159)
	@Size(max = 159)
	public String getB4xxuo02bvxxxxxxxxxxcolumn02() {
		return this.b4xxuo02bvxxxxxxxxxxcolumn02;
	}

	public void setB4xxuo02bvxxxxxxxxxxcolumn02(
			String b4xxuo02bvxxxxxxxxxxcolumn02) {
		this.b4xxuo02bvxxxxxxxxxxcolumn02 = b4xxuo02bvxxxxxxxxxxcolumn02;
	}

	@Column(name = "column03", length = 159)
	@Size(max = 159)
	public String getB7xxuo03bvxxxxxxxxxxcolumn03() {
		return this.b7xxuo03bvxxxxxxxxxxcolumn03;
	}

	public void setB7xxuo03bvxxxxxxxxxxcolumn03(
			String b7xxuo03bvxxxxxxxxxxcolumn03) {
		this.b7xxuo03bvxxxxxxxxxxcolumn03 = b7xxuo03bvxxxxxxxxxxcolumn03;
	}

	@Column(name = "column04", length = 159)
	@Size(max = 159)
	public String getC1xxuo04bvxxxxxxxxxxcolumn04() {
		return this.c1xxuo04bvxxxxxxxxxxcolumn04;
	}

	public void setC1xxuo04bvxxxxxxxxxxcolumn04(
			String c1xxuo04bvxxxxxxxxxxcolumn04) {
		this.c1xxuo04bvxxxxxxxxxxcolumn04 = c1xxuo04bvxxxxxxxxxxcolumn04;
	}

	@Column(name = "column05", length = 159)
	@Size(max = 159)
	public String getC4xxuo05bvxxxxxxxxxxcolumn05() {
		return this.c4xxuo05bvxxxxxxxxxxcolumn05;
	}

	public void setC4xxuo05bvxxxxxxxxxxcolumn05(
			String c4xxuo05bvxxxxxxxxxxcolumn05) {
		this.c4xxuo05bvxxxxxxxxxxcolumn05 = c4xxuo05bvxxxxxxxxxxcolumn05;
	}

	@Column(name = "column06", length = 159)
	@Size(max = 159)
	public String getC7xxuo06bvxxxxxxxxxxcolumn06() {
		return this.c7xxuo06bvxxxxxxxxxxcolumn06;
	}

	public void setC7xxuo06bvxxxxxxxxxxcolumn06(
			String c7xxuo06bvxxxxxxxxxxcolumn06) {
		this.c7xxuo06bvxxxxxxxxxxcolumn06 = c7xxuo06bvxxxxxxxxxxcolumn06;
	}

	@Column(name = "column07", length = 159)
	@Size(max = 159)
	public String getD1xxuo07bvxxxxxxxxxxcolumn07() {
		return this.d1xxuo07bvxxxxxxxxxxcolumn07;
	}

	public void setD1xxuo07bvxxxxxxxxxxcolumn07(
			String d1xxuo07bvxxxxxxxxxxcolumn07) {
		this.d1xxuo07bvxxxxxxxxxxcolumn07 = d1xxuo07bvxxxxxxxxxxcolumn07;
	}

	@Column(name = "column08", length = 159)
	@Size(max = 159)
	public String getD4xxuo08bvxxxxxxxxxxcolumn08() {
		return this.d4xxuo08bvxxxxxxxxxxcolumn08;
	}

	public void setD4xxuo08bvxxxxxxxxxxcolumn08(
			String d4xxuo08bvxxxxxxxxxxcolumn08) {
		this.d4xxuo08bvxxxxxxxxxxcolumn08 = d4xxuo08bvxxxxxxxxxxcolumn08;
	}

	@Column(name = "column09", length = 159)
	@Size(max = 159)
	public String getD7xxuo09bvxxxxxxxxxxcolumn09() {
		return this.d7xxuo09bvxxxxxxxxxxcolumn09;
	}

	public void setD7xxuo09bvxxxxxxxxxxcolumn09(
			String d7xxuo09bvxxxxxxxxxxcolumn09) {
		this.d7xxuo09bvxxxxxxxxxxcolumn09 = d7xxuo09bvxxxxxxxxxxcolumn09;
	}

	@Column(name = "column10", length = 159)
	@Size(max = 159)
	public String getE1xxuo10bvxxxxxxxxxxcolumn10() {
		return this.e1xxuo10bvxxxxxxxxxxcolumn10;
	}

	public void setE1xxuo10bvxxxxxxxxxxcolumn10(
			String e1xxuo10bvxxxxxxxxxxcolumn10) {
		this.e1xxuo10bvxxxxxxxxxxcolumn10 = e1xxuo10bvxxxxxxxxxxcolumn10;
	}

	@Column(name = "column11", length = 159)
	@Size(max = 159)
	public String getE4xxuo11bvxxxxxxxxxxcolumn11() {
		return this.e4xxuo11bvxxxxxxxxxxcolumn11;
	}

	public void setE4xxuo11bvxxxxxxxxxxcolumn11(
			String e4xxuo11bvxxxxxxxxxxcolumn11) {
		this.e4xxuo11bvxxxxxxxxxxcolumn11 = e4xxuo11bvxxxxxxxxxxcolumn11;
	}

	@Column(name = "column12", length = 159)
	@Size(max = 159)
	public String getE7xxuo12bvxxxxxxxxxxcolumn12() {
		return this.e7xxuo12bvxxxxxxxxxxcolumn12;
	}

	public void setE7xxuo12bvxxxxxxxxxxcolumn12(
			String e7xxuo12bvxxxxxxxxxxcolumn12) {
		this.e7xxuo12bvxxxxxxxxxxcolumn12 = e7xxuo12bvxxxxxxxxxxcolumn12;
	}

	@Column(name = "column13", length = 159)
	@Size(max = 159)
	public String getF1xxuo13bvxxxxxxxxxxcolumn13() {
		return this.f1xxuo13bvxxxxxxxxxxcolumn13;
	}

	public void setF1xxuo13bvxxxxxxxxxxcolumn13(
			String f1xxuo13bvxxxxxxxxxxcolumn13) {
		this.f1xxuo13bvxxxxxxxxxxcolumn13 = f1xxuo13bvxxxxxxxxxxcolumn13;
	}

	@Column(name = "column14", length = 159)
	@Size(max = 159)
	public String getF4xxuo14bvxxxxxxxxxxcolumn14() {
		return this.f4xxuo14bvxxxxxxxxxxcolumn14;
	}

	public void setF4xxuo14bvxxxxxxxxxxcolumn14(
			String f4xxuo14bvxxxxxxxxxxcolumn14) {
		this.f4xxuo14bvxxxxxxxxxxcolumn14 = f4xxuo14bvxxxxxxxxxxcolumn14;
	}

	@Column(name = "column15", length = 159)
	@Size(max = 159)
	public String getF7xxuo15bvxxxxxxxxxxcolumn15() {
		return this.f7xxuo15bvxxxxxxxxxxcolumn15;
	}

	public void setF7xxuo15bvxxxxxxxxxxcolumn15(
			String f7xxuo15bvxxxxxxxxxxcolumn15) {
		this.f7xxuo15bvxxxxxxxxxxcolumn15 = f7xxuo15bvxxxxxxxxxxcolumn15;
	}

	@Column(name = "column16", length = 159)
	@Size(max = 159)
	public String getG1xxuo16bvxxxxxxxxxxcolumn16() {
		return this.g1xxuo16bvxxxxxxxxxxcolumn16;
	}

	public void setG1xxuo16bvxxxxxxxxxxcolumn16(
			String g1xxuo16bvxxxxxxxxxxcolumn16) {
		this.g1xxuo16bvxxxxxxxxxxcolumn16 = g1xxuo16bvxxxxxxxxxxcolumn16;
	}

	@Column(name = "column17", length = 159)
	@Size(max = 159)
	public String getG4xxuo17bvxxxxxxxxxxcolumn17() {
		return this.g4xxuo17bvxxxxxxxxxxcolumn17;
	}

	public void setG4xxuo17bvxxxxxxxxxxcolumn17(
			String g4xxuo17bvxxxxxxxxxxcolumn17) {
		this.g4xxuo17bvxxxxxxxxxxcolumn17 = g4xxuo17bvxxxxxxxxxxcolumn17;
	}

	@Column(name = "column18", length = 159)
	@Size(max = 159)
	public String getG7xxuo18bvxxxxxxxxxxcolumn18() {
		return this.g7xxuo18bvxxxxxxxxxxcolumn18;
	}

	public void setG7xxuo18bvxxxxxxxxxxcolumn18(
			String g7xxuo18bvxxxxxxxxxxcolumn18) {
		this.g7xxuo18bvxxxxxxxxxxcolumn18 = g7xxuo18bvxxxxxxxxxxcolumn18;
	}

	@Column(name = "column19", length = 159)
	@Size(max = 159)
	public String getH1xxuo19bvxxxxxxxxxxcolumn19() {
		return this.h1xxuo19bvxxxxxxxxxxcolumn19;
	}

	public void setH1xxuo19bvxxxxxxxxxxcolumn19(
			String h1xxuo19bvxxxxxxxxxxcolumn19) {
		this.h1xxuo19bvxxxxxxxxxxcolumn19 = h1xxuo19bvxxxxxxxxxxcolumn19;
	}

	@Column(name = "column20", length = 159)
	@Size(max = 159)
	public String getH4xxuo20bvxxxxxxxxxxcolumn20() {
		return this.h4xxuo20bvxxxxxxxxxxcolumn20;
	}

	public void setH4xxuo20bvxxxxxxxxxxcolumn20(
			String h4xxuo20bvxxxxxxxxxxcolumn20) {
		this.h4xxuo20bvxxxxxxxxxxcolumn20 = h4xxuo20bvxxxxxxxxxxcolumn20;
	}

	@Column(name = "column21", length = 159)
	@Size(max = 159)
	public String getH7xxuo21bvxxxxxxxxxxcolumn21() {
		return this.h7xxuo21bvxxxxxxxxxxcolumn21;
	}

	public void setH7xxuo21bvxxxxxxxxxxcolumn21(
			String h7xxuo21bvxxxxxxxxxxcolumn21) {
		this.h7xxuo21bvxxxxxxxxxxcolumn21 = h7xxuo21bvxxxxxxxxxxcolumn21;
	}

	@Column(name = "column22", length = 159)
	@Size(max = 159)
	public String getI1xxuo22bvxxxxxxxxxxcolumn22() {
		return this.i1xxuo22bvxxxxxxxxxxcolumn22;
	}

	public void setI1xxuo22bvxxxxxxxxxxcolumn22(
			String i1xxuo22bvxxxxxxxxxxcolumn22) {
		this.i1xxuo22bvxxxxxxxxxxcolumn22 = i1xxuo22bvxxxxxxxxxxcolumn22;
	}

	@Column(name = "column23", length = 159)
	@Size(max = 159)
	public String getI4xxuo23bvxxxxxxxxxxcolumn23() {
		return this.i4xxuo23bvxxxxxxxxxxcolumn23;
	}

	public void setI4xxuo23bvxxxxxxxxxxcolumn23(
			String i4xxuo23bvxxxxxxxxxxcolumn23) {
		this.i4xxuo23bvxxxxxxxxxxcolumn23 = i4xxuo23bvxxxxxxxxxxcolumn23;
	}

	@Column(name = "column24", length = 159)
	@Size(max = 159)
	public String getI7xxuo24bvxxxxxxxxxxcolumn24() {
		return this.i7xxuo24bvxxxxxxxxxxcolumn24;
	}

	public void setI7xxuo24bvxxxxxxxxxxcolumn24(
			String i7xxuo24bvxxxxxxxxxxcolumn24) {
		this.i7xxuo24bvxxxxxxxxxxcolumn24 = i7xxuo24bvxxxxxxxxxxcolumn24;
	}

	@Column(name = "column25", length = 159)
	@Size(max = 159)
	public String getJ1xxuo25bvxxxxxxxxxxcolumn25() {
		return this.j1xxuo25bvxxxxxxxxxxcolumn25;
	}

	public void setJ1xxuo25bvxxxxxxxxxxcolumn25(
			String j1xxuo25bvxxxxxxxxxxcolumn25) {
		this.j1xxuo25bvxxxxxxxxxxcolumn25 = j1xxuo25bvxxxxxxxxxxcolumn25;
	}

	@Column(name = "column26", length = 159)
	@Size(max = 159)
	public String getJ4xxuo26bvxxxxxxxxxxcolumn26() {
		return this.j4xxuo26bvxxxxxxxxxxcolumn26;
	}

	public void setJ4xxuo26bvxxxxxxxxxxcolumn26(
			String j4xxuo26bvxxxxxxxxxxcolumn26) {
		this.j4xxuo26bvxxxxxxxxxxcolumn26 = j4xxuo26bvxxxxxxxxxxcolumn26;
	}

	@Column(name = "column27", length = 159)
	@Size(max = 159)
	public String getJ7xxuo27bvxxxxxxxxxxcolumn27() {
		return this.j7xxuo27bvxxxxxxxxxxcolumn27;
	}

	public void setJ7xxuo27bvxxxxxxxxxxcolumn27(
			String j7xxuo27bvxxxxxxxxxxcolumn27) {
		this.j7xxuo27bvxxxxxxxxxxcolumn27 = j7xxuo27bvxxxxxxxxxxcolumn27;
	}

	@Column(name = "column28", length = 159)
	@Size(max = 159)
	public String getK1xxuo28bvxxxxxxxxxxcolumn28() {
		return this.k1xxuo28bvxxxxxxxxxxcolumn28;
	}

	public void setK1xxuo28bvxxxxxxxxxxcolumn28(
			String k1xxuo28bvxxxxxxxxxxcolumn28) {
		this.k1xxuo28bvxxxxxxxxxxcolumn28 = k1xxuo28bvxxxxxxxxxxcolumn28;
	}

	@Column(name = "column29", length = 159)
	@Size(max = 159)
	public String getK4xxuo29bvxxxxxxxxxxcolumn29() {
		return this.k4xxuo29bvxxxxxxxxxxcolumn29;
	}

	public void setK4xxuo29bvxxxxxxxxxxcolumn29(
			String k4xxuo29bvxxxxxxxxxxcolumn29) {
		this.k4xxuo29bvxxxxxxxxxxcolumn29 = k4xxuo29bvxxxxxxxxxxcolumn29;
	}

	@Column(name = "column30", length = 159)
	@Size(max = 159)
	public String getK7xxuo30bvxxxxxxxxxxcolumn30() {
		return this.k7xxuo30bvxxxxxxxxxxcolumn30;
	}

	public void setK7xxuo30bvxxxxxxxxxxcolumn30(
			String k7xxuo30bvxxxxxxxxxxcolumn30) {
		this.k7xxuo30bvxxxxxxxxxxcolumn30 = k7xxuo30bvxxxxxxxxxxcolumn30;
	}

	@Column(name = "column31", length = 159)
	@Size(max = 159)
	public String getL1xxuo31bvxxxxxxxxxxcolumn31() {
		return this.l1xxuo31bvxxxxxxxxxxcolumn31;
	}

	public void setL1xxuo31bvxxxxxxxxxxcolumn31(
			String l1xxuo31bvxxxxxxxxxxcolumn31) {
		this.l1xxuo31bvxxxxxxxxxxcolumn31 = l1xxuo31bvxxxxxxxxxxcolumn31;
	}

	@Column(name = "column32", length = 159)
	@Size(max = 159)
	public String getL4xxuo32bvxxxxxxxxxxcolumn32() {
		return this.l4xxuo32bvxxxxxxxxxxcolumn32;
	}

	public void setL4xxuo32bvxxxxxxxxxxcolumn32(
			String l4xxuo32bvxxxxxxxxxxcolumn32) {
		this.l4xxuo32bvxxxxxxxxxxcolumn32 = l4xxuo32bvxxxxxxxxxxcolumn32;
	}

	@Column(name = "column33", length = 159)
	@Size(max = 159)
	public String getL7xxuo33bvxxxxxxxxxxcolumn33() {
		return this.l7xxuo33bvxxxxxxxxxxcolumn33;
	}

	public void setL7xxuo33bvxxxxxxxxxxcolumn33(
			String l7xxuo33bvxxxxxxxxxxcolumn33) {
		this.l7xxuo33bvxxxxxxxxxxcolumn33 = l7xxuo33bvxxxxxxxxxxcolumn33;
	}

	@Column(name = "column34", length = 159)
	@Size(max = 159)
	public String getM1xxuo34bvxxxxxxxxxxcolumn34() {
		return this.m1xxuo34bvxxxxxxxxxxcolumn34;
	}

	public void setM1xxuo34bvxxxxxxxxxxcolumn34(
			String m1xxuo34bvxxxxxxxxxxcolumn34) {
		this.m1xxuo34bvxxxxxxxxxxcolumn34 = m1xxuo34bvxxxxxxxxxxcolumn34;
	}

	@Column(name = "column35", length = 159)
	@Size(max = 159)
	public String getM4xxuo35bvxxxxxxxxxxcolumn35() {
		return this.m4xxuo35bvxxxxxxxxxxcolumn35;
	}

	public void setM4xxuo35bvxxxxxxxxxxcolumn35(
			String m4xxuo35bvxxxxxxxxxxcolumn35) {
		this.m4xxuo35bvxxxxxxxxxxcolumn35 = m4xxuo35bvxxxxxxxxxxcolumn35;
	}

	@Column(name = "column36", length = 159)
	@Size(max = 159)
	public String getM7xxuo36bvxxxxxxxxxxcolumn36() {
		return this.m7xxuo36bvxxxxxxxxxxcolumn36;
	}

	public void setM7xxuo36bvxxxxxxxxxxcolumn36(
			String m7xxuo36bvxxxxxxxxxxcolumn36) {
		this.m7xxuo36bvxxxxxxxxxxcolumn36 = m7xxuo36bvxxxxxxxxxxcolumn36;
	}

	@Column(name = "column37", length = 159)
	@Size(max = 159)
	public String getN1xxuo37bvxxxxxxxxxxcolumn37() {
		return this.n1xxuo37bvxxxxxxxxxxcolumn37;
	}

	public void setN1xxuo37bvxxxxxxxxxxcolumn37(
			String n1xxuo37bvxxxxxxxxxxcolumn37) {
		this.n1xxuo37bvxxxxxxxxxxcolumn37 = n1xxuo37bvxxxxxxxxxxcolumn37;
	}

	@Column(name = "column38", length = 159)
	@Size(max = 159)
	public String getN4xxuo38bvxxxxxxxxxxcolumn38() {
		return this.n4xxuo38bvxxxxxxxxxxcolumn38;
	}

	public void setN4xxuo38bvxxxxxxxxxxcolumn38(
			String n4xxuo38bvxxxxxxxxxxcolumn38) {
		this.n4xxuo38bvxxxxxxxxxxcolumn38 = n4xxuo38bvxxxxxxxxxxcolumn38;
	}

	@Column(name = "column39", length = 159)
	@Size(max = 159)
	public String getN7xxuo39bvxxxxxxxxxxcolumn39() {
		return this.n7xxuo39bvxxxxxxxxxxcolumn39;
	}

	public void setN7xxuo39bvxxxxxxxxxxcolumn39(
			String n7xxuo39bvxxxxxxxxxxcolumn39) {
		this.n7xxuo39bvxxxxxxxxxxcolumn39 = n7xxuo39bvxxxxxxxxxxcolumn39;
	}

	@Column(name = "column40", length = 159)
	@Size(max = 159)
	public String getO1xxuo40bvxxxxxxxxxxcolumn40() {
		return this.o1xxuo40bvxxxxxxxxxxcolumn40;
	}

	public void setO1xxuo40bvxxxxxxxxxxcolumn40(
			String o1xxuo40bvxxxxxxxxxxcolumn40) {
		this.o1xxuo40bvxxxxxxxxxxcolumn40 = o1xxuo40bvxxxxxxxxxxcolumn40;
	}

	@Column(name = "column41", length = 159)
	@Size(max = 159)
	public String getO4xxuo41bvxxxxxxxxxxcolumn41() {
		return this.o4xxuo41bvxxxxxxxxxxcolumn41;
	}

	public void setO4xxuo41bvxxxxxxxxxxcolumn41(
			String o4xxuo41bvxxxxxxxxxxcolumn41) {
		this.o4xxuo41bvxxxxxxxxxxcolumn41 = o4xxuo41bvxxxxxxxxxxcolumn41;
	}

	@Column(name = "column42", length = 159)
	@Size(max = 159)
	public String getO7xxuo42bvxxxxxxxxxxcolumn42() {
		return this.o7xxuo42bvxxxxxxxxxxcolumn42;
	}

	public void setO7xxuo42bvxxxxxxxxxxcolumn42(
			String o7xxuo42bvxxxxxxxxxxcolumn42) {
		this.o7xxuo42bvxxxxxxxxxxcolumn42 = o7xxuo42bvxxxxxxxxxxcolumn42;
	}

	@Column(name = "column43", length = 159)
	@Size(max = 159)
	public String getP1xxuo43bvxxxxxxxxxxcolumn43() {
		return this.p1xxuo43bvxxxxxxxxxxcolumn43;
	}

	public void setP1xxuo43bvxxxxxxxxxxcolumn43(
			String p1xxuo43bvxxxxxxxxxxcolumn43) {
		this.p1xxuo43bvxxxxxxxxxxcolumn43 = p1xxuo43bvxxxxxxxxxxcolumn43;
	}

	@Column(name = "column44", length = 159)
	@Size(max = 159)
	public String getP4xxuo44bvxxxxxxxxxxcolumn44() {
		return this.p4xxuo44bvxxxxxxxxxxcolumn44;
	}

	public void setP4xxuo44bvxxxxxxxxxxcolumn44(
			String p4xxuo44bvxxxxxxxxxxcolumn44) {
		this.p4xxuo44bvxxxxxxxxxxcolumn44 = p4xxuo44bvxxxxxxxxxxcolumn44;
	}

	@Column(name = "column45", length = 159)
	@Size(max = 159)
	public String getP7xxuo45bvxxxxxxxxxxcolumn45() {
		return this.p7xxuo45bvxxxxxxxxxxcolumn45;
	}

	public void setP7xxuo45bvxxxxxxxxxxcolumn45(
			String p7xxuo45bvxxxxxxxxxxcolumn45) {
		this.p7xxuo45bvxxxxxxxxxxcolumn45 = p7xxuo45bvxxxxxxxxxxcolumn45;
	}

	@Column(name = "column46", length = 159)
	@Size(max = 159)
	public String getQ1xxuo46bvxxxxxxxxxxcolumn46() {
		return this.q1xxuo46bvxxxxxxxxxxcolumn46;
	}

	public void setQ1xxuo46bvxxxxxxxxxxcolumn46(
			String q1xxuo46bvxxxxxxxxxxcolumn46) {
		this.q1xxuo46bvxxxxxxxxxxcolumn46 = q1xxuo46bvxxxxxxxxxxcolumn46;
	}

	@Column(name = "column47", length = 159)
	@Size(max = 159)
	public String getQ4xxuo47bvxxxxxxxxxxcolumn47() {
		return this.q4xxuo47bvxxxxxxxxxxcolumn47;
	}

	public void setQ4xxuo47bvxxxxxxxxxxcolumn47(
			String q4xxuo47bvxxxxxxxxxxcolumn47) {
		this.q4xxuo47bvxxxxxxxxxxcolumn47 = q4xxuo47bvxxxxxxxxxxcolumn47;
	}

	@Column(name = "column48", length = 159)
	@Size(max = 159)
	public String getQ7xxuo48bvxxxxxxxxxxcolumn48() {
		return this.q7xxuo48bvxxxxxxxxxxcolumn48;
	}

	public void setQ7xxuo48bvxxxxxxxxxxcolumn48(
			String q7xxuo48bvxxxxxxxxxxcolumn48) {
		this.q7xxuo48bvxxxxxxxxxxcolumn48 = q7xxuo48bvxxxxxxxxxxcolumn48;
	}

	@Column(name = "column49", length = 159)
	@Size(max = 159)
	public String getR1xxuo49bvxxxxxxxxxxcolumn49() {
		return this.r1xxuo49bvxxxxxxxxxxcolumn49;
	}

	public void setR1xxuo49bvxxxxxxxxxxcolumn49(
			String r1xxuo49bvxxxxxxxxxxcolumn49) {
		this.r1xxuo49bvxxxxxxxxxxcolumn49 = r1xxuo49bvxxxxxxxxxxcolumn49;
	}

	@Column(name = "column50", length = 159)
	@Size(max = 159)
	public String getR4xxuo50bvxxxxxxxxxxcolumn50() {
		return this.r4xxuo50bvxxxxxxxxxxcolumn50;
	}

	public void setR4xxuo50bvxxxxxxxxxxcolumn50(
			String r4xxuo50bvxxxxxxxxxxcolumn50) {
		this.r4xxuo50bvxxxxxxxxxxcolumn50 = r4xxuo50bvxxxxxxxxxxcolumn50;
	}

	@Column(name = "column51", length = 159)
	@Size(max = 159)
	public String getR7xxuo51bvxxxxxxxxxxcolumn51() {
		return this.r7xxuo51bvxxxxxxxxxxcolumn51;
	}

	public void setR7xxuo51bvxxxxxxxxxxcolumn51(
			String r7xxuo51bvxxxxxxxxxxcolumn51) {
		this.r7xxuo51bvxxxxxxxxxxcolumn51 = r7xxuo51bvxxxxxxxxxxcolumn51;
	}

	@Column(name = "column52", length = 159)
	@Size(max = 159)
	public String getS1xxuo52bvxxxxxxxxxxcolumn52() {
		return this.s1xxuo52bvxxxxxxxxxxcolumn52;
	}

	public void setS1xxuo52bvxxxxxxxxxxcolumn52(
			String s1xxuo52bvxxxxxxxxxxcolumn52) {
		this.s1xxuo52bvxxxxxxxxxxcolumn52 = s1xxuo52bvxxxxxxxxxxcolumn52;
	}

	@Column(name = "column53", length = 159)
	@Size(max = 159)
	public String getS4xxuo53bvxxxxxxxxxxcolumn53() {
		return this.s4xxuo53bvxxxxxxxxxxcolumn53;
	}

	public void setS4xxuo53bvxxxxxxxxxxcolumn53(
			String s4xxuo53bvxxxxxxxxxxcolumn53) {
		this.s4xxuo53bvxxxxxxxxxxcolumn53 = s4xxuo53bvxxxxxxxxxxcolumn53;
	}

	@Column(name = "column54", length = 159)
	@Size(max = 159)
	public String getS7xxuo54bvxxxxxxxxxxcolumn54() {
		return this.s7xxuo54bvxxxxxxxxxxcolumn54;
	}

	public void setS7xxuo54bvxxxxxxxxxxcolumn54(
			String s7xxuo54bvxxxxxxxxxxcolumn54) {
		this.s7xxuo54bvxxxxxxxxxxcolumn54 = s7xxuo54bvxxxxxxxxxxcolumn54;
	}

	@Column(name = "column55", length = 159)
	@Size(max = 159)
	public String getT1xxuo55bvxxxxxxxxxxcolumn55() {
		return this.t1xxuo55bvxxxxxxxxxxcolumn55;
	}

	public void setT1xxuo55bvxxxxxxxxxxcolumn55(
			String t1xxuo55bvxxxxxxxxxxcolumn55) {
		this.t1xxuo55bvxxxxxxxxxxcolumn55 = t1xxuo55bvxxxxxxxxxxcolumn55;
	}

	@Column(name = "column56", length = 159)
	@Size(max = 159)
	public String getT4xxuo56bvxxxxxxxxxxcolumn56() {
		return this.t4xxuo56bvxxxxxxxxxxcolumn56;
	}

	public void setT4xxuo56bvxxxxxxxxxxcolumn56(
			String t4xxuo56bvxxxxxxxxxxcolumn56) {
		this.t4xxuo56bvxxxxxxxxxxcolumn56 = t4xxuo56bvxxxxxxxxxxcolumn56;
	}

	@Column(name = "column57", length = 159)
	@Size(max = 159)
	public String getT7xxuo57bvxxxxxxxxxxcolumn57() {
		return this.t7xxuo57bvxxxxxxxxxxcolumn57;
	}

	public void setT7xxuo57bvxxxxxxxxxxcolumn57(
			String t7xxuo57bvxxxxxxxxxxcolumn57) {
		this.t7xxuo57bvxxxxxxxxxxcolumn57 = t7xxuo57bvxxxxxxxxxxcolumn57;
	}

	@Column(name = "column58", length = 159)
	@Size(max = 159)
	public String getU1xxuo58bvxxxxxxxxxxcolumn58() {
		return this.u1xxuo58bvxxxxxxxxxxcolumn58;
	}

	public void setU1xxuo58bvxxxxxxxxxxcolumn58(
			String u1xxuo58bvxxxxxxxxxxcolumn58) {
		this.u1xxuo58bvxxxxxxxxxxcolumn58 = u1xxuo58bvxxxxxxxxxxcolumn58;
	}

	@Column(name = "column59", length = 159)
	@Size(max = 159)
	public String getU4xxuo59bvxxxxxxxxxxcolumn59() {
		return this.u4xxuo59bvxxxxxxxxxxcolumn59;
	}

	public void setU4xxuo59bvxxxxxxxxxxcolumn59(
			String u4xxuo59bvxxxxxxxxxxcolumn59) {
		this.u4xxuo59bvxxxxxxxxxxcolumn59 = u4xxuo59bvxxxxxxxxxxcolumn59;
	}

	@Column(name = "column60", length = 159)
	@Size(max = 159)
	public String getU7xxuo60bvxxxxxxxxxxcolumn60() {
		return this.u7xxuo60bvxxxxxxxxxxcolumn60;
	}

	public void setU7xxuo60bvxxxxxxxxxxcolumn60(
			String u7xxuo60bvxxxxxxxxxxcolumn60) {
		this.u7xxuo60bvxxxxxxxxxxcolumn60 = u7xxuo60bvxxxxxxxxxxcolumn60;
	}

	@Column(name = "column61", length = 159)
	@Size(max = 159)
	public String getV1xxuo61bvxxxxxxxxxxcolumn61() {
		return this.v1xxuo61bvxxxxxxxxxxcolumn61;
	}

	public void setV1xxuo61bvxxxxxxxxxxcolumn61(
			String v1xxuo61bvxxxxxxxxxxcolumn61) {
		this.v1xxuo61bvxxxxxxxxxxcolumn61 = v1xxuo61bvxxxxxxxxxxcolumn61;
	}

	@Column(name = "column62", length = 159)
	@Size(max = 159)
	public String getV4xxuo62bvxxxxxxxxxxcolumn62() {
		return this.v4xxuo62bvxxxxxxxxxxcolumn62;
	}

	public void setV4xxuo62bvxxxxxxxxxxcolumn62(
			String v4xxuo62bvxxxxxxxxxxcolumn62) {
		this.v4xxuo62bvxxxxxxxxxxcolumn62 = v4xxuo62bvxxxxxxxxxxcolumn62;
	}

	@Column(name = "column63", length = 159)
	@Size(max = 159)
	public String getV7xxuo63bvxxxxxxxxxxcolumn63() {
		return this.v7xxuo63bvxxxxxxxxxxcolumn63;
	}

	public void setV7xxuo63bvxxxxxxxxxxcolumn63(
			String v7xxuo63bvxxxxxxxxxxcolumn63) {
		this.v7xxuo63bvxxxxxxxxxxcolumn63 = v7xxuo63bvxxxxxxxxxxcolumn63;
	}

	@Column(name = "column64", length = 159)
	@Size(max = 159)
	public String getW1xxuo64bvxxxxxxxxxxcolumn64() {
		return this.w1xxuo64bvxxxxxxxxxxcolumn64;
	}

	public void setW1xxuo64bvxxxxxxxxxxcolumn64(
			String w1xxuo64bvxxxxxxxxxxcolumn64) {
		this.w1xxuo64bvxxxxxxxxxxcolumn64 = w1xxuo64bvxxxxxxxxxxcolumn64;
	}

	@Column(name = "column65", length = 159)
	@Size(max = 159)
	public String getW4xxuo65bvxxxxxxxxxxcolumn65() {
		return this.w4xxuo65bvxxxxxxxxxxcolumn65;
	}

	public void setW4xxuo65bvxxxxxxxxxxcolumn65(
			String w4xxuo65bvxxxxxxxxxxcolumn65) {
		this.w4xxuo65bvxxxxxxxxxxcolumn65 = w4xxuo65bvxxxxxxxxxxcolumn65;
	}

	@Column(name = "statusfl")
	public Integer getZ1xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ1xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ2xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ2xxcztxlxxxxxxxxxxxstatusfldt(
			Date z2xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY9xxuznxbvxxxxxxxxxxnotes() {
		return this.y9xxuznxbvxxxxxxxxxxnotes;
	}

	public void setY9xxuznxbvxxxxxxxxxxnotes(String y9xxuznxbvxxxxxxxxxxnotes) {
		this.y9xxuznxbvxxxxxxxxxxnotes = y9xxuznxbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ3xxutoxlhxxxxxxxxxxowner() {
		return this.z3xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ3xxutoxlhxxxxxxxxxxowner(String z3xxutoxlhxxxxxxxxxxowner) {
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

}
