package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Yrxxch511xhhxxhxxxxxoptions generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "options", uniqueConstraints = @UniqueConstraint(columnNames = {
		"row", "owner2"}))
public class Yrxxch511xhhxxhxxxxxoptions implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private String a0xxukcxbvxxxxxxxxxxrow;
	private String b1xxuo01bvxxxxxxxxxxoptions01;
	private String b2xxup01bvxxxxxxxxxxpurpose01;
	private String b3xxuv01bvxxxxxxxxxxvalue01;
	private String b4xxuo02bvxxxxxxxxxxoptions02;
	private String b5xxup02bvxxxxxxxxxxpurpose02;
	private String b6xxuv02bvxxxxxxxxxxvalue02;
	private String b7xxuo03bvxxxxxxxxxxoptions03;
	private String b8xxup03bvxxxxxxxxxxpurpose03;
	private String b9xxuv03bvxxxxxxxxxxvalue03;
	private String c1xxuo04bvxxxxxxxxxxoptions04;
	private String c2xxup04bvxxxxxxxxxxpurpose04;
	private String c3xxuv04bvxxxxxxxxxxvalue04;
	private String c4xxuo05bvxxxxxxxxxxoptions05;
	private String c5xxup05bvxxxxxxxxxxpurpose05;
	private String c6xxuv05bvxxxxxxxxxxvalue05;
	private String c7xxuo06bvxxxxxxxxxxoptions06;
	private String c8xxup06bvxxxxxxxxxxpurpose06;
	private String c9xxuv06bvxxxxxxxxxxvalue06;
	private String d1xxuo07bvxxxxxxxxxxoptions07;
	private String d2xxup07bvxxxxxxxxxxpurpose07;
	private String d3xxuv07bvxxxxxxxxxxvalue07;
	private String d4xxuo08bvxxxxxxxxxxoptions08;
	private String d5xxup08bvxxxxxxxxxxpurpose08;
	private String d6xxuv08bvxxxxxxxxxxvalue08;
	private String d7xxuo09bvxxxxxxxxxxoptions09;
	private String d8xxup09bvxxxxxxxxxxpurpose09;
	private String d9xxuv09bvxxxxxxxxxxvalue09;
	private String e1xxuo10bvxxxxxxxxxxoptions10;
	private String e2xxup10bvxxxxxxxxxxpurpose10;
	private String e3xxuv10bvxxxxxxxxxxvalue10;
	private String e4xxuo11bvxxxxxxxxxxoptions11;
	private String e5xxup11bvxxxxxxxxxxpurpose11;
	private String e6xxuv11bvxxxxxxxxxxvalue11;
	private String e7xxuo12bvxxxxxxxxxxoptions12;
	private String e8xxup12bvxxxxxxxxxxpurpose12;
	private String e9xxuv12bvxxxxxxxxxxvalue12;
	private String f1xxuo13bvxxxxxxxxxxoptions13;
	private String f2xxup13bvxxxxxxxxxxpurpose13;
	private String f3xxuv13bvxxxxxxxxxxvalue13;
	private String f4xxuo14bvxxxxxxxxxxoptions14;
	private String f5xxup14bvxxxxxxxxxxpurpose14;
	private String f6xxuv14bvxxxxxxxxxxvalue14;
	private String f7xxuo15bvxxxxxxxxxxoptions15;
	private String f8xxup15bvxxxxxxxxxxpurpose15;
	private String f9xxuv15bvxxxxxxxxxxvalue15;
	private String g1xxuo16bvxxxxxxxxxxoptions16;
	private String g2xxup16bvxxxxxxxxxxpurpose16;
	private String g3xxuv16bvxxxxxxxxxxvalue16;
	private String g4xxuo17bvxxxxxxxxxxoptions17;
	private String g5xxup17bvxxxxxxxxxxpurpose17;
	private String g6xxuv17bvxxxxxxxxxxvalue17;
	private String g7xxuo18bvxxxxxxxxxxoptions18;
	private String g8xxup18bvxxxxxxxxxxpurpose18;
	private String g9xxuv18bvxxxxxxxxxxvalue18;
	private String h1xxuo19bvxxxxxxxxxxoptions19;
	private String h2xxup19bvxxxxxxxxxxpurpose19;
	private String h3xxuv19bvxxxxxxxxxxvalue19;
	private String h4xxuo20bvxxxxxxxxxxoptions20;
	private String h5xxup20bvxxxxxxxxxxpurpose20;
	private String h6xxuv20bvxxxxxxxxxxvalue20;
	private String h7xxuo21bvxxxxxxxxxxoptions21;
	private String h8xxup21bvxxxxxxxxxxpurpose21;
	private String h9xxuv21bvxxxxxxxxxxvalue21;
	private String i1xxuo22bvxxxxxxxxxxoptions22;
	private String i2xxup22bvxxxxxxxxxxpurpose22;
	private String i3xxuv22bvxxxxxxxxxxvalue22;
	private String i4xxuo23bvxxxxxxxxxxoptions23;
	private String i5xxup23bvxxxxxxxxxxpurpose23;
	private String i6xxuv23bvxxxxxxxxxxvalue23;
	private String i7xxuo24bvxxxxxxxxxxoptions24;
	private String i8xxup24bvxxxxxxxxxxpurpose24;
	private String i9xxuv24bvxxxxxxxxxxvalue24;
	private String j1xxuo25bvxxxxxxxxxxoptions25;
	private String j2xxup25bvxxxxxxxxxxpurpose25;
	private String j3xxuv25bvxxxxxxxxxxvalue25;
	private String j4xxuo26bvxxxxxxxxxxoptions26;
	private String j5xxup26bvxxxxxxxxxxpurpose26;
	private String j6xxuv26bvxxxxxxxxxxvalue26;
	private String j7xxuo27bvxxxxxxxxxxoptions27;
	private String j8xxup27bvxxxxxxxxxxpurpose27;
	private String j9xxuv27bvxxxxxxxxxxvalue27;
	private String k1xxuo28bvxxxxxxxxxxoptions28;
	private String k2xxup28bvxxxxxxxxxxpurpose28;
	private String k3xxuv28bvxxxxxxxxxxvalue28;
	private String k4xxuo29bvxxxxxxxxxxoptions29;
	private String k5xxup29bvxxxxxxxxxxpurpose29;
	private String k6xxuv29bvxxxxxxxxxxvalue29;
	private String k7xxuo30bvxxxxxxxxxxoptions30;
	private String k8xxup30bvxxxxxxxxxxpurpose30;
	private String k9xxuv30bvxxxxxxxxxxvalue30;
	private String l1xxuo31bvxxxxxxxxxxoptions31;
	private String l2xxup31bvxxxxxxxxxxpurpose31;
	private String l3xxuv31bvxxxxxxxxxxvalue31;
	private String l4xxuo32bvxxxxxxxxxxoptions32;
	private String l5xxup32bvxxxxxxxxxxpurpose32;
	private String l6xxuv32bvxxxxxxxxxxvalue32;
	private String l7xxuo33bvxxxxxxxxxxoptions33;
	private String l8xxup33bvxxxxxxxxxxpurpose33;
	private String l9xxuv33bvxxxxxxxxxxvalue33;
	private String m1xxuo34bvxxxxxxxxxxoptions34;
	private String m2xxup34bvxxxxxxxxxxpurpose34;
	private String m3xxuv34bvxxxxxxxxxxvalue34;
	private String m4xxuo35bvxxxxxxxxxxoptions35;
	private String m5xxup35bvxxxxxxxxxxpurpose35;
	private String m6xxuv35bvxxxxxxxxxxvalue35;
	private String m7xxuo36bvxxxxxxxxxxoptions36;
	private String m8xxup36bvxxxxxxxxxxpurpose36;
	private String m9xxuv36bvxxxxxxxxxxvalue36;
	private String n1xxuo37bvxxxxxxxxxxoptions37;
	private String n2xxup37bvxxxxxxxxxxpurpose37;
	private String n3xxuv37bvxxxxxxxxxxvalue37;
	private String n4xxuo38bvxxxxxxxxxxoptions38;
	private String n5xxup38bvxxxxxxxxxxpurpose38;
	private String n6xxuv38bvxxxxxxxxxxvalue38;
	private String n7xxuo39bvxxxxxxxxxxoptions39;
	private String n8xxup39bvxxxxxxxxxxpurpose39;
	private String n9xxuv39bvxxxxxxxxxxvalue39;
	private String o1xxuo40bvxxxxxxxxxxoptions40;
	private String o2xxup40bvxxxxxxxxxxpurpose40;
	private String o3xxuv40bvxxxxxxxxxxvalue40;
	private String o4xxuo41bvxxxxxxxxxxoptions41;
	private String o5xxup41bvxxxxxxxxxxpurpose41;
	private String o6xxuv41bvxxxxxxxxxxvalue41;
	private String o7xxuo42bvxxxxxxxxxxoptions42;
	private String o8xxup42bvxxxxxxxxxxpurpose42;
	private String o9xxuv42bvxxxxxxxxxxvalue42;
	private String p1xxuo43bvxxxxxxxxxxoptions43;
	private String p2xxup43bvxxxxxxxxxxpurpose43;
	private String p3xxuv43bvxxxxxxxxxxvalue43;
	private String p4xxuo44bvxxxxxxxxxxoptions44;
	private String p5xxup44bvxxxxxxxxxxpurpose44;
	private String p6xxuv44bvxxxxxxxxxxvalue44;
	private String p7xxuo45bvxxxxxxxxxxoptions45;
	private String p8xxup45bvxxxxxxxxxxpurpose45;
	private String p9xxuv45bvxxxxxxxxxxvalue45;
	private String q1xxuo46bvxxxxxxxxxxoptions46;
	private String q2xxup46bvxxxxxxxxxxpurpose46;
	private String q3xxuv46bvxxxxxxxxxxvalue46;
	private String q4xxuo47bvxxxxxxxxxxoptions47;
	private String q5xxup47bvxxxxxxxxxxpurpose47;
	private String q6xxuv47bvxxxxxxxxxxvalue47;
	private String q7xxuo48bvxxxxxxxxxxoptions48;
	private String q8xxup48bvxxxxxxxxxxpurpose48;
	private String q9xxuv48bvxxxxxxxxxxvalue48;
	private String r1xxuo49bvxxxxxxxxxxoptions49;
	private String r2xxup49bvxxxxxxxxxxpurpose49;
	private String r3xxuv49bvxxxxxxxxxxvalue49;
	private String r4xxuo50bvxxxxxxxxxxoptions50;
	private String r5xxup50bvxxxxxxxxxxpurpose50;
	private String r6xxuv50bvxxxxxxxxxxvalue50;
	private String r7xxuo51bvxxxxxxxxxxoptions51;
	private String r8xxup51bvxxxxxxxxxxpurpose51;
	private String r9xxuv51bvxxxxxxxxxxvalue51;
	private String s1xxuo52bvxxxxxxxxxxoptions52;
	private String s2xxup52bvxxxxxxxxxxpurpose52;
	private String s3xxuv52bvxxxxxxxxxxvalue52;
	private String s4xxuo53bvxxxxxxxxxxoptions53;
	private String s5xxup53bvxxxxxxxxxxpurpose53;
	private String s6xxuv53bvxxxxxxxxxxvalue53;
	private String s7xxuo54bvxxxxxxxxxxoptions54;
	private String s8xxup54bvxxxxxxxxxxpurpose54;
	private String s9xxuv54bvxxxxxxxxxxvalue54;
	private String t1xxuo55bvxxxxxxxxxxoptions55;
	private String t2xxup55bvxxxxxxxxxxpurpose55;
	private String t3xxuv55bvxxxxxxxxxxvalue55;
	private String t4xxuo56bvxxxxxxxxxxoptions56;
	private String t5xxup56bvxxxxxxxxxxpurpose56;
	private String t6xxuv56bvxxxxxxxxxxvalue56;
	private String t7xxuo57bvxxxxxxxxxxoptions57;
	private String t8xxup57bvxxxxxxxxxxpurpose57;
	private String t9xxuv57bvxxxxxxxxxxvalue57;
	private String u1xxuo58bvxxxxxxxxxxoptions58;
	private String u2xxup58bvxxxxxxxxxxpurpose58;
	private String u3xxuv58bvxxxxxxxxxxvalue58;
	private String u4xxuo59bvxxxxxxxxxxoptions59;
	private String u5xxup59bvxxxxxxxxxxpurpose59;
	private String u6xxuv59bvxxxxxxxxxxvalue59;
	private String u7xxuo60bvxxxxxxxxxxoptions60;
	private String u8xxup60bvxxxxxxxxxxpurpose60;
	private String u9xxuv60bvxxxxxxxxxxvalue60;
	private String v1xxuo61bvxxxxxxxxxxoptions61;
	private String v2xxup61bvxxxxxxxxxxpurpose61;
	private String v3xxuv61bvxxxxxxxxxxvalue61;
	private Integer z1xxzzfxhhxxxxxxxxxxstatusfl;
	private Date z2xxcztxlxxxxxxxxxxxstatusfldt;
	private String y9xxuznxbvxxxxxxxxxxnotes;
	private String z3xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Yrxxch511xhhxxhxxxxxoptions() {
	}

	public Yrxxch511xhhxxhxxxxxoptions(String a0xxukcxbvxxxxxxxxxxrow) {
		this.a0xxukcxbvxxxxxxxxxxrow = a0xxukcxbvxxxxxxxxxxrow;
	}
	public Yrxxch511xhhxxhxxxxxoptions(String a0xxukcxbvxxxxxxxxxxrow,
			String b1xxuo01bvxxxxxxxxxxoptions01,
			String b2xxup01bvxxxxxxxxxxpurpose01,
			String b3xxuv01bvxxxxxxxxxxvalue01,
			String b4xxuo02bvxxxxxxxxxxoptions02,
			String b5xxup02bvxxxxxxxxxxpurpose02,
			String b6xxuv02bvxxxxxxxxxxvalue02,
			String b7xxuo03bvxxxxxxxxxxoptions03,
			String b8xxup03bvxxxxxxxxxxpurpose03,
			String b9xxuv03bvxxxxxxxxxxvalue03,
			String c1xxuo04bvxxxxxxxxxxoptions04,
			String c2xxup04bvxxxxxxxxxxpurpose04,
			String c3xxuv04bvxxxxxxxxxxvalue04,
			String c4xxuo05bvxxxxxxxxxxoptions05,
			String c5xxup05bvxxxxxxxxxxpurpose05,
			String c6xxuv05bvxxxxxxxxxxvalue05,
			String c7xxuo06bvxxxxxxxxxxoptions06,
			String c8xxup06bvxxxxxxxxxxpurpose06,
			String c9xxuv06bvxxxxxxxxxxvalue06,
			String d1xxuo07bvxxxxxxxxxxoptions07,
			String d2xxup07bvxxxxxxxxxxpurpose07,
			String d3xxuv07bvxxxxxxxxxxvalue07,
			String d4xxuo08bvxxxxxxxxxxoptions08,
			String d5xxup08bvxxxxxxxxxxpurpose08,
			String d6xxuv08bvxxxxxxxxxxvalue08,
			String d7xxuo09bvxxxxxxxxxxoptions09,
			String d8xxup09bvxxxxxxxxxxpurpose09,
			String d9xxuv09bvxxxxxxxxxxvalue09,
			String e1xxuo10bvxxxxxxxxxxoptions10,
			String e2xxup10bvxxxxxxxxxxpurpose10,
			String e3xxuv10bvxxxxxxxxxxvalue10,
			String e4xxuo11bvxxxxxxxxxxoptions11,
			String e5xxup11bvxxxxxxxxxxpurpose11,
			String e6xxuv11bvxxxxxxxxxxvalue11,
			String e7xxuo12bvxxxxxxxxxxoptions12,
			String e8xxup12bvxxxxxxxxxxpurpose12,
			String e9xxuv12bvxxxxxxxxxxvalue12,
			String f1xxuo13bvxxxxxxxxxxoptions13,
			String f2xxup13bvxxxxxxxxxxpurpose13,
			String f3xxuv13bvxxxxxxxxxxvalue13,
			String f4xxuo14bvxxxxxxxxxxoptions14,
			String f5xxup14bvxxxxxxxxxxpurpose14,
			String f6xxuv14bvxxxxxxxxxxvalue14,
			String f7xxuo15bvxxxxxxxxxxoptions15,
			String f8xxup15bvxxxxxxxxxxpurpose15,
			String f9xxuv15bvxxxxxxxxxxvalue15,
			String g1xxuo16bvxxxxxxxxxxoptions16,
			String g2xxup16bvxxxxxxxxxxpurpose16,
			String g3xxuv16bvxxxxxxxxxxvalue16,
			String g4xxuo17bvxxxxxxxxxxoptions17,
			String g5xxup17bvxxxxxxxxxxpurpose17,
			String g6xxuv17bvxxxxxxxxxxvalue17,
			String g7xxuo18bvxxxxxxxxxxoptions18,
			String g8xxup18bvxxxxxxxxxxpurpose18,
			String g9xxuv18bvxxxxxxxxxxvalue18,
			String h1xxuo19bvxxxxxxxxxxoptions19,
			String h2xxup19bvxxxxxxxxxxpurpose19,
			String h3xxuv19bvxxxxxxxxxxvalue19,
			String h4xxuo20bvxxxxxxxxxxoptions20,
			String h5xxup20bvxxxxxxxxxxpurpose20,
			String h6xxuv20bvxxxxxxxxxxvalue20,
			String h7xxuo21bvxxxxxxxxxxoptions21,
			String h8xxup21bvxxxxxxxxxxpurpose21,
			String h9xxuv21bvxxxxxxxxxxvalue21,
			String i1xxuo22bvxxxxxxxxxxoptions22,
			String i2xxup22bvxxxxxxxxxxpurpose22,
			String i3xxuv22bvxxxxxxxxxxvalue22,
			String i4xxuo23bvxxxxxxxxxxoptions23,
			String i5xxup23bvxxxxxxxxxxpurpose23,
			String i6xxuv23bvxxxxxxxxxxvalue23,
			String i7xxuo24bvxxxxxxxxxxoptions24,
			String i8xxup24bvxxxxxxxxxxpurpose24,
			String i9xxuv24bvxxxxxxxxxxvalue24,
			String j1xxuo25bvxxxxxxxxxxoptions25,
			String j2xxup25bvxxxxxxxxxxpurpose25,
			String j3xxuv25bvxxxxxxxxxxvalue25,
			String j4xxuo26bvxxxxxxxxxxoptions26,
			String j5xxup26bvxxxxxxxxxxpurpose26,
			String j6xxuv26bvxxxxxxxxxxvalue26,
			String j7xxuo27bvxxxxxxxxxxoptions27,
			String j8xxup27bvxxxxxxxxxxpurpose27,
			String j9xxuv27bvxxxxxxxxxxvalue27,
			String k1xxuo28bvxxxxxxxxxxoptions28,
			String k2xxup28bvxxxxxxxxxxpurpose28,
			String k3xxuv28bvxxxxxxxxxxvalue28,
			String k4xxuo29bvxxxxxxxxxxoptions29,
			String k5xxup29bvxxxxxxxxxxpurpose29,
			String k6xxuv29bvxxxxxxxxxxvalue29,
			String k7xxuo30bvxxxxxxxxxxoptions30,
			String k8xxup30bvxxxxxxxxxxpurpose30,
			String k9xxuv30bvxxxxxxxxxxvalue30,
			String l1xxuo31bvxxxxxxxxxxoptions31,
			String l2xxup31bvxxxxxxxxxxpurpose31,
			String l3xxuv31bvxxxxxxxxxxvalue31,
			String l4xxuo32bvxxxxxxxxxxoptions32,
			String l5xxup32bvxxxxxxxxxxpurpose32,
			String l6xxuv32bvxxxxxxxxxxvalue32,
			String l7xxuo33bvxxxxxxxxxxoptions33,
			String l8xxup33bvxxxxxxxxxxpurpose33,
			String l9xxuv33bvxxxxxxxxxxvalue33,
			String m1xxuo34bvxxxxxxxxxxoptions34,
			String m2xxup34bvxxxxxxxxxxpurpose34,
			String m3xxuv34bvxxxxxxxxxxvalue34,
			String m4xxuo35bvxxxxxxxxxxoptions35,
			String m5xxup35bvxxxxxxxxxxpurpose35,
			String m6xxuv35bvxxxxxxxxxxvalue35,
			String m7xxuo36bvxxxxxxxxxxoptions36,
			String m8xxup36bvxxxxxxxxxxpurpose36,
			String m9xxuv36bvxxxxxxxxxxvalue36,
			String n1xxuo37bvxxxxxxxxxxoptions37,
			String n2xxup37bvxxxxxxxxxxpurpose37,
			String n3xxuv37bvxxxxxxxxxxvalue37,
			String n4xxuo38bvxxxxxxxxxxoptions38,
			String n5xxup38bvxxxxxxxxxxpurpose38,
			String n6xxuv38bvxxxxxxxxxxvalue38,
			String n7xxuo39bvxxxxxxxxxxoptions39,
			String n8xxup39bvxxxxxxxxxxpurpose39,
			String n9xxuv39bvxxxxxxxxxxvalue39,
			String o1xxuo40bvxxxxxxxxxxoptions40,
			String o2xxup40bvxxxxxxxxxxpurpose40,
			String o3xxuv40bvxxxxxxxxxxvalue40,
			String o4xxuo41bvxxxxxxxxxxoptions41,
			String o5xxup41bvxxxxxxxxxxpurpose41,
			String o6xxuv41bvxxxxxxxxxxvalue41,
			String o7xxuo42bvxxxxxxxxxxoptions42,
			String o8xxup42bvxxxxxxxxxxpurpose42,
			String o9xxuv42bvxxxxxxxxxxvalue42,
			String p1xxuo43bvxxxxxxxxxxoptions43,
			String p2xxup43bvxxxxxxxxxxpurpose43,
			String p3xxuv43bvxxxxxxxxxxvalue43,
			String p4xxuo44bvxxxxxxxxxxoptions44,
			String p5xxup44bvxxxxxxxxxxpurpose44,
			String p6xxuv44bvxxxxxxxxxxvalue44,
			String p7xxuo45bvxxxxxxxxxxoptions45,
			String p8xxup45bvxxxxxxxxxxpurpose45,
			String p9xxuv45bvxxxxxxxxxxvalue45,
			String q1xxuo46bvxxxxxxxxxxoptions46,
			String q2xxup46bvxxxxxxxxxxpurpose46,
			String q3xxuv46bvxxxxxxxxxxvalue46,
			String q4xxuo47bvxxxxxxxxxxoptions47,
			String q5xxup47bvxxxxxxxxxxpurpose47,
			String q6xxuv47bvxxxxxxxxxxvalue47,
			String q7xxuo48bvxxxxxxxxxxoptions48,
			String q8xxup48bvxxxxxxxxxxpurpose48,
			String q9xxuv48bvxxxxxxxxxxvalue48,
			String r1xxuo49bvxxxxxxxxxxoptions49,
			String r2xxup49bvxxxxxxxxxxpurpose49,
			String r3xxuv49bvxxxxxxxxxxvalue49,
			String r4xxuo50bvxxxxxxxxxxoptions50,
			String r5xxup50bvxxxxxxxxxxpurpose50,
			String r6xxuv50bvxxxxxxxxxxvalue50,
			String r7xxuo51bvxxxxxxxxxxoptions51,
			String r8xxup51bvxxxxxxxxxxpurpose51,
			String r9xxuv51bvxxxxxxxxxxvalue51,
			String s1xxuo52bvxxxxxxxxxxoptions52,
			String s2xxup52bvxxxxxxxxxxpurpose52,
			String s3xxuv52bvxxxxxxxxxxvalue52,
			String s4xxuo53bvxxxxxxxxxxoptions53,
			String s5xxup53bvxxxxxxxxxxpurpose53,
			String s6xxuv53bvxxxxxxxxxxvalue53,
			String s7xxuo54bvxxxxxxxxxxoptions54,
			String s8xxup54bvxxxxxxxxxxpurpose54,
			String s9xxuv54bvxxxxxxxxxxvalue54,
			String t1xxuo55bvxxxxxxxxxxoptions55,
			String t2xxup55bvxxxxxxxxxxpurpose55,
			String t3xxuv55bvxxxxxxxxxxvalue55,
			String t4xxuo56bvxxxxxxxxxxoptions56,
			String t5xxup56bvxxxxxxxxxxpurpose56,
			String t6xxuv56bvxxxxxxxxxxvalue56,
			String t7xxuo57bvxxxxxxxxxxoptions57,
			String t8xxup57bvxxxxxxxxxxpurpose57,
			String t9xxuv57bvxxxxxxxxxxvalue57,
			String u1xxuo58bvxxxxxxxxxxoptions58,
			String u2xxup58bvxxxxxxxxxxpurpose58,
			String u3xxuv58bvxxxxxxxxxxvalue58,
			String u4xxuo59bvxxxxxxxxxxoptions59,
			String u5xxup59bvxxxxxxxxxxpurpose59,
			String u6xxuv59bvxxxxxxxxxxvalue59,
			String u7xxuo60bvxxxxxxxxxxoptions60,
			String u8xxup60bvxxxxxxxxxxpurpose60,
			String u9xxuv60bvxxxxxxxxxxvalue60,
			String v1xxuo61bvxxxxxxxxxxoptions61,
			String v2xxup61bvxxxxxxxxxxpurpose61,
			String v3xxuv61bvxxxxxxxxxxvalue61,
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl,
			Date z2xxcztxlxxxxxxxxxxxstatusfldt,
			String y9xxuznxbvxxxxxxxxxxnotes, String z3xxutoxlhxxxxxxxxxxowner,
			String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.a0xxukcxbvxxxxxxxxxxrow = a0xxukcxbvxxxxxxxxxxrow;
		this.b1xxuo01bvxxxxxxxxxxoptions01 = b1xxuo01bvxxxxxxxxxxoptions01;
		this.b2xxup01bvxxxxxxxxxxpurpose01 = b2xxup01bvxxxxxxxxxxpurpose01;
		this.b3xxuv01bvxxxxxxxxxxvalue01 = b3xxuv01bvxxxxxxxxxxvalue01;
		this.b4xxuo02bvxxxxxxxxxxoptions02 = b4xxuo02bvxxxxxxxxxxoptions02;
		this.b5xxup02bvxxxxxxxxxxpurpose02 = b5xxup02bvxxxxxxxxxxpurpose02;
		this.b6xxuv02bvxxxxxxxxxxvalue02 = b6xxuv02bvxxxxxxxxxxvalue02;
		this.b7xxuo03bvxxxxxxxxxxoptions03 = b7xxuo03bvxxxxxxxxxxoptions03;
		this.b8xxup03bvxxxxxxxxxxpurpose03 = b8xxup03bvxxxxxxxxxxpurpose03;
		this.b9xxuv03bvxxxxxxxxxxvalue03 = b9xxuv03bvxxxxxxxxxxvalue03;
		this.c1xxuo04bvxxxxxxxxxxoptions04 = c1xxuo04bvxxxxxxxxxxoptions04;
		this.c2xxup04bvxxxxxxxxxxpurpose04 = c2xxup04bvxxxxxxxxxxpurpose04;
		this.c3xxuv04bvxxxxxxxxxxvalue04 = c3xxuv04bvxxxxxxxxxxvalue04;
		this.c4xxuo05bvxxxxxxxxxxoptions05 = c4xxuo05bvxxxxxxxxxxoptions05;
		this.c5xxup05bvxxxxxxxxxxpurpose05 = c5xxup05bvxxxxxxxxxxpurpose05;
		this.c6xxuv05bvxxxxxxxxxxvalue05 = c6xxuv05bvxxxxxxxxxxvalue05;
		this.c7xxuo06bvxxxxxxxxxxoptions06 = c7xxuo06bvxxxxxxxxxxoptions06;
		this.c8xxup06bvxxxxxxxxxxpurpose06 = c8xxup06bvxxxxxxxxxxpurpose06;
		this.c9xxuv06bvxxxxxxxxxxvalue06 = c9xxuv06bvxxxxxxxxxxvalue06;
		this.d1xxuo07bvxxxxxxxxxxoptions07 = d1xxuo07bvxxxxxxxxxxoptions07;
		this.d2xxup07bvxxxxxxxxxxpurpose07 = d2xxup07bvxxxxxxxxxxpurpose07;
		this.d3xxuv07bvxxxxxxxxxxvalue07 = d3xxuv07bvxxxxxxxxxxvalue07;
		this.d4xxuo08bvxxxxxxxxxxoptions08 = d4xxuo08bvxxxxxxxxxxoptions08;
		this.d5xxup08bvxxxxxxxxxxpurpose08 = d5xxup08bvxxxxxxxxxxpurpose08;
		this.d6xxuv08bvxxxxxxxxxxvalue08 = d6xxuv08bvxxxxxxxxxxvalue08;
		this.d7xxuo09bvxxxxxxxxxxoptions09 = d7xxuo09bvxxxxxxxxxxoptions09;
		this.d8xxup09bvxxxxxxxxxxpurpose09 = d8xxup09bvxxxxxxxxxxpurpose09;
		this.d9xxuv09bvxxxxxxxxxxvalue09 = d9xxuv09bvxxxxxxxxxxvalue09;
		this.e1xxuo10bvxxxxxxxxxxoptions10 = e1xxuo10bvxxxxxxxxxxoptions10;
		this.e2xxup10bvxxxxxxxxxxpurpose10 = e2xxup10bvxxxxxxxxxxpurpose10;
		this.e3xxuv10bvxxxxxxxxxxvalue10 = e3xxuv10bvxxxxxxxxxxvalue10;
		this.e4xxuo11bvxxxxxxxxxxoptions11 = e4xxuo11bvxxxxxxxxxxoptions11;
		this.e5xxup11bvxxxxxxxxxxpurpose11 = e5xxup11bvxxxxxxxxxxpurpose11;
		this.e6xxuv11bvxxxxxxxxxxvalue11 = e6xxuv11bvxxxxxxxxxxvalue11;
		this.e7xxuo12bvxxxxxxxxxxoptions12 = e7xxuo12bvxxxxxxxxxxoptions12;
		this.e8xxup12bvxxxxxxxxxxpurpose12 = e8xxup12bvxxxxxxxxxxpurpose12;
		this.e9xxuv12bvxxxxxxxxxxvalue12 = e9xxuv12bvxxxxxxxxxxvalue12;
		this.f1xxuo13bvxxxxxxxxxxoptions13 = f1xxuo13bvxxxxxxxxxxoptions13;
		this.f2xxup13bvxxxxxxxxxxpurpose13 = f2xxup13bvxxxxxxxxxxpurpose13;
		this.f3xxuv13bvxxxxxxxxxxvalue13 = f3xxuv13bvxxxxxxxxxxvalue13;
		this.f4xxuo14bvxxxxxxxxxxoptions14 = f4xxuo14bvxxxxxxxxxxoptions14;
		this.f5xxup14bvxxxxxxxxxxpurpose14 = f5xxup14bvxxxxxxxxxxpurpose14;
		this.f6xxuv14bvxxxxxxxxxxvalue14 = f6xxuv14bvxxxxxxxxxxvalue14;
		this.f7xxuo15bvxxxxxxxxxxoptions15 = f7xxuo15bvxxxxxxxxxxoptions15;
		this.f8xxup15bvxxxxxxxxxxpurpose15 = f8xxup15bvxxxxxxxxxxpurpose15;
		this.f9xxuv15bvxxxxxxxxxxvalue15 = f9xxuv15bvxxxxxxxxxxvalue15;
		this.g1xxuo16bvxxxxxxxxxxoptions16 = g1xxuo16bvxxxxxxxxxxoptions16;
		this.g2xxup16bvxxxxxxxxxxpurpose16 = g2xxup16bvxxxxxxxxxxpurpose16;
		this.g3xxuv16bvxxxxxxxxxxvalue16 = g3xxuv16bvxxxxxxxxxxvalue16;
		this.g4xxuo17bvxxxxxxxxxxoptions17 = g4xxuo17bvxxxxxxxxxxoptions17;
		this.g5xxup17bvxxxxxxxxxxpurpose17 = g5xxup17bvxxxxxxxxxxpurpose17;
		this.g6xxuv17bvxxxxxxxxxxvalue17 = g6xxuv17bvxxxxxxxxxxvalue17;
		this.g7xxuo18bvxxxxxxxxxxoptions18 = g7xxuo18bvxxxxxxxxxxoptions18;
		this.g8xxup18bvxxxxxxxxxxpurpose18 = g8xxup18bvxxxxxxxxxxpurpose18;
		this.g9xxuv18bvxxxxxxxxxxvalue18 = g9xxuv18bvxxxxxxxxxxvalue18;
		this.h1xxuo19bvxxxxxxxxxxoptions19 = h1xxuo19bvxxxxxxxxxxoptions19;
		this.h2xxup19bvxxxxxxxxxxpurpose19 = h2xxup19bvxxxxxxxxxxpurpose19;
		this.h3xxuv19bvxxxxxxxxxxvalue19 = h3xxuv19bvxxxxxxxxxxvalue19;
		this.h4xxuo20bvxxxxxxxxxxoptions20 = h4xxuo20bvxxxxxxxxxxoptions20;
		this.h5xxup20bvxxxxxxxxxxpurpose20 = h5xxup20bvxxxxxxxxxxpurpose20;
		this.h6xxuv20bvxxxxxxxxxxvalue20 = h6xxuv20bvxxxxxxxxxxvalue20;
		this.h7xxuo21bvxxxxxxxxxxoptions21 = h7xxuo21bvxxxxxxxxxxoptions21;
		this.h8xxup21bvxxxxxxxxxxpurpose21 = h8xxup21bvxxxxxxxxxxpurpose21;
		this.h9xxuv21bvxxxxxxxxxxvalue21 = h9xxuv21bvxxxxxxxxxxvalue21;
		this.i1xxuo22bvxxxxxxxxxxoptions22 = i1xxuo22bvxxxxxxxxxxoptions22;
		this.i2xxup22bvxxxxxxxxxxpurpose22 = i2xxup22bvxxxxxxxxxxpurpose22;
		this.i3xxuv22bvxxxxxxxxxxvalue22 = i3xxuv22bvxxxxxxxxxxvalue22;
		this.i4xxuo23bvxxxxxxxxxxoptions23 = i4xxuo23bvxxxxxxxxxxoptions23;
		this.i5xxup23bvxxxxxxxxxxpurpose23 = i5xxup23bvxxxxxxxxxxpurpose23;
		this.i6xxuv23bvxxxxxxxxxxvalue23 = i6xxuv23bvxxxxxxxxxxvalue23;
		this.i7xxuo24bvxxxxxxxxxxoptions24 = i7xxuo24bvxxxxxxxxxxoptions24;
		this.i8xxup24bvxxxxxxxxxxpurpose24 = i8xxup24bvxxxxxxxxxxpurpose24;
		this.i9xxuv24bvxxxxxxxxxxvalue24 = i9xxuv24bvxxxxxxxxxxvalue24;
		this.j1xxuo25bvxxxxxxxxxxoptions25 = j1xxuo25bvxxxxxxxxxxoptions25;
		this.j2xxup25bvxxxxxxxxxxpurpose25 = j2xxup25bvxxxxxxxxxxpurpose25;
		this.j3xxuv25bvxxxxxxxxxxvalue25 = j3xxuv25bvxxxxxxxxxxvalue25;
		this.j4xxuo26bvxxxxxxxxxxoptions26 = j4xxuo26bvxxxxxxxxxxoptions26;
		this.j5xxup26bvxxxxxxxxxxpurpose26 = j5xxup26bvxxxxxxxxxxpurpose26;
		this.j6xxuv26bvxxxxxxxxxxvalue26 = j6xxuv26bvxxxxxxxxxxvalue26;
		this.j7xxuo27bvxxxxxxxxxxoptions27 = j7xxuo27bvxxxxxxxxxxoptions27;
		this.j8xxup27bvxxxxxxxxxxpurpose27 = j8xxup27bvxxxxxxxxxxpurpose27;
		this.j9xxuv27bvxxxxxxxxxxvalue27 = j9xxuv27bvxxxxxxxxxxvalue27;
		this.k1xxuo28bvxxxxxxxxxxoptions28 = k1xxuo28bvxxxxxxxxxxoptions28;
		this.k2xxup28bvxxxxxxxxxxpurpose28 = k2xxup28bvxxxxxxxxxxpurpose28;
		this.k3xxuv28bvxxxxxxxxxxvalue28 = k3xxuv28bvxxxxxxxxxxvalue28;
		this.k4xxuo29bvxxxxxxxxxxoptions29 = k4xxuo29bvxxxxxxxxxxoptions29;
		this.k5xxup29bvxxxxxxxxxxpurpose29 = k5xxup29bvxxxxxxxxxxpurpose29;
		this.k6xxuv29bvxxxxxxxxxxvalue29 = k6xxuv29bvxxxxxxxxxxvalue29;
		this.k7xxuo30bvxxxxxxxxxxoptions30 = k7xxuo30bvxxxxxxxxxxoptions30;
		this.k8xxup30bvxxxxxxxxxxpurpose30 = k8xxup30bvxxxxxxxxxxpurpose30;
		this.k9xxuv30bvxxxxxxxxxxvalue30 = k9xxuv30bvxxxxxxxxxxvalue30;
		this.l1xxuo31bvxxxxxxxxxxoptions31 = l1xxuo31bvxxxxxxxxxxoptions31;
		this.l2xxup31bvxxxxxxxxxxpurpose31 = l2xxup31bvxxxxxxxxxxpurpose31;
		this.l3xxuv31bvxxxxxxxxxxvalue31 = l3xxuv31bvxxxxxxxxxxvalue31;
		this.l4xxuo32bvxxxxxxxxxxoptions32 = l4xxuo32bvxxxxxxxxxxoptions32;
		this.l5xxup32bvxxxxxxxxxxpurpose32 = l5xxup32bvxxxxxxxxxxpurpose32;
		this.l6xxuv32bvxxxxxxxxxxvalue32 = l6xxuv32bvxxxxxxxxxxvalue32;
		this.l7xxuo33bvxxxxxxxxxxoptions33 = l7xxuo33bvxxxxxxxxxxoptions33;
		this.l8xxup33bvxxxxxxxxxxpurpose33 = l8xxup33bvxxxxxxxxxxpurpose33;
		this.l9xxuv33bvxxxxxxxxxxvalue33 = l9xxuv33bvxxxxxxxxxxvalue33;
		this.m1xxuo34bvxxxxxxxxxxoptions34 = m1xxuo34bvxxxxxxxxxxoptions34;
		this.m2xxup34bvxxxxxxxxxxpurpose34 = m2xxup34bvxxxxxxxxxxpurpose34;
		this.m3xxuv34bvxxxxxxxxxxvalue34 = m3xxuv34bvxxxxxxxxxxvalue34;
		this.m4xxuo35bvxxxxxxxxxxoptions35 = m4xxuo35bvxxxxxxxxxxoptions35;
		this.m5xxup35bvxxxxxxxxxxpurpose35 = m5xxup35bvxxxxxxxxxxpurpose35;
		this.m6xxuv35bvxxxxxxxxxxvalue35 = m6xxuv35bvxxxxxxxxxxvalue35;
		this.m7xxuo36bvxxxxxxxxxxoptions36 = m7xxuo36bvxxxxxxxxxxoptions36;
		this.m8xxup36bvxxxxxxxxxxpurpose36 = m8xxup36bvxxxxxxxxxxpurpose36;
		this.m9xxuv36bvxxxxxxxxxxvalue36 = m9xxuv36bvxxxxxxxxxxvalue36;
		this.n1xxuo37bvxxxxxxxxxxoptions37 = n1xxuo37bvxxxxxxxxxxoptions37;
		this.n2xxup37bvxxxxxxxxxxpurpose37 = n2xxup37bvxxxxxxxxxxpurpose37;
		this.n3xxuv37bvxxxxxxxxxxvalue37 = n3xxuv37bvxxxxxxxxxxvalue37;
		this.n4xxuo38bvxxxxxxxxxxoptions38 = n4xxuo38bvxxxxxxxxxxoptions38;
		this.n5xxup38bvxxxxxxxxxxpurpose38 = n5xxup38bvxxxxxxxxxxpurpose38;
		this.n6xxuv38bvxxxxxxxxxxvalue38 = n6xxuv38bvxxxxxxxxxxvalue38;
		this.n7xxuo39bvxxxxxxxxxxoptions39 = n7xxuo39bvxxxxxxxxxxoptions39;
		this.n8xxup39bvxxxxxxxxxxpurpose39 = n8xxup39bvxxxxxxxxxxpurpose39;
		this.n9xxuv39bvxxxxxxxxxxvalue39 = n9xxuv39bvxxxxxxxxxxvalue39;
		this.o1xxuo40bvxxxxxxxxxxoptions40 = o1xxuo40bvxxxxxxxxxxoptions40;
		this.o2xxup40bvxxxxxxxxxxpurpose40 = o2xxup40bvxxxxxxxxxxpurpose40;
		this.o3xxuv40bvxxxxxxxxxxvalue40 = o3xxuv40bvxxxxxxxxxxvalue40;
		this.o4xxuo41bvxxxxxxxxxxoptions41 = o4xxuo41bvxxxxxxxxxxoptions41;
		this.o5xxup41bvxxxxxxxxxxpurpose41 = o5xxup41bvxxxxxxxxxxpurpose41;
		this.o6xxuv41bvxxxxxxxxxxvalue41 = o6xxuv41bvxxxxxxxxxxvalue41;
		this.o7xxuo42bvxxxxxxxxxxoptions42 = o7xxuo42bvxxxxxxxxxxoptions42;
		this.o8xxup42bvxxxxxxxxxxpurpose42 = o8xxup42bvxxxxxxxxxxpurpose42;
		this.o9xxuv42bvxxxxxxxxxxvalue42 = o9xxuv42bvxxxxxxxxxxvalue42;
		this.p1xxuo43bvxxxxxxxxxxoptions43 = p1xxuo43bvxxxxxxxxxxoptions43;
		this.p2xxup43bvxxxxxxxxxxpurpose43 = p2xxup43bvxxxxxxxxxxpurpose43;
		this.p3xxuv43bvxxxxxxxxxxvalue43 = p3xxuv43bvxxxxxxxxxxvalue43;
		this.p4xxuo44bvxxxxxxxxxxoptions44 = p4xxuo44bvxxxxxxxxxxoptions44;
		this.p5xxup44bvxxxxxxxxxxpurpose44 = p5xxup44bvxxxxxxxxxxpurpose44;
		this.p6xxuv44bvxxxxxxxxxxvalue44 = p6xxuv44bvxxxxxxxxxxvalue44;
		this.p7xxuo45bvxxxxxxxxxxoptions45 = p7xxuo45bvxxxxxxxxxxoptions45;
		this.p8xxup45bvxxxxxxxxxxpurpose45 = p8xxup45bvxxxxxxxxxxpurpose45;
		this.p9xxuv45bvxxxxxxxxxxvalue45 = p9xxuv45bvxxxxxxxxxxvalue45;
		this.q1xxuo46bvxxxxxxxxxxoptions46 = q1xxuo46bvxxxxxxxxxxoptions46;
		this.q2xxup46bvxxxxxxxxxxpurpose46 = q2xxup46bvxxxxxxxxxxpurpose46;
		this.q3xxuv46bvxxxxxxxxxxvalue46 = q3xxuv46bvxxxxxxxxxxvalue46;
		this.q4xxuo47bvxxxxxxxxxxoptions47 = q4xxuo47bvxxxxxxxxxxoptions47;
		this.q5xxup47bvxxxxxxxxxxpurpose47 = q5xxup47bvxxxxxxxxxxpurpose47;
		this.q6xxuv47bvxxxxxxxxxxvalue47 = q6xxuv47bvxxxxxxxxxxvalue47;
		this.q7xxuo48bvxxxxxxxxxxoptions48 = q7xxuo48bvxxxxxxxxxxoptions48;
		this.q8xxup48bvxxxxxxxxxxpurpose48 = q8xxup48bvxxxxxxxxxxpurpose48;
		this.q9xxuv48bvxxxxxxxxxxvalue48 = q9xxuv48bvxxxxxxxxxxvalue48;
		this.r1xxuo49bvxxxxxxxxxxoptions49 = r1xxuo49bvxxxxxxxxxxoptions49;
		this.r2xxup49bvxxxxxxxxxxpurpose49 = r2xxup49bvxxxxxxxxxxpurpose49;
		this.r3xxuv49bvxxxxxxxxxxvalue49 = r3xxuv49bvxxxxxxxxxxvalue49;
		this.r4xxuo50bvxxxxxxxxxxoptions50 = r4xxuo50bvxxxxxxxxxxoptions50;
		this.r5xxup50bvxxxxxxxxxxpurpose50 = r5xxup50bvxxxxxxxxxxpurpose50;
		this.r6xxuv50bvxxxxxxxxxxvalue50 = r6xxuv50bvxxxxxxxxxxvalue50;
		this.r7xxuo51bvxxxxxxxxxxoptions51 = r7xxuo51bvxxxxxxxxxxoptions51;
		this.r8xxup51bvxxxxxxxxxxpurpose51 = r8xxup51bvxxxxxxxxxxpurpose51;
		this.r9xxuv51bvxxxxxxxxxxvalue51 = r9xxuv51bvxxxxxxxxxxvalue51;
		this.s1xxuo52bvxxxxxxxxxxoptions52 = s1xxuo52bvxxxxxxxxxxoptions52;
		this.s2xxup52bvxxxxxxxxxxpurpose52 = s2xxup52bvxxxxxxxxxxpurpose52;
		this.s3xxuv52bvxxxxxxxxxxvalue52 = s3xxuv52bvxxxxxxxxxxvalue52;
		this.s4xxuo53bvxxxxxxxxxxoptions53 = s4xxuo53bvxxxxxxxxxxoptions53;
		this.s5xxup53bvxxxxxxxxxxpurpose53 = s5xxup53bvxxxxxxxxxxpurpose53;
		this.s6xxuv53bvxxxxxxxxxxvalue53 = s6xxuv53bvxxxxxxxxxxvalue53;
		this.s7xxuo54bvxxxxxxxxxxoptions54 = s7xxuo54bvxxxxxxxxxxoptions54;
		this.s8xxup54bvxxxxxxxxxxpurpose54 = s8xxup54bvxxxxxxxxxxpurpose54;
		this.s9xxuv54bvxxxxxxxxxxvalue54 = s9xxuv54bvxxxxxxxxxxvalue54;
		this.t1xxuo55bvxxxxxxxxxxoptions55 = t1xxuo55bvxxxxxxxxxxoptions55;
		this.t2xxup55bvxxxxxxxxxxpurpose55 = t2xxup55bvxxxxxxxxxxpurpose55;
		this.t3xxuv55bvxxxxxxxxxxvalue55 = t3xxuv55bvxxxxxxxxxxvalue55;
		this.t4xxuo56bvxxxxxxxxxxoptions56 = t4xxuo56bvxxxxxxxxxxoptions56;
		this.t5xxup56bvxxxxxxxxxxpurpose56 = t5xxup56bvxxxxxxxxxxpurpose56;
		this.t6xxuv56bvxxxxxxxxxxvalue56 = t6xxuv56bvxxxxxxxxxxvalue56;
		this.t7xxuo57bvxxxxxxxxxxoptions57 = t7xxuo57bvxxxxxxxxxxoptions57;
		this.t8xxup57bvxxxxxxxxxxpurpose57 = t8xxup57bvxxxxxxxxxxpurpose57;
		this.t9xxuv57bvxxxxxxxxxxvalue57 = t9xxuv57bvxxxxxxxxxxvalue57;
		this.u1xxuo58bvxxxxxxxxxxoptions58 = u1xxuo58bvxxxxxxxxxxoptions58;
		this.u2xxup58bvxxxxxxxxxxpurpose58 = u2xxup58bvxxxxxxxxxxpurpose58;
		this.u3xxuv58bvxxxxxxxxxxvalue58 = u3xxuv58bvxxxxxxxxxxvalue58;
		this.u4xxuo59bvxxxxxxxxxxoptions59 = u4xxuo59bvxxxxxxxxxxoptions59;
		this.u5xxup59bvxxxxxxxxxxpurpose59 = u5xxup59bvxxxxxxxxxxpurpose59;
		this.u6xxuv59bvxxxxxxxxxxvalue59 = u6xxuv59bvxxxxxxxxxxvalue59;
		this.u7xxuo60bvxxxxxxxxxxoptions60 = u7xxuo60bvxxxxxxxxxxoptions60;
		this.u8xxup60bvxxxxxxxxxxpurpose60 = u8xxup60bvxxxxxxxxxxpurpose60;
		this.u9xxuv60bvxxxxxxxxxxvalue60 = u9xxuv60bvxxxxxxxxxxvalue60;
		this.v1xxuo61bvxxxxxxxxxxoptions61 = v1xxuo61bvxxxxxxxxxxoptions61;
		this.v2xxup61bvxxxxxxxxxxpurpose61 = v2xxup61bvxxxxxxxxxxpurpose61;
		this.v3xxuv61bvxxxxxxxxxxvalue61 = v3xxuv61bvxxxxxxxxxxvalue61;
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
		this.y9xxuznxbvxxxxxxxxxxnotes = y9xxuznxbvxxxxxxxxxxnotes;
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@Column(name = "row", nullable = false, length = 2)
	@NotNull
	@Size(max = 2)
	public String getA0xxukcxbvxxxxxxxxxxrow() {
		return this.a0xxukcxbvxxxxxxxxxxrow;
	}

	public void setA0xxukcxbvxxxxxxxxxxrow(String a0xxukcxbvxxxxxxxxxxrow) {
		this.a0xxukcxbvxxxxxxxxxxrow = a0xxukcxbvxxxxxxxxxxrow;
	}

	@Column(name = "options01", length = 159)
	@Size(max = 159)
	public String getB1xxuo01bvxxxxxxxxxxoptions01() {
		return this.b1xxuo01bvxxxxxxxxxxoptions01;
	}

	public void setB1xxuo01bvxxxxxxxxxxoptions01(
			String b1xxuo01bvxxxxxxxxxxoptions01) {
		this.b1xxuo01bvxxxxxxxxxxoptions01 = b1xxuo01bvxxxxxxxxxxoptions01;
	}

	@Column(name = "purpose01", length = 159)
	@Size(max = 159)
	public String getB2xxup01bvxxxxxxxxxxpurpose01() {
		return this.b2xxup01bvxxxxxxxxxxpurpose01;
	}

	public void setB2xxup01bvxxxxxxxxxxpurpose01(
			String b2xxup01bvxxxxxxxxxxpurpose01) {
		this.b2xxup01bvxxxxxxxxxxpurpose01 = b2xxup01bvxxxxxxxxxxpurpose01;
	}

	@Column(name = "value01", length = 159)
	@Size(max = 159)
	public String getB3xxuv01bvxxxxxxxxxxvalue01() {
		return this.b3xxuv01bvxxxxxxxxxxvalue01;
	}

	public void setB3xxuv01bvxxxxxxxxxxvalue01(
			String b3xxuv01bvxxxxxxxxxxvalue01) {
		this.b3xxuv01bvxxxxxxxxxxvalue01 = b3xxuv01bvxxxxxxxxxxvalue01;
	}

	@Column(name = "options02", length = 159)
	@Size(max = 159)
	public String getB4xxuo02bvxxxxxxxxxxoptions02() {
		return this.b4xxuo02bvxxxxxxxxxxoptions02;
	}

	public void setB4xxuo02bvxxxxxxxxxxoptions02(
			String b4xxuo02bvxxxxxxxxxxoptions02) {
		this.b4xxuo02bvxxxxxxxxxxoptions02 = b4xxuo02bvxxxxxxxxxxoptions02;
	}

	@Column(name = "purpose02", length = 159)
	@Size(max = 159)
	public String getB5xxup02bvxxxxxxxxxxpurpose02() {
		return this.b5xxup02bvxxxxxxxxxxpurpose02;
	}

	public void setB5xxup02bvxxxxxxxxxxpurpose02(
			String b5xxup02bvxxxxxxxxxxpurpose02) {
		this.b5xxup02bvxxxxxxxxxxpurpose02 = b5xxup02bvxxxxxxxxxxpurpose02;
	}

	@Column(name = "value02", length = 159)
	@Size(max = 159)
	public String getB6xxuv02bvxxxxxxxxxxvalue02() {
		return this.b6xxuv02bvxxxxxxxxxxvalue02;
	}

	public void setB6xxuv02bvxxxxxxxxxxvalue02(
			String b6xxuv02bvxxxxxxxxxxvalue02) {
		this.b6xxuv02bvxxxxxxxxxxvalue02 = b6xxuv02bvxxxxxxxxxxvalue02;
	}

	@Column(name = "options03", length = 159)
	@Size(max = 159)
	public String getB7xxuo03bvxxxxxxxxxxoptions03() {
		return this.b7xxuo03bvxxxxxxxxxxoptions03;
	}

	public void setB7xxuo03bvxxxxxxxxxxoptions03(
			String b7xxuo03bvxxxxxxxxxxoptions03) {
		this.b7xxuo03bvxxxxxxxxxxoptions03 = b7xxuo03bvxxxxxxxxxxoptions03;
	}

	@Column(name = "purpose03", length = 159)
	@Size(max = 159)
	public String getB8xxup03bvxxxxxxxxxxpurpose03() {
		return this.b8xxup03bvxxxxxxxxxxpurpose03;
	}

	public void setB8xxup03bvxxxxxxxxxxpurpose03(
			String b8xxup03bvxxxxxxxxxxpurpose03) {
		this.b8xxup03bvxxxxxxxxxxpurpose03 = b8xxup03bvxxxxxxxxxxpurpose03;
	}

	@Column(name = "value03", length = 159)
	@Size(max = 159)
	public String getB9xxuv03bvxxxxxxxxxxvalue03() {
		return this.b9xxuv03bvxxxxxxxxxxvalue03;
	}

	public void setB9xxuv03bvxxxxxxxxxxvalue03(
			String b9xxuv03bvxxxxxxxxxxvalue03) {
		this.b9xxuv03bvxxxxxxxxxxvalue03 = b9xxuv03bvxxxxxxxxxxvalue03;
	}

	@Column(name = "options04", length = 159)
	@Size(max = 159)
	public String getC1xxuo04bvxxxxxxxxxxoptions04() {
		return this.c1xxuo04bvxxxxxxxxxxoptions04;
	}

	public void setC1xxuo04bvxxxxxxxxxxoptions04(
			String c1xxuo04bvxxxxxxxxxxoptions04) {
		this.c1xxuo04bvxxxxxxxxxxoptions04 = c1xxuo04bvxxxxxxxxxxoptions04;
	}

	@Column(name = "purpose04", length = 159)
	@Size(max = 159)
	public String getC2xxup04bvxxxxxxxxxxpurpose04() {
		return this.c2xxup04bvxxxxxxxxxxpurpose04;
	}

	public void setC2xxup04bvxxxxxxxxxxpurpose04(
			String c2xxup04bvxxxxxxxxxxpurpose04) {
		this.c2xxup04bvxxxxxxxxxxpurpose04 = c2xxup04bvxxxxxxxxxxpurpose04;
	}

	@Column(name = "value04", length = 159)
	@Size(max = 159)
	public String getC3xxuv04bvxxxxxxxxxxvalue04() {
		return this.c3xxuv04bvxxxxxxxxxxvalue04;
	}

	public void setC3xxuv04bvxxxxxxxxxxvalue04(
			String c3xxuv04bvxxxxxxxxxxvalue04) {
		this.c3xxuv04bvxxxxxxxxxxvalue04 = c3xxuv04bvxxxxxxxxxxvalue04;
	}

	@Column(name = "options05", length = 159)
	@Size(max = 159)
	public String getC4xxuo05bvxxxxxxxxxxoptions05() {
		return this.c4xxuo05bvxxxxxxxxxxoptions05;
	}

	public void setC4xxuo05bvxxxxxxxxxxoptions05(
			String c4xxuo05bvxxxxxxxxxxoptions05) {
		this.c4xxuo05bvxxxxxxxxxxoptions05 = c4xxuo05bvxxxxxxxxxxoptions05;
	}

	@Column(name = "purpose05", length = 159)
	@Size(max = 159)
	public String getC5xxup05bvxxxxxxxxxxpurpose05() {
		return this.c5xxup05bvxxxxxxxxxxpurpose05;
	}

	public void setC5xxup05bvxxxxxxxxxxpurpose05(
			String c5xxup05bvxxxxxxxxxxpurpose05) {
		this.c5xxup05bvxxxxxxxxxxpurpose05 = c5xxup05bvxxxxxxxxxxpurpose05;
	}

	@Column(name = "value05", length = 159)
	@Size(max = 159)
	public String getC6xxuv05bvxxxxxxxxxxvalue05() {
		return this.c6xxuv05bvxxxxxxxxxxvalue05;
	}

	public void setC6xxuv05bvxxxxxxxxxxvalue05(
			String c6xxuv05bvxxxxxxxxxxvalue05) {
		this.c6xxuv05bvxxxxxxxxxxvalue05 = c6xxuv05bvxxxxxxxxxxvalue05;
	}

	@Column(name = "options06", length = 159)
	@Size(max = 159)
	public String getC7xxuo06bvxxxxxxxxxxoptions06() {
		return this.c7xxuo06bvxxxxxxxxxxoptions06;
	}

	public void setC7xxuo06bvxxxxxxxxxxoptions06(
			String c7xxuo06bvxxxxxxxxxxoptions06) {
		this.c7xxuo06bvxxxxxxxxxxoptions06 = c7xxuo06bvxxxxxxxxxxoptions06;
	}

	@Column(name = "purpose06", length = 159)
	@Size(max = 159)
	public String getC8xxup06bvxxxxxxxxxxpurpose06() {
		return this.c8xxup06bvxxxxxxxxxxpurpose06;
	}

	public void setC8xxup06bvxxxxxxxxxxpurpose06(
			String c8xxup06bvxxxxxxxxxxpurpose06) {
		this.c8xxup06bvxxxxxxxxxxpurpose06 = c8xxup06bvxxxxxxxxxxpurpose06;
	}

	@Column(name = "value06", length = 159)
	@Size(max = 159)
	public String getC9xxuv06bvxxxxxxxxxxvalue06() {
		return this.c9xxuv06bvxxxxxxxxxxvalue06;
	}

	public void setC9xxuv06bvxxxxxxxxxxvalue06(
			String c9xxuv06bvxxxxxxxxxxvalue06) {
		this.c9xxuv06bvxxxxxxxxxxvalue06 = c9xxuv06bvxxxxxxxxxxvalue06;
	}

	@Column(name = "options07", length = 159)
	@Size(max = 159)
	public String getD1xxuo07bvxxxxxxxxxxoptions07() {
		return this.d1xxuo07bvxxxxxxxxxxoptions07;
	}

	public void setD1xxuo07bvxxxxxxxxxxoptions07(
			String d1xxuo07bvxxxxxxxxxxoptions07) {
		this.d1xxuo07bvxxxxxxxxxxoptions07 = d1xxuo07bvxxxxxxxxxxoptions07;
	}

	@Column(name = "purpose07", length = 159)
	@Size(max = 159)
	public String getD2xxup07bvxxxxxxxxxxpurpose07() {
		return this.d2xxup07bvxxxxxxxxxxpurpose07;
	}

	public void setD2xxup07bvxxxxxxxxxxpurpose07(
			String d2xxup07bvxxxxxxxxxxpurpose07) {
		this.d2xxup07bvxxxxxxxxxxpurpose07 = d2xxup07bvxxxxxxxxxxpurpose07;
	}

	@Column(name = "value07", length = 159)
	@Size(max = 159)
	public String getD3xxuv07bvxxxxxxxxxxvalue07() {
		return this.d3xxuv07bvxxxxxxxxxxvalue07;
	}

	public void setD3xxuv07bvxxxxxxxxxxvalue07(
			String d3xxuv07bvxxxxxxxxxxvalue07) {
		this.d3xxuv07bvxxxxxxxxxxvalue07 = d3xxuv07bvxxxxxxxxxxvalue07;
	}

	@Column(name = "options08", length = 159)
	@Size(max = 159)
	public String getD4xxuo08bvxxxxxxxxxxoptions08() {
		return this.d4xxuo08bvxxxxxxxxxxoptions08;
	}

	public void setD4xxuo08bvxxxxxxxxxxoptions08(
			String d4xxuo08bvxxxxxxxxxxoptions08) {
		this.d4xxuo08bvxxxxxxxxxxoptions08 = d4xxuo08bvxxxxxxxxxxoptions08;
	}

	@Column(name = "purpose08", length = 159)
	@Size(max = 159)
	public String getD5xxup08bvxxxxxxxxxxpurpose08() {
		return this.d5xxup08bvxxxxxxxxxxpurpose08;
	}

	public void setD5xxup08bvxxxxxxxxxxpurpose08(
			String d5xxup08bvxxxxxxxxxxpurpose08) {
		this.d5xxup08bvxxxxxxxxxxpurpose08 = d5xxup08bvxxxxxxxxxxpurpose08;
	}

	@Column(name = "value08", length = 159)
	@Size(max = 159)
	public String getD6xxuv08bvxxxxxxxxxxvalue08() {
		return this.d6xxuv08bvxxxxxxxxxxvalue08;
	}

	public void setD6xxuv08bvxxxxxxxxxxvalue08(
			String d6xxuv08bvxxxxxxxxxxvalue08) {
		this.d6xxuv08bvxxxxxxxxxxvalue08 = d6xxuv08bvxxxxxxxxxxvalue08;
	}

	@Column(name = "options09", length = 159)
	@Size(max = 159)
	public String getD7xxuo09bvxxxxxxxxxxoptions09() {
		return this.d7xxuo09bvxxxxxxxxxxoptions09;
	}

	public void setD7xxuo09bvxxxxxxxxxxoptions09(
			String d7xxuo09bvxxxxxxxxxxoptions09) {
		this.d7xxuo09bvxxxxxxxxxxoptions09 = d7xxuo09bvxxxxxxxxxxoptions09;
	}

	@Column(name = "purpose09", length = 159)
	@Size(max = 159)
	public String getD8xxup09bvxxxxxxxxxxpurpose09() {
		return this.d8xxup09bvxxxxxxxxxxpurpose09;
	}

	public void setD8xxup09bvxxxxxxxxxxpurpose09(
			String d8xxup09bvxxxxxxxxxxpurpose09) {
		this.d8xxup09bvxxxxxxxxxxpurpose09 = d8xxup09bvxxxxxxxxxxpurpose09;
	}

	@Column(name = "value09", length = 159)
	@Size(max = 159)
	public String getD9xxuv09bvxxxxxxxxxxvalue09() {
		return this.d9xxuv09bvxxxxxxxxxxvalue09;
	}

	public void setD9xxuv09bvxxxxxxxxxxvalue09(
			String d9xxuv09bvxxxxxxxxxxvalue09) {
		this.d9xxuv09bvxxxxxxxxxxvalue09 = d9xxuv09bvxxxxxxxxxxvalue09;
	}

	@Column(name = "options10", length = 159)
	@Size(max = 159)
	public String getE1xxuo10bvxxxxxxxxxxoptions10() {
		return this.e1xxuo10bvxxxxxxxxxxoptions10;
	}

	public void setE1xxuo10bvxxxxxxxxxxoptions10(
			String e1xxuo10bvxxxxxxxxxxoptions10) {
		this.e1xxuo10bvxxxxxxxxxxoptions10 = e1xxuo10bvxxxxxxxxxxoptions10;
	}

	@Column(name = "purpose10", length = 159)
	@Size(max = 159)
	public String getE2xxup10bvxxxxxxxxxxpurpose10() {
		return this.e2xxup10bvxxxxxxxxxxpurpose10;
	}

	public void setE2xxup10bvxxxxxxxxxxpurpose10(
			String e2xxup10bvxxxxxxxxxxpurpose10) {
		this.e2xxup10bvxxxxxxxxxxpurpose10 = e2xxup10bvxxxxxxxxxxpurpose10;
	}

	@Column(name = "value10", length = 159)
	@Size(max = 159)
	public String getE3xxuv10bvxxxxxxxxxxvalue10() {
		return this.e3xxuv10bvxxxxxxxxxxvalue10;
	}

	public void setE3xxuv10bvxxxxxxxxxxvalue10(
			String e3xxuv10bvxxxxxxxxxxvalue10) {
		this.e3xxuv10bvxxxxxxxxxxvalue10 = e3xxuv10bvxxxxxxxxxxvalue10;
	}

	@Column(name = "options11", length = 159)
	@Size(max = 159)
	public String getE4xxuo11bvxxxxxxxxxxoptions11() {
		return this.e4xxuo11bvxxxxxxxxxxoptions11;
	}

	public void setE4xxuo11bvxxxxxxxxxxoptions11(
			String e4xxuo11bvxxxxxxxxxxoptions11) {
		this.e4xxuo11bvxxxxxxxxxxoptions11 = e4xxuo11bvxxxxxxxxxxoptions11;
	}

	@Column(name = "purpose11", length = 159)
	@Size(max = 159)
	public String getE5xxup11bvxxxxxxxxxxpurpose11() {
		return this.e5xxup11bvxxxxxxxxxxpurpose11;
	}

	public void setE5xxup11bvxxxxxxxxxxpurpose11(
			String e5xxup11bvxxxxxxxxxxpurpose11) {
		this.e5xxup11bvxxxxxxxxxxpurpose11 = e5xxup11bvxxxxxxxxxxpurpose11;
	}

	@Column(name = "value11", length = 159)
	@Size(max = 159)
	public String getE6xxuv11bvxxxxxxxxxxvalue11() {
		return this.e6xxuv11bvxxxxxxxxxxvalue11;
	}

	public void setE6xxuv11bvxxxxxxxxxxvalue11(
			String e6xxuv11bvxxxxxxxxxxvalue11) {
		this.e6xxuv11bvxxxxxxxxxxvalue11 = e6xxuv11bvxxxxxxxxxxvalue11;
	}

	@Column(name = "options12", length = 159)
	@Size(max = 159)
	public String getE7xxuo12bvxxxxxxxxxxoptions12() {
		return this.e7xxuo12bvxxxxxxxxxxoptions12;
	}

	public void setE7xxuo12bvxxxxxxxxxxoptions12(
			String e7xxuo12bvxxxxxxxxxxoptions12) {
		this.e7xxuo12bvxxxxxxxxxxoptions12 = e7xxuo12bvxxxxxxxxxxoptions12;
	}

	@Column(name = "purpose12", length = 159)
	@Size(max = 159)
	public String getE8xxup12bvxxxxxxxxxxpurpose12() {
		return this.e8xxup12bvxxxxxxxxxxpurpose12;
	}

	public void setE8xxup12bvxxxxxxxxxxpurpose12(
			String e8xxup12bvxxxxxxxxxxpurpose12) {
		this.e8xxup12bvxxxxxxxxxxpurpose12 = e8xxup12bvxxxxxxxxxxpurpose12;
	}

	@Column(name = "value12", length = 159)
	@Size(max = 159)
	public String getE9xxuv12bvxxxxxxxxxxvalue12() {
		return this.e9xxuv12bvxxxxxxxxxxvalue12;
	}

	public void setE9xxuv12bvxxxxxxxxxxvalue12(
			String e9xxuv12bvxxxxxxxxxxvalue12) {
		this.e9xxuv12bvxxxxxxxxxxvalue12 = e9xxuv12bvxxxxxxxxxxvalue12;
	}

	@Column(name = "options13", length = 159)
	@Size(max = 159)
	public String getF1xxuo13bvxxxxxxxxxxoptions13() {
		return this.f1xxuo13bvxxxxxxxxxxoptions13;
	}

	public void setF1xxuo13bvxxxxxxxxxxoptions13(
			String f1xxuo13bvxxxxxxxxxxoptions13) {
		this.f1xxuo13bvxxxxxxxxxxoptions13 = f1xxuo13bvxxxxxxxxxxoptions13;
	}

	@Column(name = "purpose13", length = 159)
	@Size(max = 159)
	public String getF2xxup13bvxxxxxxxxxxpurpose13() {
		return this.f2xxup13bvxxxxxxxxxxpurpose13;
	}

	public void setF2xxup13bvxxxxxxxxxxpurpose13(
			String f2xxup13bvxxxxxxxxxxpurpose13) {
		this.f2xxup13bvxxxxxxxxxxpurpose13 = f2xxup13bvxxxxxxxxxxpurpose13;
	}

	@Column(name = "value13", length = 159)
	@Size(max = 159)
	public String getF3xxuv13bvxxxxxxxxxxvalue13() {
		return this.f3xxuv13bvxxxxxxxxxxvalue13;
	}

	public void setF3xxuv13bvxxxxxxxxxxvalue13(
			String f3xxuv13bvxxxxxxxxxxvalue13) {
		this.f3xxuv13bvxxxxxxxxxxvalue13 = f3xxuv13bvxxxxxxxxxxvalue13;
	}

	@Column(name = "options14", length = 159)
	@Size(max = 159)
	public String getF4xxuo14bvxxxxxxxxxxoptions14() {
		return this.f4xxuo14bvxxxxxxxxxxoptions14;
	}

	public void setF4xxuo14bvxxxxxxxxxxoptions14(
			String f4xxuo14bvxxxxxxxxxxoptions14) {
		this.f4xxuo14bvxxxxxxxxxxoptions14 = f4xxuo14bvxxxxxxxxxxoptions14;
	}

	@Column(name = "purpose14", length = 159)
	@Size(max = 159)
	public String getF5xxup14bvxxxxxxxxxxpurpose14() {
		return this.f5xxup14bvxxxxxxxxxxpurpose14;
	}

	public void setF5xxup14bvxxxxxxxxxxpurpose14(
			String f5xxup14bvxxxxxxxxxxpurpose14) {
		this.f5xxup14bvxxxxxxxxxxpurpose14 = f5xxup14bvxxxxxxxxxxpurpose14;
	}

	@Column(name = "value14", length = 159)
	@Size(max = 159)
	public String getF6xxuv14bvxxxxxxxxxxvalue14() {
		return this.f6xxuv14bvxxxxxxxxxxvalue14;
	}

	public void setF6xxuv14bvxxxxxxxxxxvalue14(
			String f6xxuv14bvxxxxxxxxxxvalue14) {
		this.f6xxuv14bvxxxxxxxxxxvalue14 = f6xxuv14bvxxxxxxxxxxvalue14;
	}

	@Column(name = "options15", length = 159)
	@Size(max = 159)
	public String getF7xxuo15bvxxxxxxxxxxoptions15() {
		return this.f7xxuo15bvxxxxxxxxxxoptions15;
	}

	public void setF7xxuo15bvxxxxxxxxxxoptions15(
			String f7xxuo15bvxxxxxxxxxxoptions15) {
		this.f7xxuo15bvxxxxxxxxxxoptions15 = f7xxuo15bvxxxxxxxxxxoptions15;
	}

	@Column(name = "purpose15", length = 159)
	@Size(max = 159)
	public String getF8xxup15bvxxxxxxxxxxpurpose15() {
		return this.f8xxup15bvxxxxxxxxxxpurpose15;
	}

	public void setF8xxup15bvxxxxxxxxxxpurpose15(
			String f8xxup15bvxxxxxxxxxxpurpose15) {
		this.f8xxup15bvxxxxxxxxxxpurpose15 = f8xxup15bvxxxxxxxxxxpurpose15;
	}

	@Column(name = "value15", length = 159)
	@Size(max = 159)
	public String getF9xxuv15bvxxxxxxxxxxvalue15() {
		return this.f9xxuv15bvxxxxxxxxxxvalue15;
	}

	public void setF9xxuv15bvxxxxxxxxxxvalue15(
			String f9xxuv15bvxxxxxxxxxxvalue15) {
		this.f9xxuv15bvxxxxxxxxxxvalue15 = f9xxuv15bvxxxxxxxxxxvalue15;
	}

	@Column(name = "options16", length = 159)
	@Size(max = 159)
	public String getG1xxuo16bvxxxxxxxxxxoptions16() {
		return this.g1xxuo16bvxxxxxxxxxxoptions16;
	}

	public void setG1xxuo16bvxxxxxxxxxxoptions16(
			String g1xxuo16bvxxxxxxxxxxoptions16) {
		this.g1xxuo16bvxxxxxxxxxxoptions16 = g1xxuo16bvxxxxxxxxxxoptions16;
	}

	@Column(name = "purpose16", length = 159)
	@Size(max = 159)
	public String getG2xxup16bvxxxxxxxxxxpurpose16() {
		return this.g2xxup16bvxxxxxxxxxxpurpose16;
	}

	public void setG2xxup16bvxxxxxxxxxxpurpose16(
			String g2xxup16bvxxxxxxxxxxpurpose16) {
		this.g2xxup16bvxxxxxxxxxxpurpose16 = g2xxup16bvxxxxxxxxxxpurpose16;
	}

	@Column(name = "value16", length = 159)
	@Size(max = 159)
	public String getG3xxuv16bvxxxxxxxxxxvalue16() {
		return this.g3xxuv16bvxxxxxxxxxxvalue16;
	}

	public void setG3xxuv16bvxxxxxxxxxxvalue16(
			String g3xxuv16bvxxxxxxxxxxvalue16) {
		this.g3xxuv16bvxxxxxxxxxxvalue16 = g3xxuv16bvxxxxxxxxxxvalue16;
	}

	@Column(name = "options17", length = 159)
	@Size(max = 159)
	public String getG4xxuo17bvxxxxxxxxxxoptions17() {
		return this.g4xxuo17bvxxxxxxxxxxoptions17;
	}

	public void setG4xxuo17bvxxxxxxxxxxoptions17(
			String g4xxuo17bvxxxxxxxxxxoptions17) {
		this.g4xxuo17bvxxxxxxxxxxoptions17 = g4xxuo17bvxxxxxxxxxxoptions17;
	}

	@Column(name = "purpose17", length = 159)
	@Size(max = 159)
	public String getG5xxup17bvxxxxxxxxxxpurpose17() {
		return this.g5xxup17bvxxxxxxxxxxpurpose17;
	}

	public void setG5xxup17bvxxxxxxxxxxpurpose17(
			String g5xxup17bvxxxxxxxxxxpurpose17) {
		this.g5xxup17bvxxxxxxxxxxpurpose17 = g5xxup17bvxxxxxxxxxxpurpose17;
	}

	@Column(name = "value17", length = 159)
	@Size(max = 159)
	public String getG6xxuv17bvxxxxxxxxxxvalue17() {
		return this.g6xxuv17bvxxxxxxxxxxvalue17;
	}

	public void setG6xxuv17bvxxxxxxxxxxvalue17(
			String g6xxuv17bvxxxxxxxxxxvalue17) {
		this.g6xxuv17bvxxxxxxxxxxvalue17 = g6xxuv17bvxxxxxxxxxxvalue17;
	}

	@Column(name = "options18", length = 159)
	@Size(max = 159)
	public String getG7xxuo18bvxxxxxxxxxxoptions18() {
		return this.g7xxuo18bvxxxxxxxxxxoptions18;
	}

	public void setG7xxuo18bvxxxxxxxxxxoptions18(
			String g7xxuo18bvxxxxxxxxxxoptions18) {
		this.g7xxuo18bvxxxxxxxxxxoptions18 = g7xxuo18bvxxxxxxxxxxoptions18;
	}

	@Column(name = "purpose18", length = 159)
	@Size(max = 159)
	public String getG8xxup18bvxxxxxxxxxxpurpose18() {
		return this.g8xxup18bvxxxxxxxxxxpurpose18;
	}

	public void setG8xxup18bvxxxxxxxxxxpurpose18(
			String g8xxup18bvxxxxxxxxxxpurpose18) {
		this.g8xxup18bvxxxxxxxxxxpurpose18 = g8xxup18bvxxxxxxxxxxpurpose18;
	}

	@Column(name = "value18", length = 159)
	@Size(max = 159)
	public String getG9xxuv18bvxxxxxxxxxxvalue18() {
		return this.g9xxuv18bvxxxxxxxxxxvalue18;
	}

	public void setG9xxuv18bvxxxxxxxxxxvalue18(
			String g9xxuv18bvxxxxxxxxxxvalue18) {
		this.g9xxuv18bvxxxxxxxxxxvalue18 = g9xxuv18bvxxxxxxxxxxvalue18;
	}

	@Column(name = "options19", length = 159)
	@Size(max = 159)
	public String getH1xxuo19bvxxxxxxxxxxoptions19() {
		return this.h1xxuo19bvxxxxxxxxxxoptions19;
	}

	public void setH1xxuo19bvxxxxxxxxxxoptions19(
			String h1xxuo19bvxxxxxxxxxxoptions19) {
		this.h1xxuo19bvxxxxxxxxxxoptions19 = h1xxuo19bvxxxxxxxxxxoptions19;
	}

	@Column(name = "purpose19", length = 159)
	@Size(max = 159)
	public String getH2xxup19bvxxxxxxxxxxpurpose19() {
		return this.h2xxup19bvxxxxxxxxxxpurpose19;
	}

	public void setH2xxup19bvxxxxxxxxxxpurpose19(
			String h2xxup19bvxxxxxxxxxxpurpose19) {
		this.h2xxup19bvxxxxxxxxxxpurpose19 = h2xxup19bvxxxxxxxxxxpurpose19;
	}

	@Column(name = "value19", length = 159)
	@Size(max = 159)
	public String getH3xxuv19bvxxxxxxxxxxvalue19() {
		return this.h3xxuv19bvxxxxxxxxxxvalue19;
	}

	public void setH3xxuv19bvxxxxxxxxxxvalue19(
			String h3xxuv19bvxxxxxxxxxxvalue19) {
		this.h3xxuv19bvxxxxxxxxxxvalue19 = h3xxuv19bvxxxxxxxxxxvalue19;
	}

	@Column(name = "options20", length = 159)
	@Size(max = 159)
	public String getH4xxuo20bvxxxxxxxxxxoptions20() {
		return this.h4xxuo20bvxxxxxxxxxxoptions20;
	}

	public void setH4xxuo20bvxxxxxxxxxxoptions20(
			String h4xxuo20bvxxxxxxxxxxoptions20) {
		this.h4xxuo20bvxxxxxxxxxxoptions20 = h4xxuo20bvxxxxxxxxxxoptions20;
	}

	@Column(name = "purpose20", length = 159)
	@Size(max = 159)
	public String getH5xxup20bvxxxxxxxxxxpurpose20() {
		return this.h5xxup20bvxxxxxxxxxxpurpose20;
	}

	public void setH5xxup20bvxxxxxxxxxxpurpose20(
			String h5xxup20bvxxxxxxxxxxpurpose20) {
		this.h5xxup20bvxxxxxxxxxxpurpose20 = h5xxup20bvxxxxxxxxxxpurpose20;
	}

	@Column(name = "value20", length = 159)
	@Size(max = 159)
	public String getH6xxuv20bvxxxxxxxxxxvalue20() {
		return this.h6xxuv20bvxxxxxxxxxxvalue20;
	}

	public void setH6xxuv20bvxxxxxxxxxxvalue20(
			String h6xxuv20bvxxxxxxxxxxvalue20) {
		this.h6xxuv20bvxxxxxxxxxxvalue20 = h6xxuv20bvxxxxxxxxxxvalue20;
	}

	@Column(name = "options21", length = 159)
	@Size(max = 159)
	public String getH7xxuo21bvxxxxxxxxxxoptions21() {
		return this.h7xxuo21bvxxxxxxxxxxoptions21;
	}

	public void setH7xxuo21bvxxxxxxxxxxoptions21(
			String h7xxuo21bvxxxxxxxxxxoptions21) {
		this.h7xxuo21bvxxxxxxxxxxoptions21 = h7xxuo21bvxxxxxxxxxxoptions21;
	}

	@Column(name = "purpose21", length = 159)
	@Size(max = 159)
	public String getH8xxup21bvxxxxxxxxxxpurpose21() {
		return this.h8xxup21bvxxxxxxxxxxpurpose21;
	}

	public void setH8xxup21bvxxxxxxxxxxpurpose21(
			String h8xxup21bvxxxxxxxxxxpurpose21) {
		this.h8xxup21bvxxxxxxxxxxpurpose21 = h8xxup21bvxxxxxxxxxxpurpose21;
	}

	@Column(name = "value21", length = 159)
	@Size(max = 159)
	public String getH9xxuv21bvxxxxxxxxxxvalue21() {
		return this.h9xxuv21bvxxxxxxxxxxvalue21;
	}

	public void setH9xxuv21bvxxxxxxxxxxvalue21(
			String h9xxuv21bvxxxxxxxxxxvalue21) {
		this.h9xxuv21bvxxxxxxxxxxvalue21 = h9xxuv21bvxxxxxxxxxxvalue21;
	}

	@Column(name = "options22", length = 159)
	@Size(max = 159)
	public String getI1xxuo22bvxxxxxxxxxxoptions22() {
		return this.i1xxuo22bvxxxxxxxxxxoptions22;
	}

	public void setI1xxuo22bvxxxxxxxxxxoptions22(
			String i1xxuo22bvxxxxxxxxxxoptions22) {
		this.i1xxuo22bvxxxxxxxxxxoptions22 = i1xxuo22bvxxxxxxxxxxoptions22;
	}

	@Column(name = "purpose22", length = 159)
	@Size(max = 159)
	public String getI2xxup22bvxxxxxxxxxxpurpose22() {
		return this.i2xxup22bvxxxxxxxxxxpurpose22;
	}

	public void setI2xxup22bvxxxxxxxxxxpurpose22(
			String i2xxup22bvxxxxxxxxxxpurpose22) {
		this.i2xxup22bvxxxxxxxxxxpurpose22 = i2xxup22bvxxxxxxxxxxpurpose22;
	}

	@Column(name = "value22", length = 159)
	@Size(max = 159)
	public String getI3xxuv22bvxxxxxxxxxxvalue22() {
		return this.i3xxuv22bvxxxxxxxxxxvalue22;
	}

	public void setI3xxuv22bvxxxxxxxxxxvalue22(
			String i3xxuv22bvxxxxxxxxxxvalue22) {
		this.i3xxuv22bvxxxxxxxxxxvalue22 = i3xxuv22bvxxxxxxxxxxvalue22;
	}

	@Column(name = "options23", length = 159)
	@Size(max = 159)
	public String getI4xxuo23bvxxxxxxxxxxoptions23() {
		return this.i4xxuo23bvxxxxxxxxxxoptions23;
	}

	public void setI4xxuo23bvxxxxxxxxxxoptions23(
			String i4xxuo23bvxxxxxxxxxxoptions23) {
		this.i4xxuo23bvxxxxxxxxxxoptions23 = i4xxuo23bvxxxxxxxxxxoptions23;
	}

	@Column(name = "purpose23", length = 159)
	@Size(max = 159)
	public String getI5xxup23bvxxxxxxxxxxpurpose23() {
		return this.i5xxup23bvxxxxxxxxxxpurpose23;
	}

	public void setI5xxup23bvxxxxxxxxxxpurpose23(
			String i5xxup23bvxxxxxxxxxxpurpose23) {
		this.i5xxup23bvxxxxxxxxxxpurpose23 = i5xxup23bvxxxxxxxxxxpurpose23;
	}

	@Column(name = "value23", length = 159)
	@Size(max = 159)
	public String getI6xxuv23bvxxxxxxxxxxvalue23() {
		return this.i6xxuv23bvxxxxxxxxxxvalue23;
	}

	public void setI6xxuv23bvxxxxxxxxxxvalue23(
			String i6xxuv23bvxxxxxxxxxxvalue23) {
		this.i6xxuv23bvxxxxxxxxxxvalue23 = i6xxuv23bvxxxxxxxxxxvalue23;
	}

	@Column(name = "options24", length = 159)
	@Size(max = 159)
	public String getI7xxuo24bvxxxxxxxxxxoptions24() {
		return this.i7xxuo24bvxxxxxxxxxxoptions24;
	}

	public void setI7xxuo24bvxxxxxxxxxxoptions24(
			String i7xxuo24bvxxxxxxxxxxoptions24) {
		this.i7xxuo24bvxxxxxxxxxxoptions24 = i7xxuo24bvxxxxxxxxxxoptions24;
	}

	@Column(name = "purpose24", length = 159)
	@Size(max = 159)
	public String getI8xxup24bvxxxxxxxxxxpurpose24() {
		return this.i8xxup24bvxxxxxxxxxxpurpose24;
	}

	public void setI8xxup24bvxxxxxxxxxxpurpose24(
			String i8xxup24bvxxxxxxxxxxpurpose24) {
		this.i8xxup24bvxxxxxxxxxxpurpose24 = i8xxup24bvxxxxxxxxxxpurpose24;
	}

	@Column(name = "value24", length = 159)
	@Size(max = 159)
	public String getI9xxuv24bvxxxxxxxxxxvalue24() {
		return this.i9xxuv24bvxxxxxxxxxxvalue24;
	}

	public void setI9xxuv24bvxxxxxxxxxxvalue24(
			String i9xxuv24bvxxxxxxxxxxvalue24) {
		this.i9xxuv24bvxxxxxxxxxxvalue24 = i9xxuv24bvxxxxxxxxxxvalue24;
	}

	@Column(name = "options25", length = 159)
	@Size(max = 159)
	public String getJ1xxuo25bvxxxxxxxxxxoptions25() {
		return this.j1xxuo25bvxxxxxxxxxxoptions25;
	}

	public void setJ1xxuo25bvxxxxxxxxxxoptions25(
			String j1xxuo25bvxxxxxxxxxxoptions25) {
		this.j1xxuo25bvxxxxxxxxxxoptions25 = j1xxuo25bvxxxxxxxxxxoptions25;
	}

	@Column(name = "purpose25", length = 159)
	@Size(max = 159)
	public String getJ2xxup25bvxxxxxxxxxxpurpose25() {
		return this.j2xxup25bvxxxxxxxxxxpurpose25;
	}

	public void setJ2xxup25bvxxxxxxxxxxpurpose25(
			String j2xxup25bvxxxxxxxxxxpurpose25) {
		this.j2xxup25bvxxxxxxxxxxpurpose25 = j2xxup25bvxxxxxxxxxxpurpose25;
	}

	@Column(name = "value25", length = 159)
	@Size(max = 159)
	public String getJ3xxuv25bvxxxxxxxxxxvalue25() {
		return this.j3xxuv25bvxxxxxxxxxxvalue25;
	}

	public void setJ3xxuv25bvxxxxxxxxxxvalue25(
			String j3xxuv25bvxxxxxxxxxxvalue25) {
		this.j3xxuv25bvxxxxxxxxxxvalue25 = j3xxuv25bvxxxxxxxxxxvalue25;
	}

	@Column(name = "options26", length = 159)
	@Size(max = 159)
	public String getJ4xxuo26bvxxxxxxxxxxoptions26() {
		return this.j4xxuo26bvxxxxxxxxxxoptions26;
	}

	public void setJ4xxuo26bvxxxxxxxxxxoptions26(
			String j4xxuo26bvxxxxxxxxxxoptions26) {
		this.j4xxuo26bvxxxxxxxxxxoptions26 = j4xxuo26bvxxxxxxxxxxoptions26;
	}

	@Column(name = "purpose26", length = 159)
	@Size(max = 159)
	public String getJ5xxup26bvxxxxxxxxxxpurpose26() {
		return this.j5xxup26bvxxxxxxxxxxpurpose26;
	}

	public void setJ5xxup26bvxxxxxxxxxxpurpose26(
			String j5xxup26bvxxxxxxxxxxpurpose26) {
		this.j5xxup26bvxxxxxxxxxxpurpose26 = j5xxup26bvxxxxxxxxxxpurpose26;
	}

	@Column(name = "value26", length = 159)
	@Size(max = 159)
	public String getJ6xxuv26bvxxxxxxxxxxvalue26() {
		return this.j6xxuv26bvxxxxxxxxxxvalue26;
	}

	public void setJ6xxuv26bvxxxxxxxxxxvalue26(
			String j6xxuv26bvxxxxxxxxxxvalue26) {
		this.j6xxuv26bvxxxxxxxxxxvalue26 = j6xxuv26bvxxxxxxxxxxvalue26;
	}

	@Column(name = "options27", length = 159)
	@Size(max = 159)
	public String getJ7xxuo27bvxxxxxxxxxxoptions27() {
		return this.j7xxuo27bvxxxxxxxxxxoptions27;
	}

	public void setJ7xxuo27bvxxxxxxxxxxoptions27(
			String j7xxuo27bvxxxxxxxxxxoptions27) {
		this.j7xxuo27bvxxxxxxxxxxoptions27 = j7xxuo27bvxxxxxxxxxxoptions27;
	}

	@Column(name = "purpose27", length = 159)
	@Size(max = 159)
	public String getJ8xxup27bvxxxxxxxxxxpurpose27() {
		return this.j8xxup27bvxxxxxxxxxxpurpose27;
	}

	public void setJ8xxup27bvxxxxxxxxxxpurpose27(
			String j8xxup27bvxxxxxxxxxxpurpose27) {
		this.j8xxup27bvxxxxxxxxxxpurpose27 = j8xxup27bvxxxxxxxxxxpurpose27;
	}

	@Column(name = "value27", length = 159)
	@Size(max = 159)
	public String getJ9xxuv27bvxxxxxxxxxxvalue27() {
		return this.j9xxuv27bvxxxxxxxxxxvalue27;
	}

	public void setJ9xxuv27bvxxxxxxxxxxvalue27(
			String j9xxuv27bvxxxxxxxxxxvalue27) {
		this.j9xxuv27bvxxxxxxxxxxvalue27 = j9xxuv27bvxxxxxxxxxxvalue27;
	}

	@Column(name = "options28", length = 159)
	@Size(max = 159)
	public String getK1xxuo28bvxxxxxxxxxxoptions28() {
		return this.k1xxuo28bvxxxxxxxxxxoptions28;
	}

	public void setK1xxuo28bvxxxxxxxxxxoptions28(
			String k1xxuo28bvxxxxxxxxxxoptions28) {
		this.k1xxuo28bvxxxxxxxxxxoptions28 = k1xxuo28bvxxxxxxxxxxoptions28;
	}

	@Column(name = "purpose28", length = 159)
	@Size(max = 159)
	public String getK2xxup28bvxxxxxxxxxxpurpose28() {
		return this.k2xxup28bvxxxxxxxxxxpurpose28;
	}

	public void setK2xxup28bvxxxxxxxxxxpurpose28(
			String k2xxup28bvxxxxxxxxxxpurpose28) {
		this.k2xxup28bvxxxxxxxxxxpurpose28 = k2xxup28bvxxxxxxxxxxpurpose28;
	}

	@Column(name = "value28", length = 159)
	@Size(max = 159)
	public String getK3xxuv28bvxxxxxxxxxxvalue28() {
		return this.k3xxuv28bvxxxxxxxxxxvalue28;
	}

	public void setK3xxuv28bvxxxxxxxxxxvalue28(
			String k3xxuv28bvxxxxxxxxxxvalue28) {
		this.k3xxuv28bvxxxxxxxxxxvalue28 = k3xxuv28bvxxxxxxxxxxvalue28;
	}

	@Column(name = "options29", length = 159)
	@Size(max = 159)
	public String getK4xxuo29bvxxxxxxxxxxoptions29() {
		return this.k4xxuo29bvxxxxxxxxxxoptions29;
	}

	public void setK4xxuo29bvxxxxxxxxxxoptions29(
			String k4xxuo29bvxxxxxxxxxxoptions29) {
		this.k4xxuo29bvxxxxxxxxxxoptions29 = k4xxuo29bvxxxxxxxxxxoptions29;
	}

	@Column(name = "purpose29", length = 159)
	@Size(max = 159)
	public String getK5xxup29bvxxxxxxxxxxpurpose29() {
		return this.k5xxup29bvxxxxxxxxxxpurpose29;
	}

	public void setK5xxup29bvxxxxxxxxxxpurpose29(
			String k5xxup29bvxxxxxxxxxxpurpose29) {
		this.k5xxup29bvxxxxxxxxxxpurpose29 = k5xxup29bvxxxxxxxxxxpurpose29;
	}

	@Column(name = "value29", length = 159)
	@Size(max = 159)
	public String getK6xxuv29bvxxxxxxxxxxvalue29() {
		return this.k6xxuv29bvxxxxxxxxxxvalue29;
	}

	public void setK6xxuv29bvxxxxxxxxxxvalue29(
			String k6xxuv29bvxxxxxxxxxxvalue29) {
		this.k6xxuv29bvxxxxxxxxxxvalue29 = k6xxuv29bvxxxxxxxxxxvalue29;
	}

	@Column(name = "options30", length = 159)
	@Size(max = 159)
	public String getK7xxuo30bvxxxxxxxxxxoptions30() {
		return this.k7xxuo30bvxxxxxxxxxxoptions30;
	}

	public void setK7xxuo30bvxxxxxxxxxxoptions30(
			String k7xxuo30bvxxxxxxxxxxoptions30) {
		this.k7xxuo30bvxxxxxxxxxxoptions30 = k7xxuo30bvxxxxxxxxxxoptions30;
	}

	@Column(name = "purpose30", length = 159)
	@Size(max = 159)
	public String getK8xxup30bvxxxxxxxxxxpurpose30() {
		return this.k8xxup30bvxxxxxxxxxxpurpose30;
	}

	public void setK8xxup30bvxxxxxxxxxxpurpose30(
			String k8xxup30bvxxxxxxxxxxpurpose30) {
		this.k8xxup30bvxxxxxxxxxxpurpose30 = k8xxup30bvxxxxxxxxxxpurpose30;
	}

	@Column(name = "value30", length = 159)
	@Size(max = 159)
	public String getK9xxuv30bvxxxxxxxxxxvalue30() {
		return this.k9xxuv30bvxxxxxxxxxxvalue30;
	}

	public void setK9xxuv30bvxxxxxxxxxxvalue30(
			String k9xxuv30bvxxxxxxxxxxvalue30) {
		this.k9xxuv30bvxxxxxxxxxxvalue30 = k9xxuv30bvxxxxxxxxxxvalue30;
	}

	@Column(name = "options31", length = 159)
	@Size(max = 159)
	public String getL1xxuo31bvxxxxxxxxxxoptions31() {
		return this.l1xxuo31bvxxxxxxxxxxoptions31;
	}

	public void setL1xxuo31bvxxxxxxxxxxoptions31(
			String l1xxuo31bvxxxxxxxxxxoptions31) {
		this.l1xxuo31bvxxxxxxxxxxoptions31 = l1xxuo31bvxxxxxxxxxxoptions31;
	}

	@Column(name = "purpose31", length = 159)
	@Size(max = 159)
	public String getL2xxup31bvxxxxxxxxxxpurpose31() {
		return this.l2xxup31bvxxxxxxxxxxpurpose31;
	}

	public void setL2xxup31bvxxxxxxxxxxpurpose31(
			String l2xxup31bvxxxxxxxxxxpurpose31) {
		this.l2xxup31bvxxxxxxxxxxpurpose31 = l2xxup31bvxxxxxxxxxxpurpose31;
	}

	@Column(name = "value31", length = 159)
	@Size(max = 159)
	public String getL3xxuv31bvxxxxxxxxxxvalue31() {
		return this.l3xxuv31bvxxxxxxxxxxvalue31;
	}

	public void setL3xxuv31bvxxxxxxxxxxvalue31(
			String l3xxuv31bvxxxxxxxxxxvalue31) {
		this.l3xxuv31bvxxxxxxxxxxvalue31 = l3xxuv31bvxxxxxxxxxxvalue31;
	}

	@Column(name = "options32", length = 159)
	@Size(max = 159)
	public String getL4xxuo32bvxxxxxxxxxxoptions32() {
		return this.l4xxuo32bvxxxxxxxxxxoptions32;
	}

	public void setL4xxuo32bvxxxxxxxxxxoptions32(
			String l4xxuo32bvxxxxxxxxxxoptions32) {
		this.l4xxuo32bvxxxxxxxxxxoptions32 = l4xxuo32bvxxxxxxxxxxoptions32;
	}

	@Column(name = "purpose32", length = 159)
	@Size(max = 159)
	public String getL5xxup32bvxxxxxxxxxxpurpose32() {
		return this.l5xxup32bvxxxxxxxxxxpurpose32;
	}

	public void setL5xxup32bvxxxxxxxxxxpurpose32(
			String l5xxup32bvxxxxxxxxxxpurpose32) {
		this.l5xxup32bvxxxxxxxxxxpurpose32 = l5xxup32bvxxxxxxxxxxpurpose32;
	}

	@Column(name = "value32", length = 159)
	@Size(max = 159)
	public String getL6xxuv32bvxxxxxxxxxxvalue32() {
		return this.l6xxuv32bvxxxxxxxxxxvalue32;
	}

	public void setL6xxuv32bvxxxxxxxxxxvalue32(
			String l6xxuv32bvxxxxxxxxxxvalue32) {
		this.l6xxuv32bvxxxxxxxxxxvalue32 = l6xxuv32bvxxxxxxxxxxvalue32;
	}

	@Column(name = "options33", length = 159)
	@Size(max = 159)
	public String getL7xxuo33bvxxxxxxxxxxoptions33() {
		return this.l7xxuo33bvxxxxxxxxxxoptions33;
	}

	public void setL7xxuo33bvxxxxxxxxxxoptions33(
			String l7xxuo33bvxxxxxxxxxxoptions33) {
		this.l7xxuo33bvxxxxxxxxxxoptions33 = l7xxuo33bvxxxxxxxxxxoptions33;
	}

	@Column(name = "purpose33", length = 159)
	@Size(max = 159)
	public String getL8xxup33bvxxxxxxxxxxpurpose33() {
		return this.l8xxup33bvxxxxxxxxxxpurpose33;
	}

	public void setL8xxup33bvxxxxxxxxxxpurpose33(
			String l8xxup33bvxxxxxxxxxxpurpose33) {
		this.l8xxup33bvxxxxxxxxxxpurpose33 = l8xxup33bvxxxxxxxxxxpurpose33;
	}

	@Column(name = "value33", length = 159)
	@Size(max = 159)
	public String getL9xxuv33bvxxxxxxxxxxvalue33() {
		return this.l9xxuv33bvxxxxxxxxxxvalue33;
	}

	public void setL9xxuv33bvxxxxxxxxxxvalue33(
			String l9xxuv33bvxxxxxxxxxxvalue33) {
		this.l9xxuv33bvxxxxxxxxxxvalue33 = l9xxuv33bvxxxxxxxxxxvalue33;
	}

	@Column(name = "options34", length = 159)
	@Size(max = 159)
	public String getM1xxuo34bvxxxxxxxxxxoptions34() {
		return this.m1xxuo34bvxxxxxxxxxxoptions34;
	}

	public void setM1xxuo34bvxxxxxxxxxxoptions34(
			String m1xxuo34bvxxxxxxxxxxoptions34) {
		this.m1xxuo34bvxxxxxxxxxxoptions34 = m1xxuo34bvxxxxxxxxxxoptions34;
	}

	@Column(name = "purpose34", length = 159)
	@Size(max = 159)
	public String getM2xxup34bvxxxxxxxxxxpurpose34() {
		return this.m2xxup34bvxxxxxxxxxxpurpose34;
	}

	public void setM2xxup34bvxxxxxxxxxxpurpose34(
			String m2xxup34bvxxxxxxxxxxpurpose34) {
		this.m2xxup34bvxxxxxxxxxxpurpose34 = m2xxup34bvxxxxxxxxxxpurpose34;
	}

	@Column(name = "value34", length = 159)
	@Size(max = 159)
	public String getM3xxuv34bvxxxxxxxxxxvalue34() {
		return this.m3xxuv34bvxxxxxxxxxxvalue34;
	}

	public void setM3xxuv34bvxxxxxxxxxxvalue34(
			String m3xxuv34bvxxxxxxxxxxvalue34) {
		this.m3xxuv34bvxxxxxxxxxxvalue34 = m3xxuv34bvxxxxxxxxxxvalue34;
	}

	@Column(name = "options35", length = 159)
	@Size(max = 159)
	public String getM4xxuo35bvxxxxxxxxxxoptions35() {
		return this.m4xxuo35bvxxxxxxxxxxoptions35;
	}

	public void setM4xxuo35bvxxxxxxxxxxoptions35(
			String m4xxuo35bvxxxxxxxxxxoptions35) {
		this.m4xxuo35bvxxxxxxxxxxoptions35 = m4xxuo35bvxxxxxxxxxxoptions35;
	}

	@Column(name = "purpose35", length = 159)
	@Size(max = 159)
	public String getM5xxup35bvxxxxxxxxxxpurpose35() {
		return this.m5xxup35bvxxxxxxxxxxpurpose35;
	}

	public void setM5xxup35bvxxxxxxxxxxpurpose35(
			String m5xxup35bvxxxxxxxxxxpurpose35) {
		this.m5xxup35bvxxxxxxxxxxpurpose35 = m5xxup35bvxxxxxxxxxxpurpose35;
	}

	@Column(name = "value35", length = 159)
	@Size(max = 159)
	public String getM6xxuv35bvxxxxxxxxxxvalue35() {
		return this.m6xxuv35bvxxxxxxxxxxvalue35;
	}

	public void setM6xxuv35bvxxxxxxxxxxvalue35(
			String m6xxuv35bvxxxxxxxxxxvalue35) {
		this.m6xxuv35bvxxxxxxxxxxvalue35 = m6xxuv35bvxxxxxxxxxxvalue35;
	}

	@Column(name = "options36", length = 159)
	@Size(max = 159)
	public String getM7xxuo36bvxxxxxxxxxxoptions36() {
		return this.m7xxuo36bvxxxxxxxxxxoptions36;
	}

	public void setM7xxuo36bvxxxxxxxxxxoptions36(
			String m7xxuo36bvxxxxxxxxxxoptions36) {
		this.m7xxuo36bvxxxxxxxxxxoptions36 = m7xxuo36bvxxxxxxxxxxoptions36;
	}

	@Column(name = "purpose36", length = 159)
	@Size(max = 159)
	public String getM8xxup36bvxxxxxxxxxxpurpose36() {
		return this.m8xxup36bvxxxxxxxxxxpurpose36;
	}

	public void setM8xxup36bvxxxxxxxxxxpurpose36(
			String m8xxup36bvxxxxxxxxxxpurpose36) {
		this.m8xxup36bvxxxxxxxxxxpurpose36 = m8xxup36bvxxxxxxxxxxpurpose36;
	}

	@Column(name = "value36", length = 159)
	@Size(max = 159)
	public String getM9xxuv36bvxxxxxxxxxxvalue36() {
		return this.m9xxuv36bvxxxxxxxxxxvalue36;
	}

	public void setM9xxuv36bvxxxxxxxxxxvalue36(
			String m9xxuv36bvxxxxxxxxxxvalue36) {
		this.m9xxuv36bvxxxxxxxxxxvalue36 = m9xxuv36bvxxxxxxxxxxvalue36;
	}

	@Column(name = "options37", length = 159)
	@Size(max = 159)
	public String getN1xxuo37bvxxxxxxxxxxoptions37() {
		return this.n1xxuo37bvxxxxxxxxxxoptions37;
	}

	public void setN1xxuo37bvxxxxxxxxxxoptions37(
			String n1xxuo37bvxxxxxxxxxxoptions37) {
		this.n1xxuo37bvxxxxxxxxxxoptions37 = n1xxuo37bvxxxxxxxxxxoptions37;
	}

	@Column(name = "purpose37", length = 159)
	@Size(max = 159)
	public String getN2xxup37bvxxxxxxxxxxpurpose37() {
		return this.n2xxup37bvxxxxxxxxxxpurpose37;
	}

	public void setN2xxup37bvxxxxxxxxxxpurpose37(
			String n2xxup37bvxxxxxxxxxxpurpose37) {
		this.n2xxup37bvxxxxxxxxxxpurpose37 = n2xxup37bvxxxxxxxxxxpurpose37;
	}

	@Column(name = "value37", length = 159)
	@Size(max = 159)
	public String getN3xxuv37bvxxxxxxxxxxvalue37() {
		return this.n3xxuv37bvxxxxxxxxxxvalue37;
	}

	public void setN3xxuv37bvxxxxxxxxxxvalue37(
			String n3xxuv37bvxxxxxxxxxxvalue37) {
		this.n3xxuv37bvxxxxxxxxxxvalue37 = n3xxuv37bvxxxxxxxxxxvalue37;
	}

	@Column(name = "options38", length = 159)
	@Size(max = 159)
	public String getN4xxuo38bvxxxxxxxxxxoptions38() {
		return this.n4xxuo38bvxxxxxxxxxxoptions38;
	}

	public void setN4xxuo38bvxxxxxxxxxxoptions38(
			String n4xxuo38bvxxxxxxxxxxoptions38) {
		this.n4xxuo38bvxxxxxxxxxxoptions38 = n4xxuo38bvxxxxxxxxxxoptions38;
	}

	@Column(name = "purpose38", length = 159)
	@Size(max = 159)
	public String getN5xxup38bvxxxxxxxxxxpurpose38() {
		return this.n5xxup38bvxxxxxxxxxxpurpose38;
	}

	public void setN5xxup38bvxxxxxxxxxxpurpose38(
			String n5xxup38bvxxxxxxxxxxpurpose38) {
		this.n5xxup38bvxxxxxxxxxxpurpose38 = n5xxup38bvxxxxxxxxxxpurpose38;
	}

	@Column(name = "value38", length = 159)
	@Size(max = 159)
	public String getN6xxuv38bvxxxxxxxxxxvalue38() {
		return this.n6xxuv38bvxxxxxxxxxxvalue38;
	}

	public void setN6xxuv38bvxxxxxxxxxxvalue38(
			String n6xxuv38bvxxxxxxxxxxvalue38) {
		this.n6xxuv38bvxxxxxxxxxxvalue38 = n6xxuv38bvxxxxxxxxxxvalue38;
	}

	@Column(name = "options39", length = 159)
	@Size(max = 159)
	public String getN7xxuo39bvxxxxxxxxxxoptions39() {
		return this.n7xxuo39bvxxxxxxxxxxoptions39;
	}

	public void setN7xxuo39bvxxxxxxxxxxoptions39(
			String n7xxuo39bvxxxxxxxxxxoptions39) {
		this.n7xxuo39bvxxxxxxxxxxoptions39 = n7xxuo39bvxxxxxxxxxxoptions39;
	}

	@Column(name = "purpose39", length = 159)
	@Size(max = 159)
	public String getN8xxup39bvxxxxxxxxxxpurpose39() {
		return this.n8xxup39bvxxxxxxxxxxpurpose39;
	}

	public void setN8xxup39bvxxxxxxxxxxpurpose39(
			String n8xxup39bvxxxxxxxxxxpurpose39) {
		this.n8xxup39bvxxxxxxxxxxpurpose39 = n8xxup39bvxxxxxxxxxxpurpose39;
	}

	@Column(name = "value39", length = 159)
	@Size(max = 159)
	public String getN9xxuv39bvxxxxxxxxxxvalue39() {
		return this.n9xxuv39bvxxxxxxxxxxvalue39;
	}

	public void setN9xxuv39bvxxxxxxxxxxvalue39(
			String n9xxuv39bvxxxxxxxxxxvalue39) {
		this.n9xxuv39bvxxxxxxxxxxvalue39 = n9xxuv39bvxxxxxxxxxxvalue39;
	}

	@Column(name = "options40", length = 159)
	@Size(max = 159)
	public String getO1xxuo40bvxxxxxxxxxxoptions40() {
		return this.o1xxuo40bvxxxxxxxxxxoptions40;
	}

	public void setO1xxuo40bvxxxxxxxxxxoptions40(
			String o1xxuo40bvxxxxxxxxxxoptions40) {
		this.o1xxuo40bvxxxxxxxxxxoptions40 = o1xxuo40bvxxxxxxxxxxoptions40;
	}

	@Column(name = "purpose40", length = 159)
	@Size(max = 159)
	public String getO2xxup40bvxxxxxxxxxxpurpose40() {
		return this.o2xxup40bvxxxxxxxxxxpurpose40;
	}

	public void setO2xxup40bvxxxxxxxxxxpurpose40(
			String o2xxup40bvxxxxxxxxxxpurpose40) {
		this.o2xxup40bvxxxxxxxxxxpurpose40 = o2xxup40bvxxxxxxxxxxpurpose40;
	}

	@Column(name = "value40", length = 159)
	@Size(max = 159)
	public String getO3xxuv40bvxxxxxxxxxxvalue40() {
		return this.o3xxuv40bvxxxxxxxxxxvalue40;
	}

	public void setO3xxuv40bvxxxxxxxxxxvalue40(
			String o3xxuv40bvxxxxxxxxxxvalue40) {
		this.o3xxuv40bvxxxxxxxxxxvalue40 = o3xxuv40bvxxxxxxxxxxvalue40;
	}

	@Column(name = "options41", length = 159)
	@Size(max = 159)
	public String getO4xxuo41bvxxxxxxxxxxoptions41() {
		return this.o4xxuo41bvxxxxxxxxxxoptions41;
	}

	public void setO4xxuo41bvxxxxxxxxxxoptions41(
			String o4xxuo41bvxxxxxxxxxxoptions41) {
		this.o4xxuo41bvxxxxxxxxxxoptions41 = o4xxuo41bvxxxxxxxxxxoptions41;
	}

	@Column(name = "purpose41", length = 159)
	@Size(max = 159)
	public String getO5xxup41bvxxxxxxxxxxpurpose41() {
		return this.o5xxup41bvxxxxxxxxxxpurpose41;
	}

	public void setO5xxup41bvxxxxxxxxxxpurpose41(
			String o5xxup41bvxxxxxxxxxxpurpose41) {
		this.o5xxup41bvxxxxxxxxxxpurpose41 = o5xxup41bvxxxxxxxxxxpurpose41;
	}

	@Column(name = "value41", length = 159)
	@Size(max = 159)
	public String getO6xxuv41bvxxxxxxxxxxvalue41() {
		return this.o6xxuv41bvxxxxxxxxxxvalue41;
	}

	public void setO6xxuv41bvxxxxxxxxxxvalue41(
			String o6xxuv41bvxxxxxxxxxxvalue41) {
		this.o6xxuv41bvxxxxxxxxxxvalue41 = o6xxuv41bvxxxxxxxxxxvalue41;
	}

	@Column(name = "options42", length = 159)
	@Size(max = 159)
	public String getO7xxuo42bvxxxxxxxxxxoptions42() {
		return this.o7xxuo42bvxxxxxxxxxxoptions42;
	}

	public void setO7xxuo42bvxxxxxxxxxxoptions42(
			String o7xxuo42bvxxxxxxxxxxoptions42) {
		this.o7xxuo42bvxxxxxxxxxxoptions42 = o7xxuo42bvxxxxxxxxxxoptions42;
	}

	@Column(name = "purpose42", length = 159)
	@Size(max = 159)
	public String getO8xxup42bvxxxxxxxxxxpurpose42() {
		return this.o8xxup42bvxxxxxxxxxxpurpose42;
	}

	public void setO8xxup42bvxxxxxxxxxxpurpose42(
			String o8xxup42bvxxxxxxxxxxpurpose42) {
		this.o8xxup42bvxxxxxxxxxxpurpose42 = o8xxup42bvxxxxxxxxxxpurpose42;
	}

	@Column(name = "value42", length = 159)
	@Size(max = 159)
	public String getO9xxuv42bvxxxxxxxxxxvalue42() {
		return this.o9xxuv42bvxxxxxxxxxxvalue42;
	}

	public void setO9xxuv42bvxxxxxxxxxxvalue42(
			String o9xxuv42bvxxxxxxxxxxvalue42) {
		this.o9xxuv42bvxxxxxxxxxxvalue42 = o9xxuv42bvxxxxxxxxxxvalue42;
	}

	@Column(name = "options43", length = 159)
	@Size(max = 159)
	public String getP1xxuo43bvxxxxxxxxxxoptions43() {
		return this.p1xxuo43bvxxxxxxxxxxoptions43;
	}

	public void setP1xxuo43bvxxxxxxxxxxoptions43(
			String p1xxuo43bvxxxxxxxxxxoptions43) {
		this.p1xxuo43bvxxxxxxxxxxoptions43 = p1xxuo43bvxxxxxxxxxxoptions43;
	}

	@Column(name = "purpose43", length = 159)
	@Size(max = 159)
	public String getP2xxup43bvxxxxxxxxxxpurpose43() {
		return this.p2xxup43bvxxxxxxxxxxpurpose43;
	}

	public void setP2xxup43bvxxxxxxxxxxpurpose43(
			String p2xxup43bvxxxxxxxxxxpurpose43) {
		this.p2xxup43bvxxxxxxxxxxpurpose43 = p2xxup43bvxxxxxxxxxxpurpose43;
	}

	@Column(name = "value43", length = 159)
	@Size(max = 159)
	public String getP3xxuv43bvxxxxxxxxxxvalue43() {
		return this.p3xxuv43bvxxxxxxxxxxvalue43;
	}

	public void setP3xxuv43bvxxxxxxxxxxvalue43(
			String p3xxuv43bvxxxxxxxxxxvalue43) {
		this.p3xxuv43bvxxxxxxxxxxvalue43 = p3xxuv43bvxxxxxxxxxxvalue43;
	}

	@Column(name = "options44", length = 159)
	@Size(max = 159)
	public String getP4xxuo44bvxxxxxxxxxxoptions44() {
		return this.p4xxuo44bvxxxxxxxxxxoptions44;
	}

	public void setP4xxuo44bvxxxxxxxxxxoptions44(
			String p4xxuo44bvxxxxxxxxxxoptions44) {
		this.p4xxuo44bvxxxxxxxxxxoptions44 = p4xxuo44bvxxxxxxxxxxoptions44;
	}

	@Column(name = "purpose44", length = 159)
	@Size(max = 159)
	public String getP5xxup44bvxxxxxxxxxxpurpose44() {
		return this.p5xxup44bvxxxxxxxxxxpurpose44;
	}

	public void setP5xxup44bvxxxxxxxxxxpurpose44(
			String p5xxup44bvxxxxxxxxxxpurpose44) {
		this.p5xxup44bvxxxxxxxxxxpurpose44 = p5xxup44bvxxxxxxxxxxpurpose44;
	}

	@Column(name = "value44", length = 159)
	@Size(max = 159)
	public String getP6xxuv44bvxxxxxxxxxxvalue44() {
		return this.p6xxuv44bvxxxxxxxxxxvalue44;
	}

	public void setP6xxuv44bvxxxxxxxxxxvalue44(
			String p6xxuv44bvxxxxxxxxxxvalue44) {
		this.p6xxuv44bvxxxxxxxxxxvalue44 = p6xxuv44bvxxxxxxxxxxvalue44;
	}

	@Column(name = "options45", length = 159)
	@Size(max = 159)
	public String getP7xxuo45bvxxxxxxxxxxoptions45() {
		return this.p7xxuo45bvxxxxxxxxxxoptions45;
	}

	public void setP7xxuo45bvxxxxxxxxxxoptions45(
			String p7xxuo45bvxxxxxxxxxxoptions45) {
		this.p7xxuo45bvxxxxxxxxxxoptions45 = p7xxuo45bvxxxxxxxxxxoptions45;
	}

	@Column(name = "purpose45", length = 159)
	@Size(max = 159)
	public String getP8xxup45bvxxxxxxxxxxpurpose45() {
		return this.p8xxup45bvxxxxxxxxxxpurpose45;
	}

	public void setP8xxup45bvxxxxxxxxxxpurpose45(
			String p8xxup45bvxxxxxxxxxxpurpose45) {
		this.p8xxup45bvxxxxxxxxxxpurpose45 = p8xxup45bvxxxxxxxxxxpurpose45;
	}

	@Column(name = "value45", length = 159)
	@Size(max = 159)
	public String getP9xxuv45bvxxxxxxxxxxvalue45() {
		return this.p9xxuv45bvxxxxxxxxxxvalue45;
	}

	public void setP9xxuv45bvxxxxxxxxxxvalue45(
			String p9xxuv45bvxxxxxxxxxxvalue45) {
		this.p9xxuv45bvxxxxxxxxxxvalue45 = p9xxuv45bvxxxxxxxxxxvalue45;
	}

	@Column(name = "options46", length = 159)
	@Size(max = 159)
	public String getQ1xxuo46bvxxxxxxxxxxoptions46() {
		return this.q1xxuo46bvxxxxxxxxxxoptions46;
	}

	public void setQ1xxuo46bvxxxxxxxxxxoptions46(
			String q1xxuo46bvxxxxxxxxxxoptions46) {
		this.q1xxuo46bvxxxxxxxxxxoptions46 = q1xxuo46bvxxxxxxxxxxoptions46;
	}

	@Column(name = "purpose46", length = 159)
	@Size(max = 159)
	public String getQ2xxup46bvxxxxxxxxxxpurpose46() {
		return this.q2xxup46bvxxxxxxxxxxpurpose46;
	}

	public void setQ2xxup46bvxxxxxxxxxxpurpose46(
			String q2xxup46bvxxxxxxxxxxpurpose46) {
		this.q2xxup46bvxxxxxxxxxxpurpose46 = q2xxup46bvxxxxxxxxxxpurpose46;
	}

	@Column(name = "value46", length = 159)
	@Size(max = 159)
	public String getQ3xxuv46bvxxxxxxxxxxvalue46() {
		return this.q3xxuv46bvxxxxxxxxxxvalue46;
	}

	public void setQ3xxuv46bvxxxxxxxxxxvalue46(
			String q3xxuv46bvxxxxxxxxxxvalue46) {
		this.q3xxuv46bvxxxxxxxxxxvalue46 = q3xxuv46bvxxxxxxxxxxvalue46;
	}

	@Column(name = "options47", length = 159)
	@Size(max = 159)
	public String getQ4xxuo47bvxxxxxxxxxxoptions47() {
		return this.q4xxuo47bvxxxxxxxxxxoptions47;
	}

	public void setQ4xxuo47bvxxxxxxxxxxoptions47(
			String q4xxuo47bvxxxxxxxxxxoptions47) {
		this.q4xxuo47bvxxxxxxxxxxoptions47 = q4xxuo47bvxxxxxxxxxxoptions47;
	}

	@Column(name = "purpose47", length = 159)
	@Size(max = 159)
	public String getQ5xxup47bvxxxxxxxxxxpurpose47() {
		return this.q5xxup47bvxxxxxxxxxxpurpose47;
	}

	public void setQ5xxup47bvxxxxxxxxxxpurpose47(
			String q5xxup47bvxxxxxxxxxxpurpose47) {
		this.q5xxup47bvxxxxxxxxxxpurpose47 = q5xxup47bvxxxxxxxxxxpurpose47;
	}

	@Column(name = "value47", length = 159)
	@Size(max = 159)
	public String getQ6xxuv47bvxxxxxxxxxxvalue47() {
		return this.q6xxuv47bvxxxxxxxxxxvalue47;
	}

	public void setQ6xxuv47bvxxxxxxxxxxvalue47(
			String q6xxuv47bvxxxxxxxxxxvalue47) {
		this.q6xxuv47bvxxxxxxxxxxvalue47 = q6xxuv47bvxxxxxxxxxxvalue47;
	}

	@Column(name = "options48", length = 159)
	@Size(max = 159)
	public String getQ7xxuo48bvxxxxxxxxxxoptions48() {
		return this.q7xxuo48bvxxxxxxxxxxoptions48;
	}

	public void setQ7xxuo48bvxxxxxxxxxxoptions48(
			String q7xxuo48bvxxxxxxxxxxoptions48) {
		this.q7xxuo48bvxxxxxxxxxxoptions48 = q7xxuo48bvxxxxxxxxxxoptions48;
	}

	@Column(name = "purpose48", length = 159)
	@Size(max = 159)
	public String getQ8xxup48bvxxxxxxxxxxpurpose48() {
		return this.q8xxup48bvxxxxxxxxxxpurpose48;
	}

	public void setQ8xxup48bvxxxxxxxxxxpurpose48(
			String q8xxup48bvxxxxxxxxxxpurpose48) {
		this.q8xxup48bvxxxxxxxxxxpurpose48 = q8xxup48bvxxxxxxxxxxpurpose48;
	}

	@Column(name = "value48", length = 159)
	@Size(max = 159)
	public String getQ9xxuv48bvxxxxxxxxxxvalue48() {
		return this.q9xxuv48bvxxxxxxxxxxvalue48;
	}

	public void setQ9xxuv48bvxxxxxxxxxxvalue48(
			String q9xxuv48bvxxxxxxxxxxvalue48) {
		this.q9xxuv48bvxxxxxxxxxxvalue48 = q9xxuv48bvxxxxxxxxxxvalue48;
	}

	@Column(name = "options49", length = 159)
	@Size(max = 159)
	public String getR1xxuo49bvxxxxxxxxxxoptions49() {
		return this.r1xxuo49bvxxxxxxxxxxoptions49;
	}

	public void setR1xxuo49bvxxxxxxxxxxoptions49(
			String r1xxuo49bvxxxxxxxxxxoptions49) {
		this.r1xxuo49bvxxxxxxxxxxoptions49 = r1xxuo49bvxxxxxxxxxxoptions49;
	}

	@Column(name = "purpose49", length = 159)
	@Size(max = 159)
	public String getR2xxup49bvxxxxxxxxxxpurpose49() {
		return this.r2xxup49bvxxxxxxxxxxpurpose49;
	}

	public void setR2xxup49bvxxxxxxxxxxpurpose49(
			String r2xxup49bvxxxxxxxxxxpurpose49) {
		this.r2xxup49bvxxxxxxxxxxpurpose49 = r2xxup49bvxxxxxxxxxxpurpose49;
	}

	@Column(name = "value49", length = 159)
	@Size(max = 159)
	public String getR3xxuv49bvxxxxxxxxxxvalue49() {
		return this.r3xxuv49bvxxxxxxxxxxvalue49;
	}

	public void setR3xxuv49bvxxxxxxxxxxvalue49(
			String r3xxuv49bvxxxxxxxxxxvalue49) {
		this.r3xxuv49bvxxxxxxxxxxvalue49 = r3xxuv49bvxxxxxxxxxxvalue49;
	}

	@Column(name = "options50", length = 159)
	@Size(max = 159)
	public String getR4xxuo50bvxxxxxxxxxxoptions50() {
		return this.r4xxuo50bvxxxxxxxxxxoptions50;
	}

	public void setR4xxuo50bvxxxxxxxxxxoptions50(
			String r4xxuo50bvxxxxxxxxxxoptions50) {
		this.r4xxuo50bvxxxxxxxxxxoptions50 = r4xxuo50bvxxxxxxxxxxoptions50;
	}

	@Column(name = "purpose50", length = 159)
	@Size(max = 159)
	public String getR5xxup50bvxxxxxxxxxxpurpose50() {
		return this.r5xxup50bvxxxxxxxxxxpurpose50;
	}

	public void setR5xxup50bvxxxxxxxxxxpurpose50(
			String r5xxup50bvxxxxxxxxxxpurpose50) {
		this.r5xxup50bvxxxxxxxxxxpurpose50 = r5xxup50bvxxxxxxxxxxpurpose50;
	}

	@Column(name = "value50", length = 159)
	@Size(max = 159)
	public String getR6xxuv50bvxxxxxxxxxxvalue50() {
		return this.r6xxuv50bvxxxxxxxxxxvalue50;
	}

	public void setR6xxuv50bvxxxxxxxxxxvalue50(
			String r6xxuv50bvxxxxxxxxxxvalue50) {
		this.r6xxuv50bvxxxxxxxxxxvalue50 = r6xxuv50bvxxxxxxxxxxvalue50;
	}

	@Column(name = "options51", length = 159)
	@Size(max = 159)
	public String getR7xxuo51bvxxxxxxxxxxoptions51() {
		return this.r7xxuo51bvxxxxxxxxxxoptions51;
	}

	public void setR7xxuo51bvxxxxxxxxxxoptions51(
			String r7xxuo51bvxxxxxxxxxxoptions51) {
		this.r7xxuo51bvxxxxxxxxxxoptions51 = r7xxuo51bvxxxxxxxxxxoptions51;
	}

	@Column(name = "purpose51", length = 159)
	@Size(max = 159)
	public String getR8xxup51bvxxxxxxxxxxpurpose51() {
		return this.r8xxup51bvxxxxxxxxxxpurpose51;
	}

	public void setR8xxup51bvxxxxxxxxxxpurpose51(
			String r8xxup51bvxxxxxxxxxxpurpose51) {
		this.r8xxup51bvxxxxxxxxxxpurpose51 = r8xxup51bvxxxxxxxxxxpurpose51;
	}

	@Column(name = "value51", length = 159)
	@Size(max = 159)
	public String getR9xxuv51bvxxxxxxxxxxvalue51() {
		return this.r9xxuv51bvxxxxxxxxxxvalue51;
	}

	public void setR9xxuv51bvxxxxxxxxxxvalue51(
			String r9xxuv51bvxxxxxxxxxxvalue51) {
		this.r9xxuv51bvxxxxxxxxxxvalue51 = r9xxuv51bvxxxxxxxxxxvalue51;
	}

	@Column(name = "options52", length = 159)
	@Size(max = 159)
	public String getS1xxuo52bvxxxxxxxxxxoptions52() {
		return this.s1xxuo52bvxxxxxxxxxxoptions52;
	}

	public void setS1xxuo52bvxxxxxxxxxxoptions52(
			String s1xxuo52bvxxxxxxxxxxoptions52) {
		this.s1xxuo52bvxxxxxxxxxxoptions52 = s1xxuo52bvxxxxxxxxxxoptions52;
	}

	@Column(name = "purpose52", length = 159)
	@Size(max = 159)
	public String getS2xxup52bvxxxxxxxxxxpurpose52() {
		return this.s2xxup52bvxxxxxxxxxxpurpose52;
	}

	public void setS2xxup52bvxxxxxxxxxxpurpose52(
			String s2xxup52bvxxxxxxxxxxpurpose52) {
		this.s2xxup52bvxxxxxxxxxxpurpose52 = s2xxup52bvxxxxxxxxxxpurpose52;
	}

	@Column(name = "value52", length = 159)
	@Size(max = 159)
	public String getS3xxuv52bvxxxxxxxxxxvalue52() {
		return this.s3xxuv52bvxxxxxxxxxxvalue52;
	}

	public void setS3xxuv52bvxxxxxxxxxxvalue52(
			String s3xxuv52bvxxxxxxxxxxvalue52) {
		this.s3xxuv52bvxxxxxxxxxxvalue52 = s3xxuv52bvxxxxxxxxxxvalue52;
	}

	@Column(name = "options53", length = 159)
	@Size(max = 159)
	public String getS4xxuo53bvxxxxxxxxxxoptions53() {
		return this.s4xxuo53bvxxxxxxxxxxoptions53;
	}

	public void setS4xxuo53bvxxxxxxxxxxoptions53(
			String s4xxuo53bvxxxxxxxxxxoptions53) {
		this.s4xxuo53bvxxxxxxxxxxoptions53 = s4xxuo53bvxxxxxxxxxxoptions53;
	}

	@Column(name = "purpose53", length = 159)
	@Size(max = 159)
	public String getS5xxup53bvxxxxxxxxxxpurpose53() {
		return this.s5xxup53bvxxxxxxxxxxpurpose53;
	}

	public void setS5xxup53bvxxxxxxxxxxpurpose53(
			String s5xxup53bvxxxxxxxxxxpurpose53) {
		this.s5xxup53bvxxxxxxxxxxpurpose53 = s5xxup53bvxxxxxxxxxxpurpose53;
	}

	@Column(name = "value53", length = 159)
	@Size(max = 159)
	public String getS6xxuv53bvxxxxxxxxxxvalue53() {
		return this.s6xxuv53bvxxxxxxxxxxvalue53;
	}

	public void setS6xxuv53bvxxxxxxxxxxvalue53(
			String s6xxuv53bvxxxxxxxxxxvalue53) {
		this.s6xxuv53bvxxxxxxxxxxvalue53 = s6xxuv53bvxxxxxxxxxxvalue53;
	}

	@Column(name = "options54", length = 159)
	@Size(max = 159)
	public String getS7xxuo54bvxxxxxxxxxxoptions54() {
		return this.s7xxuo54bvxxxxxxxxxxoptions54;
	}

	public void setS7xxuo54bvxxxxxxxxxxoptions54(
			String s7xxuo54bvxxxxxxxxxxoptions54) {
		this.s7xxuo54bvxxxxxxxxxxoptions54 = s7xxuo54bvxxxxxxxxxxoptions54;
	}

	@Column(name = "purpose54", length = 159)
	@Size(max = 159)
	public String getS8xxup54bvxxxxxxxxxxpurpose54() {
		return this.s8xxup54bvxxxxxxxxxxpurpose54;
	}

	public void setS8xxup54bvxxxxxxxxxxpurpose54(
			String s8xxup54bvxxxxxxxxxxpurpose54) {
		this.s8xxup54bvxxxxxxxxxxpurpose54 = s8xxup54bvxxxxxxxxxxpurpose54;
	}

	@Column(name = "value54", length = 159)
	@Size(max = 159)
	public String getS9xxuv54bvxxxxxxxxxxvalue54() {
		return this.s9xxuv54bvxxxxxxxxxxvalue54;
	}

	public void setS9xxuv54bvxxxxxxxxxxvalue54(
			String s9xxuv54bvxxxxxxxxxxvalue54) {
		this.s9xxuv54bvxxxxxxxxxxvalue54 = s9xxuv54bvxxxxxxxxxxvalue54;
	}

	@Column(name = "options55", length = 159)
	@Size(max = 159)
	public String getT1xxuo55bvxxxxxxxxxxoptions55() {
		return this.t1xxuo55bvxxxxxxxxxxoptions55;
	}

	public void setT1xxuo55bvxxxxxxxxxxoptions55(
			String t1xxuo55bvxxxxxxxxxxoptions55) {
		this.t1xxuo55bvxxxxxxxxxxoptions55 = t1xxuo55bvxxxxxxxxxxoptions55;
	}

	@Column(name = "purpose55", length = 159)
	@Size(max = 159)
	public String getT2xxup55bvxxxxxxxxxxpurpose55() {
		return this.t2xxup55bvxxxxxxxxxxpurpose55;
	}

	public void setT2xxup55bvxxxxxxxxxxpurpose55(
			String t2xxup55bvxxxxxxxxxxpurpose55) {
		this.t2xxup55bvxxxxxxxxxxpurpose55 = t2xxup55bvxxxxxxxxxxpurpose55;
	}

	@Column(name = "value55", length = 159)
	@Size(max = 159)
	public String getT3xxuv55bvxxxxxxxxxxvalue55() {
		return this.t3xxuv55bvxxxxxxxxxxvalue55;
	}

	public void setT3xxuv55bvxxxxxxxxxxvalue55(
			String t3xxuv55bvxxxxxxxxxxvalue55) {
		this.t3xxuv55bvxxxxxxxxxxvalue55 = t3xxuv55bvxxxxxxxxxxvalue55;
	}

	@Column(name = "options56", length = 159)
	@Size(max = 159)
	public String getT4xxuo56bvxxxxxxxxxxoptions56() {
		return this.t4xxuo56bvxxxxxxxxxxoptions56;
	}

	public void setT4xxuo56bvxxxxxxxxxxoptions56(
			String t4xxuo56bvxxxxxxxxxxoptions56) {
		this.t4xxuo56bvxxxxxxxxxxoptions56 = t4xxuo56bvxxxxxxxxxxoptions56;
	}

	@Column(name = "purpose56", length = 159)
	@Size(max = 159)
	public String getT5xxup56bvxxxxxxxxxxpurpose56() {
		return this.t5xxup56bvxxxxxxxxxxpurpose56;
	}

	public void setT5xxup56bvxxxxxxxxxxpurpose56(
			String t5xxup56bvxxxxxxxxxxpurpose56) {
		this.t5xxup56bvxxxxxxxxxxpurpose56 = t5xxup56bvxxxxxxxxxxpurpose56;
	}

	@Column(name = "value56", length = 159)
	@Size(max = 159)
	public String getT6xxuv56bvxxxxxxxxxxvalue56() {
		return this.t6xxuv56bvxxxxxxxxxxvalue56;
	}

	public void setT6xxuv56bvxxxxxxxxxxvalue56(
			String t6xxuv56bvxxxxxxxxxxvalue56) {
		this.t6xxuv56bvxxxxxxxxxxvalue56 = t6xxuv56bvxxxxxxxxxxvalue56;
	}

	@Column(name = "options57", length = 159)
	@Size(max = 159)
	public String getT7xxuo57bvxxxxxxxxxxoptions57() {
		return this.t7xxuo57bvxxxxxxxxxxoptions57;
	}

	public void setT7xxuo57bvxxxxxxxxxxoptions57(
			String t7xxuo57bvxxxxxxxxxxoptions57) {
		this.t7xxuo57bvxxxxxxxxxxoptions57 = t7xxuo57bvxxxxxxxxxxoptions57;
	}

	@Column(name = "purpose57", length = 159)
	@Size(max = 159)
	public String getT8xxup57bvxxxxxxxxxxpurpose57() {
		return this.t8xxup57bvxxxxxxxxxxpurpose57;
	}

	public void setT8xxup57bvxxxxxxxxxxpurpose57(
			String t8xxup57bvxxxxxxxxxxpurpose57) {
		this.t8xxup57bvxxxxxxxxxxpurpose57 = t8xxup57bvxxxxxxxxxxpurpose57;
	}

	@Column(name = "value57", length = 159)
	@Size(max = 159)
	public String getT9xxuv57bvxxxxxxxxxxvalue57() {
		return this.t9xxuv57bvxxxxxxxxxxvalue57;
	}

	public void setT9xxuv57bvxxxxxxxxxxvalue57(
			String t9xxuv57bvxxxxxxxxxxvalue57) {
		this.t9xxuv57bvxxxxxxxxxxvalue57 = t9xxuv57bvxxxxxxxxxxvalue57;
	}

	@Column(name = "options58", length = 159)
	@Size(max = 159)
	public String getU1xxuo58bvxxxxxxxxxxoptions58() {
		return this.u1xxuo58bvxxxxxxxxxxoptions58;
	}

	public void setU1xxuo58bvxxxxxxxxxxoptions58(
			String u1xxuo58bvxxxxxxxxxxoptions58) {
		this.u1xxuo58bvxxxxxxxxxxoptions58 = u1xxuo58bvxxxxxxxxxxoptions58;
	}

	@Column(name = "purpose58", length = 159)
	@Size(max = 159)
	public String getU2xxup58bvxxxxxxxxxxpurpose58() {
		return this.u2xxup58bvxxxxxxxxxxpurpose58;
	}

	public void setU2xxup58bvxxxxxxxxxxpurpose58(
			String u2xxup58bvxxxxxxxxxxpurpose58) {
		this.u2xxup58bvxxxxxxxxxxpurpose58 = u2xxup58bvxxxxxxxxxxpurpose58;
	}

	@Column(name = "value58", length = 159)
	@Size(max = 159)
	public String getU3xxuv58bvxxxxxxxxxxvalue58() {
		return this.u3xxuv58bvxxxxxxxxxxvalue58;
	}

	public void setU3xxuv58bvxxxxxxxxxxvalue58(
			String u3xxuv58bvxxxxxxxxxxvalue58) {
		this.u3xxuv58bvxxxxxxxxxxvalue58 = u3xxuv58bvxxxxxxxxxxvalue58;
	}

	@Column(name = "options59", length = 159)
	@Size(max = 159)
	public String getU4xxuo59bvxxxxxxxxxxoptions59() {
		return this.u4xxuo59bvxxxxxxxxxxoptions59;
	}

	public void setU4xxuo59bvxxxxxxxxxxoptions59(
			String u4xxuo59bvxxxxxxxxxxoptions59) {
		this.u4xxuo59bvxxxxxxxxxxoptions59 = u4xxuo59bvxxxxxxxxxxoptions59;
	}

	@Column(name = "purpose59", length = 159)
	@Size(max = 159)
	public String getU5xxup59bvxxxxxxxxxxpurpose59() {
		return this.u5xxup59bvxxxxxxxxxxpurpose59;
	}

	public void setU5xxup59bvxxxxxxxxxxpurpose59(
			String u5xxup59bvxxxxxxxxxxpurpose59) {
		this.u5xxup59bvxxxxxxxxxxpurpose59 = u5xxup59bvxxxxxxxxxxpurpose59;
	}

	@Column(name = "value59", length = 159)
	@Size(max = 159)
	public String getU6xxuv59bvxxxxxxxxxxvalue59() {
		return this.u6xxuv59bvxxxxxxxxxxvalue59;
	}

	public void setU6xxuv59bvxxxxxxxxxxvalue59(
			String u6xxuv59bvxxxxxxxxxxvalue59) {
		this.u6xxuv59bvxxxxxxxxxxvalue59 = u6xxuv59bvxxxxxxxxxxvalue59;
	}

	@Column(name = "options60", length = 159)
	@Size(max = 159)
	public String getU7xxuo60bvxxxxxxxxxxoptions60() {
		return this.u7xxuo60bvxxxxxxxxxxoptions60;
	}

	public void setU7xxuo60bvxxxxxxxxxxoptions60(
			String u7xxuo60bvxxxxxxxxxxoptions60) {
		this.u7xxuo60bvxxxxxxxxxxoptions60 = u7xxuo60bvxxxxxxxxxxoptions60;
	}

	@Column(name = "purpose60", length = 159)
	@Size(max = 159)
	public String getU8xxup60bvxxxxxxxxxxpurpose60() {
		return this.u8xxup60bvxxxxxxxxxxpurpose60;
	}

	public void setU8xxup60bvxxxxxxxxxxpurpose60(
			String u8xxup60bvxxxxxxxxxxpurpose60) {
		this.u8xxup60bvxxxxxxxxxxpurpose60 = u8xxup60bvxxxxxxxxxxpurpose60;
	}

	@Column(name = "value60", length = 159)
	@Size(max = 159)
	public String getU9xxuv60bvxxxxxxxxxxvalue60() {
		return this.u9xxuv60bvxxxxxxxxxxvalue60;
	}

	public void setU9xxuv60bvxxxxxxxxxxvalue60(
			String u9xxuv60bvxxxxxxxxxxvalue60) {
		this.u9xxuv60bvxxxxxxxxxxvalue60 = u9xxuv60bvxxxxxxxxxxvalue60;
	}

	@Column(name = "options61", length = 159)
	@Size(max = 159)
	public String getV1xxuo61bvxxxxxxxxxxoptions61() {
		return this.v1xxuo61bvxxxxxxxxxxoptions61;
	}

	public void setV1xxuo61bvxxxxxxxxxxoptions61(
			String v1xxuo61bvxxxxxxxxxxoptions61) {
		this.v1xxuo61bvxxxxxxxxxxoptions61 = v1xxuo61bvxxxxxxxxxxoptions61;
	}

	@Column(name = "purpose61", length = 159)
	@Size(max = 159)
	public String getV2xxup61bvxxxxxxxxxxpurpose61() {
		return this.v2xxup61bvxxxxxxxxxxpurpose61;
	}

	public void setV2xxup61bvxxxxxxxxxxpurpose61(
			String v2xxup61bvxxxxxxxxxxpurpose61) {
		this.v2xxup61bvxxxxxxxxxxpurpose61 = v2xxup61bvxxxxxxxxxxpurpose61;
	}

	@Column(name = "value61", length = 159)
	@Size(max = 159)
	public String getV3xxuv61bvxxxxxxxxxxvalue61() {
		return this.v3xxuv61bvxxxxxxxxxxvalue61;
	}

	public void setV3xxuv61bvxxxxxxxxxxvalue61(
			String v3xxuv61bvxxxxxxxxxxvalue61) {
		this.v3xxuv61bvxxxxxxxxxxvalue61 = v3xxuv61bvxxxxxxxxxxvalue61;
	}

	@Column(name = "statusfl")
	public Integer getZ1xxzzfxhhxxxxxxxxxxstatusfl() {
		return this.z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZ1xxzzfxhhxxxxxxxxxxstatusfl(
			Integer z1xxzzfxhhxxxxxxxxxxstatusfl) {
		this.z1xxzzfxhhxxxxxxxxxxstatusfl = z1xxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZ2xxcztxlxxxxxxxxxxxstatusfldt() {
		return this.z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZ2xxcztxlxxxxxxxxxxxstatusfldt(
			Date z2xxcztxlxxxxxxxxxxxstatusfldt) {
		this.z2xxcztxlxxxxxxxxxxxstatusfldt = z2xxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "notes", length = 60)
	@Size(max = 60)
	public String getY9xxuznxbvxxxxxxxxxxnotes() {
		return this.y9xxuznxbvxxxxxxxxxxnotes;
	}

	public void setY9xxuznxbvxxxxxxxxxxnotes(String y9xxuznxbvxxxxxxxxxxnotes) {
		this.y9xxuznxbvxxxxxxxxxxnotes = y9xxuznxbvxxxxxxxxxxnotes;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ3xxutoxlhxxxxxxxxxxowner() {
		return this.z3xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ3xxutoxlhxxxxxxxxxxowner(String z3xxutoxlhxxxxxxxxxxowner) {
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

}
