package com.rcomputer.genapp.model;
// Generated 26-May-2024 9:51:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Yxxxch5a1xhhxxhxxxxxtruefalse generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "truefalse")
public class Yxxxch5a1xhhxxhxxxxxtruefalse implements java.io.Serializable {

	private Integer a0xxuobxbxxxxxxxxxxxsid;
	private String a0xxukrdbvxxxxxxxxxxtablename;
	private String a1xxuxxxbvxxxxxxxxxxqualifier;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow001;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow002;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow003;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow004;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow005;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow006;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow007;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow008;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow009;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow010;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow011;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow012;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow013;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow014;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow015;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow016;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow017;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow018;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow019;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow020;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow021;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow022;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow023;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow024;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow025;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow026;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow027;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow028;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow029;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow030;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow031;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow032;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow033;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow034;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow035;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow036;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow037;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow038;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow039;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow040;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow041;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow042;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow043;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow044;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow045;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow046;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow047;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow048;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow049;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow050;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow051;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow052;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow053;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow054;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow055;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow056;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow057;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow058;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow059;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow060;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow061;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow062;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow063;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow064;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow065;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow066;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow067;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow068;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow069;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow070;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow071;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow072;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow073;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow074;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow075;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow076;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow077;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow078;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow079;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow080;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow081;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow082;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow083;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow084;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow085;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow086;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow087;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow088;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow089;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow090;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow091;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow092;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow093;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow094;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow095;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow096;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow097;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow098;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow099;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow100;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow101;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow102;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow103;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow104;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow105;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow106;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow107;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow108;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow109;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow110;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow111;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow112;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow113;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow114;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow115;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow116;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow117;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow118;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow119;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow120;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow121;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow122;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow123;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow124;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow125;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow126;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow127;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow128;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow129;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow130;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow131;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow132;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow133;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow134;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow135;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow136;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow137;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow138;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow139;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow140;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow141;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow142;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow143;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow144;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow145;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow146;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow147;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow148;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow149;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow150;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow151;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow152;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow153;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow154;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow155;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow156;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow157;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow158;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow159;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow160;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow161;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow162;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow163;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow164;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow165;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow166;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow167;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow168;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow169;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow170;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow171;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow172;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow173;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow174;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow175;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow176;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow177;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow178;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow179;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow180;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow181;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow182;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow183;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow184;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow185;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow186;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow187;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow188;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow189;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow190;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow191;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow192;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow193;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow194;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow195;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow196;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow197;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow198;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow199;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow200;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow201;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow202;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow203;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow204;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow205;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow206;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow207;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow208;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow209;
	private Boolean a1xxyxxxbvxxxxxxxxxxshow210;
	private Integer zixxzzfxhhxxxxxxxxxxstatusfl;
	private Date zjxxcztxlxxxxxxxxxxxstatusfldt;
	private String z3xxutoxlhxxxxxxxxxxowner;
	private String zzxxu2oxxhxxxxxxxxxxowner2;

	public Yxxxch5a1xhhxxhxxxxxtruefalse() {
	}

	public Yxxxch5a1xhhxxhxxxxxtruefalse(String a0xxukrdbvxxxxxxxxxxtablename,
			String a1xxuxxxbvxxxxxxxxxxqualifier,
			Boolean a1xxyxxxbvxxxxxxxxxxshow001,
			Boolean a1xxyxxxbvxxxxxxxxxxshow002,
			Boolean a1xxyxxxbvxxxxxxxxxxshow003,
			Boolean a1xxyxxxbvxxxxxxxxxxshow004,
			Boolean a1xxyxxxbvxxxxxxxxxxshow005,
			Boolean a1xxyxxxbvxxxxxxxxxxshow006,
			Boolean a1xxyxxxbvxxxxxxxxxxshow007,
			Boolean a1xxyxxxbvxxxxxxxxxxshow008,
			Boolean a1xxyxxxbvxxxxxxxxxxshow009,
			Boolean a1xxyxxxbvxxxxxxxxxxshow010,
			Boolean a1xxyxxxbvxxxxxxxxxxshow011,
			Boolean a1xxyxxxbvxxxxxxxxxxshow012,
			Boolean a1xxyxxxbvxxxxxxxxxxshow013,
			Boolean a1xxyxxxbvxxxxxxxxxxshow014,
			Boolean a1xxyxxxbvxxxxxxxxxxshow015,
			Boolean a1xxyxxxbvxxxxxxxxxxshow016,
			Boolean a1xxyxxxbvxxxxxxxxxxshow017,
			Boolean a1xxyxxxbvxxxxxxxxxxshow018,
			Boolean a1xxyxxxbvxxxxxxxxxxshow019,
			Boolean a1xxyxxxbvxxxxxxxxxxshow020,
			Boolean a1xxyxxxbvxxxxxxxxxxshow021,
			Boolean a1xxyxxxbvxxxxxxxxxxshow022,
			Boolean a1xxyxxxbvxxxxxxxxxxshow023,
			Boolean a1xxyxxxbvxxxxxxxxxxshow024,
			Boolean a1xxyxxxbvxxxxxxxxxxshow025,
			Boolean a1xxyxxxbvxxxxxxxxxxshow026,
			Boolean a1xxyxxxbvxxxxxxxxxxshow027,
			Boolean a1xxyxxxbvxxxxxxxxxxshow028,
			Boolean a1xxyxxxbvxxxxxxxxxxshow029,
			Boolean a1xxyxxxbvxxxxxxxxxxshow030,
			Boolean a1xxyxxxbvxxxxxxxxxxshow031,
			Boolean a1xxyxxxbvxxxxxxxxxxshow032,
			Boolean a1xxyxxxbvxxxxxxxxxxshow033,
			Boolean a1xxyxxxbvxxxxxxxxxxshow034,
			Boolean a1xxyxxxbvxxxxxxxxxxshow035,
			Boolean a1xxyxxxbvxxxxxxxxxxshow036,
			Boolean a1xxyxxxbvxxxxxxxxxxshow037,
			Boolean a1xxyxxxbvxxxxxxxxxxshow038,
			Boolean a1xxyxxxbvxxxxxxxxxxshow039,
			Boolean a1xxyxxxbvxxxxxxxxxxshow040,
			Boolean a1xxyxxxbvxxxxxxxxxxshow041,
			Boolean a1xxyxxxbvxxxxxxxxxxshow042,
			Boolean a1xxyxxxbvxxxxxxxxxxshow043,
			Boolean a1xxyxxxbvxxxxxxxxxxshow044,
			Boolean a1xxyxxxbvxxxxxxxxxxshow045,
			Boolean a1xxyxxxbvxxxxxxxxxxshow046,
			Boolean a1xxyxxxbvxxxxxxxxxxshow047,
			Boolean a1xxyxxxbvxxxxxxxxxxshow048,
			Boolean a1xxyxxxbvxxxxxxxxxxshow049,
			Boolean a1xxyxxxbvxxxxxxxxxxshow050,
			Boolean a1xxyxxxbvxxxxxxxxxxshow051,
			Boolean a1xxyxxxbvxxxxxxxxxxshow052,
			Boolean a1xxyxxxbvxxxxxxxxxxshow053,
			Boolean a1xxyxxxbvxxxxxxxxxxshow054,
			Boolean a1xxyxxxbvxxxxxxxxxxshow055,
			Boolean a1xxyxxxbvxxxxxxxxxxshow056,
			Boolean a1xxyxxxbvxxxxxxxxxxshow057,
			Boolean a1xxyxxxbvxxxxxxxxxxshow058,
			Boolean a1xxyxxxbvxxxxxxxxxxshow059,
			Boolean a1xxyxxxbvxxxxxxxxxxshow060,
			Boolean a1xxyxxxbvxxxxxxxxxxshow061,
			Boolean a1xxyxxxbvxxxxxxxxxxshow062,
			Boolean a1xxyxxxbvxxxxxxxxxxshow063,
			Boolean a1xxyxxxbvxxxxxxxxxxshow064,
			Boolean a1xxyxxxbvxxxxxxxxxxshow065,
			Boolean a1xxyxxxbvxxxxxxxxxxshow066,
			Boolean a1xxyxxxbvxxxxxxxxxxshow067,
			Boolean a1xxyxxxbvxxxxxxxxxxshow068,
			Boolean a1xxyxxxbvxxxxxxxxxxshow069,
			Boolean a1xxyxxxbvxxxxxxxxxxshow070,
			Boolean a1xxyxxxbvxxxxxxxxxxshow071,
			Boolean a1xxyxxxbvxxxxxxxxxxshow072,
			Boolean a1xxyxxxbvxxxxxxxxxxshow073,
			Boolean a1xxyxxxbvxxxxxxxxxxshow074,
			Boolean a1xxyxxxbvxxxxxxxxxxshow075,
			Boolean a1xxyxxxbvxxxxxxxxxxshow076,
			Boolean a1xxyxxxbvxxxxxxxxxxshow077,
			Boolean a1xxyxxxbvxxxxxxxxxxshow078,
			Boolean a1xxyxxxbvxxxxxxxxxxshow079,
			Boolean a1xxyxxxbvxxxxxxxxxxshow080,
			Boolean a1xxyxxxbvxxxxxxxxxxshow081,
			Boolean a1xxyxxxbvxxxxxxxxxxshow082,
			Boolean a1xxyxxxbvxxxxxxxxxxshow083,
			Boolean a1xxyxxxbvxxxxxxxxxxshow084,
			Boolean a1xxyxxxbvxxxxxxxxxxshow085,
			Boolean a1xxyxxxbvxxxxxxxxxxshow086,
			Boolean a1xxyxxxbvxxxxxxxxxxshow087,
			Boolean a1xxyxxxbvxxxxxxxxxxshow088,
			Boolean a1xxyxxxbvxxxxxxxxxxshow089,
			Boolean a1xxyxxxbvxxxxxxxxxxshow090,
			Boolean a1xxyxxxbvxxxxxxxxxxshow091,
			Boolean a1xxyxxxbvxxxxxxxxxxshow092,
			Boolean a1xxyxxxbvxxxxxxxxxxshow093,
			Boolean a1xxyxxxbvxxxxxxxxxxshow094,
			Boolean a1xxyxxxbvxxxxxxxxxxshow095,
			Boolean a1xxyxxxbvxxxxxxxxxxshow096,
			Boolean a1xxyxxxbvxxxxxxxxxxshow097,
			Boolean a1xxyxxxbvxxxxxxxxxxshow098,
			Boolean a1xxyxxxbvxxxxxxxxxxshow099,
			Boolean a1xxyxxxbvxxxxxxxxxxshow100,
			Boolean a1xxyxxxbvxxxxxxxxxxshow101,
			Boolean a1xxyxxxbvxxxxxxxxxxshow102,
			Boolean a1xxyxxxbvxxxxxxxxxxshow103,
			Boolean a1xxyxxxbvxxxxxxxxxxshow104,
			Boolean a1xxyxxxbvxxxxxxxxxxshow105,
			Boolean a1xxyxxxbvxxxxxxxxxxshow106,
			Boolean a1xxyxxxbvxxxxxxxxxxshow107,
			Boolean a1xxyxxxbvxxxxxxxxxxshow108,
			Boolean a1xxyxxxbvxxxxxxxxxxshow109,
			Boolean a1xxyxxxbvxxxxxxxxxxshow110,
			Boolean a1xxyxxxbvxxxxxxxxxxshow111,
			Boolean a1xxyxxxbvxxxxxxxxxxshow112,
			Boolean a1xxyxxxbvxxxxxxxxxxshow113,
			Boolean a1xxyxxxbvxxxxxxxxxxshow114,
			Boolean a1xxyxxxbvxxxxxxxxxxshow115,
			Boolean a1xxyxxxbvxxxxxxxxxxshow116,
			Boolean a1xxyxxxbvxxxxxxxxxxshow117,
			Boolean a1xxyxxxbvxxxxxxxxxxshow118,
			Boolean a1xxyxxxbvxxxxxxxxxxshow119,
			Boolean a1xxyxxxbvxxxxxxxxxxshow120,
			Boolean a1xxyxxxbvxxxxxxxxxxshow121,
			Boolean a1xxyxxxbvxxxxxxxxxxshow122,
			Boolean a1xxyxxxbvxxxxxxxxxxshow123,
			Boolean a1xxyxxxbvxxxxxxxxxxshow124,
			Boolean a1xxyxxxbvxxxxxxxxxxshow125,
			Boolean a1xxyxxxbvxxxxxxxxxxshow126,
			Boolean a1xxyxxxbvxxxxxxxxxxshow127,
			Boolean a1xxyxxxbvxxxxxxxxxxshow128,
			Boolean a1xxyxxxbvxxxxxxxxxxshow129,
			Boolean a1xxyxxxbvxxxxxxxxxxshow130,
			Boolean a1xxyxxxbvxxxxxxxxxxshow131,
			Boolean a1xxyxxxbvxxxxxxxxxxshow132,
			Boolean a1xxyxxxbvxxxxxxxxxxshow133,
			Boolean a1xxyxxxbvxxxxxxxxxxshow134,
			Boolean a1xxyxxxbvxxxxxxxxxxshow135,
			Boolean a1xxyxxxbvxxxxxxxxxxshow136,
			Boolean a1xxyxxxbvxxxxxxxxxxshow137,
			Boolean a1xxyxxxbvxxxxxxxxxxshow138,
			Boolean a1xxyxxxbvxxxxxxxxxxshow139,
			Boolean a1xxyxxxbvxxxxxxxxxxshow140,
			Boolean a1xxyxxxbvxxxxxxxxxxshow141,
			Boolean a1xxyxxxbvxxxxxxxxxxshow142,
			Boolean a1xxyxxxbvxxxxxxxxxxshow143,
			Boolean a1xxyxxxbvxxxxxxxxxxshow144,
			Boolean a1xxyxxxbvxxxxxxxxxxshow145,
			Boolean a1xxyxxxbvxxxxxxxxxxshow146,
			Boolean a1xxyxxxbvxxxxxxxxxxshow147,
			Boolean a1xxyxxxbvxxxxxxxxxxshow148,
			Boolean a1xxyxxxbvxxxxxxxxxxshow149,
			Boolean a1xxyxxxbvxxxxxxxxxxshow150,
			Boolean a1xxyxxxbvxxxxxxxxxxshow151,
			Boolean a1xxyxxxbvxxxxxxxxxxshow152,
			Boolean a1xxyxxxbvxxxxxxxxxxshow153,
			Boolean a1xxyxxxbvxxxxxxxxxxshow154,
			Boolean a1xxyxxxbvxxxxxxxxxxshow155,
			Boolean a1xxyxxxbvxxxxxxxxxxshow156,
			Boolean a1xxyxxxbvxxxxxxxxxxshow157,
			Boolean a1xxyxxxbvxxxxxxxxxxshow158,
			Boolean a1xxyxxxbvxxxxxxxxxxshow159,
			Boolean a1xxyxxxbvxxxxxxxxxxshow160,
			Boolean a1xxyxxxbvxxxxxxxxxxshow161,
			Boolean a1xxyxxxbvxxxxxxxxxxshow162,
			Boolean a1xxyxxxbvxxxxxxxxxxshow163,
			Boolean a1xxyxxxbvxxxxxxxxxxshow164,
			Boolean a1xxyxxxbvxxxxxxxxxxshow165,
			Boolean a1xxyxxxbvxxxxxxxxxxshow166,
			Boolean a1xxyxxxbvxxxxxxxxxxshow167,
			Boolean a1xxyxxxbvxxxxxxxxxxshow168,
			Boolean a1xxyxxxbvxxxxxxxxxxshow169,
			Boolean a1xxyxxxbvxxxxxxxxxxshow170,
			Boolean a1xxyxxxbvxxxxxxxxxxshow171,
			Boolean a1xxyxxxbvxxxxxxxxxxshow172,
			Boolean a1xxyxxxbvxxxxxxxxxxshow173,
			Boolean a1xxyxxxbvxxxxxxxxxxshow174,
			Boolean a1xxyxxxbvxxxxxxxxxxshow175,
			Boolean a1xxyxxxbvxxxxxxxxxxshow176,
			Boolean a1xxyxxxbvxxxxxxxxxxshow177,
			Boolean a1xxyxxxbvxxxxxxxxxxshow178,
			Boolean a1xxyxxxbvxxxxxxxxxxshow179,
			Boolean a1xxyxxxbvxxxxxxxxxxshow180,
			Boolean a1xxyxxxbvxxxxxxxxxxshow181,
			Boolean a1xxyxxxbvxxxxxxxxxxshow182,
			Boolean a1xxyxxxbvxxxxxxxxxxshow183,
			Boolean a1xxyxxxbvxxxxxxxxxxshow184,
			Boolean a1xxyxxxbvxxxxxxxxxxshow185,
			Boolean a1xxyxxxbvxxxxxxxxxxshow186,
			Boolean a1xxyxxxbvxxxxxxxxxxshow187,
			Boolean a1xxyxxxbvxxxxxxxxxxshow188,
			Boolean a1xxyxxxbvxxxxxxxxxxshow189,
			Boolean a1xxyxxxbvxxxxxxxxxxshow190,
			Boolean a1xxyxxxbvxxxxxxxxxxshow191,
			Boolean a1xxyxxxbvxxxxxxxxxxshow192,
			Boolean a1xxyxxxbvxxxxxxxxxxshow193,
			Boolean a1xxyxxxbvxxxxxxxxxxshow194,
			Boolean a1xxyxxxbvxxxxxxxxxxshow195,
			Boolean a1xxyxxxbvxxxxxxxxxxshow196,
			Boolean a1xxyxxxbvxxxxxxxxxxshow197,
			Boolean a1xxyxxxbvxxxxxxxxxxshow198,
			Boolean a1xxyxxxbvxxxxxxxxxxshow199,
			Boolean a1xxyxxxbvxxxxxxxxxxshow200,
			Boolean a1xxyxxxbvxxxxxxxxxxshow201,
			Boolean a1xxyxxxbvxxxxxxxxxxshow202,
			Boolean a1xxyxxxbvxxxxxxxxxxshow203,
			Boolean a1xxyxxxbvxxxxxxxxxxshow204,
			Boolean a1xxyxxxbvxxxxxxxxxxshow205,
			Boolean a1xxyxxxbvxxxxxxxxxxshow206,
			Boolean a1xxyxxxbvxxxxxxxxxxshow207,
			Boolean a1xxyxxxbvxxxxxxxxxxshow208,
			Boolean a1xxyxxxbvxxxxxxxxxxshow209,
			Boolean a1xxyxxxbvxxxxxxxxxxshow210,
			Integer zixxzzfxhhxxxxxxxxxxstatusfl,
			Date zjxxcztxlxxxxxxxxxxxstatusfldt,
			String z3xxutoxlhxxxxxxxxxxowner, String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.a0xxukrdbvxxxxxxxxxxtablename = a0xxukrdbvxxxxxxxxxxtablename;
		this.a1xxuxxxbvxxxxxxxxxxqualifier = a1xxuxxxbvxxxxxxxxxxqualifier;
		this.a1xxyxxxbvxxxxxxxxxxshow001 = a1xxyxxxbvxxxxxxxxxxshow001;
		this.a1xxyxxxbvxxxxxxxxxxshow002 = a1xxyxxxbvxxxxxxxxxxshow002;
		this.a1xxyxxxbvxxxxxxxxxxshow003 = a1xxyxxxbvxxxxxxxxxxshow003;
		this.a1xxyxxxbvxxxxxxxxxxshow004 = a1xxyxxxbvxxxxxxxxxxshow004;
		this.a1xxyxxxbvxxxxxxxxxxshow005 = a1xxyxxxbvxxxxxxxxxxshow005;
		this.a1xxyxxxbvxxxxxxxxxxshow006 = a1xxyxxxbvxxxxxxxxxxshow006;
		this.a1xxyxxxbvxxxxxxxxxxshow007 = a1xxyxxxbvxxxxxxxxxxshow007;
		this.a1xxyxxxbvxxxxxxxxxxshow008 = a1xxyxxxbvxxxxxxxxxxshow008;
		this.a1xxyxxxbvxxxxxxxxxxshow009 = a1xxyxxxbvxxxxxxxxxxshow009;
		this.a1xxyxxxbvxxxxxxxxxxshow010 = a1xxyxxxbvxxxxxxxxxxshow010;
		this.a1xxyxxxbvxxxxxxxxxxshow011 = a1xxyxxxbvxxxxxxxxxxshow011;
		this.a1xxyxxxbvxxxxxxxxxxshow012 = a1xxyxxxbvxxxxxxxxxxshow012;
		this.a1xxyxxxbvxxxxxxxxxxshow013 = a1xxyxxxbvxxxxxxxxxxshow013;
		this.a1xxyxxxbvxxxxxxxxxxshow014 = a1xxyxxxbvxxxxxxxxxxshow014;
		this.a1xxyxxxbvxxxxxxxxxxshow015 = a1xxyxxxbvxxxxxxxxxxshow015;
		this.a1xxyxxxbvxxxxxxxxxxshow016 = a1xxyxxxbvxxxxxxxxxxshow016;
		this.a1xxyxxxbvxxxxxxxxxxshow017 = a1xxyxxxbvxxxxxxxxxxshow017;
		this.a1xxyxxxbvxxxxxxxxxxshow018 = a1xxyxxxbvxxxxxxxxxxshow018;
		this.a1xxyxxxbvxxxxxxxxxxshow019 = a1xxyxxxbvxxxxxxxxxxshow019;
		this.a1xxyxxxbvxxxxxxxxxxshow020 = a1xxyxxxbvxxxxxxxxxxshow020;
		this.a1xxyxxxbvxxxxxxxxxxshow021 = a1xxyxxxbvxxxxxxxxxxshow021;
		this.a1xxyxxxbvxxxxxxxxxxshow022 = a1xxyxxxbvxxxxxxxxxxshow022;
		this.a1xxyxxxbvxxxxxxxxxxshow023 = a1xxyxxxbvxxxxxxxxxxshow023;
		this.a1xxyxxxbvxxxxxxxxxxshow024 = a1xxyxxxbvxxxxxxxxxxshow024;
		this.a1xxyxxxbvxxxxxxxxxxshow025 = a1xxyxxxbvxxxxxxxxxxshow025;
		this.a1xxyxxxbvxxxxxxxxxxshow026 = a1xxyxxxbvxxxxxxxxxxshow026;
		this.a1xxyxxxbvxxxxxxxxxxshow027 = a1xxyxxxbvxxxxxxxxxxshow027;
		this.a1xxyxxxbvxxxxxxxxxxshow028 = a1xxyxxxbvxxxxxxxxxxshow028;
		this.a1xxyxxxbvxxxxxxxxxxshow029 = a1xxyxxxbvxxxxxxxxxxshow029;
		this.a1xxyxxxbvxxxxxxxxxxshow030 = a1xxyxxxbvxxxxxxxxxxshow030;
		this.a1xxyxxxbvxxxxxxxxxxshow031 = a1xxyxxxbvxxxxxxxxxxshow031;
		this.a1xxyxxxbvxxxxxxxxxxshow032 = a1xxyxxxbvxxxxxxxxxxshow032;
		this.a1xxyxxxbvxxxxxxxxxxshow033 = a1xxyxxxbvxxxxxxxxxxshow033;
		this.a1xxyxxxbvxxxxxxxxxxshow034 = a1xxyxxxbvxxxxxxxxxxshow034;
		this.a1xxyxxxbvxxxxxxxxxxshow035 = a1xxyxxxbvxxxxxxxxxxshow035;
		this.a1xxyxxxbvxxxxxxxxxxshow036 = a1xxyxxxbvxxxxxxxxxxshow036;
		this.a1xxyxxxbvxxxxxxxxxxshow037 = a1xxyxxxbvxxxxxxxxxxshow037;
		this.a1xxyxxxbvxxxxxxxxxxshow038 = a1xxyxxxbvxxxxxxxxxxshow038;
		this.a1xxyxxxbvxxxxxxxxxxshow039 = a1xxyxxxbvxxxxxxxxxxshow039;
		this.a1xxyxxxbvxxxxxxxxxxshow040 = a1xxyxxxbvxxxxxxxxxxshow040;
		this.a1xxyxxxbvxxxxxxxxxxshow041 = a1xxyxxxbvxxxxxxxxxxshow041;
		this.a1xxyxxxbvxxxxxxxxxxshow042 = a1xxyxxxbvxxxxxxxxxxshow042;
		this.a1xxyxxxbvxxxxxxxxxxshow043 = a1xxyxxxbvxxxxxxxxxxshow043;
		this.a1xxyxxxbvxxxxxxxxxxshow044 = a1xxyxxxbvxxxxxxxxxxshow044;
		this.a1xxyxxxbvxxxxxxxxxxshow045 = a1xxyxxxbvxxxxxxxxxxshow045;
		this.a1xxyxxxbvxxxxxxxxxxshow046 = a1xxyxxxbvxxxxxxxxxxshow046;
		this.a1xxyxxxbvxxxxxxxxxxshow047 = a1xxyxxxbvxxxxxxxxxxshow047;
		this.a1xxyxxxbvxxxxxxxxxxshow048 = a1xxyxxxbvxxxxxxxxxxshow048;
		this.a1xxyxxxbvxxxxxxxxxxshow049 = a1xxyxxxbvxxxxxxxxxxshow049;
		this.a1xxyxxxbvxxxxxxxxxxshow050 = a1xxyxxxbvxxxxxxxxxxshow050;
		this.a1xxyxxxbvxxxxxxxxxxshow051 = a1xxyxxxbvxxxxxxxxxxshow051;
		this.a1xxyxxxbvxxxxxxxxxxshow052 = a1xxyxxxbvxxxxxxxxxxshow052;
		this.a1xxyxxxbvxxxxxxxxxxshow053 = a1xxyxxxbvxxxxxxxxxxshow053;
		this.a1xxyxxxbvxxxxxxxxxxshow054 = a1xxyxxxbvxxxxxxxxxxshow054;
		this.a1xxyxxxbvxxxxxxxxxxshow055 = a1xxyxxxbvxxxxxxxxxxshow055;
		this.a1xxyxxxbvxxxxxxxxxxshow056 = a1xxyxxxbvxxxxxxxxxxshow056;
		this.a1xxyxxxbvxxxxxxxxxxshow057 = a1xxyxxxbvxxxxxxxxxxshow057;
		this.a1xxyxxxbvxxxxxxxxxxshow058 = a1xxyxxxbvxxxxxxxxxxshow058;
		this.a1xxyxxxbvxxxxxxxxxxshow059 = a1xxyxxxbvxxxxxxxxxxshow059;
		this.a1xxyxxxbvxxxxxxxxxxshow060 = a1xxyxxxbvxxxxxxxxxxshow060;
		this.a1xxyxxxbvxxxxxxxxxxshow061 = a1xxyxxxbvxxxxxxxxxxshow061;
		this.a1xxyxxxbvxxxxxxxxxxshow062 = a1xxyxxxbvxxxxxxxxxxshow062;
		this.a1xxyxxxbvxxxxxxxxxxshow063 = a1xxyxxxbvxxxxxxxxxxshow063;
		this.a1xxyxxxbvxxxxxxxxxxshow064 = a1xxyxxxbvxxxxxxxxxxshow064;
		this.a1xxyxxxbvxxxxxxxxxxshow065 = a1xxyxxxbvxxxxxxxxxxshow065;
		this.a1xxyxxxbvxxxxxxxxxxshow066 = a1xxyxxxbvxxxxxxxxxxshow066;
		this.a1xxyxxxbvxxxxxxxxxxshow067 = a1xxyxxxbvxxxxxxxxxxshow067;
		this.a1xxyxxxbvxxxxxxxxxxshow068 = a1xxyxxxbvxxxxxxxxxxshow068;
		this.a1xxyxxxbvxxxxxxxxxxshow069 = a1xxyxxxbvxxxxxxxxxxshow069;
		this.a1xxyxxxbvxxxxxxxxxxshow070 = a1xxyxxxbvxxxxxxxxxxshow070;
		this.a1xxyxxxbvxxxxxxxxxxshow071 = a1xxyxxxbvxxxxxxxxxxshow071;
		this.a1xxyxxxbvxxxxxxxxxxshow072 = a1xxyxxxbvxxxxxxxxxxshow072;
		this.a1xxyxxxbvxxxxxxxxxxshow073 = a1xxyxxxbvxxxxxxxxxxshow073;
		this.a1xxyxxxbvxxxxxxxxxxshow074 = a1xxyxxxbvxxxxxxxxxxshow074;
		this.a1xxyxxxbvxxxxxxxxxxshow075 = a1xxyxxxbvxxxxxxxxxxshow075;
		this.a1xxyxxxbvxxxxxxxxxxshow076 = a1xxyxxxbvxxxxxxxxxxshow076;
		this.a1xxyxxxbvxxxxxxxxxxshow077 = a1xxyxxxbvxxxxxxxxxxshow077;
		this.a1xxyxxxbvxxxxxxxxxxshow078 = a1xxyxxxbvxxxxxxxxxxshow078;
		this.a1xxyxxxbvxxxxxxxxxxshow079 = a1xxyxxxbvxxxxxxxxxxshow079;
		this.a1xxyxxxbvxxxxxxxxxxshow080 = a1xxyxxxbvxxxxxxxxxxshow080;
		this.a1xxyxxxbvxxxxxxxxxxshow081 = a1xxyxxxbvxxxxxxxxxxshow081;
		this.a1xxyxxxbvxxxxxxxxxxshow082 = a1xxyxxxbvxxxxxxxxxxshow082;
		this.a1xxyxxxbvxxxxxxxxxxshow083 = a1xxyxxxbvxxxxxxxxxxshow083;
		this.a1xxyxxxbvxxxxxxxxxxshow084 = a1xxyxxxbvxxxxxxxxxxshow084;
		this.a1xxyxxxbvxxxxxxxxxxshow085 = a1xxyxxxbvxxxxxxxxxxshow085;
		this.a1xxyxxxbvxxxxxxxxxxshow086 = a1xxyxxxbvxxxxxxxxxxshow086;
		this.a1xxyxxxbvxxxxxxxxxxshow087 = a1xxyxxxbvxxxxxxxxxxshow087;
		this.a1xxyxxxbvxxxxxxxxxxshow088 = a1xxyxxxbvxxxxxxxxxxshow088;
		this.a1xxyxxxbvxxxxxxxxxxshow089 = a1xxyxxxbvxxxxxxxxxxshow089;
		this.a1xxyxxxbvxxxxxxxxxxshow090 = a1xxyxxxbvxxxxxxxxxxshow090;
		this.a1xxyxxxbvxxxxxxxxxxshow091 = a1xxyxxxbvxxxxxxxxxxshow091;
		this.a1xxyxxxbvxxxxxxxxxxshow092 = a1xxyxxxbvxxxxxxxxxxshow092;
		this.a1xxyxxxbvxxxxxxxxxxshow093 = a1xxyxxxbvxxxxxxxxxxshow093;
		this.a1xxyxxxbvxxxxxxxxxxshow094 = a1xxyxxxbvxxxxxxxxxxshow094;
		this.a1xxyxxxbvxxxxxxxxxxshow095 = a1xxyxxxbvxxxxxxxxxxshow095;
		this.a1xxyxxxbvxxxxxxxxxxshow096 = a1xxyxxxbvxxxxxxxxxxshow096;
		this.a1xxyxxxbvxxxxxxxxxxshow097 = a1xxyxxxbvxxxxxxxxxxshow097;
		this.a1xxyxxxbvxxxxxxxxxxshow098 = a1xxyxxxbvxxxxxxxxxxshow098;
		this.a1xxyxxxbvxxxxxxxxxxshow099 = a1xxyxxxbvxxxxxxxxxxshow099;
		this.a1xxyxxxbvxxxxxxxxxxshow100 = a1xxyxxxbvxxxxxxxxxxshow100;
		this.a1xxyxxxbvxxxxxxxxxxshow101 = a1xxyxxxbvxxxxxxxxxxshow101;
		this.a1xxyxxxbvxxxxxxxxxxshow102 = a1xxyxxxbvxxxxxxxxxxshow102;
		this.a1xxyxxxbvxxxxxxxxxxshow103 = a1xxyxxxbvxxxxxxxxxxshow103;
		this.a1xxyxxxbvxxxxxxxxxxshow104 = a1xxyxxxbvxxxxxxxxxxshow104;
		this.a1xxyxxxbvxxxxxxxxxxshow105 = a1xxyxxxbvxxxxxxxxxxshow105;
		this.a1xxyxxxbvxxxxxxxxxxshow106 = a1xxyxxxbvxxxxxxxxxxshow106;
		this.a1xxyxxxbvxxxxxxxxxxshow107 = a1xxyxxxbvxxxxxxxxxxshow107;
		this.a1xxyxxxbvxxxxxxxxxxshow108 = a1xxyxxxbvxxxxxxxxxxshow108;
		this.a1xxyxxxbvxxxxxxxxxxshow109 = a1xxyxxxbvxxxxxxxxxxshow109;
		this.a1xxyxxxbvxxxxxxxxxxshow110 = a1xxyxxxbvxxxxxxxxxxshow110;
		this.a1xxyxxxbvxxxxxxxxxxshow111 = a1xxyxxxbvxxxxxxxxxxshow111;
		this.a1xxyxxxbvxxxxxxxxxxshow112 = a1xxyxxxbvxxxxxxxxxxshow112;
		this.a1xxyxxxbvxxxxxxxxxxshow113 = a1xxyxxxbvxxxxxxxxxxshow113;
		this.a1xxyxxxbvxxxxxxxxxxshow114 = a1xxyxxxbvxxxxxxxxxxshow114;
		this.a1xxyxxxbvxxxxxxxxxxshow115 = a1xxyxxxbvxxxxxxxxxxshow115;
		this.a1xxyxxxbvxxxxxxxxxxshow116 = a1xxyxxxbvxxxxxxxxxxshow116;
		this.a1xxyxxxbvxxxxxxxxxxshow117 = a1xxyxxxbvxxxxxxxxxxshow117;
		this.a1xxyxxxbvxxxxxxxxxxshow118 = a1xxyxxxbvxxxxxxxxxxshow118;
		this.a1xxyxxxbvxxxxxxxxxxshow119 = a1xxyxxxbvxxxxxxxxxxshow119;
		this.a1xxyxxxbvxxxxxxxxxxshow120 = a1xxyxxxbvxxxxxxxxxxshow120;
		this.a1xxyxxxbvxxxxxxxxxxshow121 = a1xxyxxxbvxxxxxxxxxxshow121;
		this.a1xxyxxxbvxxxxxxxxxxshow122 = a1xxyxxxbvxxxxxxxxxxshow122;
		this.a1xxyxxxbvxxxxxxxxxxshow123 = a1xxyxxxbvxxxxxxxxxxshow123;
		this.a1xxyxxxbvxxxxxxxxxxshow124 = a1xxyxxxbvxxxxxxxxxxshow124;
		this.a1xxyxxxbvxxxxxxxxxxshow125 = a1xxyxxxbvxxxxxxxxxxshow125;
		this.a1xxyxxxbvxxxxxxxxxxshow126 = a1xxyxxxbvxxxxxxxxxxshow126;
		this.a1xxyxxxbvxxxxxxxxxxshow127 = a1xxyxxxbvxxxxxxxxxxshow127;
		this.a1xxyxxxbvxxxxxxxxxxshow128 = a1xxyxxxbvxxxxxxxxxxshow128;
		this.a1xxyxxxbvxxxxxxxxxxshow129 = a1xxyxxxbvxxxxxxxxxxshow129;
		this.a1xxyxxxbvxxxxxxxxxxshow130 = a1xxyxxxbvxxxxxxxxxxshow130;
		this.a1xxyxxxbvxxxxxxxxxxshow131 = a1xxyxxxbvxxxxxxxxxxshow131;
		this.a1xxyxxxbvxxxxxxxxxxshow132 = a1xxyxxxbvxxxxxxxxxxshow132;
		this.a1xxyxxxbvxxxxxxxxxxshow133 = a1xxyxxxbvxxxxxxxxxxshow133;
		this.a1xxyxxxbvxxxxxxxxxxshow134 = a1xxyxxxbvxxxxxxxxxxshow134;
		this.a1xxyxxxbvxxxxxxxxxxshow135 = a1xxyxxxbvxxxxxxxxxxshow135;
		this.a1xxyxxxbvxxxxxxxxxxshow136 = a1xxyxxxbvxxxxxxxxxxshow136;
		this.a1xxyxxxbvxxxxxxxxxxshow137 = a1xxyxxxbvxxxxxxxxxxshow137;
		this.a1xxyxxxbvxxxxxxxxxxshow138 = a1xxyxxxbvxxxxxxxxxxshow138;
		this.a1xxyxxxbvxxxxxxxxxxshow139 = a1xxyxxxbvxxxxxxxxxxshow139;
		this.a1xxyxxxbvxxxxxxxxxxshow140 = a1xxyxxxbvxxxxxxxxxxshow140;
		this.a1xxyxxxbvxxxxxxxxxxshow141 = a1xxyxxxbvxxxxxxxxxxshow141;
		this.a1xxyxxxbvxxxxxxxxxxshow142 = a1xxyxxxbvxxxxxxxxxxshow142;
		this.a1xxyxxxbvxxxxxxxxxxshow143 = a1xxyxxxbvxxxxxxxxxxshow143;
		this.a1xxyxxxbvxxxxxxxxxxshow144 = a1xxyxxxbvxxxxxxxxxxshow144;
		this.a1xxyxxxbvxxxxxxxxxxshow145 = a1xxyxxxbvxxxxxxxxxxshow145;
		this.a1xxyxxxbvxxxxxxxxxxshow146 = a1xxyxxxbvxxxxxxxxxxshow146;
		this.a1xxyxxxbvxxxxxxxxxxshow147 = a1xxyxxxbvxxxxxxxxxxshow147;
		this.a1xxyxxxbvxxxxxxxxxxshow148 = a1xxyxxxbvxxxxxxxxxxshow148;
		this.a1xxyxxxbvxxxxxxxxxxshow149 = a1xxyxxxbvxxxxxxxxxxshow149;
		this.a1xxyxxxbvxxxxxxxxxxshow150 = a1xxyxxxbvxxxxxxxxxxshow150;
		this.a1xxyxxxbvxxxxxxxxxxshow151 = a1xxyxxxbvxxxxxxxxxxshow151;
		this.a1xxyxxxbvxxxxxxxxxxshow152 = a1xxyxxxbvxxxxxxxxxxshow152;
		this.a1xxyxxxbvxxxxxxxxxxshow153 = a1xxyxxxbvxxxxxxxxxxshow153;
		this.a1xxyxxxbvxxxxxxxxxxshow154 = a1xxyxxxbvxxxxxxxxxxshow154;
		this.a1xxyxxxbvxxxxxxxxxxshow155 = a1xxyxxxbvxxxxxxxxxxshow155;
		this.a1xxyxxxbvxxxxxxxxxxshow156 = a1xxyxxxbvxxxxxxxxxxshow156;
		this.a1xxyxxxbvxxxxxxxxxxshow157 = a1xxyxxxbvxxxxxxxxxxshow157;
		this.a1xxyxxxbvxxxxxxxxxxshow158 = a1xxyxxxbvxxxxxxxxxxshow158;
		this.a1xxyxxxbvxxxxxxxxxxshow159 = a1xxyxxxbvxxxxxxxxxxshow159;
		this.a1xxyxxxbvxxxxxxxxxxshow160 = a1xxyxxxbvxxxxxxxxxxshow160;
		this.a1xxyxxxbvxxxxxxxxxxshow161 = a1xxyxxxbvxxxxxxxxxxshow161;
		this.a1xxyxxxbvxxxxxxxxxxshow162 = a1xxyxxxbvxxxxxxxxxxshow162;
		this.a1xxyxxxbvxxxxxxxxxxshow163 = a1xxyxxxbvxxxxxxxxxxshow163;
		this.a1xxyxxxbvxxxxxxxxxxshow164 = a1xxyxxxbvxxxxxxxxxxshow164;
		this.a1xxyxxxbvxxxxxxxxxxshow165 = a1xxyxxxbvxxxxxxxxxxshow165;
		this.a1xxyxxxbvxxxxxxxxxxshow166 = a1xxyxxxbvxxxxxxxxxxshow166;
		this.a1xxyxxxbvxxxxxxxxxxshow167 = a1xxyxxxbvxxxxxxxxxxshow167;
		this.a1xxyxxxbvxxxxxxxxxxshow168 = a1xxyxxxbvxxxxxxxxxxshow168;
		this.a1xxyxxxbvxxxxxxxxxxshow169 = a1xxyxxxbvxxxxxxxxxxshow169;
		this.a1xxyxxxbvxxxxxxxxxxshow170 = a1xxyxxxbvxxxxxxxxxxshow170;
		this.a1xxyxxxbvxxxxxxxxxxshow171 = a1xxyxxxbvxxxxxxxxxxshow171;
		this.a1xxyxxxbvxxxxxxxxxxshow172 = a1xxyxxxbvxxxxxxxxxxshow172;
		this.a1xxyxxxbvxxxxxxxxxxshow173 = a1xxyxxxbvxxxxxxxxxxshow173;
		this.a1xxyxxxbvxxxxxxxxxxshow174 = a1xxyxxxbvxxxxxxxxxxshow174;
		this.a1xxyxxxbvxxxxxxxxxxshow175 = a1xxyxxxbvxxxxxxxxxxshow175;
		this.a1xxyxxxbvxxxxxxxxxxshow176 = a1xxyxxxbvxxxxxxxxxxshow176;
		this.a1xxyxxxbvxxxxxxxxxxshow177 = a1xxyxxxbvxxxxxxxxxxshow177;
		this.a1xxyxxxbvxxxxxxxxxxshow178 = a1xxyxxxbvxxxxxxxxxxshow178;
		this.a1xxyxxxbvxxxxxxxxxxshow179 = a1xxyxxxbvxxxxxxxxxxshow179;
		this.a1xxyxxxbvxxxxxxxxxxshow180 = a1xxyxxxbvxxxxxxxxxxshow180;
		this.a1xxyxxxbvxxxxxxxxxxshow181 = a1xxyxxxbvxxxxxxxxxxshow181;
		this.a1xxyxxxbvxxxxxxxxxxshow182 = a1xxyxxxbvxxxxxxxxxxshow182;
		this.a1xxyxxxbvxxxxxxxxxxshow183 = a1xxyxxxbvxxxxxxxxxxshow183;
		this.a1xxyxxxbvxxxxxxxxxxshow184 = a1xxyxxxbvxxxxxxxxxxshow184;
		this.a1xxyxxxbvxxxxxxxxxxshow185 = a1xxyxxxbvxxxxxxxxxxshow185;
		this.a1xxyxxxbvxxxxxxxxxxshow186 = a1xxyxxxbvxxxxxxxxxxshow186;
		this.a1xxyxxxbvxxxxxxxxxxshow187 = a1xxyxxxbvxxxxxxxxxxshow187;
		this.a1xxyxxxbvxxxxxxxxxxshow188 = a1xxyxxxbvxxxxxxxxxxshow188;
		this.a1xxyxxxbvxxxxxxxxxxshow189 = a1xxyxxxbvxxxxxxxxxxshow189;
		this.a1xxyxxxbvxxxxxxxxxxshow190 = a1xxyxxxbvxxxxxxxxxxshow190;
		this.a1xxyxxxbvxxxxxxxxxxshow191 = a1xxyxxxbvxxxxxxxxxxshow191;
		this.a1xxyxxxbvxxxxxxxxxxshow192 = a1xxyxxxbvxxxxxxxxxxshow192;
		this.a1xxyxxxbvxxxxxxxxxxshow193 = a1xxyxxxbvxxxxxxxxxxshow193;
		this.a1xxyxxxbvxxxxxxxxxxshow194 = a1xxyxxxbvxxxxxxxxxxshow194;
		this.a1xxyxxxbvxxxxxxxxxxshow195 = a1xxyxxxbvxxxxxxxxxxshow195;
		this.a1xxyxxxbvxxxxxxxxxxshow196 = a1xxyxxxbvxxxxxxxxxxshow196;
		this.a1xxyxxxbvxxxxxxxxxxshow197 = a1xxyxxxbvxxxxxxxxxxshow197;
		this.a1xxyxxxbvxxxxxxxxxxshow198 = a1xxyxxxbvxxxxxxxxxxshow198;
		this.a1xxyxxxbvxxxxxxxxxxshow199 = a1xxyxxxbvxxxxxxxxxxshow199;
		this.a1xxyxxxbvxxxxxxxxxxshow200 = a1xxyxxxbvxxxxxxxxxxshow200;
		this.a1xxyxxxbvxxxxxxxxxxshow201 = a1xxyxxxbvxxxxxxxxxxshow201;
		this.a1xxyxxxbvxxxxxxxxxxshow202 = a1xxyxxxbvxxxxxxxxxxshow202;
		this.a1xxyxxxbvxxxxxxxxxxshow203 = a1xxyxxxbvxxxxxxxxxxshow203;
		this.a1xxyxxxbvxxxxxxxxxxshow204 = a1xxyxxxbvxxxxxxxxxxshow204;
		this.a1xxyxxxbvxxxxxxxxxxshow205 = a1xxyxxxbvxxxxxxxxxxshow205;
		this.a1xxyxxxbvxxxxxxxxxxshow206 = a1xxyxxxbvxxxxxxxxxxshow206;
		this.a1xxyxxxbvxxxxxxxxxxshow207 = a1xxyxxxbvxxxxxxxxxxshow207;
		this.a1xxyxxxbvxxxxxxxxxxshow208 = a1xxyxxxbvxxxxxxxxxxshow208;
		this.a1xxyxxxbvxxxxxxxxxxshow209 = a1xxyxxxbvxxxxxxxxxxshow209;
		this.a1xxyxxxbvxxxxxxxxxxshow210 = a1xxyxxxbvxxxxxxxxxxshow210;
		this.zixxzzfxhhxxxxxxxxxxstatusfl = zixxzzfxhhxxxxxxxxxxstatusfl;
		this.zjxxcztxlxxxxxxxxxxxstatusfldt = zjxxcztxlxxxxxxxxxxxstatusfldt;
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getA0xxuobxbxxxxxxxxxxxsid() {
		return this.a0xxuobxbxxxxxxxxxxxsid;
	}

	public void setA0xxuobxbxxxxxxxxxxxsid(Integer a0xxuobxbxxxxxxxxxxxsid) {
		this.a0xxuobxbxxxxxxxxxxxsid = a0xxuobxbxxxxxxxxxxxsid;
	}

	@Column(name = "tablename", length = 50)
	@Size(max = 50)
	public String getA0xxukrdbvxxxxxxxxxxtablename() {
		return this.a0xxukrdbvxxxxxxxxxxtablename;
	}

	public void setA0xxukrdbvxxxxxxxxxxtablename(
			String a0xxukrdbvxxxxxxxxxxtablename) {
		this.a0xxukrdbvxxxxxxxxxxtablename = a0xxukrdbvxxxxxxxxxxtablename;
	}

	@Column(name = "qualifier", length = 32)
	@Size(max = 32)
	public String getA1xxuxxxbvxxxxxxxxxxqualifier() {
		return this.a1xxuxxxbvxxxxxxxxxxqualifier;
	}

	public void setA1xxuxxxbvxxxxxxxxxxqualifier(
			String a1xxuxxxbvxxxxxxxxxxqualifier) {
		this.a1xxuxxxbvxxxxxxxxxxqualifier = a1xxuxxxbvxxxxxxxxxxqualifier;
	}

	@Column(name = "show001")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow001() {
		return this.a1xxyxxxbvxxxxxxxxxxshow001;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow001(
			Boolean a1xxyxxxbvxxxxxxxxxxshow001) {
		this.a1xxyxxxbvxxxxxxxxxxshow001 = a1xxyxxxbvxxxxxxxxxxshow001;
	}

	@Column(name = "show002")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow002() {
		return this.a1xxyxxxbvxxxxxxxxxxshow002;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow002(
			Boolean a1xxyxxxbvxxxxxxxxxxshow002) {
		this.a1xxyxxxbvxxxxxxxxxxshow002 = a1xxyxxxbvxxxxxxxxxxshow002;
	}

	@Column(name = "show003")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow003() {
		return this.a1xxyxxxbvxxxxxxxxxxshow003;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow003(
			Boolean a1xxyxxxbvxxxxxxxxxxshow003) {
		this.a1xxyxxxbvxxxxxxxxxxshow003 = a1xxyxxxbvxxxxxxxxxxshow003;
	}

	@Column(name = "show004")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow004() {
		return this.a1xxyxxxbvxxxxxxxxxxshow004;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow004(
			Boolean a1xxyxxxbvxxxxxxxxxxshow004) {
		this.a1xxyxxxbvxxxxxxxxxxshow004 = a1xxyxxxbvxxxxxxxxxxshow004;
	}

	@Column(name = "show005")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow005() {
		return this.a1xxyxxxbvxxxxxxxxxxshow005;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow005(
			Boolean a1xxyxxxbvxxxxxxxxxxshow005) {
		this.a1xxyxxxbvxxxxxxxxxxshow005 = a1xxyxxxbvxxxxxxxxxxshow005;
	}

	@Column(name = "show006")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow006() {
		return this.a1xxyxxxbvxxxxxxxxxxshow006;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow006(
			Boolean a1xxyxxxbvxxxxxxxxxxshow006) {
		this.a1xxyxxxbvxxxxxxxxxxshow006 = a1xxyxxxbvxxxxxxxxxxshow006;
	}

	@Column(name = "show007")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow007() {
		return this.a1xxyxxxbvxxxxxxxxxxshow007;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow007(
			Boolean a1xxyxxxbvxxxxxxxxxxshow007) {
		this.a1xxyxxxbvxxxxxxxxxxshow007 = a1xxyxxxbvxxxxxxxxxxshow007;
	}

	@Column(name = "show008")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow008() {
		return this.a1xxyxxxbvxxxxxxxxxxshow008;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow008(
			Boolean a1xxyxxxbvxxxxxxxxxxshow008) {
		this.a1xxyxxxbvxxxxxxxxxxshow008 = a1xxyxxxbvxxxxxxxxxxshow008;
	}

	@Column(name = "show009")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow009() {
		return this.a1xxyxxxbvxxxxxxxxxxshow009;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow009(
			Boolean a1xxyxxxbvxxxxxxxxxxshow009) {
		this.a1xxyxxxbvxxxxxxxxxxshow009 = a1xxyxxxbvxxxxxxxxxxshow009;
	}

	@Column(name = "show010")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow010() {
		return this.a1xxyxxxbvxxxxxxxxxxshow010;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow010(
			Boolean a1xxyxxxbvxxxxxxxxxxshow010) {
		this.a1xxyxxxbvxxxxxxxxxxshow010 = a1xxyxxxbvxxxxxxxxxxshow010;
	}

	@Column(name = "show011")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow011() {
		return this.a1xxyxxxbvxxxxxxxxxxshow011;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow011(
			Boolean a1xxyxxxbvxxxxxxxxxxshow011) {
		this.a1xxyxxxbvxxxxxxxxxxshow011 = a1xxyxxxbvxxxxxxxxxxshow011;
	}

	@Column(name = "show012")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow012() {
		return this.a1xxyxxxbvxxxxxxxxxxshow012;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow012(
			Boolean a1xxyxxxbvxxxxxxxxxxshow012) {
		this.a1xxyxxxbvxxxxxxxxxxshow012 = a1xxyxxxbvxxxxxxxxxxshow012;
	}

	@Column(name = "show013")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow013() {
		return this.a1xxyxxxbvxxxxxxxxxxshow013;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow013(
			Boolean a1xxyxxxbvxxxxxxxxxxshow013) {
		this.a1xxyxxxbvxxxxxxxxxxshow013 = a1xxyxxxbvxxxxxxxxxxshow013;
	}

	@Column(name = "show014")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow014() {
		return this.a1xxyxxxbvxxxxxxxxxxshow014;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow014(
			Boolean a1xxyxxxbvxxxxxxxxxxshow014) {
		this.a1xxyxxxbvxxxxxxxxxxshow014 = a1xxyxxxbvxxxxxxxxxxshow014;
	}

	@Column(name = "show015")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow015() {
		return this.a1xxyxxxbvxxxxxxxxxxshow015;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow015(
			Boolean a1xxyxxxbvxxxxxxxxxxshow015) {
		this.a1xxyxxxbvxxxxxxxxxxshow015 = a1xxyxxxbvxxxxxxxxxxshow015;
	}

	@Column(name = "show016")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow016() {
		return this.a1xxyxxxbvxxxxxxxxxxshow016;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow016(
			Boolean a1xxyxxxbvxxxxxxxxxxshow016) {
		this.a1xxyxxxbvxxxxxxxxxxshow016 = a1xxyxxxbvxxxxxxxxxxshow016;
	}

	@Column(name = "show017")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow017() {
		return this.a1xxyxxxbvxxxxxxxxxxshow017;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow017(
			Boolean a1xxyxxxbvxxxxxxxxxxshow017) {
		this.a1xxyxxxbvxxxxxxxxxxshow017 = a1xxyxxxbvxxxxxxxxxxshow017;
	}

	@Column(name = "show018")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow018() {
		return this.a1xxyxxxbvxxxxxxxxxxshow018;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow018(
			Boolean a1xxyxxxbvxxxxxxxxxxshow018) {
		this.a1xxyxxxbvxxxxxxxxxxshow018 = a1xxyxxxbvxxxxxxxxxxshow018;
	}

	@Column(name = "show019")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow019() {
		return this.a1xxyxxxbvxxxxxxxxxxshow019;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow019(
			Boolean a1xxyxxxbvxxxxxxxxxxshow019) {
		this.a1xxyxxxbvxxxxxxxxxxshow019 = a1xxyxxxbvxxxxxxxxxxshow019;
	}

	@Column(name = "show020")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow020() {
		return this.a1xxyxxxbvxxxxxxxxxxshow020;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow020(
			Boolean a1xxyxxxbvxxxxxxxxxxshow020) {
		this.a1xxyxxxbvxxxxxxxxxxshow020 = a1xxyxxxbvxxxxxxxxxxshow020;
	}

	@Column(name = "show021")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow021() {
		return this.a1xxyxxxbvxxxxxxxxxxshow021;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow021(
			Boolean a1xxyxxxbvxxxxxxxxxxshow021) {
		this.a1xxyxxxbvxxxxxxxxxxshow021 = a1xxyxxxbvxxxxxxxxxxshow021;
	}

	@Column(name = "show022")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow022() {
		return this.a1xxyxxxbvxxxxxxxxxxshow022;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow022(
			Boolean a1xxyxxxbvxxxxxxxxxxshow022) {
		this.a1xxyxxxbvxxxxxxxxxxshow022 = a1xxyxxxbvxxxxxxxxxxshow022;
	}

	@Column(name = "show023")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow023() {
		return this.a1xxyxxxbvxxxxxxxxxxshow023;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow023(
			Boolean a1xxyxxxbvxxxxxxxxxxshow023) {
		this.a1xxyxxxbvxxxxxxxxxxshow023 = a1xxyxxxbvxxxxxxxxxxshow023;
	}

	@Column(name = "show024")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow024() {
		return this.a1xxyxxxbvxxxxxxxxxxshow024;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow024(
			Boolean a1xxyxxxbvxxxxxxxxxxshow024) {
		this.a1xxyxxxbvxxxxxxxxxxshow024 = a1xxyxxxbvxxxxxxxxxxshow024;
	}

	@Column(name = "show025")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow025() {
		return this.a1xxyxxxbvxxxxxxxxxxshow025;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow025(
			Boolean a1xxyxxxbvxxxxxxxxxxshow025) {
		this.a1xxyxxxbvxxxxxxxxxxshow025 = a1xxyxxxbvxxxxxxxxxxshow025;
	}

	@Column(name = "show026")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow026() {
		return this.a1xxyxxxbvxxxxxxxxxxshow026;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow026(
			Boolean a1xxyxxxbvxxxxxxxxxxshow026) {
		this.a1xxyxxxbvxxxxxxxxxxshow026 = a1xxyxxxbvxxxxxxxxxxshow026;
	}

	@Column(name = "show027")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow027() {
		return this.a1xxyxxxbvxxxxxxxxxxshow027;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow027(
			Boolean a1xxyxxxbvxxxxxxxxxxshow027) {
		this.a1xxyxxxbvxxxxxxxxxxshow027 = a1xxyxxxbvxxxxxxxxxxshow027;
	}

	@Column(name = "show028")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow028() {
		return this.a1xxyxxxbvxxxxxxxxxxshow028;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow028(
			Boolean a1xxyxxxbvxxxxxxxxxxshow028) {
		this.a1xxyxxxbvxxxxxxxxxxshow028 = a1xxyxxxbvxxxxxxxxxxshow028;
	}

	@Column(name = "show029")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow029() {
		return this.a1xxyxxxbvxxxxxxxxxxshow029;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow029(
			Boolean a1xxyxxxbvxxxxxxxxxxshow029) {
		this.a1xxyxxxbvxxxxxxxxxxshow029 = a1xxyxxxbvxxxxxxxxxxshow029;
	}

	@Column(name = "show030")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow030() {
		return this.a1xxyxxxbvxxxxxxxxxxshow030;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow030(
			Boolean a1xxyxxxbvxxxxxxxxxxshow030) {
		this.a1xxyxxxbvxxxxxxxxxxshow030 = a1xxyxxxbvxxxxxxxxxxshow030;
	}

	@Column(name = "show031")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow031() {
		return this.a1xxyxxxbvxxxxxxxxxxshow031;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow031(
			Boolean a1xxyxxxbvxxxxxxxxxxshow031) {
		this.a1xxyxxxbvxxxxxxxxxxshow031 = a1xxyxxxbvxxxxxxxxxxshow031;
	}

	@Column(name = "show032")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow032() {
		return this.a1xxyxxxbvxxxxxxxxxxshow032;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow032(
			Boolean a1xxyxxxbvxxxxxxxxxxshow032) {
		this.a1xxyxxxbvxxxxxxxxxxshow032 = a1xxyxxxbvxxxxxxxxxxshow032;
	}

	@Column(name = "show033")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow033() {
		return this.a1xxyxxxbvxxxxxxxxxxshow033;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow033(
			Boolean a1xxyxxxbvxxxxxxxxxxshow033) {
		this.a1xxyxxxbvxxxxxxxxxxshow033 = a1xxyxxxbvxxxxxxxxxxshow033;
	}

	@Column(name = "show034")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow034() {
		return this.a1xxyxxxbvxxxxxxxxxxshow034;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow034(
			Boolean a1xxyxxxbvxxxxxxxxxxshow034) {
		this.a1xxyxxxbvxxxxxxxxxxshow034 = a1xxyxxxbvxxxxxxxxxxshow034;
	}

	@Column(name = "show035")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow035() {
		return this.a1xxyxxxbvxxxxxxxxxxshow035;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow035(
			Boolean a1xxyxxxbvxxxxxxxxxxshow035) {
		this.a1xxyxxxbvxxxxxxxxxxshow035 = a1xxyxxxbvxxxxxxxxxxshow035;
	}

	@Column(name = "show036")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow036() {
		return this.a1xxyxxxbvxxxxxxxxxxshow036;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow036(
			Boolean a1xxyxxxbvxxxxxxxxxxshow036) {
		this.a1xxyxxxbvxxxxxxxxxxshow036 = a1xxyxxxbvxxxxxxxxxxshow036;
	}

	@Column(name = "show037")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow037() {
		return this.a1xxyxxxbvxxxxxxxxxxshow037;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow037(
			Boolean a1xxyxxxbvxxxxxxxxxxshow037) {
		this.a1xxyxxxbvxxxxxxxxxxshow037 = a1xxyxxxbvxxxxxxxxxxshow037;
	}

	@Column(name = "show038")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow038() {
		return this.a1xxyxxxbvxxxxxxxxxxshow038;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow038(
			Boolean a1xxyxxxbvxxxxxxxxxxshow038) {
		this.a1xxyxxxbvxxxxxxxxxxshow038 = a1xxyxxxbvxxxxxxxxxxshow038;
	}

	@Column(name = "show039")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow039() {
		return this.a1xxyxxxbvxxxxxxxxxxshow039;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow039(
			Boolean a1xxyxxxbvxxxxxxxxxxshow039) {
		this.a1xxyxxxbvxxxxxxxxxxshow039 = a1xxyxxxbvxxxxxxxxxxshow039;
	}

	@Column(name = "show040")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow040() {
		return this.a1xxyxxxbvxxxxxxxxxxshow040;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow040(
			Boolean a1xxyxxxbvxxxxxxxxxxshow040) {
		this.a1xxyxxxbvxxxxxxxxxxshow040 = a1xxyxxxbvxxxxxxxxxxshow040;
	}

	@Column(name = "show041")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow041() {
		return this.a1xxyxxxbvxxxxxxxxxxshow041;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow041(
			Boolean a1xxyxxxbvxxxxxxxxxxshow041) {
		this.a1xxyxxxbvxxxxxxxxxxshow041 = a1xxyxxxbvxxxxxxxxxxshow041;
	}

	@Column(name = "show042")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow042() {
		return this.a1xxyxxxbvxxxxxxxxxxshow042;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow042(
			Boolean a1xxyxxxbvxxxxxxxxxxshow042) {
		this.a1xxyxxxbvxxxxxxxxxxshow042 = a1xxyxxxbvxxxxxxxxxxshow042;
	}

	@Column(name = "show043")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow043() {
		return this.a1xxyxxxbvxxxxxxxxxxshow043;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow043(
			Boolean a1xxyxxxbvxxxxxxxxxxshow043) {
		this.a1xxyxxxbvxxxxxxxxxxshow043 = a1xxyxxxbvxxxxxxxxxxshow043;
	}

	@Column(name = "show044")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow044() {
		return this.a1xxyxxxbvxxxxxxxxxxshow044;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow044(
			Boolean a1xxyxxxbvxxxxxxxxxxshow044) {
		this.a1xxyxxxbvxxxxxxxxxxshow044 = a1xxyxxxbvxxxxxxxxxxshow044;
	}

	@Column(name = "show045")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow045() {
		return this.a1xxyxxxbvxxxxxxxxxxshow045;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow045(
			Boolean a1xxyxxxbvxxxxxxxxxxshow045) {
		this.a1xxyxxxbvxxxxxxxxxxshow045 = a1xxyxxxbvxxxxxxxxxxshow045;
	}

	@Column(name = "show046")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow046() {
		return this.a1xxyxxxbvxxxxxxxxxxshow046;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow046(
			Boolean a1xxyxxxbvxxxxxxxxxxshow046) {
		this.a1xxyxxxbvxxxxxxxxxxshow046 = a1xxyxxxbvxxxxxxxxxxshow046;
	}

	@Column(name = "show047")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow047() {
		return this.a1xxyxxxbvxxxxxxxxxxshow047;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow047(
			Boolean a1xxyxxxbvxxxxxxxxxxshow047) {
		this.a1xxyxxxbvxxxxxxxxxxshow047 = a1xxyxxxbvxxxxxxxxxxshow047;
	}

	@Column(name = "show048")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow048() {
		return this.a1xxyxxxbvxxxxxxxxxxshow048;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow048(
			Boolean a1xxyxxxbvxxxxxxxxxxshow048) {
		this.a1xxyxxxbvxxxxxxxxxxshow048 = a1xxyxxxbvxxxxxxxxxxshow048;
	}

	@Column(name = "show049")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow049() {
		return this.a1xxyxxxbvxxxxxxxxxxshow049;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow049(
			Boolean a1xxyxxxbvxxxxxxxxxxshow049) {
		this.a1xxyxxxbvxxxxxxxxxxshow049 = a1xxyxxxbvxxxxxxxxxxshow049;
	}

	@Column(name = "show050")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow050() {
		return this.a1xxyxxxbvxxxxxxxxxxshow050;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow050(
			Boolean a1xxyxxxbvxxxxxxxxxxshow050) {
		this.a1xxyxxxbvxxxxxxxxxxshow050 = a1xxyxxxbvxxxxxxxxxxshow050;
	}

	@Column(name = "show051")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow051() {
		return this.a1xxyxxxbvxxxxxxxxxxshow051;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow051(
			Boolean a1xxyxxxbvxxxxxxxxxxshow051) {
		this.a1xxyxxxbvxxxxxxxxxxshow051 = a1xxyxxxbvxxxxxxxxxxshow051;
	}

	@Column(name = "show052")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow052() {
		return this.a1xxyxxxbvxxxxxxxxxxshow052;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow052(
			Boolean a1xxyxxxbvxxxxxxxxxxshow052) {
		this.a1xxyxxxbvxxxxxxxxxxshow052 = a1xxyxxxbvxxxxxxxxxxshow052;
	}

	@Column(name = "show053")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow053() {
		return this.a1xxyxxxbvxxxxxxxxxxshow053;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow053(
			Boolean a1xxyxxxbvxxxxxxxxxxshow053) {
		this.a1xxyxxxbvxxxxxxxxxxshow053 = a1xxyxxxbvxxxxxxxxxxshow053;
	}

	@Column(name = "show054")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow054() {
		return this.a1xxyxxxbvxxxxxxxxxxshow054;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow054(
			Boolean a1xxyxxxbvxxxxxxxxxxshow054) {
		this.a1xxyxxxbvxxxxxxxxxxshow054 = a1xxyxxxbvxxxxxxxxxxshow054;
	}

	@Column(name = "show055")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow055() {
		return this.a1xxyxxxbvxxxxxxxxxxshow055;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow055(
			Boolean a1xxyxxxbvxxxxxxxxxxshow055) {
		this.a1xxyxxxbvxxxxxxxxxxshow055 = a1xxyxxxbvxxxxxxxxxxshow055;
	}

	@Column(name = "show056")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow056() {
		return this.a1xxyxxxbvxxxxxxxxxxshow056;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow056(
			Boolean a1xxyxxxbvxxxxxxxxxxshow056) {
		this.a1xxyxxxbvxxxxxxxxxxshow056 = a1xxyxxxbvxxxxxxxxxxshow056;
	}

	@Column(name = "show057")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow057() {
		return this.a1xxyxxxbvxxxxxxxxxxshow057;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow057(
			Boolean a1xxyxxxbvxxxxxxxxxxshow057) {
		this.a1xxyxxxbvxxxxxxxxxxshow057 = a1xxyxxxbvxxxxxxxxxxshow057;
	}

	@Column(name = "show058")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow058() {
		return this.a1xxyxxxbvxxxxxxxxxxshow058;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow058(
			Boolean a1xxyxxxbvxxxxxxxxxxshow058) {
		this.a1xxyxxxbvxxxxxxxxxxshow058 = a1xxyxxxbvxxxxxxxxxxshow058;
	}

	@Column(name = "show059")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow059() {
		return this.a1xxyxxxbvxxxxxxxxxxshow059;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow059(
			Boolean a1xxyxxxbvxxxxxxxxxxshow059) {
		this.a1xxyxxxbvxxxxxxxxxxshow059 = a1xxyxxxbvxxxxxxxxxxshow059;
	}

	@Column(name = "show060")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow060() {
		return this.a1xxyxxxbvxxxxxxxxxxshow060;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow060(
			Boolean a1xxyxxxbvxxxxxxxxxxshow060) {
		this.a1xxyxxxbvxxxxxxxxxxshow060 = a1xxyxxxbvxxxxxxxxxxshow060;
	}

	@Column(name = "show061")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow061() {
		return this.a1xxyxxxbvxxxxxxxxxxshow061;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow061(
			Boolean a1xxyxxxbvxxxxxxxxxxshow061) {
		this.a1xxyxxxbvxxxxxxxxxxshow061 = a1xxyxxxbvxxxxxxxxxxshow061;
	}

	@Column(name = "show062")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow062() {
		return this.a1xxyxxxbvxxxxxxxxxxshow062;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow062(
			Boolean a1xxyxxxbvxxxxxxxxxxshow062) {
		this.a1xxyxxxbvxxxxxxxxxxshow062 = a1xxyxxxbvxxxxxxxxxxshow062;
	}

	@Column(name = "show063")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow063() {
		return this.a1xxyxxxbvxxxxxxxxxxshow063;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow063(
			Boolean a1xxyxxxbvxxxxxxxxxxshow063) {
		this.a1xxyxxxbvxxxxxxxxxxshow063 = a1xxyxxxbvxxxxxxxxxxshow063;
	}

	@Column(name = "show064")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow064() {
		return this.a1xxyxxxbvxxxxxxxxxxshow064;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow064(
			Boolean a1xxyxxxbvxxxxxxxxxxshow064) {
		this.a1xxyxxxbvxxxxxxxxxxshow064 = a1xxyxxxbvxxxxxxxxxxshow064;
	}

	@Column(name = "show065")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow065() {
		return this.a1xxyxxxbvxxxxxxxxxxshow065;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow065(
			Boolean a1xxyxxxbvxxxxxxxxxxshow065) {
		this.a1xxyxxxbvxxxxxxxxxxshow065 = a1xxyxxxbvxxxxxxxxxxshow065;
	}

	@Column(name = "show066")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow066() {
		return this.a1xxyxxxbvxxxxxxxxxxshow066;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow066(
			Boolean a1xxyxxxbvxxxxxxxxxxshow066) {
		this.a1xxyxxxbvxxxxxxxxxxshow066 = a1xxyxxxbvxxxxxxxxxxshow066;
	}

	@Column(name = "show067")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow067() {
		return this.a1xxyxxxbvxxxxxxxxxxshow067;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow067(
			Boolean a1xxyxxxbvxxxxxxxxxxshow067) {
		this.a1xxyxxxbvxxxxxxxxxxshow067 = a1xxyxxxbvxxxxxxxxxxshow067;
	}

	@Column(name = "show068")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow068() {
		return this.a1xxyxxxbvxxxxxxxxxxshow068;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow068(
			Boolean a1xxyxxxbvxxxxxxxxxxshow068) {
		this.a1xxyxxxbvxxxxxxxxxxshow068 = a1xxyxxxbvxxxxxxxxxxshow068;
	}

	@Column(name = "show069")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow069() {
		return this.a1xxyxxxbvxxxxxxxxxxshow069;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow069(
			Boolean a1xxyxxxbvxxxxxxxxxxshow069) {
		this.a1xxyxxxbvxxxxxxxxxxshow069 = a1xxyxxxbvxxxxxxxxxxshow069;
	}

	@Column(name = "show070")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow070() {
		return this.a1xxyxxxbvxxxxxxxxxxshow070;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow070(
			Boolean a1xxyxxxbvxxxxxxxxxxshow070) {
		this.a1xxyxxxbvxxxxxxxxxxshow070 = a1xxyxxxbvxxxxxxxxxxshow070;
	}

	@Column(name = "show071")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow071() {
		return this.a1xxyxxxbvxxxxxxxxxxshow071;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow071(
			Boolean a1xxyxxxbvxxxxxxxxxxshow071) {
		this.a1xxyxxxbvxxxxxxxxxxshow071 = a1xxyxxxbvxxxxxxxxxxshow071;
	}

	@Column(name = "show072")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow072() {
		return this.a1xxyxxxbvxxxxxxxxxxshow072;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow072(
			Boolean a1xxyxxxbvxxxxxxxxxxshow072) {
		this.a1xxyxxxbvxxxxxxxxxxshow072 = a1xxyxxxbvxxxxxxxxxxshow072;
	}

	@Column(name = "show073")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow073() {
		return this.a1xxyxxxbvxxxxxxxxxxshow073;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow073(
			Boolean a1xxyxxxbvxxxxxxxxxxshow073) {
		this.a1xxyxxxbvxxxxxxxxxxshow073 = a1xxyxxxbvxxxxxxxxxxshow073;
	}

	@Column(name = "show074")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow074() {
		return this.a1xxyxxxbvxxxxxxxxxxshow074;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow074(
			Boolean a1xxyxxxbvxxxxxxxxxxshow074) {
		this.a1xxyxxxbvxxxxxxxxxxshow074 = a1xxyxxxbvxxxxxxxxxxshow074;
	}

	@Column(name = "show075")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow075() {
		return this.a1xxyxxxbvxxxxxxxxxxshow075;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow075(
			Boolean a1xxyxxxbvxxxxxxxxxxshow075) {
		this.a1xxyxxxbvxxxxxxxxxxshow075 = a1xxyxxxbvxxxxxxxxxxshow075;
	}

	@Column(name = "show076")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow076() {
		return this.a1xxyxxxbvxxxxxxxxxxshow076;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow076(
			Boolean a1xxyxxxbvxxxxxxxxxxshow076) {
		this.a1xxyxxxbvxxxxxxxxxxshow076 = a1xxyxxxbvxxxxxxxxxxshow076;
	}

	@Column(name = "show077")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow077() {
		return this.a1xxyxxxbvxxxxxxxxxxshow077;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow077(
			Boolean a1xxyxxxbvxxxxxxxxxxshow077) {
		this.a1xxyxxxbvxxxxxxxxxxshow077 = a1xxyxxxbvxxxxxxxxxxshow077;
	}

	@Column(name = "show078")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow078() {
		return this.a1xxyxxxbvxxxxxxxxxxshow078;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow078(
			Boolean a1xxyxxxbvxxxxxxxxxxshow078) {
		this.a1xxyxxxbvxxxxxxxxxxshow078 = a1xxyxxxbvxxxxxxxxxxshow078;
	}

	@Column(name = "show079")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow079() {
		return this.a1xxyxxxbvxxxxxxxxxxshow079;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow079(
			Boolean a1xxyxxxbvxxxxxxxxxxshow079) {
		this.a1xxyxxxbvxxxxxxxxxxshow079 = a1xxyxxxbvxxxxxxxxxxshow079;
	}

	@Column(name = "show080")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow080() {
		return this.a1xxyxxxbvxxxxxxxxxxshow080;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow080(
			Boolean a1xxyxxxbvxxxxxxxxxxshow080) {
		this.a1xxyxxxbvxxxxxxxxxxshow080 = a1xxyxxxbvxxxxxxxxxxshow080;
	}

	@Column(name = "show081")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow081() {
		return this.a1xxyxxxbvxxxxxxxxxxshow081;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow081(
			Boolean a1xxyxxxbvxxxxxxxxxxshow081) {
		this.a1xxyxxxbvxxxxxxxxxxshow081 = a1xxyxxxbvxxxxxxxxxxshow081;
	}

	@Column(name = "show082")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow082() {
		return this.a1xxyxxxbvxxxxxxxxxxshow082;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow082(
			Boolean a1xxyxxxbvxxxxxxxxxxshow082) {
		this.a1xxyxxxbvxxxxxxxxxxshow082 = a1xxyxxxbvxxxxxxxxxxshow082;
	}

	@Column(name = "show083")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow083() {
		return this.a1xxyxxxbvxxxxxxxxxxshow083;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow083(
			Boolean a1xxyxxxbvxxxxxxxxxxshow083) {
		this.a1xxyxxxbvxxxxxxxxxxshow083 = a1xxyxxxbvxxxxxxxxxxshow083;
	}

	@Column(name = "show084")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow084() {
		return this.a1xxyxxxbvxxxxxxxxxxshow084;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow084(
			Boolean a1xxyxxxbvxxxxxxxxxxshow084) {
		this.a1xxyxxxbvxxxxxxxxxxshow084 = a1xxyxxxbvxxxxxxxxxxshow084;
	}

	@Column(name = "show085")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow085() {
		return this.a1xxyxxxbvxxxxxxxxxxshow085;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow085(
			Boolean a1xxyxxxbvxxxxxxxxxxshow085) {
		this.a1xxyxxxbvxxxxxxxxxxshow085 = a1xxyxxxbvxxxxxxxxxxshow085;
	}

	@Column(name = "show086")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow086() {
		return this.a1xxyxxxbvxxxxxxxxxxshow086;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow086(
			Boolean a1xxyxxxbvxxxxxxxxxxshow086) {
		this.a1xxyxxxbvxxxxxxxxxxshow086 = a1xxyxxxbvxxxxxxxxxxshow086;
	}

	@Column(name = "show087")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow087() {
		return this.a1xxyxxxbvxxxxxxxxxxshow087;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow087(
			Boolean a1xxyxxxbvxxxxxxxxxxshow087) {
		this.a1xxyxxxbvxxxxxxxxxxshow087 = a1xxyxxxbvxxxxxxxxxxshow087;
	}

	@Column(name = "show088")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow088() {
		return this.a1xxyxxxbvxxxxxxxxxxshow088;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow088(
			Boolean a1xxyxxxbvxxxxxxxxxxshow088) {
		this.a1xxyxxxbvxxxxxxxxxxshow088 = a1xxyxxxbvxxxxxxxxxxshow088;
	}

	@Column(name = "show089")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow089() {
		return this.a1xxyxxxbvxxxxxxxxxxshow089;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow089(
			Boolean a1xxyxxxbvxxxxxxxxxxshow089) {
		this.a1xxyxxxbvxxxxxxxxxxshow089 = a1xxyxxxbvxxxxxxxxxxshow089;
	}

	@Column(name = "show090")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow090() {
		return this.a1xxyxxxbvxxxxxxxxxxshow090;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow090(
			Boolean a1xxyxxxbvxxxxxxxxxxshow090) {
		this.a1xxyxxxbvxxxxxxxxxxshow090 = a1xxyxxxbvxxxxxxxxxxshow090;
	}

	@Column(name = "show091")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow091() {
		return this.a1xxyxxxbvxxxxxxxxxxshow091;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow091(
			Boolean a1xxyxxxbvxxxxxxxxxxshow091) {
		this.a1xxyxxxbvxxxxxxxxxxshow091 = a1xxyxxxbvxxxxxxxxxxshow091;
	}

	@Column(name = "show092")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow092() {
		return this.a1xxyxxxbvxxxxxxxxxxshow092;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow092(
			Boolean a1xxyxxxbvxxxxxxxxxxshow092) {
		this.a1xxyxxxbvxxxxxxxxxxshow092 = a1xxyxxxbvxxxxxxxxxxshow092;
	}

	@Column(name = "show093")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow093() {
		return this.a1xxyxxxbvxxxxxxxxxxshow093;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow093(
			Boolean a1xxyxxxbvxxxxxxxxxxshow093) {
		this.a1xxyxxxbvxxxxxxxxxxshow093 = a1xxyxxxbvxxxxxxxxxxshow093;
	}

	@Column(name = "show094")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow094() {
		return this.a1xxyxxxbvxxxxxxxxxxshow094;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow094(
			Boolean a1xxyxxxbvxxxxxxxxxxshow094) {
		this.a1xxyxxxbvxxxxxxxxxxshow094 = a1xxyxxxbvxxxxxxxxxxshow094;
	}

	@Column(name = "show095")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow095() {
		return this.a1xxyxxxbvxxxxxxxxxxshow095;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow095(
			Boolean a1xxyxxxbvxxxxxxxxxxshow095) {
		this.a1xxyxxxbvxxxxxxxxxxshow095 = a1xxyxxxbvxxxxxxxxxxshow095;
	}

	@Column(name = "show096")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow096() {
		return this.a1xxyxxxbvxxxxxxxxxxshow096;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow096(
			Boolean a1xxyxxxbvxxxxxxxxxxshow096) {
		this.a1xxyxxxbvxxxxxxxxxxshow096 = a1xxyxxxbvxxxxxxxxxxshow096;
	}

	@Column(name = "show097")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow097() {
		return this.a1xxyxxxbvxxxxxxxxxxshow097;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow097(
			Boolean a1xxyxxxbvxxxxxxxxxxshow097) {
		this.a1xxyxxxbvxxxxxxxxxxshow097 = a1xxyxxxbvxxxxxxxxxxshow097;
	}

	@Column(name = "show098")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow098() {
		return this.a1xxyxxxbvxxxxxxxxxxshow098;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow098(
			Boolean a1xxyxxxbvxxxxxxxxxxshow098) {
		this.a1xxyxxxbvxxxxxxxxxxshow098 = a1xxyxxxbvxxxxxxxxxxshow098;
	}

	@Column(name = "show099")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow099() {
		return this.a1xxyxxxbvxxxxxxxxxxshow099;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow099(
			Boolean a1xxyxxxbvxxxxxxxxxxshow099) {
		this.a1xxyxxxbvxxxxxxxxxxshow099 = a1xxyxxxbvxxxxxxxxxxshow099;
	}

	@Column(name = "show100")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow100() {
		return this.a1xxyxxxbvxxxxxxxxxxshow100;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow100(
			Boolean a1xxyxxxbvxxxxxxxxxxshow100) {
		this.a1xxyxxxbvxxxxxxxxxxshow100 = a1xxyxxxbvxxxxxxxxxxshow100;
	}

	@Column(name = "show101")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow101() {
		return this.a1xxyxxxbvxxxxxxxxxxshow101;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow101(
			Boolean a1xxyxxxbvxxxxxxxxxxshow101) {
		this.a1xxyxxxbvxxxxxxxxxxshow101 = a1xxyxxxbvxxxxxxxxxxshow101;
	}

	@Column(name = "show102")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow102() {
		return this.a1xxyxxxbvxxxxxxxxxxshow102;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow102(
			Boolean a1xxyxxxbvxxxxxxxxxxshow102) {
		this.a1xxyxxxbvxxxxxxxxxxshow102 = a1xxyxxxbvxxxxxxxxxxshow102;
	}

	@Column(name = "show103")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow103() {
		return this.a1xxyxxxbvxxxxxxxxxxshow103;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow103(
			Boolean a1xxyxxxbvxxxxxxxxxxshow103) {
		this.a1xxyxxxbvxxxxxxxxxxshow103 = a1xxyxxxbvxxxxxxxxxxshow103;
	}

	@Column(name = "show104")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow104() {
		return this.a1xxyxxxbvxxxxxxxxxxshow104;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow104(
			Boolean a1xxyxxxbvxxxxxxxxxxshow104) {
		this.a1xxyxxxbvxxxxxxxxxxshow104 = a1xxyxxxbvxxxxxxxxxxshow104;
	}

	@Column(name = "show105")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow105() {
		return this.a1xxyxxxbvxxxxxxxxxxshow105;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow105(
			Boolean a1xxyxxxbvxxxxxxxxxxshow105) {
		this.a1xxyxxxbvxxxxxxxxxxshow105 = a1xxyxxxbvxxxxxxxxxxshow105;
	}

	@Column(name = "show106")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow106() {
		return this.a1xxyxxxbvxxxxxxxxxxshow106;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow106(
			Boolean a1xxyxxxbvxxxxxxxxxxshow106) {
		this.a1xxyxxxbvxxxxxxxxxxshow106 = a1xxyxxxbvxxxxxxxxxxshow106;
	}

	@Column(name = "show107")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow107() {
		return this.a1xxyxxxbvxxxxxxxxxxshow107;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow107(
			Boolean a1xxyxxxbvxxxxxxxxxxshow107) {
		this.a1xxyxxxbvxxxxxxxxxxshow107 = a1xxyxxxbvxxxxxxxxxxshow107;
	}

	@Column(name = "show108")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow108() {
		return this.a1xxyxxxbvxxxxxxxxxxshow108;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow108(
			Boolean a1xxyxxxbvxxxxxxxxxxshow108) {
		this.a1xxyxxxbvxxxxxxxxxxshow108 = a1xxyxxxbvxxxxxxxxxxshow108;
	}

	@Column(name = "show109")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow109() {
		return this.a1xxyxxxbvxxxxxxxxxxshow109;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow109(
			Boolean a1xxyxxxbvxxxxxxxxxxshow109) {
		this.a1xxyxxxbvxxxxxxxxxxshow109 = a1xxyxxxbvxxxxxxxxxxshow109;
	}

	@Column(name = "show110")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow110() {
		return this.a1xxyxxxbvxxxxxxxxxxshow110;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow110(
			Boolean a1xxyxxxbvxxxxxxxxxxshow110) {
		this.a1xxyxxxbvxxxxxxxxxxshow110 = a1xxyxxxbvxxxxxxxxxxshow110;
	}

	@Column(name = "show111")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow111() {
		return this.a1xxyxxxbvxxxxxxxxxxshow111;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow111(
			Boolean a1xxyxxxbvxxxxxxxxxxshow111) {
		this.a1xxyxxxbvxxxxxxxxxxshow111 = a1xxyxxxbvxxxxxxxxxxshow111;
	}

	@Column(name = "show112")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow112() {
		return this.a1xxyxxxbvxxxxxxxxxxshow112;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow112(
			Boolean a1xxyxxxbvxxxxxxxxxxshow112) {
		this.a1xxyxxxbvxxxxxxxxxxshow112 = a1xxyxxxbvxxxxxxxxxxshow112;
	}

	@Column(name = "show113")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow113() {
		return this.a1xxyxxxbvxxxxxxxxxxshow113;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow113(
			Boolean a1xxyxxxbvxxxxxxxxxxshow113) {
		this.a1xxyxxxbvxxxxxxxxxxshow113 = a1xxyxxxbvxxxxxxxxxxshow113;
	}

	@Column(name = "show114")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow114() {
		return this.a1xxyxxxbvxxxxxxxxxxshow114;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow114(
			Boolean a1xxyxxxbvxxxxxxxxxxshow114) {
		this.a1xxyxxxbvxxxxxxxxxxshow114 = a1xxyxxxbvxxxxxxxxxxshow114;
	}

	@Column(name = "show115")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow115() {
		return this.a1xxyxxxbvxxxxxxxxxxshow115;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow115(
			Boolean a1xxyxxxbvxxxxxxxxxxshow115) {
		this.a1xxyxxxbvxxxxxxxxxxshow115 = a1xxyxxxbvxxxxxxxxxxshow115;
	}

	@Column(name = "show116")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow116() {
		return this.a1xxyxxxbvxxxxxxxxxxshow116;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow116(
			Boolean a1xxyxxxbvxxxxxxxxxxshow116) {
		this.a1xxyxxxbvxxxxxxxxxxshow116 = a1xxyxxxbvxxxxxxxxxxshow116;
	}

	@Column(name = "show117")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow117() {
		return this.a1xxyxxxbvxxxxxxxxxxshow117;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow117(
			Boolean a1xxyxxxbvxxxxxxxxxxshow117) {
		this.a1xxyxxxbvxxxxxxxxxxshow117 = a1xxyxxxbvxxxxxxxxxxshow117;
	}

	@Column(name = "show118")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow118() {
		return this.a1xxyxxxbvxxxxxxxxxxshow118;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow118(
			Boolean a1xxyxxxbvxxxxxxxxxxshow118) {
		this.a1xxyxxxbvxxxxxxxxxxshow118 = a1xxyxxxbvxxxxxxxxxxshow118;
	}

	@Column(name = "show119")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow119() {
		return this.a1xxyxxxbvxxxxxxxxxxshow119;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow119(
			Boolean a1xxyxxxbvxxxxxxxxxxshow119) {
		this.a1xxyxxxbvxxxxxxxxxxshow119 = a1xxyxxxbvxxxxxxxxxxshow119;
	}

	@Column(name = "show120")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow120() {
		return this.a1xxyxxxbvxxxxxxxxxxshow120;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow120(
			Boolean a1xxyxxxbvxxxxxxxxxxshow120) {
		this.a1xxyxxxbvxxxxxxxxxxshow120 = a1xxyxxxbvxxxxxxxxxxshow120;
	}

	@Column(name = "show121")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow121() {
		return this.a1xxyxxxbvxxxxxxxxxxshow121;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow121(
			Boolean a1xxyxxxbvxxxxxxxxxxshow121) {
		this.a1xxyxxxbvxxxxxxxxxxshow121 = a1xxyxxxbvxxxxxxxxxxshow121;
	}

	@Column(name = "show122")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow122() {
		return this.a1xxyxxxbvxxxxxxxxxxshow122;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow122(
			Boolean a1xxyxxxbvxxxxxxxxxxshow122) {
		this.a1xxyxxxbvxxxxxxxxxxshow122 = a1xxyxxxbvxxxxxxxxxxshow122;
	}

	@Column(name = "show123")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow123() {
		return this.a1xxyxxxbvxxxxxxxxxxshow123;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow123(
			Boolean a1xxyxxxbvxxxxxxxxxxshow123) {
		this.a1xxyxxxbvxxxxxxxxxxshow123 = a1xxyxxxbvxxxxxxxxxxshow123;
	}

	@Column(name = "show124")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow124() {
		return this.a1xxyxxxbvxxxxxxxxxxshow124;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow124(
			Boolean a1xxyxxxbvxxxxxxxxxxshow124) {
		this.a1xxyxxxbvxxxxxxxxxxshow124 = a1xxyxxxbvxxxxxxxxxxshow124;
	}

	@Column(name = "show125")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow125() {
		return this.a1xxyxxxbvxxxxxxxxxxshow125;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow125(
			Boolean a1xxyxxxbvxxxxxxxxxxshow125) {
		this.a1xxyxxxbvxxxxxxxxxxshow125 = a1xxyxxxbvxxxxxxxxxxshow125;
	}

	@Column(name = "show126")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow126() {
		return this.a1xxyxxxbvxxxxxxxxxxshow126;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow126(
			Boolean a1xxyxxxbvxxxxxxxxxxshow126) {
		this.a1xxyxxxbvxxxxxxxxxxshow126 = a1xxyxxxbvxxxxxxxxxxshow126;
	}

	@Column(name = "show127")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow127() {
		return this.a1xxyxxxbvxxxxxxxxxxshow127;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow127(
			Boolean a1xxyxxxbvxxxxxxxxxxshow127) {
		this.a1xxyxxxbvxxxxxxxxxxshow127 = a1xxyxxxbvxxxxxxxxxxshow127;
	}

	@Column(name = "show128")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow128() {
		return this.a1xxyxxxbvxxxxxxxxxxshow128;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow128(
			Boolean a1xxyxxxbvxxxxxxxxxxshow128) {
		this.a1xxyxxxbvxxxxxxxxxxshow128 = a1xxyxxxbvxxxxxxxxxxshow128;
	}

	@Column(name = "show129")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow129() {
		return this.a1xxyxxxbvxxxxxxxxxxshow129;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow129(
			Boolean a1xxyxxxbvxxxxxxxxxxshow129) {
		this.a1xxyxxxbvxxxxxxxxxxshow129 = a1xxyxxxbvxxxxxxxxxxshow129;
	}

	@Column(name = "show130")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow130() {
		return this.a1xxyxxxbvxxxxxxxxxxshow130;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow130(
			Boolean a1xxyxxxbvxxxxxxxxxxshow130) {
		this.a1xxyxxxbvxxxxxxxxxxshow130 = a1xxyxxxbvxxxxxxxxxxshow130;
	}

	@Column(name = "show131")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow131() {
		return this.a1xxyxxxbvxxxxxxxxxxshow131;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow131(
			Boolean a1xxyxxxbvxxxxxxxxxxshow131) {
		this.a1xxyxxxbvxxxxxxxxxxshow131 = a1xxyxxxbvxxxxxxxxxxshow131;
	}

	@Column(name = "show132")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow132() {
		return this.a1xxyxxxbvxxxxxxxxxxshow132;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow132(
			Boolean a1xxyxxxbvxxxxxxxxxxshow132) {
		this.a1xxyxxxbvxxxxxxxxxxshow132 = a1xxyxxxbvxxxxxxxxxxshow132;
	}

	@Column(name = "show133")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow133() {
		return this.a1xxyxxxbvxxxxxxxxxxshow133;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow133(
			Boolean a1xxyxxxbvxxxxxxxxxxshow133) {
		this.a1xxyxxxbvxxxxxxxxxxshow133 = a1xxyxxxbvxxxxxxxxxxshow133;
	}

	@Column(name = "show134")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow134() {
		return this.a1xxyxxxbvxxxxxxxxxxshow134;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow134(
			Boolean a1xxyxxxbvxxxxxxxxxxshow134) {
		this.a1xxyxxxbvxxxxxxxxxxshow134 = a1xxyxxxbvxxxxxxxxxxshow134;
	}

	@Column(name = "show135")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow135() {
		return this.a1xxyxxxbvxxxxxxxxxxshow135;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow135(
			Boolean a1xxyxxxbvxxxxxxxxxxshow135) {
		this.a1xxyxxxbvxxxxxxxxxxshow135 = a1xxyxxxbvxxxxxxxxxxshow135;
	}

	@Column(name = "show136")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow136() {
		return this.a1xxyxxxbvxxxxxxxxxxshow136;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow136(
			Boolean a1xxyxxxbvxxxxxxxxxxshow136) {
		this.a1xxyxxxbvxxxxxxxxxxshow136 = a1xxyxxxbvxxxxxxxxxxshow136;
	}

	@Column(name = "show137")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow137() {
		return this.a1xxyxxxbvxxxxxxxxxxshow137;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow137(
			Boolean a1xxyxxxbvxxxxxxxxxxshow137) {
		this.a1xxyxxxbvxxxxxxxxxxshow137 = a1xxyxxxbvxxxxxxxxxxshow137;
	}

	@Column(name = "show138")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow138() {
		return this.a1xxyxxxbvxxxxxxxxxxshow138;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow138(
			Boolean a1xxyxxxbvxxxxxxxxxxshow138) {
		this.a1xxyxxxbvxxxxxxxxxxshow138 = a1xxyxxxbvxxxxxxxxxxshow138;
	}

	@Column(name = "show139")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow139() {
		return this.a1xxyxxxbvxxxxxxxxxxshow139;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow139(
			Boolean a1xxyxxxbvxxxxxxxxxxshow139) {
		this.a1xxyxxxbvxxxxxxxxxxshow139 = a1xxyxxxbvxxxxxxxxxxshow139;
	}

	@Column(name = "show140")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow140() {
		return this.a1xxyxxxbvxxxxxxxxxxshow140;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow140(
			Boolean a1xxyxxxbvxxxxxxxxxxshow140) {
		this.a1xxyxxxbvxxxxxxxxxxshow140 = a1xxyxxxbvxxxxxxxxxxshow140;
	}

	@Column(name = "show141")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow141() {
		return this.a1xxyxxxbvxxxxxxxxxxshow141;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow141(
			Boolean a1xxyxxxbvxxxxxxxxxxshow141) {
		this.a1xxyxxxbvxxxxxxxxxxshow141 = a1xxyxxxbvxxxxxxxxxxshow141;
	}

	@Column(name = "show142")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow142() {
		return this.a1xxyxxxbvxxxxxxxxxxshow142;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow142(
			Boolean a1xxyxxxbvxxxxxxxxxxshow142) {
		this.a1xxyxxxbvxxxxxxxxxxshow142 = a1xxyxxxbvxxxxxxxxxxshow142;
	}

	@Column(name = "show143")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow143() {
		return this.a1xxyxxxbvxxxxxxxxxxshow143;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow143(
			Boolean a1xxyxxxbvxxxxxxxxxxshow143) {
		this.a1xxyxxxbvxxxxxxxxxxshow143 = a1xxyxxxbvxxxxxxxxxxshow143;
	}

	@Column(name = "show144")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow144() {
		return this.a1xxyxxxbvxxxxxxxxxxshow144;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow144(
			Boolean a1xxyxxxbvxxxxxxxxxxshow144) {
		this.a1xxyxxxbvxxxxxxxxxxshow144 = a1xxyxxxbvxxxxxxxxxxshow144;
	}

	@Column(name = "show145")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow145() {
		return this.a1xxyxxxbvxxxxxxxxxxshow145;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow145(
			Boolean a1xxyxxxbvxxxxxxxxxxshow145) {
		this.a1xxyxxxbvxxxxxxxxxxshow145 = a1xxyxxxbvxxxxxxxxxxshow145;
	}

	@Column(name = "show146")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow146() {
		return this.a1xxyxxxbvxxxxxxxxxxshow146;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow146(
			Boolean a1xxyxxxbvxxxxxxxxxxshow146) {
		this.a1xxyxxxbvxxxxxxxxxxshow146 = a1xxyxxxbvxxxxxxxxxxshow146;
	}

	@Column(name = "show147")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow147() {
		return this.a1xxyxxxbvxxxxxxxxxxshow147;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow147(
			Boolean a1xxyxxxbvxxxxxxxxxxshow147) {
		this.a1xxyxxxbvxxxxxxxxxxshow147 = a1xxyxxxbvxxxxxxxxxxshow147;
	}

	@Column(name = "show148")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow148() {
		return this.a1xxyxxxbvxxxxxxxxxxshow148;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow148(
			Boolean a1xxyxxxbvxxxxxxxxxxshow148) {
		this.a1xxyxxxbvxxxxxxxxxxshow148 = a1xxyxxxbvxxxxxxxxxxshow148;
	}

	@Column(name = "show149")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow149() {
		return this.a1xxyxxxbvxxxxxxxxxxshow149;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow149(
			Boolean a1xxyxxxbvxxxxxxxxxxshow149) {
		this.a1xxyxxxbvxxxxxxxxxxshow149 = a1xxyxxxbvxxxxxxxxxxshow149;
	}

	@Column(name = "show150")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow150() {
		return this.a1xxyxxxbvxxxxxxxxxxshow150;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow150(
			Boolean a1xxyxxxbvxxxxxxxxxxshow150) {
		this.a1xxyxxxbvxxxxxxxxxxshow150 = a1xxyxxxbvxxxxxxxxxxshow150;
	}

	@Column(name = "show151")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow151() {
		return this.a1xxyxxxbvxxxxxxxxxxshow151;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow151(
			Boolean a1xxyxxxbvxxxxxxxxxxshow151) {
		this.a1xxyxxxbvxxxxxxxxxxshow151 = a1xxyxxxbvxxxxxxxxxxshow151;
	}

	@Column(name = "show152")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow152() {
		return this.a1xxyxxxbvxxxxxxxxxxshow152;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow152(
			Boolean a1xxyxxxbvxxxxxxxxxxshow152) {
		this.a1xxyxxxbvxxxxxxxxxxshow152 = a1xxyxxxbvxxxxxxxxxxshow152;
	}

	@Column(name = "show153")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow153() {
		return this.a1xxyxxxbvxxxxxxxxxxshow153;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow153(
			Boolean a1xxyxxxbvxxxxxxxxxxshow153) {
		this.a1xxyxxxbvxxxxxxxxxxshow153 = a1xxyxxxbvxxxxxxxxxxshow153;
	}

	@Column(name = "show154")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow154() {
		return this.a1xxyxxxbvxxxxxxxxxxshow154;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow154(
			Boolean a1xxyxxxbvxxxxxxxxxxshow154) {
		this.a1xxyxxxbvxxxxxxxxxxshow154 = a1xxyxxxbvxxxxxxxxxxshow154;
	}

	@Column(name = "show155")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow155() {
		return this.a1xxyxxxbvxxxxxxxxxxshow155;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow155(
			Boolean a1xxyxxxbvxxxxxxxxxxshow155) {
		this.a1xxyxxxbvxxxxxxxxxxshow155 = a1xxyxxxbvxxxxxxxxxxshow155;
	}

	@Column(name = "show156")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow156() {
		return this.a1xxyxxxbvxxxxxxxxxxshow156;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow156(
			Boolean a1xxyxxxbvxxxxxxxxxxshow156) {
		this.a1xxyxxxbvxxxxxxxxxxshow156 = a1xxyxxxbvxxxxxxxxxxshow156;
	}

	@Column(name = "show157")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow157() {
		return this.a1xxyxxxbvxxxxxxxxxxshow157;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow157(
			Boolean a1xxyxxxbvxxxxxxxxxxshow157) {
		this.a1xxyxxxbvxxxxxxxxxxshow157 = a1xxyxxxbvxxxxxxxxxxshow157;
	}

	@Column(name = "show158")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow158() {
		return this.a1xxyxxxbvxxxxxxxxxxshow158;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow158(
			Boolean a1xxyxxxbvxxxxxxxxxxshow158) {
		this.a1xxyxxxbvxxxxxxxxxxshow158 = a1xxyxxxbvxxxxxxxxxxshow158;
	}

	@Column(name = "show159")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow159() {
		return this.a1xxyxxxbvxxxxxxxxxxshow159;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow159(
			Boolean a1xxyxxxbvxxxxxxxxxxshow159) {
		this.a1xxyxxxbvxxxxxxxxxxshow159 = a1xxyxxxbvxxxxxxxxxxshow159;
	}

	@Column(name = "show160")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow160() {
		return this.a1xxyxxxbvxxxxxxxxxxshow160;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow160(
			Boolean a1xxyxxxbvxxxxxxxxxxshow160) {
		this.a1xxyxxxbvxxxxxxxxxxshow160 = a1xxyxxxbvxxxxxxxxxxshow160;
	}

	@Column(name = "show161")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow161() {
		return this.a1xxyxxxbvxxxxxxxxxxshow161;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow161(
			Boolean a1xxyxxxbvxxxxxxxxxxshow161) {
		this.a1xxyxxxbvxxxxxxxxxxshow161 = a1xxyxxxbvxxxxxxxxxxshow161;
	}

	@Column(name = "show162")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow162() {
		return this.a1xxyxxxbvxxxxxxxxxxshow162;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow162(
			Boolean a1xxyxxxbvxxxxxxxxxxshow162) {
		this.a1xxyxxxbvxxxxxxxxxxshow162 = a1xxyxxxbvxxxxxxxxxxshow162;
	}

	@Column(name = "show163")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow163() {
		return this.a1xxyxxxbvxxxxxxxxxxshow163;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow163(
			Boolean a1xxyxxxbvxxxxxxxxxxshow163) {
		this.a1xxyxxxbvxxxxxxxxxxshow163 = a1xxyxxxbvxxxxxxxxxxshow163;
	}

	@Column(name = "show164")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow164() {
		return this.a1xxyxxxbvxxxxxxxxxxshow164;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow164(
			Boolean a1xxyxxxbvxxxxxxxxxxshow164) {
		this.a1xxyxxxbvxxxxxxxxxxshow164 = a1xxyxxxbvxxxxxxxxxxshow164;
	}

	@Column(name = "show165")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow165() {
		return this.a1xxyxxxbvxxxxxxxxxxshow165;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow165(
			Boolean a1xxyxxxbvxxxxxxxxxxshow165) {
		this.a1xxyxxxbvxxxxxxxxxxshow165 = a1xxyxxxbvxxxxxxxxxxshow165;
	}

	@Column(name = "show166")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow166() {
		return this.a1xxyxxxbvxxxxxxxxxxshow166;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow166(
			Boolean a1xxyxxxbvxxxxxxxxxxshow166) {
		this.a1xxyxxxbvxxxxxxxxxxshow166 = a1xxyxxxbvxxxxxxxxxxshow166;
	}

	@Column(name = "show167")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow167() {
		return this.a1xxyxxxbvxxxxxxxxxxshow167;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow167(
			Boolean a1xxyxxxbvxxxxxxxxxxshow167) {
		this.a1xxyxxxbvxxxxxxxxxxshow167 = a1xxyxxxbvxxxxxxxxxxshow167;
	}

	@Column(name = "show168")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow168() {
		return this.a1xxyxxxbvxxxxxxxxxxshow168;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow168(
			Boolean a1xxyxxxbvxxxxxxxxxxshow168) {
		this.a1xxyxxxbvxxxxxxxxxxshow168 = a1xxyxxxbvxxxxxxxxxxshow168;
	}

	@Column(name = "show169")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow169() {
		return this.a1xxyxxxbvxxxxxxxxxxshow169;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow169(
			Boolean a1xxyxxxbvxxxxxxxxxxshow169) {
		this.a1xxyxxxbvxxxxxxxxxxshow169 = a1xxyxxxbvxxxxxxxxxxshow169;
	}

	@Column(name = "show170")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow170() {
		return this.a1xxyxxxbvxxxxxxxxxxshow170;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow170(
			Boolean a1xxyxxxbvxxxxxxxxxxshow170) {
		this.a1xxyxxxbvxxxxxxxxxxshow170 = a1xxyxxxbvxxxxxxxxxxshow170;
	}

	@Column(name = "show171")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow171() {
		return this.a1xxyxxxbvxxxxxxxxxxshow171;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow171(
			Boolean a1xxyxxxbvxxxxxxxxxxshow171) {
		this.a1xxyxxxbvxxxxxxxxxxshow171 = a1xxyxxxbvxxxxxxxxxxshow171;
	}

	@Column(name = "show172")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow172() {
		return this.a1xxyxxxbvxxxxxxxxxxshow172;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow172(
			Boolean a1xxyxxxbvxxxxxxxxxxshow172) {
		this.a1xxyxxxbvxxxxxxxxxxshow172 = a1xxyxxxbvxxxxxxxxxxshow172;
	}

	@Column(name = "show173")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow173() {
		return this.a1xxyxxxbvxxxxxxxxxxshow173;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow173(
			Boolean a1xxyxxxbvxxxxxxxxxxshow173) {
		this.a1xxyxxxbvxxxxxxxxxxshow173 = a1xxyxxxbvxxxxxxxxxxshow173;
	}

	@Column(name = "show174")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow174() {
		return this.a1xxyxxxbvxxxxxxxxxxshow174;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow174(
			Boolean a1xxyxxxbvxxxxxxxxxxshow174) {
		this.a1xxyxxxbvxxxxxxxxxxshow174 = a1xxyxxxbvxxxxxxxxxxshow174;
	}

	@Column(name = "show175")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow175() {
		return this.a1xxyxxxbvxxxxxxxxxxshow175;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow175(
			Boolean a1xxyxxxbvxxxxxxxxxxshow175) {
		this.a1xxyxxxbvxxxxxxxxxxshow175 = a1xxyxxxbvxxxxxxxxxxshow175;
	}

	@Column(name = "show176")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow176() {
		return this.a1xxyxxxbvxxxxxxxxxxshow176;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow176(
			Boolean a1xxyxxxbvxxxxxxxxxxshow176) {
		this.a1xxyxxxbvxxxxxxxxxxshow176 = a1xxyxxxbvxxxxxxxxxxshow176;
	}

	@Column(name = "show177")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow177() {
		return this.a1xxyxxxbvxxxxxxxxxxshow177;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow177(
			Boolean a1xxyxxxbvxxxxxxxxxxshow177) {
		this.a1xxyxxxbvxxxxxxxxxxshow177 = a1xxyxxxbvxxxxxxxxxxshow177;
	}

	@Column(name = "show178")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow178() {
		return this.a1xxyxxxbvxxxxxxxxxxshow178;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow178(
			Boolean a1xxyxxxbvxxxxxxxxxxshow178) {
		this.a1xxyxxxbvxxxxxxxxxxshow178 = a1xxyxxxbvxxxxxxxxxxshow178;
	}

	@Column(name = "show179")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow179() {
		return this.a1xxyxxxbvxxxxxxxxxxshow179;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow179(
			Boolean a1xxyxxxbvxxxxxxxxxxshow179) {
		this.a1xxyxxxbvxxxxxxxxxxshow179 = a1xxyxxxbvxxxxxxxxxxshow179;
	}

	@Column(name = "show180")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow180() {
		return this.a1xxyxxxbvxxxxxxxxxxshow180;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow180(
			Boolean a1xxyxxxbvxxxxxxxxxxshow180) {
		this.a1xxyxxxbvxxxxxxxxxxshow180 = a1xxyxxxbvxxxxxxxxxxshow180;
	}

	@Column(name = "show181")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow181() {
		return this.a1xxyxxxbvxxxxxxxxxxshow181;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow181(
			Boolean a1xxyxxxbvxxxxxxxxxxshow181) {
		this.a1xxyxxxbvxxxxxxxxxxshow181 = a1xxyxxxbvxxxxxxxxxxshow181;
	}

	@Column(name = "show182")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow182() {
		return this.a1xxyxxxbvxxxxxxxxxxshow182;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow182(
			Boolean a1xxyxxxbvxxxxxxxxxxshow182) {
		this.a1xxyxxxbvxxxxxxxxxxshow182 = a1xxyxxxbvxxxxxxxxxxshow182;
	}

	@Column(name = "show183")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow183() {
		return this.a1xxyxxxbvxxxxxxxxxxshow183;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow183(
			Boolean a1xxyxxxbvxxxxxxxxxxshow183) {
		this.a1xxyxxxbvxxxxxxxxxxshow183 = a1xxyxxxbvxxxxxxxxxxshow183;
	}

	@Column(name = "show184")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow184() {
		return this.a1xxyxxxbvxxxxxxxxxxshow184;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow184(
			Boolean a1xxyxxxbvxxxxxxxxxxshow184) {
		this.a1xxyxxxbvxxxxxxxxxxshow184 = a1xxyxxxbvxxxxxxxxxxshow184;
	}

	@Column(name = "show185")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow185() {
		return this.a1xxyxxxbvxxxxxxxxxxshow185;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow185(
			Boolean a1xxyxxxbvxxxxxxxxxxshow185) {
		this.a1xxyxxxbvxxxxxxxxxxshow185 = a1xxyxxxbvxxxxxxxxxxshow185;
	}

	@Column(name = "show186")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow186() {
		return this.a1xxyxxxbvxxxxxxxxxxshow186;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow186(
			Boolean a1xxyxxxbvxxxxxxxxxxshow186) {
		this.a1xxyxxxbvxxxxxxxxxxshow186 = a1xxyxxxbvxxxxxxxxxxshow186;
	}

	@Column(name = "show187")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow187() {
		return this.a1xxyxxxbvxxxxxxxxxxshow187;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow187(
			Boolean a1xxyxxxbvxxxxxxxxxxshow187) {
		this.a1xxyxxxbvxxxxxxxxxxshow187 = a1xxyxxxbvxxxxxxxxxxshow187;
	}

	@Column(name = "show188")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow188() {
		return this.a1xxyxxxbvxxxxxxxxxxshow188;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow188(
			Boolean a1xxyxxxbvxxxxxxxxxxshow188) {
		this.a1xxyxxxbvxxxxxxxxxxshow188 = a1xxyxxxbvxxxxxxxxxxshow188;
	}

	@Column(name = "show189")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow189() {
		return this.a1xxyxxxbvxxxxxxxxxxshow189;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow189(
			Boolean a1xxyxxxbvxxxxxxxxxxshow189) {
		this.a1xxyxxxbvxxxxxxxxxxshow189 = a1xxyxxxbvxxxxxxxxxxshow189;
	}

	@Column(name = "show190")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow190() {
		return this.a1xxyxxxbvxxxxxxxxxxshow190;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow190(
			Boolean a1xxyxxxbvxxxxxxxxxxshow190) {
		this.a1xxyxxxbvxxxxxxxxxxshow190 = a1xxyxxxbvxxxxxxxxxxshow190;
	}

	@Column(name = "show191")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow191() {
		return this.a1xxyxxxbvxxxxxxxxxxshow191;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow191(
			Boolean a1xxyxxxbvxxxxxxxxxxshow191) {
		this.a1xxyxxxbvxxxxxxxxxxshow191 = a1xxyxxxbvxxxxxxxxxxshow191;
	}

	@Column(name = "show192")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow192() {
		return this.a1xxyxxxbvxxxxxxxxxxshow192;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow192(
			Boolean a1xxyxxxbvxxxxxxxxxxshow192) {
		this.a1xxyxxxbvxxxxxxxxxxshow192 = a1xxyxxxbvxxxxxxxxxxshow192;
	}

	@Column(name = "show193")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow193() {
		return this.a1xxyxxxbvxxxxxxxxxxshow193;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow193(
			Boolean a1xxyxxxbvxxxxxxxxxxshow193) {
		this.a1xxyxxxbvxxxxxxxxxxshow193 = a1xxyxxxbvxxxxxxxxxxshow193;
	}

	@Column(name = "show194")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow194() {
		return this.a1xxyxxxbvxxxxxxxxxxshow194;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow194(
			Boolean a1xxyxxxbvxxxxxxxxxxshow194) {
		this.a1xxyxxxbvxxxxxxxxxxshow194 = a1xxyxxxbvxxxxxxxxxxshow194;
	}

	@Column(name = "show195")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow195() {
		return this.a1xxyxxxbvxxxxxxxxxxshow195;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow195(
			Boolean a1xxyxxxbvxxxxxxxxxxshow195) {
		this.a1xxyxxxbvxxxxxxxxxxshow195 = a1xxyxxxbvxxxxxxxxxxshow195;
	}

	@Column(name = "show196")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow196() {
		return this.a1xxyxxxbvxxxxxxxxxxshow196;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow196(
			Boolean a1xxyxxxbvxxxxxxxxxxshow196) {
		this.a1xxyxxxbvxxxxxxxxxxshow196 = a1xxyxxxbvxxxxxxxxxxshow196;
	}

	@Column(name = "show197")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow197() {
		return this.a1xxyxxxbvxxxxxxxxxxshow197;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow197(
			Boolean a1xxyxxxbvxxxxxxxxxxshow197) {
		this.a1xxyxxxbvxxxxxxxxxxshow197 = a1xxyxxxbvxxxxxxxxxxshow197;
	}

	@Column(name = "show198")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow198() {
		return this.a1xxyxxxbvxxxxxxxxxxshow198;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow198(
			Boolean a1xxyxxxbvxxxxxxxxxxshow198) {
		this.a1xxyxxxbvxxxxxxxxxxshow198 = a1xxyxxxbvxxxxxxxxxxshow198;
	}

	@Column(name = "show199")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow199() {
		return this.a1xxyxxxbvxxxxxxxxxxshow199;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow199(
			Boolean a1xxyxxxbvxxxxxxxxxxshow199) {
		this.a1xxyxxxbvxxxxxxxxxxshow199 = a1xxyxxxbvxxxxxxxxxxshow199;
	}

	@Column(name = "show200")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow200() {
		return this.a1xxyxxxbvxxxxxxxxxxshow200;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow200(
			Boolean a1xxyxxxbvxxxxxxxxxxshow200) {
		this.a1xxyxxxbvxxxxxxxxxxshow200 = a1xxyxxxbvxxxxxxxxxxshow200;
	}

	@Column(name = "show201")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow201() {
		return this.a1xxyxxxbvxxxxxxxxxxshow201;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow201(
			Boolean a1xxyxxxbvxxxxxxxxxxshow201) {
		this.a1xxyxxxbvxxxxxxxxxxshow201 = a1xxyxxxbvxxxxxxxxxxshow201;
	}

	@Column(name = "show202")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow202() {
		return this.a1xxyxxxbvxxxxxxxxxxshow202;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow202(
			Boolean a1xxyxxxbvxxxxxxxxxxshow202) {
		this.a1xxyxxxbvxxxxxxxxxxshow202 = a1xxyxxxbvxxxxxxxxxxshow202;
	}

	@Column(name = "show203")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow203() {
		return this.a1xxyxxxbvxxxxxxxxxxshow203;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow203(
			Boolean a1xxyxxxbvxxxxxxxxxxshow203) {
		this.a1xxyxxxbvxxxxxxxxxxshow203 = a1xxyxxxbvxxxxxxxxxxshow203;
	}

	@Column(name = "show204")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow204() {
		return this.a1xxyxxxbvxxxxxxxxxxshow204;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow204(
			Boolean a1xxyxxxbvxxxxxxxxxxshow204) {
		this.a1xxyxxxbvxxxxxxxxxxshow204 = a1xxyxxxbvxxxxxxxxxxshow204;
	}

	@Column(name = "show205")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow205() {
		return this.a1xxyxxxbvxxxxxxxxxxshow205;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow205(
			Boolean a1xxyxxxbvxxxxxxxxxxshow205) {
		this.a1xxyxxxbvxxxxxxxxxxshow205 = a1xxyxxxbvxxxxxxxxxxshow205;
	}

	@Column(name = "show206")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow206() {
		return this.a1xxyxxxbvxxxxxxxxxxshow206;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow206(
			Boolean a1xxyxxxbvxxxxxxxxxxshow206) {
		this.a1xxyxxxbvxxxxxxxxxxshow206 = a1xxyxxxbvxxxxxxxxxxshow206;
	}

	@Column(name = "show207")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow207() {
		return this.a1xxyxxxbvxxxxxxxxxxshow207;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow207(
			Boolean a1xxyxxxbvxxxxxxxxxxshow207) {
		this.a1xxyxxxbvxxxxxxxxxxshow207 = a1xxyxxxbvxxxxxxxxxxshow207;
	}

	@Column(name = "show208")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow208() {
		return this.a1xxyxxxbvxxxxxxxxxxshow208;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow208(
			Boolean a1xxyxxxbvxxxxxxxxxxshow208) {
		this.a1xxyxxxbvxxxxxxxxxxshow208 = a1xxyxxxbvxxxxxxxxxxshow208;
	}

	@Column(name = "show209")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow209() {
		return this.a1xxyxxxbvxxxxxxxxxxshow209;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow209(
			Boolean a1xxyxxxbvxxxxxxxxxxshow209) {
		this.a1xxyxxxbvxxxxxxxxxxshow209 = a1xxyxxxbvxxxxxxxxxxshow209;
	}

	@Column(name = "show210")
	public Boolean getA1xxyxxxbvxxxxxxxxxxshow210() {
		return this.a1xxyxxxbvxxxxxxxxxxshow210;
	}

	public void setA1xxyxxxbvxxxxxxxxxxshow210(
			Boolean a1xxyxxxbvxxxxxxxxxxshow210) {
		this.a1xxyxxxbvxxxxxxxxxxshow210 = a1xxyxxxbvxxxxxxxxxxshow210;
	}

	@Column(name = "statusfl")
	public Integer getZixxzzfxhhxxxxxxxxxxstatusfl() {
		return this.zixxzzfxhhxxxxxxxxxxstatusfl;
	}

	public void setZixxzzfxhhxxxxxxxxxxstatusfl(
			Integer zixxzzfxhhxxxxxxxxxxstatusfl) {
		this.zixxzzfxhhxxxxxxxxxxstatusfl = zixxzzfxhhxxxxxxxxxxstatusfl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusfldt", length = 29)
	public Date getZjxxcztxlxxxxxxxxxxxstatusfldt() {
		return this.zjxxcztxlxxxxxxxxxxxstatusfldt;
	}

	public void setZjxxcztxlxxxxxxxxxxxstatusfldt(
			Date zjxxcztxlxxxxxxxxxxxstatusfldt) {
		this.zjxxcztxlxxxxxxxxxxxstatusfldt = zjxxcztxlxxxxxxxxxxxstatusfldt;
	}

	@Column(name = "owner", length = 40)
	@Size(max = 40)
	public String getZ3xxutoxlhxxxxxxxxxxowner() {
		return this.z3xxutoxlhxxxxxxxxxxowner;
	}

	public void setZ3xxutoxlhxxxxxxxxxxowner(String z3xxutoxlhxxxxxxxxxxowner) {
		this.z3xxutoxlhxxxxxxxxxxowner = z3xxutoxlhxxxxxxxxxxowner;
	}

	@Column(name = "owner2", length = 40)
	@Size(max = 40)
	public String getZzxxu2oxxhxxxxxxxxxxowner2() {
		return this.zzxxu2oxxhxxxxxxxxxxowner2;
	}

	public void setZzxxu2oxxhxxxxxxxxxxowner2(String zzxxu2oxxhxxxxxxxxxxowner2) {
		this.zzxxu2oxxhxxxxxxxxxxowner2 = zzxxu2oxxhxxxxxxxxxxowner2;
	}

}
