<#assign tobegeneratedCandidate = "N">  
<#include "../view/assigns/PositionLength.properties" >
<#if (pojo.shortName?length > eL)>
<#assign menuAttributes = pojo.shortName?substring(0,9)?upper_case>
<#if (menuAttributes?substring(efS,efE) == '20' || menuAttributes?substring(efS,efE) == '30' || menuAttributes?substring(efS,efE) == '40' || menuAttributes?substring(efS,efE) == '1A'  || menuAttributes?substring(efS,efE) == '1F') >
 <#assign tobegeneratedCandidate ="Y" >
</#if>
<#if tobegeneratedCandidate == "Y">  
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
                             "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<#assign entityName = pojo.shortName>
<#assign componentName = util.lower(entityName)>
<#include "../util/TypeInfo.ftl">
<#include "../view/assigns/mergedassigns.properties" >
<#assign menuAttributesFunction = entityName?substring(efS,efE)>
<#assign listName = componentName + "List">
<#assign homeName = componentName + "Home">
<#assign pageName = entityName?substring(eL)>
<#assign editPageName = entityName?substring(eL) + "Edit">
<#assign listPageName = entityName?substring(eL) + "LabelsPrint">
<#assign menuPageName = "home">
<#assign reportName = "reportName">
<#assign displayAs = "displayAs">
<#assign start = "start">
<#assign end = "end">
<#assign markedOnes = "markedOnes">    
<#assign statusFlagField="">
<#assign targetId = "targetId">   
<#assign useDateKey="">
<#assign useDateKeyField="">
<#assign keyedKeyName = "">
<#assign documentField="">
<#assign keyfromsubkeys = "Y">
<#foreach property in pojo.allPropertiesIterator>
 <#if !c2h.isCollection(property) && !c2h.isManyToOne(property)>
  <#if c2j.isComponent(property)>
   <#foreach componentProperty in property.value.propertyIterator>
     <#if componentProperty.name?substring(pfS,pfE)=="ss">
      <#assign useDateKey="Y">
      <#assign useDateKeyField=componentProperty.name>
     </#if>
   </#foreach>
  <#else>
    <#if property.name?substring(pfS,pfE)=="ee">
      <#assign useDateKey="Y">
    </#if>
    <#if property.name?substring(pfS,pfS2)=="o"  >
           <#assign keyAutoGen="Y">
    </#if>
    <#if property.name?substring(pkS,pkE)=="k" || property.name?substring(pkS,pkE)=="n"  >
           <#assign keyedKeyName=property.name>
    </#if>
    <#if property.name?substring(pfS,pfE)=="zf"> 
      <#assign statusFlagField=property.name>
    </#if>   
    <#if property.name?substring(5,7)=="zd" || property.name?substring(5,7)=="zb" || property.name?substring(5,7)=="za"  > 
      <#assign documentField=property.name>
    </#if> 
  </#if>
 </#if>
</#foreach>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="layout/rtemplate.xhtml">
<#-- Generated By reportlabelsprint.ftl on ${.now} -->
<f:metadata>
    <f:viewAction action="${'#'}{${homeName}.restrict()}" />
</f:metadata>
<ui:define name="title">${'#'}{customIdentity.owner2} webpage to print Avery labels for ${'#'}{messages['${entityName?substring(pL)?cap_first}']}</ui:define>
<ui:remove>
 This .ftl produces {class-name}LabelsPrint which calls EntityList print method with report name w prefix like 59,66 etc
 Report name is {class_name}labelsReport ex: 59Fpxxfq1a5xwwqqhxxxxxitemlabelsReport.

 Based on the prefix, print will set fields like show1,2 etc in truefalse table and also pass those as a report
  parameters like show001 boolean (upto 137 fields ).

 Reports used by these are generated by genjasperlabellreports.ftl as classname.jrxml ex:Fpxxfq1a5xwwqqhxxxxxitemlabelsReport.jrxml
               
</ui:remove>
                       
<ui:define name="body">
    <h:form id="${componentName}Report" styleClass="edit">
     <h:outputStylesheet>

     </h:outputStylesheet>

	<p:toolbar height="26" itemSeparator="grid">
	  <p:toolbarGroup>
              <h:commandButton id="printb" value="Print"  action="${'#'}{${listName}.print}" image="/img/Print16.gif" />
	  </p:toolbarGroup>
	  <p:toolbarGroup>
              <h:button id="tdoneh" image="./img/home_24.png"  alt="Home" value="Home" propagation="end" outcome="/home.xhtml" />
	  </p:toolbarGroup>
	  <p:toolbarGroup location="right">
              <h:outputText value="${'#'}{customIdentity.username}"/> 
              <h:outputText value="${'#'}{authenticator.currcaldates}"/> 
 		   <h:graphicImage value="/img/Search16.gif" styleClass="pic"/>
	  </p:toolbarGroup>
	  <p:toolbarGroup location="right">
		   <h:graphicImage id="Helpt" value="/img/help.gif" styleClass="pic" rendered="${'#'}{messages['${componentName?substring(eL)?cap_first}LabelsPrintHelp']!=null}">
             <p:tooltip > <span style="white-space: nowrap"> <h:inputTextarea  cols="70" rows="10" readonly="true"  value="${'#'}{messages['${componentName?substring(eL)?cap_first}LabelsPrintHelp']}"/></span> </p:tooltip> 
             </h:graphicImage>
	  </p:toolbarGroup>
	</p:toolbar>
       <h:messages globalOnly="true" styleClass="message" id="globalMessages"/>
            <#if (menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25")  
              || menuAttributesFunction?contains("26")  || menuAttributesFunction?contains("27")  || menuAttributesFunction?contains("33")
              || menuAttributesFunction?contains("34")  || menuAttributesFunction?contains("35")  || menuAttributesFunction?contains("36")
              || menuAttributesFunction?contains("37")  || menuAttributesFunction?contains("38")  || menuAttributesFunction?contains("44")  )>
             <p:panel  toggleable="true" toggleableHeader="true" style="width: 20%;" header="${'#'}{messages['${entityName?substring(eL)?cap_first}']}" switchType="client" collapsed="false"
              leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
              <h:panelGrid columns="1">
              <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['label.reportName']}</ui:define>
                <h:selectOneMenu id="${reportName}" value="${'#'}{${listName}.${reportName}}">
                 <f:selectItem id="ritem1" itemLabel="${entityName?substring(eL)?cap_first}" itemValue="${entityName}Master"/>
                 <f:selectItem id="ritem2" itemLabel="${entityName?substring(eL)?cap_first} List" itemValue="${entityName}" />
                </h:selectOneMenu> 
              </ui:decorate>
              </h:panelGrid>
             </p:panel >
            <#else>
             <p:panel  toggleable="true" toggleableHeader="true" style="width: 20%;" header="${'#'}{messages['${entityName?substring(eL)?cap_first}']}" switchType="client" collapsed="false"
              leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
              <h:panelGrid columns="1">
              <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['label.Size']}</ui:define>
                <h:selectOneMenu id="${reportName}" value="${'#'}{${listName}.${reportName}}">
                 <f:selectItem id="ritem1" itemLabel="${entityName?substring(eL)?cap_first}Avery5960" itemValue="59${entityName}labelsReport" />
                 <f:selectItem id="ritem2" itemLabel="${entityName?substring(eL)?cap_first}Avery6656" itemValue="66${entityName}labelsReport"/>
                 <f:selectItem id="ritem3" itemLabel="${entityName?substring(eL)?cap_first}SKUAvery5960" itemValue="59${entityName}labelsReport.more" />
                 <#if (menuAttributesFunction?contains("1a"))>
                  <f:selectItem id="ritem4" itemLabel="${entityName?substring(eL)?cap_first}UPCDymo30299" itemValue="up${entityName?substring(eL)?cap_first}labelsDymo30299Report1019UPC" />
                  <f:selectItem id="ritem5" itemLabel="${entityName?substring(eL)?cap_first}SKUDymo30334" itemValue="12${entityName?substring(eL)?cap_first}labelsDymo30334Report3257128a" />
                 <#else>
                 </#if>
                </h:selectOneMenu> 
              </ui:decorate>
              </h:panelGrid>
             </p:panel >
            </#if>
         <p:panel  toggleable="true" toggleableHeader="true" style="width: 20%;" header="Label details parameters" switchType="client" collapsed="true"
          leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.displayAs']}</ui:define>
                <h:selectOneMenu id="${displayAs}" value="${'#'}{${listName}.${displayAs}}">
                 <f:selectItem id="ditem1" itemLabel="PDF" itemValue="PDF" />
                 <f:selectItem id="ditem2" itemLabel="HTML" itemValue="HTML" />
                 <f:selectItem id="ditem3" itemLabel="CSV" itemValue="HTML" />
                 <f:selectItem id="ditem4" itemLabel="EXCEL" itemValue="EXCEL" />
                </h:selectOneMenu> 
            </ui:decorate>
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.markedOnes']}</ui:define>
                <h:inputText id="${markedOnes}" value="${'#'}{${listName}.${markedOnes}}"/>
            </ui:decorate>
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.targetId']}</ui:define>
                <h:selectOneMenu id="${targetId}" value="${'#'}{${listName}.${targetId}}">
                 <f:selectItem id="titem1" itemLabel="None" itemValue="None" />
                 <f:selectItem id="titem2" itemLabel="DownLoad" itemValue="DownLoad" />
                 <f:selectItem id="titem3" itemLabel="Archive" itemValue="Archive" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
         </p:panel >
        <div class="actionButtons">
         <h:panelGrid columns="8">      
            <h:commandButton id="report" value="Generate Labels" styleClass="buttonMain"  onclick="this.form.target='_blank'"  action="${'#'}{${listName}.print}"/>

            <h:button outcome="/${'#'}{empty ${componentName}From ? '${menuPageName}' : ${componentName}From}.xhtml"
                    id="done"
                 value="Done"/>
                 <f:param name="reportName" value="${'#'}{${listName}.${reportName}}"/>
                 <f:param name="displayAs" value="${'#'}{${listName}.${displayAs}}" /> 
                 <h:graphicImage value="/img/script_start16.png" />
            <h:panelGrid columns="2">
                 <h:selectOneMenu  value="${'#'}{${listName}.start}" 
                  rendered="${'#'}{!fn:containsIgnoreCase(request.getHeader('User-Agent'), 'Jayfox')}">
                  <f:selectItem itemValue="${'#'}{null}" itemLabel="" />
                  <#if (menuAttributesFunction?contains("1a"))>
                   <f:selectItems value="${'#'}{${listName}.get${entityName?substring(10)}KeyList()}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#else>
                   <f:selectItems value="${'#'}{${listName}.suggest(${homeName}.prefix)}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  </#if>  
                 </h:selectOneMenu>
            </h:panelGrid>
            <h:graphicImage value="/img/script_stop16.png" />
            <h:panelGrid columns="2">
                 <h:selectOneMenu  value="${'#'}{${listName}.end}" 
                  rendered="${'#'}{!fn:containsIgnoreCase(request.getHeader('User-Agent'), 'Jayfox')}">
                  <f:selectItem itemValue="${'#'}{null}" itemLabel="" />
                  <#if (menuAttributesFunction?contains("1a"))>
                   <f:selectItems value="${'#'}{${listName}.get${entityName?substring(10)}KeyList()}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#else>
                   <f:selectItems value="${'#'}{${listName}.suggest(${homeName}.prefix)}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  </#if>  
                 </h:selectOneMenu>
            </h:panelGrid>
         </h:panelGrid>      
        </div>

        
    
 <p:panel  toggleable="true" toggleableHeader="true" header="${'#'}{messages['${entityName?substring(eL)?cap_first}']}- ${'#'}{messages['List']}" switchType="ajax" collapsed="true"
     leftCollapsedIcon="/img/List16.png" leftExpandedIcon="/img/control_remove16.png">

        <f:facet name="header">${entityName?substring(eL)?cap_first} search results</f:facet>
    <div class="results" id="${componentName}List" style="overflow-x:auto">

    <h:outputText value="No ${componentName?substring(eL)?cap_first} exists" 
               rendered="${'#'}{empty ${listName}.resultList}"/>
    <p:dataTable id="${listName}"  frozenColumns="2" resizableColumns="true" tableStyle="table-layout:auto;"  scrollable="false" scrollWidth="100%" 
                var="${componentName}"
              value="${'#'}{${listName}.resultList}"
           rendered="${'#'}{not empty ${listName}.resultList}">
           <#assign loop =0 >
           <#if c2j.isComponent(pojo.identifierProperty)>
            <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
             <#if loop = 0>
              <#assign selectParam = '_'+componentName+'.' + pojo.identifierProperty.name>
              <#assign loop =1 >
             </#if>
            </#foreach> 
           <#else>
            <#assign selectParam = '_'+componentName +'.'+pojo.identifierProperty.name>
           </#if>

        <p:column>
                            <f:facet id="MarkerFacet" name="header">
                                <h:outputText id="markit" value="Flag" />
                            </f:facet>
                            <h:selectBooleanCheckbox id="MarkItCheckbox" value="${'#'}{${homeName}.checked[${componentName}.a0xxuobxbxxxxxxxxxxxsid]}"/>
            <h:link outcome="/${'#'}{empty from ? '${pageName}' : from}.xhtml"
                   value="${'#'}{empty from ? 'View' : 'Select'}"
             propagation="${'#'}{empty from ? 'none' : 'default'}"
                      id="${componentName}ViewId">
             <#if pojo.isComponent(pojo.identifierProperty)>
              <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
                <f:param name="${componentName}${componentProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}.${componentProperty.name}}"/>
              </#foreach>
             <#else>
                <f:param name="${componentName}${pojo.identifierProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}}"/>
             </#if>
            </h:link>
            <h:graphicImage 
                  value="/img/accept16.png"  rendered="${'#'}{${componentName}.${statusFlagField} gt 127 ?'true': 'false'}">
            </h:graphicImage> 

        </p:column>

<#-- @outputValue is a macro inside typeInfo.ftl in r3gen/util dir -->
<#foreach property in pojo.allPropertiesIterator>
<#if (property.name?length > eL)>
<#if !c2h.isCollection(property) && !c2h.isManyToOne(property)>
 <#if pojo.isComponent(property)>
  <#foreach componentProperty in property.value.propertyIterator>
        <p:column>
            <f:facet name="header">
            <#assign propertyPath = property.name + '.' + componentProperty.name>
                <ui:include src="layout/sort.xhtml">
                    <ui:param name="entityList" value="${'#'}{${listName}}"/>
                    <ui:param name="propertyLabel" value=${'#'}{messages['${componentProperty.name?substring(pL)?cap_first}']}"/>
                    <ui:param name="propertyPath" value="${'#'}${componentName}.${propertyPath}"/>
                </ui:include>
            </f:facet>
            <@outputValue property=componentProperty expression="${'#'}{${componentName}.${property.name}.${componentProperty.name}}" indent=pL/>

        </p:column>
  </#foreach>
 <#else>
        <#if ( ((property.name?substring(pfS,pfE)!="za") && (property.name?substring(pfS,pfE)!="zb") && (property.name?substring(pfS,pfE)!="zd") && (property.name?substring(pfS,pfE)!="zf") && (property.name?substring(pfS,pfE)!="zt")) && ((property.name?substring(0,1) == "y") || (property.name?substring(0,1) == "z" )
        || (property.name?substring(0,6) == "a0xxuo" ) ) )   >
        <#-- ${property.name}-->
      <#else>
        <p:column>
            <f:facet name="header">
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(pL)} ${'#'}{${listName}.order=='${property.name} asc' ? messages.down : ( ${listName}.order=='${property.name} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${property.name} asc' ? '${property.name} desc' : '${property.name} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${property.name}}
        </p:column>
      </#if>
 </#if>
</#if>
<#if c2h.isManyToOne(property)>
<#assign parentPojo = c2j.getPOJOClass(cfg.getClassMapping(property.value.referencedEntityName))>
<#if parentPojo.isComponent(parentPojo.identifierProperty)>
<#foreach componentProperty in parentPojo.identifierProperty.value.propertyIterator>
        <p:column>
            <f:facet name="header">
             <#assign propertyPath = property.name + '.' + parentPojo.identifierProperty.name + '.' + componentProperty.name>
                <h:link styleClass="columnHeader"
                    value="${property.name?substring(eL)} ${componentProperty.name?substring(pL)} ${'#'}{${listName}.order=='${propertyPath} asc' ? messages.down : ( ${listName}.order=='${propertyPath} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${propertyPath} asc' ? '${propertyPath} desc' : '${propertyPath} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${propertyPath}}
        </p:column>
</#foreach>
<#else>
        <p:column>
            <f:facet name="header">
<#assign propertyPath = property.name + '.' + parentPojo.identifierProperty.name>
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(eL)} ${parentPojo.identifierProperty.name?substring(pL)} ${'#'}{${listName}.order=='${propertyPath} asc' ? messages.down : ( ${listName}.order=='${propertyPath} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${propertyPath} asc' ? '${propertyPath} desc' : '${propertyPath} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${propertyPath}}
        </p:column>
</#if>
</#if>
</#if>
</#foreach>
        <p:column styleClass="action">
            <f:facet name="header">Action</f:facet>
            ${'#'}{' '}
            <h:link outcome="/${editPageName}.xhtml"
                   value="Edit"
             propagation="none"
                      id="${componentName}Edit"
                rendered="${'#'}{empty from and (customIdentity.hasRole('UH')||customIdentity.hasRole('UQ')||customIdentity.hasRole('VH')||customIdentity.hasRole('VQ'))}">
             <#if pojo.isComponent(pojo.identifierProperty)>
              <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
                <f:param name="${componentName}${componentProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}.${componentProperty.name}}"/>
              </#foreach>
             <#else>
                <f:param name="${componentName}${pojo.identifierProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}}"/>
             </#if>
            </h:link>
            ${'#'}{' '}
           <#if documentField != "" >
            <h:commandButton id="Download" value="Download" rendered="${'#'}{empty from}" action="${'#'}{${homeName}.downloadThis(${selectParam})}"/>
           </#if>
        </p:column>
</p:dataTable>

    </div>
    </p:panel>
    
    <div class="tableControl">
      
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.previousExists}" 
               value="${'#'}{messages.left}${'#'}{messages.left} First Page"
                  id="firstPage">
          <f:param name="firstResult" value="0"/>
        </h:link>
        
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.previousExists}" 
               value="${'#'}{messages.left} Previous Page"
                  id="previousPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.previousFirstResult}"/>
        </h:link>
        
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.nextExists}" 
               value="Next Page ${'#'}{messages.right}"
                  id="nextPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.nextFirstResult}"/>
        </h:link>
        
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.nextExists}" 
               value="Last Page ${'#'}{messages.right}${'#'}{messages.right}"
                  id="lastPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.lastFirstResult}"/>
        </h:link>
        
    </div>
    
    <div styleClass="actionButtons" rendered="${'#'}{empty from}">
        <h:button outcome="/${editPageName}.xhtml"
                    id="create" 
                 value="Create ${componentName?substring(eL)}">
<#assign idName = componentName + util.upper(pojo.identifierProperty.name)>
<#if c2j.isComponent(pojo.identifierProperty)>
<#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
<#assign cidName = componentName + util.upper(componentProperty.name)>
            <f:param name="${cidName}" value="1"/>
</#foreach>
<#else>
            <f:param name="${idName}" value="1"/>
</#if>
        </h:button>
    </div>
     <p:hotkey  onkeydown="PF('report').click()" preventDefault="true" enabledInInput="true" key="return">
     </p:hotkey>

    </h:form>
    
</ui:define>

</ui:composition>
</#if>
</#if>

