<#include "../view/assigns/PositionLength.properties" >
<#if (pojo.shortName?length > eL)>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
                             "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<#assign entityName = pojo.shortName>
<#assign componentName = util.lower(entityName)>
<#include "../util/TypeInfo.ftl">
<#include "../view/assigns/mergedassigns.properties" >
<#assign menuAttributesFunction = entityName?substring(efS,efE)>
<#assign listName = componentName + "List">
<#assign homeName = componentName + "Home">
<#assign pageName = entityName?substring(eL)>
<#assign editPageName = entityName?substring(eL) + "Edit">
<#assign listPageName = entityName?substring(eL) + "List">
<#assign menuPageName = "home">
<#assign reportName = "reportName">
<#assign displayAs = "displayAs">
<#assign start = "start">
<#assign end = "end">
<#assign markedOnes = "markedOnes">    
<#assign statusFlagField="">
<#assign targetId = "targetId">   
<#assign sortKey = "sortKey">   
<#assign sortOrder = "sortOrder">   
<#assign useDateKey="">
<#assign useDateKeyField="">
<#assign keyedKeyName = "">
<#assign documentField="">
<#assign keyfromsubkeys = "Y">
<#foreach property in pojo.allPropertiesIterator>
<#if (property.name?length > eL)>
 <#if !c2h.isCollection(property) && !c2h.isManyToOne(property)>
  <#if c2j.isComponent(property)>
   <#foreach componentProperty in property.value.propertyIterator>
     <#if componentProperty.name?substring(pfS,pfE)=="ss">
      <#assign useDateKey="Y">
      <#assign useDateKeyField=componentProperty.name>
     </#if>
   </#foreach>
  <#else>
    <#if property.name?substring(pfS,pfE)=="ee">
      <#assign useDateKey="Y">
    </#if>
    <#if property.name?substring(pfS,pfS2)=="o"  >
           <#assign keyAutoGen="Y">
    </#if>
    <#if property.name?substring(pkS,pkE)=="k" || property.name?substring(pkS,pkE)=="n"  >
           <#assign keyedKeyName=property.name>
    </#if>
  </#if>
 </#if>
</#if>
</#foreach>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pe="http://primefaces.org/ui/extensions"
                template="layout/rtemplate.xhtml">
<#-- Generated By report.xhtml.ftl on ${.now} --->
<f:metadata>
    <f:viewAction action="${'#'}{${homeName}.restrict()}" />
</f:metadata>
<ui:define name="title">${'#'}{customIdentity.owner2} webpage to print Report for ${'#'}{messages['${entityName?substring(pL)?cap_first}']}</ui:define>
<ui:remove>
 This .ftl produces {class-name}Report.xhtml which calls EntityList print method with report name w prefix like dg,me,a1 etc
 Report name is class-name Fpxxfq1a5xwwqqhxxxxxitem ex: meFpxxfq1a5xwwqqhxxxxxitem.

 Based on the prefix, print will set fields like show1,2 etc in truefalse table and also pass those as a report
  parameters like show001 boolean (upto 137 fields ).

 Reports used by these are generated by gentitletablelistreports.ftl as classname.jrxml ex:Fpxxfq1a5xwwqqhxxxxxitem.jrxml
 ReportGenerator has hardcoded extra logic to use subreport to show needed fields from foreign table ex:counted stock 
 from serialnumbers table         
 
 For certain entities (with details as in txns) there is another report fi${entityName}Master
 which has 3 subreports under it 
      
</ui:remove>
                       
<ui:define name="body">
    <h:form id="${componentName}Report" styleClass="edit">
     <h:outputStylesheet>
.ui-datatable table {
border-collapse: collapse;
width: 100%;
table-layout: auto !important;
}

     </h:outputStylesheet>

	<p:toolbar height="26" itemSeparator="grid">
	  <p:toolbarGroup>
              <h:commandButton id="printb" value="Print"  action="${'#'}{${listName}.print}" image="/img/Print16.gif" />
	  </p:toolbarGroup>
	  <p:toolbarGroup>
              <h:button id="tdoneh" image="./img/home_24.png"  alt="Home" value="Home" propagation="end" outcome="/home.xhtml" />
	  </p:toolbarGroup>
	  <p:toolbarGroup location="right">
              <h:outputText value="${'#'}{customIdentity.username}"/> 
              <h:outputText value="${'#'}{authenticator.currcaldates}"/> 
	  </p:toolbarGroup>
	  <p:toolbarGroup location="right">
		   <h:graphicImage id="Helpt" value="/img/help.gif" styleClass="pic" rendered="${'#'}{messages['${componentName?substring(eL)?cap_first}ReportHelp']!=null}">
             <p:tooltip > <span style="white-space: nowrap"> <h:inputTextarea  cols="70" rows="10" readonly="true"  value="${'#'}{messages['${componentName?substring(eL)?cap_first}ReportHelp']}"/></span> </p:tooltip> 
             </h:graphicImage>
	  </p:toolbarGroup>
	</p:toolbar>
       <h:messages globalOnly="true" styleClass="message" id="globalMessages"/>
<#--
 postion 10 in property can be used for default report generation ie de
 demographic ie dg will show mostly not qty/amount based on type
 merix ie me is just the opposite
 the above stock reports are done by app logic in entitylist.ftl and uses truefalse table showxxx fields
 adhocs ie a1 or a2 for custom report and can be done via setup/truefalse edit
 jun28 2019 if txn report let start/end show all but via searchStatus filter further. This was needed to see data for closed records
-->
            <#if (menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25")  
              || menuAttributesFunction?contains("26")  || menuAttributesFunction?contains("27")  || menuAttributesFunction?contains("33")
              || menuAttributesFunction?contains("34")  || menuAttributesFunction?contains("35")  || menuAttributesFunction?contains("36")
              || menuAttributesFunction?contains("37")  || menuAttributesFunction?contains("38")  || menuAttributesFunction?contains("44")  
              || menuAttributesFunction?contains("9c")
             )>
             <p:panel  toggleable="true" toggleableHeader="true" style="width: 20%;" header="${'#'}{messages['${entityName?substring(eL)?cap_first}']} Report Selection" switchType="client" collapsed="false"
              leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
              <h:panelGrid columns="1">
              <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.reportName']}</ui:define>
                <h:selectOneMenu id="${reportName}" value="${'#'}{${listName}.${reportName}}">
                 <#if !menuAttributesFunction?contains("36")>
                 <f:selectItem id="ritem0" itemLabel="${entityName?substring(eL)?cap_first}" itemValue="fi${entityName}Master"/>
                 </#if>
                 <#if menuAttributesFunction?contains("26")>
                 <f:selectItem id="ritem57" itemLabel="Receipt57(dymo 30270)" itemValue="57cuinvoiceReceipt57Master"/>
                 </#if>
                 <f:selectItem id="ritem1" itemLabel="${entityName?substring(eL)?cap_first} List" itemValue="de${entityName}" />
                 <f:selectItem id="ritem2" itemLabel="${entityName?substring(eL)?cap_first} Demographics " itemValue="dg${entityName}" />
                 <f:selectItem id="ritem3" itemLabel="${entityName?substring(eL)?cap_first} Metrics" itemValue="me${entityName}" />
                 <#if menuAttributesFunction?contains("26")>
                 <#-- needs debugging why returns null
                  <f:selectItem id="ritem4" itemLabel="${'#'}{messages['Statement']}" itemValue="a1CustomerTxns" />
                 -->
                 <#else>
                  <f:selectItem id="ritem4" itemLabel="${entityName?substring(eL)?cap_first} Ad hoc 1" itemValue="a1${entityName}" />
                 </#if>
                 <f:selectItem id="ritem5" itemLabel="${entityName?substring(eL)?cap_first} Ad hoc 2" itemValue="a2${entityName}" />
                </h:selectOneMenu> 
              </ui:decorate>
              </h:panelGrid>
             </p:panel >
            <#else>
             <p:panel  toggleable="true" toggleableHeader="true" style="width: 30%;" header="${'#'}{messages['${entityName?substring(eL)?cap_first}']} Report Selection" switchType="client" collapsed="false"
              leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
              <h:panelGrid columns="1">
              <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.reportName']}</ui:define>
                <h:selectOneMenu id="${reportName}" value="${'#'}{${listName}.${reportName}}">
                 <f:selectItem id="sitem1" itemLabel="${entityName?substring(eL)?cap_first} List" itemValue="de${entityName}" />
                 <f:selectItem id="sitem2" itemLabel="${entityName?substring(eL)?cap_first} Demographics " itemValue="dg${entityName}" />
                 <f:selectItem id="sitem3" itemLabel="${entityName?substring(eL)?cap_first} Metrics" itemValue="me${entityName}" />
                 <#if menuAttributesFunction?contains("1a")>
                  <f:selectItem id="sitem4C" itemLabel="${entityName?substring(eL)?cap_first} Stock Count" itemValue="meFxxxuq1ffxwwqqhefxxxserialnumbers" />
                 </#if>
                 <#if menuAttributesFunction?contains("20")>
                  <f:selectItem id="ritem4" itemLabel="${'#'}{messages['Statement']}" itemValue="a1CustomerTxns" />
                  <f:selectItem id="sitem4C" itemLabel="${entityName?substring(eL)?cap_first} Ad hoc 1" itemValue="a1${entityName}" />
                 <#else>
                  <f:selectItem id="ritem4" itemLabel="${entityName?substring(eL)?cap_first} Ad hoc 1" itemValue="a1${entityName}" />
                 </#if>
                 <f:selectItem id="sitem5" itemLabel="${entityName?substring(eL)?cap_first} Ad hoc 2" itemValue="a2${entityName}" />
                </h:selectOneMenu> 
              </ui:decorate>
              </h:panelGrid>
             </p:panel >
            </#if>
         <p:panel  toggleable="true" toggleableHeader="true" style="width: 25%;" header="Report Generation parameters" switchType="client" collapsed="true"
          leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
       <h:panelGrid columns="2">
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.displayAs']}</ui:define>
                <h:selectOneMenu id="displayAs" value="${'#'}{${listName}.displayAs}">
                 <f:selectItem id="ditem2" itemLabel="HTML" itemValue="HTML" />
                 <f:selectItem id="ditem1" itemLabel="PDF" itemValue="PDF" />
                 <f:selectItem id="ditem3" itemLabel="CSV" itemValue="CSV" />
                 <f:selectItem id="ditem4" itemLabel="EXCEL" itemValue="EXCEL" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.markedOnes']}</ui:define>
                <h:inputText id="markedOnes" value="${'#'}{${listName}.markedOnes}"/>
            </ui:decorate>
        </h:panelGrid>
       </h:panelGrid>
       <h:panelGrid columns="2">

        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.targetId']}</ui:define>
                <h:selectOneMenu id="targetId" value="${'#'}{${listName}.targetId}">
                 <f:selectItem id="titem1" itemLabel="None" itemValue="None" />
                 <f:selectItem id="titem2" itemLabel="DownLoad" itemValue="DownLoad" />
                 <f:selectItem id="titem3" itemLabel="Archive" itemValue="Archive" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['sortBy']}</ui:define>
                <h:selectOneMenu id="oby" value="${'#'}{${listName}.sortKey}">
                 <f:selectItem id="oitem1" itemLabel="record id " itemValue="sid" />
                  <f:selectItem id="oitem2" itemLabel="KeyField" itemValue="customer" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
       </h:panelGrid>
       <h:panelGrid columns="2">
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['sortOrder']}</ui:define>
                <h:selectOneMenu id="so" value="${'#'}{${listName}.sortOrder}">
                 <f:selectItem id="soitem1" itemLabel="Ascending" itemValue="Asc" />
                 <f:selectItem id="soitem2" itemLabel="Descending" itemValue="Desc" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['font']}</ui:define>
                <h:selectOneMenu id="fo" value="${'#'}{${listName}.fontName}">
                 <ui:remove>
                 <f:selectItem id="foitem1" itemLabel="DejaVu Sans" itemValue="DejaVu Sans" />
                 </ui:remove>
                 <f:selectItem id="foitem2" itemLabel="DejaVu Serif" itemValue="DejaVu Serif" />
                 <ui:remove>
                 <f:selectItem id="foitem3" itemLabel="DejaVu Sans Mono" itemValue="DejaVu Sans Mono" />
                 </ui:remove>
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
       </h:panelGrid>
          <h:outputText style="font-weight:bold;color:blue;" value="${'#'}{messages['Wide']} ${'#'}{messages['report']}: ${'#'}{messages['Display']} ${'#'}{messages['as']} ${'#'}{messages['EXCEL']} ${'#'}{messages['to']} ${'#'}{messages['view']}/${'#'}{messages['print']} ${'#'}{messages['all']} ${'#'}{messages['columns']}"/>
         </p:panel >
        <div class="actionButtons">
         <h:panelGrid columns="15">      
            <h:commandButton id="report" value="${'#'}{messages['Generate']} ${'#'}{messages['Report']}" styleClass="buttonMain" onclick="this.form.target='_blank'"  action="${'#'}{${listName}.print}"
             rendered="${'#'}{not empty ${listName}.resultList}"/>             
            <#if (menuAttributesFunction?contains("1a") || menuAttributesFunction?contains("18") || menuAttributesFunction?contains("1b")  
              || menuAttributesFunction?contains("20")  || menuAttributesFunction?contains("30")  || menuAttributesFunction?contains("40")
             )>
             <h:commandButton id="chartview" value="Show Pie Chart"  action="/${pageName}PieChart.xhtml?faces-redirect=true">
              <f:param name="key" value="${'#'}{fpxxfq1a5xwwqqhxxxxxitemHome.instance.a0xxukixbxxxxxxxxxxxmatcode}"/>
             </h:commandButton>
             <h:commandButton id="chartviewb" value="Show Line Chart"  action="/${pageName}BarChart.xhtml?faces-redirect=true">
              <f:param name="key" value="${'#'}{fpxxfq1a5xwwqqhxxxxxitemHome.instance.a0xxukixbxxxxxxxxxxxmatcode}"/>
             </h:commandButton>
            </#if>

            <h:button outcome="/${'#'}{empty ${componentName}From ? '${menuPageName}' : ${componentName}From}.xhtml"
                    id="done"
                 value="Done"/>
            <f:param name="reportName" value="${'#'}{${listName}.${reportName}}"/>
            <f:param name="displayAs" value="${'#'}{${listName}.${displayAs}}" /> 
        <ui:decorate template="layout/display.xhtml">
         <ui:define name="label"> ${'#'}{messages['status']}  </ui:define>
         <h:panelGrid columns="2" >
          <h:selectOneMenu value="${'#'}{${listName}.searchStatus}"> 
          <f:selectItem itemLabel="all" itemValue="${'#'}{null}"/>
          <f:selectItem itemLabel="open" itemValue="0"/>
          <f:selectItem itemLabel="active/ordered" itemValue="1"/>
          <f:selectItem itemLabel="return" itemValue="4"/>
          <f:selectItem itemLabel="closed" itemValue="8"/>
          <#if menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25") || menuAttributesFunction?contains("26")>
           <f:selectItem itemLabel="paid" itemValue="16"/>
           <f:selectItem itemLabel="partial/shipped" itemValue="32"/>
           <f:selectItem itemLabel="invoiced" itemValue="64"/>
          <#elseif menuAttributesFunction?contains("20") || menuAttributesFunction?contains("30") || menuAttributesFunction?contains("40")>
           <f:selectItem itemLabel="unsubscribed" itemValue="64"/>
          </#if>
          <#if menuAttributesFunction?contains("1a") >
           <ui:remove> could not get jaspersoft conditional working with $Pstatus_t
           <f:selectItem itemLabel="Qty &lt; &gt; Zero" itemValue="NZ"/>
           </ui:remove>
          </#if>
          <#if menuAttributesFunction?contains("1f") >
           <ui:remove>
           <f:selectItem itemLabel="Before Count Qty &lt; &gt; Stock Count" itemValue="NS"/>
           </ui:remove>
          </#if>

          <ui:remove>
          <f:selectItem itemLabel="marked" itemValue="128"/>
          <f:selectItem itemLabel="deleted" itemValue="256"/>
          </ui:remove>
          <f:selectItem itemLabel="printed/final approved" itemValue="512"/>
         </h:selectOneMenu>
        </h:panelGrid>
       </ui:decorate>

            ${'#'}{messages['Start']}&nbsp;<h:graphicImage value="/img/report_start16.png" />
            <h:panelGrid columns="2">
                 <h:selectOneMenu  value="${'#'}{${listName}.start}" 
                  rendered="${'#'}{!fn:containsIgnoreCase(request.getHeader('User-Agent'), 'Jayfox')}">
                  <f:selectItem itemValue="${'#'}{null}" itemLabel="" />
                  <#if (menuAttributesFunction?contains("1a"))>
                   <f:selectItems value="${'#'}{${listName}.get${entityName?substring(10)}KeyList()}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#elseif (menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25")  
              || menuAttributesFunction?contains("26")  || menuAttributesFunction?contains("27")  || menuAttributesFunction?contains("33")
              || menuAttributesFunction?contains("34")  || menuAttributesFunction?contains("35")  || menuAttributesFunction?contains("36")
              || menuAttributesFunction?contains("37")  || menuAttributesFunction?contains("38")  || menuAttributesFunction?contains("44")  
              || menuAttributesFunction?contains("9c"))>
                   <f:selectItems value="${'#'}{${listName}.suggest('*')}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#else>
                   <f:selectItems value="${'#'}{${listName}.suggest(${homeName}.prefix)}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  </#if>  
                 </h:selectOneMenu>
            </h:panelGrid>
            ${'#'}{messages['End']}&nbsp;<h:graphicImage value="/img/report_stop16.png" />
            <h:panelGrid columns="2">
                 <h:selectOneMenu  value="${'#'}{${listName}.end}" 
                  rendered="${'#'}{!fn:containsIgnoreCase(request.getHeader('User-Agent'), 'Jayfox')}">
                  <f:selectItem itemValue="${'#'}{null}" itemLabel="" />
                  <#if (menuAttributesFunction?contains("1a"))>
                   <f:selectItems value="${'#'}{${listName}.get${entityName?substring(10)}KeyList()}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#elseif (menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25")  
              || menuAttributesFunction?contains("26")  || menuAttributesFunction?contains("27")  || menuAttributesFunction?contains("33")
              || menuAttributesFunction?contains("34")  || menuAttributesFunction?contains("35")  || menuAttributesFunction?contains("36")
              || menuAttributesFunction?contains("37")  || menuAttributesFunction?contains("38")  || menuAttributesFunction?contains("44")  
              || menuAttributesFunction?contains("9c"))>
                   <f:selectItems value="${'#'}{${listName}.suggest('*')}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#else>
                   <ui:remove>prefix default is blank and via suggest gets key values >= blank, start holds first key value    
                     , end holds last key value , item above gets whole entity via keylist (not suggest) so that all
                      values including below blank like numeric values can be shown in drop down
                   </ui:remove>
                   <f:selectItems value="${'#'}{${listName}.suggest(${homeName}.prefix)}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  </#if>  
                 </h:selectOneMenu>
            </h:panelGrid>
            &nbsp;<h:outputText style="color:red;" value=" ${'#'}{messages['will']} ${'#'}{messages['take']} ${'#'}{messages['some']} ${'#'}{messages['time']} ${'#'}{messages['to']} ${'#'}{messages['load']} ${'#'}{${listName}.resultCount} ${'#'}{messages['records']}, ${'#'}{messages['use']} ${'#'}{messages['range']} ${'#'}{messages['to']} ${'#'}{messages['reduce']} ${'#'}{messages['time']}  " rendered="${'#'}{${listName}.resultCount gt 500}"/>     
         </h:panelGrid>      
        </div>

 <p:panel  toggleable="true" toggleableHeader="true" header="${'#'}{messages['${entityName?substring(eL)?cap_first}']}- ${'#'}{messages['List']}" switchType="ajax" collapsed="true"
     leftCollapsedIcon="/img/List16.png" leftExpandedIcon="/img/control_remove16.png">

    <f:facet name="header">${entityName?substring(eL)?cap_first} List</f:facet>
    <div class="results" id="${componentName}List" style="overflow-x:auto">

    <h:outputText value="No ${componentName?substring(eL)?cap_first} exists" 
               rendered="${'#'}{empty ${listName}.resultList}"/>
    <p:dataTable id="${listName}"  frozenColumns="2" scrollable="true" scrollWidth="100%"  rows="6" scrollRows="6"
                var="${componentName}"
              value="${'#'}{${listName}.resultList}"
           rendered="${'#'}{not empty ${listName}.resultList}">
           <#assign loop =0 >
           <#if c2j.isComponent(pojo.identifierProperty)>
            <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
             <#if loop = 0>
              <#assign selectParam = '_'+componentName+'.' + pojo.identifierProperty.name>
              <#assign loop =1 >
             </#if>
            </#foreach> 
           <#else>
            <#assign selectParam = '_'+componentName +'.'+pojo.identifierProperty.name>
           </#if>

        <p:column>
                            <f:facet id="MarkerFacet" name="header">
                                <h:outputText id="markit" value="Flag" />
                            </f:facet>
                            <h:selectBooleanCheckbox id="MarkItCheckbox" value="${'#'}{${homeName}.checked[${componentName}.a0xxuobxbxxxxxxxxxxxsid]}"/>
            <h:link outcome="/${'#'}{empty from ? '${pageName}' : from}.xhtml"
                   value="${'#'}{empty from ? 'View' : 'Select'}"
             propagation="${'#'}{empty from ? 'none' : 'default'}"
                      id="${componentName}ViewId">
             <#if pojo.isComponent(pojo.identifierProperty)>
              <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
                <f:param name="${componentName}${componentProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}.${componentProperty.name}}"/>
              </#foreach>
             <#else>
                <f:param name="${componentName}${pojo.identifierProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}}"/>
             </#if>
            </h:link>
            <#if statusFlagField != "">
             <h:graphicImage 
                  value="/img/accept16.png"  rendered="${'#'}{${componentName}.${statusFlagField} gt 127 ?'true': 'false'}">
             </h:graphicImage> 
            </#if>

        </p:column>

<#-- @outputValue is a macro inside typeInfo.ftl in r3gen/util dir -->
<#foreach property in pojo.allPropertiesIterator>
<#if (property.name?length > eL)>
 <#if !c2h.isCollection(property) && !c2h.isManyToOne(property)>
  <#if pojo.isComponent(property)>
   <#foreach componentProperty in property.value.propertyIterator>
        <p:column>
            <f:facet name="header">
            <#assign propertyPath = property.name + '.' + componentProperty.name>
                <ui:include src="layout/sort.xhtml">
                    <ui:param name="entityList" value="${'#'}{${listName}}"/>
                    <ui:param name="propertyLabel" value=${'#'}{messages['${componentProperty.name?substring(pL)?cap_first}']}"/>
                    <ui:param name="propertyPath" value="${'#'}${componentName}.${propertyPath}"/>
                </ui:include>
            </f:facet>
            <@outputValue property=componentProperty expression="${'#'}{${componentName}.${property.name}.${componentProperty.name}}" indent=pL/>

        </p:column>
   </#foreach>
 <#else>
       <#if ( ((property.name?substring(pfS,pfE)!="za") && (property.name?substring(pfS,pfE)!="zb") && (property.name?substring(pfS,pfE)!="zd") && (property.name?substring(pfS,pfE)!="zf") && (property.name?substring(pfS,pfE)!="zt")) && ((property.name?substring(0,1) == "y") || (property.name?substring(0,1) == "z" )
           || (property.name?substring(0,6) == "a0xxuo" ) ) )   > 
           <#-- ${property.name}-->
       <#else>
        <p:column>
            <f:facet name="header">
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(pL)} ${'#'}{${listName}.order=='${property.name} asc' ? messages.down : ( ${listName}.order=='${property.name} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${property.name} asc' ? '${property.name} desc' : '${property.name} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${property.name}}
        </p:column>
       </#if>
 </#if>
</#if>
<#if c2h.isManyToOne(property)>
<#assign parentPojo = c2j.getPOJOClass(cfg.getClassMapping(property.value.referencedEntityName))>
<#if parentPojo.isComponent(parentPojo.identifierProperty)>
<#foreach componentProperty in parentPojo.identifierProperty.value.propertyIterator>
        <p:column>
            <f:facet name="header">
<#assign propertyPath = property.name + '.' + parentPojo.identifierProperty.name + '.' + componentProperty.name>
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(eL)} ${componentProperty.name?substring(pL)} ${'#'}{${listName}.order=='${propertyPath} asc' ? messages.down : ( ${listName}.order=='${propertyPath} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${propertyPath} asc' ? '${propertyPath} desc' : '${propertyPath} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${propertyPath}}
        </p:column>
</#foreach>
<#else>
        <p:column>
            <f:facet name="header">
<#assign propertyPath = property.name + '.' + parentPojo.identifierProperty.name>
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(eL)} ${parentPojo.identifierProperty.name?substring(pL)} ${'#'}{${listName}.order=='${propertyPath} asc' ? messages.down : ( ${listName}.order=='${propertyPath} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${propertyPath} asc' ? '${propertyPath} desc' : '${propertyPath} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${propertyPath}}
        </p:column>
</#if>
</#if>
</#if>
</#foreach>
        <p:column styleClass="action">
            <f:facet name="header">Action</f:facet>
            ${'#'}{' '}
            <h:link outcome="/${editPageName}.xhtml"
                   value="Edit"
             propagation="none"
                      id="${componentName}Edit"
                rendered="${'#'}{empty from and (customIdentity.hasRole('UH')||customIdentity.hasRole('UQ')||customIdentity.hasRole('VH')||customIdentity.hasRole('VQ'))}">
             <#if pojo.isComponent(pojo.identifierProperty)>
              <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
                <f:param name="${componentName}${componentProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}.${componentProperty.name}}"/>
              </#foreach>
             <#else>
                <f:param name="${componentName}${pojo.identifierProperty.name?cap_first}"
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}}"/>
             </#if>
            </h:link>
            ${'#'}{' '}
           <#if documentField != "" >
            <h:commandButton id="Download" value="Download" rendered="${'#'}{empty from}" action="${'#'}{${homeName}.downloadThis(${selectParam})}"/>
           </#if>
        </p:column>
</p:dataTable>

    </div>
    </p:panel>
    
    <div class="tableControl">
      
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.previousExists}" 
               value="${'#'}{messages.left}${'#'}{messages.left} First Page"
                  id="firstPage">
          <f:param name="firstResult" value="0"/>
        </h:link>
        
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.previousExists}" 
               value="${'#'}{messages.left} Previous Page"
                  id="previousPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.previousFirstResult}"/>
        </h:link>
        
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.nextExists}" 
               value="Next Page ${'#'}{messages.right}"
                  id="nextPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.nextFirstResult}"/>
        </h:link>
        
        <h:link outcome="/${listPageName}.xhtml" 
            rendered="${'#'}{${listName}.nextExists}" 
               value="Last Page ${'#'}{messages.right}${'#'}{messages.right}"
                  id="lastPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.lastFirstResult}"/>
        </h:link>
        
    </div>
<ui:remove>
 in jsf 2 use f:metadata and f:viewparam in target page to put value for f:param name
 This replaces seam page.xml for view page
</ui:remove>    
    <h:panelGroup layout="block" styleClass="actionButtons" rendered="${'#'}{empty from}">
        <h:button outcome="/${editPageName}.xhtml"
                    id="create" 
                 value="Create ${componentName?substring(eL)}">
<#assign idName = componentName + util.upper(pojo.identifierProperty.name)>
<#if c2j.isComponent(pojo.identifierProperty)>
<#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
<#assign cidName = componentName + util.upper(componentProperty.name)>

            <f:param name="${cidName}" value="1" />
</#foreach>
<#else>
            <f:param name="${idName}" value="1" />
</#if>
        </h:button>

            &nbsp;&nbsp;

             <h:commandButton id="ePrint" value="${'#'}{messages['Print']}/${'#'}{messages['Preview']} ${'#'}{messages['report']}"   onclick="this.form.target='_blank'"
              action="${'#'}{${listName}.ePrint('IGNORE',${listName}.start,${listName}.end,false,fn:substring(${listName}.reportName,2,fn:length(${listName}.reportName)))}" rendered="true"/>

             <h:commandButton id="emailS" value="${'#'}{messages['email']} ${'#'}{messages['to']}" onclick="this.form.target='_self'"
              action="${'#'}{${listName}.eSend('EMAIL'.concat(${listName}.displayAs),${listName}.start,${listName}.start,false,${homeName}.EMailingAddress)}" rendered="true">
                 <p:tooltip  attached="true" for="emailS" >
                 <h:outputText value="${'#'}{messages.For} ${'#'}{messages.email} ${'#'}{messages.only} ${'#'}{messages.one} ${'#'}{messages.report}, ${'#'}{messages.the} ${'#'}{messages.one} ${'#'}{messages.selected} ${'#'}{messages.as} ${'#'}{messages.start}, ${'#'}{messages.will} ${'#'}{messages.be} ${'#'}{messages.sent} " />
                 </p:tooltip>
             </h:commandButton>

             <ui:decorate id="ejay"  rendered="true" template="layout/display.xhtml">
               <ui:define name="label">${'#'}{messages['emailTo']} 
               </ui:define>
               <h:inputText  id="eMailA"
                          size="35"
                     maxlength="50"
                         value="${'#'}{${homeName}.EMailingAddress}">
               </h:inputText>
             </ui:decorate>
    </h:panelGroup>
          <h:panelGrid columns="1" >
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['Greeting']} ${'#'}{messages['text']}- ${'#'}{messages['Transaction']} ${'#'}{messages['Receipt']} ${'#'}{messages['from']} ${'#'}{customIdentity.owner2}
                </ui:define>
                <pe:ckEditor id="editor" secure="false" height="100" width="600"  value="${'#'}{${listName}.mailingSource}"
                      toolbar="[['NewPage','Preview','Cut','Copy','Image','Table','HorizontalRule'','PageBreak','Iframe','Link','Unlink','Anchor','Paste','PasteText','PasteFromWord','Find','Replace','-','SelectAll','-', 'Scayt'], '/', ['Undo', 'Redo']]">  
                </pe:ckEditor>

            </ui:decorate>
          </h:panelGrid >

     <p:hotkey  onkeydown="PF('report').click()" preventDefault="true" enabledInInput="true" key="return">
     </p:hotkey>

    </h:form>
    
</ui:define>

</ui:composition>
</#if>

