<#assign tobegeneratedCandidate = "N">  
<#include "../view/assigns/PositionLength.properties" >
<#if (pojo.shortName?length > eL)>
<#assign menuAttributes2 = pojo.shortName?substring(0,9)?upper_case>
<#assign menuAttributesFunction = pojo.shortName?substring(efS,efE)>
<#if (menuAttributes2?substring(efS,efE) == '36' )  >
 <#assign tobegeneratedCandidate ="Y" >
</#if>
<#if tobegeneratedCandidate == "Y">  
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
                             "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<#assign entityName = pojo.shortName>
<#assign componentName = util.lower(entityName)>
<#assign listName = componentName + "List">
<#assign pageName = entityName>
<#assign editPageName = entityName + "Edit">
<#assign listPageName = entityName + "List">
<#assign menuPageName = "home">
<#assign reportName = "reportName">
<#assign displayAs = "displayAs">
<#assign start = "start">
<#assign end = "end">
<#assign markedOnes = "markedOnes">    
<#assign targetId = "targetId">   
<#assign useDateKey="">
<#assign useDateKeyField="">

<#foreach property in pojo.allPropertiesIterator>
 <#if !c2h.isCollection(property) && !c2h.isManyToOne(property)>
  <#if c2j.isComponent(property)>
   <#foreach componentProperty in property.value.propertyIterator>
     <#if componentProperty.name?substring(pfS,pfE)=="ss">
      <#assign useDateKey="Y">
      <#assign useDateKeyField=componentProperty.name>
     </#if>
   </#foreach>
  <#else>
    <#if property.name?substring(pfS,pfE)=="ee">
      <#assign useDateKey="Y">
    </#if>
  </#if>
 </#if>
</#foreach>

 

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="layout/rtemplate.xhtml">
<#-- Generated By vendorcheques.xhtml.ftl on ${.now} -->
<f:metadata>
    <f:viewAction action="${'#'}{${componentName}Home.restrict()}" />
    <f:viewAction action="${'#'}{txxxuq366xwwqqhxxxxxvenarthaList.setDisplayAs('PDF')}" />
</f:metadata>
                       
<ui:define name="body">
    <h:form id="${componentName}Report" styleClass="edit">
     <h:outputStylesheet>

     </h:outputStylesheet>
	<p:toolbar height="26" itemSeparator="grid">
	  <p:toolbarGroup>
              <h:commandButton id="printb" value="Print"  action="${'#'}{${listName}.print}" image="/img/Print16.gif" />
	  </p:toolbarGroup>
	  <p:toolbarGroup>
              <h:button id="tdoneh" image="./img/home_24.png"  alt="Home" value="Home" propagation="end" outcome="/home.xhtml" />
	  </p:toolbarGroup>
	  <p:toolbarGroup location="right">
              <h:outputText value="${'#'}{customIdentity.username}"/> 
              <h:outputText value="${'#'}{authenticator.currcaldates}"/> 
 		   <h:graphicImage value="/img/Search16.gif" styleClass="pic"/>
	  </p:toolbarGroup>
	  <p:toolbarGroup location="right">
             <h:commandButton id="About" value="Help" alt="Help" action="${'#'}{${listName}.print}" image="/img/About16.gif" >
             <p:tooltip > <span style="white-space: nowrap"> <h:outputText value="Put Help Info here"/></span> </p:tooltip> 
             </h:commandButton>
	  </p:toolbarGroup>
       <h:messages globalOnly="true" styleClass="message" id="globalMessages"/>
	</p:toolbar>
         <p:panel toggleable="true" toggleableHeader="true" label="${'#'}{messages['Venartha']} Reports using default parameters          (Use the Browser back button after viewing or have multiple browser windows open)  " switchType="ajax" opened="true">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.reportName']}</ui:define>
                <h:selectOneMenu id="${reportName}" value="${'#'}{${listName}.${reportName}}">
                 <f:selectItem id="ritem1" itemLabel="Cheques" itemValue="fiVendorcheques" />
                </h:selectOneMenu> 

            </ui:decorate>

        </p:panel>
         <p:panel toggleable="true" toggleableHeader="true" style="width: 25%;" header="Report Generation parameters" switchType="client" collapsed="true"
          leftCollapsedIcon="/img/control_add16.png" leftExpandedIcon="/img/control_remove16.png">
       <h:panelGrid columns="2">
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.displayAs']}</ui:define>
                <h:selectOneMenu id="displayAs" value="${'#'}{${listName}.displayAs}">
                 <f:selectItem id="ditem1" itemLabel="PDF" itemValue="PDF" />
                 <f:selectItem id="ditem2" itemLabel="HTML" itemValue="HTML" />
                 <f:selectItem id="ditem3" itemLabel="CSV" itemValue="CSV" />
                 <f:selectItem id="ditem4" itemLabel="EXCEL" itemValue="EXCEL" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.markedOnes']}</ui:define>
                <h:inputText id="markedOnes" value="${'#'}{${listName}.markedOnes}"/>
            </ui:decorate>
        </h:panelGrid>
       </h:panelGrid>
       <h:panelGrid columns="2">

        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['report.targetId']}</ui:define>
                <h:selectOneMenu id="targetId" value="${'#'}{${listName}.targetId}">
                 <f:selectItem id="titem1" itemLabel="None" itemValue="None" />
                 <f:selectItem id="titem2" itemLabel="DownLoad" itemValue="DownLoad" />
                 <f:selectItem id="titem3" itemLabel="Archive" itemValue="Archive" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['sortBy']}</ui:define>
                <h:selectOneMenu id="oby" value="${'#'}{${listName}.sortKey}">
                 <f:selectItem id="oitem1" itemLabel="record id " itemValue="sid" />
                  <f:selectItem id="oitem2" itemLabel="KeyField" itemValue="customer" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
       </h:panelGrid>
       <h:panelGrid columns="2">
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['sortOrder']}</ui:define>
                <h:selectOneMenu id="so" value="${'#'}{${listName}.sortOrder}">
                 <f:selectItem id="soitem1" itemLabel="Ascending" itemValue="Asc" />
                 <f:selectItem id="soitem2" itemLabel="Descending" itemValue="Desc" />
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
        <h:panelGrid columns="2">
            <ui:decorate template="layout/display.xhtml">
                <ui:define name="label">${'#'}{messages['font']}</ui:define>
                <h:selectOneMenu id="fo" value="${'#'}{${listName}.fontName}">
                 <ui:remove>
                 <f:selectItem id="foitem1" itemLabel="DejaVu Sans" itemValue="DejaVu Sans" />
                 </ui:remove>
                 <f:selectItem id="foitem2" itemLabel="DejaVu Serif" itemValue="DejaVu Serif" />
                 <ui:remove>
                 <f:selectItem id="foitem3" itemLabel="DejaVu Sans Mono" itemValue="DejaVu Sans Mono" />
                 </ui:remove>
                </h:selectOneMenu> 
            </ui:decorate>
        </h:panelGrid>
       </h:panelGrid>
         </p:panel>

        <div class="actionButtons">
         <h:panelGrid columns="15">      
            <h:commandButton id="report" value="${'#'}{messages['Generate']} ${'#'}{messages['only']} " styleClass="buttonMain"  onclick="this.form.target='_blank'" action="${'#'}{${listName}.print}"/>

            <h:commandButton id="reportpr" value="${'#'}{messages['Generate']} ${'#'}{messages['and']} ${'#'}{messages['mark']} ${'#'}{messages['as']} ${'#'}{messages['Printed']}" styleClass="buttonMain"  onclick="this.form.target='_blank'" action="${'#'}{${listName}.markPrinted}"/>

            <h:button outcome="/${'#'}{empty ${componentName?substring(eL)}From ? '${menuPageName}' : ${componentName}From}.xhtml"
                    id="done"
                 value="Done"/>

            <h:graphicImage value="/img/report_start16.png" />
            <h:panelGrid columns="2">
                 <h:selectOneMenu  value="${'#'}{${listName}.start}" 
                  rendered="${'#'}{!fn:containsIgnoreCase(request.getHeader('User-Agent'), 'Jayfox')}">
                  <f:selectItem itemValue="${'#'}{null}" itemLabel="" />
                  <#if (menuAttributesFunction?contains("1a"))>
                   <f:selectItems value="${'#'}{${listName}.get${entityName?substring(10)}KeyList()}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#elseif (menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25")  
              || menuAttributesFunction?contains("26")  || menuAttributesFunction?contains("27")  || menuAttributesFunction?contains("33")
              || menuAttributesFunction?contains("34")  || menuAttributesFunction?contains("35")  || menuAttributesFunction?contains("36")
              || menuAttributesFunction?contains("37")  || menuAttributesFunction?contains("38")  || menuAttributesFunction?contains("44")  
              || menuAttributesFunction?contains("9c"))>
                   <f:selectItems value="${'#'}{${listName}.suggest('*')}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#else>
                   <f:selectItems value="${'#'}{${listName}.suggest(${homeName}.prefix)}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  </#if>  
                 </h:selectOneMenu>
            </h:panelGrid>
            <h:graphicImage value="/img/report_stop16.png" />
            <h:panelGrid columns="2">
                 <h:selectOneMenu  value="${'#'}{${listName}.end}" 
                  rendered="${'#'}{!fn:containsIgnoreCase(request.getHeader('User-Agent'), 'Jayfox')}">
                  <f:selectItem itemValue="${'#'}{null}" itemLabel="" />
                  <#if (menuAttributesFunction?contains("1a"))>
                   <f:selectItems value="${'#'}{${listName}.get${entityName?substring(10)}KeyList()}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#elseif (menuAttributesFunction?contains("23") || menuAttributesFunction?contains("24") || menuAttributesFunction?contains("25")  
              || menuAttributesFunction?contains("26")  || menuAttributesFunction?contains("27")  || menuAttributesFunction?contains("33")
              || menuAttributesFunction?contains("34")  || menuAttributesFunction?contains("35")  || menuAttributesFunction?contains("36")
              || menuAttributesFunction?contains("37")  || menuAttributesFunction?contains("38")  || menuAttributesFunction?contains("44")  
              || menuAttributesFunction?contains("9c"))>
                   <f:selectItems value="${'#'}{${listName}.suggest('*')}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  <#else>
                   <ui:remove>prefix default is blank and via suggest gets key values >= blank, start holds first key value    
                     , end holds last key value , item above gets whole entity via keylist (not suggest) so that all
                      values including below blank like numeric values can be shown in drop down
                   </ui:remove>
                   <f:selectItems value="${'#'}{${listName}.suggest(${homeName}.prefix)}" var="result"
                    itemValue="${'#'}{result}" itemLabel="${'#'}{result}" />
                  </#if>  
                 </h:selectOneMenu>
            </h:panelGrid>
            &nbsp;<h:outputText style="color:red;" value=" ${'#'}{messages['will']} ${'#'}{messages['take']} ${'#'}{messages['some']} ${'#'}{messages['time']} ${'#'}{messages['to']} ${'#'}{messages['load']} ${'#'}{${listName}.resultCount} ${'#'}{messages['records']}, ${'#'}{messages['use']} ${'#'}{messages['range']} ${'#'}{messages['to']} ${'#'}{messages['reduce']} ${'#'}{messages['time']}  " rendered="${'#'}{${listName}.resultCount gt 500}"/>     
         </h:panelGrid>      
        </div>
        
    
    <p:panel>
            <f:facet name="header">${entityName?substring(eL)?cap_first} search results</f:facet>

        <f:facet name="header">${entityName?substring(eL)?cap_first} search results</f:facet>
    <div class="results" id="${componentName}List">

    <h:outputText value="No ${componentName?substring(eL)?cap_first} exists" 
               rendered="${'#'}{empty ${listName}.resultList}"/>
               
    <p:dataTable id="${listName}" 
                var="${componentName}"
              value="${'#'}{${listName}.resultList}" 
           rendered="${'#'}{not empty ${listName}.resultList}">
           <#assign loop =0 >
           <#if c2j.isComponent(pojo.identifierProperty)>
            <#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
             <#if loop = 0>
              <#assign selectParam = componentName+'.'+ pojo.identifierProperty.name+'.'+componentProperty.name>
              <#assign loop =1 >
             </#if>
             <#if useDateKeyField != "">
              <#assign selectParam = componentName+'.'+ pojo.identifierProperty.name+'.'+useDateKeyField>
             </#if>
            </#foreach> 
           <#else>
            <#assign selectParam = componentName +'.'+pojo.identifierProperty.name>
           </#if>

        <h:column>
          <f:facet name="header">Select</f:facet>
          <h:commandButton id="SelectStart" value="Start"  action="${'#'}{${listName}.setStart(${selectParam})}"/>
        </h:column>

        <h:column>
          <f:facet name="header">Select</f:facet>
          <h:commandButton id="SelectEnd" value="End"  action="${'#'}{${listName}.setEnd(${selectParam})}"/>
        </h:column>

<#foreach property in pojo.allPropertiesIterator>
<#if !c2h.isCollection(property) && !c2h.isManyToOne(property)>
<#if pojo.isComponent(property)>
<#foreach componentProperty in property.value.propertyIterator>
        <h:column>
            <f:facet name="header">${'#'}{messages['${componentProperty.name?substring(pL)?cap_first}']}</f:facet>
            ${'#'}{${componentName}.${property.name}.${componentProperty.name}}
        </h:column>
</#foreach>
<#else>
        <h:column>
            <f:facet name="header">
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(pL)} ${'#'}{${listName}.order=='${property.name} asc' ? messages.down : ( ${listName}.order=='${property.name} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${property.name} asc' ? '${property.name} desc' : '${property.name} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${property.name}}
        </h:column>
</#if>
</#if>
<#if c2h.isManyToOne(property)>
<#assign parentPojo = c2j.getPOJOClass(cfg.getClassMapping(property.value.referencedEntityName))>
<#if parentPojo.isComponent(parentPojo.identifierProperty)>
<#foreach componentProperty in parentPojo.identifierProperty.value.propertyIterator>
        <h:column>
            <f:facet name="header">
<#assign propertyPath = property.name + '.' + parentPojo.identifierProperty.name + '.' + componentProperty.name>
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(eL)} ${componentProperty.name?substring(pL)} ${'#'}{${listName}.order=='${propertyPath} asc' ? messages.down : ( ${listName}.order=='${propertyPath} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${propertyPath} asc' ? '${propertyPath} desc' : '${propertyPath} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${propertyPath}}
        </h:column>
</#foreach>
<#else>
        <h:column>
            <f:facet name="header">
<#assign propertyPath = property.name + '.' + parentPojo.identifierProperty.name>
                <h:link styleClass="columnHeader"
                             value="${property.name?substring(eL)} ${parentPojo.identifierProperty.name?substring(pL)} ${'#'}{${listName}.order=='${propertyPath} asc' ? messages.down : ( ${listName}.order=='${propertyPath} desc' ? messages.up : '' )}">
                    <f:param name="order" value="${'#'}{${listName}.order=='${propertyPath} asc' ? '${propertyPath} desc' : '${propertyPath} asc'}"/>
                </h:link>
            </f:facet>
            ${'#'}{${componentName}.${propertyPath}}
        </h:column>
</#if>
</#if>
</#foreach>
        <h:column>
            <f:facet name="header">action</f:facet>
            <h:link outcome="/${'#'}{empty from ? '${pageName?substring(eL)}' : from}.xhtml" 
                   value="Select" 
                      id="${componentName}">
<#if pojo.isComponent(pojo.identifierProperty)>
<#foreach componentProperty in pojo.identifierProperty.value.propertyIterator>
                <f:param name="${componentName}${util.upper(componentProperty.name)}" 
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}.${componentProperty.name}}"/>
</#foreach>
<#else>
                <f:param name="${componentName}${util.upper(pojo.identifierProperty.name)}" 
                        value="${'#'}{${componentName}.${pojo.identifierProperty.name}}"/>
</#if>
            </h:link>
        </h:column>
    </p:dataTable>

    </div>
    </p:panel>
    
    <div class="tableControl">
      
        <h:link outcome="/${listPageName?substring(eL)}.xhtml" 
            rendered="${'#'}{${listName}.previousExists}" 
               value="${'#'}{messages.left}${'#'}{messages.left} First Page"
                  id="firstPage">
          <f:param name="firstResult" value="0"/>
        </h:link>
        
        <h:link outcome="/${listPageName?substring(eL)}.xhtml" 
            rendered="${'#'}{${listName}.previousExists}" 
               value="${'#'}{messages.left} Previous Page"
                  id="previousPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.previousFirstResult}"/>
        </h:link>
        
        <h:link outcome="/${listPageName?substring(eL)}.xhtml" 
            rendered="${'#'}{${listName}.nextExists}" 
               value="Next Page ${'#'}{messages.right}"
                  id="nextPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.nextFirstResult}"/>
        </h:link>
        
        <h:link outcome="/${listPageName?substring(eL)}.xhtml" 
            rendered="${'#'}{${listName}.nextExists}" 
               value="Last Page ${'#'}{messages.right}${'#'}{messages.right}"
                  id="lastPage">
            <f:param name="firstResult" 
                    value="${'#'}{${listName}.lastFirstResult}"/>
        </h:link>
        
    </div>
    
    </h:form>
    
</ui:define>

</ui:composition>
</#if>
</#if>

